### ISSUE TITLE
lake_chelan

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#100]
# AVA: Lake Chelan (lake_chelan)

name | value
--- | ---
ava_id | lake_chelan
cfr_index | 9.215
revision | [T.D. TTB-76, 74 FR 19415, Apr. 29, 2009]
state | WA
county | Chelan
within | Columbia Valley
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Manson Quadrangle, Washington—Chelan Co., 1968, photorevised 1987; 
2. Cooper Ridge Quadrangle—Washington, 1968, photorevised 1987; 
3. Chelan Quadrangle—Washington, 1968, photorevised 1987; 
4. Chelan Falls Quadrangle—Washington, 1968, photorevised 1981; and 
5. Winesap Quadrangle—Washington, 1968, photorevised 1987.

## Boundary [src]

(1) The beginning point is on the Manson map at the intersection of the east shore of Lake Chelan and the north boundary line of section 15, T28N/R21E, north of Greens Landing. From the beginning point, proceed straight east 1.6 miles along the northern boundary line of sections 15 and 4 to its intersection with the 2,000-foot elevation line, T28N/R21E; then 
(2) Follow the meandering 2,000-foot elevation line generally southeast onto the Cooper Ridge map, crossing Purtterman Gulch; continue southeast onto the Chelan map and follow the meandering 2,000-foot elevation line onto the Chelan Falls map, over the Cagle Gulch, and then return to the Chelan map; continue generally southeast onto the Chelan Falls map and follow the 2,000-foot elevation line to section 8, T27N/R23E, to a point 0.3 mile due north of BM 1404 at the intersection of U.S. Route 97 and State Route 151, T27N/R23E; then 
(3) Proceed in a straight south-southeast line 1.35 miles to its intersection with the section 20 north boundary line and the 1,000-foot elevation line, T27N/R23E; then 
(4) Proceed south-southwest along the 1,000-foot contour line to its intersection with the section 20 south boundary line, south of Chelan Station and immediately west of State Route 151, T27N/R23E; then 
(5) Proceed straight west along the south boundary line of sections 20 and 19 for 0.75 mile to its intersection with the light-duty Gorge Road, as identified on the adjoining Chelan map, T27N/R23E; then 
(6) Proceed northwest along Gorge Road, crossing onto the Chelan map, to the southeast corner of section 13, T27N/R22E; then 
(7) Proceed straight west along the south boundary line of sections 13, 14, 15, 16, 17, and 18, and crossing onto the Winesap map in section 18, to its intersection with the R21E/R22E line, T27N; then 
(8) Proceed straight north along the R21E/R22E line to its intersection with the south boundary line of section 13 and the 2,440-foot contour line, T27N/R21E; then 
(9) Proceed straight west to the southwest corner of section 13, T27N/R21E; then 
(10) Proceed straight north along the section 14 east boundary line to the northeast corner of section 14, T27N/R21E; then 
(11) Proceed straight west along the section 14 north boundary line to the northwest corner of section 14, T27N/R21E; then 
(12) Proceed straight north along the east boundary line of section 10 for 0.3 mile to its intersection with the 2,520-foot contour line and a 90-degree turn in the Wenatchee National Forest 
(WNF) boundary line, T27N/R21E; then 
(13) Proceed straight west along the WNF boundary line 0.3 mile to its intersection with the 2,600-foot contour line and a 90-degree turn in the WNF boundary line, T27N/R21E; then 
(14) Proceed straight south along the WNF boundary line 0.3 mile to its intersection with the south boundary line of section 10, T27N/R21E; then 
(15) Proceed straight west along the south boundary lines of sections 10 and 9 to the southeast corner of section 8, T27N/R21E; then 
(16) Proceed straight north along the east boundary line of section 8 to the northeast corner of section 8, T27N/R21E; then 
(17) Proceed straight west along the north boundary line of section 8 to the northwest corner of section 8, T27N/R21E; then 
(18) Proceed generally north along the east boundary line of section 6, crossing onto the Manson map, and continue along the east boundary lines of sections 31 and 30, to the northeast corner of section 30, T28N/R21E; then 
(19) Proceed straight east along the north boundary lines of sections 29 and 28 to the intersection with the east shoreline of Lake Chelan; and 
(20) Proceed generally northwest and northeast along the east shoreline of Lake Chelan to the point of beginning.

**Comment by gdmf** [comment]
Please add the "In Progress" label to this one.
