### ISSUE TITLE
lake_erie

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#101]
# AVA: Lake Erie (lake_erie)

name | value
--- | ---
ava_id | lake_erie
cfr_index | 9.83
revision | [T.D. ATF-156, 48 FR 48819, Oct. 21, 1983]
state | NY|OH|PA
county | 
within | 
contains | Grand River Valley (OH)\|Isle St. George (OH)

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Toledo,” scale 1:250,000 
1956, revised 1978.; 
2. “Cleveland,” scale 1:250,000 
1956, revised 1972.; 
3. “Erie,” scale 1:250,000 
1959, revised 1972.; and 
4. “Buffalo,” scale 1:250,000 
1962..

## Boundary [src]

(1) From the beginning point the boundary proceeds up Buffalo Creek to the confluence of Cazenovia Creek. 
(2) The boundary proceeds up Cazenovia Creek and thence up the west branch of Cazenovia Creek to a point approximately one mile north of Colden, New York, exactly 12 statute miles inland from any point on the shore of Lake Erie. 
(3) The boundary proceeds southwestward and along a line exactly 12 statute miles inland from any point on the shore of Lake Erie to a point approximately one mile north of Dayton, New York, where it intersects the 1,300-foot contour line. 
(4) The boundary proceeds generally southwestward along the 1,300-foot contour line to a point almost two miles north-northwest of Godard, Pennsylvania, exactly six statute miles inland from any point on the shore of Lake Erie. 
(5) The boundary proceeds southwestward along a line exactly six statute miles inland from any point on the shore of Lake Erie to the point where it intersects Ohio Route 45 near the intersection with Interstate 90. 
(6) The boundary proceeds southward along Ohio Route 45 to a point exactly 14 statute miles inland from any point on the shore of Lake Erie approximately one mile north of Rock Creek, Ohio. 
(7) The boundary proceeds southwestward, then westward, then northwestward along a line 14 statute miles inland from any point on the shore of Lake Erie to the point where it intersects the Ohio-Michigan boundary just north of Centennial, Ohio. 
(8) The boundary then follows the Ohio-Michigan border in an easterly direction to the shoreline of Lake Erie. Thence in a generally southeasterly direction along the shoreline of Lake Erie to the mouth of the Portage River just north of Port Clinton. Thence due north in a straight line to the United States-Canada border. Thence in a southeasterly and then an easterly direction along the United States-Canada border until a point is reached which is due north of the easternmost point of Kelleys Island. 
(9) The boundary then proceeds due south until it reaches the shoreline of Lake Erie. Thence the boundary follows the lakeshore in a generally northeasterly direction to the beginning point at the mouth of Buffalo Creek.

**Comment by ericallanwest** [comment]
Please label this one In Progress and Virginia Tech. Thanks!

**Comment by MicheleTobias** [comment]
Making a note to think more about how to better address step 3.  What we have will work for now, but I think there are other methods to consider.

**Comment by ericallanwest** [comment]
I believe this issue can be closed as a result of PR #502.

**Comment by MicheleTobias** [comment]
I'd like to leave it open while I think about step 3.

**Comment by ericallanwest** [comment]
I have read the boundary descriptions for each of the 246 established AVAs. This is the only AVA boundary that requires a buffer, as far as I can tell. There are no features on the referenced maps that correspond to the boundary description. So a GIS buffer is the best alternative.

**Comment by MicheleTobias** [comment]
I agree.  My plan was to digitize the coastline in the approved map and then buffer it

**Comment by ericallanwest** [comment]
By law, each boundary description proceeds in a clockwise direction. In theory, you could start anywhere in the description, proceed in a clockwise direction around the boundary, and would still end up where you started. That was the license I took in creating this boundary.

As far as tracing the coastline, the USGS published a product in the 1990s called Digital Line Graphs (DLGs). DLGs are raster-to-vector representations derived directly from scanned paper maps. DLGs are historically accurate and represent the exact features referenced by AVA petitioners. They are not modern equivalents such as [TIGER/Line Shapefiles](https://www.census.gov/cgi-bin/geo/shapefiles/index.php) or the [National Hydrography Dataset](https://www.usgs.gov/core-science-systems/ngp/national-hydrography/national-hydrography-dataset). DLGs can be used to re-create coastlines and other features such as roads, railroads, streams/rivers, township/range/section lines, elevation contours, and power lines that are often referenced in AVA descriptions. 

DLGs were released in a format called SDTS that was not widely embraced. I discovered a tool that converts SDTS vector files to shapefiles (see [A Data Converter for SDTS DLG Vector GIS files and DEM files](https://spatialreserves.wordpress.com/2018/04/02/spatial-data-converter-for-dlg-files/)), and the results are fantastic. I believe these DLGs will be very important for verifying the accuracy of previously digitized AVA boundaries.

I am attaching [lake_erie_shoreline.zip](https://github.com/UCDavisLibrary/ava/files/4313053/lake_erie_shoreline.zip) which contains two GeoJSON files. _lake_erie_shoreline_full.geojson_ contains the relevant DLG hydrography data and _lake_erie_shoreline_clean.geojson_ contains my interpretation of the shoreline based on that data. I re-created the shoreline, which is hundreds of miles long, in just a few hours with basic GIS tools. It would take a few days (or weeks?) to digitally trace the entire shoreline, and the results would likely be less accurate than what the USGS has already made available.

**Comment by MicheleTobias** [comment]
I don't think we need to digitize the entire coastline, just the section that is needed for this AVA.  Our process requires that we use only the maps or data listed in the official description whenever possible.  It's not about making things easy, but following the methods we set out at the beginning.  I'm happy to finish this one up or have one of my students work on it.

**Comment by sdelong** [comment]
It doesn't sound like making it easy, but making it more accurate. Using the underlining data instead of someone digitizing the paper map sounds right to me.  Are you that confident in the USGS's online map digitizations? And the guaranteed human error in tracing the shoreline?  The Lake Erie shoreline of 1969 no longer exists.

**Comment by MicheleTobias** [comment]
It's not that I'm not confident in the other datasets, it's that when we started the project we decided to follow the official descriptions as closely as possible.  If the description references the map, that's what we use.  So far, I've only seen one boundary that mentions an additional dataset and it was the Napa parcels.  That wasn't cited fully so we don't know what dataset they used and had to guess.  The other USGS datasets may more closely reflect reality, but these descriptions aren't necessarily a reflection of reality - they are a description based on a set of maps.  Again, I'm happy to work with this one to make sure it follows the methods we set out for the project.  I can't justify bringing in additional datasets when we have access to the official maps.

**Comment by ericallanwest** [comment]
Not only is the DLG method is easier, it is also more accurate.

Here is a [sample document](https://github.com/UCDavisLibrary/ava/files/4330429/hp01catd.pdf) that explains the process of creating DLGs from paper maps. The DLGs are as close to a primary source as you can get, and they meet National Map Accuracy Standards, as explained in this document. The digitizing work has already been done for us; we just have to select the edges that correspond to the boundary descriptions.

I am not trying to undermine the project's approach. But once the final AVAs are digitized, I hope that the editing/revision process incorporates the DLGs and/or other modern vector datasets such as the TIGER shapefiles. It would greatly enhance the prestige of the project.

**Comment by MicheleTobias** [comment]
Eric, please understand that a committee of people from both the fields of geospatial tech, wine, and law set up these methods in 2017 for a very specific purpose.  We want to carefully control the methods so we can tell researchers precisely what we are offering them.  The TTB is using methods similar to what you propose.  There is no reason to reproduce what they are doing.  Your definition of accuracy is different than the one employed by this project.  Yes, the old maps might be different from what we think of today as "correct" but the AVA descriptions don't use the current day understanding.  I'm firm in my decision that we should not other data sources unless it is absolutely necessary.  In the checking process, any boundaries deviating from the approved maps will be corrected.

**Comment by ericallanwest** [comment]
The DLGs are not another data source; they literally are the old paper maps. They were created with great care by the USGS and do accurately reflect the intent of the original petition.

**Comment by davidkli** [comment]
I have reviewed this AVA. The boundary looks good, just had to fix some formatting in the attribute table.
