### ISSUE TITLE
lake_wisconsin

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#103]
# AVA: Lake Wisconsin (lake_wisconsin)

name | value
--- | ---
ava_id | lake_wisconsin
cfr_index | 9.146
revision | [T.D. ATF-352, 59 FR 539, Jan. 5, 1994]
state | WI
county | Columbia|Dane
within | Upper Mississippi\|River Valley
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Sauk City, Wis., 1975; and 
2. Lodi, Wis., 1975.

## Boundary [src]

(1) The point of beginning is on the “Lodi, Wisc.” U.S.G.S. map in the northeast quarter-section of section 17, Lodi Township, Columbia County, where Spring Creek enters Lake Wisconsin; 
(2) From the point of beginning, follow the southern shoreline of Lake Wisconsin northwest to where Lake Wisconsin narrows and becomes the Wisconsin River on the map, in the vicinity of the town of Merrimac, Sauk County; 
(3) Then continue along the southern shoreline of the Wisconsin River, west and south past Goose Egg Hill, Columbia County, on the “Sauk City, Wisc.” quadrangle map, and then west to a southwest bend in the shoreline opposite Wiegands Bay, Sauk County, where the Wisconsin River becomes Lake Wisconsin again on the map; 
(4) Then southwest and south along the eastern shoreline of Lake Wisconsin, to the powerplant that defines where Lake Wisconsin ends and the Wisconsin River begins again; 
(5) Then continuing south along the Wisconsin River shoreline to where it intersects with U.S. Highway 12 opposite Sauk City, Sauk County; 
(6) Then in a southeasterly direction on U.S. Highway 12 to the intersection at State Highway 188, just over one-half a mile; 
(7) Then in a northeasterly direction about 1,000 feet on State Highway 188, to the intersection of Mack Road; 
(8) Then east on Mack Road to the intersection of State Highway Y, about 3 miles; 
(9) Then follow State Highway Y in a generally northeasterly direction onto the “Lodi, Wisc.” quadrangle map and continue in a northeasterly direction to the intersection with State Highway 60; 
(10) Then in a northeasterly direction on State Highway 60 to the intersection with State Highway 113 in the town of Lodi; 
(11) Then in a northwesterly direction on State Highway 113 to where it crosses Spring Creek the second time just before Chrislaw Road; 
(12) Then follow Spring Creek in a northwesterly direction to where it enters Lake Wisconsin, the point of beginning.

**Comment by amgard** [comment]
I am working on this boundary.

**Comment by MicheleTobias** [comment]
Sounds good! Let me or Sierra or Alex know if you have questions!

**Comment by alisonsnwong** [comment]
Reviewed this AVA. I updated the used_maps section by adding the revision edition of the map used. I also did minor boundary edits.
