### ISSUE TITLE
lamorinda

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#104]
# AVA: Lamorinda (lamorinda)

name | value
--- | ---
ava_id | lamorinda
cfr_index | 9.254
revision | [T.D. TTB-133, 81 FR 9108, Feb. 24, 2016]
state | CA
county | Contra Costa
within | Central Coast\|San Francisco Bay
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Walnut Creek, CA, 1995; 
2. Las Trampas Ridge, CA, 1995; 
3. Oakland East, CA, 1997; and 
4. Briones Valley, CA, 1995.

## Boundary [src]

(1) The beginning point is on Walnut Creek map at the water tank 
(known locally as the Withers Reservoir) at the end of an unnamed light-duty road known locally as Kim Road, in the Cañada del Hambre y Las Bolsas Land Grant. 
(2) From the beginning point, proceed south-southeast in a straight line approximately 0.8 mile to the 833-foot peak marked “Hump 2;” then 
(3) Proceed southeast in a straight line approximately 1.7 miles to the marked 781-foot peak south of the shared Lafayette-Walnut Creek corporate boundary line and north of an unnamed light-duty road known locally as Peaceful Lane; then 
(4) Proceed southeast in a straight line approximately 0.3 mile to the marked 610-foot peak southwest of an unnamed light-duty road known locally as Secluded Place; then 
(5) Proceed south-southwest in a straight line approximately 1.7 miles to an unidentified benchmark at the end of an unnamed unimproved road known locally as Diablo Oaks Way in section 33, T1N/R2W; then 
(6) Proceed southeast in a straight line approximately 0.5 mile, crossing onto the Las Trampas map, and continuing another 0.9 mile to the substation at the southeast corner of section 4, T1S/R2W; then 
(7) Proceed southeast in a straight line approximately 2.3 miles to the 1,827-foot summit of Las Trampas Peak, section 22, T1S/R2W; then 
(8) Proceed south-southeast in a straight line approximately 2.1 miles to the 2,024-foot benchmark marked “Rock 2” in section 26, T1S/R2W; then 
(9) Proceed west-southwest in a straight line approximately 2.7 miles to the marked 1,057-foot peak in section 29, T1S/R2W; then 
(10) Proceed west-southwest in a straight line approximately 2 miles to the intersection of the 1,000-foot elevation line with the Contra Costa-Alameda County line in section 31, T1S/R2W; then 
(11) Proceed northwest in a straight line approximately 0.4 mile, crossing onto the Oakland East map, then continuing another 0.1 mile to the 1,121-foot peak in section 30, T1S/R2W; then 
(12) Proceed northwest in a straight line approximately 3.6 miles to the 1,301-foot peak in section 15, T1S/R3W; then 
(13) Proceed northwest in a straight line approximately 1.6 miles to the 1,634-foot peak in section 9, T1S/R3W; then 
(14) Proceed northwest in a straight line approximately 2.2 miles to the communication tower on the Contra Costa-Alameda County line in section 5, T1S/R3W; then 
(15) Proceed north in a straight line approximately 0.1 mile, crossing onto the Briones Valley map, then continuing another 0.6 mile to the 1,905-foot summit of Vollmer Peak in the El Sobrante Land Grant; then 
(16) Proceed north-northeast in a straight line approximately 3 miles, crossing over to the 1,027-foot peak in the Boca de la Cañada del Pinole Land Grant, to the Orinda corporate boundary line; then 
(17) Proceed generally east along the Orinda corporate boundary line approximately 3.3 miles to the water tank at the 1,142-foot elevation in the Boca de la Cañada del Pinole Land Grant; then 
(18) Proceed east-northeast in a straight line approximately 1.2 miles to the 1,357-foot benchmark marked “Russell” in the Boca de la Cañada del Pinole Land Grant; then 
(19) Proceed northwest in a straight line approximately 0.8 mile to the 1,405-foot peak in the Boca de la Cañada del Pinole Land Grant; then 
(20) Proceed east-northeast in a straight line approximately 0.5 mile, crossing onto the Walnut Creek map, then continuing another 1.1 miles to the beginning point.

**Comment by fyfangyao** [comment]
I am working on this

**Comment by fyfangyao** [comment]
(1) Walnut Creek, CA, 1995 (photorevised 1999) 
(2) Las Trampas Ridge, CA, 1995 (photorevised 1997) 
(3) Oakland East, CA, 1997 (photoinspected 1997) 
(4) Briones Valley, CA, 1995 (photorevised 1999)

**Comment by MicheleTobias** [comment]
@ariellerose I've got this one.  It's going to be pretty quick I hope.

**Comment by SoominHur** [comment]
Reviewed
- Add cfr author name in the attribute table.
- Add scale information of used maps in the attribute table.
