### ISSUE TITLE
lancaster_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#105]
# AVA: Lancaster Valley (lancaster_valley)

name | value
--- | ---
ava_id | lancaster_valley
cfr_index | 9.41
revision | [T.D. ATF-102, 47 FR 20301, May 12, 1982]
state | PA
county | Chester|Lancaster
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Lancaster County, Pennsylvania”, scaled 1:50,000, edition of 1977; and 
2. “Honey Brook Quadrangle”, 7.5 minute series, edition of 1955, photorevised 1969 and 1974.

## Boundary [src]

(1) Then in a southeasterly direction following the Lancaster County boundary for approximately 0.9 mile to the 500 foot contour line immediately south of the Conestoga River. 
(2) Then following the 500 foot contour in a southwesterly direction to the Caernarvon-East Earl Township boundary. 
(3) Then south approximately 0.1 mile following the Caernarvon-East Earl Township boundary to U.S. Highway 322. 
(4) Then west following U.S. Highway 322 for approximately 1.7 miles to the electric transmission line between Fetterville and Cedar Grove School. 
(5) Then southwest in a straight line for approximately 5.2 miles to the intersection of Earl, Upper Leacock, and Leacock Townships at the Mill Creek. 
(6) Then southeast following the boundary between Earl Township and Leacock Township to the point where Earl, East Earl, Salisbury, and Leacock Townships intersect. 
(7) Then east in a straight line for approximately 4.8 miles to the point where the 500 foot contour line intersects Pequea Creek northwest of Mt. Pleasant School. 
(8) Then following the 500 foot contour line past Cole Hill through the town of Gap and along Mine Ridge to the 76°07  west longitude line in Paradise Township. 
(9) Then southwest in a straight line for approximately 7.7 miles to the Boehm Church south of Willow Street. 
(10) The northwest in a straight line for approximately 1.2 miles to the township school in West Willow. 
(11) Then west in a straight line for 4.2 miles to the confluence of Stehman Run and the Conestoga River. 
(12) Then northwest in a straight line for approximately 0.5 mile to the confluence of Indian Run and Little Conestoga Creek. 
(13) Then west following Indian Run for approximately 3.6 miles to the source of the more northerly branch. 
(14) Then northwest in a straight line for approximately 0.25 mile to the source of Wisslers Run. 
(15) Then west following Wisslers Run downstream for approximately 0.7 mile to the 300 foot contour line. 
(16) Then north following the 300 foot contour line to its intersection with Pennsylvania Highway 999 in Washington Boro. 
(17) Then east following Pennsylvania Highway 999 to the school in Central Manor. 
(18) Then northeast in a straight line for approximately 2.7 miles to the point where the West Branch of the Little Conestoga Creek intersects with Pennsylvania Highway 462. 
(19) Then west following Pennsylvania Highway 462 for approximately 1.5 miles to Strickler Run. 
(20) Then following Strickler Run southwest to the Columbia municipal boundary. 
(21) Then north following the eastern boundary of Columbia to Shawnee Run. 
(22) Then northeast in a straight line for approximately 5.8 miles to the intersection of Pennsylvania Highway 23 and Running Pump Road [unnamed on map] at elevation check point 436 near Centerville. 
(23) Then east following Pennsylvania Highway 23 for approximately 0.5 mile to the 400 foot contour line. 
(24) Then following the 400 foot contour line north around Chestnut Ridge, past Millers Run and continuing until the 400 foot contour line intersects an unnamed stream. 
(25) Then due south in a straight line for approximately 0.8 mile to Pennsylvania Highway 23. 
(26) Then west following Pennsylvania Highway 23 to the intersection with Pennsylvania Highway 441 at Marietta. 
(27) Then west following Pennsylvania Highway 441 to Pennsylvania Highway 241 near Bainbridge. 
(28) Then northwest in a straight line for approximately 5.5 miles to the point where the Consolidated Railroad Corporation crosses the West Donegal-Mount Joy Township boundary in Rheems. 
(29) Then east in a straight line for approximately 3.3 miles to the Mt. Pleasant Church. 
(30) Then east in a straight line for approximately 3.8 miles to the Erismans Church. 
(31) Then east in a straight line for approximately 3.3 miles to the point where the 400 foot contour line crosses Pennsylvania Highway 72 south of Valley View. 
(32) Then following the 400 foot contour line east to Pennsylvania Highway 501. 
(33) Then east in a straight line for approximately 2.9 miles to the Union Meetinghouse. 
(34) Then southeast in a straight line for approximately 1.0 miles to the point where Pennsylvania Highway 272 
(indicated as U.S. Highway 222 on the map) crosses Cocalico Creek 
(which forms the boundary between West Earl and Warwick Townships). 
(35) Then northwest following the West Earl Township boundary to its intersection with U.S. Highway 322 southeast of Ephrata. 
(36) Then east in a straight line for approximately 3.4 miles to the Lincoln Independence School. 
(37) Then southeast in a straight line for approximately 1.7 miles to the West Terre Hill School. 
(38) Then east in a straight line for approximately 8.5 miles to the beginning point.

**Comment by davidkli** [comment]
Reviewing this AVA currently.
The Lancaster County, Pennsylvania, scaled 1:50,000 map could not be found on Topoview.
Used maps updated to:
(1) "Honey Brook Quadrangle", 7.5 minute series, edition of 1955, photorevised 1969 and 1974; and (2) "New Holland Quadrangle", 7.5 minute series, edition of 1956, photorevised 1969 and 1975; and (3) "Morgantown Quadrangle", 7.5 minute series, edition of 1956, photorevised 1969 and 1975; and (4) "Terre Hill Quadrangle", 7.5 minute series, edition of 1956, photorevised 1969 and 1976; and 
(5) "Ephrata Quadrangle", 7.5 minute series, edition of 1956, photorevised 1969 and 1974; and 
(6) "Lititz Quadrangle", 7.5 minute series, edition of 1956, photorevised 1969 and 1975; and 
(7) "Leola Quadrangle", 7.5 minute series, edition of 1956, photorevised 1969 and 1975; and 
(8) "Manheim Quadrangle", 7.5 minute series, edition of 1955, photorevised 1969 and 1975; and 
(9) "Elizabethtown Quadrangle", 7.5 minute series, edition of 1964, photorevised 1972; and 
(10) "Columbia West Quadrangle", 7.5 minute series, edition of 1964, photorevised 1972; and 
(11) "York Haven Quadrangle", 7.5 minute series, edition of 1964, photorevised 1972; and 
(12) "Columbia East Quadrangle", 7.5 minute series, edition of 1956, photorevised 1969 and 1970; and 
(13) "Lancaster Quadrangle", 7.5 minute series, edition of 1956, photorevised 1969 and 1976; and 
(14) "Safe Harbor Quadrangle", 7.5 minute series, edition of 1955, photorevised 1969 and 1976; and 
(15) "Conestoga Quadrangle", 7.5 minute series, edition of 1955, photorevised 1969 and 1976; and 
(16) "Quarryville Quadrangle", 7.5 minute series, edition of 1955, photorevised 1969 and 1976; and 
(17) "Gap Quadrangle", 7.5 minute series, edition of 1955, photorevised 1969 and 1976.
