### ISSUE TITLE
leelanau_peninsula

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#106]
# AVA: Leelanau Peninsula (leelanau_peninsula)

name | value
--- | ---
ava_id | leelanau_peninsula
cfr_index | 9.40
revision | [T.D. ATF-99, 47 FR 13329, Mar. 30, 1982]
state | MI
county | Leelanau
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Empire Quadrangle, Michigan,” 15 minute series; 
2. “Maple City Quadrangle, Michigan,” 15 minute series; 
3. “Traverse City Quadrangle, Michigan,” 15 minute series; and 
4. “Northport Quadrangle, Michigan,” 15 minute series.

(c) Boundaries. The Leelanau Peninsula viticultural area encompasses all of Leelanau County, Michigan, excluding the offshore islands.

**Comment by davidkli** [comment]
In progress
