### ISSUE TITLE
lehigh_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#107]
# AVA: Lehigh Valley (lehigh_valley)

name | value
--- | ---
ava_id | lehigh_valley
cfr_index | 9.210
revision | [TTB-66, 73 FR 12874, Mar. 11, 2008]
state | PA
county | Berks|Carbon|Lehigh|Monroe|Northampton|Schuylkill
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Berks County, Pennsylvania, 1978; 
2. Schuylkill County 
West Half., Pennsylvania, 1979; 
3. Schuylkill County 
East Half., Pennsylvania, 1979; 
4. Carbon County, Pennsylvania, 1991; 
5. Monroe County, Pennsylvania, 1980; 
6. Northampton County, Pennsylvania, 1981; and 
7. Lehigh County, Pennsylvania, 1987.

## Boundary [src]

(1) The beginning point is on the Berks County map at the intersection of the Berks-Lancaster County line and the single-track Conrail rail line located near Cacoosing Creek in South Heidelberg Township; 
(2) From the beginning point, proceed northwest along the Berks County line and, crossing onto the Schuylkill County 
(West Half) map, continue northwest along the Schuylkill-Lebanon County line to the county line&#39;s intersection with the northern boundary of Pine Grove township; then 
(3) Proceed northeast along the northern boundary of Pine Grove, Washington, and Wayne Townships and, crossing onto the Schuylkill County 
(East Half) map, continue along the northern boundary of Wayne Township to the northeast corner of that township, then 
(4) Proceed east-northeasterly in a straight line to the confluence of Beaver Creek and Cold Run at the northeast corner of State Game Lands No. 222 in Walker township; then 
(5) Proceed north-northeasterly in a straight line to the 1,402-foot elevation point on Wildcat Mountain in Walker township; then 
(6) Proceed easterly in a straight line, crossing onto the Carbon County map, and continue to Bench Mark 
(BM) 1032 located on Highway 902, south of the village of Bloomingdale; then 
(7) Proceed east-northeasterly in a straight line to BM 555 located immediately east of the Lehigh River in the city of Jim Thorpe; then 
(8) Proceed east-northeasterly in a straight line to the northern most point of Lehighton Reservoir; then 
(9) Proceed east-northeasterly in a straight line to the western end of the dam at the Penn Forest Reservoir; then 
(10) Proceed easterly in a straight line and, crossing onto the Monroe County map, continue to the 847-foot elevation point located at the intersection of Highway 534 and an unnamed road locally know as Dotters Corner Road in Polk township; then 
(11) Proceed east-northeasterly in a straight line to the intersection of Highway 115 and an unnamed secondary road locally known as Astolat Road immediately north of the village of Effort; then 
(12) Proceed east-northeasterly in a straight line to St. Johns Cemetery, located along Appenzell Creek northwest of the village of Neola; then 
(13) Proceed straight northeast to the intersection of Interstate 80 and an unnamed road locally known as Hamilton Turnpike at the town of Bartonsville; then 
(14) Proceed east-southeast along Interstate 80 through Stroudsburg to the west bank of the Delaware River; then 
(15) Proceed south 
(downstream) along the west bank of the Delaware River, and, crossing onto the Northampton County map, continue south along the west bank of the Delaware River to the mouth of Lehigh River at Easton; then 
(16) Proceed southwesterly 
(upstream) along the south bank of the Lehigh River, and crossing onto the Lehigh County map, continue along the south bank of the Lehigh River to the mouth of Jordan Creek in Allentown; then 
(17) Proceed westerly 
(upstream) along Jordan Creek to the first railroad bridge over the creek, and then, following the Conrail rail line on that bridge, proceed southerly along the Conrail rail line 
(paralleling Trout Creek at first) through Emmaus, Macungie, and Alburtis, and continue along the rail line to the Lehigh-Berks County line; then 
(18) Crossing onto the Berks County map, continue southerly along the Conrail rail line through Mertztown, Topton, Lyons, Fleetwood, Blandon, and Muhlenburg to the Conrail rail bridge across the Schuylkill River in Reading; then 
(19) Following the Conrail rail line on the Schuylkill River bridge, proceed southerly along the rail line through Wyomissing to the rail line&#39;s junction with a single-track Conrail rail line in Sinking Springs; then 
(20) From the Conrail rail line junction in Sinking Springs, follow the single track Conrail rail line through Montello, Fritztown, and Vinemont, and return to the beginning point.

**Comment by davidkli** [comment]
The approved maps were not found on Topoview. Instead maps from the 7.5 minute series were used.
The used maps field was updated to:
(1) Sinking Spring, Pennsylvania 1:24,000 (1955, revised 1968 and 1974);
(2) Womelsdorf, Pennsylvania 1:24,000 (1955, revised 1969 and 1977); 
(3) Bethel, Pennsylvania 1:24,000 (1955, revised 1969 and 1974); 
(4) Fredericksburg, Pennsylvania 1:24,000 (1955, revised 1978); 
(5) Swatara Hill, Pennsylvania 1:24,000 (1955, revised 1969 and 1976); 
(6) Pine Grove, Pennsylvania 1:24,000 (1954, revised 1969 and 1977); 
(7) Tower City, Pennsylvania 1:24,000 (1969, revised 1974); 
(8) Minersville, Pennsylvania 1:24,000 (1955, revised 1969 and 1976); 
(9) Pottsville, Pennsylvania 1:24,000 (1944, revised 1968 and 1976); 
(10) Orwigsburg, Pennsylvania 1:24,000 (1944, revised 1968 and 1976); 
(11) Tamaqua, Pennsylvania 1:24,000 (1944, revised 1969 and 1976); 
(12) Nesquehoning, Pennsylvania 1:24,000 (1948, revised 1969 and 1976); 
(13) Lehighton, Pennsylvania 1:24,000 (1992); 
(14) Christmans, Pennsylvania 1:24,000 (1960, revised 1970, inspected 1980); 
(15) Pohopco Mountain, Pennsylvania 1:24,000 (1960, revised 1983); 
(16) Broadheadsville, Pennsylvania 1:24,000 (1960, revised 1970); 
(17) Saylorsburg, Pennsylvania 1:24,000 (1960, revised 1983); 
(18) Mount Pocono, Pennsylvania 1:24,000 (1966, revised 1983); 
(19) Stroudsburg, Pennsylvania 1:24,000 (1953, revised 1968 and 1973); 
(20) Portland, Pennsylvania 1:24,000 (1955, revised 1984); 
(21) Belvidere, New Jersey 1:24,000 (1955, revised 1971); 
(22) Bangor, Pennsylvania 1:24,000 (1956, revised 1968 and 1973); 
(23) Easton, New Jersey 1:24,000 (1956, revised 1968 and 1973); 
(24) Nazareth, Pennsylvania 1:24,000 (1964, revised 1983);  
(25) Hellertown, Pennsylvania 1:24,000 (1965, revised 1992); 
(26) Allentown East, Pennsylvania 1:24,000 (1964, revised 1983); 
(27) Allentown West, Pennsylvania 1:24,000 (1964, revised 1984); 
(28) Topton, Pennsylvania 1:24,000 (1965, revised 1972); 
(29) Manatawny, Pennsylvania 1:24,000 (1957, revised 1969 and 1973); 
(30) Fleetwood, Pennsylvania 1:24,000 (1956, revised 1969 and 1974); 
(31) Temple, Pennsylvania 1:24,000 (1956, revised 1968 and 1978); 
(32) Reading, Pennsylvania 1:24,000 (1956, revised 1968 and 1974);
