### ISSUE TITLE
leona_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#108]
# AVA: Leona Valley (leona_valley)

name | value
--- | ---
ava_id | leona_valley
cfr_index | 9.212
revision | [T.D. TTB-71, 73 FR 64202, Oct. 29, 2008]
state | CA
county | Los Angeles
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Ritter Ridge, Calif., 1958; Photorevised 1974; 
2. Sleepy Valley, CA, 1995; 
3. Del Sur, CA, 1995; and 
4. Lake Hughes, CA, 1995.

## Boundary [src]

(1) From the beginning point on the Ritter Ridge map at the intersection of Elizabeth Lake Pine Canyon Road and the section 23 east boundary line, T6N, R13W, proceed straight south along the section 23 east boundary line approximately 0.1 mile to its intersection with the 3,000-foot elevation line, T6N, R13W; then 
(2) Proceed west along the 3,000-foot elevation line to its intersection with the section 23 west boundary line, T6N, R13W; then 
(3) Proceed south along the section 23 west boundary line to the southwest corner of section 23 at the 3,616-foot marked elevation point, T6N, R13W; then 
(4) Proceed west along the section 22 south boundary line, crossing onto the Sleepy Valley map, and continuing along the section 21 south boundary line, crossing over Pine Creek, to its intersection with the 3,400-foot elevation line, T6N, R13W; then 
(5) Proceed west along the 3,400-foot elevation line to its intersection with the section 19 south boundary line and Bouquet Canyon Road, T6N, R13W; then 
(6) Proceed straight west along the section 19 south boundary line to its intersection with the 3,560-foot elevation line, an unimproved road, and a power transmission line, north of Lincoln Crest, T6N, R13W; then 
(7) Proceed northeast along the 3,560-foot elevation line across section 19 to its east boundary line, T6N, R13W; then 
(8) Proceed in a straight line north-northwest approximately 0.25 mile to its intersection with a trail and the 3,800-foot elevation line, T6N, R13W; then 
(9) Proceed northwest along the meandering 3,800-foot elevation line through section 19 to its intersection with the section 13 southeast corner, T6N, R14W; then 
(10) Proceed straight west, followed by straight north, along the marked Angeles National Forest border to the section 11 southeast corner; then 
(11) Proceed straight north along the section 11 east boundary line to its intersection with the 3,400-foot elevation line south of an unimproved road, T6N, R14W; then 
(12) Proceed generally northwest along the 3,400-foot elevation line through section 11, crossing onto the Del Sur map, to its intersection with the section 3 southeast corner, T6N, R14W; then 
(13) Proceed straight west to the section 4 southeast corner, T6N, R14W; then 
(14) Proceed straight north along the section 4 east boundary line approximately 0.05 mile to its intersection with the 3,600-foot elevation line, T6N, R14W; then 
(15) Proceed northwest along the 3,600-foot elevation line, through section 4 and crossing onto the Lake Hughes map, to its intersection with the Angeles National Forest border and the section 4 western boundary line, T6N, R14W; then 
(16) Proceed straight north along the section 4 western boundary line to its intersection with BM 3402, south of Andrade Corner, T7N, R14W; then 
(17) Proceed in a line straight northeast, crossing onto the Del Sur map, to its intersection with the marked 3,552-foot elevation point, section 33, T7N, R14W; then 
(18) Proceed in a line straight east-southeast to its intersection with the marked 3,581-foot elevation point, and continue in a straight line east-southeast to its intersection with the marked 3,637-foot elevation point, T6N, R14W; then 
(19) Proceed in a line straight northeast to its intersection with the section 2 northwest corner, T6N, R14W; then 
(20) Proceed straight east along the section 2 north boundary line 0.35 mile to its intersection with the 3,600-foot elevation line, T6N, R14W; then 
(21) Proceed north and then generally southeast along the 3,600-foot elevation line that runs parallel to and south of the Portal Ridge to the elevation line&#39;s intersection with the section 7 east boundary line, T6N, R13W; then 
(22) Proceed straight south along the section 7 east boundary line, crossing onto the Sleepy Valley map, to its intersection with the 3,400-foot elevation line north of the terminus of 90th Street, T6N, R13W; then 
(23) Proceed generally east-southeast along the 3,400-foot elevation line that runs north of the San Andreas Rift Zone to its intersection with the section 16 east boundary line, T6N, R13W; then 
(24) Proceed straight south along the section 16 east boundary line to its intersection with the 3,000-foot elevation line, between Goode Hill Road and Elizabeth Lake Pine Canyon Road, T6N, R13W; then 
(25) Proceed generally southeast along the 3,000-foot elevation line, crossing onto the Ritter Ridge map, to its intersection with the section 23 east boundary line, north of the intermittent Amargosa Creek and Elizabeth Lake Pine Canyon Road, T6N, R13W; then 
(26) Proceed straight south along the section 23 east boundary line, returning to the beginning point.

**Comment by SoominHur** [comment]
Reviewed.
