### ISSUE TITLE
lime_kiln_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#110]
# AVA: Lime Kiln Valley (lime_kiln_valley)

name | value
--- | ---
ava_id | lime_kiln_valley
cfr_index | 9.27
revision | [T.D. ATF-106, 47 FR 24296, June 4, 1982, as amended by T.D. ATF-249, 52 FR 5956, Feb. 27, 1987]
state | CA
county | San Benito
within | Cienega Valley\|Central Coast\|San Benito
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Boundary [src]

(1) Thence in a straight line from the summit of the unnamed peak 
(1,288 feet) to a point where it intersects the 1,400-foot contour line, by the elevation marker, in the southwest quarter of T.14 S./R.6 E, Section 28; 
(2) Thence following the 1,400-foot contour line through the following sections; Sections 28, 29, and 30, T.14 S./R.6 E.; Section 25, T.14 S./R.5 E.; Sections 30, 19, 20, and returning to 19, T.14 S./R.6 E., to a point where the 1,400-foot contour line intersects with the section line between Sections 19 and 18, T.14 S./R.6 E.; 
(3) Thence in a straight line to the Cienega School Building along Cienega Road; 
(4) Thence along Cienega Road to the point of beginning.

**Comment by SoominHur** [comment]
Reviewed
- Corrected cf.author name
- Corrected Beginning point
