### ISSUE TITLE
linganore

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#111]
# AVA: Linganore (linganore)

name | value
--- | ---
ava_id | linganore
cfr_index | 9.63
revision | [T.D. ATF-140, 48 FR 37374, Aug. 18, 1983]
state | MD
county | Carroll|Frederick
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Walkersville Quadrangle, Maryland—Frederick Co.”, 7.5 minute series, 1953 
Photorevised 1979.; 
2. “Libertytown Quadrangle, Maryland”, 7.5 minute series, 1944 
Photorevised 1971.; 
3. “Damascus Quadrangle, Maryland”, 7.5 minute series, 1944 
Photorevised 1979.; 
4. “Winfield Quadrangle, Maryland”, 7.5 minute series, 1950 
Photorevised 1979.; and 
5. “Union Bridge Quadrangle, Maryland,” 7.5 minute series, 1953 
Photorevised 1971..

## Boundary [src]

(1) South-southeasterly 5,000 feet in a straight line to the point lying approximately 1,000 feet south of Interstate Highway 70 at the intersection of two unnamed light duty roads in the town of Bartonsville; 
(2) Then east-southeasterly 15,500 feet in a straight line to the point lying at the intersection of Mussetter Road and latitude line 39 degrees 22 minutes 30 seconds; 
(3) Then east-northeasterly 8,125 feet in a straight line to the point lying at the intersection of Mill Road and State Highway 144; 
(4) Then easterly along State Highway 144 on the Walkersville Quadrangle, Libertytown Quadrangle, and Damascus Quadrangle maps to the point of intersection with State Highway 27, approximately midway between the towns of Ridgeville and Parrsville, on the Damascus Quadrangle map; 
(5) Then northeasterly along State Highway 27 on the Damascus Quadrangle, Libertytown Quadrangle, and Winfield Quadrangle maps to the point of intersection with State Highway 26 in the town of Taylorsville on the Winfield Quadrangle map; 
(6) Then northerly 2,750 feet in a straight line to the point on a hill identified as having an elevation of 850 feet; 
(7) Then northwesterly 21,000 feet in a straight line to the point lying at the intersection of State Highway 31 and latitude line 39 degrees 30 minutes on the Libertytown Quadrangle and Union Bridge Quadrangle maps; 
(8) Then westerly 15,625 feet along latitude line 39 degrees 30 minutes to the point of intersection with Copper Mine Road; 
(9) Then northwesterly along Copper Mine Road on the Union Bridge Quadrangle map to the point of intersection with longitude line 77 degrees 15 minutes; 
(10) Then southerly 5,250 feet along longitude line 77 degrees 15 minutes to the point of intersection with latitude line 39 degrees 30 minutes on the Union Bridge Quadrangle and Walkersville Quadrangle maps; 
(11) Then southwesterly 46,750 feet in a straight line on the Walkersville Quadrangle map to the point of beginning.

**Comment by ericallanwest** [comment]
Please label this one In Progress. Thanks!

**Comment by davidkli** [comment]
I have checked this AVA and the boundary is correct. Only had to update the attribute table to follow the correct formatting.
