### ISSUE TITLE
livermore_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#112]
# AVA: Livermore Valley (livermore_valley)

name | value
--- | ---
ava_id | livermore_valley
cfr_index | 9.46
revision | [T.D. ATF-112, 47 FR 38520, Sept. 1, 1982, as amended by T.D. TTB-47, 71 FR 34531, June 15, 2006]
state | CA
county | Alameda|Contra Costa
within | Central Coast\|San Francisco Bay
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Clayton, CA 
1953; Photorevised 1980; Minor Revision 1994.; 
2. Diablo, Calif. 
1953; Photorevised 1980.; 
3. Tassajara, CA 
1996.; 
4. Byron Hot Springs, Calif., 
1953, Photorevised 1968.; 
5. Altamont, Calif., 
1953, Photorevised 1981.; 
6. Midway, Calif., 
1953, Photorevised 1980.; 
7. Cedar Mtn., CA, 
1956, Photorevised 1971, Minor Revision 1994.; 
8. Mendenhall Springs, CA 
1996.; 
9. La Costa Valley, CA 
1996.; 
10. Niles, Calif., 
1961, Photorevised 1980.; 
11. Dublin, Calif., 
1961, Photorevised 1980.; 
12. Hayward, CA 
1993.; and 
13. Las Trampas Ridge, CA 
1995..

## Boundary [src]

(1) The beginning point is on the Clayton map at the peak of Mount Diablo 
(VABM 3849) where the Mount Diablo Base Line and Mount Diablo Meridian Line intersect, T1S, R1E; 
(2) From the beginning point proceed southeast in a straight line for approximately 14 miles, crossing the Diablo and Tassajara maps, and pass onto the Byron Hot Springs map to the summit of Brushy Peak 
(elevation 1,702 feet), T1S, R2E; then 
(3) Continue due south in a straight line approximately 400 feet to the northern boundary of section 13, T2S, R2E; then 
(4) Proceed due east along the section 13 and section 18 northern boundary lines to the northeast corner of section 18, T2S, R3E; then 
(5) Continue southeast in a straight line approximately 1.8 miles to BM 720 in section 21, T2S, R3E, on the Altamont map; then 
(6) Continue south-southeast in a straight line approximately 1 mile to an unnamed, 1,147-foot peak in section 28, T2S, R3E; then 
(7) Continue south-southwest in a straight line approximately 1.1 miles to the intersection of the eastern boundary of section 32, T2S, R3E, with Interstate 580; then 
(8) Continue southeast in a straight line approximately 2.7 miles to BM 1602 in Patterson Pass in section 10, T3S, R3E; then 
(9) Continue south-southeast in a straight line approximately 2.8 miles to BM 1600, adjacent to Tesla Road in section 26, T3S, R3E, on the Midway map; then 
(10) Continue south in a straight line approximately 4.2 miles, passing onto the Cedar Mtn. map, to BM 1878, 40 feet north of Mines Road, in section 14, T4S, R3E; then 
(11) Proceed west-southwest in a straight line approximately 4.2 miles, passing onto the Mendenhall Springs map, to the southeast corner of section 19, T4S, R3E; then 
(12) Continue west along the southern boundaries of section 19, T4S, R3E, and section 24, T4S, R2E, to the southwest corner of section 24; then 
(13) Proceed north along the western boundary of section 24, T4S, R2E, to the southeast corner of section 14, T4S, R2E; then 
(14) Continue west along the southern boundary of section 14, T4S, R2E, to its southwest corner and then proceed north along the western boundary of section 14 to its intersection with the Hetch Hetchy Aqueduct, T4S, R2E; then 
(15) Follow the Hetch Hetchy Aqueduct west-southwest approximately 4.2 miles to the Aqueduct&#39;s intersection with the R1E/R2E range line on the La Costa Valley map, T4S; then 
(16) Continue southwest in a straight line approximately 3.9 miles, crossing Apperson, Welsh, and Alameda Creeks, to BM 533 in section 10, T5S, R1E; then 
(17) Proceed due west-northwest in a straight line approximately 1.9 miles, passing onto the Niles map, to the line&#39;s intersection with the eastern boundary of section 5 and the Fremont Boundary Line, T5S, R1E; then 
(18) Continue northwest in a straight line approximately 1.1 miles to an unnamed, 1,291-foot peak in section 32, T4S, R1E; then 
(19) Continue northwest in a straight line approximately 1.1 miles to an unnamed, 1,058-foot peak in section 30, T4S, R1E; then 
(20) Continue northwest in a straight line approximately 3.8 miles, passing through BM 161 in section 11, T4S, R1W, until the line intersects Palomares Road, a medium duty road, in section 11; then 
(21) Follow Palomares Road in a northerly direction for approximately 0.7 miles to the road&#39;s intersection with the power transmission line shown in section 11, T4S, R1W; then 
(22) Proceed northwest along the power transmission line for approximately 6.4 miles, passing through the Dublin map near Walpert Ridge, onto the Hayward map to the point where the power transmission line turns nearly west, approximately 500 feet south of an unnamed, 891-foot, peak, T3S, R2W; then 
(23) Continue north-northwest in a straight line approximately 1.4 miles to an unnamed, 840-foot peak, T3S, R2W; then 
(24) Proceed north-northeast in a straight line approximately 3.4 miles, returning to the Dublin map, to the point where the Contra Costa County-Alameda County line turns to the northwest, about 0.4 mile west of Wiedemann Hill 
(elevation 1,854 feet), section 20, T2S, R1W; then 
(25) Proceed in a northwesterly direction along the meandering Contra Costa County-Alameda County line for approximately 6.0 miles, passing briefly onto the Hayward, Las Trampas Ridge, and Diablo maps, before returning to the Las Trampas Ridge map and continuing to the point where the Contra Costa County-Alameda County line turns to the west-northwest, section 35, T1S, R2W; then 
(26) Continue north-northwest in a straight line approximately 2.7 miles to the summit of Las Trampas Peak 
(elevation 1,827 feet) in section 22, T1S, R2W; then 
(27) Proceed east-northeast in a straight line approximately 8.8 miles, passing through the Diablo map, and return to the beginning point.

**Comment by fyfangyao** [comment]
I am working on this.

**Comment by fyfangyao** [comment]
I use (1) Tassajara, Calif., 1996, photorevised 1999; (2) Byron Hot Springs, Calif., 1953, photorevised 1969; (3) Midway, Calif., 1953, photorevised 1981; (4) Mendenhall Springs, Calif., 1996, photorevised 1998; (4) Mendenhall Springs, Calif., 1996, photorevised 1998; (5) La Costa Valley, Calif., 1996, photorevised 1999; (6) Dublin, Calif., 1961, photorevised 1981. (7) Hayward, Calif., 1993, photorevised 1997; and (8) Las Trampas Ridge, Calif., 1995, photorevised 1999.

**Comment by MicheleTobias** [comment]
Don't forget to submit a pull request if this one is done.

**Comment by SoominHur** [comment]
Reviewed
- Add scale information of used maps in the attribute table
