### ISSUE TITLE
lodi

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#113]
# AVA: Lodi (lodi)

name | value
--- | ---
ava_id | lodi
cfr_index | 9.107
revision | [T.D. ATF-223, 51 FR 5324, Feb. 13, 1986, as amended by T.D. ATF-482, 67 FR 56484, Sept. 4, 2002]
state | CA
county | Sacramento|San Joaquin
within | 
contains | Alta Mesa\|Borden Ranch\|Clements Hills\|Cosumnes River\|Jahant\|Mokelumne River\|Sloughhouse

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Valley Springs SW, Calif. 1962;  
2. Farmington, Calif. 1968 
Photorevised 1987.;  
3. Peters, CA 1952 
Photorevised 1968.;  
4. Stockton East, Calif. 1968 
Photorevised 1987.;  
5. Waterloo, Calif. 1968 
Photoinspected 1978.;  
6. Lodi South, Calif. 1968 
Photorevised 1976.;  
7. Terminous, Calif. 1978 
Minor Revision 1993.;  
8. Thornton, Calif. 1978;  
9. Bruceville, Calif. 1968 
Photorevised 1980.;  
10. Florin, Calif. 1968 
Photorevised 1980.;  
11. Elk Grove, Calif. 1968 
Photorevised 1979.;  
12. Sloughhouse, Calif. 1968 
Photorevised 1980, Minor Revision 1993.;  
13. Buffalo Creek, Calif. 1967 
Photorevised 1980.;  
14. Folsom SE, Calif. 1954 
Photorevised 1980.;  
15. Carbondale, Calif. 1968 
Photorevised 1980, Minor Revision 1993.;  
16. Goose Creek, Calif. 1968 
Photorevised 1980, Minor Revision 1993.;  
17. Clements, Calif. 1968 
Minor Revision 1993.; and  
18. Wallace, Calif. 1962.

## Boundary [src]

(1) From the beginning point, proceed south along the San Joaquin-Stanislaus County line to its intersection with State Route 4, also known as Funck Road, T1N, R9E 
(Farmington, Calif. map);  
(2) Then proceed west on State Route 4 
(west on Funck Road, then south on Waverly Road, then west through the village of Farmington on Farmington Road) to State Route 4&#39;s intersection with Jack Tone Road, T1N, R7E 
(beginning on the Farmington, Calif. map, passing through the Peters, CA map, and ending on the Stockton East, Calif. map);  
(3) Then proceed north along Jack Tone Road to its intersection with Eightmile Road, T3N, R7E 
(ending on the Waterloo, Calif. map);  
(4) Then proceed west along Eightmile Road to its intersection with Bishop Cut, T3N, R5E 
(beginning on the Waterloo, Calif. map, passing through the Lodi South, Calif. map, and ending on the Terminous, Calif. map);  
(5) Then proceed north along Bishop Cut to White Slough, T3N, R5E 
(Terminous, Calif. map);  
(6) Then proceed west along White Slough to an unnamed drainage canal on Terminous Tract, across the slough from a marked pumping station on King Island, T3N, R5E 
(Terminous, Calif. map);  
(7) Then proceed straight northwest on the Terminous Tract to the south end of Peatland Road and follow it north to its intersection with State Route 12, T3N, R5E 
(Terminous, Calif. map);  
(8) Then proceed west 0.2 mile on State Route 12 to its intersection with an unnamed unimproved road at BM-8, and continue straight northwest on the Terminous Tract to the marked siphon on the south side of Sycamore Slough, T3N, R5E 
(ending on the Thornton, Calif. map);  
(9) Then proceed in a straight line north-to-northeast across Brack Tract, Hog Slough and Canal Ranch to the line&#39;s intersection with Beaver Slough near the 90-degree east turn of an unnamed light duty road, west of a small cluster of buildings, T4N, R5E 
(Thornton, Calif. map);  
(10) Then proceed west along Beaver Slough to its intersection with the South Mokelumne River, following the river north and east to its intersection with Interstate 5 
(marked as under construction), T5N, R5E 
(ending on the Bruceville, Calif. map);  
(11) Then proceed northwest along Interstate 5 to its intersection with an unnamed road, locally known as Hood-Franklin Road.  
(12) From Interstate 5, proceed east on Hood-Franklin Road to its intersection with Franklin Boulevard, Section 17, T6N, R5E 
(ending on the Florin, Calif. map);  
(13) Proceed generally north along Franklin Boulevard to its intersection with Sims Road and a section line running due east marking the northern boundary of Section 28, T7N, R5E 
(Florin, Calif. map).  
(14) Follow this section line due east to its junction with Sheldon Road and then proceed east along Sheldon Road to its intersection with the Central California Traction Co. Railroad 
(beginning on the Florin, Calif. map and ending on the Elk Grove, Calif. map);  
(15) Proceed southeast along the Central California Traction Co. Railroad to its intersection with Grant Line Road 
(Elk Grove, Calif. map);  
(16) Then northeast along Grant Line Road to its intersection with State Highway 16 
(beginning on the Elk Grove, Calif. map, passing through the Sloughhouse, Calif. map, and ending on the Buffalo Creek, Calif. map);  
(17) Proceed southeast along State Highway 16 to its intersection with Deer Creek 
(ending on the Sloughhouse, Calif. map);  
(18) Then proceed generally northeast along Deer Creek to its intersection with the eastern boundary of Sacramento County 
(beginning on the Sloughhouse, Calif. map, passing through the Buffalo Creek, Calif. map, and ending on the Folsom SE, Calif. map); and  
(19) Proceed generally south along the eastern boundary of Sacramento County to the meeting point of Sacramento, Amador, and San Joaquin Counties 
(beginning on the Folsom SE, Calif. map, passing through the Carbondale, Calif. map, and ending on the Goose Creek, Calif. map); and  
(20) Then proceed generally south-southeast along the eastern boundary of San Joaquin County to the point of beginning 
(beginning on the Goose Creek, Calif. map, passing through the Clements, Calif. and Wallace, Calif. maps, and ending on the Valley Springs SW, Calif. map).

**Comment by fyfangyao** [comment]
I am working on it.

**Comment by fyfangyao** [comment]
(1) Peters, Calif., 1952, photorevised 1969; (2) Waterloo, Calif., 1968, photorevised 1980; (3) Lodi South, Calif., 1968, photorevised 1977; (4) Thornton, Calif., 1978, photorevised 1985; (5) Bruceville, Calif., 1968, photorevised 1981; (6) wallace, Calif., 1962, photorevised 1991; and (7)Valley Springs SW, Calif., 1962, photorevised 1980.

**Comment by MicheleTobias** [comment]
This file had an extra polygon that was making a blank line in the avas.geojson file.  I've updated it and it should behave better now.

**Comment by SoominHur** [comment]
Reviewed.
- Add cfr. author name in the attribute table.
- Add petitioner information in the attribute table.
- Add scale information of the used maps in the attribute table.
- Add description about the beginning point in the attribute table.
