### ISSUE TITLE
long_island

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#115]
# AVA: Long Island (long_island)

name | value
--- | ---
ava_id | long_island
cfr_index | 9.170
revision | [T.D. ATF-453, 66 FR 26791, May 15, 2001]
state | NY
county | Nassau|Suffolk
within | 
contains | North Fork of Long Island\|The Hamptons

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “New York, N.Y.; N.J.; Conn.,” 1960 
revised 1979.;  
2. “Hartford, Conn.; N.Y.; N.J.; Mass.,” 1962 
revised 1975.; and  
3. “Providence, R.I.; Mass.; Conn.; N.Y.,” 1947 
revised 1969..

**Comment by ericallanwest** [comment]
Please label this one In Progress and Virginia Tech. Thanks!
