### ISSUE TITLE
loramie_creek

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#116]
# AVA: Loramie Creek (loramie_creek)

name | value
--- | ---
ava_id | loramie_creek
cfr_index | 9.62
revision | [T.D. ATF-118, 47 FR 53356, Nov. 26, 1982]
state | OH
county | Shelby
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Boundary [src]

(1) From the beginning point of the boundary at the intersection of State Route 47 and Wright-Puthoff Road, the boundary runs southward on Wright-Puthoff Road for a distance of 1  miles to the intersection of the Wright-Puthoff Road with Consolidated Railroad Corporation 
(indicated on the U.S.G.S. map as New York Central Railroad); 
(2) Then along the Consolidated Railroad Corporation right-of-way in a southwesterly direction for a distance of 2  miles to the intersection of the Consolidated Railroad Corporation right-of-way with Loramie Creek; 
(3) Then upstream along Loramie Creek in a northwesterly direction for a distance of approximately 3  miles to the intersection of Loramie Creek and State Route 47; 
(4) Then eastward on State Route 47 for a distance of approximately 4  miles to the beginning point of State Route 47 and Wright-Puthoff Road.

**Comment by dannyo33** [comment]
in progress
