### ISSUE TITLE
los_olivos_district

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#117]
# AVA: Los Olivos District (los_olivos_district)

name | value
--- | ---
ava_id | los_olivos_district
cfr_index | 9.253
revision | [T.D. TTB-132, 81 FR 3329, Jan. 21, 2016]
state | CA
county | Santa Barbara
within | Central Coast\|Santa Ynez Valley
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Los Olivos, CA, 1995; 
2. Zaca Creek, Calif., 1959; 
3. Solvang, CA, 1995; and 
4. Santa Ynez, CA, 1995.

## Boundary [src]

(1) The beginning point is on the Los Olivos map at the intersection of Foxen Canyon Road with California State Road 154 
(known locally as San Marcos Pass Road/Chumash Highway), section 23, T7N/R31W. 
(2) From the beginning point, proceed southwesterly in a straight line approximately 0.3 mile, crossing onto the Zaca Creek map, to the intersection of Ballard Canyon Road and an unnamed, unimproved road known locally as Los Olivos Meadows Drive, T7N/R31W; then 
(3) Proceed south-southeasterly in a straight line approximately 1 mile, crossing onto the Los Olivos map, to a marked, unnamed structure within a circular-shaped 920-foot contour line in the southwest corner of section 26, T7N/R31W; then 
(4) Proceed south-southwesterly in a straight line approximately 1.25 miles, crossing onto the Zaca Creek map, to the point marked by the “Ball” 801-foot elevation control point, T6N/R31W; then 
(5) Proceed south-southwesterly in a straight line approximately 1.45 miles, crossing onto the Solvang map, to a marked, unnamed 775-foot peak, T6N/R31W; then 
(6) Proceed south-southwesterly in a straight line approximately 0.55 mile to a marked communication tower located within the 760-foot contour line, T6N/R31W; then 
(7) Proceed south-southeasterly in a straight line approximately 0.6 mile to the intersection of Chalk Hill Road with an unnamed creek descending from Adobe Canyon, northwest of the unnamed road known locally as Fredensborg Canyon Road, T6N/R31W; then 
(8) Proceed southwesterly 
(downstream) along the creek approximately 1 mile to the creek&#39;s intersection with the Santa Ynez River, T6N/R31W; then 
(9) Proceed easterly 
(upstream) along the Santa Ynez River approximately 8 miles, crossing onto the Santa Ynez map, to the river&#39;s intersection with State Highway 154, T6N/R30W; then 
(10) Proceed north-northwest in a straight line approximately 1.2 miles to the marked 924-foot elevation point, T6R/R30W; then 
(11) Proceed north-northwest in a straight line 1.2 miles to the “Y” in an unimproved road 0.1 mile south of the 800-foot contour line, west of Happy Canyon Road, T6R/R30W; then 
(12) Proceed north-northwest in a straight line for 0.5 mile, crossing onto the Los Olivos map, and continuing approximately 2.3 miles to the third intersection of the line with the 1,000-foot contour line northwest of BM 812, T7N/R30W; then 
(13) Proceed westerly along the meandering 1,000-foot contour line to the contour line&#39;s intersection with an unnamed, unimproved road, an unnamed light-duty road, and the northern boundary line of section 23, T7N/R31W; then 
(14) Proceed northerly, then westerly, along the unnamed, unimproved road to Figueroa Mountain Road, near the marked 895-foot elevation, T7N/R31W; then 
(15) Proceed north on Figueroa Mountain Road approximately 400 feet to the 920-foot contour line, T7N/R31W; then 
(16) Proceed initially south, then northwesterly along the meandering 920-foot contour line, crossing onto the Zaca Creek map, to Foxen Canyon Road, T7N/R31W; then 
(17) Proceed southeasterly on Foxen Canyon Road approximately 1.7 miles, crossing onto the Los Olivos map, returning to the beginning point.

**Comment by tbrittnacher** [comment]
Tom Brittnacher is working on this boundary.

**Comment by SoominHur** [comment]
Reviewed.
- (2) Unable to find "Zaca Creek map ... intersection of Ballard Canyon Road and an unnamed, unimproved road, known locally as Los Olivos Meadows Drive." So, searched google maps and put the node at the third intersection (from north to south direction) of Ballard Cayon Road and eastern edge of Zaca Creek map. Where is approximately 115 feet above in straight line from "unimproved road known locally as Los Olivos Meadows Drive" in Los Olivos map
- (12) The line intersected with the 1,000-foot contour line for the fourth time. So moved node little east side fulfilling following description; "Proceed north-northwest in a straight line for" 2.8 mile "to the third intersection of the line with the 1,000-foot contour line." 
- Refined lines.
- Add scale information of used maps in attribute table.
