### ISSUE TITLE
madera

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#118]
# AVA: Madera (madera)

name | value
--- | ---
ava_id | madera
cfr_index | 9.92
revision | [T.D. ATF-192, 49 FR 47833, Dec. 12, 1984; 50 FR 2782, Jan. 22, 1985, as amended by T.D. ATF-249, 52 FR 5960, Feb. 27, 1987]
state | CA
county | Fresno|Madera
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Clovis, Cal.,” 7  minute series, edition of 1964, photorevised 1972; 
2. “Fresno North, Cal.,” 7  minute series, edition of 1965, photorevised 1972; 
3. “Friant, Cal.,” 7  minute series, edition of 1964; 
4. “Lanes Bridge, Cal.,” 7  minute series, edition of 1964, photoinspected 1973; 
5. “Gregg, Cal.,” 7  minute series, edition of 1965; 
6. “Madera, Cal.,” 7  minute series, edition of 1963; 
7. “Kismet, Cal.,” 7  minute series, edition of 1961; 
8. “Raynor Creek, Cal.,” 7  minute series, edition of 1961; 
9. “Fresno, Cal.,” scaled 1:250,000, edition of 1962, revised 1971; 
10. “Monterey, Cal.,” scaled 1:250,000, edition of 1974; and 
11. “San Jose, Cal.,” scaled 1:250,000, edition of 1962, revised 1969.

## Boundary [src]
minute series U.S.G.S. map at the point where the San Joaquin River intersects the section line dividing sections 20 and 29, and sections 21 and 28, T. 12 S., R. 20 E.; 
(1) Then east approximately 6 miles following the section line and Shepherd Avenue to the intersection with Sunnyside Road; 
(2) Then north approximately 7 miles following Sunnyside Road and continuing along the section line to the point of intersection of section 16, 17, 20, and 21, T.11S., R 21E.; 
(3) Then west approximately 17.6 miles following the section line and continuing along Avenue 15 to the intersection with the Atchison, Topeka and Santa Fe Railroad; 
(4) Then northwest following the Atchison, Topeka and Santa Fe Railroad to Road 26; 
(5) Then north following Road 26 and continuing north in a straight line to the Chowchilla River in the “Raynor Creek” 7  minute series U.S.G.S. map, and in the “San Jose” scaled 1:250,000 U.S.G.S. map; 
(6) Then west following the Chowchilla River to the point where the Madera County-Merced County boundary diverges from the river; 
(7) Then southwest following the Madera County-Merced County boundary to the San Joaquin River; 
(8) Then following the San Joaquin River south and east returning to the point of beginning.

**Comment by sierramabanta** [comment]
Hi! I'd like to work on this one!

**Comment by SoominHur** [comment]
Reviewed
- Edit created date in the attribute table.
