### ISSUE TITLE
malibu_coast

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#119]
# AVA: Malibu Coast (malibu_coast)

name | value
--- | ---
ava_id | malibu_coast
cfr_index | 9.235
revision | [T.D. TTB-121, 79 FR 41896, July 18, 2014]
state | CA
county | Los Angeles|Ventura
within | 
contains | Malibu-Newton Canyon\|Saddle Rock-Malibu

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Canoga Park, Calif., 1953; photorevised 1967; 
2. Topanga, CA, 1991; 
3. Malibu Beach, CA, 1995; 
4. Point Dume, CA, 1995; 
5. Triunfo Pass, CA, 1994; 
6. Point Mugu, Calif., 1949; photorevised 1967; photoinspected 1974; 
7. Carmarillo, Calif., 1950; photorevised 1967; 
8. Newbury Park, Calif., 1950; photorevised 1967; 
9. Thousand Oaks, Calif., 1950; photorevised 1981; and 
10. Calabasas, Calif., 1952; photorevised 1967.

## Boundary [src]

(1) The beginning point is on the Canoga Park map beside Mulholland Drive at the 1,126-foot benchmark 
(BM 1126), located on the marked Los Angeles city boundary line and the northern boundary line of section 24, T1N/R17W. From the beginning point, proceed east-southeasterly along the Los Angeles city boundary line approximately 3.25 miles to the marked 1,718-foot elevation point; then 
(2) Proceed south-southwesterly along the Los Angeles city boundary line approximately 4.35 miles, crossing onto the Topanga map, to the northeast corner of section 19, T1S/R16W; then 
(3) Proceed east-southeasterly along the Los Angeles city boundary line approximately 1.7 miles to the point east of Topanga Canyon where the city boundary line turns south, and then continue southerly along the city boundary line approximately 1.9 miles to the boundary line&#39;s intersection with State Route 1 
(the Pacific Coast Highway); then 
(4) Proceed westerly on State Route 1, crossing onto the Malibu Beach map and then the Point Dume map, to the road&#39;s intersection with the unnamed intermittent creek located within Walnut Canyon 
(near the Zuma Fire Station); then 
(5) Proceed southeasterly 
(downstream) along the unnamed intermittent creek located within Walnut Canyon to the Pacific Ocean shoreline; then 
(6) Proceed southwesterly along the Pacific Ocean shoreline approximately 1.5 miles to Point Dume and then continue northwesterly along the Pacific Ocean shoreline approximately 1.3 miles to the mouth of an unnamed intermittent stream; then 
(7) Proceed northeasterly along the unnamed intermittent stream 
(upstream) approximately 0.35 mile to the stream&#39;s intersection with State Route 1 
(at BM 30); then 
(8) Proceed westerly on State Route 1 approximately 17.4 miles, crossing onto the Triunfo Pass map and then the Point Mugu map, to the road&#39;s intersection with an unnamed light-duty road known locally as Calleguas Creek Road; then 
(9) Proceed north-northeasterly approximately 1.2 miles on Calleguas Creek Road, crossing onto the Camarillo map, to the road&#39;s intersection with an unnamed, unimproved road known locally as Caryl Drive; then 
(10) Encircle an unnamed 350-foot hill by proceeding westerly on Caryl Drive approximately 0.2 mile to the road&#39;s intersection with an unnamed, unimproved road, then continuing on that unnamed, unimproved road around the hill in a clock-wise direction for approximately 0.8 mile until the road intersects again with Caryl Drive; then 
(11) Proceed easterly on Caryl Drive approximately 0.55 mile to the road&#39;s intersection with an unnamed, unimproved road at Broome Ranch; then 
(12) Proceed easterly on the unnamed, unimproved road approximately 0.2 mile to the road&#39;s intersection with the 80-foot elevation line; then 
(13) Proceed initially northeasterly along the meandering 80-foot elevation line, and then continue to follow the meandering 80-foot elevation line westerly, then northeasterly to its intersection with West Potrero Road 
(near Camarillo State Hospital, now the site of California State University Channel Islands); then 
(14) Proceed easterly on West Potrero Road approximately 0.5 mile to the road&#39;s third intersection with the 200-foot elevation; then 
(15) Proceed northerly along the 200-foot elevation line approximately 0.75 mile, crossing over an unnamed intermittent creek in Long Grade Canyon, to the elevation line&#39;s intersection with a second unnamed intermittent stream; then 
(16) Proceed westerly 
(downstream) along the unnamed intermittent stream approximately 0.75 mile to the stream&#39;s intersection with an unnamed medium-duty road known locally as Camarillo Street; then 
(17) Proceed northerly on Camarillo Street approximately 0.7 mile to the street&#39;s intersection with an unnamed light-duty road at the south-bank levee for Calleguas Creek; then 
(18) Proceed easterly on the unnamed light-duty road approximately 0.9 mile to the road&#39;s intersection with the 100-foot elevation line; then 
(19) Proceed initially westerly and then continue easterly and then northerly along the meandering 100-foot elevation line, crossing back and forth between the Camarillo map and the Newbury Park map, to the 100-foot elevation line&#39;s intersection with the T1N/T2N boundary line near Conejo Creek on the Newbury Park map; then 
(20) Proceed east along the T1N/T2N boundary line approximately 0.7 mile to the line&#39;s intersection with U.S. Highway 101 
(Ventura Boulevard); then 
(21) Proceed easterly on U.S. Highway 101 approximately 1.8 miles to the highway&#39;s intersection with Conejo Road 
(known locally as Old Conejo Road); then 
(22) Proceed southerly and then easterly on Conejo Road approximately 0.75 mile to the road&#39;s intersection with Borchard Road 
(also known locally as N. Reino Road); then 
(23) Proceed southerly on Borchard Road 
(also known locally as N. Reino Drive) approximately 0.9 mile to the point where Borchard Road 
(N. Reino Road) turns eastward, and then continue easterly on Borchard Road approximately 1.75 miles to Borchard Road&#39;s intersection with U.S. Highway 101 
(Ventura Boulevard); then 
(24) Proceed easterly on U.S. Highway 101 
(Ventura Boulevard/Freeway) approximately 5 miles, crossing onto the Thousand Oaks map, to the highway&#39;s sixth and last intersection with the 920-foot elevation line in section 14, T1N/R19W 
(approximately 0.2 mile west of the intersection of U.S. Highway 101 and an unnamed road known locally as Hampshire Road); then 
(25) Proceed southerly and then southwesterly along the meandering 920-foot elevation line to its intersection with an unnamed medium-duty road known locally as E Potrero Road, section 27, T1N/R19W; then 
(26) Proceed easterly on E. Potrero Road approximately 0.55 mile to its intersection with an unnamed heavy-duty road known locally as Westlake Boulevard, section 26, T1N/R19W; then 
(27) Proceed northeasterly on Westlake Boulevard approximately 0.4 mile to the road&#39;s second intersection with the 900-foot elevation line, section 26, T1N/R19W; then 
(28) Proceed easterly along the 900-foot elevation line, crossing the Los Angeles-Ventura County line, to the elevation line&#39;s intersection with the boundary line of the Las Virgenes Land Grant 
(concurrent at this point with the northern boundary line of section 31, T1N/R18W); then 
(29) Proceed northeasterly along the Las Virgenes Land Grant boundary line approximately 0.3 mile, crossing Triunfo Canyon, to the boundary line&#39;s intersection with the 1,000-foot elevation line; then 
(30) Proceed westerly and then east-northeasterly along the 1,000-foot elevation line to the line&#39;s intersection with the Las Virgenes Land Grant boundary line, and then continue northeasterly along the Las Virgenes Land Grant boundary line approximately 0.2 mile to the boundary line&#39;s intersection with U.S. Highway 101 
(Ventura Freeway); then 
(31) Proceed easterly on U.S. Highway 101 
(Ventura Freeway) approximately 5.7 miles, crossing onto the Calabasas map, to the highway&#39;s intersection with the northern boundary line of section 30, T1N/R17, near Brents Junction; then 
(32) Proceed west along the northern boundary line of section 30, T1N/R17W approximately 0.5 mile to its intersection with the 1,000-foot elevation line; then 
(33) Proceed northerly, southerly, and easterly along the meandering 1,000-foot elevation line, encompassing portions of Las Virgenes, East Las Virgenes, and Gates Canyons, to the elevation line&#39;s intersection with the western boundary line of section 21, T1N/R17W; then 
(34) Proceed north along the western boundary lines of sections 21 and 16, T1N/R17W, to the section line&#39;s intersection with the Los Angeles-Ventura County line; then 
(35) Proceed east along the Los Angeles-Ventura County line approximately 0.45 mile, and then proceed north along the county line approximately 0.1 mile to the county line&#39;s intersection with Long Valley Road; then 
(36) Proceed east-southeasterly on Long Valley Road approximately 1.7 miles to the road&#39;s intersection with the Los Angeles city boundary line 
(approximately 0.1 mile north of U.S. Highway 101 
(Ventura Freeway)), section 23, T1N/R17W; then 
(37) Proceed south along the Los Angeles city boundary line approximately 0.2 mile, then east-northeasterly approximately 0.2 mile, and then southeasterly approximately 0.9 mile to the city boundary line&#39;s intersection with the northern boundary line of section 26, T1N/R17W; then 
(38) Proceed east-northeasterly along the Los Angeles city boundary line approximately 0.3 mile, and then continue easterly along the city boundary line approximately 0.5 mile, crossing onto the Canoga Park map, and returning to the beginning point.

**Comment by SoominHur** [comment]
Reviewed
- Add scale information of the used maps in the attribute table.
- Could not find any "Canoga Park, CA" map made in 1953 at USGS topo view website. Instead, I used "Canoga Park, CA" 1952 (1986 ed.), photorevised 1967, scale 1:24000 to review.
- Edit typo of approved map #7 to "Camarillo, CA"
