### ISSUE TITLE
adelaida_district

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#12]
# AVA: Adelaida District (adelaida_district)

name | value
--- | ---
ava_id | adelaida_district
cfr_index | 9.238
revision | [T.D. TTB-125, 79 FR 60960, Oct. 9, 2014]
state | CA
county | San Luis Obispo
within | Central Coast\|Paso Robles
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c

## Approved Maps [src]

1.   Paso Robles, Calif., 1948, photorevised 1979; 
 - (2) Templeton, Calif., 1948, photorevised 1979;
 - (3) York Mountain, Calif., 1948, photorevised 1979; 
 - (4) Cypress Mountain, Calif., 1948, photorevised 1979; 
 - (5) Lime Mountain, Calif., 1948, photorevised 1979; and 
 - (6) Adelaida, Calif., 1948, photorevised 1978.

## Boundary [src]
(1) The beginning point is on the Paso Robles map at the point where an unnamed light-duty road locally known as Wellsona Road crosses the main channel of the Salinas River, section 4, T26S/R12E. From the beginning point, proceed southerly (upstream) along the main channel of the Salinas River approximately 3.4 miles to the river&#39;s first intersection with the city of Paso Robles Corporate Boundary line, T26S/R12E; then (2) Proceed westerly and then southerly along the meandering city of Paso Robles Corporate Boundary line, crossing onto the Templeton map, to the boundary line&#39;s intersection with Peachy Canyon Road, T26S/R12E; then (3) Proceed westerly on Peachy Canyon Road approximately 2.6 miles, crossing to and from the Paso Robles map, to the road&#39;s intersection with an unnamed intermittent stream at the 1,100-foot elevation line near the center of section 36, T26S/R11; then (4) Proceed south-southeasterly (downstream) along the unnamed intermittent stream approximately 1.2 miles to the stream&#39;s intersection with the R11E/R12E common boundary line, section 1, T27S/R11E; then (5) Proceed south along the R11E/R12E common boundary line approximately 0.15 mile to the line&#39;s intersection with an unnamed light-duty road locally known as Kiler Canyon Road, section 1, T27S/R11E; then (6) Proceed westerly on the light-duty and then unimproved Kiler Canyon Road approximately 4 miles, crossing onto the York Mountain map, to the road&#39;s intersection with Summit Canyon Road (locally known as Peachy Canyon Road), section 33, T26S/R11E; then (7) Proceed southwesterly on Summit Canyon Road (locally known as Peachy Canyon Road) approximately 3.5 miles to the road&#39;s intersection with Willow Creek Road (locally known as Vineyard Drive), T27S/R11E; then (8) Proceed southerly on Willow Creek Road (locally known as Vineyard Drive) approximately 0.4 mile to the road&#39;s intersection with Dover Canyon Road, T27S/R11E; then (9) Proceed westerly on Dover Canyon Road approximately 2.8 miles to the road&#39;s intersection with an intermittent stream and an unnamed jeep trail in Dover Canyon, section 14, T27S/R10E; then (10) Proceed west-northwesterly in a straight line approximately 5.7 miles, crossing onto the Cypress Mountain map, to the R9E/R10E common boundary line at the northwest corner of section 6, T27S/R10E; then (11) Proceed north along the R9E/R10E common boundary line approximately 6.5 miles, crossing onto the Lime Mountain map, to the line&#39;s intersection with the second unnamed intermittent stream that crosses the western boundary line of section 31, T25S/R10E; then (12) Proceed easterly in a straight line approximately 0.45 mile to a marked 1,165-foot peak in section 31, T25S/R10E, and then continue easterly in a straight line approximately 0.8 mile to the marked 1,135-foot peak in section 32, T25S/R10E; then (13) Proceed due east-northeasterly in a straight line approximately 0.3 mile to the line&#39;s intersection with Dip Creek, section 32, T25S/R10E; then (14) Proceed southeasterly and then easterly along Dip Creek approximately 6 miles, crossing onto the Adelaida map, to the creek&#39;s intersection with San Miguel Road (locally known as Chimney Rock Road), section 13, T26S/R10E; then (15) Proceed easterly on San Miguel Road (locally known as Chimney Rock Road, then Nacimiento Lake Drive, then Godfrey Road, and then San Marcos Road) approximately 8.6 miles, crossing onto the Paso Robles map, to the road&#39;s intersection with an unnamed light-duty road locally known as Wellsona Road, section 6, T26S/R12E; then (16) Proceed southeasterly and then easterly on Wellsona Road approximately 2.0 miles, returning to the beginning point.

**Comment by SoominHur** [comment]
Reviewed.
- Add scale information of used maps.
