### ISSUE TITLE
malibu_newton_canyon

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#120]
# AVA: Malibu-Newton Canyon (malibu_newton_canyon)

name | value
--- | ---
ava_id | malibu_newton_canyon
cfr_index | 9.152
revision | [T.D. ATF-375, 61 FR 29952, June 13, 1996]
state | CA
county | Los Angeles
within | Malibu Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Boundary [src]

(1) Beginning at the intersection of the Newton Canyon creek 
(lowest elevation) and an unnamed medium duty road referred to by the petitioner as Kanan Dume Road at the boundary of section 13 and 18 on the U.S.G.S. map “Point Dume Quadrangle.” 
(2) Then south along Kanan Dume Road to the point where an unnamed, unimproved dirt road referred to by the petitioner as Ramerez Mountain Way crosses over Kanan Dume Road at the tunnel in the northwest corner of section 19. 
(3) Then east along Ramerez Mountain Way, following the southern ridgeline of Newton Canyon, to Latigo Canyon Road in the southwest corner of section 17. 
(4) Then south along Latigo Canyon Road to an unnamed, unimproved dirt road referred to by the petitioner as Newton Mountain Way at the southern boundary of section 17. 
(5) Then northeast along Newton Mountain Way, following the southeastern ridgeline of Newton Canyon, to an unnamed, unimproved dirt road referred to by the petitioner as Castro Mountain Way in section 16. 
(6) Then west along Castro Mountain Way, past Castro Peak, following the northern ridgeline of Newton Canyon to Latigo Canyon Road in section 18. 
(7) Then southwest along the natural ridgeline of Newton Canyon to the intersection of Kanan Dume Road and the 1,600 foot contour line in the southeastern portion of section 13. 
(8) Then southeasterly along Kanan Dume Road to the beginning point.

**Comment by SoominHur** [comment]
Reviewed
