### ISSUE TITLE
manton_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#121]
# AVA: Manton Valley (manton_valley)

name | value
--- | ---
ava_id | manton_valley
cfr_index | 9.236
revision | [T.D. TTB-122, 79 FR 44689, Aug. 1, 2014]
state | CA
county | Shasta|Tehama
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Manton, CA, 1995; 
2. Shingletown, CA, 1985 
provisional.; and 
3. Grays Peak, CA, 1995.

## Boundary [src]

(1) The beginning point is on the Manton map, in the community of Manton, at the intersection of three unnamed light-duty roads known locally as Manton Road, Forward Road, and Rock Creek Road, section 21, T30N/R1E. From the beginning point, proceed northerly, then northeasterly on Rock Creek Road approximately 0.8 mile to the road&#39;s intersection with an unnamed light-duty road known locally as Wilson Hill Road, section 21, T30N/R1E; then 
(2) Proceed westerly, then northerly on Wilson Hill Road, crossing onto the Shingletown map, then continue westerly, then northerly, then northeasterly on the turning Wilson Hill Road, approximately 4 miles in total distance, to the road&#39;s intersection with the marked power line in section 8, T30N/R1E; then 
(3) Proceed east-southeasterly along the marked power line, crossing onto the Manton map, approximately 1.1 miles to the power line&#39;s intersection with the Volta Powerhouse, section 16, T30N/R1E; then 
(4) From the Volta Powerhouse, proceed south-southeasterly 
(downstream) along an aqueduct and penstock, approximately 0.7 mile in total distance, to the penstock&#39;s intersection with the North Fork of Battle Creek, section 16, T30N/R1E; then 
(5) Proceed north-northeasterly 
(upstream) along the North Fork of Battle Creek approximately 0.3 mile to the confluence of Bailey Creek, section 15, T30N/R1E; then 
(6) Proceed east-northeasterly 
(upstream) along Bailey Creek approximately 2 miles to the creek&#39;s intersection with an unnamed light-duty road known locally as Manton Ponderosa Way, section 11; T30N/R1E; then 
(7) Proceed southeasterly along Manton Ponderosa Way approximately 1.8 miles to the road&#39;s intersection with Rock Creek Road, and then proceed easterly on Rock Creek Road approximately 0.05 mile to the road&#39;s intersection with an unnamed light-duty road known locally as Forwards Mill Road, section 19, T30N/R2E; then 
(8) Proceed easterly along Forwards Mill Road approximately 4.5 miles, crossing onto the Grays Peak map, to the road&#39;s intersection with an unnamed light-duty road known locally as Forward Road, section 26, T30N/R2E; then 
(9) Proceed generally westerly along Forward Road approximately 4.8 miles, crossing onto the Manton map, to the road&#39;s intersection with an unnamed light-duty road known locally as Ponderosa Way, section 31, T30N/R2E; then 
(10) Proceed southerly along Ponderosa Way approximately 1.7 miles to the road&#39;s intersection with an unimproved road 
(Pacific Gas and Electric service road, approximately 0.25 mile west-southwest of Bluff Springs), section 1, T29N/R1E; then 
(11) Proceed westerly along the unimproved road approximately 2.2 miles to the road&#39;s intersection with the South Battle Creek Canal, section 3, T29N/R1E; then 
(12) Proceed generally northwesterly 
(downstream) along the meandering South Battle Creek Canal approximately 1.3 miles to the canal&#39;s intersection with an unimproved road known locally as South Powerhouse Road, section 4, T29N/R1E; then 
(13) Proceed northerly along South Powerhouse Road approximately 2 miles to the road&#39;s intersection with an unnamed light-duty road known locally as Manton Road, section 21, T30N/R1E; then 
(14) Proceed easterly along Manton Road approximately 0.1 mile, returning to the beginning point.

**Comment by MicheleTobias** [comment]
I'm working on this one.

**Comment by SoominHur** [comment]
Reviewed.
