### ISSUE TITLE
martha_s_vineyard

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#122]
# AVA: Martha’s Vineyard (martha_s_vineyard)

name | value
--- | ---
ava_id | martha_s_vineyard
cfr_index | 9.73
revision | [T.D. ATF-193, 50 FR 256, Jan. 3, 1985]
state | MA
county | Dukes
within | Southeastern New England
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c

**Comment by MicheleTobias** [comment]
Done!  Don't hesitate to ask any questions!
