### ISSUE TITLE
mcdowell_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#123]
# AVA: McDowell Valley (mcdowell_valley)

name | value
--- | ---
ava_id | mcdowell_valley
cfr_index | 9.36
revision | [T.D. ATF-97, 46 FR 59243, Dec. 4, 1981, as amended by T.D. ATF-249, 52 FR 5956, Feb. 27, 1987]
state | CA
county | Mendocino
within | Mendocino\|North Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]
 Approved maps. The appropriate map for determining the boundaries of the McDowell Valley viticultural area is a USGS map. That map is titled: “Hopland Quadrangle California” 7.5 minute series.

## Boundary [src]

(2) Then southerly along the section line between Sections 22 and 21 approximately 1700 feet to the intersection of the section line and the ridge line 
(highest elevation line) between the McDowell Creek Valley and the Dooley Creek Valley. 
(3) Then southeasterly along the ridge line 
(highest elevation line) to the intersection of the ridge line and the 1000-foot contour line in Section 27. 
(4) Then southeasterly and on the McDowell Creek Valley side of the ridge along the 1000-foot contour line to the intersection of the 1000-foot contour line and the south section line of Section 27. 
(5) Then easterly along the section line between Sections 27 and 34 and between Sections 26 and 35 to the intersection of the section line and the centerline of Younce Road. 
(6) Then southeasterly and then northeasterly along Younce Road to the intersection of Younce Road and the section line between Sections 26 and 35. 
(7) Then due north from the section line, across Coleman Creek approximately 1250 feet, to the 1000-foot contour line. 
(8) Then westerly and then meandering generally to the north and east along the 1000-foot contour line to the intersection of the 1000-foot contour line and section line between Sections 26 and 25. 
(9) Then continuing along the 1000-foot countour line easterly and then northwesterly in Section 25 to the intersection of the 1000-foot contour line and the section line between Sections 26 and 25. 
(10) Then northerly along the 1000-foot contour line to the intersection of the 1000-foot contour line and the section line between Sections 23 and 24. 
(11) Then northerly along the section line across State Highway 175 approximately 1000 feet to the intersection of the section line and the 1000-foot contour line. 
(12) Then generally to the northwest along the 1000-foot contour line through Sections 23 and 14 and into Section 15 to the intersection of the 1000-foot contour line and the flowline of an unnamed creek near the northeast corner of Section 15. 
(13) Then southwesterly and down stream along the flowline of said unnamed creek and across Section 15, to the stream&#39;s intersection with the section line between Sections 15 and 16. 
(14) Then southerly along the section approximately 100 feet to the northwest corner of Section 22 and to the point of beginning.

**Comment by fyfangyao** [comment]
I am working on this.

**Comment by fyfangyao** [comment]
I use “Hopland, CA,” 7.5 Minute Series, edition of 1960, (photoinspected 1984) because the approved map doesn’t specify the edition.

**Comment by SoominHur** [comment]
Reviewed. Improved (2) ... along the ridge line ...
