### ISSUE TITLE
mcminnville

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#124]
# AVA: McMinnville (mcminnville)

name | value
--- | ---
ava_id | mcminnville
cfr_index | 9.181
revision | [T.D. TTB-22, 70 FR 2804, Jan. 18, 2005]
state | OR
county | Yamhill
within | Willamette Valley
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. McMinnville, Oregon, 1957, revised 1992; 
2. Muddy Valley, Oregon, 1979, revised 1992; 
3. Stony Mountain, Oregon, 1979, revised 1992; 
4. Sheridan, Oregon, 1956, revised 1992; and 
5. Ballston, Oregon, 1956, revised 1992.

## Boundary [src]

(1) The beginning point is on the McMinnville, Oregon, map where the 200-foot contour line intersects the common boundary between section 13, T4S, R5W, and section 18, T4S, R4W. From this point follow the meandering 200-foot contour line westerly for about 2 miles to its intersection with Baker Creek Road in section 54, T4W, R5W, on the Muddy Valley map; 
(2) Then follow Baker Creek Road west about 2 miles through Happy Valley to the road&#39;s intersection with Power House Hill Road in section 50, T4S, R5W 
(Muddy Valley map); 
(3) Proceed southwest on Power House Hill Road for about 1.4 miles to its intersection with Peavine Road in section 17, T4S, R5W 
(Muddy Valley map); 
(4) Follow Peavine Road west and then northwest about 1.5 miles to its intersection with Gill Creek in section 18, T4S, R5W 
(Muddy Valley map); 
(5) Follow Gill Creek southerly 
(downstream) for about 0.6 miles to its intersection with the 800-foot contour line in section 18, T4S, R5W, on the Muddy Valley map; 
(6) From Gill Creek, follow the meandering 800-foot contour line westerly, crossing Deer Creek in section 14, T4S, R6W, on the Stony Mountain map, and, crossing back and forth four times between the Stony Mountain and Muddy Valley maps in section 24, T4S, R6W, continue southwesterly to the contour line&#39;s intersection with Thomson Mill Road in section 27, T4S, R6W, on the Stony Mountain map; 
(7) Continue to follow the meandering 800-foot contour line southwesterly, crossing Cronin and Beaver Creeks, to the 800-foot contour line&#39;s intersection with Rock Creek Road in section 46, T5S, R6W, on the Stony Mountain map; 
(8) Then follow Rock Creek Road south for about 5 miles to its intersection with the West Valley Highway in section 44, T5S, R6W, on the Sheridan map, and continue about 200 feet due south in a straight line to from that intersection to the 200-foot contour line, just north of the Yamhill River 
(Sheridan map); 
(9) Then follow the meandering 200-foot contour line easterly, passing north of most of the village of Sheridan, crossing onto the Ballston map, and continue easterly and then northerly along the 200-foot contour line to its first intersection with Christensen Road at the common boundary between sections 27 and 34, T5S, R5W 
(Ballston map); 
(10) Continue to follow the 200-foot contour line westerly and then northerly, passing onto the Muddy Valley map and then the Stony Mountain map, to the contour line&#39;s intersection with Deer Creek in section 64, T5S, R6W 
(Stony Mountain map); 
(11) Cross Deer Creek and follow the 200-foot contour line southeasterly, crossing Dupree Creek in section 64, T5S, R6W, on the Muddy Valley map, and, crossing onto the Ballston map, continue southerly and then easterly along the 200-foot contour line to its intersection with State Route 18 at the hamlet of Bellevue, section 28, T5S, R5W 
(Ballston map); 
(12) Continue westerly then northerly along the meandering 200-foot contour line, crossing Latham Road at the northern boundary of section 53, T5S, R5W, and, crossing onto the Muddy Valley map, continue northerly along the 200-foot contour line to its intersection with Muddy Creek in section 40, T5S, R5W 
(Muddy Valley map); 
(13) Crossing Muddy Creek, follow the 200-foot contour line southerly, then easterly, and then northerly to its intersection with Peavine Road in the western extension of section 47, T4S, R5W 
(Muddy Valley map); 
(14) From Peavine Road, continue northeasterly along the meandering 200-foot contour line, crossing Cozine Creek in section 46, T4S, R5W, and, crossing onto the McMinnville map, follow the 200-foot contour line across Redmond Hill Road in section 44, T4S, R5W, and return to the point of beginning 
(McMinnville map)

**Comment by alisonsnwong** [comment]
Checked!
