### ISSUE TITLE
mendocino

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#125]
# AVA: Mendocino (mendocino)

name | value
--- | ---
ava_id | mendocino
cfr_index | 9.93
revision | [T.D. ATF-178, 49 FR 24714, June 15, 1984, as amended by T.D. ATF-397, 63 FR 16904, Apr. 7, 1998; T.D. TTB-124, 79 FR 60972, Oct. 9, 2014]
state | CA
county | Mendocino
within | North Coast
contains | Anderson Valley\|Cole Ranch\|McDowell Valley\|Mendocino Ridge\|Potter Valley\|Redwood Valley\|Yorkville Highlands

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Willits Quadrangle, California—Mendocino Co.,” 15 minute series 
1961.; 
2. “Potter Valley Quadrangle, California,” 15 minute series 
1960.; 
3. “Ukiah Quadrangle, California,” 15 minute series 
1958.; 
4. “Hopland Quadrangle, California,” 15 minute series 
1960.; 
5. “Boonville Quadrangle, California—Mendocino Co.,” 15 minute series 
1959.; 
6. “Navarro Quadrangle, California—Mendocino Co.,” 15 minute series 
1961.; 
7. “Ornbaun Valley Quadrangle, California,” 15 minute series 
1960..

## Boundary [src]

The beginning point is the southeast corner of Section 30, Township 12 North (T. 12 N.), Range 10 West (R. 10 W.) located along the Mendocino County/Sonoma County line in the southeast quadrant of U.S.G.S. map “Hopland Quadrangle.”
(1) From the beginning point, the boundary runs north along the eastern boundary of Sections 30, 19, 18, 7 and 6 to the point labeled Jakes Cr 
(Jakes Creek) located at the northwest corner of Section 5, T. 12 N., R. 10 W.; 
(2) Thence in a straight line in a northwest direction to the point labeled Bedford Rock in Section 3, T. 13 N., R. 11 W.; 
(3) Thence in a straight line in a northwest direction to a point labeled Red Mtn in Section 17, T. 14 N., R. 11 W.; 
(4) Thence in a straight line in a northwest direction to the southeast corner of Section 25, T. 16 N., R. 11 W.; 
(5) Thence in a straight line in a northeast direction to the northeast corner of Section 1, T. 16 N., R. 11 W. located along the Mendocino County/Lake County line; 
(6) Thence in a straight line in a northwest direction to the northeast corner of Section 5, T. 17 N., R. 11 W.; 
(7) Thence due west along the T.18N./T.17N. common line until the common line intersects with the R.13W./R.12W. common line; 
(8) Thence in a straight line in a south-southwesterly direction, crossing onto the Willits map, to the intersection of the 1,600-foot contour line and Baker Creek 
(within McGee Canyon) along the west boundary line of Section 25, T.17N./R.13W.; 
(9) Thence in a southeasterly direction 
(downstream) along Bakers Creek to where the creek intersects with the 1,400-foot contour line in Section 25, T.17N/R.13W.; 
(10) Thence in a straight line in a southeasterly direction to the southeast corner of Section 36, T.17N./R.13W.; 
(11) Thence in a straight line in a west-southwesterly direction to the intersection of U.S. Highway 101 and an unnamed road known locally as Reeves Canyon Road in Section 1, T.16N./R.13W.; 
(12) Thence in a straight line in a southeasterly direction to the southeast corner of Section 1, T.16N./R.13W.; 
(13) Thence in a straight line in a south-southwesterly direction to the intersection of an unnamed, unimproved road and an unnamed, intermittent stream, approximately 500 feet south of Seward Creek, in Section 12, T.16N./R.13W.; 
(14) Thence in a straight line in a west-southwesterly direction to the southwest corner of Section 12, T.16N./R.13W.; 
(15) Thence in a straight line in a southwesterly direction to the southwest corner of Section 14, T.16N./R.13W.; 
(16) Thence in a straight line in a southwest direction to the point labeled Eagle Rock located in Section 16, T. 15 N., R. 13 W.; 
(17) Thence in a straight line in a southeast direction to the point labeled Bus McGall Peak located in Section 4, T. 13 N., R. 12 W.; 
(18) Thence in a straight line in a westerly direction to an unnamed hilltop, elevation 2,015 feet, in the northeast corner of Section 9, T. 13 N., R. 13 W.; 
(19) Thence in a straight line in a northwest direction to the junction of Baily Gulch and the South Branch, North Fork of the Navarro River, located in Section 8, T.15N., R.15W.; 
(20) Thence in a straight line in a southwest direction to Benchmark 
(BM) 1057 located in Section 28, T. 15 N., R. 16 W.; 
(21) Thence due south in a straight line approximately 1.4 miles to Greenwood Creek located in Section 33, T. 15 N., R. 16 W.; 
(22) Thence following Greenwood Creek in a generally southeasterly and then a northeasterly direction to where it intersects with the south section line of Section 16, T. 14 N., R. 15 W., approximately .2 miles west of Cold Springs Road; 
(23) Thence in an easterly direction along the south section lines of Sections 16, 15, and 14, T. 14 N., R. 15 W., to the intersection of the south section line of Section 14 with an unnamed creek; 
(24) Thence in a straight line in a southeasterly direction to Benchmark 
(BM) 680 located in Section 30, T. 13 N., R. 13 W.; 
(25) Thence continuing in a straight line in a southerly direction to the southwest corner of Section 5, T. 12 N., R. 13 W., and the Mendocino County/Sonoma County line; 
(26) Thence continuing in a straight line in a southeasterly direction to the intersection of the southwest corner of Section 32, T. 12 N., R. 11 W., and the Mendocino County/Sonoma County line; 
(27) Thence following the Mendocino County/Sonoma County line in an easterly, northerly, and then an easterly direction to the beginning point.

**Comment by SoominHur** [comment]
Reviewed
- Edit created date in the attribute table.
