### ISSUE TITLE
merritt_island

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#127]
# AVA: Merritt Island (merritt_island)

name | value
--- | ---
ava_id | merritt_island
cfr_index | 9.68
revision | [T.D. ATF-134, 48 FR 22146, May 17, 1983, as amended by T.D. ATF-249, 52 FR 5959, Feb. 27, 1987]
state | CA
county | Yolo
within | Clarksburg
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Clarksburg Quadrangle, California,” 1967 
Photo revised 1980.; and 
2. “Courtland Quadrangle, California,” 1978.

## Boundary [src]

(1) Starting at the most southernly point, the intersection of Sutter Slough with the Sacramento River. 
(2) Then west along the course of Sutter Slough for 0.54 miles until it intersects Elk Slough. 
(3) Then northeast along the course of Elk Slough for 9.58 miles to the community of Clarksburg and the intersection of Sacramento River. 
(4) Then southeasterly along the course of the Sacramento River for 7.8 miles to the beginning point.

**Comment by SoominHur** [comment]
Reviewed. cfr author name was missing in attribute table, so added it.
