### ISSUE TITLE
mesilla_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#128]
# AVA: Mesilla Valley (mesilla_valley)

name | value
--- | ---
ava_id | mesilla_valley
cfr_index | 9.100
revision | [T.D. ATF-197, 50 FR 6163, Feb. 14, 1985]
state | NM|TX
county | 
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Anthony, N. Mex.-Tex.,” 7.5 minute series, edition of 1955; 
2. “Bishop Cap, N. Mex.,” 7.5 minute series, edition of 1955; 
3. “Black Mesa, N. Mex.,” 7.5 minute series, edition of 1978; 
4. “Canutillo, Tex.-N. Mex.,” 7.5 minute series, edition of 1955 
photorevised 1967.; 
5. “Dona Ana, N. Mex.,” 7.5 minute series, edition of 1978; 
6. “La Mesa, N. Mex.,” 7.5 minute series, edition of 1955; 
7. “La Union, N. Mex.-Tex.” 7.5 minute series, edition of 1955; 
8. “Las Cruces, N. Mex.,” 7.5 minute series, edition of 1978; 
9. “Leasburg, N. Mex.,” 7.5 minute series, edition of 1978; 
10. “Little Black Mountain, N. Mex.,” 7.5 minute series, edition of 1978; 
11. “Picacho Mountain, N. Mex.,” 7.5 minute series, edition of 1978; 
12. “San Miguel, N. Mex.,” 7.5 minute series, edition of 1955; 
13. “Smeltertown, Tex.-N. Mex.,” 7.5 minute series, edition of 1955 
photorevised 1967 and 1973.; 
14. “Strauss, N. Mex.-Tex.,” 7.5 minute series, edition of 1955; and 
15. “Tortugas Mountain, N. Mex.,” 7.5 minute series, edition of 1955.

## Boundary [src]

(1) From the beginning point, the boundary runs east 3.7 miles along the north section line until it converges with the 4,200 foot elevation contour line at Section 18, T21S/R1E; 
(2) Then it runs southeasterly 31 miles along the 4,200 foot elevation contour line to a point approximately 3.5 miles south of Bishop Cap where it intersects the Fort Bliss Military Reservation boundary at the northeast portion of Section 13, T25S/R3E on the “Bishop Cap, N. Mex.” U.S.G.S. map; 
(3) Then it follows the Fort Bliss Military Reservation boundary south for approximately 3.7 miles and east approximately .8 mile to the intersection with the 4,200 foot elevation contour line at the southeast portion of Section 6, T26S/R4E on the “Anthony, N. Mex.-Tex.” U.S.G.S. map; 
(4) Then it runs south along the 4,200 foot elevation contour line for approximately 20 miles until it intersects the La Mesa Road 
(Mesa Avenue) in the city limits of El Paso, Texas, on the “Smeltertown, Tex.-N. Mex.” U.S.G.S. map; 
(5) Then it heads south on the La Mesa Road 
(Mesa Avenue) for 1.2 miles until it meets Executive Center Boulevard that goes to La Guna/Smeltertown; 
(6) Then it travels in a southwesterly direction for 1.1 miles on Executive Center Boulevard to La Guna/Smeltertown until it crosses the Southern Pacific Railroad tracks at Smeltertown, Texas; 
(7) Then it proceeds back into New Mexico northwesterly along the Southern Pacific Railroad tracks approximately 12.5 miles to a point near the switch yards at Strauss, New Mexico, where it intersects the 4,100 foot elevation contour line at the center of Section 24, T28S/R2E on the “Strauss, N. Mex.-Tex.” U.S.G.S. map; 
(8) Then it follows the 4,100 foot elevation contour line in a northwesterly direction for 17 miles until it intersects with the south section line of Section 29, T25S/R2E, on the “Little Black Mountain, N. Mex.” U.S.G.S. map; 
(9) Then it runs westerly approximately .5 mile along the south section line until it meets the 4,150 foot elevation contour line at Section 29, T25S/R2E; 
(10) Then it follows the 4,150 foot elevation contour line northward for 15 miles until it meets with Interstate Highway 70/80/180 at the southeast corner of Section 19, T23S/R1E, on the “Las Cruces, N. Mex.” U.S.G.S. map; 
(11) Then it runs southwest along Interstate Highway 70/80/180 for approximately .9 mile until it reaches the 4,200 foot elevation contour line at the northwest corner of Section 30, T23S/R1E, on the “Picacho Mt., N. Mex.” U.S.G.S. map; 
(12) Then it meanders in a northerly direction on the 4,200 foot elevation contour line for 15 miles until it reaches the section line at the southwest corner of Section 15, T21S/R1W on the “Leasburg, N. Mex.” U.S.G.S. map; 
(13) Then finally it goes north along the section line to Faulkner Canyon until it meets with the northwest corner of Section 15, T21S/R1W, which is the beginning point.

**Comment by alisonsnwong** [comment]
Checked! Updated `used_maps` section.
