### ISSUE TITLE
middleburg_virginia

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#129]
# AVA: Middleburg Virginia (middleburg_virginia)

name | value
--- | ---
ava_id | middleburg_virginia
cfr_index | 9.225
revision | [T.D. TTB-106, 77 FR 56548, Sept. 13, 2012]
state | VA
county | Fauquier|Loudoun
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Harpers Ferry Quadrangle, West Virginia-Virginia-Maryland, 1996; 
2. Point of Rocks Quadrangle, Maryland-Virginia, 1970, photoinspected 1981; 
3. Waterford Quadrangle, Virginia-Maryland, 1970, photorevised 1984; 
4. Leesburg Quadrangle, Virginia-Maryland, 1994; 
5. Lincoln Quadrangle, Virginia-Loudoun Co., 1970, photoinspected 1981; 
6. Middleburg Quadrangle, Virginia, 1968, photorevised 1978, photoinspected 1981; 
7. Rectortown Quadrangle, Virginia, 1970, photoinspected 1981; 
8. Marshall Quadrangle, Virginia-Fauquier Co., 1970, photorevised 1983; 
9. Orlean Quadrangle, Virginia, 1970, photorevised 1983; 
10. Upperville Quadrangle, Virginia, 1970, photorevised 1983; 
11. Linden Quadrangle, Virginia, 1994; 
12. Ashby Gap Quadrangle, Virginia, 1970, photorevised 1978, photoinspected 1981; 
13. Bluemont Quadrangle, Virginia, 1970, photorevised 1979; photoinspected 1981; and 
14. Purcellville Quadrangle, Virginia-Loudoun Co., 1970, photorevised 1984.

## Boundary [src]

(1) The beginning point is on the Harpers Ferry map at the intersection of the easternmost boundary line of the Harpers Ferry National Historical Park and the south bank of the Potomac River in Loudoun County, Virginia. From the beginning point, follow the south bank of the Potomac River easterly 
(downstream) for approximately 8.2 miles, crossing onto the Point of Rocks map, to the mouth of Catoctin Creek; then 
(2) Proceed southwesterly 
(upstream) along the meandering Catoctin Creek for approximately 4 miles to State Route 663 
(locally known as Taylorstown Road) at Taylorstown; then 
(3) Proceed easterly on State Route 663 for approximately 0.1 mile to State Route 665 
(locally known as Loyalty Road) in Taylorstown; then 
(4) Proceed southerly on State Route 665 for approximately 5.4 miles, crossing onto the Waterford map, to State Route 662 on the south side of Waterford; then 
(5) Proceed southerly on State Route 662 for approximately 2.5 miles to State Route 9 
(locally known as Charles Town Pike) near Paeonian Springs; then 
(6) Proceed southerly on State Route 9 
(Charles Town Pike) for approximately 0.7 mile, crossing over State Route 7 
(locally known as Harry Byrd Highway), to State Business Route 7 
(locally known as E. Colonial Highway); then 
(7) Proceed westerly on State Business Route 7 
(E. Colonial Highway) for approximately 0.4 mile to the continuation of State Route 662 
(locally known as Canby Road); then 
(8) Proceed southerly on State Route 662 
(Canby Road) for approximately 0.75 miles to an unnamed, unimproved road near the marked 701-foot elevation; then 
(9) Proceed southeasterly in a straight line for approximately 0.4 miles, crossing onto the Leesburg map, to the northern terminus of an unnamed light-duty road known locally as Gore Lane; then 
(10) Proceed southerly along Gore Lane for approximately 0.7 miles to State Route 820; then 
(11) Proceed southwesterly along State Route 820 for approximately 0.68 miles, crossing onto the Lincoln map, to State Route 622 
(Canby Road); then 
(12) Proceed southwesterly on State Route 622 
(Canby Road) for approximately 2 miles to the intersection with State Route 729; then 
(13) Proceed southwesterly on State Route 729 for approximately 2.8 miles to the State Route 729 bridge at North Fork Creek; then 
(14) Proceed southeasterly 
(downstream) along the meandering North Fork Creek for approximately 4 miles to the confluence of North Fork Creek with Goose Creek; then 
(15) Proceed southwesterly 
(upstream) along the meandering Goose Creek for approximately 5.6 miles to State Route 734 at Carters Bridge; then 
(16) Proceed southeasterly on State Route 734 for approximately 2.4 miles, crossing onto the Middleburg map, to State Route 629; then 
(17) Proceed southerly on State Route 629 for approximately 1 mile to the road&#39;s intersection with U.S. Route 50 at Benchmark 
(BM) 341 at Dover, then continue in a straight line due south for approximately 150 feet to the Little River; then 
(18) Proceed southwesterly 
(upstream) along the meandering Little River for approximately 8 miles to the State Route 626 bridge at Halfway; then 
(19) Proceed northwesterly on State Route 626 for approximately 0.3 mile to State Route 706, and then continue northwesterly on State Route 706 for approximately 1.6 miles, crossing onto the Rectortown map, to Burnt Mill Run; then 
(20) Proceed west-southwesterly 
(upstream) along Burnt Mill Run for approximately 0.4 mile to State Route 705; then 
(21) Proceed south-southwesterly on State Route 705 for approximately 0.5 mile to State Route 715; then 
(22) Proceed west-northwesterly on State Route 715 for approximately 0.4 mile to State Route 709 at Zulla; then 
(23) Proceed south-southwesterly on State Route 709 for approximately 4.6 miles, crossing onto the Marshall map, to Interstate Highway 66 
(0.6 mile south of Brookes Corner); then 
(24) Proceed west-northwesterly on Interstate Highway 66 for approximately 4.0 miles, crossing onto the Orlean map, to State Route 732 
(locally known as Ramey Road); then 
(25) Proceed westerly on State Route 732 approximately 2 miles to State Route 731 
(locally known as Ashville Road) near Ashville; then 
(26) Proceed northwesterly in a straight line, crossing onto the Upperville map, to the marked 1,304-foot peak on Little Cobbler Mountain, then northerly in a straight line to the marked 1,117-foot peak on Little Cobbler Mountain, and then continue northerly in a straight line to the marked 771-foot peak near the northern end of Little Cobbler Mountain; then 
(27) Proceed west in a straight line for approximately 2.7 miles to the 595-foot elevation point on State Route 724, southeast of Markham, and continue west in a straight line for approximately 3.1 miles, crossing onto the Linden map, to State Route 726 and an unnamed side road 
(near a cemetery), approximately 0.7 mile southwest of the intersection of State Route 726 and State Route 55 
(near Belle Meade); then 
(28) Proceed northeasterly along State Route 726 for approximately 0.7 mile to State Route 55; then 
(29) Proceed east-northeast in a straight line for approximately 1.7 miles to State Route 688 at BM 629 in Wildcat Hollow; then 
(30) Proceed northerly and then northeasterly on State Route 688 for approximately 5.5 miles, crossing over and back between the Linden and Upperville maps and then continuing on the Upperville map, to U.S. Route 17; then 
(31) Proceed northerly on U.S. Route 17 for approximately 2.0 miles, crossing onto the Ashby Gap map, to U.S. Route 50 
(just east of Paris); then 
(32) Proceed east-northeasterly in a straight line for approximately 1.5 miles to the marked 797-foot elevation point located along State Route 618 at a fork in the road approximately 0.65 miles north of U.S. Route 50; then 
(33) Proceed southeasterly in a straight line for approximately 0.9 mile to U.S. Route 50 at BM 625, which is located at a bridge over an unnamed branch of Panther Skin Creek; then 
(34) Proceed south-southeasterly in a straight line for approximately 2.9 miles, crossing onto the Upperville map, to the intersection of State Routes 712 and 710 at Kerfoot; then 
(35) Proceed southeasterly on State Route 710 for approximately 2.5 miles, crossing onto the Rectortown map, to the State Route 710 bridge over Goose Creek; then 
(36) Proceed northeasterly 
(downstream) along the meandering Goose Creek for approximately 10.9 miles to State Route 626 at Bentons Bridge; then 
(37) Proceed northwesterly on State Route 626 for approximately 4.0 miles, crossing onto the Bluemont map, to State Route 630 at Unison; then 
(38) Proceed northeasterly on State Route 630 for approximately 0.75 mile to Dog Branch; then 
(39) Proceed northwesterly along Dog Branch for approximately 1.75 miles to State Route 719; then 
(40) Proceed north-northeasterly on State Route 719 for approximately 2 miles to State Route 734 at Airmont; then 
(41) Proceed east-southeasterly on State Route 734 for approximately 0.7 mile to State Route 735; then 
(42) Proceed northeasterly on State Route 735 for approximately 2 miles to State Route 725; then 
(43) Proceed north-northeasterly in a straight line for approximately 4.4 miles, crossing over the northwest corner of the Lincoln map and then onto the Purcellville map, to the intersection of State Routes 711 and 690, 
(northwest of Purcellville); then 
(44) Proceed north-northeasterly on State Route 690 for approximately 3.1 miles to State Route 9, then proceed east on State Route 9 for approximately 0.2 mile to the continuation of State Route 690, then proceed northerly on State Route 690 for approximately 5.3 miles, crossing onto the Harpers Ferry map, to the road&#39;s intersection with the 600-foot elevation line immediately south of the road&#39;s marked 592-foot elevation point 
(located 0.75 mile east-northeast of the radio facilities at the 1,424-foot peak of Short Hill Mountain); then 
(45) Proceed northerly along the 600-foot elevation line for approximately 4 miles to the Harpers Ferry National Historical Park south boundary line; then 
(46) Proceed east and north approximately 0.75 mile along the Harpers Ferry National Historical Park boundary line, returning to the beginning point.

**Comment by ericallanwest** [comment]
Please label this one In Progress. Thanks!

**Comment by alisonsnwong** [comment]
Checked! Edited used_maps section & made minor border edits.
