### ISSUE TITLE
alexander_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#13]
# AVA: Alexander Valley (alexander_valley)

name | value
--- | ---
ava_id | alexander_valley
cfr_index | 9.53
revision | [T.D. ATF-187, 49 FR 42724, Oct. 24, 1984, as amended by T.D. ATF-233, 51 FR 30354, Aug. 26, 1986; T.D. ATF-272, 53 FR 17025, May 13, 1988; T.D. ATF-300, 55 FR 32402, Aug. 9, 1990; T.D. ATF-468, 66 FR 50565, Oct. 4, 2001; T.D. TTB-65, 73 FR 12877, Mar. 11, 2008]
state | CA
county | Sonoma
within | North Coast\|Northern Sonoma
contains | Pine Mountain--Cloverdale Peak\|Russian River Valley

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Mark West Springs Quadrangle, California,” 7.5 minute series, 1958; 
2. “Mount St. Helena Quadrangle, California,” 7.5 minute series, 1959; 
3. “Jimtown Quadrangle, California—Sonoma County,” 7.5 minute series, 1955 
Photorevised 1975.; 
4. “Geyserville Quadrangle, California—Sonoma County,” 7.5 minute series, 1955 
Photorevised 1975.; 
5. “Healdsburg Quadrangle, California—Sonoma County,” 7.5 minute series, 1955; 
6. “Asti Quadrangle, California,” 7.5 minute series, 1959 
Photorevised 1978.; and 
7. “Cloverdale Quadrangle, California,” 7.5 minute series, 1960.

## Boundary [src]

From the beginning point at the northeast corner of Section 32, Township 12 North (T. 12 N.), Range 10 West (R. 10 W.), on the Asti Quadrangle map, the boundary runs—
(1) West along the north line of Sections 32 and 31, T. 12 N., R. 10 W., and Sections 36, 35, and 34, T. 12 N., R. 11 W., to the northwest corner of Section 34, on the Cloverdale Quadrangle map; 
(2) Then south along the west line of Section 34 to the southwest corner thereof; 
(3) Then east southeasterly in a straight line to the southeast corner of section 2, T. 11 N., R. 11 W.; 
(4) Then south southeasterly in a straight line to the southeast corner of section 24, T. 11 N., R. 11 W.; 
(5) Then straight south along the eastern boundary line of Section 25, to its intersection with Kelly Road, a medium-duty road, T. 11 N., R. 11 W.; 
(6) Then southwest along Kelly Road to its intersection with the northern boundary line of Section 36, T. 11 N., R. 11 W.; 
(7) Then straight south to its intersection with 38° 45  N. latitude along the southern border of the Cloverdale Quadrangle map, T. 10 N., R. 11 W. and R. 10 W.; 
(8) Then straight east to its intersection with 123° 00  E. longitude at the southeastern corner of the Cloverdale Quadrangle map, T. 10 N., R. 10 W.; 
(9) Then southeasterly in a straight line approximately 11,000 feet 
(closely following the ridge line) to the northwest corner of Section 10, T. 10 N., R.10 W. on the Geyserville Quadrangle map;  
(10) [Reserved] 
(11) Then southerly along the west line of Section 10, T. 10 N., R. 10 W.; 
(12) Then S. 74 degrees, E. 2,800 feet in a straight line to the northeasterly tip of a small lake; 
(13) Then N. 57 degrees, E. 2,300 feet in a straight line to the southeast corner of Section 10, T. 10 N., R. 10 W.; 
(14) Then S. 16 degrees, E. 1,800 feet in a straight line to the point on a peak identified as having an elevation of 664 feet; 
(15) Then S. 55 degrees, E. 7,900 feet in a straight line to the most northerly point on the northeasterly line of “Olive Hill” Cemetery, lying on the easterly side of a light-duty road identified as Canyon Road; 
(16) Then southeasterly along the northeasterly line of “Olive Hill” cemetery to most easterly point thereon; 
(17) Then southerly 3,000 feet along the meanders of the west fork of Wood Creek to the point lying 400 feet north of the point on a peak identified as having an elevation of 781 feet; 
(18) Then southerly 400 feet in a straight line to the point on a peak identified as having an elevation of 781 feet; 
(19) Then S. 50  degrees, E. 15,200 feet in a straight line to the point lying at the intersection of Lytton Creek with the township line common to T. 9 N. and T. 10 N. in R. 9 W.; 
(20) Then southerly along the meanders of Lytton Creek to the point of intersection with a light-duty road identified as Lytton Springs Road in T. 9 N., R. 9 W.; 
(21) Then easterly along Lytton Springs Road to the point of intersection with a heavy-duty road identified as U.S. Highway 101 
(a.k.a. Redwood Highway), on the Jimtown Quadrangle map; 
(22) Then southerly along U.S. Highway 101 to the point of intersection with an unnamed light-duty road 
(known locally as Chiquita Road), on the Geyserville Quadrangle map; 
(23) Then easterly along the unnamed light-duty road to the point of intersection with an unnamed heavy-duty road 
(known locally as Healdsburg Avenue), on the Jimtown Quadrangle map; 
(24) Then southeasterly in a straight line approximately 11,000 feet to the 991-foot peak of Fitch Mountain; 
(25) Then east southeasterly approximately 7,000 feet in a straight line to the peak identified as having an elevation of 857 feet; 
(26) Then east southeasterly approximately 1,750 feet to the peak identified as Black Peak; 
(27) Then southeasterly approximately 7,333 feet to the peak identified as having an elevation of 672 feet; 
(28) Then northeasterly approximately 5,000 feet in a straight line to the point of confluence of Brooks Creek with the Russian River in T. 9 N., R. 8 W., on the Healdsburg Quadrangle map; 
(29) Then east-southeasterly 2,400 feet in a straight line to the top of a peak identified as Chalk Hill; 
(30) Then south from said peak, in a straight line, approximately 0.2 mile to the point where Chalk Hill Road crosses Brooks Creek 
(on the Healdsburg Quadrangle map); 
(31) Then southeasterly, approximately 1.3 miles, along the roadbed of Chalk Hill Road to the point near the confluence of Brooks Creek and Barnes Creek where Chalk Hill Road intersects an unnamed unimproved road 
(known locally as Spurgeon Road) that parallels Barnes Creek in section 32,   T. 9 N., R. 8 W.; 
(32) Then easterly, approximately 0.45 mile, along said road 
(known locally as Spurgeon Road) to the point where the road is intersected by an unnamed unimproved road 
(known locally as the access to the Shurtleff Ranch) in section 33, T. 9 N., R. 8 W.; 
(33) Then continuing along the unnamed unimproved road 
(known locally as the access to the Shurtleff Ranch), approximately 1.33 miles, in a generally easterly direction, to the eastern terminus of said road at a small dwelling along the north fork of Barnes Creek in section 34, T. 9 N., R. 8 W. on the Mark West Springs, California, Quadrangle map; 
(34) Then easterly along the north fork of Barnes Creek, approximately 0.5 mile, to the point in the northeast corner of section 34, T. 9 N., R. 8 W. where the north fork of Barnes Creek intersects the east line of section 34, T. 9 N., R. 8 W.; 
(35) Then north, approximately 0.65 mile, along the east lines of sections 34 and 27, T. 9 N., R. 8 W., to the point at which an unnamed unimproved road which parallels the south bank of Martin Creek intersects the eastern border of section 27, T. 9 N., R. 8 W.; 
(36) Then in a generally northwesterly direction, approximately 1.07 miles, along said road to the point at which the road is crossed by the west line of section 27, T. 9 N., R. 8 W.; 
(37) Then north, approximately 0.08 mile, along the west line of section 27, T. 9 N., R. 8 W., to the southeast corner of section 21, T. 9 N., R. 8 W.; 
(38) Then northerly along the east line of Sections 21, 16, and 9, T. 9 N., R. 8 W. to the northeast corner of Section 9, on the Mount St. Helena Quadrangle map; 
(39) Then westerly along the north line of Section 9 to the northwest corner thereof, on the Jimtown Quadrangle map; 
(40) Then northerly along the western lines of section 4, of T. 9 N, R. 8 W., and sections 33, 28, 21, 16, and 9 of T. 10 N., R. 8 W.; 
(41) Then westerly along the northern lines of section 8 and 7, T. 10 N., R. 8 W. and section 12, T. 10 N., R. 9 W. to the southeastern corner of section 2, T. 10 N., R. 9 W.; 
(42) Then northwesterly in a straight line to the eastern line of section 3 at 38 degrees 45 minutes latitude, T. 10 N., R. 9 W.; 
(43) Then westerly along latitude line 38 degrees 45 minutes to the point lying at 122 degrees 52 minutes 30 seconds longitude; 
(44) Then northwesterly in a straight line to the southeast corner of section 4, T. 11 N., R. 10 W., on the Asti, Quadrangle map; 
(45) Then northeasterly in a straight line to the southeast corner of section 34, T. 12 N., R. 10 W.; 
(46) Then north along the east boundary of section 34, T. 12 N., R. 10 W., to the northeast corner of section 34, T. 12 N., R. 10 W.; 
(47) Then west along the north boundaries of sections 34 and 33, T. 12 N., R. 10 W., to the point of beginning.

**Comment by SoominHur** [comment]
Reviewed.
- Edit created date in the attribute table.
- Edit (8) because the node was at the R11W/R10W line's intersection with northwestern corner of Section 5 instead of "intersection with 123° 00 E. longitude.'
- Edit (9) because the line was not "in a straight line ... to the northwest corner of Section 10, T. 10 N., R.10 W. on the Geyserville Quadrangle map."
- After (16) get to the most easterly point of “Olive Hill”, it is unclear from where to start (17) meandering the west fork of Wood Creek. "dry_creek_valley #63" has same exact description with (16) and (17), which are (7) and (9). But unlike "alexander_valley #13", "dry_creek_valley #63" has (8) "Then S. 2 degrees, E. 3,100 feet in a straight line to the point in the westerly fork of Wood Creek lying at the westerly terminus of a dirt road;" describing from where to start meandering the west fork of Wood Creek. Since "alexander_valley #13" and "dry_creek_valley #63" have similar/close enough description and created date (which are 1984-11-23 and 1983-09-06), I will start to meander the west fork of Wood Creek from where (8) of "dry_creek_valley #63" describes.
- Edit (41) because it was straight line from northeastern corner of section 8 (T10N, R8W) to southeastern corner of section 2 (T10N, R9W) instead of "along the northern lines of section 8 and 7, T. 10 N., R. 8 W. and section 12, T. 10 N., R. 9 W. to the southeastern corner of section 2, T. 10 N., R. 9 W."
- Edit (42) because the line was not "in a straight line to the eastern line of section 3 at 38 degrees 45 minutes latitude, T. 10 N., R. 9 W." but in a straight line to the south-most point of section 3.
- Edit (43) because the line straightly went toward (44) instead of "westerly along latitude line 38 degrees 45 minutes to the point lying at 122 degrees 52 minutes 30 seconds. longitude."
