### ISSUE TITLE
middle_rio_grande_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#130]
# AVA: Middle Rio Grande Valley (middle_rio_grande_valley)

name | value
--- | ---
ava_id | middle_rio_grande_valley
cfr_index | 9.119
revision | [T.D. ATF-266, 52 FR 2836, Feb. 2, 1988]
state | NM
county | Bernalillo|Sandoval|Socorro|Valencia
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Abeytas, N. Mex. 
1952., revised 1979. 
2. Alameda, N. Mex. 
1960., revised 1967 and 1972. 
3. Alburquerque East, N. Mex. 
1960., revised 1967 and 1972. 
4. Albuquerque West, N. Mex. 
1960., revised 1967 and 1972. 
5. Belen, N. Mex. 
1952., revised 1971. 
6. Bernalillo, N. Mex. 
1954., revised 1972. 
7. Dalies, N. Mex. 
1952., revised 1971. 
8. Isleta, N. Mex. 
1952., revised 1967 and 1974. 
9. La Joya, N. Mex. 
1952., revised 1971. 
10. Lemitar, N. Mex. 
1952., revised 1971. 
11. Loma De Las Canas, N. Mex. 
1959., revised 1979. 
12. Loma Machete, N. Mex. 
1954., revised 1972. 
13. Los Griegos, N. Mex. 
1960., revised 1967 and 1972. 
14. Los Lunas, N. Mex. 
1952., revised 1971 and 1974. 
15. Mesa Del Yeso, N. Mex. 
1959.. 
16. Placitas, N. Mex. 
1954.. 
17. San Acacia, N. Mex. 
1952., revised 1971. 
18. San Antonio, N. Mex. 
1948.—15 minute series. 
19. San Felipe Pueblo, N. Mex. 
1954., revised 1978. 
20. Santa Ana Pueblo, N. Mex. 
1954., revised 1978. 
21. Socorro, N. Mex. 
1959., revised 1971. 
22. Tome, N. Mex. 
1952., revised 1979. 
23. Turn, N. Mex. 
1952., revised 1979. 
24. Veguita, N. Mex. 
1952., revised 1979. 
25. Wind Mesa, N. Mex. 
1952., revised 1967.

## Boundary [src]

(1) The beginning point is at the transmission line tower in the middle of Section 34, T14N, R4E of the Santa Ana Pueblo, N. Mex. U.S.G.S. map; 
(2) The boundary follows the power transmission line east for 2.5 miles until it converges with New Mexico State Route 25/Interstate 85 
(now known as Interstate 25) at Sec. 1, T13N, R4E on the San Felipe Pueblo, M. Mex. U.S.G.S. map; 
(3) It follows I-25 southwest for 1.2 miles until it arrives at an unimproved dirt road approx. .2 mile east of Algodones Cemetery, at Sec. 11, T13N, R4E on the Placitas, N. Mex. U.S.G.S. map; 
(4) The boundary follows the unimproved dirt road southeast for 5.5 miles until it meets another unimproved dirt road at Tecolote, NM, south of Sec. 27 and 28, T13N, R5E; 
(5) It travels southwest on the unimproved dirt road .7 mile until it meets NM-44 approx. 100 feet northwest of BM 6,075 in Placitas, NM, at T13N, R5E; 
(6) It then goes southeast on NM-44 for approx. 250 feet until it intersects the 6,100 foot elevation contour line approx. 250 feet southeast of BM 6,075, at T13N, R5E; 
(7) It then travels west for 3.5 miles on the 6,100 feet elevation contour line until it reaches a light-duty road on the Huertas Grant/Cibola National Forest Boundary at Sec. 6, T12N, R5E; 
(8) The boundary runs north to northwest on the light-duty road for approx. .9 mile until it meets NM-44 next to BM 5,875 in Sec. 31, T13N, R5E; 
(9) It travels west 5.2 miles on NM-44 until it arrives at I-25 
(southbound interchange) near the Bernalillo Cemetery at T13N, R4E on the Bernalillo, N. Mex. U.S.G.S. map; 
(10) It proceeds south on I-25 for approx. 8.6 miles until it intersects with NM-556 at the east bound interchange at Sec. 1, T11N, R3E on the Alameda, N. Mex. U.S.G.S. map; 
(11) The boundary goes east approx. 5 miles on NM-556 until it intersects the 106°30  longitude meridian, T11N, R4E; 
(12) Then it goes south on the 106°30  longitude meridian for approx. 4.5 miles until it arrives at Montgomery Blvd. at Sec. 34, T10/11N, R4E; 
(13) The boundary travels west on Montgomery Blvd. for approx. 6.1 miles until it meets the south exit ramp of 1-25 in Sec. 34, T11N, R3E; 
(14) Then it travels south on I-25 for approx. 13.3 miles 
(through Albuquerque, NM) until it intersects with NM-47 at Sec. 6, T8N, R3E on the Isleta, N. Mex. U.S.G.S. map; 
(15) It heads south on NM-47 for approx. 3.2 miles until it converges with the 4,900 foot elevation contour line at Isleta Pueblo, NM, in Sec. 24, T8N, R2E; 
(16) The boundary follows the 4,900 foot elevation contour line south for approx. 25 miles until it arrives at a point north on Madron, NM, at the Atchison, Topeka and Santa Fe Railroad 
(AT&amp;SF RR) tracks, approx. 250 feet east of elevation mark 4,889 feet on the Turn, N. Mex. U.S.G.S. map; 
(17) It then travels north on the AT&amp;SF RR tracks for approx. 350 feet until it intersects NM-47 approx. 350 feet north of elevation mark 4,889 feet; 
(18) The boundary goes southwest on NM-47 
(through Turn, N.M.) for approx. 2.4 miles until it reaches the 106°45  longitude meridian between the Turn, N. Mex. &amp; Vequita, N. Mex. U.S.G.S. maps; 
(19) Then it travels south on the 106°45  longitude meridian for approx. 4.7 miles until it meets the 34°30  latitude parallel on the Veguita, N. Mex. U.S.G.S. map; 
(20) It then proceeds west on the 34°30  latitude parallel for approx. 1 mile until it arrives at NM-47 approx. .75 mile south of San Juan Church; 
(21) Then it moves south on NM-47 for approx. 13.2 miles until it reaches an improved light-duty road at La Joya, NM, approx. 500 feet west of La Joya Cemetery on the La Joya, N. Mex. U.S.G.S. map; 
(22) It then travels south on the improved light-duty road for approx. 450 feet until it intersects another improved light-duty road; 
(23) Then it goes 500 feet west on the improved light-duty road until it reaches a north-south unimproved road at a point approx. .9 mile east of the AT&amp;SF RR tracks; 
(24) The boundary heads south on the unimproved road for approx. 7.9 miles until it reaches the 34°15  latitude parallel on the La Joya, N. Mex. U.S.G.S. map; 
(25) It travels west on the 34°15  latitude parallel for approx. .9 mile until it intersects the 106°52  longitude meridian on the Mesa Del Yeso, N. Mex. U.S.G.S. map; 
(26) It then goes south on the 106°52  longitude meridian for approx. 3.3 miles until it intersects the south section line of Sec. 19, T1S, R1E; 
(27) It then runs east for approx. 1.25 miles until it reaches the east section line 
(marked altitude 5,058 feet) of Sec. 20, T1S, R1E; 
(28) It travels south on the section line for approx. 7.1 miles, until it meets the Grant Boundary at altitude mark 4,734 feet at Sec. 32/33, T2S, R1E on the Loma De Las Canas, N. Mex. U.S.G.S. map; 
(29) It proceeds east on the Grant Boundary for .25 mile until it arrives at the section line 
(Grant Boundary at Sec. 32/33, T2S, R1E; 
(30) The boundary moves south on the Grant Boundary for approx. 5.2 miles until it meets the 
(Grant Boundary) section line near altitude spot 4,702 feet at Sec. 28/29, T3S, R1E; 
(31) The boundary goes west on the section line 
(Grant Boundary) for approx. .25 mile until it arrives at the section line at Sec. 28/29, T3S, R1E; 
(32) Then it moves south on the section line for approx. 5.7 miles until it meets an unimproved dirt road at Bosquecito, N.M. on the west section line of Sec. 9, T4S, R1E on the San Antonio, N. Mex. 
(15 minute series) U.S.G.S. map; 
(33) It heads south on the unimproved dirt road for approx. 2 miles until it changes to a light-duty road at Padilla Ranch in Sec. 21, T4S, R1E; 
(34) It follows the light-duty road for 2.25 miles until it intersects US-380/85, in Sec. 33, T4S, R1E; 
(35) Then it follows US-380/85, first west then it loops north for approx. 8 miles until it meets the 34°00  latitude parallel; 
(36) The boundary moves west on the 34°00  latitude parallel of the Socorro, N. Mex. U.S.G.S. map for approx. .75 mile until it meets the 4,800 foot elevation contour line in Sec. 35; 
(37) It meanders north on the 4,800 foot elevation contour line for approx. 9 miles until it meets the 34°07  latitude parallel; 
(38) It travels east for approx. .2 mile on the 34°07  latitude parallel until it meets I-25 
(US-60/85); 
(39) It goes north on I-25 
(US-60/85) for approx 27.8 miles until it meets the Belen Highline Canal levee approx. 1.6 mile south of San Antonio Church on the Veguita, N. Mex. U.S.G.S. map; 
(40) Then the boundary follows the Belen Highline Canal north for approx. 9.4 miles until it intersects I-25, approx. .5 mile west of Bacaville, NM, on the Belen, N. Mex. U.S.G.S. map; 
(41) Then it travels north on I-25 for approx. 16 miles until it meets the 34°52  latitude parallel on the Isleta, N. Mex. U.S.G.S. map; 
(42) The boundary goes west on the 34°52 30  latitude parallel for approx. 1 mile until it arrives at the 106°45  longitude meridian; 
(43) Then it moves north on the 106°45  longitude meridian for approx. 16.5 miles until it reaches the 35°07  longitude meridian on the Albuquerque West, N. Mex. U.S.G.S. map; 
(44) At this point it heads east for approx. 1.2 miles along the 35°07  latitude parallel until it reaches the power transmission line towers at Sec. 3/4, T10N, R2E of the Los Griegos, N. Mex. U.S.G.S. map; and finally 
(45) From there it follows the power transmission line towers 
(and for 1 mile along a connecting unimproved road) north and northeast for a total of approx. 24.4 miles to the point of beginning at Sec. 34, T14N, R4E, of the Santa Ana Pueblo, N. Mex. U.S.G.S. map.

**Comment by APRios** [comment]
I will begin digitizing MRGV AVA

**Comment by MicheleTobias** [comment]
Welcome! Please don't hesitate to ask any questions about our process with this project or for clarification about any of the descriptions.

**Comment by APRios** [comment]
Thank you. Greeting from Albuquerque, NM. New to GitHub workflow, so it will be a learning process. Comfortable with QGIS, PLSS descriptions, and the Middle Rio Grande Valley.

**Comment by APRios** [comment]
Progress report: have completed boundary through description number 36. 37 through 45 remain. No troubles to date with description or digitizing.
