### ISSUE TITLE
mimbres_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#131]
# AVA: Mimbres Valley (mimbres_valley)

name | value
--- | ---
ava_id | mimbres_valley
cfr_index | 9.103
revision | [T.D. ATF-217, 50 FR 48081, Nov. 21, 1985]
state | NM
county | Grant|Luna
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Akela, N. Mex.,” 7.5 minute series, edition of 1972; 
2. “Antelope Hill, N. Mex.,” 7.5 minute series, edition of 1963 
photoinspected 1974.; 
3. “Bisbee Hills, N. Mex.,” 7.5 minute series, edition of 1965; 
4. “Bowlin Ranch, N. Mex.,” 7.5 minute series, edition of 1965; 
5. “Capital Dome, N. Mex.,” 7.5 minute series, edition of 1965; 
6. “Carne, N. Mex.,” 7.5 minute series, edition of 1965; 
7. “Columbus, N. Mex.,” 7.5 minute series, edition of 1965; 
8. “Columbus NE, N. Mex.,” 7.5 minute series, edition of 1966; 
9. “Columbus SE, N. Mex.,” 7.5 minute series, edition of 1966; 
10. “Deming East, N. Mex.,” 7.5 minute series, edition of 1965; 
11. “Deming West, N. Mex.,” 7.5 minute series, edition of 1964 
photoinspected 1972.; 
12. “Dwyer, N. Mex.,” 15 minute series, edition of 1956; 
13. “Faywood Station, N. Mex.,” 7.5 minute series, edition of 1947; 
14. “Florida Gap, N. Mex.,” 7.5 mintue series, edition of 1964; 
15. “Goat Ridge, N. Mex.,” 7.5 minute series, edition of 1964; 
16. “Gym Peak, N. Mex.,” 7.5 minute series, edition of 1964; 
17. “Hermanas, N. Mex.,” 7.5 minute series, edition of 1964; 
18. “Malpais Hill, N. Mex.,” 7.5 minute series, edition of 1965; 
19. “Midway Butte, N. Mex.,” 7.5 minute series, edition of 1965; 
20. “Myndus, N. Mex.,” 7.5 minute series, edition of 1972; 
21. “North Peak, N. Mex.,” 7.5 minute series, edition of 1965; 
22. “Red Mountain, N. Mex.,” 7.5 minute series, edition of 1965; 
23. “San Lorenzo, N. Mex.,” 15 minute series, edition of 1956; 
24. “Sibley Hole, N. Mex.,” 7.5 minute series, edition of 1972; 
25. “South Peak, N. Mex.,” 7.5 minute series, edition of 1965; 
26. “Spalding, N. Mex.,” 7.5 minute series, edition of 1964; 
27. “West Lime Hills, N. Mex.,” 7.5 minute series, edition of 1965; and 
28. “Williams Ranch, N. Mex.,” 7.5 minute series, edition of 1964.

## Boundary [src]

(1) From the beginning point the boundary runs northeast 2.25 miles along an unimproved dirt road until it intersects U.S. Routh 180 
(indicated on map as U.S. Rte. 260) at New Mexico Highway 61 
(indicated on map as an unnumbered secondary highway) at the south portion of Sec. 30, T20S/R11W; 
(2) The boundary proceeds in a generally northerly direction on N.M. Hwy. 61 for 34.5 miles crossing over U.S. Rte. 90 
(indicated on map as U.S. Rte. 180) west of San Lorenzo, N.M. until it meets an unimproved dirt road near Bear Canyon Dam at the west line of Sec. 28, T16S/R11W on the San Lorenzo, N. Mex. U.S.G.S. map; 
(3) It then heads east on the unimproved dirt road for .2 mile until it meets the Mimbres River at Sec. 28, T16S/R11W; 
(4) It then goes south on the Mimbres River for .25 mile until it intersects the 6,000 foot elevation contour line at Sec. 28, T16S/R11W; 
(5) From there the boundary runs south along the 6,000 foot elevation contour line until it meets the east line of Sec. 11, T17S/R11W; 
(6) Then it proceeds south on the section line for .6 mile until it hits the south line of Sec. 12, T17S/R11W; 
(7) Then it travels east on the section line for 1.8 miles until it intersects an unimproved dirt road in Noonday Canyon on the north line of Sec. 18, T17S/R10W; 
(8) It then heads south on the unimproved dirt road for 2.2 miles until it intersects a medium duty road at the northern part of Sec. 30, T17S/R10W; 
(9) The boundary goes south on the medium duty road for .8 mile until it reaches the north line of Sec. 31, T17S/R10W; 
(10) The boundary goes east 5 miles on the section line to the east line of Sec. 36, T17S/R10W; 
(11) The boundary proceeds south on the section line for 13 miles to the south line of Sec. 36 
(also indicated on map as Luna/Grant Country line), T19S/R10W on the Dwyer, N. Mex. U.S.G.S. map; 
(12) The boundary travels west on the Luna/Grant County line for three miles to the east line of Sec. 4, T20S/R10W; 
(13) The boundary goes south on the section line for three miles to the south line of Sec. 16, T20S/R10W; 
(14) Then it goes west on the section line for approximately .6 mile to a light duty road located 500 feet south of Benchmark 5119 on the south line of Sec. 16, T20S/R10W; 
(15) The boundary heads south on the light duty road for approximately 10.25 miles until it meets Hwy. 180 at Benchmark 4672 near the west line of Sec. 9, T22S/R10W on the Spalding, N. Mex. U.S.G.S. map; 
(16) Then it proceeds southeasterly on Hwy. 180 for approximately 5 miles to the north line of Sec. 6, T23S/R9W on the Deming West, N. Mex. U.S.G.S. map; 
(17) It then goes east on the section line approximately 11.75 miles to the east line of Sec. 1, T23S/R8W on the Carne, N. Mex. U.S.G.S. map; 
(18) It then travels south on the section line for 1.5 miles until it meets an unimproved dirt road at Sec. 12, T23S/R8W; 
(19) It follows the unimproved dirt road in an easterly direction for 3 miles to Carne Windmill at the northeast part of Sec. 17, T23S/R7W; 
(20) From there it follows an unimproved dirt road in a southeasterly direction for .75 mile until it meets the south line of Sec. 16, T23S/R7W; 
(21) Then it proceeds east along the section line for 9 miles until it arrives at the east line of Sec. 24, T23S/R6W on the Myndus, N. Mex. U.S.G.S. map; 
(22) Then it goes south on the section line for 15 miles until it meets the south line of Sec. 36, T25S/R6W on the Sibley Hole, N. Mex. U.S.G.S. map; 
(23) Then it heads west on the section line for 8 miles until it intersects the 4,200 foot elevation contour line at the southeast corner of Sec. 34, T25S/R7W on the Gym Peak, N. Mex. U.S.G.S. map; 
(24) Then it heads north on the 4,200 foot elevation contour line for 11 miles until it meets N.M. Hwy. 549 
(indicated on map as U.S. Rte. 70/80/180) at the southwest corner of Sec. 5, T24S/R7W on the Florida Gap, N. Mex. U.S.G.S. map; 
(25) The boundary heads west on M.M. Hwy. 549 
(indicated on map as U.S. Rte. 70/80/180) for 4.5 miles until it meets the light duty road at the east line of Sec. 3, T24S/R8W on the Capital Dome, N. Mex. U.S.G.S. map; 
(26) It then goes south on the light duty road/section line for 4 miles until it meets another light duty road at the south line of Sec. 22, T24S/R8W; 
(27) Then the boundary heads west for 2 miles on the light duty road/section line until it intersects an unimproved dirt road at the east line of Sec. 29, T24S/R8W; 
(28) Then it travels south on the unimproved dirt road/section line for 2 miles until it meets another unimproved dirt road at the south line of Sec. 32, T24S/R8W; 
(29) It then moves west .25 mile on the unimproved dirt road until it reaches the east line of Sec. 5, T25S/R8W; 
(30) Then it goes south on the section line for 6 miles until it reaches an unimproved dirt road near Crawford Ranch at the north line of Sec. 5, T25S/R8W on the South Peak, N. Mex. U.S.G.S. map; 
(31) Then it follows the unimproved dirt road in a southwest then southern direction for approximately 3 miles until it hits the north line of Sec. 19, T26S/R8W; 
(32) It then travels east for 1.1 mile along the section line until it hits the east line of Sec. 20, T26S/R8W; 
(33) From there it proceeds south for 2 miles on the section line until it intersects the north line of Sec. 33, T26S/R8W; 
(34) It then heads east for 5 miles on the section line until it intersects the east line of Sec. 31, T26S/R7W on the Gym Peak, N. Mex. U.S.G.S. map; 
(35) The boundary goes south on the section line for 7 miles until it meets the north line of Sec. 5 
(which also is a light duty road), T28S/R7W on the Columbus NE, N. Mex. U.S.G.S. map; 
(36) Then it goes east for 4 miles on the section line until it meets the east line of Sec. 2 near Oney Tank T28S/R7W; 
(37) Then it goes south on the section line for 8.7 miles until it meets the New Mexico, U.S.A./Mexico International border at the east line of Sec. 17, T29S/R7W on the Columbus SE, N. Mex. U.S.G.S. map; 
(38) The boundary follows in a westerly direction along the International border for 23 miles to the west line of Sec. 18, T29S/R10W on the Hermanas, N. Mex. U.S.G.S. map; 
(39) It then heads north on the western section for 3.5 miles to the north line of Sec. 31, T28S/R10W; 
(40) It then moves east for 13 miles on the section line until it intersects the east line of Sec. 32, T28S/R8W on the Columbus, N. Mex. U.S.G.S. map; 
(41) Then it follows the section line north for 8 miles until it meets the south line of Sec. 18, T27S/R8W on the North Peak, N. Mex. U.S.G.S. map; 
(42) Then it proceeds west on the section line for 11 miles to the west part of Sec. 16 identified as longitude point 107 degrees, 52 minutes, 30 seconds, T27S/R10W on the West Lime Hills, N. Mex. U.S.G.S. map; 
(43) Then it moves north on the 107 degrees, 52 minutes, 30 seconds longitude point for 9 miles until it intersects the north line of Sec. 4, T26S/R10W on the Midway Butte, N. Mex. U.S.G.S. map; 
(44) Then it goes west on the section line for 6.5 miles until it meets the west line of Sec. 33, T25S/R11W on the Bisbee Hills, N. Mex. U.S.G.S. map; 
(45) The boundary then travels north on the section line for 26.5 miles 
(crossing the Southern Pacific Railroad tracks) until it intersects with the Atchison, Topeka and Santa Fe Railroad tracks on the west line of Sec. 21, T21S/R11W on the Spalding, N. Mex. U.S.G.S. map; 
(46) Finally it follows the Atchison, Topeka and Santa Fe Railroad tracks in a northwesterly direction for 5 miles until it reaches the beginning point at benchmark 4911 on an unimproved dirt road in Faywood Station at Sec. 2, T21S/R12W on the Faywood Station, N. Mex. U.S.G.S. map.

**Comment by APRios** [comment]
Hello. I would like to begin digitizing Mimbres Valley.

**Comment by MicheleTobias** [comment]
Enjoy! I'll mark it as in progress.

**Comment by APRios** [comment]
Thank you.

**Comment by ericallanwest** [comment]
@APRios If you are open to collaborating, I have time to help digitize this one. I could start in the middle (perhaps Step 24) and work back around to the beginning point. Once I am done, I can send my part of the boundary, which you could then combine with your part.

**Comment by APRios** [comment]
Hello Eric. I am making slow but good progress with Mimbres Valley. Would you be willing to digitize Mesilla Valley AVA? That would complete the AVA's for New Mexico once Mimbres and Mesilla are complete.

**Comment by MicheleTobias** [comment]
Hi Arturo!  There's no rush to get it done, so take your time.  I think there's plenty of other data that Eric can work on.  The New Mexico AVAs look particularly complex.

**Comment by ericallanwest** [comment]
Arturo, I have already completed Mesilla Valley. That is why I am able to help with Mimbres Valley. I completely understand if you want to complete Mimbres Valley on your own.

**Comment by APRios** [comment]
Thanks Michele. I will continue working on Mimbres Valley. Eric, you may want to submit a pull request to get Mesilla Valley evaluated and taken off the Issues Tracker. Good Luck.

**Comment by MicheleTobias** [comment]
Thanks, Arturo! Eric has submitted a pull request.  I've got a back-log of pull requests to approve.  Things have been busy lately.  : )
