### ISSUE TITLE
mississippi_delta

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#132]
# AVA: Mississippi Delta (mississippi_delta)

name | value
--- | ---
ava_id | mississippi_delta
cfr_index | 9.96
revision | [T.D. ATF-181, 49 FR 34354, Aug. 30, 1984]
state | MS|LA|TN
county | 
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Helena, scale of 1:250,000, 1955 
revised 1977.. 
2. Greenwood, scale of 1:250,000, 1953 
revised 1979.. 
3. Jackson, scale of 1:250,000, 1955 
revised 1973..

## Boundary [src]
General.  The Mississippi Delta viticultural area is located in Mississippi, Louisiana, and Tennessee. The starting point of the following boundary description is the intersection of the Illinois Central Gulf 
(I.C.G.) Railroad and the Mississippi River levee system, on the southeast side of Lake Horne, between Lake View, Mississippi, and Walls, Mississippi, on the Helena map. Boundary Description.  
(i) From the starting point generally southward along the Mississippi River levee system until it again intersects the I.C.G. Railroad, near Twin Lake, Mississippi 
(about 10 miles north of Vicksburg, on the Jackson map). In any place where there is more than one continuous levee, the one closest to the Mississippi River is the boundary. 
(ii) From the intersection described in paragraph 
(c)
(2)
(i), the boundary continues southward along the I.C.G. tracks, until they merge with another branch of the I.C.G. Railroad, near Redwood, Mississippi. 
(iii) Then generally northeastward along that other branch of the I.C.G. Railroad, to the Leflore County-Holmes County line 
(on the Greenwood map). 
(iv) Then southeastward along that county line to the Leflore County-Carroll County line. 
(v) Then generally northward along that county line to Mississippi Route 7. 
(vi) Then generally northeastward along Route 7 to the 90°00  longitude line. 
(vii) Then northward along that longitude line to Mississippi Route 8. 
(viii) Then eastward along Route 8 to Mississippi Route 35. 
(ix) Then northward along Route 35 to Mississippi Route 322 
(on the Helena map). 
(x) Then generally eastward along Route 322 to the Panola Quitman Floodway. 
(xi) Then northward along that floodway to the range line R.9W./R.8W. 
(xii) Then northward along that range line to the 200 ft. contour line 
(north of Ballentine, Mississippi). 
(xiii) Then generally northeastward along that contour line to Mississippi Route 3. 
(xiv) Then northward along Route 3 to the Tunica County-Tate County line. 
(xv) Then northward along that county line to the Tunica County-De Soto County line. 
(xvi) Then northward along that county line to the I.C.G. Railroad. 
(xvii) Then northward along the I.C.G. tracks to the starting point.

**Comment by amgard** [comment]
I'm going to start working on this ava

**Comment by amgard** [comment]
@micheletobias I'm having trouble following the description to go east to Panola Quitman Floodway. From intersect of 35 and 322, it is west. I checked original source description and it still has this discrepancy - I checked to make sure I was digitizing on the correct maps and they are okay. Do you have any suggestions on how to proceed?

**Comment by amgard** [comment]
![1](https://user-images.githubusercontent.com/46685046/53196035-d635e400-35cb-11e9-94cb-50be62e703b3.PNG)

**Comment by amgard** [comment]
![2](https://user-images.githubusercontent.com/46685046/53196044-ddf58880-35cb-11e9-9627-1d482a0bbc63.PNG)

**Comment by MicheleTobias** [comment]
I suspect the person writing the description meant to say "westward".  We've seen this in a handful of other descriptions where the writer gets their cardinal directions mixed up.  The only way I can see to make this description work is to go west along highway 322.

**Comment by amgard** [comment]
That is what I was thinking. Thanks! I will assume "westward"
