### ISSUE TITLE
mokelumne_river

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#133]
# AVA: Mokelumne River (mokelumne_river)

name | value
--- | ---
ava_id | mokelumne_river
cfr_index | 9.200
revision | [T.D. TTB-50, 71 FR 40414, July 17, 2006]
state | CA
county | San Joaquin
within | Lodi
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Lodi South, Calif., 1968, photorevised 1976; 
2. Terminous, Calif., 1978, minor revision 1993; 
3. Thornton, Calif., 1978; 
4. Bruceville, Calif., 1968, photorevised 1980; 
5. Lodi North, Calif., 1968, photorevised 1976; 
6. Lockeford, Calif., 1968, photorevised 1979, minor revision 1993; and 
7. Waterloo, Calif., edition of 1968, photoinspected 1978.

## Boundary [src]

(1) The beginning point is on the Lodi South map at the intersection of Eightmile Road and Interstate 5, section 36 south boundary line, T3N, R5E. From the beginning point, proceed north-northwest 14.7 miles on Interstate 5, crossing over the Terminous and Thornton maps, to the Interstate&#39;s intersection with the Mokelumne River, T5N, R6E 
(Bruceville Quadrangle); then 
(2) Proceed southeast 
(upstream) 5 miles along the meandering Mokelumne River to its intersection with Peltier Road, section 16, T4N, R6E 
(Lodi North Quadrangle); then 
(3) Proceed east 8.3 miles along Peltier Road to its intersection with Elliott Road at the northeast corner of section 23, T4N, R7E 
(Lockeford Quadrangle); then 
(4) Proceed south then southeast 2.3 miles on Elliott Road to its intersection with Jack Tone Road in the village of Lockeford 
(where Jack Tone Road is known as E. Hammond Street for a short distance), section 30, T4N, R8E 
(Lockeford Quadrangle); then 
(5) Proceed south 6.7 miles on Jack Tone Road to its intersection with the Calaveras River, section 36 east boundary line, T3N, R7E 
(Waterloo Quadrangle); then 
(6) Proceed southwesterly 
(downstream) 0.9 mile along the meandering Calaveras River to its intersection with Eightmile Road, section 36 south boundary line, T3N, R7E 
(Waterloo Quadrangle); and 
(7) Proceed west 8.6 miles on Eightmile Road, returning to the beginning point.

**Comment by MicheleTobias** [comment]
I'm working on this one.

**Comment by SoominHur** [comment]
Continue Reviewing
- Add scale information of used maps in the attribute table.
