### ISSUE TITLE
monterey

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#134]
# AVA: Monterey (monterey)

name | value
--- | ---
ava_id | monterey
cfr_index | 9.98
revision | [T.D. ATF-178, 49 FR 24718, June 15, 1984, as amended by T.D. ATF-249, 52 FR 5960, Feb. 27, 1987]
state | CA
county | Monterey
within | Central Coast
contains | Arroyo Seco\|Hames Valley\|San Bernabe\|San Lucas\|Santa Lucia\|Highlands

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Sycamore Flat, CA, 1956, photoinspected 1972; 
2. Junipero Serra Peak, CA, 1949, photoinspected 1972; 
3. Reliz Canyon, CA, 1949; 
4. Paraiso Springs, CA, 1956; 
5. Thompson Canyon, CA, 1949, photo-revised 1979; 
6. Cosio Knob, CA, 1948, photoinspected 1976; 
7. Espinosa Canyon, CA, 1948; 
8. San Ardo, CA, 1967; 
9. Hames Valley, CA, 1949; 
10. Tierra Redonda Mtn., CA, 1948; 
11. Bradley, CA, 1949; 
12. Wunpost, CA, 1948; 
13. Pancho Rico Valley, CA, 1967; 
14. Nattras Valley, CA, 1967; 
15. San Lucas, CA, 1949; 
16. Pinalito Canyon, CA, 1969; 
17. North Chalone Peak, CA, 1969; 
18. Soledad, CA, 1955; 
19. Mount Johnson, CA, 1968; 
20. Gonzales, CA, 1955; 
21. Mt. Harlan Quadrangle, CA, 1968; 
22. Natividad Quadrangle, CA, 1947, photo-revised 1968, photoinspected 1974; 
23. San Juan Bautista Quadrangle, CA, 1955, photo-revised 1980; 
24. Prunedale Quadrangle, CA, 1954, photo-revised 1981; 
25. Watsonville East Quadrangle, CA, 1955, photo-revised 1980; 
26. Watsonville West Quadrangle, CA, 1954, photo-revised 1980; 
27. Moss Landing Quadrangle, CA, 1954, photo-revised 1980; 
28. Marina Quadrangle, CA, 1947, photo-revised 1968 and 1974; 
29. Monterey, CA, 1947, photo-revised 1968, photoinspected 1974; 
30. Mt. Carmel, CA, 1956, photoinspected 1972; 
31. Carmel Valley, CA, 1956, photoinspected 1974; 
32. Spreckels, CA, 1947, photo-revised 1968, photoinspected 1975; 
33. Chualar, CA, 1947, photo-revised 1968, photoinspected 1974; 
34. Rana Creek, CA, 1956, photoinspected 1973; and 
35. Palo Escrito Peak, CA, 1956; 
36. Greenfield, CA, 1956; 
37. Salinas, CA, 1947 
photorevised 1975.; and 
38. Seaside, CA, 1947 
photorevised 1968, photoinspected 1974..

## Boundary [src]

(1) The beginning point is found on the “Sycamore Flat” U.S.G.S. 7.5 minute map at the junction of Arroyo Seco Road and the Jamesburg Road, in the southeast corner of section 21, T
(ownship) 19 S., R
(ange) 5 E. 
(This is also the beginning point for the Arroyo Seco viticultural area.) 
(2) The boundary proceeds directly west along the southern boundary of section 21 to the southwest corner of section 21, T. 19 S., R. 5 E. 
(3) Then southeast in a straight diagonal line across section 28 to the southeast corner of section 28, T. 19 S., R. 5 E. 
(4) Then directly east along the southern boundaries of sections 27, 26 and 25 in T. 19 S., R. 5 E., sections 30, 29, 28, 27, 26 and 25 in T. 19 S., R. 6 E., and sections 30, 29, and 28 in T. 19 S., R. 7 E. to the southeast corner of section 28, T. 19 S., R. 7 E. 
(5) Then south along the eastern boundary of section 33 to the southeast corner of section 33, T. 19 S., R. 7 E. 
(6) Then southeast in a straight diagonal line across section 3 to the southeast corner of section 3, T. 20 S., R. 7 E. 
(7) Then south southeast in a straight diagonal line across sections 11 and 14 to the southeast corner of section 14, T. 20 S., R. 7 E. 
(8) Then south along the western boundaries of sections 24 and 25 to the southwest corner of section 25, T. 20 S., R. 7 E. 
(9) Then east along the southern boundaries of sections 25 and 30 to the southeast corner of section 30, T. 20 S., R. 8 E. 
(10) Then southwest in a straight diagonal line across section 31 to the southwest corner of section 31, T. 20 S., R. 8 E. 
(11) Then west along the southern boundary of section 36, T. 20 S., R. 7 E., to the northwest corner of section 6, T. 21 S., R. 8 E. 
(12) Then south along the western boundaries of sections 6 and 7 to the southwest corner of section 7, T. 21 S., R. 8 E. 
(13) Then west along the northern boundary of section 13 to the northwest corner of section 13, T. 21 S., R. 7 E. 
(14) Then south along the western boundaries of sections 13 and 24 to the southwest corner of section 24, T. 21 S., R. 7 E. 
(15) Then east northeast in a straight diagonal line across section 24, T. 21 S., R. 7 E., and across section 19, T. 21 S., R. 8 E., to the northeast corner of section 19, T. 21 S., R. 8 E. 
(16) Then northeast in a straight diagonal line across section 17 to the northeast corner of section 17, T. 21 S., R. 8 E. 
(17) Then southeast in a straight diagonal line across sections 16, 22, 26 and 36 in T. 21 S., R. 8 E. and across sections 6, 8, and 16 in T. 22 S., R. 9 E. to the southeast corner of section 16, T. 22 S., R. 9 E. 
(18) Then east southeast in a straight diagonal line across sections 22, 23, 24, T. 22 S., R. 9 E., and across section 19, T. 22 S., R. 10 E., to the southeast corner of section 19, T. 22 S., R. 10 E. 
(19) Then south southeast in a straight diagonal line across sections 29, 32, and 33, T. 22 S., R. 10 E., to the southeast corner of section 4, T. 23 S., R. 10 E. 
(20) Then south southeast in a straight diagonal line across sections 10, 15, 23, and 26 to the southeast corner of section 26, T. 23 S., R. 10 E. 
(21) Then northwest in a straight diagonal line across section 26 to the northwest corner of section 26, T. 23 S., R. 10 E. 
(22) Then west northwest in a straight diagonal line across sections 22, 21, 20, and 19, T. 23 S., R. 10 E. to the northwest corner of section 24, T. 23 S., R. 9 E. 
(23) Then southeast across sections 24, 25, 30, 31, and 32, to the southeast corner of section 5, T. 24 S., R. 10 E. 
(24) Then east southeast in a straight diagonal line across section 9 to the southeast corner of section 10, T. 24 S., R. 10 E. 
(25) Then south southeast in a straight diagonal line across section 14 to the southeast corner of section 23, T. 24 S., R. 10 E. 
(26) Then southwest in a straight diagonal line to the southwest corner of section 26, T. 24 S., R. 10 E. 
(27) Then south along the western boundary of section 35 to the southwest corner of section 35, T. 24 S., R. 10 E. 
(28) Then east along the southern boundaries of sections 35 and 36 to the southeast corner of section 36, T. 24 S., R. 10 E. 
(29) Then north along the eastern boundaries of sections 36 and 25 to the northeast corner of section 25, T. 24 S., R. 10 E. 
(30) Then northeast in a straight diagonal line across sections 19, 18, and 17 to the northeast corner of section 8, T. 24 S., R. 11 E. 
(31) Then west northwest in a straight diagonal line across section 5 to the northwest corner of section 6, T. 24 S., R. 11 E. 
(32) Then north along the line separating Range 10 E. and Range 11 E. along the eastern boundary lines of sections 36, 25, 24, 13, 12 and 1 in Township 23 S., and along the western boundaries of sections 36, 25, 24, 13, 12 and 1 in Township 22 S., to the northeast corner of section 36, T. 21 S., R. 10 E. 
(33) Then west northwest in a straight diagonal line across sections 25, 26, 23, 22, 15, 16 and 9 to the northwest corner of section 8, T. 21 S., R. 10 E. 
(34) Then northwest in a straight diagonal line to the northwest corner of section 6, T. 21 S., R. 10 E. 
(35) Then west along the northern boundary of section 1, T. 21 S., R. 9 E. to the southeast corner of section 36, T. 20 S., R. 9 E. 
(36) Then northwest in a straight diagonal line across sections 36, 26, 22, 16, 8, and 6 in T. 20 S., R. 9 E. to the northwest corner of section 6, T. 20 S., R. 9 E. 
(37) Then north along the line separating Range 8 E. and Range 9 E. along the western boundaries of sections 36, 25, 24, 13, 12, and 1, T. 19S., R. 8 E. to the northeast corner of section 1, T. 19 S., R. 9 E. 
(38) Then northwest in a straight diagonal line to the point of intersection of the boundary line separating R. 7 E. and R. 8 E. and the boundary line separating T. 17 S. and T. 18 S. 
(39) Then west along the northern boundaries of sections 1 and 2 to the northwest corner of section 2, T. 18 S., R. 7 E. 
(40) Then northwest in a straight diagonal line across section 34 to the northwest corner of section 34, T. 17 S., R. 7 E. 
(41) Then west along the southern boundaries of sections 28 and 29 to the southwest corner of section 29, T. 17 S., R. 7 E. 
(42) Then northwest in a straight diagonal line across sections 30, 24, 14, 10 and 4 to the northwest corner of section 4, T. 17 S., R. 6 E. 
(43) Then north northeast in a straight line across the easternmost portion of section 32 to the northeast corner of section 32, T. 16 S., R. 6 E. 
(44) Then north along the eastern boundary of section 29 to the northeast corner of section 29, T. 16 S., R. 6 E. 
(45) Then northwest in a straight diagonal line across section 20 to the northwest corner of section 20, T. 16 S., R. 6 E. 
(46) Then west northwest in a straight diagonal line across sections 18 and 13 to the northwest corner of section 13, T. 16 S., R. 5 E. 
(47) Then north northwest in a straight diagonal line across sections 11 and 2 to the northwest corner of section 2, T. 16 S., R. 5 E. 
(48) Then west along the southern boundaries of section 34 and 33 to the southwest corner of section 33, T. 15 S., R. 5 E. 
(49) Then north along the western boundary of section 33, T. 15 S., R. 5 E., in a straight line for approximately 0.5 mile to the intersection with the Chualar Land Grant boundary at the northwestern corner of section 33, T. 15 S., R. 5 E. 
(50) Then northeast in a straight diagonal line across the Chualar Land Grant and section 27 to the northeast corner of section 27, T. 15 S., R. 5 E. 
(51) Then northwest in a straight diagonal line across section 22 to the northwest corner of section 22, T. 15 S., R. 5 E. 
(52) Then west in a straight line along the southern boundaries of sections 16 and 17, T. 15 S., R. 5 E., to the southwest corner of section 17 where it intersects with the Encinal Y Buena Esperanza Land Grant boundary. 
(53) Then north and then west along the eastern boundary of the Encinal Y Buena Esperanza Land Grant and the western boundaries of sections 21, 17, 8, and 7, T. 15 S., R. 5 E. 
(54) Then in a straight line from the northwest corner of the Encinal Y Buena Esperanza Land Grant boundary and section 7, T. 15 S., R. 5 E. in a west northwest direction to the point where the power transmission line 
(with located metal tower) intersects at the western boundary of the Cienega del Gabilan Land Grant and the eastern boundary of the El Alisal Land Grant, T. 14 S., R. 4 E. 
(55) Then north and then northwest along the boundary line between the Cienega del Gabilan Land Grant and El Alisal Land Grant to the westernmost corner of the Cienega del Gabilan Land Grant, T. 14 S., R. 4 E. 
(56) Then west along the boundary line between the Sausal Land Grant and La Natividad Land Grant to the point where the boundary line intersects Old Stage Road. 
(57) Then north along Old Stage Road to the point where Old Stage Road intersects the Monterey County—San Benito County line, T. 13 S., R. 4 E. 
(58) Then northwest along the Monterey County—San Benito County line to the point near the Town of Aromas where the boundary lines of the counties of Monterey, Santa Cruz, and San Benito meet, T. 12 S., R. 3 E. 
(59) Then in a meandering line along the Monterey County—Santa Cruz County line east then southeast to the Pacific Ocean, T. 12 S., R. 1 E. 
(60) Then south along the coastline of Monterey Bay to its intersection with the northwesternmost boundary of Fort Ord Military Reservation, T. 14 S., R. 1 E. 
(61) Then following the boundry line of the Fort Ord Military Reservation in an irregular line generally east, then south, then west to the point where the boundary line of the military reservation meets the Pacific Ocean, T. 15 S., R. 1 E. 
(62) Then following the coastline of the Monterey Peninsula south along the coastline of Carmel Bay to Carmel Point, the northwesternmost point of Point Lobos State Reserve on the Carmel Peninsula. 
(63) Then southeast in a straight diagonal line to the southwestern corner of section 25, T. 16 S., R. 1 W. 
(64) Then east along the southern boundaries of section 25, T. 16 S., R. 1 W., and sections 30 and 29, T. 16 S., R. 1 E., to the southeastern corner of section 29 where it intersects with the southwestern boundary of the El Potrero de San Carlos Land Grant. 
(65) Then southeast along the southwestern boundary line of the El Potrero de San Carlos Land Grant to the southeastern corner of section 33, T. 16 S., R. 1 E. 
(66) Then east along the line separating Township 16 S. and Township 17 S. and across Pinyon Peak to the southeast corner of section 32, T. 16 S., R. 2 E. 
(This is the beginning and ending point of the boundary of Carmel Valley viticultural area.) 
(67) Then continuing east along the line separating Township 16 S. from Township 17 S. to its point of intersection with the line separating Range 2 E. and Range 3 E. 
(68) Then north along the western boundaries of sections 31, 30, 19, 18, 7 and 6 in T. 16 S., R. 3 E. to the southwestern corner of section 31, T. 15 S., R. 3 E. 
(69) Then in a straight diagonal line east northeast across sections 31, 32 and 33, T. 15 S., R. 3 E. to the southeast corner of section 28, T. 15 S., R. 3 E. 
(70) Then southeast in a straight diagonal line along the eastern boundaries of sections 33 and 34, T. 15 S., R. 3 E., and sections 3, 2, 12, 16, 20, 21, and 28, T. 16 S., R. 4 E., to the point where the eastern boundary line of section 28 intersects the boundary line of the Guadalupe Y Llanitos de Los Correos Land Grant. 
(71) Then south to the southwest corner of section 34, T. 16 S., R. 4 E. 
(72) Then east to the northwest corner of section 2, T. 17 S., R. 4 E. 
(73) Then south along the eastern boundary of section 3 to the southeast corner of section 3, T. 17 S., R. 4 E. 
(74) Then southeast in a straight diagonal line across sections 11, 13, 19, and 29, to the southeast corner of section 29, T. 17 S., R. 5 E. 
(75) Then south along the western boundary of section 33 to the southwest corner of section 33, T. 17 S., R. 5 E. 
(76) Then east along the southern boundary of section 33 to the northeast corner of section 4, T. 18 S., R. 5 E. 
(77) Then southeast in a diagonal line acros sections 3 and 11 to the southeast corner of section 11, T. 18 S., R. 5 E. 
(78) Then south along the western boundary of section 13 to the southwest corner of section 13, T. 18 S., R. 5 E. 
(79) Then southeast in a diagonal line across section 24 to the southeast corner of section 24, T. 18 S., R. 5 E. 
(80) Then south along the western boundaries of section 30 and 31 to the southwest corner of section 31, T. 18 S., R. 6 E. 
(81) Then east along the southern boundaries of sections 31 and 32 to the southeast corner of section 32, T. 18 S., R. 6 E. 
(From this point, the Monterey and Arroyo Seco viticultural areas share the same boundary lines.) 
(82) Then south along the eastern boundaries of sections 5, 8, and 17 to Arroyo Seco Road, T. 19 S., R. 6 E. 
(83) Then southwest in a straight line for approximately 1.0 mile to Benchmark 673, T. 19 S., R. 6 E. 
(84) Then west in a straight line for approximately 1.8 miles to Bench Mark 649. 
(85) Then northwest in a straight line for approximately 0.2 mile to the northeast corner of section 23, T. 19 S., R. 5 E. 
(86) Then west following the northern boundaries of sections 23 and 22 to the northwest corner of section 22, T. 19 S., R. 5 E. 
(87) Then south in a straight line along the western boundary of section 22 to the point of beginning.

**Comment by MicheleTobias** [comment]
I'm working on this one.

**Comment by MicheleTobias** [comment]
I checked the whole boundary really carefully on this one and corrected a self-intersection caused by the boundary description.  Extending the boundary along the coast just past Carmel Point made the line not cross over itself.
