### ISSUE TITLE
monticello

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#135]
# AVA: Monticello (monticello)

name | value
--- | ---
ava_id | monticello
cfr_index | 9.48
revision | [T.D. ATF-164, 49 FR 2758, Jan. 23, 1984, as amended by T.D. ATF-249, 52 FR 5957, Feb. 27, 1987; T.D. ATF-255, 52 FR 23652, June 24, 1987]
state | VA
county | Albemarle|Greene|Nelson|Orange
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Charlottesville Quadrangle, Virginia: 1:250,000 minute series; 
2. Roanoke Quadrangle, Virginia: 1:250,000 minute series; and 
3. Washington, DC: 1:250,000 minute series.

## Boundary [src]

(2) Following this boundary northeast to Virginia Rt. 664; 
(3) Then west following Rt. 664 to its intersection with the Nelson County line; 
(4) Then northeast along the Nelson County line to its intersection with the Albemarle County line at Jarman Gap; 
(5) From this point continuing northeast along the eastern boundary of the Shenandoah National Park to its intersection with the northern Albemarle County line; 
(6) Continuing northeast along the Greene County line to its intersection with Virginia Rt. 33; 
(7) Follow Virginia Rt. 33 east to the intersection of Virginia Rt. 230 at Stanardsville; 
(8) Follow Virginia Rt. 230 north to the Greene County line 
(the Conway River); 
(9) Following the Greene County line 
(Conway River which becomes the Rapidan River) southeast to its intersection with the Orange County line; 
(10) Following the Orange County line 
(Rapidan River) east and northeast to its confluence with the Mountain Run River; 
(11) Then following the Mountain Run River southwest to its intersection with Virginia Rt. 20; 
(12) Continuing southwest along Rt. 20 to the corporate limits of the town of Orange; 
(13) Following southwest the corporate limit line to its intersection with U.S. Rt. 15; 
(14) Continuing southwest on Rt. 15 to its intersection with Virginia Rt. 231 in the town of Gordonsville; 
(15) Then southwest along Rt. 231 to its intersection with the Albemarle County line. 
(16) Continuing southwest along the county line to its intersection with the James River; 
(17) Then following the James River to its confluence with the Tye River at Norwood, Virginia, the beginning point.

**Comment by ericallanwest** [comment]
Please label this one In Progress. Thanks!
