### ISSUE TITLE
moon_mountain_district_sonoma_county

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#136]
# AVA: Moon Mountain District Sonoma County (moon_mountain_district_sonoma_county)

name | value
--- | ---
ava_id | moon_mountain_district_sonoma_county
cfr_index | 9.231
revision | [T.D. TTB-117, 78 FR 60692, Oct. 2, 2013]
state | CA
county | Sonoma
within | North Coast\|Sonoma Valley
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Rutherford, CA, 1951; photorevised 1968; 
2. Sonoma, CA, 1951; photorevised 1980 
3. Glen Ellen, CA, 1954; photorevised 1980; and 
4. Kenwood, CA, 1954; photorevised 1980.

## Boundary [src]

(1) The beginning point is on the Rutherford map at the 2,188-foot elevation point located on the Sonoma-Napa County boundary line in section 26, T7N/R6W. From the beginning point, proceed southerly along the meandering Sonoma-Napa County boundary line, crossing onto the Sonoma map, to the intersection of the county line and Lovall Valley Road, Huichica Land Grant; then 
(2) Continue along the Sonoma-Napa County boundary line approximately 0.2 mile to the intersection of the county line and the end of an unnamed light-duty road; then 
(3) Proceed southwesterly in a straight line approximately 1.2 miles, passing through the marked 692-foot peak, to the intersection of the line with an unnamed light-duty road known locally as Thornsberry Road; then 
(4) Proceed north-northwesterly in a straight line approximately 1 mile to the intersection of two unnamed light-duty roads known locally as Castle Road and Bartholomew Road 
(marked by the 218-foot elevation point); then 
(5) Proceed west in a straight line approximately 1.4 miles, passing through the southern-most quarry marked on Schocken Hill, to the intersection of the line with the 400-foot elevation line, Pueblo Lands of Sonoma; then 
(6) Proceed northwesterly along the meandering 400-foot elevation line for approximately 7.4 miles, crossing onto the Glen Ellen map and then the Kenwood map, to the intersection of the contour line with Nelligan Road, near the mouth of Nunns Canyon, T6N/R6W; then 
(7) Proceed northerly on Nelligan Road approximately 0.6 mile to the intersection of the road with the 600-foot elevation line; then 
(8) Proceed northwest along the 600-foot elevation line approximately 1.8 miles to its second intersection with a marked trail 
(near a marked quarry and approximately 0.2 mile southeasterly of a marked 973-foot peak), Los Guilicos Land Grant; then 
(9) Proceed east-northeasterly in a straight line approximately 0.8 miles to the marked 1,483-foot peak; then 
(10) Proceed east-southeasterly in a straight line approximately 1.5 miles, crossing onto the Rutherford map, returning to the beginning point.

**Comment by SoominHur** [comment]
Reviewed
- Edit created date in the attribute table.
- Edit petitioner name in the attribute table.
- (3) Search google map and edit the node at the intersection with Wood Valley Road instead of "the intersection ... with an unnamed light-duty road known locally as Thornsberry Road."
