### ISSUE TITLE
mt__harlan

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#137]
# AVA: Mt. Harlan (mt__harlan)

name | value
--- | ---
ava_id | mt__harlan
cfr_index | 9.131
revision | [T.D. ATF-304, 55 FR 47747, Nov. 15, 1990]
state | CA
county | San Benito
within | Central Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Mt. Harlan, California 
Photorevised (1984.). 
2. Paicines, California 
Photorevised (1984.).

## Boundary [src]
peak on the county line between San Benito and Monterey Counties in Township 14 S., Range 5 E., Section 34 of the “Mt. Harlan,” California Quadrangle map. 
(2) From the point of beginning on the Mt. Harlan Quadrangle map proceed in a generally northwesterly direction along the county line through Sections 34 and 33, briefly into Section 28 and back through Section 33, and then through Sections 32, 29, and 30 all in Township 14 S., Range 5 E., to the point at which the county line intersects the line between Sections 30 and 19 of said Township and Range. 
(3) Thence proceed in a straight line northeast approximately 750 feet to the commencement of the westernmost stream leading into Pescadero Creek. The stream commences in the southwest corner of Section 19 in Township 14 S., Range 5 E. 
(4) Thence following the stream in a northeasterly direction to its intersection with the 1,800-foot contour line near the center of Section 19 in Township 14 S., Range 5 E. 
(5) Thence following the 1,800  contour line in a southeasterly and then northeasterly direction through Sections 19, 20, 17, 16, 15, 14, then through the area north of Section 14, then southerly through Section 13 on the Mt. Harlan Quadrangle map and continuing on the “Paicines,” California Quadrangle map to the point at which the 1800-foot contour line intersects the line between Sections 13 and 24 of Township 14 S., Range 5 E. 
(6) Thence along the 1,800  contour line through Section 24, back up through Section 13, and then in a southerly direction through Sections 18, 19, and 30 
(all on the Paicines Quadrangle map), then westerly through Section 25 on the Paicines Quadrangle map and continuing on the Mt. Harlan Quadrangle map, and then through Section 26 to the point of intersection of said 1,800  contour and Thompson Creek near the center of Section 26 in Township 14 S., Range 5 E., on the Mt. Harlan Quadrangle map. 
(7) Thence southwesterly along Thompson Creek to its commencement in the northwest corner of Section 34, Township 14 S., Range 5 E. 
(8) Thence in a straight line to the beginning point.

**Comment by ariellerose** [comment]
I am working on this one.

**Comment by ariellerose** [comment]
Under boundary i think the very first step is missing a sentence? I think it would say (1), right?

**Comment by MicheleTobias** [comment]
Click the "src" link to see the text it should have.  Occasionally the automated process cuts off the starting point.

**Comment by ariellerose** [comment]
(1) The point of beginning is the unnamed 3,063′
Found it!

**Comment by ariellerose** [comment]
Thank you

**Comment by MicheleTobias** [comment]
Not all of the polygons match up with others.  You might read the description of the AVA next to yours to see if they have the same description.  My feeling is that the purple one follows a different topo line.  Great question!

**Comment by MicheleTobias** [comment]
The digitizing looks great!  When you finish up the attribute table, submit a new pull request, and I'll probably be able to merge your data.

**Comment by ariellerose** [comment]
I am having a challenging time finding the petitioner name and the crf author. Do you know any tricks for finding these? I am on the federal register document and here are all the names I found: 
![image](https://user-images.githubusercontent.com/37452956/38387456-afaccb20-38cc-11e8-9d49-66bbb255a904.png)
![image](https://user-images.githubusercontent.com/37452956/38387490-c9720674-38cc-11e8-8eb4-376a995eff13.png)
I don't think any of these names are what they want... in the petition section they refer to the petitioner as the "petitioner".

**Comment by MicheleTobias** [comment]
I just read through the document and I couldn't find the petitioner's name.  I think they left it out.  Usually it's in the "Petition" section, or in the area where they give a description of how the process was started.  Typically they say something like "On X date, Sally Jones of Jones Vineyards petitioned the ATF to establish the Jones Valley AVA."  I don't see that here.  I would write "unlisted" in the attribute table for this one.

**Comment by ariellerose** [comment]
Okay. I couldn't find the crf author either, is it okay to write "unlisted" for that section too?

**Comment by MicheleTobias** [comment]
The author of the document is the person you listed above.

**Comment by SoominHur** [comment]
Reviewed.

In attribute table
- corrected created date
- add scale information of used & approved maps
- filled missed description; "(1) The point of beginning is the unnamed 3,063′" This part is written in source link but not in descriptions written above and attribute table.
