### ISSUE TITLE
mt__veeder

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#138]
# AVA: Mt. Veeder (mt__veeder)

name | value
--- | ---
ava_id | mt__veeder
cfr_index | 9.123
revision | [T.D. ATF-295, 55 FR 5844, Feb. 20, 1990, as amended by T.D. ATF-351, 58 FR 65126, Dec. 13, 1993]
state | CA
county | Napa
within | Napa Valley\|North Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Napa, California 
1951 (Photorevised (1980.) 
2. Rutherford, California 
1951 (Photorevised (1968.) 
3. Sonoma, California 
1951 (Photorevised (1980.)

## Boundary [src]

(2) Thence south along common boundary between Napa County and Sonoma County to unnamed peak, elevation 1,135 feet on the Sonoma, Calif. U.S.G.S. map; 
(3) Thence continuing south along the ridge line approximately   mile to unnamed peak, elevation 948 feet; 
(4) Thence due east in a straight line approximately   mile to the 400 foot contour; 
(5) Thence following the 400 foot contour line north around Carneros Valley and then to the west of Congress Valley and Browns Valley on the Napa, Calif. U.S.G.S. map; 
(6) Thence paralleling Redwood Road to its intersection with the line dividing Range 5 West and Range 4 West, east of the unnamed 837 foot peak; 
(7) Thence north along the line dividing Range 5 West and Range 4 West approximately   mile to the 400 foot contour; 
(8) Thence briefly southeast, then northwest along the 400 foot contour to the point where that contour intersects the northern border of Section 10, Township 6 North, Range 5 West immediately adjacent to Dry Creek on the Rutherford Calif. U.S.G.S. map; 
(9) Thence northwesterly along Dry Creek through Sections 3 and 4 of Township 6 North, Range 5 West, and Sections 32 and 31 of Township 7 North, Range 5 West, to the fork of Dry Creek near the center of Section 25 of Township 7 North, Range 6 West; 
(10) Continuing along the northern fork of Dry Creek through Sections 25 and 24 of Township 7 North, Range 6 West, to the point at which the main channel of Dry Creek ends and divides into three tributaries; 
(11) Thence following the middle tributary of Dry Creek through Sections 24 and 23 of Township 7 North, Range 6 West, to its source at the intersection with a trail indicated on the map; 
(12) Thence following a straight line west approximately   mile to the top of unnamed peak, elevation 1,820, the beginning point.

**Comment by SoominHur** [comment]
Reviewed.
- Edit created date in the attribute table
- According to (7), the line should proceed "north along the line dividing Range 5 West and Range 4 West approximately 4⁄10 mile to the 400 foot contour." However, decided to move onto the 400' contour after proceeding 0.2 miles along R5W & R4W, instead of 0.4 miles. Because the direction descried in (8) is "briefly southeast, then northwest along the 400 foot contour."
