### ISSUE TITLE
naches_heights

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#139]
# AVA: Naches Heights (naches_heights)

name | value
--- | ---
ava_id | naches_heights
cfr_index | 9.222
revision | [T.D. TTB-99, 76 FR 77699, Dec. 14, 2011]
state | WA
county | Yakima
within | Columbia Valley
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Selah, Wash., 1958, photorevised 1985; 
2. Yakima West, Wash., 1958, photorevised 1985; 
3. Wiley City, Wash., 1958, photorevised 1985; 
4. Naches, Wash., 1958, photorevised 1978; and 
5. Tieton, Wash., 1971, photoinspected 1981.

## Boundary [src]

(1) The beginning point is on the Selah map at the intersection of the Burlington Northern single-track rail line and the Congdon 
(Schuler) Canal, section 9, T13N/R18E. From the beginning point, proceed south-southwesterly along the single rail line, onto the Yakima West map, approximately 0.35 mile to the first intersection of the rail line with an unnamed creek, locally known as Cowiche Creek, section 9, T13N/R18E; then 
(2) Proceed upstream 
(westerly) along Cowiche Creek, onto the Wiley City map and then onto the Naches map, approximately 6.25 miles to the confluence of the North and South Forks of Cowiche Creek, south of Mahoney Road, section 3, T13N/R17E; then 
(3) Proceed upstream 
(northwesterly) along the North Fork of Cowiche Creek approximately 1.6 miles to the intersection of the North Fork with Livengood Road, section 34, T14N/R17E; then 
(4) Proceed north and northwest on Livengood Road approximately 1.12 miles until the road turns west and joins Forney Road, and continue approximately 1.02 miles along Forney Road to the intersection of Forney Road with the North Fork of Cowiche Creek, section 28 northwest corner, T14N/R17E; then 
(5) Proceed upstream 
(northwesterly) along the North Fork of Cowiche Creek approximately 1.8 miles to the intersection of the North Fork with the section 17 west boundary line, T14N/R17E; then 
(6) Proceed straight north along the section 17 west boundary line to its intersection with Cox Road, and then continue north along Cox Road to the intersection of Cox Road with Rosenkranz Road, section 17 northwest corner, T14N/R17E; then 
(7) Proceed west on Rosenkranz Road, onto the Tieton map, approximately 0.6 mile to the intersection of Rosenkranz Road with North Tieton Road, section 7 south boundary line, T14N/R17E; then 
(8) Proceed north on North Tieton Road approximately 0.5 mile to the intersection of North Tieton Road with Dilley Road, section 7, T14N/R17E; then 
(9) Proceed west on Dilley Road approximately 0.5 mile to the intersection of Dilley Road with Franklin Road, section 7 west boundary line and the R16E and R17E common line, T14N; then 
(10) Proceed north on Franklin Road approximately 0.8 mile to the intersection of Franklin Road with Schenk Road and the section 6 west boundary line, T14N/R16E; then 
(11) Proceed west on Schenk Road approximately 0.55 mile to the intersection of Schenk Road with Section 1 Road, section 1, T14N/R16E; then 
(12) Proceed straight north from the intersection of Schenk Road and Section 1 Road approximately 2.2 miles to the 1,600-foot elevation line, section 36, T15N/R16E; then 
(13) Proceed easterly and then southeasterly along the 1,600-foot elevation line, onto the Naches map, approximately 7.5 miles to the intersection of the 1,600-foot elevation line with the section 26 north boundary line, T14N/R17E; then 
(14) Proceed straight east along the section 26 north boundary line approximately 0.25 mile to the intersection of the section 26 north boundary line with the 1,400-foot elevation line, T14N/R17E; then 
(15) Proceed southeasterly along the 1,400-foot elevation line approximately 2.5 miles to the intersection of the 1,400-foot elevation line with Young Grade Road, section 31, T14N/R18E; then 
(16) Proceed east in a straight line approximately 0.15 mile to the Congdon 
(Schuler) Canal, which closely parallels the 1,300-foot elevation line, section 31, T14N/R18E; and then 
(17) Proceed southeasterly along the Congdon 
(Schuler) Canal, onto the Selah map, approximately 3.25 miles, returning to the beginning point, section 9, T13N/R18E.

**Comment by alisonsnwong** [comment]
Checked! Performed boudary edits
