### ISSUE TITLE
alexandria_lakes

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#14]
# AVA: Alexandria Lakes (alexandria_lakes)

name | value
--- | ---
ava_id | alexandria_lakes
cfr_index | 9.177
revision | [T.D. TTB-29, 70 FR 38003, July 1, 2005]
state | MN
county | Douglas
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c

## Approved Maps [src]

1. Alexandria West, Minn., 1966, revised 1994. 
2. Alexandria East, Minn., 1966, revised 1994. 
3. Lake Miltona East, Minn., 1969. 
4. Lake Miltona West, Minn., 1969.

## Boundary [src]

(1) The beginning point is on the Alexandria West, Minn. map between Lake Carlos and Lake Darling at benchmark 
(BM) 1366, which is an unmarked bridge on County Road 11, known as the Carlos-Darling Bridge. From this point the boundary line continues— 
(2) Along the Carlos-Darling bridge and then northeasterly along the western shore of Lake Carlos on to the Alexandria East, Minn. map; then 
(3) Along the shoreline until the point where the Lake Carlos shoreline parallels an unlabeled road known as County Road 38; then 
(4) North along County Road 38 until it intersects with an unlabeled road known as County Road 62; then 
(5) North along County Road 62 on to the Lake Miltona, East, Minn. map and then on to an unlabeled road known as Buckskin Road; then 
(6) North on Buckskin Road to the point at BM 1411; then 
(7) North from BM 1411 in a straight line to the south shoreline of Lake Miltona; then 
(8) Generally west along the south shoreline of Lake Miltona onto the Lake Miltona West, Minn. map until the southern shoreline parallels an unlabeled road known as Krohnfeldt Drive; then 
(9) South and then west along Krohnfeldt Drive until it intersects with an unlabeled road known as County Road 34; then 
(10) South along County Road 34 until the point where County Road 34 runs parallel to Lake Ida&#39;s eastern shoreline; then 
(11) South along Lake Ida&#39;s eastern shoreline, then onto the Alexandria West, Minn. map to the point where two unlabeled roads known as Burkey&#39;s Lane and Sunset Strip Road intersect; then 
(12) South along Sunset Strip Road to the point where it intersects with an unlabeled road known as County Road 104; then 
(13) Generally east along County Road 104 until it intersects with an unlabeled road known as County Road 34; then 
(14) East along County Road 34 until it intersects with an unlabeled road known as County Road 11; then 
(15) East along County Road 11 to the beginning point for the area at BM 1366, at the Carlos-Darling Bridge.

**Comment by dannyo33** [comment]
in progress
