### ISSUE TITLE
niagara_escarpment

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#141]
# AVA: Niagara Escarpment (niagara_escarpment)

name | value
--- | ---
ava_id | niagara_escarpment
cfr_index | 9.186
revision | [T.D. TTB-33, 70 FR 53303, Sept. 8, 2005]
state | NY
county | Niagara
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Lewiston, New York—Ontario, 1980;  
2. Ransomville, New York, 1980;  
3. Cambria, New York, 1980;  
4. Lockport, New York, 1980; and  
5. Gasport, New York, 1979.

## Boundary [src]

(1) On the Lewiston map, south of the village of Lewiston within the Brydges State Artpark, begin on the east bank of the Niagara River at the mouth of Fish Creek; then 
(2) Proceed north along the east bank of the Niagara River about 0.6 mile to the northern boundary of the Brydges State Artpark; then 
(3) Proceed east along the northern boundary of the Brydges State Artpark about 0.8 mile to the park&#39;s northeast corner, and continue east in a straight line a short distance to the Robert Moses Parkway; then 
(4) Proceed north along the Robert Moses Parkway about 0.25 mile to Ridge Road, and then east on Ridge Road 
(State Route 104) about 0.15 mile to the road&#39;s first intersection with the 400-foot contour line; then 
(5) Continue easterly along the 400-foot contour line, through the Ransomville map 
(crossing Model City Road, Dickersonville Road, and State Route 429) and the Cambria map 
(crossing Baer Road, Plank Road, and State Route 93/270), and pass onto the Lockport map to the contour line&#39;s junction with Sunset Drive; then 
(6) Proceed north on Sunset Drive 0.3 mile to its intersection with Stone Road, then east on Stone Road about 1.25 miles 
(crossing Eighteenmile Creek) to the intersection of Stone, Purdy, and Old Niagara Roads, and continue east along Old Niagara Road about 0.4 mile to its first intersection with the 400-foot contour line; then 
(7) Proceed northeasterly along the 400-foot contour line to its first junction with Slayton Settlement Road, proceed east on Slayton Settlement Road to Day Road, and then proceed north on Day Road to its first junction with the 400-foot contour line; then 
(8) Proceed easterly along the 400-foot contour line, pass onto the Gasport map 
(crossing Humphrey and Orangeport Roads), and continue to the contour line&#39;s junction with Quaker Road; then 
(9) Proceed north on Quaker Road about 0.4 mile to its intersection with State Route 104, and then east on State Route 104 to its intersection with Johnson Creek 
(at the village of Johnson Creek); then 
(10) Proceed south along Johnson Creek 
(crossing the Erie Canal), to the creek&#39;s junction with Mountain Road; then 
(11) Proceed west on Mountain Road to its intersection with Gasport Road, then south on Gasport Road to its intersection with Mill Road, then west on Mill Road to its intersection with Kayner Road, then north on Kayner Road 0.65 mile to its junction with the 600-foot contour line; then 
(12) Proceed westerly along the 600-foot contour line 
(crossing Cottage Road) to its junction with State Route 31, and continue west on State Route 31, passing onto the Lockport map and crossing the Erie Canal within the city of Lockport, to the intersection of State Route 31 and Upper Mountain Road; then 
(13) Proceed north-northwesterly on Upper Mountain Road 0.65 mile and then northerly on Sunset Drive 0.25 mile to the junction of Sunset Drive and the 600-foot contour line; then 
(14) Proceed westerly along the 600-foot contour line, continuing through the Cambria map 
(crossing State Route 93/270 and then Blackman and Baer Roads), through the Ransomville map 
(crossing State Route 429 just north of Pekin and then crossing Black Nose Spring and Model City Roads), and, passing onto the Lewiston map, continue westward along the contour line 
(through the Escarpment, Ramsey Ridge, and Lewiston Heights subdivisions), to the contour line&#39;s junction with Mountain View Drive 
(just east of State Highway 104 near the Niagara Falls Country Club); then 
(15) Proceed west along Mountain View Drive to its intersection with State Route 104, and then proceed south on State Route 104 to its junction with Fish Creek; then 
(16) Proceed westerly along Fish Creek and return to the beginning point on the east bank of the Niagara River at the mouth of Fish Creek.

**Comment by ekalalip** [comment]
I'm going to work on niagara_escarpment #141

**Comment by MicheleTobias** [comment]
Note: The maps scale is 1:25,000 as stated in the approved maps, although this is unusual.
