### ISSUE TITLE
north_coast

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#142]
# AVA: North Coast (north_coast)

name | value
--- | ---
ava_id | north_coast
cfr_index | 9.30
revision | [T.D. ATF-145, 48 FR 42977, Sept. 21, 1983]
state | CA
county | Lake|Marin|Mendocino|Napa|Solano|Sonoma
within | 
contains | Alexander Valley\|Anderson Valley\|Atlas Peak\|Benmore Valley\|Bennett Valley\|Big Valley District–Lake County\|Calistoga\|Chalk Hill\|Chiles Valley\|Clear Lake\|Cole Ranch\|Coombsville\|Diamond Mountain District\|Dry Creek Valley\|Eagle Peak Mendocino County\|Fort Ross-Seaview\|Fountaingrove District\|Green Valley of the Russian River Valley\|Guenoc Valley\|High Valley\|Howell Mountain\|Kelsey Bench–Lake County\|Knights Valley\|Los Carneros\|McDowell Valley\|Mendocino\|Mendocino Ridge\|Moon Mountain\|District Sonoma\|County\|Mt. Veeder\|Napa Valley\|Northern Sonoma\|Oak Knoll District of Napa Valley\|Oakville\|Pine Mountain—Cloverdale Peak\|Potter Valley\|Red Hills Lake County\|Redwood Valley\|Rockpile\|Russian River Valley\|Rutherford\|Solano County Green Valley\|Sonoma Coast\|Sonoma Mountain\|Sonoma Valley\|Spring Mountain District\|St. Helena\|Stags Leap District\|Suisun Valley\|Wild Horse Valley\|Yorkville Highlands\|Yountville

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “San Francisco, Cal.”, scaled 1:250,000, edition of 1956, revised 1980; 
2. “Santa Rosa, Cal.”, scaled 1:250,000, edition of 1958, revised 1970; and 
3. “Ukiah, Cal.”, scaled 1:250,000, edition of 1957, revised 1971.

## Boundary [src]

(1) Then east and southeast following the boundary between Marin and Sonoma Counties to the point where Estero Americano/Americano Creek crosses State Highway 1 east of Valley Ford; 
(2) Then southeast in a straight line for approximately 22.0 miles to the peak of Barnabe Mountain 
(elevation 1466 feet); 
(3) Then southeast in a straight line for approximately 10.0 miles to the peak of Mount Tamalpais 
(western peak, elevation 2604 feet); 
(4) Then northeast in a straight line for approximately 5.8 miles to the confluence of San Rafael Creek and San Rafael Bay in San Rafael; 
(5) Then north and northeast following San Rafael Bay and San Pablo Bay to Sonoma Creek; 
(6) Then north following Sonoma Creek to the boundary between Napa and Solano Counties; 
(7) Then east and north following the boundary between Napa and Solano Counties to the right-of-way of the Southern Pacific Railroad in Jameson Canyon; 
(8) Then east following the right-of-way of the Southern Pacific Railroad to the junction with the Southern Pacific in Suisun City; 
(9) Then north in a straight line for approximately 5.5 miles to the extreme southeastern corner of Napa County; 
(10) Then north following the boundary between Napa and Solano Counties to the Monticello Dam at the eastern end of Lake Berryessa; 
(11) Then following the south and west shore of Lake Berryessa to Putah Creek; 
(12) Then northwest following Putah Creek to the boundary between Napa and Lake Counties; 
(13) Then northwest in a straight line for approximately 11.4 miles to the peak of Brushy Sky High Mountain 
(elevation 3196 feet); 
(14) Then northwest in a straight line for approximately 5.0 miles to Bally Peak 
(elevation 2288 feet); 
(15) Then northwest in a straight line for approximately 6.6 miles to the peak of Round Mountain; 
(16) Then northwest in a straight line for approximately 5.5 miles to Evans Peak; 
(17) Then northwest in a straight line for approximately 5.0 miles to Pinnacle Rock Lookout; 
(18) Then northwest in a straight line for approximately 8.0 miles to Youngs Peak 
(elevation 3683 feet); 
(19) Then northwest in a straight line for approximately 11.2 miles to the peak of Pine Mountain 
(elevation 4057 feet); 
(20) Then northwest in a straight line for approximately 12.1 miles to the peak of Sanhedrin Mountain 
(elevation 6175 feet); 
(21) Then northwest in a straight line for approximately 9.4 miles to the peak of Brushy Mountain 
(elevation 4864 feet); 
(22) Then southwest in a straight line for approximately 17.6 miles to the confluence of Redwood Creek and the Noyo River; 
(23) Then west following the Noyo River to its mouth at the Pacific Ocean; 
(24) Then southeast following the Pacific Ocean shoreline to the point of beginning.

**Comment by fyfangyao** [comment]
I am working in north_coast.

**Comment by fyfangyao** [comment]
I use "Santa Rosa, CA 1958 (1973 ed.) scaled 1:250,000" and "Ukiah, CA 1957 (1974 ed.) scaled 1:250,000" because I could not find maps with right edition years.
