### ISSUE TITLE
northern_neck_george_washington_birthplace

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#143]
# AVA: Northern Neck George Washington Birthplace (northern_neck_george_washington_birthplace)

name | value
--- | ---
ava_id | northern_neck_george_washington_birthplace
cfr_index | 9.109
revision | [T.D. ATF-250, 52 FR 13082, Apr. 21, 1987]
state | VA
county | King George|Lancaster|Northumberland|Richmond|Westmoreland
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Washington, DC; Maryland; Virginia, 1957 
Revised 1979.; and 
2. Richmond, VA; MD., 1973.

## Boundary [src]

(1) Beginning on the Washington, DC; Maryland; Virginia U.S.G.S. map at a point on Potomac Creek where the King George County western boundary line at its northermost point intersects Potomac Creek the boundary proceeds easterly and southeasterly on the Richmond, VA; MD. U.S.G.S. map, along the Virginia shoreline of the Potomac River for approximately 66 miles to Smith Point on the Chesapeake Bay; 
(2) Thence southerly along the shoreline of the Chesapeake Bay for approximately 20 miles to Windmill Point at the mouth of the Rappahannock River; 
(3) Thence northwesterly along the banks of the Rappahannock River for approximately 72 air miles to Muddy Creek at the point where the western boundary line of King George County at its southernmost point begins; 
(4) Thence northward along the King George County/Stafford County line approximately 7 miles to the point of the beginning.

**Comment by ericallanwest** [comment]
Please label this one In Progress. Thanks!

**Comment by alisonsnwong** [comment]
Checked! made minor border edits
