### ISSUE TITLE
northern_sonoma

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#144]
# AVA: Northern Sonoma (northern_sonoma)

name | value
--- | ---
ava_id | northern_sonoma
cfr_index | 9.70
revision | [T.D. ATF-204, 50 FR 20562, May 17, 1985, as amended by T.D. ATF-233, 51 FR 30354, Aug. 26, 1986; T.D. ATF-300, 55 FR 32402, Aug. 9, 1990; T.D. TTB-97, 76 FR 70877, Nov. 16, 2011]
state | CA
county | Sonoma
within | North Coast
contains | Alexander Valley\|Chalk Hill\|Dry Creek\|Green Valley of Russian River Valley\|Knights Valley\|Pine Mountain-Cloverdale Peak\|Rockpile\|Russian River Valley\|Sonoma Coast

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Sonoma County, California, scale 1:100 000, 1970; 
2. Asti Quadrangle, California, scale 1:24 000, 1959, photorevised 1978; 
3. Jimtown Quadrangle, California—Sonoma County; scale 1:24 000, 1955, photorevised 1975; 
4. Camp Meeker Quadrangle, California—Sonoma Co., scale 1:24 000, 1954, photorevised 1971; 
5. Valley Ford Quadrangle, California, scale 1:24 000, 1954, photorevised 1971; 
6. Two Rock Quadrangle, California, scale 1:24 000, 1954, photorevised 1971; 
7. Cotati Quadrangle, California—Sonoma Co., scale 1:24 000, 1954, photorevised 1980; 
8. Santa Rosa Quadrangle, California—Sonoma Co., scale 1:24 000, 1954, photorevised 1980; and 
9. Mark West Springs Quadrangle, California, scale 1:24 000, 1993.

## Boundary [src]

(1) The beginning point is on the Sonoma County, map in the town of Monte Rio at the intersection of the Russian River and a secondary highway 
(Bohemian Highway); 
(2) The boundary follows this secondary highway 
(Bohemian Highway), southeasterly parallel to Dutch Bill Creek, through the towns of Camp Meeker, Occidental, and Freestone, and then northeasterly to its intersection with an unnamed secondary highway designated as State Highway 12 
(Bodega Road) at BM 214, as shown on the Valley Ford map. 
(3) The boundary follows Bodega Road northeasterly 0.9 miles on the Valley Ford map; then onto the Camp Meeker map to its intersection, at BM 486, with Jonive Road to the north and an unnamed light duty road to the south 
(Barnett Valley Road), Township 6 North, Range 9 West, on the Camp Meeker map. 
(4) The boundary follows Barnett Valley Road south 2.2 miles, then east crossing over the Valley Ford map and onto the Two Rock map, to Barnett Valley Road&#39;s intersection with Burnside Road, section 17, Township 6 North, Range 9 West. 
(5) The boundary follows Burnside Road southeast 3.3 miles to Burnside Road&#39;s intersection with an unnamed medium duty road at BM 375, Township 6 North, Range 9 West. 
(6) The boundary follows a straight line southeast 0.6 mile to an unnamed 610-foot elevation peak, 1.5 miles southwest of Canfield School, Township 6 North, Range 9 West. 
(7) The boundary follows a straight line east-southeast 0.75 mile to an unnamed 641-foot elevation peak 1.4 miles south-southwest of Canfield School, Township 6 North, Range 9 West. 
(8) The boundary follows a straight line northeast 0.85 mile to its intersection with an unnamed intermittent stream and Canfield Road; then continues on the straight line northeast 0.3 mile to the line&#39;s intersection with the common Ranges 8 and 9 line, just west of an unnamed unimproved dirt road, Township 6 North. 
(9) The boundary follows a straight line southeast 0.5 mile, crossing over the end of an unnamed, unimproved dirt road to an unnamed 524-foot elevation peak, Township 6 North, Range 8 West. 
(10) The boundary follows a straight line southeast 0.75 mile to the intersection of an unnamed unimproved dirt road 
(leading to four barn-like structures) and an unnamed medium-duty road 
(Roblar Road), Township 6 North, Range 8 West. 
(11) The boundary follows a straight line south 0.5 mile to an unnamed 678-foot elevation peak, Township 6 North, Range 8 West. 
(12) The boundary follows a straight line east-southeast 0.8 mile to an unnamed peak with a 599-foot elevation, Township 5 North, Range 8 West. 
(13) The boundary follows a straight line east-southeast 0.7 mile to an unnamed peak with a 604-foot elevation, Township 5 North, Range 8 West. 
(14) The boundary follows a straight line east-southeast 0.9 mile, onto the Cotati map, to the intersection of a short, unnamed light-duty road leading past a group of barn-like structures and Meacham Road, Township 5 North, Range 8 West. 
(15) The boundary follows Meacham Road north-northeast 0.75 mile to Meacham Road&#39;s intersection with Stony Point Road, Township 5 North, Range 8 West. 
(16) The boundary follows Stony Point Road southeast 1.1 miles to the point where the 200-foot elevation contour line intersects Stony Point Road, Township 5 North, Range 8 West. 
(17) The boundary follows a straight line north-northeast 0.5 mile to the point where an unnamed intermittent stream intersects U.S. 101, Township 5 North, Range 8 West. 
(18) The boundary follows U.S. Route 101 north 4.25 miles to the point where Santa Rosa Avenue exits U.S. Route 101 to the east 
(approximately 0.5 mile north of the Wilfred Avenue overpass) Township 6 North, Range 8 West. 
(19) The boundary follows Santa Rosa Avenue north 1.1 miles to its intersection with Todd Road, crossing on to the Santa Rosa map, Township 6 North, Range 8 West. 
(20) The boundary follows Santa Rosa Avenue generally north 5.8 miles, eventually becoming Mendocino Avenue, to Santa Rosa Avenue&#39;s intersection with an unnamed secondary road 
(Bicentennial Way), 0.3 mile north-northwest of BM 161 on Mendocino Avenue, section 11, Township 7 North, Range 8 West. 
(21) The boundary follows a straight line north 2.5 miles crossing over the 906-foot elevation peak in section 35, T8N, R8W, crossing onto the Mark West Springs map, to the line&#39;s intersection with Mark West Springs Road and the meandering 280-foot elevation line in section 26, Township 6 North, Range 8 West. 
(22) The boundary follows the unnamed secondary highway, Mark West Springs Road, on the Sonoma County map, generally north and east, eventually turning into Porter Road and then to Petrified Forest Road, passing BM 545, the town of Mark West Springs, BM 495, and the Petrified Forest area, to Petrified Forest Road&#39;s intersection with the Sonoma County-Napa County line. 
(23) The boundary follows the Sonoma County-Napa County line northerly to the Sonoma County-Lake County line. 
(24) The boundary follows the Sonoma County-Lake County line northwesterly to the section line on the north side of Section 11, Township 10 North, Range 8 West. 
(25) The boundary follows this section line west to the northwest corner of Section 9, Township 10 North, Range 8, West. 
(26) The boundary follows the section line south to the southwest corner of Section 4, Township 9 North, Range 8, West. 
(27) The boundary proceeds northerly along the western lines of section 4, of Township 9 North, Range 8 West, and sections 33, 28, 21, 16, and 9 of Township 10 North, Range 8 West of the Jimtown Quadrangle map. 
(28) The boundary proceeds westerly along the northern lines of sections 8 and 7, Township 10 North, Range 8 West and section 12, Township 10 North, Range 9 West to the southeastern corner of section 2, Township 10 North, Range 9 West. 
(29) The boundary proceeds northwesterly in a straight line to the eastern line of section 3 at 38 degrees 45 minutes latitude, Township 10 North, Range 9 West. 
(30) The boundary proceeds westerly along latitude line 38 degrees 45 minutes to the point lying at 122 degrees 52 minutes 30 seconds longitude. 
(31) The boundary proceeds northwesterly in a straight line to the southeast corner of section 4, Township 11 North, Range 10 West, on the Asti, Quadrangle map. 
(32) The boundary proceeds northeasterly in a straight line to the southeast corner of section 34, Township 12 North, Range 10 West. 
(33) The boundary proceeds north along the east boundary of section 34, Township 12 North, Range 10 West on the U.S.G.S. Topographical Map of Sonoma County, California, to the Sonoma County-Mendocino County line. 
(34) The boundary proceeds along the Sonoma County-Mendocino County line west then south to the southwest corner of section 34, Township 12 North, Range 11 West. 
(35) The boundary proceeds in a straight line east southeasterly to the southeast corner of section 2, Township 11 North, Range 11 West. 
(36) The boundary proceeds in a straight line south southeasterly to the southeast corner of section 24, Township 11 North, Range 11 West. 
(37) The boundary proceeds in a straight line southeasterly across sections 30, 31, and 32 in Township 11 North, Range 10 West, to the point at 38 degrees 45 minutes North latitude parallel and 123 degrees 00 minutes East longitude in section 5, Township 10 North, Range 10 West. 
(38) The boundary proceeds along this latitude parallel west to the west line of section 5, Township 10 North, Range 11 West. 
(39) The boundary proceeds along the section line south to the southeast corner of section 18, Township 9 North, Range 11 West. 
(40) The boundary proceeds in a straight line southwesterly approximately 5 miles to the peak of Big Oat Mountain, elevation 1,404 feet. 
(41) The boundary proceeds in a straight line southerly approximately 2  miles to the peak of Pole Mountain, elevation 2,204 feet. 
(42) The boundary proceeds in a straight line southeasterly approximately 4  miles to the confluence of Austin Creek and the Russian River. 
(43) The boundary proceeds along the Russian River northeasterly, then southeasterly to the beginning point.

**Comment by SoominHur** [comment]
Reviewed
- Edit created date in the attribute table
- For review, I cannot find the "Sonoma County, CA" 1970, scale 1:100,000. Instead, I used  "Calistoga, CA" (Topographic) 1958, photorevised 1980, scale 1:24000; "Cazadero, CA" (Topographic) 1978, scale 1:24000; "Cloverdale, CA" (Topographic) 1960, photoinspected 1975, scale 1:24000; "Mount St. Helena, CA" (Topographic) 1959, photoinspected 1973, scale 1:24000; "Detert Reservoir, CA" (Topographic) 1958, photorevised 1980, scale 1:24000; "Duncans Mills, CA" (Topographic) 1979, scale 1:24000; "Warm Springs Dam, CA" (Topographic) 1978, scale 1:24000; and "Fort Ross, CA" (Topographic) 1978, scale 1:24000, which had been used by @amberreyes .
- Move the node at the intersection with an unnamed intermittent stream and unimproved/unnamed road to (8) the intersection with an unnamed intermittent stream and Canfield Road. Following are two more reasons why I thought the location of the previous node is wrong; if the line proceed "straight in the same northeast ... direction to its intersection with the common boundary of Ranges 8 and 9," that intersection should be "just west of an unnamed unimproved dirt road, T6N, on the Two Rock map." Also, from that intersection point with Ranges 8/9, the line should (9) "proceed southeast 0.5 mile, crossing over the end of an unnamed, unimproved dirt road to an unnamed 524-foot elevation peak, T6N, R8W, on the Two Rock map." However, these requirements does not apply with previous node.
- There is a shorter/unnamed road above the location of previous node at the end of longer/unnamed road. So I move the node to the intersection of that shorter (14) "unnamed light-duty road leading past a group of barn-like structures and ... Meacham Road ... on to the Cotati map T5N, R8W" so the distance (15) "to the intersection of Meacham and Stony Point Roads, T5N, R8W, on the Cotati map" can be approximately 0.75 mile.

**Comment by sdelong** [comment]
The west boundary has an error in (38) and (39).  Currently, both are using Range 10 West, when they should be using Range 11 West:

(38) The boundary proceeds along this latitude parallel west to the west line of section 5, Township 10 North, Range 11 West.
(39) The boundary proceeds along the section line south to the southeast corner of section 18, Township 9 North, Range 11 West.

These are both found on this map:
Warm Springs Dam., scale 1:24 000, 1978,

**Comment by MicheleTobias** [comment]
Thanks for this!  I've confirmed this and fixed the boundary.
