### ISSUE TITLE
north_fork_of_long_island

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#145]
# AVA: North Fork of Long Island (north_fork_of_long_island)

name | value
--- | ---
ava_id | north_fork_of_long_island
cfr_index | 9.113
revision | [T.D. ATF-240, 51 FR 36398, Oct. 10, 1986]
state | NY
county | Suffolk
within | Long Island
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Wading River, N.Y., 7.5 minute series, scaled at 1:24,000 edition of 1967. 
2. Riverhead, N.Y., 7.5 minute series, scaled at 1:24,000, edition of 1956. 
3. New York, N.Y.; N.J.; Conn., U.S., 1:250,000 series, scaled at 1:250,000, edition of 1960, revised 1979. 
4. Providence, R.I.; Mass.; Conn., N.Y., U.S., 1:250,000 series, scaled at 1:250,000, edition of 1947, revised 1969. 
5. Hartford, Conn.; N.Y.; N.J.; Mass., U.S., 1:250,000 series, scaled at 1,250,000, edition of 1962, revised 1975.

## Boundary [src]

(1) The point of beginning is on the Wading River, N.Y., 7.5 minute series, U.S.G.S. map at the northern boundary of the Brookhaven/Riverhead Township line on the Long Island Sound 
(approximately 500 feet east of the mouth of the Wading River); 
(2) The boundary goes south on the Brookhaven/Riverhead Town line for approximately 6.5 miles until it meets the Peconic River approximately 1 mile east of U.S. Reservation Brookhaven National Laboratory; 
(3) Then the boundary travels east on the Peconic River 
(Brookhaven/Riverhead Town line) for 2.7 miles until it meets the Riverhead/Southampton Township line on the Riverhead, N.Y., U.S.G.S. map; 
(4) It then goes east on the Riverhead/Southampton Township line for 4.2 miles until it reaches an area where the Peconic River widens north of Flanders; 
(5) Then the boundary proceeds east to Orient Point then west along the shoreline, beaches, islands, and mainland areas of the North Fork of Long Island, described on the “New York”, “Providence” and “Hartford” U.S.G.S. maps until it reaches the Brookhaven/Riverhead Township line at the point of beginning. These boundaries consist of all the land 
(and isolated islands including without limitation, Wicopesset Island, Robins Island, Fishers Island, Great Gull Island, Plum Island, and Shelter Island) in the Townships of Riverhead, Shelter Island, and Southold.

**Comment by ericallanwest** [comment]
Please label this one In Progress and Virginia Tech. Thanks!
