### ISSUE TITLE
north_yuba

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#147]
# AVA: North Yuba (north_yuba)

name | value
--- | ---
ava_id | north_yuba
cfr_index | 9.106
revision | [T.D. ATF-211, 50 FR 30820, July 30, 1985]
state | CA
county | Yuba
within | Sierra Foothills
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Oregon House Quadrangle,” edition of 1948, photo-revised 1969. 
2. “Rackerby Quadrangle,” edition of 1948, photo-revised 1969. 
3. “Challenge Quadrangle,” edition of 1948 photo-revised 1969. 
4. “French Corral Quadrangle,” edition of 1948, photo-revised 1969.

## Boundary [src]

(1) Beginning on the “Oregon House Quadrangle” map at the point where the Browns Valley Ditch crosses Woods Creek in the southwest corner of section 25, T. 17 N., R. 6 E., the boundary proceeds northeasterly in a meandering line approximately 1.5 miles along the east bank of Woods Creek to the point near Richards Ranch where the paved light duty road crosses said creek; 
(2) Then west and north, approximately 0.33 mile to the point where the paved light duty road meets the unimproved dirt road accessing Dixon Hill and Texas Hill; 
(3) Then northwest continuing along the paved light duty road approximately 2.75 miles to the intersection at Oregon House of said light duty road with the medium duty road which travels east and west between Virginia Ranch Reservoir of Dry Creek and the Yuba County Forestry Headquarters near Dobbins; 
(4) Then northeasterly, 0.7 mile, along same light duty road to its intersection with the unimproved dirt road to Lake Mildred, located in the northwest corner of section 2, T. 17 N., R. 6 E.; 
(5) Then northwesterly, 1.0 miles, along the unimproved dirt road to the end of said road at the shoreline of Lake Mildred; 
(6) Then southwest along the shoreline of Lake Mildred to the Los Verjeles Dam at the westernmost end of said lake; 
(7) Then across the face of said dam and continuing northeast along the shoreline of Lake Mildred to the point where the stream running through Smokey Ravine flows into Lake Mildred; 
(8) Then north and west along said stream to the point where the stream crosses the 1,900-foot contour line in the northeast corner of section 27, T. 18 N., R. 6 E.; 
(9) Then southwest in a meandering line along the 1.900-foot contour line of Lamb Hill; 
(10) Then northwest along the 1,900-foot contour line of High Spring Ridge to the point where the medium duty paved road running north and south along Willow Glen Creek crosses the 1,900-foot contour line, approximately 0.75 mile north of Finley Ranch; 
(11) Then north along said road, approximately 1 mile, to its intersection at Willow Glen Ranch near the west boundary line of section 15, T. 18 N., R. 6 E., with the light duty road which crosses Critterden Ridge; 
(12) Then in a generally easterly direction along said road, approximately 2.0 miles, to its point of intersection with the light duty paved road named Frenchtown Road which runs north and south between Brownsville and Frenchtown; 
(13) Then south along the Frenchtown Road to the point where the road crosses the 1,600-foot contour line in the northwest corner of section 24, T. 18 N., R. 6 E.; 
(14) Then east along the 1,600-foot contour line to the point where Dry Creek crosses the 1,600-foot contour line near the south boundary line of section 13, T. 18 N., R. 6 E.; 
(15) Then south along Dry Creek, approximately 0.16 mile, to the confluence of Indiana Creek with Dry Creek; 
(16) Then in a generally easterly direction, approximately 1 mile, along Indiana Creek to the confluence of Keystone Creek with Indiana Creek; 
(17) Then north along indiana Creek, approximately 0.87 mile, to the point where Indiana Creek meets the 2,000-foot contour line of Oregon Hills; 
(18) Then in a generally southeasterly direction along the 2,000-foot contour line of Oregon Hills, approximately 6 miles, to the point near the east boundary line of section 9, T. 17 N., R. 7 E., where the power transmission line on Red Bluff crosses the 2,000-foot contour line; 
(19) Then southwest along the right of way of said power transmission line to the point near the south boundary of section 9, T. 17 N., R. 7 E., where it meets the power transmission line running northwest and southeast between Dobbins and the Colgate Power House; 
(20) Then southeast along the power transmission line between Dobbins and Colgate Power House to the Colgate Power House; 
(21) Then in a generally westerly direction from the Colgate Power House along the power transmission line which crosses over Dobbins Creek to the point west of Dobbins Creek where the power transmission line intersects the 1,000-foot contour line; 
(22) Then in a generally southwesterly direction along the 1,000-foot contour line above the north bank of the Yuba River and Harry L. Englebright lake of the Yuba River to the intersection of the 1,000-foot contour line with Woods Creek in the northeast corner of section 36, T. 17 N., R. 6 E.; 
(23) Then east and north along the east bank of Woods Creek, approximately 0.5 miles, to the point of beginning.

**Comment by SoominHur** [comment]
Reviewed.
- Add scale information of used maps.
- (21) There are multiple 1000-foot contour line at the "west of Dobbins Creek where the power transmission line intersects the 1,000-foot contour line." The line started meandering second next (west) intersection from the Dobbins Creek, so I edit it to start meandering the contour line right (first) next (west) intersection from the Dobbins Creek.
- Refine some lines.
