### ISSUE TITLE
oak_knoll_district_of_napa_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#148]
# AVA: Oak Knoll District of Napa Valley (oak_knoll_district_of_napa_valley)

name | value
--- | ---
ava_id | oak_knoll_district_of_napa_valley
cfr_index | 9.161
revision | [T.D. TTB-9, 69 FR 8564, Feb. 25, 2004]
state | CA
county | Napa
within | Napa Valley\|North Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Napa, California, 1951 
Photo revised 1980.; and  
2. Yountville, California, 1951 
Photo revised 1968..

## Boundary [src]

(1) Beginning at the intersection of State Highway 29 and Trancas Road in the city of Napa on the Napa, CA quadrangle map;  
(2) Proceed easterly along Trancas Road until it meets the Napa River;  
(3) Proceed southerly along the Napa River approximately 3,500 feet to its confluence with Milliken Creek;  
(4) Continue northerly up Milliken Creek to its intersection with Monticello Road;  
(5) Then proceed westerly along Monticello Road to its intersection with Silverado Trail;  
(6) Then proceed northerly and then northeasterly along Silverado Trail to its intersection with an unimproved dirt road located approximately 1,300 feet north of the intersection of Silverado Trail and Oak Knoll Avenue;  
(7) From that point, proceed west in a straight line to the confluence of Dry Creek and the Napa River;  
(8) Then proceed northwesterly along Dry Creek onto the Yountville map to the fork in the creek; then northwesterly along the north fork of Dry Creek to its intersection with the easterly end of the light-duty road labeled Ragatz Lane;  
(9) Proceed southwesterly along Ragatz Lane to the west side of State Highway 29;  
(10) Then proceed southerly along the west side of State Highway 29 for 982 feet to a point marking the easterly extension of the northern boundary of Napa County Assessor&#39;s parcel number 034-170-015 
(marked in part by a fence along the southern edge of the orchard shown along the west side of State Highway 29 just above the bottom of the Yountville map);  
(11) Then proceed westerly for 3,550 feet along the northern boundary of Napa County Assessor&#39;s parcel number 034-170-015 and its westerly extension to the dividing line between Range 5 West and Range 4 West on the Napa, CA map;  
(12) Then proceed southwest in a straight line to the peak marked with an elevation of 564 feet; then south-southwest in a straight line to the peak marked with an elevation of 835 feet;  
(13) Then proceed southwest in a straight line approximately 1,300 feet to the reservoir gauging station located on Dry Creek; then proceed west in a straight line across Dry Creek to the 400 foot contour line;  
(14) Proceed along the 400-foot contour line in a generally southeasterly direction to its intersection with the line dividing Range 5 West and Range 4 West; then proceed south along that dividing line approximately 2,400 feet to the center of Redwood Road;  
(15) Then proceed southerly and then easterly along Redwood Road to the point of beginning at Highway 29.

**Comment by SoominHur** [comment]
- matched nodes' coordination with that of Yountville polygon when it shares boundary with Yountville polygon
- moved node next to (6) "... unimproved dirt road located approximately 1,300 feet north of the intersection of Silverado Trail and Oak Knoll Avenue"
- (13) "... proceed [line] west in a straight line across Dry Creek to the 400 foot contour line" because the line proceeded straightly in southwest direction.
- Corrected created date in attribute table
