### ISSUE TITLE
alta_mesa

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#15]
# AVA: Alta Mesa (alta_mesa)

name | value
--- | ---
ava_id | alta_mesa
cfr_index | 9.195
revision | [T.D. TTB-50, 71 FR 40414, July 17, 2006]
state | CA
county | Sacramento
within | Lodi
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c

## Approved Maps [src]

1. North Lodi, Calif., 1968, photorevised 1976; 
2. Galt, Calif., 1968, photorevised 1980; 
3. Florin, Calif., 1968, photorevised 1980; 
4. Elk Grove, Calif., 1968, photorevised 1979; 
5. Sloughhouse, Calif., 1968, photorevised 1980, minor revision 1993; 
6. Clay, Calif., 1968, photorevised 1980, minor revision 1993; and 
7. Lockeford, Calif., 1968, photorevised 1979, minor revision 1993.

## Boundary [src]

(1) The beginning point is on the Lodi North map at the intersection of Kost Road and the Southern Pacific railway, section 34, T5N, R6E. From the beginning point, proceed north-northwest 8.7 miles along the Southern Pacific railway to its intersection with State Route 99 at McConnel, section 20, T6N, R6E 
(Galt Quadrangle); then 
(2) Proceed northwest 4.7 miles on State Route 99 to its intersection with Sheldon Road at the northern boundary of section 26, T7N, R5E 
(Florin Quadrangle); then 
(3) Proceed east 5.2 miles on Sheldon Road to its intersection with the Central California Traction railroad at the northern boundary of section 27, T7N, R6E 
(Elk Grove Quadrangle); then 
(4) Proceed southeast 3.85 miles along the Central California Traction railroad to Grant Line Road, then southwest on Grant Line Road to Wilton Road at the hamlet of Sheldon, and then continue southeast on Wilton Road to its intersection with Dillard Road, section 6, T6N, R7E 
(Elk Grove Quadrangle); then 
(5) Proceed northeast 2.6 miles on Dillard Road to its intersection with Lee Shorthorn Road, T7N, R7E 
(Sloughhouse Quadrangle); then 
(6) Proceed southeast 0.9 mile on Lee Shorthorn Road to its intersection with Tavernor Road, T7N, R7E 
(Sloughhouse Quadrangle); then 
(7) Proceed south 0.95 mile on Tavernor Road to its first 90 degree turn to the west 
(where two unimproved roads join Tavernor Road from the east and south), section 4, T6N, R7E 
(Sloughhouse Quadrangle); then 
(8) Continue due south 1 mile in a straight line to the line&#39;s intersection with the 105-foot contour line and an unimproved extension of Blake Road, section 9, T6N, R7E 
(Sloughhouse Quadrangle); then 
(9) Proceed west 0.3 mile on the unimproved extension of Blake Road to its intersection with Tavernor Road, section 9, T6N, R7E 
(Sloughhouse Quadrangle); then 
(10) Proceed south 0.7 mile on Tavernor Road to the center of the loop at the end of the road, section 16, T6N, R7E 
(Sloughhouse Quadrangle); then 
(11) Proceed southwest in a straight line for 0.1 mile to the line&#39;s intersection with the east end of the landing strip shown in the northwest quadrant of section 16, T6N, R7E 
(Sloughhouse Quadrangle); then 
(12) Proceed west along the landing strip and a line extending from its western end to the line&#39;s intersection with Alta Mesa Road on the eastern boundary of section 17, T6N, R7E 
(Sloughhouse Quadrangle); then 
(13) Proceed south 6.1 miles on Alta Mesa Road, crossing State Route 104, to Alta Mesa Road&#39;s intersection with Borden Road at the southwest corner of section 9, T5N, R7E 
(Clay Quadrangle); then 
(14) Proceed east 1 mile on Borden Road to its intersection with Alabama Road at the southeast corner of section 9, T5N, R7E 
(Clay Quadrangle); then 
(15) Proceed south 2 miles on Alabama Road to its intersection with Simmerhorn Road at the southeast corner of section 21, T5N, R7E 
(Clay Quadrangle); then 
(16) Proceed east 2 miles on Simmerhorn Road to its intersection with Clay Station Road at the northeast corner of section 26, T5N, R7E 
(Clay Quadrangle); then 
(17) Proceed south 0.5 mile on Clay Station Road to its intersection with Dry Creek, section 26, T5N, R7E 
(Clay Quadrangle); then 
(18) Proceed west-southwest 
(downstream) 7.8 miles along Dry Creek, crossing over the northwest corner of the Lockeford map, and twice crossing over the southeast corner of the Galt map, to Dry Creek&#39;s intersection with Lincoln Way, section 35, T5N, R6E 
(Lodi North Quadrangle); then 
(19) Proceed northwest 0.1 mile on Lincoln Way to its intersection with Kost Road, section 35, T5N, R6E 
(Lodi North Quadrangle); and 
(20) Proceed west 0.3 mile on Kost Road, returning to the beginning point.

**Comment by fyfangyao** [comment]
I am working on it.

**Comment by fyfangyao** [comment]
I use “Lodi North, CA, 7.5 Minute Series, edition of 1968, (revised 1977),” “Sloughhouse Calif. 7.5 Minute Series, edition of 1968, (revised 1993),” “Clay Calif. 7.5 Minute Series, edition of 1968, (revised 1993),” and “Lockeford, CA, 7.5 Minute Series, edition of 1968, (revised 1993).”

**Comment by SoominHur** [comment]
Reviewed.
- Add scale information of used maps in the attribute table.
- According to (4), the line should move from "Central California Traction railroad to Grant Line Road, then southwest on Grant Line Road to Wilton Road at the hamlet of Sheldon, and then continue southeast on Wilton Road to its intersection with Dillard Road, section 6, T6N, R7E." But the line continued following Central California Traction railroad, past the intersection with Grant Line Road, until it intersects with Dillard Road. So, edited that line to be like how it described in (4).
