### ISSUE TITLE
ohio_river_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#150]
# AVA: Ohio River Valley (ohio_river_valley)

name | value
--- | ---
ava_id | ohio_river_valley
cfr_index | 9.78
revision | [T.D. ATF-144, 48 FR 40379, Sept. 7, 1983, as amended by T.D. ATF-249, 52 FR 5959, Feb. 27, 1987; T.D. TTB-110, 78 FR, 8021, Feb. 5, 2013]
state | IN|KY|OH|WV
county | 
within | 
contains | Kanawha River Valley (WV)

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Paducah NJ 16-7 
dated 1949, revised 1969.; 
2. Belleville NJ 16-4 
dated 1958, revised 1977.; 
3. Vincennes NJ 16-5 
dated 1956, revised 1969.; 
4. Louisville NJ 16-6 
dated 1956, revised 1969.; 
5. Cincinnati NJ 16-3 
dated 1953, revised 1974.; 
6. Columbus NJ 17-1 
dated 1967.; 
7. Clarksburg NJ 17-2 
dated 1956, limited revision 1965.; 
8. Canton NJ 17-11 
dated 1957, revised 1969.; 
9. Charleston NJ 17-5 
dated 1957, limited revision 1965.; 
10. Huntington NJ 17-4 
dated 1957, revised 1977.; 
11. Winchester NJ 16-9 
dated 1957, revised 1979.; and 
12. Evansville NJ 16-8 
dated 1957, revised 1974.;

## Boundary [src]

(1) The beginning point is the point at which the Kentucky, Illinois, and Indiana State lines converge at the confluence of the Wabash River and the Ohio River 
(Paducah map). 
(2) The boundary follows the Illinois-Indiana State line northerly 
(across the Belleville map) to Interstate Route 64 
(Vincennes map). 
(3) From the intersection of Interstate Route 64 and the Wabash River, the boundary proceeds in a straight line northeasterly to the town of Oatsville in Pike County, Indiana 
(Vincennes map). 
(4) The boundary proceeds in a straight line southeasterly to the point in Spencer County, Indiana, at which State Route 162 diverges northerly from U.S. Route 460, which is knownlocally as State Route 62 
(Vincennes map). 
(5) The boundary proceeds in a straight line southeasterly to the confluence of the Anderson River and the Ohio River at Troy, Indiana 
(Evansville map). 
(6) The boundary proceeds along the Indiana shoreline of the Ohio River 
(Evansville and Vincennes maps) generally easterly to the mouth of French Creek in Franklin Township, Floyd County, Indiana 
(Louisville map).  
(7) The boundary proceeds in a straight line northerly to the peak of Lost Knob, then continues in a straight line north-northeasterly through the peak of Bald Knob to the junction of State Route 111 and a road locally known as W. St. Joe Road at St. Joseph in New Albany Township, Floyd County, Indiana 
(Louisville map). 
(8) The boundary then proceeds on State Route 111 northerly to State Route 60 at Bennettsville in Clark County, Indiana, then on State Route 60 westerly to Carwood, and then in a straight line northerly to the point where the Clark-Scott county line crosses Interstate 65 at Underwood, Indiana 
(Louisville map). 
(9) The boundary proceeds in a straight line northwesterly to Leota in Scott County, Indiana 
(Louisville map). 
(10) The boundary proceeds in a straight line northeasterly to the town of New Marion in Ripley County, Indiana 
(Cincinnati map). 
(11) The boundary proceeds in a straight line northerly to the town of Clarksburg in Decatur County, Indiana 
(Cincinnati map). 
(12) The boundary proceeds in a straight line easterly to the town of Ridgeville in Warren County, Ohio 
(Cincinnati map). 
(13) The boundary proceeds in a straight line southeasterly to the town of Chapman in Jackson County, Ohio 
(Columbus map). 
(14) The boundary proceeds in a straight line northeasterly to the town identified on the map as Hesboro, also known as Ilesboro, in Hocking County, Ohio 
(Columbus map). 
(15) The boundary proceeds in a straight line northeasterly to the town of Tacoma in Belmont County, Ohio 
(Clarksburg map). 
(16) The boundary proceeds in a straight line easterly to the town of Valley Grove in Ohio County, West Virginia 
(Canton map). 
(17) The boundary proceeds in a straight line southerly to the town of Jarvisville in Harrison County, West Virginia 
(Clarksburg map). 
(18) The boundary proceeds in a straight line southwesterly to the town of Gandeeville in Roane County West Virginia 
(Charleston map). 
(19) The boundary proceeds in a straight line southwesterly to the town of Atenville in Lincoln County West Virginia 
(Huntington map). 
(20) The boundary proceeds in a straight line westerly to the town of Isonville in Elliott County, Kentucky 
(Huntington map). 
(21) The boundary proceeds in a straight line northwesterly to the town of Berlin in Bracken County, Kentucky 
(Louisville map). 
(22) The boundary proceeds in a straight line westerly to the town of Dry Ridge in Grant County, Kentucky 
(Louisville map). 
(23) The boundary proceeds in a straight line southwesterly to the town of Crest in Hardin County, Kentucky 
(Winchester map). 
(24) The boundary proceeds in a straight line westerly to the intersection of State Route 56 and U.S. Route 41 in the city of Sebree in Webster County, Kentucky 
(Evansville map). 
(25) The boundary proceeds in a straight line northwesterly to the beginning point 
(Paducah map). Transition period.  A label containing the words “Ohio River Valley” in the brand name or as an appellation of origin approved prior to March 7, 2013 may be used on wine bottled before March 9, 2015, if the wine conforms to the standards for use of the label set forth in §4.25 or §4.39
(i) of this chapter in effect prior to March 7, 2013.

**Comment by sdelong** [comment]
working on it

**Comment by davidkli** [comment]
I have checked this AVA. The boundary was updated to follow step 6 and the counties field in the attribute table was updated to include all counties in the AVA.
