### ISSUE TITLE
old_mission_peninsula

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#151]
# AVA: Old Mission Peninsula (old_mission_peninsula)

name | value
--- | ---
ava_id | old_mission_peninsula
cfr_index | 9.114
revision | [T.D. ATF-252, 52 FR 21515, June 8, 1987]
state | MI
county | Grand Traverse
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Elk Rapids, Mich. 
1957.; and 
2. Traverse City, Mich. 
1957..

## Boundary [src]

(1) The beginning point is on the Traverse City, Mich., U.S.G.S. map at the shoreline of the West Arm of Grand Traverse Bay at Section 1, Township 27 North, Range 11 West 
(T27N, R11W), approximately 500 feet due west of the intersection of two unmarked light-duty roads 
(approx. 750 feet north of Bryant Park); 
(2) The boundary proceeds north 19 miles along the western shoreline of the Old Mission Peninsula until it reaches the lighthouse near Old Mission Point at the north side of the Peninsula on the Elk Rapids, Mich., U.S.G.S. map, Sec. 23, T30N, R10W; 
(3) It then proceeds south for approximately 19 miles along the eastern shoreline of the peninsula to the southeast portion of an unmarked light-duty road 
(known locally as Eastern Avenue) at Sec. 6, T27N, R10W on the Traverse City, Mich., U.S.G.S. map. The unmarked light-duty road is located immediately north of Northwestern Michigan College on the shoreline of the East Arm of the Grand Traverse Bay; 
(4) The boundary travels west along the unmarked light-duty road 
(known locally as Eastern Avenue) for approximately one mile until it meets an unmarked north/south light-duty road at Sec. 1, T27N, R11W; and 
(5) Finally, the boundary proceeds due east 500 feet to the beginning point on the shoreline of the West Arm of the Grand Traverse Bay at Sec. 1, T27N, R11W.

**Comment by SoominHur** [comment]
In progress

**Comment by dannyo33** [comment]
Currently working on this one.
