### ISSUE TITLE
outer_coastal_plain

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#152]
# AVA: Outer Coastal Plain (outer_coastal_plain)

name | value
--- | ---
ava_id | outer_coastal_plain
cfr_index | 9.207
revision | [T.D. TTB-58, 72 FR 6167, Feb. 9, 2007]
state | NJ
county | Atlantic|Burlington|Camden|Cape May|Cumberland|Gloucester|Monmouth|Ocean|Salem
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Wilmington, Delaware-New Jersey-Pennsylvania-Maryland, 1984, 1:100,000 scale; 
2. Hammonton, New Jersey, 1984, 1:100,000 scale; 
3. Trenton, New Jersey-Pennsylvania-New York, 1986, 1:100,000 scale; 
4. Long Branch, New Jersey, 1954, photorevised 1981, 1:24,000 scale; 
5. Atlantic City, New Jersey, 1984, 1:100,000 scale; 
6. Cape May, New Jersey, 1981, 1:100,000 scale; and 
7. Dover, Delaware-New Jersey-Maryland, 1984, 1:100,000 scale.

## Boundary [src]

(1) The beginning point is on the Wilmington map at the confluence of Alloway Creek with the Delaware River 
(within Mad Horse Creek State Wildlife Management Area) in Salem County; 
(2) From the beginning point, proceed northeasterly in a straight line to the village of Hagerville; then 
(3) Continue north on an unnamed road locally known as County Road 
(CR) 658 to its intersection with State Route 
(SR) 49; then 
(4) Proceed northwesterly on SR 49 to its intersection with SR 45 in the center of the town of Salem; then 
(5) Proceed northeasterly on SR 45 to its intersection with SR 540 at the village of Pointers; then 
(6) Proceed north on SR 540 into the village of Slapes Corner; then 
(7) Proceed northeasterly on an unnamed road locally known as CR 646 to its intersection with the New Jersey Turnpike near the village of Auburn; then 
(8) Proceed northeasterly on the New Jersey Turnpike for approximately 18 miles to its intersection with SR 47; then 
(9) Proceed south on SR 47 for approximately 0.5 mile to its intersection with SR 534 at the village of Gardenville Center; then 
(10) Proceed southeasterly through Gardenville Center on SR 534 to its intersection with SR 544; then 
(11) Proceed northeasterly on SR 544 to its intersection with SR 73 on the Hammonton map; then 
(12) Proceed north-northwesterly on SR 73 to its intersection with SR 70 in Cropwell; then 
(13) Proceed east on SR 70 to its intersection with U.S. 206 in Red Lion; then 
(14) Proceed north on U.S. 206, onto the Trenton map, to the intersection of U.S. 206 and an unnamed road locally known as CR 537, in the village of Chambers Corner; then 
(15) Proceed northeasterly on CR 537, through the village of Jobstown; then 
(16) Continue northeasterly on CR 537, through the villages of Smithburg and Freehold, to its intersection with SR 18, east-northeast of Freehold; then 
(17) Proceed easterly on SR 18 to its intersection with the Garden State Parkway; then 
(18) Proceed north on the Garden State Parkway to its intersection with SR 36 and proceed east along SR 36 onto the Long Branch map; then 
(19) Using the Long Branch map, continue east on SR 36 to where it intersects with Joline Avenue; then 
(20) Proceed northeasterly on Joline Avenue to the Atlantic Ocean shoreline; then 
(21) Follow the Atlantic Ocean shoreline south, encompassing all coastal islands, onto the Trenton, Hammonton, Atlantic City, and Cape May maps, to the city of Cape May; then 
(22) Proceed west, then north, along the eastern bank of the Delaware River, onto the Atlantic City, Dover, and Wilmington maps to the beginning point.

**Comment by davidkli** [comment]
I am currently checking this AVA. It looks like after this issue was created, the AVA had updated it's boundary (on December 7, 2017). So whoever digitized this AVA followed the updated boundaries and topo maps which do not match up with the boundary description and maps in this issue. However, the boundary that they made is correct with the updated version, just not sure if it is a problem if it does not match with what is in this issue.
