### ISSUE TITLE
ozark_highlands

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#153]
# AVA: Ozark Highlands (ozark_highlands)

name | value
--- | ---
ava_id | ozark_highlands
cfr_index | 9.115
revision | [T.D. ATF-256, 52 FR 32785, Aug. 31, 1987]
state | MO
county | Crawford|Dent|Franklin|Gasconade|Maries|Osage|Phelps|Pulaski|Reynolds|Shannon|Texas
within | Ozark Mountain
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Rolla, Missouri; Illinois, 1954 
revised 1969.. 
2. St. Louis, Missouri; Illinois, 1963 
revised 1969.. 
3. Springfield, Missouri, 1954 
revised 1969..

## Boundary [src]
General.  The Ozark Highlands viticultural area is located in south central Missouri. The area comprises portions of the following counties: Phelps, Maries, Osage, Gasconade, Franklin, Crawford, Texas, Shannon, Dent, Reynolds, and Pulaski. The beginning point of the following boundary description is the junction of Little Piney Creek and the Gasconade River, near Jerome, Missouri 
(in the northwest corner of the Rolla map). Boundary Description.  
(i) From the beginning point, the boundary goes northward along the Gasconade River to the latitude line 38°00  
(the dividing line between the Rolla and St. Louis maps); 
(ii) Then eastward along that latitude line to U.S. Highway 63; 
(iii) Then northward along U.S. 63 to Spring Creek; 
(iv) Then north-northwestward along Spring Creek to the Gasconade River; 
(v) Then northward along the Gasconade River to a power transmission line 
(less than 1 mile north of Buck Elk Creek); 
(vi) Then eastward and east-northeastward along that power transmission line to Missouri Route 19; 
(vii) Then southward along Route 19 to the Bourbeuse River; 
(viii) Then east-northeastward along the Bourbeuse River to the range line dividing R. 2 W. and R. 1 W.; 
(ix) Then southward along that range line to the Meramec River; 
(x) Then southwestward along the Meramec River to Huzzah Creek; 
(xi) Then southward along Huzzah Creek to Dry Creek 
(on the Rolla map, where Missouri Route 8 crosses Huzzah Creek); 
(xii) Then southward along Dry Creek to Cherry Valley Creek; 
(xiii) Then south-southwestward along Cherry Valley Creek to Missouri Route 19; 
(xiv) Then southward and southwestward along Route 19 to Crooked Creek; 
(xv) Then northwestward along Crooked Creek to the Meramec River; 
(xvi) Then southward along the Meramec River to Hutchins Creek; 
(xvii) The southeastward along Hutchins Creek to its source near Missouri Route 32, across from the Howes Mill Post Office; 
(xviii) Then in a straight line toward the Howes Mill Post Office to Route 32; 
(xix) Then eastward along Route 32 to the range line dividing R. 3 W. and R. 2 W.; 
(xx) Then southward along that range line to the township line dividing T. 33 N. and T. 32 N.; 
(xxi) Then westward along that township line 
(which coincides, in R. 3 W., with the Reynolds County/Dent County line) to the boundary of Clark National Forest; 
(xxii) Then generally southward along that national forest boundary to the Dent County/Shannon County line; 
(xxiii) Then westward along that county line to the Current River; 
(xxiv) Then southeastward along the Current River to Missouri Route 19; 
(xxv) Then southward along Route 19 to Jack&#39;s Fork; 
(xxvi) Then westward, southwestward and northwestward along Jack&#39;s Fork, taking the North Prong, to its northwesternmost source; 
(xxvii) Then in a straight line northwestward to the southeasternmost source of Hog Creek; 
(xxviii) Then northwestward along Hog Creek to the Big Piney River 
(on the Springfield map); 
(xxix) Then northward along the Big Piney River to the township line dividing T. 35 N. and T. 36 N.; 
(xxx) Then eastward along that township line to Little Piney Creek 
(on the Rolla map); 
(xxxi) Then northward and westward along Little Piney Creek to the beginning point.

**Comment by ekalalip** [comment]
I'd like to start with this location

**Comment by MicheleTobias** [comment]
How's it going with this AVA?  Do you have any questions I can answer?

**Comment by ekalalip** [comment]
Hi, Thanks for asking. I basically just started the AVA today, since I was
working on another project until today.
I will let you know if I have any questions?

Best

Emad Kalalipour

**Comment by MicheleTobias** [comment]
No worries!  Take your time!  I just wanted to check in.

**Comment by ekalalip** [comment]
There is a mistake in the instructions; at steps (xx), T33N & T32N don't meet at the Reynolds/Dent County line, it's T33N & T34N
