### ISSUE TITLE
ozark_mountain

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#154]
# AVA: Ozark Mountain (ozark_mountain)

name | value
--- | ---
ava_id | ozark_mountain
cfr_index | 9.108
revision | [T.D. ATF-231, 51 FR 24144, July 2, 1986; 51 FR 25366, July 14, 1986]
state | AR|MO|OK
county | 
within | 
contains | Altus (AR)\|Arkansas Mountain (AR)\|Augusta (MO)\|Hermann (MO)\|Ozark Highlands (MO)

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. St. Louis, Missouri 
1963, revised 1969.; 
2. Jefferson City, Missouri 
1955, revised 1970.; 
3. Springfield, Missouri 
1954, revised 1969.; 
4. Joplin, Missouri; Kansas 
1954, revised 1974.; 
5. Tulsa, Oklahoma; Arkansas; Missouri; Kansas 
1958, revised 1973.; 
6. Fort Smith, Arkansas-Oklahoma 
1978.; 
7. Russellville, Arkansas 
compiled in 1954.; 
8. Memphis, Tennessee; Arkansas; Missouri 
1953, revised 1978.; 
9. Poplar Bluff, Missouri; Arkansas 
1957, revised 1978.; 
10. Paducah, Kentucky; Illinois; Missouri; Indiana 
1949, revised 1969.; and 
11. Rolla, Missouri; Illinois 
1954, revised 1969..

## Boundary [src]
General.  The Ozark Mountain viticultural area is located in Missouri, Oklahoma, and Arkansas. The starting point of the following boundary description is the point at which the Missouri River joins the Mississippi River north of St. Louis, Missouri 
(on the St. Louis map). Boundary Description.  
(i) The boundary proceeds from the starting point westward along the Missouri River until it meets the Osage River; 
(ii) Then further westward along the Osage River 
(flowing through Lake of the Ozarks and the Harry S. Truman Reservoir) until it passes adjacent to Missouri Highway 82 in Osceola, Missouri 
(on the Jefferson City map); 
(iii) Then southwestward along Missouri Highway 82 until it intersects U.S. Highway 54 in Eldorado Springs, Missouri 
(on the Joplin map); 
(iv) Then westward along U.S. Highway 54 until it intersects U.S. Highway 71 near Nevada, Missouri; 
(v) Then southward along U.S. Highway 71 until it intersects Interstate Highway 44, approximately 5 miles south of Carthage, Missouri; 
(vi) Then westward and southwestward along Interstate Highway 44 into the State of Oklahoma, and continuing southwestward until Interstate Highway 44 crosses the Neosho River near Miami, Oklahoma 
(on the Tulsa map); 
(vii) Then southward along the Neosho River 
(flowing through the Lake of the Cherokees, Lake Hudson, and Fort Gibson Lake) until it flows into the Arkansas River, approximately 2 miles west of Fort Gibson, Oklahoma 
(on the Fort Smith map); 
(viii) Then southward and eastward along the Arkansas River 
(flowing through the Robert S. Kerr Lake) into the State of Arkansas, and continuing eastward until the Arkansas River is joined by Vache Grasse Creek, approximately 4 miles east of Barling, Arkansas; 
(ix) Then southeastward and southwestward following Vache Grasse Creek to the place where it is crossed by Arkansas Highway 10, near Greenwood, Arkansas; 
(x) Then westward along Highway 10 to U.S. Highway 71. Note: Highway 10 is the primary highway leading from Greenwood to Hackett, Arkansas; 
(xi) Then southward and eastward along Highway 71 until it crosses Rock Creek; 
(xii) Then northeastward along Rock Creek to Petit Jean Creek; 
(xiii) Then generally northeastward and eastward along Petit Jean Creek until it becomes the Petit Jean River 
(on the Russellville map); 
(xiv) Then generally eastward along the Petit Jean River, flowing through Blue Mountain Lake, until the Petit Jean River joins the Arkansas River; 
(xv) Then generally eastward along the Arkansas River to Cadron Creek; 
(xvi) Then northeastward and eastward along Cadron Creek, for about 2  miles, until it pases under U.S. Highway 64, approximately 3  miles west of Conway, Arkansas; 
(xvii) Then eastward along U.S. Highway 64 until it intersects U.S. Highway 67, near Beebe, Arkansas 
(on the Memphis map); 
(xviii) Then northeastward along U.S. Highway 67 into the state of Missouri, then northward until U.S. Highway 67 intersects U.S. Highway 60, in Poplar Bluff, Missouri 
(on the Poplar Bluff map); 
(xix) Then eastward along U.S. Highway 60 until it crosses the western boundary of Stoddard County. Note: Here that boundary is the St. Francis River; 
(xx) Then northward, northeastward, and eastward along the boundary of Stoddard County until it joins the southern boundary of Cape Girardeau County 
(on the Cape Girardeau map); 
(xxi) Then northeastward along the Cape Girardeau County boundary until it meets the Mississippi River south of Cape Girardeau, Missouri; 
(xxii) Then northward along the Mississippi River to the starting point.

**Comment by ouwxmaniac** [comment]
In progress

**Comment by dannyo33** [comment]
Need to match Ozark Mountain AVA boundary to Arkansas Mountain AVA #22 boundary.

**Comment by MicheleTobias** [comment]
The boundary for this AVA is complete, but now we need to match it to the Arkansas Mountain boundary since they share a common boundary.  Anyone can take this on, just make a comment so we know it's in progress.
