### ISSUE TITLE
pacheco_pass

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#155]
# AVA: Pacheco Pass (pacheco_pass)

name | value
--- | ---
ava_id | pacheco_pass
cfr_index | 9.88
revision | [T.D. ATF-167, 49 FR 9169, Mar. 12, 1984]
state | CA
county | San Benito
within | Central Coast\|San Francisco Bay\|Santa Clara Valley
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. San Felipe Quadrangle, 7.5 minute series, 1955 
photorevised 1971.. 
2. Three Sisters Quadrangle, 7.5 minute series, 1954 
photorevised 1971..

## Boundary [src]
General.  The Pacheco Pass viticultural area is located in California. The starting point of the following boundary description is the crossing of Pacheco Creek under California Highway 156, about 4 miles north of Hollister Municipal Airport, in San Benito County, California. Boundary Description.  
(i) From the starting point northwestward along Pacheco Creek to the intersection with the straight-line extension of Barnheisel Road. 
( Note.  This is an old land grant boundary and appears on the U.S.G.S. map as the western boundary of an orchard.) 
(ii) From there in a straight line northeastward to the intersection of Barnheisel Road and California Highway 156. 
(iii) From there northward along Highway 156 to California Highway 152 
(“Pacheco Pass Highway”). 
(iv) Then northward along Pacheco Pass Highway to the 37° latitude line. 
(v) Then eastward along that latitude line to the land line R. 5E./R. 6E. 
(vi) Then southward along that land line, crossing Foothill Road, and continuing southward to a point exactly 2,300 feet south of Foothill Road. 
(vii) From there is a straight line to the starting point.

**Comment by SoominHur** [comment]
Reviewed.
From the starting point, the line followed along Hwy 156 instead of (ii) Pacheco Creek and straight -line extension of Barnheisel Road. So, corrected line according to (ii) and (iii).
