### ISSUE TITLE
paicines

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#156]
# AVA: Paicines (paicines)

name | value
--- | ---
ava_id | paicines
cfr_index | 9.39
revision | [T.D. ATF-108, 47 FR 35481, Aug. 16, 1982]
state | CA
county | San Benito
within | Central Coast\|San Benito
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Tres Pinos Quadrangle, California,” 7.5 minute series 
1971.; 
2. “Paicines Quadrangle, California,” 7.5 minute series 
1968.; and 
3. “Cherry Peak Quadrangle, California,” 7.5 minute series 
1968..

## Boundary [src]

(1) From the beginning point the boundary runs east along the north border of Sections 3, 2, and 1, Township 14 South, Range 6 East; 
(2) Thence south along the east border of Section 1, Township 14 South, Range 6 East; thence east along the north border of Section 7, Township 14 South, Range 7 East; thence south along the east border of Section 7, Township 14 South, Range 7 East; 
(3) Thence continuing south along the east border of Section 18, Township 14 South, Range 7 East; thence east along the north border of Section 20, Township 14 South, Range 7 East; thence south along the east border of Sections 20, 29 and 32, Township 14 South, Range 7 East; 
(4) Thence continuing south along the east border of Section 5, Township 15 South, Range 7 East; thence south along the east border of Sections 8 and 17, Township 15 South, Range 7 East to latitude line 36°37 
(5) Thence west along latitude line 36°37  to the west border of Section 18, Township 15 South, Range 7 East; 
(6) Thence north along the west border of Sections 18 and 7, Township 15 South, Range 7 East; thence west along the south border of Section 1, Township 15 South, Range 6 East; thence north along the west border of Section 1, Township 15 South, Range 6 East to the 800-foot elevation contour line and then in a generally northwest direction along this 800-foot contour line to where it intersects with the south border of Section 35, Township 14 South, Range 6 East; 
(7) Thence west along the south border of Section 35, Township 14 South, Range 6 East; thence north along the east border of Section 34, Township 14 South, Range 6 East; thence in a northwest direction along the northeast border of Section 34, Township 14 South, Range 6 East; thence continuing in a northwest direction along the east border of Section 27, Township 14 South, Range 6 East; 
(8) Thence continuing in a northwest direction to the northeast border of Section 22, Township 14 South, Range 6 East to where an unnamed, unimproved dirt road intersects the northeast border; thence east and then northwest along the unimproved dirt road to the intersection with the San Benito River; thence following the San Benito River and meandering north to the intersection with the east border of Section 4, Township 14 South, Range 6 East; 
(9) Thence continuing north along the east border of Section 4, Township 14 South, Range 6 East to the point of beginning.

**Comment by MicheleTobias** [comment]
I'm working on this one.

**Comment by SoominHur** [comment]
Continue Reviewing
- Edit cfr_author name in attribute table
