### ISSUE TITLE
paso_robles_estrella_district

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#157]
# AVA: Paso Robles Estrella District (paso_robles_estrella_district)

name | value
--- | ---
ava_id | paso_robles_estrella_district
cfr_index | 9.241
revision | [T.D. TTB-125, 79 FR 60962, Oct. 9, 2014]
state | CA
county | San Luis Obispo
within | Central Coast\|Paso Robles
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Paso Robles, Calif., 1948, photorevised 1979; 
2. San Miguel, Calif., 1948, photorevised 1979; 
3. Ranchito Canyon, Calif., 1948, photorevised 1976; 
4. Estrella, Calif., 1948, photorevised 1979; and 
5. Shandon, Calif., 1961.

## Boundary [src]

(1) The beginning point is on the Paso Robles map at the confluence of San Jacinto Creek and the Estrella River, section 26, T25S/R12E. From the beginning point, proceed north-northeasterly 
(upstream) along San Jacinto Creek approximately 6.5 miles, crossing onto the San Miguel map, to the creek&#39;s intersection with the San Luis Obispo County-Monterey County boundary line, northern boundary of section 1, T25S/R12E; then 
(2) Proceed east along the San Luis Obispo County-Monterey County boundary line approximately 2.4 miles, crossing onto the Ranchito Canyon map, to the county line&#39;s intersection with an unnamed light-duty road locally known as Ranchita Canyon Road, northern boundary of section 4, T25S/R13E; then 
(3) Proceed east-southeasterly in a straight line approximately 4.5 miles to the 1,819-foot elevation point in the northwestern quadrant of section 18, T25S/R14E; then 
(4) Proceed southeasterly in a straight line approximately 1.6 miles, crossing over the northeastern corner of the Estrella map and then onto the Shandon map, to the 1,614-foot elevation point in the northwestern quadrant of section 20, T25S/R14E; then 
(5) Proceed southeasterly in a straight line approximately 1.05 miles to the 1,601-foot elevation point in the northeastern quadrant of section 29, T25S/R14E; then 
(6) Proceed east-southeasterly in a straight line approximately 2.2 miles to the 1,562-foot elevation point, section 34, T25S/R14E; then 
(7) Proceed south-southeasterly in a straight line approximately 3 miles to the 1,481-foot “Estrella” elevation point, section 14, T26S/R14E; then 
(8) Proceed southwesterly in a straight line approximately 0.95 mile to the intersection of the eastern boundary line of section 15, T26S/R14E, and U.S. 446/State Route 41 
(now known as State Route 46); then 
(9) Proceed south along the eastern boundary lines of sections 15 and 22, approximately 0.55 mile, to the intersection of the section 22 boundary line and the unnamed intermittent stream that flows from Shedd Canyon, section 22, T26S/R14E; then 
(10) Proceed southeasterly and then southerly 
(upstream) along the unnamed intermittent stream located within Shedd Canyon approximately 1.9 miles to the stream&#39;s intersection with the southern boundary line of section 26, T26S/R14E; then 
(11) Proceed west along the southern boundary lines of sections 26, 27 and 28, T26S/R14E, approximately 1.9 miles to the section 28 boundary line&#39;s intersection with an unnamed unimproved road located between the 1,220- and 1,240-foot contour lines, section 28, T26S/R14E; then 
(12) Proceed southwesterly along the unnamed unimproved road approximately 0.4 miles to a fork and then continue on the westerly fork of the unnamed unimproved road approximately 0.3 miles to the 1,385-foot elevation point, section 32, T26S/R14E; then 
(13) Proceed west-northwesterly in a straight line approximately 1.6 miles, crossing onto the Estrella map, to the line&#39;s intersection with an unnamed unimproved road and the southern boundary of section 30, T26R/R14E; then 
(14) Proceed northerly along the unnamed unimproved road approximately 2.0 miles to the road&#39;s intersection with an unnamed light-duty road known locally as River Grove Drive in Whitley Gardens, T26S/R14E; then 
(15) Proceed westerly in a straight line less than 0.1 mile to the intersection of the western boundary line of section 19, T26S/R14E and State Route 46, and then continue west on State Route 46 approximately 2.1 miles to the southwest corner of section 14, T26S/R13E; then 
(16) Proceed west along the southern boundary lines of sections 14, 15, 16, 17, and 18 
(largely concurrent with State Route 46) approximately 4 miles to the southwest corner of section 18, T26S/R13E; then 
(17) Proceed southwest in a straight line approximately 1.45 miles, crossing onto the Paso Robles map, to the line&#39;s intersection with State Route 46 at the southwestern corner of section 24, T26S/R12E; then 
(18) Proceed west on State Route 46 approximately 2.4 miles to the road&#39;s intersection with the Salinas River at the city of Paso Robles, T26S/R12E; then 
(19) Proceed northerly 
(downstream) along the main channel of the Salinas River approximately 5.2 miles in straight-line distance to the river&#39;s intersection with the northern boundary line of section 33, T25S/R12E; then 
(20) Proceed east along the northern boundary lines of sections 33, 34, and 35, T25S/R12E, approximately 1.8 miles to the intersection of the section 35 boundary line with the Estrella River; then 
(21) Proceed northerly 
(downstream) along the main channel of the Estrella River approximately 0.7 mile, returning to the beginning point.

**Comment by SoominHur** [comment]
Reviewed.
- Add scale information of the used maps.
