### ISSUE TITLE
paso_robles_geneseo_district

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#158]
# AVA: Paso Robles Geneseo District (paso_robles_geneseo_district)

name | value
--- | ---
ava_id | paso_robles_geneseo_district
cfr_index | 9.242
revision | [T.D. TTB-125, 79 FR 60963, Oct. 9, 2014]
state | CA
county | San Luis Obispo
within | Central Coast\|Paso Robles
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Paso Robles, Calif., 1948, photorevised 1979; 
2. Estrella Calif., 1948; photorevised 1979; 
3. Creston, Calif., 1948; photorevised 1980; and 
4. Templeton, Calif., 1948; photorevised 1979.

## Boundary [src]

(1) The beginning point is on the Paso Robles map at the intersection of State Route 46 and Golden Hill Road at the northwest corner of section 26, T26S/R12E. From the beginning point, proceed east on State Route 46 for 1 mile to the southwest corner of section 24, T26S/R12E; then 
(2) Proceed northeast in a straight line approximately 1.45 miles, crossing onto the Estrella map, to the northwest corner of section 19, T26S/R13E; then 
(3) Proceed east along the northern boundary lines of sections 19 and 20, T26S/R13E, to the section 20 boundary line&#39;s intersection with State Route 46 and then continue east on State Route 46 to the road&#39;s intersection with the eastern boundary line of section 24, T26S/R13E; then 
(4) Proceed easterly in a straight line less than 0.1 mile to the intersection of an unnamed light duty road locally known as River Grove Drive and an unnamed unimproved road in Whitley Gardens, section 19, T26S/R14E; then 
(5) Proceed south on the unnamed unimproved road approximately 2 miles to the road&#39;s intersection with the southern boundary line of section 30, T26S/R14E; then 
(6) Proceed west-southwesterly in a straight line approximately 1.9 miles, crossing onto the Creston map, to the intersection of an unnamed light duty road locally known as Geneseo Road and an unnamed unimproved road locally known as Dry Canyon Road 
(just east of a windmill within Dry Canyon), section 35, T26S/R13E; then 
(7) Proceed south on Geneseo Road approximately 1 mile to the road&#39;s intersection with the eastern boundary line of section 3, T27S/R13E 
(near BM 1200); then 
(8) Proceed south along the eastern boundary lines of sections 3, 10, and 15, T27S/R13E, approximately 1.9 miles to the first intersection of the section 15 eastern boundary line with the unnamed light-duty road locally known as Geneseo Road, section 15, T27S/R13E; then 
(9) Proceed south-southeasterly on Geneseo Road approximately 0.85 mile to the road&#39;s intersection with an unnamed light duty road locally known as Creston Road, Huerhuero Land Grant, T27S/R13E; then 
(10) Proceed west on Creston Road 0.5 mile to the road&#39;s intersection with a marked, unnamed light-duty road 
(locally known as a private driveway located approximately 430 feet east of Old Ford Road), southern boundary of section 15, T27S/R13E; then 
(11) Proceed north on the marked, unnamed light-duty road 
(locally known as a private driveway located approximately 430 feet east of Old Ford Road) approximately 0.3 mile to the road&#39;s end, section 15, T27S/R13E; then 
(12) Proceed west-northwesterly in a straight line approximately 0.6 mile to the 1,342 foot elevation point in section 15, T27S/R13E, and then continue west-northwesterly in a straight line approximately 0.6 mile to an unnamed peak above the 1,380-foot elevation line 
(marked on the map with a triangle), section 16, T27S/R13E; then 
(13) Proceed westerly in a straight line approximately 0.75 mile to the 1,255-foot elevation point in the northwest quadrant of section 16, T27S/R13E; then 
(14) Proceed northwesterly in a straight line approximately 1.4 miles to the confluence of Huerhuero Creek and an unnamed intermittent stream in the northwest quadrant of section 8, T27S/R13E; then 
(15) Proceed northwesterly 
(downstream) along Huerhuero Creek approximately 2.4 miles to the creek&#39;s intersection with the R12E/R13E common boundary line, section 31, T26S/R13E; then 
(16) Proceed westerly in a straight line approximately 2.3 miles, crossing onto the Templeton map, to the line&#39;s intersection with the junction of a marked telephone line and an unnamed light duty road locally known as Creston Road 
(approximately 1.3 miles due east of U.S. Route 101 in the Santa Ysabel Land Grant, T26S/R12E; then 
(17) Proceed west on Creston Road approximately 0.05 mile to the road&#39;s intersection with an unnamed light-duty road locally known as Rolling Hills Road, Santa Ysabel Land Grant; then 
(18) Proceed north on Rolling Hills Road, crossing onto the Paso Robles map 
(where a portion of Rolling Hills Road is labeled Golden Hill Road), and continue north on Rolling Hills Road and then Golden Hill Road 
(a total distance of approximately 1.5 miles), returning to the beginning point.

**Comment by SoominHur** [comment]
Reviewed.
- (8) edited the line proceeded along Geneseo Road from the third intersection instead of "first intersection of the section 15 eastern boundary line with the unnamed light-duty road locally known as Geneseo Road, section 15, T27S/R13E"
- (10)-(12) There are two marked, unnamed light-duty road in section 15 (T27S/R13E); one is straight and the other is curved. The description is unclear which one to proceed along. It seems more reasonable to follow straight road according to the distance descriptions; (10) "west on Creston Road 0.5 mile", (11) "approximately 0.3 mile to the road's end", and (12) "approximately 0.6 mile to the 1,342 foot elevation point." However, the name of straight road is _Old Ford Road_  according to the google map. And the marked, unnamed light-duty road must not Old Ford Road because of descriptions in (10) & (11); "locally known as a private driveway located approximately 430 feet east of Old Ford Road" Therefore, I decided to proceed along curved road next to straight (Old Ford) road.
- added scale information in the attribute table.
