### ISSUE TITLE
paso_robles_highlands_district

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#159]
# AVA: Paso Robles Highlands District (paso_robles_highlands_district)

name | value
--- | ---
ava_id | paso_robles_highlands_district
cfr_index | 9.243
revision | [T.D. TTB-125, 79 FR 60964, Oct. 9, 2014]
state | CA
county | San Luis Obispo
within | Central Coast\|Paso Robles
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Camatta Ranch, CA, 1995; 
2. Wilson Corner, CA, 1995; 
3. Shedd Canyon, Calif., 1961, revised 1993; 
4. Camatta Canyon, Calif., 1961, revised 1993; 
5. Holland Canyon, Calif., 1961, revised 1993; and 
6. La Panza Ranch, CA, 1995.

## Boundary [src]

(1) The beginning point is on the Camatta Ranch map along the T28S/T29S common boundary line 
(also concurrent with the northern boundary line of the Los Padres National Forest) at the southwest corner of section 34, T28S/R15E. From the beginning point, proceed north along the western boundary lines of sections 34 and 27, T28S/R15E, approximately 1.5 miles to the section 27 boundary line&#39;s intersection with State Route 58; then 
(2) Proceed west on State Route 58 approximately 1.5 miles, crossing onto the Wilson Corner map, to the road&#39;s intersection with an unnamed light-duty road known locally as La Panza Road at Wilson Corner, section 29, T28S/R15E; then 
(3) Proceed northwest on the unnamed light-duty road known locally as La Panza Road approximately 0.15 mile to the road&#39;s intersection with Indian Creek, section 20, T28S/R15E; then 
(4) Proceed north-northwesterly 
(downstream) along the meandering Indian Creek approximately 8.5 miles in straight-line distance, crossing onto the Shedd Canyon map, to the creek&#39;s intersection with the northern boundary line of section 13, T27S/R14E, within Shedd Canyon; then 
(5) Proceed east approximately 6.2 miles along the northern boundary line of section 13, T27S/R14E, and the northern boundary lines of sections 18, 17, 16, 15, 14, and 13, T27S/R15E, crossing onto the Camatta Canyon map, to the intersection of the northern boundary line of section 13, T27S/R15E, with the 1,200-foot elevation line on the western edge of the San Juan Valley; then 
(6) Proceed southerly then easterly along the 1,200-foot elevation line to the elevation line&#39;s first intersection with the eastern boundary line of section 13, T27S/R15E; then 
(7) Proceed south along the eastern boundary line of section 13, T27S/R15E, approximately 0.2 mile to the section 13 boundary line&#39;s second intersection with an unnamed unimproved road; then 
(8) Proceed southeasterly on the unnamed unimproved road approximately 3 miles as it follows the southwestern edge of the San Juan Valley to the road&#39;s intersection with the eastern boundary line of section 29, T27S/R16E; then 
(9) Proceed south along the eastern boundary line of section 29, T27S/R16E, approximately 0.3 mile to the section line&#39;s intersection with the 1,300-foot elevation line; then 
(10) Proceed southeasterly along the 1,300-foot elevation line approximately 3.7 miles as it follows the southwestern edge of the San Juan Valley, crossing onto the Holland Canyon map, to the elevation line&#39;s first intersection with the eastern boundary line of section 3, T28S/R16E; then 
(11) Proceed south along the eastern boundary line of section 3, T28S/R16E, approximately 0.55 mile to the section boundary line&#39;s fifth intersection with the 1,300-foot elevation line 
(northwest of Pear Tree Spring); then 
(12) Proceed southeasterly along the 1,300-foot elevation line approximately 1.3 miles to the elevation line&#39;s intersection with an unnamed tributary of San Juan Creek 
(approximately 0.35 mile east of the 1,686-foot San Juan peak), section 11, T28S/R16E; then 
(13) Proceed southerly in a straight line approximately 0.6 mile, crossing onto the La Panza Ranch map, to the northwestern corner of section 13, T28S/R16E; then 
(14) Proceed east along the northern boundary line of section 13, T28S/R16E, approximately 0.7 mile to the section boundary line&#39;s intersection with an unnamed unimproved road; then 
(15) Proceed south-southeasterly on the unnamed unimproved road approximately 0.85 mile to the road&#39;s intersection with the eastern boundary line of section 13, T28S/R16E, which is concurrent with the R16E/R17E common boundary line; then 
(16) Proceed south along the R16E/R17E common boundary line approximately 3.35 miles to the southeast corner of section 36, T28S/R16E, which is concurrent with the eastern-most intersection of the R16E/R17E and T28S/T29S common boundary lines; then 
(17) Proceed west along the T28S/R29S common boundary line approximately 9.1 miles, crossing onto the Camatta Ranch map, returning to the beginning point.

**Comment by SoominHur** [comment]
Reviewed.
- Add scale information of the used maps in attribute table.
