### ISSUE TITLE
altus

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#16]
# AVA: Altus (altus)

name | value
--- | ---
ava_id | altus
cfr_index | 9.77
revision | [T.D. ATF-176, 49 FR 22471, May 30, 1984]
state | AR
county | Franklin
within | Arkansas Mountain\|Ozark Mountain
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Ozark Quadrangle, 1966. 
2. Coal Hill Quadrangle, 1961. 
3. Hartman Quadrangle, 1961. 
4. Hunt Quadrangle, 1963. 
5. Watalula Quadrangle, 1973.

## Boundary [src]
General.  The Altus viticultural area is located in Arkansas. The starting point of the following boundary description is the crossing of the Missouri Pacific Railroad over Gar Creek, near the Arkansas River at the southeast corner of the city of Ozark, Arkansas 
(on the Ozark Quadrangle map). Boundary Description: 
(i) From the crossing of the Missouri Pacific Railroad over Gar Creek, following the railroad tracks eastward to the crossing over Horsehead Creek 
(on the Hartman Quadrangle map). 
(ii) From there northward along Horsehead Creek to the merger with Dirty Creek 
(on the Coal Hill Quadrangle map). 
(iii) From there generally northwestward along Dirty Creek to Arkansas Highway 352 
(where Dirty Creek passes under the highway as a perennial stream—on the Hunt Quadrangle map). 
(iv) From there along Highway 352 westward to Arkansas Highway 219 
(on the Watalula Quadrangle map). 
(v) Then southward along Highway 219 to Gar Creek 
(on the Ozark Quadrangle map). 
(vi) Then southeastward along Gar Creek to the beginning point.

**Comment by dannyo33** [comment]
in progress
