### ISSUE TITLE
paso_robles

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#160]
# AVA: Paso Robles (paso_robles)

name | value
--- | ---
ava_id | paso_robles
cfr_index | 9.84
revision | [T.D. ATF-148, 48 FR 45241, Oct. 4, 1983, as amended by T.D. ATF-377, 61 FR 29953, June 13, 1996; T.D. TTB-72, 74 FR 3429, Jan. 21, 2009]
state | CA
county | San Luis Obispo
within | Central Coast
contains | Adelaida District\|Creston District\|El Pomar District\|Paso Robles Estrella District\|Paso Robles Geneseo District\|Paso Robles Highlands District\|Paso Robles Willow Creek District\|San Juan Creek\|San Miguel District\|Santa Margarita Ranch\|Templeton Gap District

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Boundary [src]

(1) Then in a westerly direction along this county line for 42 miles to the range line between R.9E. and R.10E.; 
(2) Then in a southerly direction for 12 miles along the range line to the southwest of corner of T.26S. and R.10E.; 
(3) Then in a southeasterly direction, approximately 5.5 miles to a point of intersection of the Dover Canyon Jeep Trail and Dover Canyon Road; 
(4) Then in an easterly direction along Dover Canyon Road, approximately 1.5 miles, to the western border line of Rancho Paso de Robles; 
(5) Then, following the border of the Paso Robles land grant, beginning in an easterly direction, to a point where it intersects the range line between R.11E. and R.12E.; 
(6) Then southeasterly for approximately 16.5 miles to the point of intersection of the township line between T.29S. and T.30S. and the range line between R.12E. and R.13E.; 
(7) Then in an easterly direction along the T.29S. and T.30S. line for approximately 3.1 miles to its intersection with the eastern boundary line of the Los Padres National Forest; 
(8) Then in a southeasterly direction along the eastern boundary line of the Los Padres National Forest for approximately 4.1 miles to its intersection with the R.13E. and R.14E. line; 
(9) Then in a northerly direction along the R.13E. and R.14E. line for approximately 8.7 miles to its intersection with the T.28S. and T.29S. line;  
(10) Then in an easterly direction for approximately 18 miles to the range line between R.16E. and R.17E.; 
(11) Then in a northerly direction for approximately 24 miles to the point of beginning.

**Comment by SoominHur** [comment]
Reviewed
- According to the attribute table, previous worker used _"San Luis Obispo, CA" 1956, revised 1969, scale 1:250,000_. For review, I used _"San Luis Obispo, CA" 1956, revised 1969, shoreline revised and bathymetry added 1979, scale 1:250,000,_ which is the approved map listed in source page (www.ecfr.gov).
