### ISSUE TITLE
paso_robles_willow_creek_district

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#161]
# AVA: Paso Robles Willow Creek District (paso_robles_willow_creek_district)

name | value
--- | ---
ava_id | paso_robles_willow_creek_district
cfr_index | 9.244
revision | [T.D. TTB-125, 79 FR 60964, Oct. 9, 2014]
state | CA
county | San Luis Obispo
within | Central Coast\|Paso Robles
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. York Mountain, Calif., 1948, photorevised 1979; 
2. Templeton, Calif., 1948, photorevised 1979; and 
3. Paso Robles, Calif. 1948, photorevised 1979.

## Boundary [src]

(1) The beginning point is on the York Mountain map at the intersection of Summit Canyon Road 
(locally known as Peachy Canyon Road), and an unnamed unimproved road locally known as Kiler Canyon Road, section 33, T26S/R11E. From the beginning point, proceed southerly and then southwesterly on Summit Canyon Road 
(locally known as Peachy Canyon Road) approximately 3.3 miles to the road&#39;s intersection with Willow Canyon Road 
(locally known as Vineyard Drive), Paso de Robles Land Grant; then 
(2) Proceed southerly on Willow Creek Road 
(locally known as Vineyard Drive) approximately 0.35 mile to its intersection with Dover Canyon Road; then 
(3) Proceed westerly then southerly on Dover Canyon Road approximately 1 mile to the road&#39;s intersection with the common boundary line of section 18, T27S/R11E, and the Paso de Robles Land Grant; then 
(4) Proceed east, south, and southeast along the Paso de Robles Land Grant Boundary line approximately 1.9 miles to the fourth crossing of an unnamed intermittent tributary of Jack Creek by the common boundary line of section 20, T27S/R11E, and the Paso de Robles Land Grant; then 
(5) Proceed northerly 
(downstream) along the unnamed intermittent tributary of Jack Creek approximately 0.15 mile to the tributary&#39;s confluence with Jack Creek, Paso de Robles Land Grant; then 
(6) Proceed southeasterly 
(downstream) along Jack Creek approximately 1.8 miles to the creek&#39;s intersection with an unnamed light-duty road locally known as Jack Creek Road 
(near BM 920), Paso de Robles Land Grant; then 
(7) Proceed northeasterly and then east-southeasterly along Jack Creek Road approximately 1 mile to the road&#39;s intersection with State Route 46; then 
(8) Proceed east on State Route 46 approximately 0.15 mile to the road&#39;s intersection with an unnamed light-duty road locally known as Hidden Valley Road, Paso de Robles Land Grant; then 
(9) Proceed southeasterly and then easterly on Hidden Valley Road approximately 2.2 miles, crossing onto the Templeton map, to the road&#39;s intersection with an unnamed light-duty road locally known as Vineyard Drive, Paso de Robles Land Grant; then 
(10) Proceed east on Vineyard Drive approximately 0.85 mile to the road&#39;s intersection with an unnamed light-duty road locally known as S. Bethel Road, Paso de Robles Land Grant; then 
(11) Proceed north-northeasterly on S. Bethel Road and then N. Bethel Road approximately 1.7 miles to the road&#39;s fifth intersection with an unnamed intermittent stream, Paso de Robles Land Grant; then 
(12) Proceed westerly 
(upstream) along the unnamed intermittent stream and then the stream&#39;s middle branch approximately 1.1 miles to the marked end of the stream, and then continue due west in a straight line approximately 0.05 mile to State Route 46 
(Cayucos Road), Paso de Robles Land Grant; then 
(13) Proceed northeasterly on State Route 46 
(Cayucos Road) approximately 0.8 mile to BM 924, Paso de Robles Land Grant; then 
(14) Proceed due north in a straight line to the southeast corner of section 12, T27S/R11E, and continue north along the eastern boundary line of section 12, a total of approximately 1.1 miles, to the section boundary line&#39;s intersection with a light-duty road locally known as Live Oak Road; then 
(15) Proceed easterly on Live Oak Road approximately 0.2 mile to the road&#39;s intersection with an unnamed intermittent stream, Paso de Robles Land Grant; then 
(16) Proceed northwesterly 
(upstream) along the unnamed intermittent stream approximately 0.35 mile to the eastern boundary line of section 12, T27S/R11E; then 
(17) Proceed north along the eastern boundary line of section 12, T27S/R11E, to the section&#39;s northeast corner, and then proceed east along the southern boundary line of section 6, T27S/R11E, a total of approximately 1.3 miles, to the intersection of the section 6 boundary line with an unnamed light-duty road locally known as Arbor Road; then 
(18) Proceed south-southeasterly on Arbor Road approximately 0.35 mile to the road&#39;s first intersection with an unnamed intermittent stream, Paso de Robles Land Grant; then 
(19) Proceed southeasterly and then easterly 
(downstream) along the unnamed intermittent stream approximately 1.4 miles to the stream&#39;s intersection with an unnamed light-duty road known locally as S. Vine Street, just west of the U.S. 101/State Route 46 interchange, Paso de Robles Land Grant; then 
(20) Proceed northerly along S. Vine Street 
(which generally parallels U.S. 101) approximately 1.8 miles to the street&#39;s intersection with the marked city of Paso Robles Corporate Boundary line 
(concurrent with the locally-known intersection of S. Vine and 1st Streets), Paso de Robles Land Grant; then 
(21) Proceed west, north, west, and north again along the marked city of Paso Robles Corporate Boundary line approximately 1 mile to the boundary line&#39;s junction with the intersection of an unnamed light-duty road locally known as Merry Hill Road and Peachy Canyon Road, Paso de Robles Land Grant; then 
(22) Proceed westerly on Peachy Canyon Road approximately 2.6 miles, crossing to and from the Paso Robles map, to the road&#39;s intersection with an unnamed intermittent stream near the center of section 36, T26S/R11E; then 
(23) Proceed south-southeasterly 
(downstream) along the unnamed intermittent stream approximately 1.2 miles to the stream&#39;s intersection with the eastern boundary line of section 1, T27S/R11E; then 
(24) Proceed south along the eastern boundary line of section 1, T27S/R11E, approximately 0.15 mile to the line&#39;s intersection with an unnamed light-duty road locally known as Kiler Canyon Road, section 1, T27S/R11E; then 
(25) Proceed westerly on Kiler Canyon Road approximately 3.7 miles, crossing onto the York Mountain map, returning to the beginning point.

**Comment by SoominHur** [comment]
Reviewed.
