### ISSUE TITLE
pine_mountain_cloverdale_peak

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#162]
# AVA: Pine Mountain-Cloverdale Peak (pine_mountain_cloverdale_peak)

name | value
--- | ---
ava_id | pine_mountain_cloverdale_peak
cfr_index | 9.220
revision | [T.D. TTB-96, 76 FR 66637, Oct. 27, 2011]
state | CA
county | Mendocino|Sonoma
within | North Coast\|Northern Sonoma
contains | Alexander Valley

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Asti Quadrangle—California, 1998; 
2. Cloverdale Quadrangle—California, 1960, photoinspected 1975; and 
3. Highland Springs Quadrangle—California, 1959, photorevised 1978.

## Boundary [src]

(1) The beginning point is on the Asti map at the intersection of Pine Mountain Road and the Sonoma-Mendocino County line, section 35, T12N, R10W. From the beginning point, proceed southwesterly on Pine Mountain Road to its intersection with a light duty road known locally as Green Road, section 33, T12N, R10W; then 
(2) Proceed northerly on Green Road approximately 500 feet to its first intersection with the 1,600-foot contour line, section 33, T12N, R10W; then 
(3) Proceed northwesterly along the meandering 1,600-foot contour line, crossing onto the Cloverdale map in section 32, T12N, R10W, and continue to the contour line&#39;s intersection with the eastern boundary line of section 31, T12N, R10W; then 
(4) Proceed straight north along the eastern boundary line of section 31, crossing the Sonoma-Mendocino line, to the boundary line&#39;s intersection with the 1,600-foot contour line on the west side of Section 29, T12N, R10W; then 
(5) Proceed northeasterly along the meandering 1,600-foot contour line to its intersection with the intermittent Ash Creek, section 29, T12N, R10W; then 
(6) Proceed northeasterly in a straight line, crossing onto the Asti map, to the unnamed 2,769-foot peak located south of Salty Spring Creek, section 20, T12N, R10W; then 
(7) Continue northeasterly in a straight line, crossing onto the Highland Springs map, to the unnamed 2,792-foot peak in the northeast quadrant of section 21, T12N, R10W; then 
(8) Proceed east-southeasterly in a straight line, crossing onto the Asti map, to the unnamed 2,198-foot peak in section 23, T12N, R10W; and then 
(9) Proceed south-southeasterly in a straight line, returning to the beginning point.

**Comment by SoominHur** [comment]
Reviewed. Corrected created date in attribute table.
