### ISSUE TITLE
potter_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#163]
# AVA: Potter Valley (potter_valley)

name | value
--- | ---
ava_id | potter_valley
cfr_index | 9.82
revision | [T.D. ATF-151, 48 FR 46521, Oct. 13, 1983]
state | CA
county | Mendocino
within | Mendocino\|North Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Boundary [src]

(1) From the beginning point at the southeast corner of quadrant 36 and southwest corner of quadrant 32 
(a point where Mendocino and Lake Counties border on the T. 17 N.-T. 16 N. township line), the boundary runs northwest to the northeastern corner of quadrant 4, on the T. 18 N.-T. 17 N. township line; 
(2) Then west to the northwest corner of quadrant 1; 
(3) Then south to the southwest corner of quadrant 36; 
(4) Then east to R. 12 W.-R. 11 W. range line at the southeast corner of quadrant 36; 
(5) Then south to Highway 20; 
(6) Then southeast on Highway 20 to where Highway 20 passes from quadrant 20 to quadrant 21; and 
(7) Thence northeast, returning to the point of beginning.

**Comment by SoominHur** [comment]
Reviewed
- Edit effective date in the attribute table.
