### ISSUE TITLE
ramona_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#165]
# AVA: Ramona Valley (ramona_valley)

name | value
--- | ---
ava_id | ramona_valley
cfr_index | 9.191
revision | [T.D. TTB-39, 70 FR 72719, Dec. 7, 2005]
state | CA
county | San Diego
within | South Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Borrego Valley, California, 1982 edition; and 
2. El Cajon, California, 1979 edition.

## Boundary [src]

(1) Beginning in the southwest corner of the Borrego Valley map at the 882-meter 
(2,894-foot) peak of Woodson Mountain, T13S, R1W, proceed straight north-northwest approximately 3.25 miles to the 652-meter 
(2,140-foot) peak of Starvation Mountain, T13S, R1W 
(Borrego Valley map); then 
(2) Proceed straight east-northeast approximately 12.5 miles to the Gaging Station on the northwest shoreline of Sutherland Lake, T12S, R2E 
(Borrego Valley map); then 
(3) Proceed straight southeast approximately 4.4 miles to the 999-meter 
(3,278-foot) peak of Witch Creek Mountain, T13S, R2E, east of Ballena Valley 
(Borrego Valley map); then 
(4) Proceed straight south-southeasterly approximately 6.6 miles, crossing onto the El Cajon map, to the summit of Eagle Peak 
(3,166 feet), T14S, R3E, northeast of the El Capitan Reservoir 
(El Cajon map); then 
(5) Proceed straight west-southwest approximately 12.7 miles, passing through Barona Valley, to the peak 
(1,002 feet) near the center of the unnamed island in the San Vicente Reservoir, T14S, R1E 
(El Cajon map); then 
(6) Proceed straight northwesterly approximately 3.9 miles to the 822-meter 
(2,697-foot) peak of Iron Mountain, T14S, R1W 
(El Cajon map); and 
(7) Proceed straight north-northwest approximately 2.8 miles, crossing onto the Borrego Valley map, and return to the beginning point at the peak of Woodson Mountain.

**Comment by SoominHur** [comment]
Reviewed.
- Add scale information of used maps in the attribute table.
