### ISSUE TITLE
rattlesnake_hills

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#166]
# AVA: Rattlesnake Hills (rattlesnake_hills)

name | value
--- | ---
ava_id | rattlesnake_hills
cfr_index | 9.193
revision | [T.D. TTB-43, 71 FR 8211, Feb. 16, 2006]
state | WA
county | Yakima
within | Yakima Valley\|Columbia Valley
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Yakima East Quadrangle, Washington—Yakima Co., 1953, photorevised 1985; 
2. Elephant Mountain Quadrangle, Washington—Yakima Co., 1953, photorevised 1985; 
3. Granger NW Quadrangle, Washington—Yakima Co., 1965; 
4. Granger NE Quadrangle, Washington—Yakima Co., 1964; 
5. Sunnyside Quadrangle, Washington—Yakima Co., 1965, photorevised 1978; 
6. Granger Quadrangle, Washington—Yakima Co., 1965; 
7. Toppenish Quadrangle, Washington—Yakima Co., 1958, photorevised 1985; and 
8. Wapato Quadrangle, Washington—Yakima Co., 1958, photorevised 1985.

## Boundary [src]

(1) The beginning point is on the Yakima East map at the point where a line drawn straight east from the west end of the Wapato Dam on the Yakima River intersects Interstate Highway 82, section 17, T12N/R19E. This line coincides with the boundary of the Yakima Valley viticultural area 
(27 CFR 9.69). From the beginning point, the Rattlesnake Hills viticultural area boundary line— 
(2) Proceeds straight eastward, crossing onto the Elephant Mountain map, to the 2,192-foot peak of Elephant Mountain, section 16, T12N/R20E; then 
(3) Continues straight east-southeast, crossing over the northeast corner of the Toppenish map, and continuing onto the Granger NW map, to the 2,186-foot pinnacle of Zillah Peak, section 32, T12N/R21E; then 
(4) Continues straight eastward, crossing onto the Granger NE map, to the 3,021-foot peak of High Top Mountain, section 32, T12N/R22E; then 
(5) Continues straight east-southeast to the 2,879-foot peak in the northeast quadrant of section 3, T11N/R22E, and continues in the same direction in a straight line until the line intersects with the 120°00  west longitude line in section 1 of T11N/R22E along the east margin of the Granger NE map; then 
(6) Proceeds straight south along the 120°00  west longitude line to its intersection with a set of power lines in section 24, T11N/R22E, on the east margin of the Granger NE map; then 
(7) Follows the power lines southwest, crossing onto the Sunnyside map, to their intersection with the Sunnyside Canal, section 8, T10N/R22E; then 
(8) Follows the meandering Sunnyside Canal generally northwest, crossing over the northeast corner of the Granger map, and continuing over the Granger NW map, the Toppenish map, and onto the Wapato map to the canal&#39;s intersection with Interstate Highway 82, section 27 west boundary line, T12N/R19E; then 
(9) Follows Interstate Highway 82 northwest for 2.75 miles, crosses onto the Yakima East map, and returns to the beginning point.

**Comment by alisonsnwong** [comment]
Checked! Performed minor boundary edits.
