### ISSUE TITLE
red_hill_douglas_county__oregon

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#167]
# AVA: Red Hill Douglas County, Oregon (red_hill_douglas_county__oregon)

name | value
--- | ---
ava_id | red_hill_douglas_county__oregon
cfr_index | 9.190
revision | [T.D. TTB-35, 70 FR 60001, Oct. 14, 2005]
state | OR
county | Douglas
within | Southern Oregon\|Umpqua Valley
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Sutherlin, OR 
Provisional edition 1988.; 
2. Scotts Valley, OR 
Provisional edition 1987.; and 
3. Yoncalla, OR 
Provisional edition 1987..

## Boundary [src]

(1) Beginning on the Yoncalla map along the southern boundary of section 35, T23S/R5W, at the point where a pipeline crosses the T23S/T24S township line, proceed due west 0.8 mile along the T23S/T24S township line to its intersection with the 800-foot contour line just west of Pollock Creek in section 34, T23S/R5W 
(Yoncalla Quadrangle); then 
(2) Proceed southerly along the meandering 800-foot contour line, cross onto the Sutherlin map in section 10, T24S/R5W, and continue westerly along the 800-foot contour line to its first intersection with the eastern boundary of section 8, T24S/R5W 
(Sutherlin Quadrangle); then 
(3) Proceed northerly along the meandering 800-foot contour line, return to the Yoncalla map in section 9, T23S/R5W, and continue northerly along the 800-foot contour line to its intersection with the T23S/T24S township line very near the northwest corner of section 4, T24S/R5W 
(Yoncalla Quadrangle); then 
(4) Proceed northeasterly along the 800-foot contour line, cross Wilson Creek in the northern portion of section 23, T23S/R5W, pass onto the Scotts Valley map at Section 14, T23S/R5W, and continue northeasterly along the 800-foot contour line to its intersection with the R4W/R5W range line, which at that point is also the eastern boundary of section 1, T23S/R5W 
(Scotts Valley Quadrangle); then 
(5) Proceed southwesterly along the 800-foot contour line, re-cross the R4W/R5W range line, and continue to the second intersection of the 800-foot contour line and the pipeline in section 1, T23/R5W 
(Scotts Valley Quadrangle); then 
(6) Proceed 5.75 miles southwesterly along the pipeline, cross Wilson Creek in section 24, T23S/R5W, return to the Yoncalla map in section 26, T23S/R5W, and continue southwesterly along the pipeline to the point of beginning at the intersection of the pipeline intersection and the T23S/T24S township line in section 35, T23S/R5W 
(Yoncalla Quadrangle).

**Comment by alisonsnwong** [comment]
Checked!
