### ISSUE TITLE
red_hills_lake_county

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#168]
# AVA: Red Hills Lake County (red_hills_lake_county)

name | value
--- | ---
ava_id | red_hills_lake_county
cfr_index | 9.169
revision | [T.D. TTB-15, 69 FR 41754, July 12, 2004; T.D. TTB-118, 78 FR 60688, Oct. 2, 2013]
state | CA
county | Lake
within | Clear Lake\|North Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Clearlake Highlands Quadrangle, CA—Lake Co. 1958, photorevised 1975; 
2. Lower Lake Quadrangle, CA—Lake Co. 1958, photorevised 1975; 
3. Whispering Pines Quadrangle, CA 1958, photoinspected 1975; 
4. Kelseyville Quadrangle—California. 1993.

## Boundary [src]

(1) Beginning on the Clearlake Highlands map at the intersection of the Clear Lake shoreline, south of Slater Island, with the common boundary line between sections 3 and 4, T12N, R7W, proceed approximately 0.1 miles due south along the common section line to its intersection with the 1,400-foot contour line, section 3, T12N, R7W 
(Clearlake Highlands Quadrangle); then 
(2) Proceed east-southeasterly along the meandering 1,400-foot contour line onto the Lower Lake map south of Anderson Flat, then reverse direction with the contour line and continue westerly, leaving the Lower Lake map, to the 1,400-foot contour line&#39;s intersection with Seigler Canyon Creek, section 10, T12N, R7W 
(Clearlake Highlands Quadrangle); then 
(3) Proceed generally west then south along Seigler Canyon Creek to its confluence with Perini Creek, section 9, R7W, T12N, and continue southerly about 1.2 miles along Perini Creek to its intersection with the 1,800-foot contour line, section 16, R7W, T12N 
(Clearlake Highlands Quadrangle); then 
(4) Continue southerly along the 1,800-foot contour line, crossing on to the Whispering Pines map, and, turning westerly, continue along the 1,800-foot contour line to its intersection with Copsey Creek, section 28, T12N, R7W 
(Whispering Pines Quadrangle); then 
(5) Proceed generally west-northwest along Copsey Creek to its headwaters in section 29, then continue straight west-southwesterly to the headwaters of Bad Creek at its intersection with the section 30 eastern boundary line, and, from that point, proceed approximately 0.1 miles due west to Big Canyon Road, section 30, T12N, R7W 
(Whispering Pines Quadrangle); then 
(6) Proceed about 1.1 miles north-northwesterly along Big Canyon Road, leaving the Whispering Pines map, to its intersection with Loch Lomond Road, northeast of Hoberg Airport, section 19, T12N, R7W 
(Clearlake Highlands Quadrangle); then 
(7) Proceed approximately 1.5 miles westerly then southerly along Loch Lomond Road, returning to the Whispering Pines map, passing through Seigler Springs, to the road&#39;s first intersection with the 2,640-foot contour line, northwest of Bonanza Springs, section 25, T12N, R8W 
(Whispering Pines Quadrangle); then 
(8) From that point, proceed about 1.9 miles northwesterly in a straight line, passing through the peak of Seigler Mountain, elevation 3,692 feet, and returning to the Clearlake Highlands map, to the line&#39;s intersection with Salmina Road, section 23, T12N, R8W 
(Clearlake Highlands Quadrangle); then 
(9) Proceed 1.25 miles northwesterly along Salmina Road to its intersection with State Highway 175, section 15, T12N, R8W 
(Clearlake Highlands Quadrangle); then 
(10) Proceed south 0.6 miles on State Highway 175 to its intersection with the section 15 southern boundary line, T12N, R8W 
(Clearlake Highlands Quadrangle); then 
(11) From that point, proceed about 1 mile in a straight northwesterly line to the peak of Mt. Hannah, elevation 3,978 feet, section 16, T12N, R8W 
(Clearlake Highlands Quadrangle); then 
(12) From the peak of Mt. Hannah, proceed about 0.8 miles in a westerly straight line, crossing on to the Kelseyville map, to the intersection of the 3,000-foot contour line with the section 17 east boundary line, and continue for about 0.45 miles along the same line of direction to the 2,800-foot contour line east of Boggs Lake, section 17, T12N, R8W 
(Kelseyville Quadrangle); then 
(13) Proceed northerly and then westerly along the 2,800-foot contour line around Boggs Lake to the contour line&#39;s intersection with Harrington Flat Road, section 18, T12N, R8W 
(Kelseyville Quadrangle); then 
(14) Proceed about 0.4 miles northwesterly along Harrington Flat Road to its intersection with Bottle Rock Road, and continue north-northwesterly along Bottle Rock Road for about 4 miles to its intersection with Cole Creek Road to the west and an unimproved road to the east, section 25, T13N, R9W 
(Kelseyville Quadrangle); then 
(15) Proceed east and then northeast approximately 0.4 mile along the unimproved road to the road&#39;s intersection with State Highway 29/175, then proceed east along State Highway 29/175 to the intersection of the highway with the 1,720-foot elevation line located just west of the 1,758-foot benchmark 
(BM) in section 25, T13N, R9W 
(Kelseyville Quadrangle); then 
(16) Proceed northwest along the 1,720-foot elevation line to the common boundary line between sections 25 and 26, T13N, R9W; then 
(17) Proceed north along the common boundary line between sections 25 and 26, T13N, R9W, and then the common boundary line between sections 23 and 24, T13N, R9W, 
(partially concurrent with Wilkinson Road) to the intersection of the common section 23-24 boundary line with the 1,600-foot elevation line 
(Kelseyville Quadrangle); then 
(18) Proceed about 1.35 miles straight easterly to the 2,493 benchmark located along an unnamed light-duty road known locally as Konocti Road, section 19, T13N, R8W 
(Kelseyville Quadrangle); then 
(19) Proceed less than 0.2 miles easterly and then northerly along the unnamed light-duty road to its intersection with the 2,600-foot elevation line, section 19, T13N, R8W 
(Kelseyville Quadrangle); then 
(20) Proceed about 3.0 miles generally east along the 2,600-foot elevation line to its intersection, north of Bell Mine, with an unnamed intermittent stream near the section 20 east boundary line, T13N, R8W 
(Kelseyville Quadrangle); then 
(21) Proceed about 1.2 miles in a straight east-northeasterly line to the intersection of Konocti Bay Road and Soda Bay Road, and continue due east to the shore of Clear Lake, section 22, T13N, R8W 
(Clearlake Highlands Quadrangle); then 
(22) Proceed southeasterly along the shoreline of Clear Lake, returning to the point of beginning at the shoreline&#39;s intersection with the common boundary line between sections 3 and 4, T12N, R7W 
(Clearlake Highlands Quadrangle).

**Comment by MicheleTobias** [comment]
@fyfangyao I figured out why there were two records for this AVA.  It should be fixed in the online data soon.

**Comment by SoominHur** [comment]
Reviewed.
- Add scale information of used maps.
