### ISSUE TITLE
redwood_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#170]
# AVA: Redwood Valley (redwood_valley)

name | value
--- | ---
ava_id | redwood_valley
cfr_index | 9.153
revision | [T.D. ATF-386, 61 FR 67466, Dec. 23, 1996, as amended by T.D. TTB-124, 79 FR 60972, Oct. 9, 2014]
state | CA
county | Mendocino
within | Mendocino\|North Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Redwood Valley, Calif., 1960, photorevised 1975; 
2. Ukiah, Calif., 1958, photorevised 1975; 
3. Laughlin Range, Calif., 1991; 
4. Orrs Springs, California, provisional edition, 1991.

## Boundary [src]

(1) The beginning point is in the northeastern portion of the Ukiah map at the point where State Highway 20 crosses the R11W/R12W range line along the south bank of the East Fork of the Russian River, T16N/R12W. From the beginning point, proceed north along the R11W/R12W range line, crossing onto the Redwood Valley map, to the northeast corner of section 1, T16N/R12W; then 
(2) Proceed west along the northern boundary of section 1 to the section&#39;s northwest corner, T16N/R12W; then 
(3) Proceed north along the eastern boundary lines of sections 35, 26, 23, 14, 11, and 2 to the T17N/T18N common boundary line at the northeast corner of section 2, T17N/R12W; then 
(4) Proceed west along the T17N/T18N common line to the northwest corner of section 6, T17N/R12W; then 
(5) Proceed south-southwesterly in a straight line, crossing onto the Laughlin Range map, to the intersection of the 1,400-foot contour line and Bakers Creek within McGee Canyon, section 25, T17N/R13W; then 
(6) Proceed southeasterly in a straight line approximately 1.5 miles, crossing onto the Redwood Valley map, to the southeast corner of section 36, T17N/R13W; then 
(7) Proceed west-southwesterly in a straight line approximately 0.55 mile, crossing onto the Laughlin Range map, to the intersection of U.S. Highway 101 and an unnamed road known locally as Reeves Canyon Road, section 1, T16N/R13W; then 
(8) Proceed southeasterly in a straight line approximately 0.9 mile, crossing onto the Redwood Valley map, to the southeast corner of section 1, T16N/R13W; then 
(9) Proceed south-southwesterly in a straight line approximately 0.65 mile to the intersection of an unnamed, unimproved road and an unnamed, intermittent stream, approximately 500 feet south of Seward Creek, section 12, T16N/R13W; then 
(10) Proceed west-southwesterly in a straight line approximately 0.9 mile, crossing onto the Laughlin Range map, to the southwest corner of section 12, T16N/R13W; then 
(11) Proceed east-southeasterly in a straight line, crossing onto the far northeastern corner of the Orrs Springs map, then continuing onto the Ukiah map, to the intersection of State Highway 20 and a road known locally as North State Street 
(old U.S. Highway 101), north of Calpella, T16N/R12W; then 
(12) Proceed easterly along State Highway 20, returning to the beginning point. Transition period.  A label containing the words “Redwood Valley” in the brand name or as an appellation of origin approved prior to November 10, 2014 may be used on wine bottled before November 10, 2016 if the wine conforms to the standards for use of the label set forth in §4.25 or §4.39
(i) of this chapter in effect prior to November 10, 2014.

**Comment by SoominHur** [comment]
Reviewed
- Add scale information of used maps in the attribute table.
