### ISSUE TITLE
ribbon_ridge

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#171]
# AVA: Ribbon Ridge (ribbon_ridge)

name | value
--- | ---
ava_id | ribbon_ridge
cfr_index | 9.182
revision | [T.D. TTB-27, 70 FR 31344, June 1, 2005]
state | OR
county | Yamhill
within | Chehalem Mountains\|Willamette Valley
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Laurelwood Quadrangle, Oregon, 1956, photorevised 1978; and 
2. Dundee Quadrangle, Oregon, 1956, revised 1993.

## Boundary [src]

(1) The beginning point is on the Laurelwood Quadrangle map at the intersection of a light-duty road known locally as Albertson Road and Dopp Road 
(named on the Dundee map), just east of the Lake View School, section 58, T2S, R3W. From the beginning point, the boundary line— 
(2) Continues south on Dopp Road for about 4.9 miles, crossing onto the Dundee map, to the road&#39;s intersection with North Valley Road, near the Erwin Young School, section 39, T3S, R3W 
(Dundee Quadrangle); then 
(3) Continues west then north on North Valley Road for about 5 miles, crossing over to the Laurelwood map, to the road&#39;s intersection with Laughlin and Albertson Roads, just west of the Lake View School, section 58, T2S, R3W 
(Laurelwood Quadrangle); then 
(4) Continues east on Albertson Road for about 0.2 miles and returns to the beginning point.

**Comment by gdmf** [comment]
Please tag ribbon_ridge as "In Progress". Thanks!

**Comment by alisonsnwong** [comment]
Checked!
