### ISSUE TITLE
river_junction

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#172]
# AVA: River Junction (river_junction)

name | value
--- | ---
ava_id | river_junction
cfr_index | 9.164
revision | [T.D. ATF-452, 66 FR 23592, May 9, 2001]
state | CA
county | San Joaquin
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Ripon, CA 1969, photorevised 1980;  
2. Vernalis, CA 1969, photorevised 1980.

## Boundary [src]

(1) Beginning on the Vernalis, CA quadrangle map at the intersection of the secondary highway Airport Way and the San Joaquin River levee, near Benchmark 35 in T3S/R6E;  
(2) Then in a southeasterly direction, follow the levee along the San Joaquin River onto the Ripon, CA quadrangle map;  
(3) Then in a northerly direction around Sturgeon Bend in section 18 T3S/R7E;  
(4) Then continuing in a generally southeasterly, then northeasterly direction along the levee adjoining the Stanislaus River through sections 19, 20 and 17 to the point where the levee intersects sections 17 and 8;  
(5) Then continuing in a northerly direction along the levee in section 8 for approximately 1,000 feet;  
(6) Then in a straight line in a northwesterly direction for approximately 100 feet to the intersection with Division Road;  
(7) Then in a southwesterly, then northwesterly direction along Division Road through sections 8, 17, 18 and 7 to the intersection with the secondary highway Airport Way;  
(8) Then in a southwesterly direction along Airport Way onto the Vernalis quadrangle map to the starting point at the intersection of Airport Way and the San Joaquin River levee T3S/R6E.

**Comment by fyfangyao** [comment]
I have finished this.
