### ISSUE TITLE
rockpile

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#173]
# AVA: Rockpile (rockpile)

name | value
--- | ---
ava_id | rockpile
cfr_index | 9.173
revision | [T.D. ATF-473, 67 FR 9193, Feb. 28, 2002]
state | CA
county | Sonoma
within | North Coast\|Northern Sonoma
contains | Dry Creek Valley

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Warm Springs Dam Quadrangle, CA—Sonoma Co. 1978; 
2. Cloverdale Quadrangle, CA 1975; 
3. Tombs Creek Quadrangle, CA—Sonoma Co. 1978; and 
4. Big Foot Mountain Quadrangle, CA 1991.

## Boundary [src]

(1) Then proceed straight north to the 800-foot contour line, Section 10, T 10 N, R 11 W 
(Warm Springs Dam Quadrangle); 
(2) Then proceed west along the 800-foot contour line through Sections 10, 9, 4, 5, and 32 to the Section 31 east boundary line, T 11 N, R 11 W 
(Warm Springs Dam and Cloverdale Quadrangles); 
(3) Then proceed west along the 800-foot contour line in Section 31, following the line as it reverses from the west to the east direction, returning to the east boundary of Section 31, T 11 N, R 11 W 
(Cloverdale and Big Foot Mountain Quadrangles); 
(4) Then proceed along the 800-foot contour line east through Section 32 and northwest through Sections 33, 32, 29, 30, 25, 24, 23, 14, 15, 22, 21, and 20 to the east boundary line of Section 19, T 11 N, R 12 W 
(Cloverdale and Big Foot Mountain Quadrangles); 
(5) Then proceed west, north, south and east along the meandering 800-foot contour line, in a loop, crossing the southwest and northwest headwaters of Galloway Creek, and returning to the east boundary line of Section 19, T 11 N, R 12 W 
(Big Foot Mountain Quadrangle); 
(6) Then proceed straight north to the Mendocino-Sonoma county boundary line, then follow the county line straight west to the R 13 and 12 W line, and continue straight south to the 1,600-foot contour line in the Section 19 southwest corner, T 11 N, R 12 W 
(Big Foot Mountain Quadrangle); 
(7) Then proceed southeast along the meandering 1,600-foot contour line to the Section 29 west boundary line, and continue straight south to the T 11 and 10 N boundary line, R 12 W 
(Big Foot Mountain Quadrangle); 
(8) Then proceed east along the T 11 and 10 N boundary line to the Section 1 west boundary line, R 12 W 
(Big Foot Mountain Quadrangle); 
(9) Then proceed south along the Section 1 west boundary line, turning east at the Section 1 south boundary and continue east to the northwest corner of Section 8, T 10 N, R 11 W 
(Big Foot Mountain, Tombs Creek and Warm Springs Dam Quadrangles); 
(10) Then proceed south along the west boundary of Section 8, turning east at its southwest corner, and continue east to the 876-foot elevation marker, T 10 N, R 11 W 
(Warm Springs Dam Quadrangle); 
(11) Then proceed straight south approximately 2,000 feet to the 800-foot contour line, T 10 N, R 11 W 
(Warm Springs Dam Quadrangle); 
(12) Then follow the 800-foot contour line as it meanders west, southeast, southwest, and east to the Section 14 west boundary, and then straight north, returning to the point of beginning at Rockpile Road, T 10 N, R 11 W 
(Warm Springs Dam Quadrangle).

**Comment by SoominHur** [comment]
Reviewed.
- Edited creation date in the attribute table.
- Added description about the beginning point in the attribute table.
