### ISSUE TITLE
rocky_knob

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#174]
# AVA: Rocky Knob (rocky_knob)

name | value
--- | ---
ava_id | rocky_knob
cfr_index | 9.43
revision | [T.D. ATF-124, 48 FR 1293, Jan. 12, 1983, as amended by T.D. ATF-249, 52 FR 5957, Feb. 27, 1987; T.D. TTB-91, 76 FR 5477, Feb. 1, 2011]
state | VA
county | Floyd|Patrick
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Boundary [src]

(1) The beginning point is the intersection of Virginia State Route Nos. 776 and 799 at Connors Grove. 
(2) Then follow State Route No. 799 south and east to the Blue Ridge Parkway. 
(3) Then south on the parkway to its first intersection with State Route No. 758. 
(4) Then follow State Route No. 758 east to the intersection of State Route No. 726 at the southern boundary of the Rocky Knob Recreation Area. 
(5) Then follow the boundary of the Rocky Knob Recreation Area south then in a northeastern direction to where the boundary first intersects State Route No. 8. 
(6) Then from that point at State Route No. 8, proceed northeast in a straight line to State Route No. 719 and Widgeon Creek at a point about 0.7 of a mile west of the intersection of State Route Nos. 719 and 710. 
(7) Then proceed northwest in a straight line to the intersection with State Route No. 710 and the Blue Ridge Parkway. 
(8) Then follow the Parkway southwest to the intersection with State Route No. 726. 
(9) Then turn right on State Route No. 726 and proceed 0.6 of a mile to a roadway at the 3308 elevation point on the map. 
(10) Then from that point, proceed west in a straight line back to the starting point at Connors Grove.

**Comment by bsllee** [comment]
I'll start working on this AVA, thank you!

**Comment by alisonsnwong** [comment]
Checked! Updated `used_maps` section.
