### ISSUE TITLE
rogue_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#175]
# AVA: Rogue Valley (rogue_valley)

name | value
--- | ---
ava_id | rogue_valley
cfr_index | 9.132
revision | [T.D. ATF-310, 56 FR 2435, Jan. 23, 1991]
state | OR
county | Jackson|Josephine
within | Southern Oregon
contains | Applegate Valley

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Boundary [src]

(1) Beginning at the point of intersection of Interstate 5 and the Josephine County/Douglas County line approximately 20 miles north of Grants Pass, the boundary proceeds southerly and southwesterly along U.S. Interstate 5 to and including the town of Wolf Creek; 
(2) Then westerly and southerly out of the town of Wolf Creek along the Southern Pacific Railway Line to and including the town of Hugo; 
(3) Then southwesterly along the secondary, hard surface road known as Hugo Road to the point where the Hugo Road crosses Jumpoff Joe Creek; 
(4) Then westerly and down stream along Jumpoff Joe Creek to the intersection of Jumpoff Joe Creek and the Rogue River; 
(5) Then northwesterly and down stream along the Rogue River to the first point where the Wild and Scenic Rogue River designated area touches the easterly boundary of the Siskiyou National Forest just south of Galice; 
(6) Then in a generally southwesterly direction 
(with many diversions) along the easterly border of the Siskiyou National Forest to the 42 degree 0 minute latitude line; 
(7) Then easterly along the 42 degree 0 minute latitude line to the point where the Siskiyou National Forest again crosses into Oregon approximately 1 mile east of U.S. Highway 199; 
(8) Then in a generally northeasterly direction and then a southeasterly direction 
(with many diversions) along the northern boundary of the Siskiyou National Forest to the point where the Siskiyou National Forest touches the Rogue River National Forest at Big Sugarloaf Peak; 
(9) Then in a generally easterly direction 
(with many diversions) along the northern border of the Rogue River National Forest to the point where the Rogue River National Forest intersects with Slide Creek approximately 6 miles southeast of Ashland; 
(10) Then southeasterly and northeasterly along Slide Creek to the point where it intersects State Highway 273; 
(11) Then northwesterly along State Highway 273 to the point where it intersects State Highway 66; 
(12) Then in an easterly direction approximately 5 miles along State Highway 66 to the east line of Township 39 South, Range 2 East 
(T39S, R2E); 
(13) Then following the east line of T39S, R2E, in a northerly direction to the northeast corner of T39S, R2E; 
(14) Then westerly approximately 5 miles along the north line of T39S, R2E, to the 2,600 foot contour line; 
(15) Then in a northerly direction following the 2,600 foot contour line across Walker Creek and then in a southwesterly direction to the point where the 2,600 foot contour line touches the east line of T38S, R1E; 
(16) Then northerly along the east line of T38S, R1E, to the northeast corner of T38S, R1E; 
(17) Then westerly along the north line of T38S, R1E, to the northwest corner of T38S, R1E; 
(18) Then northerly along the west line of T37S, R1E, to the northwest corner of T37S, R1E. 
(19) Then easterly along the north lines of T37S, R1E, and T37S, R2E, to the southeast corner of T36S, R2E; 
(20) Then northerly along the east line of T36S, R2E, to the northeast corner of T36S, R2E; 
(21) Then westerly along the north line of T36S, R2E, to the northwest corner of T36S, R2E; 
(22) Then northerly along the east line of T35S, R1E, to the northeast corner of T35S, R1E; 
(23) Then westerly along the north line of T35S, R1E, to the northwest corner of T35S, R1E; 
(24) Then northerly along the east line of T34S, R1W, to the northeast corner of T34S, R1W; 
(25) Then westerly along the north lines of T34S, R1E; T34S, R2W; T34S, R3W; T34S, R4W; and T34S, R5W, to the northwest corner of T34S, R5W; 
(26) Then northerly along the west line of T33S, R5W, to the Josephine County/Douglas County line; 
(27) Then westerly along the Josephine County/Douglas County line to U.S. Interstate 5, the point of beginning.

**Comment by gdmf** [comment]
Please add the "In Progress" label to this one.
