### ISSUE TITLE
russian_river_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#176]
# AVA: Russian River Valley (russian_river_valley)

name | value
--- | ---
ava_id | russian_river_valley
cfr_index | 9.66
revision | [T.D. ATF-159, 48 FR 48813, Oct. 21, 1983, as amended by T.D. ATF-249, 52 FR 5959, Feb. 27, 1987; T.D. TTB-7, 68 FR 67370, Dec. 2, 2003; T.D. TTB-32, 70 FR 53299, Sept. 8, 2005; T.D. TTB-97, 76 FR 70877, Nov. 16, 2011]
state | CA
county | Sonoma
within | North Coast\|Northern Sonoma\|Sonoma Coast
contains | Alexander Valley\|Chalk Hill\|Green Valley of Russian River Valley

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Healdsburg, California Quadrangle—Sonoma Co., 7.5 Minute Series, edition of 1993; 
2. Guerneville, California Quadrangle—Sonoma Co., 7.5 Minute Series, edition of 1993; 
3. Cazadero, California Quadrangle—Sonoma Co., 7.5 Minute Series, edition of 1978; 
4. Duncans Mills California Quadrangle—Sonoma Co., 7.5 Minute Series, edition of 1979; 
5. Camp Meeker, California Quadrangle—Sonoma Co., 7.5 Minute Series, edition of 1995; 
6. Valley Ford, California Quadrangle, 7.5 Minute Series, edition of 1954; photorevised 1971; 
7. Two Rock, California Quadrangle, 7.5 Minute Series, edition of 1954; photorevised 1971; 
8. Sebastopol, California Quadrangle—Sonoma Co., 7.5 Minute Series, edition of 1954; photorevised 1980; 
9. Santa Rosa, California Quadrangle—Sonoma Co., 7.5 Minute Series, edition of 1954;  
10. Mark West Springs, California Quadrangle, 7.5 Minute Series, edition of 1998; 
11. Jimtown, California Quadrangle—Sonoma Co., 7.5 Minute Series, edition of 1993; and 
12. Cotati Quadrangle, California—Sonoma Co., scale 1:24 000, 1954, photorevised 1980.

## Boundary [src]

(1) Starting point Healdsburg map-Healdsburg Avenue Bridge over the Russian River at Healdsburg. Proceed south along Russian River to the point where Russian River and Dry Creek converge, from this point proceed west in a straight line to Forman Lane. 
(2) Proceed west along Foreman Lane to where it crosses Westside Road and becomes Felta School Road. 
(3) Proceed west on Felta School Road to the point where it crosses Felta Creek. 
(4) Proceed 18000  up Felta Creek to its headwaters as shown on the  Guerneville, map  as “Springs.” 
(5) Proceed southwest in a straight line 58 degrees W 27000  to an intersection with Hulbert Creek on the Cazadero map. 
(6) Proceed south and southeast along Hulbert Creek to the point where it intersects California Hwy 116 on the Duncan Mills map. 
(7) Proceed in a westerly direction along California Hwy 116 to Monte Rio where it intersects the Bohemian Hwy. 
(8) Proceed southeast along the Bohemian Highway, crossing over the Camp Meeker map, to the town of Freestone, where the highway intersects at BM 214 with an unnamed medium-duty road 
(known locally as Bodega Road, section 12, T6N, R10W, on the Valley Ford map). 
(9) Proceed 0.9 mile northeast on Bodega Road to its intersection, at BM 486, with Jonvive Road to the north and an unnamed light duty road to the south, 
(known locally as Barnett Valley Road, T6N, R9W, on the Camp Meeker map). 
(10) Proceed 2.2 miles south, and then east, on Barnett Valley Road, crossing over the Valley Ford map, to its intersection with Burnside Road in section 17, T6N, R9W, on the Two Rock map. 
(11) Proceed 3.3 miles southeast on Burnside Road to its intersection with an unnamed medium duty road at BM 375, T6N, R9W, on the Two Rock map. 
(12) Proceed 0.6 mile straight southeast to an unnamed 610-foot elevation peak, 1.5 miles southwest of Canfield School, T6N, R9W, on the Two Rock map. 
(13) Proceed 0.75 mile straight east-southeast to an unnamed 641-foot elevation peak, 1.4 miles south-southwest of Canfield School, T6N, R9W, on the Two Rock map. 
(14) Proceed 0.85 mile straight northeast to the intersection with an unnamed intermittent stream and Canfield Road; continue 0.3 mile straight in the same northeast line of direction to its intersection with the common boundary of Ranges 8 and 9, just west of an unnamed unimproved dirt road, T6N, on the Two Rock map. 
(15) Proceed southeast 0.5 mile, crossing over the end of an unnamed, unimproved dirt road to an unnamed 524-foot elevation peak, T6N, R8W, on the Two Rock map. 
(16) Proceed southeast 0.75 mile in a straight line to the intersection of an unnamed unimproved dirt road 
(leading to four barn-like structures) and an unnamed medium-duty road 
(known locally as Roblar Road), T6N, R8W, on the Two Rock map. 
(17) Proceed south 0.5 mile to an unnamed 678-foot elevation peak just slightly north of the intersection of T5N and T6N, R8W, on the Two Rock map. 
(18) Proceed east-southeast 0.8 mile to an unnamed peak with a 599-foot elevation, T5N, R8W, on the Two Rock map. 
(19) Proceed east-southeast 0.7 mile to an unnamed peak with a 604-foot elevation, T5N, R8W, on the Two Rock map. 
(20) Proceed east-southeast 0.9 mile to the intersection of a short, unnamed light-duty road leading past a group of barn-like structures and a medium duty road known locally as Meacham Road, and cross on to the Cotati map T5N, R8W. 
(21) Proceed north-northeast 0.75 mile to the intersection of Meacham and Stony Point Roads, T5N, R8W, on the Cotati map. 
(22) Proceed southeast 1.1 miles along Stony Point Road to the point where the 200-foot elevation contour line intersects Stony Point Road, T5N, R8W, on the Cotati map. 
(23) Proceed north-northeast 0.5 mile to the point where an unnamed intermittent stream intersects U.S. 101, T5N, R8W, on the Cotati map. 
(24) Proceed north 4.25 miles along U.S. 101 to the point where Santa Rosa Avenue exits U.S. 101 
(approximately 0.5 mile north of the Wilfred Avenue overpass) T6N, R8W, on the Cotati map. 
(25) Proceed north 1.1 miles along Santa Rosa Avenue to its intersection with Todd Road, crossing on to the Santa Rosa map, T6N, R8W, on the Santa Rosa map. 
(26) Proceed 5.8 miles generally north along Santa Rosa Avenue, which becomes Mendocino Avenue, to its intersection with an unnamed secondary road, known locally as Bicentennial Way, 0.3 mile north-northwest of BM 161 on Mendocino Avenue, section 11, T7N, R8W, on the Santa Rosa map. 
(27) Proceed 2.5 miles straight north, crossing over the 906-foot elevation peak in section 35 of the Santa Rosa map, to its intersection with Mark West Springs Road and the meandering 280-foot elevation in section 26, T8N, R8W, of the Mark West Springs map. 
(28) Proceed 4.8 miles north-northwest along Mark West Springs Road, which becomes Porter Creek Road, to its intersection with Franz Valley Road, a light-duty road to the north of Porter Creek Road, in section 12, T8N, R8W, on the Mark West Springs map. 
(29) Proceed in a northerly direction along Franz Vally Road to the northerly most crossing of Franz Creek. 
(30) Proceed west along Franz Creek until it intersects the line separating Section 21 and Section 22. 
(31) Proceed south on this line separating Section 21 and 22 to the corner common to Section 21 and 22 and Section 27 and 28. 
(32) Proceed west from the common corner of Section 21 and 22 and 27 and 28 and in a straight line to the peak of Chalk Hill on the  Healdsburg map. 
(33) Proceed west from the peak of Chalk Hill in a straight line to the point where Brooks Creek joins the Russian River. 
(34) Proceed north west in a straight line 8000  to a peak marked 772  elv. on the  Jimtown map. 
(35) Proceed north west in a straight line from hill top 772  elv. to hill top 596  elv. 
(36) Proceed north west in a straight line from hill top 596  elv. to hill top 516  elv. 
(37) Proceed north west in a straight line from hill top 516  elv. to hill top 530  elv. 
(38) Proceed west in a straight line from hill top 530  elv. to hill top 447  elv. 
(39) Proceed west in a straight line from hill top 447  elv. to the point where Alexander Valley Road meets Healdsburg Avenue. 
(40) Proceed south along Healdsburg Avenue through the city of Healdsburg on the  Healdsburg map  to the point where it crosses the Russian River at the point of beginning.

**Comment by SoominHur** [comment]
Reviewed
- Edit typo in cfr_author name in the attribute table.
- Edit created date in the attribute table.
- Edit the information of some maps in the attribute table because they omitted its edition years.
- The line should (2) "proceed west along Foreman Lane to where it crosses Westside Road and becomes Felta School Road." But according to the google map, the line followed along Bramkampo Rd in the middle. So I edit the line to just proceed along Foreman Ln.
- Move the node at the intersection with an unnamed intermittent stream and unimproved/unnamed road to (14) the intersection with an unnamed intermittent stream and Canfield Road. Following are two more reasons why I thought the location of the previous node is wrong; if the line proceed "straight in the same northeast ... direction to its intersection with the common boundary of Ranges 8 and 9," that intersection should be "just west of an unnamed unimproved dirt road, T6N, on the Two Rock map." Also, from that intersection point with Ranges 8/9, the line should (15) "proceed southeast 0.5 mile, crossing over the end of an unnamed, unimproved dirt road to an unnamed 524-foot elevation peak, T6N, R8W, on the Two Rock map." However, these requirements does not apply with previous node.
- There is a shorter/unnamed road above the location of previous node at the end of longer/unnamed road. So I move the node to the intersection of that shorter (20) "unnamed light-duty road leading past a group of barn-like structures and ... Meacham Road ... on to the Cotati map T5N, R8W" so the distance (21) "to the intersection of Meacham and Stony Point Roads, T5N, R8W, on the Cotati map" can be approximately 0.75 mile.
- Edit the node because it was at the intersection between Healdsburg Ave and Chiquita Rd instead of (39) "the point where Alexander Valley Road meets Healdsburg Avenue."

**Comment by elistockwell** [comment]
While creating history for this AVA (see #618) I was unsure about step 5 "Proceed southwest in a straight line 58 degrees W 27000 to an intersection with Hulbert Creek on the Cazadero map."  The only way that the compass bearing made sense in the context of the map was as 58 degrees West of South, or 238 degrees.  However, this resulted in a length of ~33000'.  Instead, we decided to just find the point closest to this bearing where the length was 27000', which ended up being at an angle between 250-255 degrees.
