### ISSUE TITLE
rutherford

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#177]
# AVA: Rutherford (rutherford)

name | value
--- | ---
ava_id | rutherford
cfr_index | 9.133
revision | [T.D. ATF-342, 58 FR 35876, July 2, 1993]
state | CA
county | Napa
within | Napa Valley\|North Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Yountville Quadrangle, California,” edition of 1951, photorevised 1968. 
2. “Rutherford Quadrangle, California,” edition of 1951, photorevised 1968, photoinspected 1973.

## Boundary [src]

(1) Beginning on the Yountville quadrangle map at the point where the county road known as the Silverado Trail intersects Skellenger Lane, just outside the southwest corner of Section 12, Township 7 North 
(T.7 N.), Range 5 West 
(R.5 W.), the boundary proceeds in a southwesterly direction in a straight line approximately 1.7 miles along Skellenger Lane, past its intersection with Conn Creek Road, to the point of intersection with the main channel of the Napa River 
(on the “Rutherford” map); 
(2) Then south along the center of the river bed approximately .4 miles to the point where an unnamed stream drains into the Napa River from the west; 
(3) Then along the unnamed stream in a generally northwesterly direction to its intersection with the west track of the Southern Pacific Railroad Track; 
(4) Then southeasterly along said railroad track 1,650 feet to a point which is approximately 435 feet north of the centerline of the entry road to Robert Mondavi Winery 
(shown on the map) to the southeast corner of Assessor&#39;s Parcel Number 27-250-14; 
(5) Thence southwesterly S 55°06  W for 3,869 feet along the common boundary between Assessor&#39;s Parcel Numbers 27-250-14 and 27-280-50/51 to the southwest corner of Assessor&#39;s Parcel Number 27-250-14; 
(6) Thence northwesterly N 40°31  W for 750 feet along the westerly property line of Assessor&#39;s Parcel Number 27-250-14; 
(7) Thence southwesterly S 51°00  W in a straight line to the 500-foot contour line of the Mayacamas Range in the northwestern corner of Section 28, T.7 N., R.5 W.; 
(8) Then proceeding along the 500-foot contour line in a generally northwesterly direction in T.7 N., R.5 W. through Sections 21, 20, 17, 18, 17, and 18 to the northwest portion of Section 7 where the 500-foot contour line intersects a southwestward straight line extension of the light-duty road known as Inglewood Avenue; 
(9) Thence in a straight line in a northeasterly direction along this extension of Inglewood Avenue to its intersection with the north fork of Bale Slough; 
(10) Thence in a southeasterly direction along the north fork of Bale Slough approximately 2,750 feet to its intersection with the end of the county road shown on the map as Zinfandel Avenue, known locally as Zinfandel Lane, near the 201-foot elevation marker; 
(11) Then in a northeasterly direction along Zinfandel Avenue 
(Zinfandel Lane) approximately 2.12 miles to the intersection of that road and Silverado Trail, then continuing northeasterly in a straight line to the 380-foot contour line; 
(12) Then following the 380-foot contour line southeasterly through Section 33 to the western border of Section 34, T.8 N., R.5 W., then following that section line north to the 500-foot contour line; 
(13) Then following the 500-foot contour line southeasterly to the western border of Section 2, T.7 N., R.5 W., then south along that section line past Conn Creek to its intersection with the 500-foot contour line northwest of the unnamed 832-foot peak; 
(14) Then continuing in a westerly direction and then a generally southeasterly direction along the 500-foot contour line through Sections 3, 2, 11 and 12 to the intersection of that contour line with the southern border of Section 12 
(on Yountville map); 
(15) Then proceeding in a straight line in a westerly direction to the intersection of the Silverado Trail with Skellenger Lane, the point of beginning.

**Comment by SoominHur** [comment]
Continue Reviewing
- (3) Extended line along unnamed stream until it actually"intersection with the west track of the Southern Pacific Railroad Track" because the line moved to railroad before the stream actually intersects railroad.
- (4) Moved node because it located near BM 149 instead of "southeast corner of Assessor's Parcel Number 27-250-14."
- (7) Moved node located near the center of section 28 instead of "northwestern corner of Section 28, T.7 N., R.5 W."
- (9) Removed extra nodes so the line can move from the 500' contour to the Bale Slough "... along this extension of Inglewood Avenue to its intersection with the north fork of Bale Slough"
