### ISSUE TITLE
saddle_rock__malibu

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#178]
# AVA: Saddle Rock- Malibu (saddle_rock__malibu)

name | value
--- | ---
ava_id | saddle_rock__malibu
cfr_index | 9.203
revision | [T.D. TTB-52, 71 FR 40400, July 17, 2006]
state | CA
county | Los Angeles
within | Malibu Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Boundary [src]

(1) The beginning point is on the Point Dume map at the intersection of Decker Road and Mulholland Highway, section 3, T1S/R19W; 
(2) From the beginning point, proceed north-northeast along Decker Road approximately 0.7 mile to its intersection with the southern boundary of the El Conejo land grant, section 3, T1S/R19W; then 
(3) Proceed straight east-southeast along the El Conejo land grant boundary line approximately 0.4 mile to the point where the land grant boundary line changes direction to the northeast, section 2, T1S/R19W; then 
(4) Proceed straight northeast for approximately 0.5 mile along the El Conejo land grant boundary line to its second intersection with the 1,700-foot contour line in section 2, T1S/R19W; then 
(5) Proceed southeasterly along the meandering 1,700-foot contour line, crossing the R19W/R18W range line near the southwest corner of section 6, T1S/R18W, and continue along the 1,700-foot contour line to its intersection with Kanan Road near the southwest corner of section 6, T1S/R18W; then 
(6) Proceed south along Kanan Road approximately 0.35 mile to its intersection with the 1,800-foot contour line 
(very near the intersection of Kanan Road and an unnamed unimproved road), section 7, T1S/R18W; then 
(7) Proceed southeasterly along the meandering 1,800-foot contour line to a point approximately 200 feet due north of the intersection of Mulholland Highway and two unnamed, unimproved roads near the center of section 7, T1S/R18W, and, from that point, proceed due south in a straight line to the intersection of Mulholland Highway and the two unnamed, unimproved roads, section 7, T1S/R18W; then 
(8) Following the eastern-most unimproved road, proceed southerly along the meandering unimproved road, passing to the west of a 2,054-foot peak, and continue to the road&#39;s intersection with another unnamed, unimproved road immediately south of the section 18 north boundary line and due east of a 2,448-foot peak, section 18, T1S/R18W; then 
(9) Proceed southwesterly along the unnamed, unimproved road to its intersection with the Latigo Canyon Road, just east of BM 2125, section 18, T1S/R18W; then 
(10) Proceed northerly then westerly along Latigo Canyon Road to its intersection with Kanan Road very near the southeast corner of section 12, T1S/R19W; then 
(11) Proceed south along Kanan Road for approximately 0.6 mile to its intersection with the 1,700-foot contour line, located immediately south of the four-way intersection of two unnamed, unimproved roads and Kanan Road, section 13, T1S/R19W; then 
(12) Proceed 1.5 miles generally west and northwest along the unnamed, unimproved road that meanders westerly, crossing over several intermittent streams, and continues through Zuma Canyon to its intersection with Encinal Canyon Road at about the 1,806-foot elevation mark, section 11, T1S/R19W; then 
(13) Crossing Encinal Canyon Road, proceed northwesterly along the unnamed, unimproved road, which becomes a trail, and continue northerly to the trail&#39;s intersection with the 1,900-foot contour line, near the center of section 11, T1S/R19W; then 
(14) Proceed northwesterly along the meandering 1,900-foot contour line, circling to the west of the 2,189-foot peak in section 11, to the contour line&#39;s intersection with Mulholland Highway at the northern boundary of section 11, T1S/R19W; then 
(15) Proceed westerly about 0.8 mile on Mulholland Highway and return to the beginning point.

**Comment by SoominHur** [comment]
Reviewed
