### ISSUE TITLE
salado_creek

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#179]
# AVA: Salado Creek (salado_creek)

name | value
--- | ---
ava_id | salado_creek
cfr_index | 9.163
revision | [T.D. TTB-13, 69 FR 38833, June 29, 2004]
state | CA
county | Stanislaus
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Patterson, California Quadrangle,—Stanislaus Co., 7.5 Minute Series, edition of 1953; photorevised 1971, photoinspected 1978; and 
2. Crows Landing, California Quadrangle,—Stanislaus Co., 7.5 Minute Series, edition of 1952, photorevised 1980.

## Boundary [src]

(1) Beginning on the Patterson Quadrangle map, section 19, T6S, R8E, at the intersection of Interstate Highway 5 and Fink Road, proceed northwest for 4.25 miles along Interstate 5 to its junction with an unnamed light duty road in section 35, T5S, R7E; then 
(2) Follow the unnamed light duty road for approximately 0.45 miles, going east across the California Aqueduct and then north, to the road&#39;s intersection with the light duty road atop the levee on the east bank of the Delta-Mendota Canal in section 35, T5S, R7E; then 
(3) Proceed southeast approximately 0.3 miles along the Delta-Mendota Canal levee road to its intersection with an unnamed unimproved road in section 35, T5S, R7E; then 
(4) Proceed north and then east on the unimproved road for approximately 0.4 mile to its intersection with Baldwin Road and continue east on Baldwin Road approximately one mile, crossing Salado Creek, to the Baldwin Road&#39;s intersection with Ward Avenue at the eastern boundary line of section 36, T5S, R7E; then, 
(5) Proceed north on Ward Avenue approximately 400 feet to its intersection with the 2nd Lift drainage canal in section 31, T5S, R8E; then 
(6) Follow the 2nd Lift canal southeast approximately 0.75 miles to its intersection with Elfers Road in section 31, T5S, R8E; then 
(7) Proceed east on Elfers Road approximately for 0.45 miles, crossing onto the Crows Landing Quadrangle map, to its intersection with an unnamed, unimproved road on the south side of Elfers Road that also marks the western boundary of section 6, T6S, R8E; then 
(8) Proceed straight south on the unimproved road approximately one mile to its intersection with Marshall Road in section 6, T6S, R8E; then 
(9) Follow Marshall Road straight west 1.1 miles, crossing onto the USGS Patterson map, to its intersection with Ward Avenue in section 6, T6S, R8E; then 
(10) Proceed south 1.65 miles on Ward Avenue to its intersection with the California Aqueduct, then continue generally south approximately 1.4 miles along the aqueduct to its intersection with Fink Road in section 19, T6S, R8E; then 
(11) Follow Fink Road northwest for approximately 0.5 miles, returning to the beginning point at the intersection of Interstate Highway 5 and Fink Road in section 19, T6S, R8E.

**Comment by MicheleTobias** [comment]
I'm working on this one.

**Comment by SoominHur** [comment]
Reviewed. Nothing to Correct.
