### ISSUE TITLE
anderson_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#18]
# AVA: Anderson Valley (anderson_valley)

name | value
--- | ---
ava_id | anderson_valley
cfr_index | 9.86
revision | [T.D. ATF-139, 48 FR 37370, Aug. 18, 1983]
state | CA
county | Mendocino
within | Mendocino \|North Coast
contains | Mendocino Ridge

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Navarro Quadrangle, California—Mendocino Co.,” 15 minute series 
1961.; 
2. “Boonville Quadrangle, California—Mendocino Co.,” 15 minute series 
1959.; and 
3. “Ornbaun Valley Quadrangle, California,” 15 minute series 
1960..

## Boundary [src]

(1) From the beginning point, the boundary runs southeasterly in a straight line to an unnamed hilltop 
(elevation 2015 feet) in the northeast corner of Section 9, T.13N., R.13W., located in the southeast portion of U.S.G.S. map “Boonville Quadrangle”; 
(2) Then southwesterly in a straight line to Benchmark 
(BM) 680 in Section 30, T.13N., R.13W., located in the northeast portion of U.S.G.S. map “Ornbaun Valley Quadrangle”; 
(3) Then northwesterly in a straight line to the intersection of an unnamed creek and the south section line of Section 14, T.14N., R.15W., located in the southwest portion of U.S.G.S. map “Boonville Quadrangle”; 
(4) Then in a westerly direction along the south section lines of Sections 14, 15, and 16, T.14N., R.15W., to the intersection of the south section line of Section 16 with Greenwood Creek, approximately .2 miles west of Cold Springs Road which is located in the southeast portion of U.S.G.S. map “Navarro Quadrangle”; 
(5) Then in a southwesterly and then a northwesterly direction along Greenwood Creek to a point in Section 33 directly south 
(approximately 1.4 miles) of Benchmark 
(BM) 1057 in Section 28, T.15N., R.16W.; 
(6) Then directly north in a straight line to Benchmark 
(BM) 1057 in Section 28, T.15N., R.16W.; 
(7) Then in a northeasterly direction in a straight line to the beginning point.

**Comment by SoominHur** [comment]
Reviewed.
- Edit created date in the attribute table.
- Add description about the beginning point in the attribute table.
