### ISSUE TITLE
san_antonio_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#180]
# AVA: San Antonio Valley (san_antonio_valley)

name | value
--- | ---
ava_id | san_antonio_valley
cfr_index | 9.194
revision | [T.D. TTB-46, 71 FR 33242, June 8, 2006]
state | CA
county | Monterey
within | Central Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Hames Valley, California, 1949, photorevised 1978; 
2. Tierra Redonda Mountain, California, 1949, photorevised 1979; 
3. Bradley, California, 1949, photorevised 1979; 
4. Bryson, California, 1949, photorevised 1979; 
5. Williams Hill, California, 1949, photorevised 1979; 
6. Jolon, California, 1949; 
7. Alder Peak, California, 1995; 
8. Bear Canyon, California, 1949, photoinspected 1972; 
9. Cosio Knob, California, 1949, photorevised 1984; and 
10. Espinosa Canyon, California, 1949, photorevised 1979.

## Boundary [src]

(1) The beginning point is at the southeast corner of section 14, T23S, R9E, on the Hames Valley map; 
(2) From the beginning point, proceed southeast in a straight line for approximately 5 miles across sections 24 and 25, T23S, R9E, and sections 30, 31, and 32, T23S, R10E, and section 5, T24S, R10E, to the southeast corner of section 5, on the Tierra Redonda Mountain map; then 
(3) Continue southeast in a straight line for approximately 3.25 miles through sections 9, 16, 15, and 22, T24S, R10E, to the mid-point of the eastern boundary of section 22 on the Bradley map; then 
(4) Proceed straight south for approximately 2.5 miles along the eastern boundary line of sections 22, 27, and 34, T24S, R10E, to the Monterey-San Luis Obispo County line; then 
(5) Follow the Monterey-San Luis Obispo County line west for approximately 7.0 miles, back onto the Tierra Redonda Mountain map, to the southwest corner of section 34, T24S, R9E; then 
(6) Proceed northwest in a straight line for approximately 17 miles, crossing sections 33, 32, 29, 30, and 19, T24S, R9E, and sections 24, 13, 14, 10, 9, and 4, T24S, R8E, on the Bryson map, section 5, T24S, R8E in the southwest corner of the Williams Hill map, section 32, T23S, and sections 23, 22, 15, and 16, T23S, R7E, on the Jolon map, to an 1,890-foot peak located approximately 2,100 feet west of section 8, T23S, R7E; then 
(7) Continue northwest in a straight line for approximately 9 miles, crossing the Alder Peak map between Milpitas Grant and Stony Valley, and sections 9, 4, and 5, T22S, R6E, on the Bear Canyon map, to a 2,713-foot peak located in section 5, T22S, R6E; then 
(8) Proceed east-northeast in a straight line for approximately 3.9 miles, passing onto the Hunter Liggett Military Reservation and crossing the San Antonio River, to a 2,449-foot peak on the Hunter Liggett Military Reservation; then 
(9) Proceed northeast in a straight line for approximately 2.5 miles, crossing Mission Creek, across sections 30 and 29, T21S, R7E, on the Cosio Knob map to the 2,530-foot peak of Cosio Knob; then 
(10) From Cosio Knob, proceed east-southeast in a straight line for approximately 9.5 miles across sections 29, 28, 27, 26, 35, and 36, T21S, R7E, sections 31 and 32, T21S, R8E, and sections 5, 4, 3, and 2, T22S, R8E, on the Espinosa Canyon map, to a 1,811-foot peak located in section 2; then 
(11) Proceed southeast in a straight line for approximately 10.4 miles across sections 2, 11, 12, and 13, T22S, R8E, and sections 18 and 19, T22S, R9E, on the Espinosa Canyon map, sections 19, 30, 29, 32, and 33, T22S, R9E, on the northwest corner of the Williams Hill map, and sections 4, 3, 10, 11, and 14, T23S, R9E, on the Hames Valley map, to the beginning point at the southeast corner of section 14, T23S, R9E.

**Comment by MicheleTobias** [comment]
I'm working on this one.

**Comment by SoominHur** [comment]
Reviewed.
- Add scale information of used maps in the attribute table.

**Comment by MicheleTobias** [comment]
@sdelong reports that step 5 needs to be reviewed:
 * (5) The wrong section 34 southwest corner has been plotted - the correct one is approx 5 miles west T24S, R9E.

**Comment by MicheleTobias** [comment]
I corrected step 5 and reviewed the other steps just to be sure.
