### ISSUE TITLE
san_benito

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#181]
# AVA: San Benito (san_benito)

name | value
--- | ---
ava_id | san_benito
cfr_index | 9.110
revision | [T.D. ATF-258, 52 FR 37137, Oct. 5, 1987]
state | CA
county | San Benito
within | Central Coast
contains | Cienega Valley\|Lime Kiln Valley\|Paicines

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Hollister Quadrangle, 7.5 minute series, 1955 
photorevised 1971.. 
2. Tres Pinos Quadrangle, 7.5 minute series, 1955 
photorevised 1971.. 
3. Quien Sabe Valley Quadrangle, 7.5 minute series, 1968. 
4. Mt. Harlan Quadrangle, 7.5 minute series, 1968. 
5. Paicines Quadrangle, 7.5 minute series, 1968. 
6. Cherry Peak Quadrangle, 7.5 minute series, 1968.

## Boundary [src]
General.  The San Benito viticultural area is located in San Benito County, California. The starting point of the following boundary description is the point where the eastern border of Section 17 of Township 15 South, Range 7 East, crosses the latitude 36°37  
(on the Cherry Peak map). Boundary Description.  
(i) From the starting point, westward along latitude 36°37  to the Range Line R.6E./R.7E. 
(on the Paicines map). 
(ii) Then northward along that range line to the southern border of Section 1, Township 15 South, Range 6 East. 
(iii) Then westward along that southern border to the western border of the same section. 
(iv) Then northward along that western border to the 800-foot contour line. 
(v) Then northwestward along that contour line to the Township Line T.14S./T.15S. 
(vi) Then westward along that township line to the southern border of Section 34, Township 15 South, Range 6 East. 
(vii) Then continuing westward along that southern border to the 1200-foot contour line. 
(viii) Then generally northwestward along that contour line until it crosses for the second time the southern border of Section 28, Township 14 South, Range 6 East. 
(ix) Then westward along that southern border to the 1400-foot contour line. 
(x) Then following the 1400-foot contour line through the folloowing sections: Sections 28, 29, and 30, Township 14 South, Range 6 East; Section 25, Township 14 South, Range 5 East; Sections 30, 19, 20, and returning to 19, Township 14 South, Range 6 East; to the point where the 1400-foot contour line intersects the section line between Sections 19 and 18, Township 14 South, Range 6 East. 
(xi) From there in a straight line due northward to the 1200-foot contour line in Section 18, Township 14 South, Range 6 East. 
(xii) Then following the 1200-foot contour line generally northwestward to the northern border of Section 10, Township 14 South, Range 5 East 
(on the Mt. Harlan map). 
(xiii) Then following that northern border northwestward to the 1600-foot contour line. 
(xiv) Then following the 1600-foot contour line generally northward to an unimproved road. 
(xv) Then looping southward along the unimproved road and continuing eastward past the designated “Spring” and then northward parallel with Bonanza Gulch to the Vineyard School on Cienega Road 
(on the Hollister map). 
(xvi) From there in a straight line northeastward, crossing Bird Creek and the San Benito River, to the northwestern corner of Section 19, Township 13 South, Range 6 East 
(on the Tres Pinos map). 
(xvii) From there following the northern border of Sections 19 and 20, Township 13 South, Range 6 East, to the northeastern corner of Section 20. 
(xviii) From there in a straight line due eastward to the Range line R.6E./R7E. 
(xix) Then southward along that Range line to the Township line T.13S./T.14S. 
(xx) Then eastward along that Township line to the eastern border of Section 6, Township 14 South, Range 7 East 
(on the Quien Sabe Valley map). 
(xxi) Then southward along the eastern border of Sections 6, 7, and 18, Township 14 South, Range 7 East, to the northern border of Section 20, Township 14 South, Range 7 East 
(on the Cherry Peak map). 
(xxii) Then eastward along that northern border to the eastern border of Section 20. 
(xxiii) Then southward along the eastern border of Sections 20, 29, and 32, Township 14 South, Range 7 East, and continuing southward along the eastern border of Sections 5, 8, and 17, Township 15 South, Range 7 East, to the starting point.

**Comment by MicheleTobias** [comment]
I'm working on this one.

**Comment by SoominHur** [comment]
Reviewed.
- Edit created date in the attribute table.
- Michele used (6) "Cherry Peak, CA" 1968, photorevised 1984, Scale 1:24000. But I could find (6) "Cherry Peak, CA" 1968, Scale 1:2400, which has the same map year described in the approved maps. So i used (6) "Cherry Peak, CA" 1968, Scale 1:24000 for editing.
