### ISSUE TITLE
san_bernabe

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#182]
# AVA: San Bernabe (san_bernabe)

name | value
--- | ---
ava_id | san_bernabe
cfr_index | 9.171
revision | [T.D. TTB-14, 69 FR 38836, June 29, 2004]
state | CA
county | Monterey
within | Central Coast\|Monterey
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Thompson Canyon Quadrangle, California-Monterey County, 1949 
photorevised 1984.; 
2. San Lucas Quadrangle, California-Monterey County, 1949 
photorevised 1984.; 
3. Espinosa Canyon Quadrangle, California-Monterey County, 1949 
photorevised 1979.; and 
4. Cosio Knob Quadrangle, California-Monterey County, 1949 
photorevised 1984.;

## Boundary [src]

(1) The point of beginning on the Thompson Canyon Quadrangle is benchmark 304, located one-half mile southwest of King City, along the Salinas River, in Township 20 South 
(T20S) and Range 8 East 
(R8E). Proceed southeast in a straight line for 2.35 miles to benchmark 304, at the intersection of a trail and the 300-foot contour line, between U.S. Highway 101 and the Salinas River, in T20S and R8E 
(San Lucas Quadrangle); then 
(2) Proceed southeast in a straight line for 2.9 miles to benchmark 336, between U.S. Highway 101 and the Salinas River, in T20S and R8E 
(San Lucas Quadrangle); then 
(3) Proceed southeast in a straight line for 3 miles to benchmark 340, between U.S. Highway 101 and the Salinas River, in T21S and R9E 
(San Lucas Quadrangle); then 
(4) Proceed south in a straight line for 0.8 mile to the intersection of the Salinas River and the Highway 198 bridge, in T21S and R9E 
(Espinosa Canyon Quadrangle); then 
(5) Proceed southwest along Highway 198 for 0.6 mile to its intersection with an unnamed light duty road, in T21S and R9E 
(Espinosa Canyon Quadrangle); then 
(6) Proceed northwest, followed by southwest, about 1.2 miles along the meandering, unnamed, light duty road to its intersection with the fork of an intermittent stream, in T21S and R8E 
(Espinosa Canyon Quadrangle); then 
(7) Proceed southwest in a straight line for 0.6 mile to the 595-foot peak, Section 13, in T21S and R8E 
(Espinosa Canyon Quadrangle); then 
(8) Proceed southwest in a straight line for 1.3 miles to the 788-foot peak, section 23, in T21S and R8E 
(Espinosa Canyon Quadrangle); then 
(9) Proceed southwest in a straight line for 0.7 mile to the intersection of the unimproved road and jeep trail, east of the 73-degree longitudinal line, section 26, in T21S and R8E 
(Espinosa Canyon Quadrangle); then 
(10) Proceed northwest in a straight line for 3.2 miles to the northwest corner of section 16, in T21S and R8E 
(Espinosa Canyon Quadrangle); then 
(11) Proceed southwest in a straight line for 1.5 miles to the northeast corner of section 19, in T21S and R8E 
(Cosio Knob Quadrangle); then 
(12) Proceed southwest in a straight line for 2.2 miles to the southwest corner of section 24, in T21S and R7E 
(Cosio Knob Quadrangle); then 
(13) Proceed north in a straight line for 2 miles to the northwest corner of section 13, in T21S and R7E 
(Cosio Knob Quadrangle); then 
(14) Proceed east in a straight line for 1 mile to the northeast corner of section 13, in T21S and R7E 
(Cosio Knob Quadrangle); then 
(15) Proceed north in a straight line for 2 miles, along the R7E and R8E common boundary line, to the northwest corner of section 6, in T21S and R8E 
(Thompson Canyon Quadrangle); then 
(16) Proceed east in a straight line for 0.1 mile to the southwest corner of section 31 and continue diagonally to the northeast corner of section 31, in T20S and R8E 
(Thompson Canyon Quadrangle); then 
(17) Proceed west in a straight line for 2 miles to the southwest corner of section 25, in T20S and R7E 
(Thompson Canyon Quadrangle); then 
(18) Proceed due north in a straight line for 0.1 mile to the intersection with a light duty road, named Pine Canyon Road, in section 25, and continue northeast along that road for 3.2 miles to its intersection with an unnamed secondary highway, north of benchmark 337, section 18, in T20S and R8E 
(Thompson Canyon Quadrangle); then 
(19) Proceed northwest along the unnamed secondary highway for 0.3 mile to its intersection with U.S. Highway 101, in T20S and R8E 
(Thompson Canyon Quadrangle); then 
(20) Proceed northeast along U.S. Highway 101 for 0.7 mile to benchmark 304, returning to the point of beginning 
(Thompson Canyon Quadrangle).

**Comment by MicheleTobias** [comment]
I'm working on this one

**Comment by SoominHur** [comment]
Reviewed
- Add (1) The point of beginning, which is benchmark 304 (Thompson Canyon Quadrangle)
- Move node locating the southeast corner of section 24 (12) to the southwest corner of section 24, in T21S and R7E (Cosio Knob Quadrangle).
