### ISSUE TITLE
san_francisco_bay

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#183]
# AVA: San Francisco Bay (san_francisco_bay)

name | value
--- | ---
ava_id | san_francisco_bay
cfr_index | 9.157
revision | [T.D. ATF-407, 64 FR 3024, Jan. 20, 1999, as amended by T.D. TTB-48, 71 FR 34525, June 15, 2006; T.D. TTB-67, 73 FR 12880, Mar. 11, 2008]
state | CA
county | Alameda|Contra Costa|San Benito|San Francisco|San Mateo|Santa Clara|Santa Cruz|Solano
within | Central Coast
contains | Lamorinda\|Livermore Valley\|Pacheco Pass\|San Ysidro District\|Santa Clara Valley

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Pacheco Peak, California, scale 1:24,000, dated 1955, Photorevised 1971; 
2. Gilroy Hot Springs, California, scale 1:24,000, dated 1955, Photoinspected 1978, Photorevised 1971 
3. Mt. Sizer, California, scale 1:24,000, dated 1955, Photoinspected 1978, Photorevised 1971 
4. Morgan Hill, California, scale 1:24,000, dated 1955, Photorevised 1980 
5. Lick Observatory, California, scale 1:24,000, dated 1955, Photoinspected 1973, Photorevised 1968 
6. San Jose East, California, scale 1:24,000, dated 1961, Photorevised 1980; 
7. Calaveras Reservoir, California, scale 1:24,000, dated 1961, Photorevised 1980; 
8. La Costa Valley, California, scale 1:24,000, dated 1960, Photorevised 1968; 
9. Mendenhall Springs, California, scale 1:24,000, dated 1956, Photoinspected 1978, Photorevised 1971; 
10. Altamont, California, scale 1:24,000, dated 1953, Photorevised 1981; 
11. Byron Hot Springs, California, scale 1:24,000, dated 1953, Photorevised 1968; 
12. Tassajara, California, scale 1:24,000, dated 1953, Photoinspected 1974, Photorevised 1968; 
13. Diablo, California, scale 1:24,000, dated 1953, Photorevised 1980; 
14. Clayton, California, scale 1:24,000, dated 1953, Photorevised 1980; 
15. Honker Bay, California, scale 1:24,000, dated 1953, Photorevised 1980; 
16. Vine Hill, California, scale 1:24,000, dated 1959, Photorevised 1980; 
17. Benicia, California, scale 1:24,000, dated 1959, Photorevised 1980; 
18. Mare Island, California, scale 1:24,000, dated 1959, Photorevised 1980; 
19. Richmond, California, scale 1:24,000, dated 1959, Photorevised 1980; 
20. San Quentin, California, scale 1:24,000, dated 1959, Photorevised 1980; 
21. Oakland West, California, scale 1:24,000, dated 1959, Photorevised 1980; 
22. San Francisco North, California, scale 1:24,000, dated 1956, Photorevised 1968 and 1973; 
23. San Francisco South, California, scale 1:24,000, dated 1956, Photorevised 1980; 
24. Montara Mountain, California, scale 1:24,000, dated 1956, Photorevised 1980; 
25. Half Moon Bay, California, scale 1:24,000, dated 1961, Photoinspected 1978, Photorevised 1968 and 1973; 
26. San Gregorio, California, scale 1:24,000, dated 1961, Photoinspected 1978, Photorevised 1968; 
27. Pigeon Point, California, scale 1:24,000, dated 1955, Photorevised 1968; 
28. Franklin Point, California, scale 1:24,000, dated 1955, Photorevised 1968; 
29. Año Nuevo, California, scale 1:24,000, dated 1955, Photorevised 1968; 
30. Davenport, California, scale 1:24,000, dated 1955, Photorevised 1968; 
31. Santa Cruz, California, scale 1:24,000, dated 1954, Photorevised 1981; 
32. Felton, California, scale 1:24,000, dated 1955, Photorevised 1980; 
33. Laurel, California, scale 1:24,000, dated 1955, Photoinspected 1978, Photorevised 1968; 
34. Soquel, California, scale 1:24,000, dated 1954, Photorevised 1980; 
35. Watsonville West, California, scale 1:24,000, dated 1954, Photorevised 1980; 
36. Loma Prieta, California, scale 1:24,000, dated 1955, Photoinspected 1978, Photorevised 1968; 
37. Watsonville East, California, scale 1:24,000, dated 1955, Photorevised 1980; 
38. Mt. Madonna, California, scale 1:24,000, dated 1955, Photorevised 1980; 
39. Gilroy, California, scale 1:24,000, dated 1955, Photorevised 1981; 
40. Chittenden, California, scale 1:24,000, dated 1955, Photorevised 1980; 
41. San Felipe, California, scale 1:24,000, dated 1955, Photorevised 1971;  
42. Three Sisters, California, scale 1:24,000, dated 1954, Photoinspected 1978, Photorevised 1971; 
43. Cedar Mtn., California, scale 1:24,000, dated 1956, Photorevised 1971; Minor Revision 1994; 
44. Cuttings Wharf, Calif.; 1949; Photorevised 1981; 
45. Sears Point, Calif.; 1951; Photorevised 1968; 
46. Cordelia, Calif.; 1951; Photorevised 1980; and 
47. Fairfield South, Calif.; 1949; Photorevised 1980.

## Boundary [src]

(1) Beginning at the intersection of the 37 degree 00  North latitude parallel with State Route 152 on the Pacheco Peak Quadrangle. 
(2) Then proceed in a northwesterly direction in a straight line to the intersection of Coyote Creek with the township line dividing Township 9 South from Township 10 South on the Gilroy Hot Springs Quadrangle. 
(3) Then proceed in a northwesterly direction in a straight line to the intersection of the township line dividing Township 8 South from Township 9 South with the range line dividing Range 3 East from Range 4 East on the Mt. Sizer Quadrangle. 
(4) Then proceed in a northwesterly direction in a straight line 
(across the Morgan Hill Quadrangle) to the intersection of the township line dividing Township 7 South from Township 8 South with the range line dividing Range 2 East from Range 3 East on the Lick Observatory Quadrangle. 
(5) Then proceed in a northwesterly direction in a straight line to the intersection of State Route 130 with the township line dividing Township 6 South from Township 7 South on the San Jose East Quadrangle. 
(6) Then proceed in a northeasterly direction following State Route 130 to its intersection with the range line dividing Range 1 East from Range 2 East on the Calaveras Reservoir Quadrangle. 
(7) Then proceed north following this range line to its intersection with the Hetch Hetchy Aqueduct on the La Costa Valley Quadrangle. 
(8) Then proceed in a northeasterly direction in a straight line following the Hetch Hetchy Aqueduct to the western boundary of Section 14 in Township 4 South, Range 2 East on the Mendenhall Springs Quadrangle. 
(9) Then proceed south along the western boundary of Section 14 in Township 4 South, Range 2 East to the southwest corner of Section 14 on the Mendenhall Springs Quadrangle. 
(10) Then proceed east along the southern boundary of Section 14 in Township 4 South, Range 2 East to the southeast corner of Section 14 on the Mendenhall Springs Quadrangle. 
(11) Then proceed south along the western boundary of Section 24 in Township 4 South, Range 2 East to the southwest corner of Section 24 on the Mendenhall Springs Quadrangle. 
(12) Then proceed east along the southern boundary of Section 24 in Township 4 South, Range 2 East and Section 19 in Township 4 South, Range 3 East to the southeast corner of Section 19 on the Mendenhall Springs Quadrangle. 
(13) Then proceed northeast in a straight line approximately 3.2 miles to BM 1878 in Section 14 on the Cedar Mtn. Quadrangle. 
(14) Then proceed north in a straight line approximately 4.2 miles to BM 1600 adjacent to Tesla Road in Section 26, Township 3 South, Range 3 East on the Midway Quadrangle. 
(15) Then proceed north-northwest in a straight line approximately 2.8 miles to Patterson Pass, BM 1602, in Section 10, Township 3 South, Range 3 East, on the Altamont Quadrangle. 
(16) Then proceed north-northwest in a straight line approximately 2.7 miles to the intersection of the eastern boundary of Section 32 with Highway 580 in Township 2 South, Range 3 East. 
(17) Then proceed north-northeast in a straight line approximately 1.1 miles to an unnamed peak, elevation 1147, in Section 28, Township 2 South, Range 3 East. 
(18) Then proceed north-northwest in a straight line approximately 1 mile to BM 720 in Section 21, Township 2 South, Range 3 East, and proceed northwest in a straight line approximately 1.8 miles to the northeast corner of Section 18 on the Byron Hot Springs Quadrangle, Township 2 South, Range 3 East. 
(19) Then proceed due west along the northern boundaries of Section 18 and Section 13 
(Township 2 South, Range 2 East) to a point approximately 400 feet due south of Brushy Peak on the Byron Hot Springs Quadrangle. 
(20) Then proceed due north to Brushy Peak 
(elevation 1,702) on the Byron Hot Springs Quadrangle. 
(21) Then proceed in a northwesterly direction in a straight line 
(across the Tassajara and Diablo Quadrangles) to Mt. Diablo 
(elevation 3,849) on the Clayton Quadrangle. 
(22) Then proceed in a northwesterly direction in a straight line to Mulligan Hill 
(elevation 1,438) on the Clayton Quadrangle. 
(23) Then proceed in a northwesterly direction in a straight line 
(across the Honker Bay Quadrangle) to a point marked BM 15 on the shoreline of Contra Costa County on the Vine Hill Quadrangle. 
(24) Then proceed west-southwest along the south shoreline of the Suisun Bay and the Carquinez Strait to its intersection with Interstate 680 at the Benicia-Martinez Bridge and BM 66, T3N/R2W, on the Vine Hill Quadrangle. 
(25) Then proceed generally north following Interstate 680, crossing over and back on the Benicia Quadrangle map and continuing over the Fairfield South Quadrangle map, to its intersection with the Southern Pacific railroad track at Cordelia, Section 12, T4N/R3W, on the Cordelia Quadrangle map. 
(26) Then proceed generally west along the Southern Pacific railroad track to its intersection with the Napa and Solano Counties boundary line in Jameson Canyon at Creston, Section 9, T4N/R3W, on the Cordelia Quadrangle map. 
(27) Then proceed generally south-southeast, followed by straight west along the Napa and Solano Counties boundary line; continue straight west, crossing over the Cuttings Wharf Quadrangle map, to its intersection with the east shoreline of Sonoma Creek slough, which coincides with the Highway 37 bridge on the Solano County side of the creek, T4N/R5W, on the Sears Point Quadrangle. 
(28) Then proceed generally southeast along the north and east shorelines of San Pablo Bay, also known as the San Pablo Bay National Wildlife Refuge, crossing over the Cuttings Wharf Quadrangle map, to its intersection with the Breakwater line, located within the Vallejo City boundary and 0.7 mile west-southwest of the beacon, T3N/R4W, on the Mare Island Quadrangle. 
(29) Then proceed straight south-southwest 1.2 miles to its intersection with the San Pablo Bay shoreline at BM 14, west of Davis Point, T3N/R4W, on the Mare Island Quadrangle. 
(30) Then proceed generally south along the contiguous eastern shorelines of San Pablo Bay and San Francisco Bay, crossing over the Richmond and San Quentin Quadrangle maps, to its intersection with the San Francisco/Oakland Bay Bridge on the Oakland West Quadrangle. 
(31) Then proceed west on the San Francisco/Oakland Bay Bridge to the San Francisco County shoreline on the San Francisco North Quadrangle. 
(32) Then proceed along the San Francisco, San Mateo, and Santa Cruz County shoreline 
(across the Quadrangles of San Francisco South, Montara Mountain, Half Moon Bay, San Gregorio, Pigeon Point, Franklin Point, Año Nuevo and Davenport) to the place where Majors Creek flows into the Pacific Ocean on the Santa Cruz Quadrangle. 
(33) Then proceed northeasterly along Majors Creek to its intersection with the 400 foot contour line on the Felton Quadrangle. 
(34) Then proceed along the 400 foot contour line in a generally easterly/northeasterly direction to its intersection with Bull Creek on the Felton Quadrangle. 
(35) Then proceed along Bull Creek to its intersection with Highway 9 on the Felton Quadrangle. 
(36) Then proceed along Highway 9 in a northerly direction to its intersection with Felton Empire Road. 
(37) Then proceed along Felton Empire Road in a westerly direction to its intersection with the 400 foot contour line on the Felton Quadrangle. 
(38) Then proceed along the 400 foot contour line 
(across the Laurel, Soquel, Watsonville West and Loma Prieta Quadrangles) to its intersection with Highway 152 on the Watsonville East Quadrangle. 
(39) Then proceed along Highway 152 in a northeasterly direction to its intersection with the 600 foot contour line just west of Bodfish Creek on the Watsonville East Quadrangle. 
(40) Then proceed in a generally east/southeasterly direction along the 600 foot contour line 
(across the Mt. Madonna and Gilroy Quadrangles), approximately 7.3 miles, to the first intersection of the western section line of Section 30, Township 11 South, Range 4 East on the Chittenden Quadrangle. 
(41) Then proceed south along the section line approximately 1.9 miles to the south township line at Section 31, Township 11 South, Range 4 East on the Chittenden Quadrangle. 
(42) Then proceed in an easterly direction along the township line 
(across the San Felipe Quadrangle), approximately 12.4 miles to the intersection of Township 11 South and Township 12 South and Range 5 East and Range 6 East on the Three Sisters Quadrangle. 
(43) Then proceed north along the Range 5 East and Range 6 East range line approximately 5.5 miles to Pacheco Creek on the Pacheco Creek Quadrangle. 
(44) Then proceed northeast along Pacheco Creek approximately .5 mile to the beginning point.

**Comment by fyfangyao** [comment]
I am working on this.

**Comment by fyfangyao** [comment]
(1) Pacheco Peak, Calif., 1955, photorevised 1972; (2) Gilroy Hot Springs, Calif., 1955, photorevised 1972; (3) Mt. Sizer, Calif., 1955, photorevised 1972; (4) Lick Observatory, Calif., 1955, photorevised 1977; (5) La Costa Valley, Calif., 1960, photorevised 1967; (6) Mendenhall Springs, Calif., 1956, photorevised 1973; (7) Byron Hot Springs, Calif., 1953, photorevised 1969; (8) Tassajara, Calif., 1953, photorevised 1969; (9) Diablo, Calif., 1953, photorevised 1969; (10) Clayton, Calif., 1953, photorevised 1981; (11) Honker Bay, Calif., 1953, photorevised 1981; (12) Vine Hill, Calif., 1959, photorevised 1981; (13) Benicia, Calif., 1959, photorevised 1981; (14) Mare Island, Calif., 1959, photorevised 1981; (15) Oakland West, Calif., 1959, photorevised 1981; (16) San Francisco North, Calif., 1956, photorevised 1975; (17) San Francisco South, Calif., 1956, photorevised 1981; (18) Montara Mountain, Calif., 1956, photorevised 1981; (19) Half Moon Bay, Calif., 1961, photorevised 1975; (20) San Gregorio, Calif., 1961, photorevised 1969; (21) Pigeon Point, Calif., 1955, photorevised 1969; (22) Franklin Point, Calif., 1955, photorevised 1969; (23) And Nuevo, Calif., 1955, photorevised 1969; (24) Davenport Calif., 1955, photorevised 1970; (25) Santa Cruz, Calif., 1954, photorevised 1982; (26) Laurel, Calif., 1955, photorevised 1969; (27) Soquel, Calif., 1954, photorevised 1981; (28) Watsonville West, Calif., 1954, photorevised 1981; (29) Loma Prieta, Calif., 1955, photorevised 1969; (30) Gilroy, Calif., 1955, photorevised 1982; (31) San Felipe, Calif., 1955, photorevised 1972; (32) Three Sisters, Calif., 1954, photorevised 1972; and (33) Sears Point, Calif., 1951, photorevised 1969.

**Comment by fyfangyao** [comment]
(1) Pacheco Peak, Calif., 1955, photorevised 1977; 
(2) Gilroy Hot Springs, Calif., 1955, photorevised 1972; 
(3) Mt. Sizer, Calif., 1955, photorevised 1972; 
(4) Lick Observatory, Calif., 1955, photorevised 1977; 
(5) La Costa Valley, Calif., 1960, photorevised 1967;
(6) Mendenhall Springs, Calif., 1956, photorevised 1973. 
(7) Byron Hot Springs, Calif., 1953, photorevised 1969; 
(8) Tassajara, Calif., 1953, photorevised 1969; 
(9) Clayton, Calif., 1953, photorevised 1981; 
(10) Honker Bay, Calif., 1953, photorevised 1981; 
(11) Vine Hill, Calif., 1959, photorevised 1981;
(12) Benicia, Calif., 1959, photorevised 1981. 
(13) Mare Island, Calif., 1959, photorevised 1980; 
(14) Oakland West, Calif., 1959, photorevised 1981; 
(15) San Francisco North, Calif., 1956, photorevised 1975; 
(16) San Francisco South, Calif., 1956, photorevised 1981;
(17) Montara Mountain, Calif., 1956, photorevised 1981;
(18) Half Moon Bay, Calif., 1961, photorevised 1975. 
(19) San Gregorio, Calif., 1961, photorevised 1969; 
(20) Pigeon Point, Calif., 1955, photorevised 1969; 
(21) Franklin Point, Calif., 1955, photorevised 1969; 
(22) Ano Nuevo, Calif., 1955, photorevised 1969; 
(23) Davenport, Calif., 1955, photorevised 1970;
(24) Santa Cruz, Calif., 1954, photorevised 1982. 
(25) Laurel, Calif., 1955, photorevised 1969; 
(26) Soquel, Calif., 1954, photorevised 1981; 
(27) Watsonville West, Calif., 1954, photorevised 1981; 
(28) Loma Prieta, Calif., 1955, photorevised 1969; 
(29) Watsonville East, Calif., 1954, photorevised 1981;
(30) Gilroy, Calif., 1955, photorevised 1982. 
(31) San Felipe, Calif., 1955, photorevised 1972; 
(32) Three Sisters, Calif., 1954, photorevised 1972; 
(33) Sears Point, Calif., 1951, photorevised 1969;

**Comment by fyfangyao** [comment]
Map “Midway, CA, 1:24,000” is required in the boundary description step (14) but doesn’t be listed in Approved Map. I use “Midway, CA, 1:24,000, 1953, photorevised 1981” for this boundary.

**Comment by MicheleTobias** [comment]
I'm glad you figured that out!  Add it to the list of the maps you used in the attribute table.

**Comment by fyfangyao** [comment]
Map “Hunter, CA, 1:24,000” is not mentioned but supposed to be required in the boundary description step (32). I use “Hunter, CA, 1:24,000, 1956, photorevised 1980” for this boundary.

**Comment by MicheleTobias** [comment]
Coming back to this one while @elistockwell is working on the historic boundaries, we noticed that the last direction (step 44) isn't possible.  Our decision is to leave it as Yao digitized it - ending at the intersection of the R 5/6 E line and the creek, and then making a straight line to the starting point.  Following the creek in either direction doesn't take you back to the starting point.
