### ISSUE TITLE
san_juan_creek

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#184]
# AVA: San Juan Creek (san_juan_creek)

name | value
--- | ---
ava_id | san_juan_creek
cfr_index | 9.245
revision | [T.D. TTB-125, 79 FR 60965, Oct. 9, 2014]
state | CA
county | San Luis Obispo
within | Central Coast\|Paso Robles
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Cholame, Calif., 1961, revised 1993; 
2. Camatta Canyon, Calif., 1961, revised 1993; 
3. Holland Canyon, Calif. 1961, revised 1993; 
4. La Panza Ranch, CA, 1995; 
5. Shedd Canyon, Calif., 1961, revised 1993; and 
6. Shandon, Calif., 1961, revised 1993.

## Boundary [src]

(1) The beginning point is on the Cholame map in the Shandon Valley at the intersection of State Route 41 and San Juan Road, northern boundary of section 21, T26S/R15E. From the beginning point on the Cholame map, and crossing onto the Camatta Canyon map and then the Holland Canyon map, proceed south and then southeasterly approximately 16 miles along the eastern edge of the Shandon Valley and then the San Juan Valley by following San Juan Road 
(also locally known in places as Shandon San Juan Road, Camatti-Shandon Road, Bitterwater Canyon Road, and then San Juan Road again), passing the San Juan Ranch 
(where to road is marked as unimproved), to the road&#39;s intersection with the San Luis Obispo-Kern County boundary line at the eastern boundary line of section 12, T28S/R16E, which is also concurrent with the R16E/R17E common boundary line; then 
(2) Proceed south along the R16E/R17E common boundary line approximately 1.3 miles, crossing onto the La Panza Ranch map, to the boundary line&#39;s intersection with an unnamed unimproved road locally known as Navajo Creek Road, immediately south of the 1,340-foot elevation line, section 13, T28S/R16E; then 
(3) Proceed north-northwesterly on Navajo Creek Road to the road&#39;s intersection with the southern boundary line of section 12, T28S/R16E; then 
(4) Proceed west along the southern boundary line of section 12, T28S/R16E, approximately 0.7 mile to the section&#39;s southwestern corner; then 
(5) Proceed northerly in a straight line approximately 0.6 mile, crossing onto the Holland Canyon map, to the intersection of the 1,300-foot elevation line and an unnamed tributary of San Juan Creek 
(approximately 0.35 mile east of the 1,686-foot San Juan peak), in section 11, T28S/R16E; then 
(6) Proceed northwesterly along the 1,300-foot elevation line approximately 1.3 miles to the line&#39;s first intersection with the western boundary line of section 2, T28S/R16E, northwest of Pear Tree Spring; then 
(7) Proceed north along the western boundary line of section 2 approximately 0.55 to the section boundary line&#39;s last intersection with the 1,300-foot elevation line, near the northwestern corner of section 2, T28S/R16E; then 
(8) Proceed northwesterly along the meandering 1,300-foot elevation line approximately 3.7 miles, crossing onto the Camatta Canyon map, to the elevation line&#39;s intersection with the western boundary line of section 28, T27S/R16E; then 
(9) Proceed north along the western boundary line of section 28 approximately 0.15 mile to the section boundary line&#39;s intersection with an unnamed unimproved road, section 28, T27S/R16E; then 
(10) Proceed northwesterly on the unnamed unimproved road approximately 3 miles as it follows the southwestern edge of the San Juan Valley to the road&#39;s intersection with western boundary line of section 18, T27S/R16E; then 
(11) Proceed north along the western boundary line of section 18, T27S/R16E, approximately 0.2 mile to the section boundary line&#39;s intersection with 1,200-foot elevation line, section 18, T27S/R16E; then 
(12) Proceed westerly then northerly along the 1,200-foot elevation line to the elevation line&#39;s intersection with the southern boundary of section 12, T27S/R15E; then 
(13) Proceed west approximately 6.4 miles along the southern boundary lines of sections 12, 11, 10, 9, 8, and 7, T27S/R15E, crossing onto the Shedd Canyon map, and continue west along the southern boundary lines of sections 12 and 11, T27S/R14E, to the intersection of the southern boundary line of section 11 with an unnamed unimproved road locally known as Shedd Canyon Road 
(within Shedd Canyon 0.1 mile west of State Route 41); then 
(14) Proceed northerly on Shedd Canyon Road approximately 3.2 miles, crossing onto the Shandon map, to the road&#39;s intersection with the southern boundary line of section 26, T26S/R14E; then 
(15) Proceed west along the southern boundary line of section 26, T26S/R14E, to the boundary line&#39;s intersection with the unnamed intermittent stream located within Shedd Canyon; then 
(16) Proceed northerly along the unnamed intermittent stream located within Shedd Canyon approximately 1.8 miles to the stream&#39;s intersection with the western boundary line of section 23, T26S/R14E; then 
(17) Proceed north along the western boundary lines of sections 23 and 14, T26S/R14E, approximately 0.6 mile to the section 14 boundary line&#39;s intersection with State Route 46; then 
(18) Proceed northeasterly in a straight line approximately 0.95 mile to the 1,481-foot “Estrella” elevation point, section 14, T26S/R14E; then 
(19) Proceed north-northwesterly in a straight line approximately 1.25 miles to the line&#39;s intersection with 1,300-foot elevation line and the northern boundary line of section 11, T26S/R14E; then 
(20) Proceed east along northern section boundary lines of sections 11 and 12, T26S/R14E, and the northern boundary lines of sections 7, 8, 9, and 10, T26S/R15E, approximately 5.9 miles in total distance and crossing onto the Cholame map, to the northeast corner of section 10, T26S/R15E 
(adjacent to State Routes 41/46); then 
(21) Proceed south along the eastern boundary line of section 10, T26S/R15E, approximately 1 mile to the section&#39;s southeast corner; then 
(22) Proceed west-southwesterly in a straight line approximately 1.8 miles, returning to the beginning point.

**Comment by SoominHur** [comment]
Reviewed
- The description directs to (16) Proceed northerly along the unnamed intermittent stream from the southern boundary line of section 26 (T26S/R14E) until the stream intersect with the western boundary line of section 23 (T26S/R14E). However, the intermittent stream line at the middle of the section 26 (T26S/R14E). So referenced the previous edition of map ("Shandon, CA" 1961 (1975 ed.) to follow along the intermittent stream.
- Add scale information of used maps in the attribute table
