### ISSUE TITLE
san_lucas

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#185]
# AVA: San Lucas (san_lucas)

name | value
--- | ---
ava_id | san_lucas
cfr_index | 9.56
revision | [T.D. ATF-248, 52 FR 2945, Jan. 29, 1987, as amended by T.D. TTB-14, 69 FR 38836, June 29, 2004]
state | CA
county | Monterey
within | Central Coast\|Monterey
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]
San Lucas, CA, 1949, photorevised 1979, Nattrass Valley, CA, 1967, San Ardo, CA, 1967, and, Espinosa Canyon, CA, 1949, photorevised 1979.

## Boundary [src]
Beginning on the “San Lucas Quadrangle” map at the northwest corner of section 5 in Township 21 South, Range 9 East, the boundary proceeds northeasterly in a straight line approximately 0.35 mile to the 630-foot promontory in section 32, T. 20 S., R. 9 E.; 
(1) Then east southeasterly in a straight line approximately 0.6 mile to the 499-foot promontory in the southwest corner of section 33, T. 20 S., R. 9 E.; 
(2) Then east southeasterly in a straight line approximately 1.3 miles to the 847-foot promontory in section 3, T. 21 S., R. 9 E., on the “Nattrass Valley Quadrangle” map; 
(3) Then south southeasterly in a straight line approximately 2.2 miles to the 828-foot promontory in section 14, T. 21 S., R. 9 E., on the “San Ardo Quadrangle” map; 
(4) Then east southeasterly in a straight line approximately 1.3 miles to the 868-foot promontory in section 13, T. 21 S., R. 9 E.; 
(5) Then southeasterly in a straight line approximately 0.94 mile to the 911-foot promontory in section 19, T. 21 S., R. 10 E.; 
(6) Then easterly in a straight line approximately 1.28 miles to the 1,042-foot promontory in section 20, T. 21 S., R. 10 E.; 
(7) Then east northeasterly in a straight line approximately 1.28 miles to the 998-foot promontory in southeast corner of section 16, T. 21 S., R. 10 E.; 
(8) Then southerly in a straight line approximately 2.24 miles to the 1,219-foot promontory near the east boundary of section 28, T. 21 S., R. 10 E.; 
(9) Then southwesterly in a straight line approximately 1.5 miles to the 937-foot promontory near the north boundary of section 32, T. 21 S., R. 10 E.; 
(10) Then southwesterly in a straight line approximately 0.34 mile to the 833-foot promontory in section 32, T. 21 S., R. 10 E.; 
(11) Then south southeasterly in a straight line approximately 0.5 mile to the 886-foot “Rosenberg” promontory in section 32, T. 21 S., R. 10 E.; 
(12) Then south southeasterly approximately 1.1 miles to the 781-foot promontory in section 5, T. 22 S., R. 10 E.; 
(13) Then southeasterly in a straight line approximately 0.7 mile to the 767-foot promontory in section 9, T. 22 S., R. 10 E.; 
(14) Then southerly in a straight line approximately 0.5 mile to the 647-foot promontory along the south boundary of section 9, T. 22 S., R. 10 E.; 
(15) Then southwesterly in a straight line approximately 2.67 miles to the 835-foot promontory in section 19, T. 22 S., R. 10 E.; 
(16) Then west southwesterly in a straight line approximately 1.1 miles to the 1,230-foot promontory in section 24, T. 22 S., R. 9 E.; 
(17) Then north northwesterly in a straight line approximately 1.4 miles to the 1,149-foot promontory in section 14, T. 22 S., R. 9 E.; 
(18) Then northwesterly in a straight line approximately 0.57 mile to the 1,128-foot promontory in section 11, T. 22 S., R. 9 E.; 
(19) Then west southwesterly in a straight line approximately 0.58 mile to the 1,220-foot promontory near the north boundary of section 15, T. 22 S., R. 9 E.; 
(20) Then northwesterly in a straight line approximately 1.33 miles to the 1,071-foot promontory in the northwest corner of section 9, T. 22 S., R. 9 E.; 
(21) Then northwesterly in a straight line approximately 2.82 miles to the 1,004-foot promontory in section 31, T. 21 S., R. 9 E., on the “Espinosa Canyon Quadrangle” map; 
(22) Then north northwesterly in a straight line approximately 1.32 miles to the 882-foot promontory in section 25, T. 21 S., R. 8 E.; 
(23) Then northwesterly in a straight line approximately 1.05 miles to the 788-foot promontory in section 23, T. 21 S., R. 8 E.; 
(24) Then northeasterly approximately 1.3 miles to the 595-foot promontory, section 13, T21S, R8E 
(Espinosa Canyon Quadrangle); 
(25) Then northeasterly approximately 0.6 mile to the intersection of a meandering, unnamed, light duty road and the fork of an intermittent stream, then continue meandering northeasterly, followed by southeasterly, approximately 1.1 miles to its intersection with an unnamed, light duty road south of the windmill, T21, R8E 
(Espinosa Canyon Quadrangle); 
(26) Then northeasterly along the unnamed road approximately 0.6 mile to its intersection with the Salinas River, then continue 0.8 mile north in a straight line to benchmark 340, between U.S. Highway 101 and the Salinas River, in T21S, R9E 
(San Lucas Quadrangle); 
(27) Then approximately 0.4 mile northwesterly in a straight line to the intersection with a water tank, then continues northeasterly in a straight line approximately 0.7 mile, and return to the point of beginning in the northwest corner of section 5, in T21S, R9E 
(San Lucas Quadrangle).

**Comment by MicheleTobias** [comment]
I'm working on this one.

**Comment by SoominHur** [comment]
Reviewed.
- Edit cfr author and petitioner name in the attribute table. 
- Add scale information of the used maps. 
- Moved a node at 1,123-foot promontory (18) "to the 1,128-foot promontory in section 11, T. 22 S., R. 9 E."
