### ISSUE TITLE
san_miguel_district

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#186]
# AVA: San Miguel District (san_miguel_district)

name | value
--- | ---
ava_id | san_miguel_district
cfr_index | 9.246
revision | [T.D. TTB-125, 79 FR 60966, Oct. 9, 2014]
state | CA
county | San Luis Obispo
within | Central Coast\|Paso Robles
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. San Miguel, Calif., 1948, photorevised 1979; 
2. Paso Robles, Calif., 1948, photorevised 1979; and 
3. Adelaida, Calif., 1948, photorevised 1978.

## Boundary [src]

(1) The beginning point is on the San Miguel map at the intersection of U.S. Highway 101 and the San Luis Obispo-Monterey County boundary line, section 1, T25S/R11E. From the beginning point, proceed east along the San Luis Obispo-Monterey County line approximately 5.9 miles to the county line&#39;s intersection with San Jacinto Creek, section 1, T25S/R12E; then 
(2) Proceed south-southwesterly 
(downstream) along San Jacinto Creek for approximately 6.5 miles, crossing on to the Paso Robles map, to the creek&#39;s confluence with the Estrella River, section 26, T25S/R12E; then 
(3) Proceed southerly 
(upstream) 0.7 mile along the main channel of the Estrella River to the river&#39;s intersection with the southern boundary line of section 26, T25S/R12E; then 
(4) Proceed west along the southern boundary lines of sections 26, 27, and 28, T25S/R12E, approximately 1.85 miles to the section 28 boundary line&#39;s intersection with the Salinas River; then 
(5) Proceed southerly 
(upstream) along the main channel of the Salinas River approximately 1.6 miles to the river&#39;s intersection with an unnamed light-duty road locally known as Wellsona Road, section 4, T26S/R12E; then 
(6) Proceed west then northwesterly on Wellsona Road approximately 2 miles to the road&#39;s intersection with San Miguel Road 
(locally known as San Marcos Road), section 6, T26S/R12E; then 
(7) Proceed west-southwesterly on San Miguel Road 
(locally known as San Marcos Road) approximately 2.6 miles, crossing onto the Adelaida map, to the road&#39;s intersection with the eastern boundary line of the Camp Roberts Military Reservation 
(approximately 400 feet east of the road&#39;s intersection with Generals Road), section 2, T26S/R11E; then 
(8) Proceed northerly along the meandering eastern boundary line of the Camp Roberts Military Reservation 
(approximately 6.3 miles in straight line distance), crossing onto the San Miguel map, to the intersection of the military reservation&#39;s boundary line with U.S. Highway 101 near the northeast corner of section 7, T25S/R12E; then 
(9) Proceed northwesterly on U.S. Highway 101 approximately 1.55 miles, returning to the beginning point.

**Comment by SoominHur** [comment]
Reviewed.
- add scale information of used maps
- refined some nodes
