### ISSUE TITLE
santa_cruz_mountains

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#189]
# AVA: Santa Cruz Mountains (santa_cruz_mountains)

name | value
--- | ---
ava_id | santa_cruz_mountains
cfr_index | 9.31
revision | [T.D. ATF-98, 46 FR 59240, Dec. 4, 1981]
state | CA
county | San Mateo|Santa Clara|Santa Cruz
within | 
contains | Ben Lomond Mountain

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Ano Nuevo Quadrangle, California”; 
2. “Big Basin Quadrangle, California”; 
3. “Castle Rock Ridge Quadrangle, California”; 
4. “Cupertino Quadrangle, California”; 
5. “Davenport Quadrangle, California—Santa Cruz County”; 
6. “Felton Quadrangle, California—Santa Cruz County”; 
7. “Franklin Point Quadrangle, California”; 
8. “Half Moon Bay Quadrangle, California—San Mateo County”; 
9. “La Honda Quadrangle, California—San Mateo County”; 
10. “Laurel Quadrangle, California”; 
11. “Loma Prieta Quadrangle, California”; 
12. “Los Gatos Quadrangle, California”; 
13. “Mt. Madonna Quadrangle, California”; 
14. “Mindego Hill Quadrangle, California”; 
15. “Morgan Hill Quadrangle, California—Santa Clara County”; 
16. “Palo Alto Quadrangle, California”; 
17. “San Gregorio Quadrangle, California—San Mateo County”; 
18. “San Mateo Quadrangle, California—San Mateo County”; 
19. “Santa Teresa Hills Quadrangle—Santa Clara County”; 
20. “Soquel Quadrangle, California—Santa Cruz County”; 
21. “Watsonville East Quadrangle, California”; 
22. “Watsonville West Quadrangle, California”; 
23. “Woodside Quadrangle, California—San Mateo County”; and 
24. One 5 × 11 minute series map entitled: “Santa Cruz, California.”

## Boundary [src]

(1) From the beginning point where Highway 92 and the 400-foot contour line intersect 
(Half Moon Bay Quadrangle), the boundary line follows Highway 92, beginning in a southeasterly direction, to a point where Highway 92 and the 400-foot contour line intersect 
(San Mateo Quadrangle); 
(2) Thence along the 400-foot contour line, beginning in a southeasterly direction, to a point where the 400-foot contour line and Canada Road intersect 
(Woodside Quadrangle); 
(3) Thence along Canada Road, beginning in a southerly direction, to a point where Canada Road and Highway 280 intersect 
(Woodside Quadrangle); 
(4) Thence along Highway 280, beginning in a southeasterly direction, to a point where Highway 280 and 84 intersect 
(Palo Alto Quadrangle); 
(5) Thence along Highway 84, beginning in a southwesterly direction, to a point where Highway 84 and Mountain Home Road intersect 
(Woodside Quadrangle); 
(6) Thence along Mountain Home Road, beginning in a southerly direction, to a point where Mountain Home Road and Portola Road intersect 
(Palo Alto Quadrangle); 
(7) Thence along Portola Road, beginning in a westerly direction, to a point where Portola Road and Highway 84 intersect 
(Woodside Quadrangle); 
(8) Thence along Highway 84, beginning in a southwesterly direction, to a point where Highway 84 and the 600-foot contour line intersect 
(Woodside Quadrangle); 
(9) Thence along the 600-foot contour line, beginning in a northeasterly direction, to a point where the 600-foot contour line and Regnart Road intersect 
(Cupertino Quadrangle); 
(10) Thence along Regnart Road, beginning in a northeasterly direction, to a point where Regnart Road and the 400-foot contour line intersect 
(Cupertino Quadrangle); 
(11) Thence along the 400-foot contour line, beginning in a southerly direction, to a point where the 400-foot contour line and the north section line of Section 35, T. 6 S./R. 2 W, intersect 
(Cupertino Quadrangle); 
(12) Thence along the north section line of Sections 35 and 36, in an easterly direction, to a point where the section line and Highway 85 intersect 
(Cupertino Quadrangle); 
(13) Thence along Highway 85, in a southerly direction, to a point where Highway 85 and the southern section line of Section 36 intersect 
(Cupertino Quadrangle); 
(14) Thence along the section line, in a westerly direction, to a point where the section line and the 600-foot contour line intersect 
(Cupertino Quadrangle); 
(15) Thence along the 600-foot contour line, beginning in a southerly direction, to a point where the 600-foot contour line and Pierce Road intersect 
(Cupertino Quadrangle); 
(16) Thence along Pierce Road, in a southerly direction, to a point where Pierce Road and the 800-foot contour line intersect 
(Cupertino Quadrangle); 
(17) Thence along the 800-foot line, beginning in a northwesterly direction, to a point where the 800-foot contour line and the east section line of Section 25, T. 10 S./R. 2 E., intersect 
(Mt. Madonna Quadrangle); 
(18) Thence along the east section line, in a southerly direction, to a point where this section line and the 800-foot contour line intersect 
(Mt. Madonna Quadrangle); 
(19) Thence along the 800-foot contour line, beginning in a southeasterly direction, to a point where the 800-foot contour line and Highway 152 intersect 
(Watsonville East Quadrangle); 
(20) Thence along Highway 152, in a southwesterly direction, to a point where Highway 152 and the 400-foot contour line intersect 
(Watsonville East Quadrangle); 
(21) Thence along the 400-foot contour line, beginning in a northwesterly direction, to a point where the 400-foot contour line and the Felton Empire Road intersect 
(Felton Quadrangle); 
(22) Thence along Felton Empire Road, in an easterly direction, to a point where Felton Empire Road and Highway 9 intersect 
(Felton Quadrangle); 
(23) Thence along Highway 9, in a southerly direction, to a point where Highway 9 and Bull Creek intersect 
(Felton Quadrangle); 
(24) Thence along Bull Creek, beginning in a southwesterly direction, to a point where Bull Creek and the 400-foot contour line intersect 
(Felton Quadrangle); and 
(25) Thence along the 400-foot contour line, beginning in a southeasterly direction, back to the point of beginning.

**Comment by fyfangyao** [comment]
I am working on this one.

**Comment by fyfangyao** [comment]
I am still working on this one, and I will finish it within this month.

**Comment by MicheleTobias** [comment]
Thanks!  Once I get this one and Lamorinda from you, and then the last one that I think Sierra is working on, we'll be done with California!

**Comment by MicheleTobias** [comment]
I finished this one.

**Comment by SoominHur** [comment]
Reviewed
- The polygon missed the first intersection of (14) "the section line and the 600-foot contour line (Cupertino Quadrangle)" and started to follow 600' contour line after the second intersection. So I edited the line to follow 600' contour line after the first intersection.
