### ISSUE TITLE
antelope_valley_of_the_california_high_desert

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#19]
# AVA: Antelope Valley of the California High Desert (antelope_valley_of_the_california_high_desert)

name | value
--- | ---
ava_id | antelope_valley_of_the_california_high_desert
cfr_index | 9.219
revision | [T.D. TTB-93, 76 FR 30007, May 24, 2011]
state | CA
county | Kern|Los Angeles
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Rosamond Quadrangle, California, 1973; 
2. Rosamond Lake Quadrangle, California, 1973; 
3. Redman Quadrangle, California, 1992; 
4. Rogers Lake South Quadrangle, California, 1992; 
5. Alpine Butte Quadrangle, California-Los Angeles Co., 1992; 
6. Hi Vista Quadrangle, California-Los Angeles Co., 1957, revised 1992; 
7. Lovejoy Buttes Quadrangle, California-Los Angeles Co., 1957, revised 1992; 
8. El Mirage Quadrangle, California, 1956, revised 1992; 
9. Littlerock Quadrangle, California-Los Angeles Co., 1957, revised 1992; 
10. Palmdale Quadrangle, California-Los Angeles Co., 1958, photorevised 1974; 
11. Ritter Ridge Quadrangle, California-Los Angeles Co., 1958, photorevised 1974; 
12. Lancaster West Quadrangle, California-Los Angeles Co., 1958, photorevised 1974; 
13. Del Sur Quadrangle, California-Los Angeles Co., 1995; 
14. Lake Hughes Quadrangle, California-Los Angeles Co., 1995; 
15. Fairmont Butte Quadrangle, California, 1995; 
16. Neenach School Quadrangle, California, 1995; 
17. Tylerhorse Canyon Quadrangle, California-Kern Co., 1995; 
18. Willow Springs Quadrangle, California-Kern Co., 1965, photorevised 1974; 
19. Little Buttes Quadrangle, California, 1965, photorevised 1974; and 
20. Soledad Mtn. Quadrangle, California-Kern Co., 1973.

## Boundary [src]

(1) The beginning point is on the Rosamond map at the intersection of the Kern and Los Angeles Counties boundary line and the Edwards Air Force Base 
(AFB), boundary line, T8N, R12W. From the beginning point, proceed south along the Edwards AFB boundary line to West Avenue E, where the Edwards AFB boundary line turns east, section 22, T8N/R12W; then 
(2) Proceed generally east along the Edwards AFB boundary line, crossing over the Rosamond Lake and Redman maps, onto the Rogers Lake South map to the point where the Edwards AFB boundary line crosses the 2,500-foot elevation line along the northern boundary of section 30, T8N/R9W; then 
(3) Proceed generally south along the meandering 2,500-foot elevation line, crossing over the Redman and Alpine Butte maps, onto the Hi Vista map to the elevation line&#39;s intersection with Avenue J, section 17, T7N/R9W; then 
(4) Proceed straight east approximately 0.2 mile along Avenue J to the northeast corner of section 20, T7N/R9W, 
(intersection of Avenue J and 160th Street East); then 
(5) Proceed straight south along the eastern boundary lines of sections 20 and 29, T7N/R9W, to the northwestern corner of section 33, T7N, R9W; then 
(6) Proceed in a clockwise direction along the northern and eastern boundary lines of section 33, T7N/R9W, to the northwestern corner of section 3, T6N/R9W 
(intersection of Avenue M and 170th Street East); then 
(7) Proceed in a clockwise direction along the northern and eastern boundary lines of section 3, T6N/R9W, to the northwestern corner of section 11, T6N/R9W; then 
(8) Proceed in a clockwise direction along the northern and eastern boundary lines of section 11, T6N/R9W, crossing onto the Lovejoy Buttes map, to the northwestern corner of section 13, T6N/R9W; then 
(9) Proceed in a clockwise direction along the northern and eastern boundary lines of section 13 and then the eastern boundary line of section 24, T6N/R9W, to the northwestern corner of section 30, T6N/R8W 
(intersection of Avenue Q and 200th Street East); then 
(10) Proceed in a clockwise direction along the northern and eastern boundary lines of section 30, T6N/R8W, to the northwestern corner of section 32, T6N/R8W; then 
(11) Proceed east along the northern boundary of section 32 T6N/R8W, crossing onto the El Mirage map, and continue along the northern boundary of section 33, T6N/R8W, to elevation point 2916 
(along Avenue R); then 
(12) Proceed due south in a straight line to the point where the 3,100-foot elevation line crosses the eastern boundary line of section 8, T5N/R8W; then 
(13) Proceed generally west-southwest along the meandering 3,100-foot elevation line, crossing over the Lovejoy Buttes map, onto the Littlerock map and continue to the elevation line&#39;s intersection with the California Aqueduct, approximately 0.2 mile south of Pearlblossom Highway, section 22, T5N/R10W; then 
(14) Proceed generally north and then northwest along the California Aqueduct, crossing over the Palmdale, Ritter Ridge, Lancaster West, Del Sur, Lake Hughes, and Fairmont Butte maps, onto the Neenach School map to the California Aqueduct&#39;s intersection with the Pacific Crest National Scenic Trail 
(adjacent to the Los Angeles Aqueduct) in section 16, T8N/R16W; then 
(15) Proceed north and then generally east and north along the Pacific Crest National Scenic Trail, crossing over the Fairmont Butte map, and continue onto the Tylerhorse Canyon map to the point where the Trail and the adjacent Los Angeles Aqueduct separate near elevation point 3120 and West Antelope Station in section 3, T9N/R15W; then 
(16) Proceed generally northeast along the Los Angeles Aqueduct crossing onto the Willow Springs map, to the Aqueduct&#39;s intersection with Tehachapi Willow Springs Road, section 7, T10N/R13W; then 
(17) Proceed generally south on Tehachapi Willow Springs Road, crossing onto the Little Buttes map, to the road&#39;s intersection with the 2,500-foot elevation line along the western boundary of section 17, T9N/R13W; then 
(18) Proceed generally east along the meandering 2,500-foot elevation line, crossing over the Willow Springs map and continuing onto the Soledad Mtn. map, where that elevation line crosses over and back three times from the Rosamond map, to the elevation line&#39;s intersection with the Edwards AFB boundary line, section 10, T9N/R12W; and then 
(19) Proceed straight south along the Edwards AFB boundary line, crossing over to the Rosamond map, and return to the beginning point.

**Comment by SoominHur** [comment]
Reviewed
