### ISSUE TITLE
santa_lucia_highlands

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#190]
# AVA: Santa Lucia Highlands (santa_lucia_highlands)

name | value
--- | ---
ava_id | santa_lucia_highlands
cfr_index | 9.139
revision | [T.D. ATF-321, 57 FR 20764, May 15, 1992, as amended by T.D. TTB-49, 71 FR 34527, June 15, 2006]
state | CA
county | Monterey
within | Central Coast\|Monterey
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Chualar, Calif., 1947 
photorevised 1984. 
2. Gonzales, Calif., 1955 
photorevised 1984. 
3. Rana Creek, Calif., 1956 
photoinspected 1973. 
4. Palo Escrito Peak, Calif., 1956 
photorevised 1984. 
5. Soledad, Calif., 1955 
photorevised 1984. 
6. Sycamore Flat, Calif., 1956 
photorevised 1984. 
7. Paraiso Springs, Calif., 1956 
photorevised 1984.

## Boundary [src]

(1) From the beginning point the boundary follows Limekiln Creek for approximately 1.25 miles northeast to the 100 foot elevation. 
(2) Then following the 100 foot contour in a southeasterly direction for approximately 1 mile, where the boundary intersects the west bank of the Salinas River. 
(3) Then following the west bank of the Salinas River in a southeasterly direction on the Gonzales, California U.S.G.S. map for approximately 2.50 miles to the point on the Palo Escrito Peak, California U.S.G.S. map where the river channel crosses the 120 foot elevation. 
(4) Then following the 120 foot elevation due south for approximately 2,200 feet where it climbs to the 160 foot elevation. 
(5) Then following the 160 foot elevation in a southeasterly direction for approximately 6.50 miles, to the point where the 160 foot elevation crosses River Road. 
(6) Then following River Road in a southeasterly direction for approximately 1 mile to the junction of River, Fort Romie and Foothill Roads. 
(7) Then following Foothill Road in a southeasterly direction for approximately 4 miles to the junction of Foothill and Paraiso Roads on the Soledad, California U.S.G.S. map. 
(8) Then following Paraiso Road in a southerly direction to the intersection with Clark Road on the Paraiso Springs, California U.S.G.S. map. 
(9) Then east-northeasterly along Clark Road for approximately 1,000 feet to its intersection with an unnamed light-duty road to the south. 
(10) Then in a straight south-southeasterly line for approximately 1.9 miles to the line&#39;s intersection with the southeast corner of section 33, T18S, R6E 
(this line coincides with the unnamed light duty road for about 0.4 miles and then with the eastern boundaries of sections 29, 32 and 33, T18S, R6E, which mark this portion of the western boundary of the historical Arroyo Seco Land Grant). 
(11) Then straight west along the southern boundaries of sections 33, 32, and 31, T18S, R6E, to the southwest corner of section 31. 
(12) Then north along the western boundaries of sections 31 and 30, to the northwestern corner of section 30 T. 18S., R. 6E. 
(13) Then northwest in a straight diagonal line to the northwest corner of section 24, T. 18S., R. 5E on the Sycamore Flat, California U.S.G.S. map. 
(14) Then north along the western boundary of section 13, T. 18S., R. 5E., to the northwestern corner of section 13, T. 18S., R. 5E. 
(15) Then northwest in a diagonal line across sections 11 and 3, to the northwest corner of section 3, T. 18S., R. 5E on the Palo Escrito Peak, California U.S.G.S. map. 
(16) Then due west along the southern boundary of section 33, T. 17S., R. 5E., to the southwestern corner of section 33, T. 17S., R. 5E. 
(17) Then north along the western boundary of section 33 to the southeast corner of section 29, T. 17S., R. 5E. 
(18) Then northwest in a diagonal line through sections 29, 19, 13, and 11, to the northwest corner of section 11, T. 17S., R. 4E on the Rana Creek, California U.S.G.S. map. 
(19) Then north along the western boundary of section 2, T. 17S., R. 4E., to the northwestern corner of section 2, T. 17S., R. 4E. 
(20) Then west along the southern boundary of section 34, T. 16S., R. 4E., to the southwestern corner of section 34, T. 16S., R. 4E. 
(21) Then north along the eastern boundary of sections 33 and 28, T. 16S., R. 4E., for approximately 1 mile, to the point where the eastern boundary of section 28 T. 165., R. 4E., coincides with the western boundary of the Guadalupe Y Llanitos de los Correos Land Grant on the Chualar, California U.S.G.S. map. 
(22) Then northwest along the grant line for approximately 2,500 feet to the point of beginning on Limekiln Creek.

**Comment by fyfangyao** [comment]
I am working on this one

**Comment by fyfangyao** [comment]
Rana Creek, Calif., 1956 (photoinspected 1977).

**Comment by SoominHur** [comment]
Reviewed.
- (5) Followed 160' elevation only 1 mile instead of "approximately 6.50 miles, to the point where the 160 foot elevation crosses River Road." So, meandered 160' contour about 5 more miles and then moved onto River Road.
- Add description about the beginning point in the attribute table.
- Add scale information of used maps in the attribute table.
- Could not found "Rana Creek, CA" photoinspected 1997, which fyfangyao used. So I used "Rana Creek, CA" 1956, photoinspected 1973, Scale 1:24000, which was listed as approved maps)
