### ISSUE TITLE
santa_margarita_ranch

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#191]
# AVA: Santa Margarita Ranch (santa_margarita_ranch)

name | value
--- | ---
ava_id | santa_margarita_ranch
cfr_index | 9.247
revision | [T.D. TTB-125, 79 FR 60967, Oct. 9, 2014]
state | CA
county | San Luis Obispo
within | Central Coast\|Paso Robles
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Santa Margarita, Calif., 1965, revised 1993; 
2. Lopez Mountain, CA, 1995; 
3. San Luis Obispo, CA, 1995; and 
4. Atascadero, CA, 1995.

## Boundary [src]

(1) The beginning point is on the Santa Margarita map at the intersection of the northern boundary line of section 10, T29S/R13E, and the Salinas River. From the beginning point, proceed southerly 
(upstream) along the meandering Salinas River approximately 7.9 miles, crossing onto the Lopez Mountain map, to the river&#39;s intersection with the R13E/R14E boundary line, which coincides with the eastern boundary line of section 36, T29S/R13E; then 
(2) Proceed south along the R13E/R14E boundary line approximately 3.2 miles to the boundary line&#39;s first intersection with the Los Padres National Forest boundary line, section 13, T30S/R13E; then 
(3) Proceed northwesterly along the Los Padres National Forest boundary line approximately 4 miles to the Forest boundary line&#39;s intersection with the T29S/T30S boundary line, near the northwest corner of section 3, T30S/R13E; then 
(4) Proceed west along the Los Padres National Forest boundary line and then the T29S/T30S boundary line approximately 2 miles to the southwest corner of section 32, T29S/R13E; then 
(5) Proceed north along the western boundary line of section 32, T29S/R13E, and then the Los Padres National Forest boundary line to northwest corner of section 32 where the Forest boundary line makes a 90 degree turn to the west; then 
(6) Proceed west along the Los Padres National Forest boundary line approximately 1.5 miles, crossing onto the San Luis Obispo map, to the point where the Los Padres National Forest boundary line first dips to the south and is no longer concurrent with the northern boundary line of section 36, T29S/R12E; then 
(7) Proceed north-northwesterly in a straight line approximately 2.25 miles, crossing onto the Atascadero map, to the western-most intersection of the 1,400-foot elevation line with the northern boundary line of section 23, T29S/R12E; then 
(8) Proceed west along the northern boundary line of section 23, T29S/R12E, approximately 0.6 mile to the section&#39;s northeast corner; then 
(9) Proceed east along the western boundary line of section 13, T29S/R12E, to the section&#39;s northwest corner, and then continue east along the northern boundary line of section 13, T29S/R12E, to the section boundary line&#39;s intersection with the R12E/R13E common boundary line at section 13&#39;s northeast corner; then 
(10) Proceed due north along the R12E/R13E common boundary line approximately 0.75 mile to the boundary line&#39;s intersection with the T-intersection of two unnamed unimproved roads, locally known as Powerline Road and Santa Margarita Road; then 
(11) Proceed easterly and then east-northeasterly on Santa Margarita Road approximately 1.5 miles, crossing onto the Santa Margarita map, to the road&#39;s intersection with El Camino Real, Santa Margarita Land Grant, T29S/R13E; then 
(12) Proceed southeasterly on El Camino Real approximately 300 feet to the road&#39;s intersection with an unnamed light-duty road locally known as Asuncion Road at BM 931 
(just south of Santa Margarita Creek), Santa Margarita Land Grant; then 
(13) Proceed northeasterly on Asuncion Road approximately 0.3 mile 
(crossing a railroad line) to the road&#39;s intersection with Chispa Road; then 
(14) Proceed due east in a straight line approximately 0.1 mile to the line&#39;s intersection with the boundary line of the Santa Margarita Land Grant, which, at this point, is concurrent with the southwestern boundary line of section 5, T29S/R13E; then 
(15) Proceed southeasterly along the Santa Margarita Land Grant boundary line approximately 0.7 mile to the boundary line&#39;s intersection with the northwest corner of section 9, T29S/R13E, and then continue east along the northern boundary lines of sections 9 and 10, T29S/R13E, approximately 1.15 miles, returning to the beginning point.

**Comment by SoominHur** [comment]
Reviewed.
- Some direction descriptions do not make sense. Following are the descriptions that do not make sense and direction inside [ ] is how previous worker & I guess what the description must meant.
(8) "Proceed west [ -> east] along the northern boundary line of section 23, T29S/R12E, approximately 0.6 mile to the section's northeast corner"
(9) "Proceed east [-> north] along the western boundary line of section 13, T29S/R12E, to the section's northwest corner"
- added scale information of used maps in the attribute table
