### ISSUE TITLE
santa_maria_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#192]
# AVA: Santa Maria Valley (santa_maria_valley)

name | value
--- | ---
ava_id | santa_maria_valley
cfr_index | 9.28
revision | [T.D. ATF-89, 46 FR 39812, Aug. 5, 1981, as amended by T.D. TTB-88, 75 FR 81849, Dec. 29, 2010]
state | CA
county | San Luis Obispo|Santa Barbara
within | Central Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Orcutt Quadrangle, California-Santa Barbara Co., 7.5 minute series, 1959, photorevised 1967 and 1974, photoinspected 1978; 
2. Santa Maria Quadrangle, California, 7.5 minute series, 1959, photorevised 1982; 
3. “San Luis Obispo”, N.I. 10-3, series V 502, scale 1: 250,000; 
4. “Santa Maria”, N.I. 10-6, 9, series V 502, scale 1: 250,000; 
5. Foxen Canyon Quadrangle, California-Santa Barbara Co., 7.5-minute series, 1995; and 
6. Sisquoc Quadrangle, California-Santa Barbara Co., 7.5 minute series, 1959, photoinspected 1974.

## Boundary [src]

(1) Begin on the Orcutt quadrangle map at the intersection of U.S. Route 101 and Clark Avenue, section 18 north boundary line, T9N/R33W, then proceed generally north along U.S. Route 101 approximately 10 miles onto the Santa Maria quadrangle map to U.S. Route 101&#39;s intersection with State Route 166 
(east), T10N/R34W; then 
(2) Proceed generally northeast along State Route 166 
(east) onto the San Luis Obispo N.I. 10-3 map to State Route 166&#39;s intersection with the section line southwest of Chimney Canyon, T11N/R32W; then 
(3) Proceed south in a straight line onto the Santa Maria N.I. 10-6 map to the 3,016-foot summit of Los Coches Mountain; then 
(4) Proceed southeast in a straight line onto the Foxen Canyon quadrangle map to the 2,822-foot summit of Bone Mountain, T9N/R32W; then 
(5) Proceed south-southwest in a straight line approximately 6 miles to the line&#39;s intersection with secondary highways Foxen Canyon Road and Alisos Canyon Road and a marked 1,116-foot elevation point, T8N/R32W; then 
(6) Proceed west-northwest in a straight line approximately 6 miles onto the Sisquoc quadrangle map to the southeast corner of section 4, T8N/R32W; then 
(7) Proceed west-northwest in a straight line approximately 6.2 miles, crossing over the Solomon Hills, to the line&#39;s intersection with U.S. Route 101 and a private, unnamed light-duty road that meanders east into the Cat Canyon Oil Field, T9N/R33W; then 
(8) Proceed north 3.75 miles along U.S. Route 101 onto the Orcutt quadrangle map and return to the point of beginning.

**Comment by SoominHur** [comment]
Reviewed
- Add edition and revised years of (3) “San Luis Obispo”, N.I. 10-3, series V 502, scale 1: 250,000 and (4) “Santa Maria”, N.I. 10-6, 9, series V 502, scale 1: 250,000 in the attribute table.
