### ISSUE TITLE
santa_ynez_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#193]
# AVA: Santa Ynez Valley (santa_ynez_valley)

name | value
--- | ---
ava_id | santa_ynez_valley
cfr_index | 9.54
revision | [T.D. ATF-132, 48 FR 16252, Apr. 15, 1983]
state | CA
county | Santa Barbara
within | Central Coast
contains | Ballard Canyon\|Happy Canyon of Santa Barbara\|Los Olivos District\|Sta. Rita Hills

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Figueroa Mountain, Cal.”, 7.5 minute series, edition of 1959; 
2. “Foxen Canyon, Cal.”, 7.5 minute series, edition of 1964; 
3. “Lake Cachuma, Cal.”, 7.5 minute series, edition of 1959; 
4. “Lompoc, Cal.”, 7.5 minute series, edition of 1959 
photorevised 1974.; 
5. “Lompoc Hills, Cal.”, 7.5 minute series, edition of 1959; 
6. “Los Alamos, Cal.”, 7.5 minute series, edition of 1959; 
7. “Los Olivos, Cal.”, 7.5 minute series, edition of 1959 
photoinspected 1974.; 
8. “Santa Rosa Hills, Cal.”, 7.5 minute series, edition of 1959; 
9. “Santa Ynez, Cal.”, 7.5 minute series, edition of 1959 
photorevised 1974.; 
10. “Solvang, Cal.”, 7.5 minute series, edition of 1959 
photorevised 1974.; 
11. “Zaca Creek, Cal.”, 7.5 minute series, edition of 1959; and 
12. “Zaca Lake, Cal.”, 7.5 minute series, edition of 1964.

## Boundary [src]
longitude line. 
(1) Then north following the 120°22  longitude line to Cebada Canyon Road. 
(2) Then northeast following Cebada Canyon Road and an unnamed jeep trail to the northern boundary of Section 9, T. 7 N., R. 33 W. 
(3) Then east following the northern boundaries of Sections 9, 10, 11, 12, 7, and 8 to the northeast corner of Section 8, T. 7 N., R. 33 W. 
(4) Then south following the eastern boundaries of Sections 8 and 17 to the intersection with the boundary dividing the La Laguna and San Carlos de Jonata Land Grants. 
(5) Then east following the boundary between the La Laguna and the San Carlos de Jonata Land Grants to the intersection with Canada de Santa Ynez. 
(6) Then northeast in a straight line for approximately 3.6 miles to Benchmark 947 at U.S. Highway 101. 
(7) Then northeast in a straight line for approximately 2.6 miles to the southwest corner of the La Zaca Land Grant. 
(8) Then following the boundary of the La Zaca Land Grant north, then east to its northeast corner. 
(9) Then east in a straight line for approximately 2.0 miles to the point of intersection of the La Laguna and Sisquoc Land Grants with the Los Padres National Forest. 
(10) Then following the boundary of the Los Padres National Forest south, east, and south until it intersects with the eastern boundary of Section 29, T. 7 N., R. 29 W. 
(11) Then south following the eastern boundaries of Sections 29, 32, 5, 8, and 17 to the boundary of the Cachuma Recreation Area at Bitt Benchmark 1074. 
(12) Then following the boundary of the Cachuma Recreation Area west and south to the point of intersection with the Los Padres National Forest. 
(13) Then south and west following the boundary of the Los Padres National Forest to its intersection with the Las Cruces Land Grant at the southwest corner of Section 12, T. 5 N., R. 32 W. 
(14) Then north following the boundary of the Las Cruces Land Grant to the southeast corner of Section 26, T. 6 N., R. 32 W. 
(15) Then west following the southern boundaries of Sections 26, 27, 28, and 29 to the intersection with the northern boundary of the San Julian Land Grant at the southwestern corner of Section 29, T. 6 N., R. 32 W. 
(16) Then northwest following the boundary of the San Julian Land Grant to its intersection with the 120°22  longitude line. 
(17) Then northwest in a straight line for approximately 3.2 miles to the point where Santa Rosa Road intersects Salsipuedes Creek. 
(18) Then following Salsipuedes Creek downstream to the point of confluence with the Santa Ynez River. 
(19) Then northeast in a straight line for approximately 1.4 miles to an unnamed hill, elevation 597 feet. 
(20) Then northeast in a straight line for approximately 1.7 miles to the point of beginning.

**Comment by SoominHur** [comment]
Reviewed.
- Could not find the “Figueroa Mountain, CA” edition of 1959, scale 1:24000, so used “Figueroa Mountain, CA” edition of 1995, scale 1:24000 for review
