### ISSUE TITLE
san_ysidro_district

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#194]
# AVA: San Ysidro District (san_ysidro_district)

name | value
--- | ---
ava_id | san_ysidro_district
cfr_index | 9.130
revision | [T.D. ATF-305, 55 FR 47749, Nov. 15, 1990]
state | CA
county | Santa Clara
within | Central Coast\|San Francisco Bay\|Santa Clara Valley
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Gilroy, Calif., 1955 
photorevised 1981.; 
2. Chittenden, Calif., 1955 
photorevised 1980.; 
3. San Felipe, Calif., 1955 
photorevised 1971.; 
4. Gilroy Hot Springs, Calif., 1955 
photorevised 1971, photoinspected 1978..

## Boundary [src]

(1) The beginning point is the intersection of California State Highway 152 and Ferguson Road with an un-named wash, or intermittent stream, on the Gilroy, Calif., U.S.G.S. map; 
(2) From the beginning point, the boundary follows the wash northeast as it runs co-incident with the old Grant boundary for approximately 3,800 feet; 
(3) The boundary then follows the wash when it diverges from the old Grant boundary and continues approximately 2,300 feet in a northeasterly direction, crosses and recrosses Crews Road, then follows the wash southeast until the wash turns northeast in section 35, T.10S., R.4E., on the Gilroy Hot Springs, Calif., map; 
(4) The boundary then diverges from the wash, continuing in a straight line in a southeasterly direction, across an unimproved road, until it intersects with the 600 foot contour line. 
(5) The boundary then proceeds in a straight line at about the 600 foot elevation in a southeasterly direction until it meets the minor northerly drainage of the San Ysidro Creek; 
(6) The boundary then follows the minor northerly drainage of San Ysidro Creek southeast for approximately 2,000 feet to the seasonal pond adjacent to Canada Road; 
(7) From the seasonal pond, the boundary follows the southerly drainage of San Ysidro Creek for about 1,300 feet until it reaches the southwest corner of section 36, T.10S., R.4E.; 
(8) The boundary then continues in a straight line in a southerly direction across Canada Road for approximately 900 feet until it intersects with the 600 foot contour line; 
(9) The boundary follows the 600 foot contour line for approximately 6,000 feet in a generally southeasterly direction, diverges from the contour line and continues southeast another 1,200 feet until it meets an unimproved road near the north end of a seasonal pond on the San Felipe, Calif., U.S.G.S. map; 
(10) The boundary follows the unimproved road to Bench Mark 160 at Highway 152. 
(11) The boundary then follows Highway 152 in a northwesterly direction across the northeast corner of the Chittenden, Calif., U.S.G.S. map, and back to the beginning point at the junction of Ferguson Road and Highway 152.

**Comment by ehurr** [comment]
I am working on this

**Comment by MicheleTobias** [comment]
@ehurr Are you still planning to work on this one?  As we get close to finishing CA, I may need to re-assign this one to @fyfangyao so just let me know where you're at.  It's no big deal either way.

**Comment by ehurr** [comment]
Hi Michele,

No I haven't been able to start it. Please reassign it! Sorry for not
releasing it earlier.

Thanks,
Emily

**Comment by MicheleTobias** [comment]
No worries!  I'll remove the In Progress tag so someone else can pick it up if they want.  Feel free to claim this one again or another if you want to work on one later.

**Comment by sierramabanta** [comment]
Hi Michele, I'd like to work on this one!

**Comment by ariellerose** [comment]
I'm on it!

 (I will be working on this one)

**Comment by MicheleTobias** [comment]
Thanks for finishing this one up, @ariellerose !  Once I get this one and the two Yao is working on, we'll be done with CA!  I'd like to get all the data in by the end of June, so don't hesitate to ask questions if something isn't working right.

**Comment by SoominHur** [comment]
Reviewed.
- Corrected created date & cfr. author @ attribute table
- (9) is unclear whether the line should "diverges from the contour line ... until it meets an unimproved road" in straight line or when the contour line actually intersect with unimproved road. Left as previous person worked ("diverges from the contour line ... until it meets an unimproved road" in straight line).
