### ISSUE TITLE
seiad_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#195]
# AVA: Seiad Valley (seiad_valley)

name | value
--- | ---
ava_id | seiad_valley
cfr_index | 9.148
revision | [T.D. ATF-357, 59 FR 26114, May 19, 1994]
state | CA
county | Siskiyou
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

(b) Approved map. The appropriate map for determining the boundary of the Seiad Valley viticultural area is a U.S.G.S. 7.5 minute series topographical map of the 1:24000 scale, titled “Seiad Valley, Calif.,” 1980.

## Boundary [src]
(c) Boundary. The Seiad Valley viticultural area is located in Siskiyou County, California. The boundary is as follows:

(1) The beginning point is the intersection of the 1600 foot contour line with the power transmission line north of the Klamath River, near Mile 130; 
(2) From the beginning point, the boundary follows the 1600  contour line in a generally northeasterly direction until it reaches the intersection of an unnamed light duty road and an unimproved road just west of Canyon Creek; 
(3) The boundary then follows the unimproved road north to its end, then goes east in a straight line until it reaches the 1800  contour line; 
(4) The boundary then follows the 1800  contour line in a northeasterly direction to the point, near Sawmill Gulch, where the contour line crosses Seiad Creek and turns south and west; 
(5) The boundary continues to follow the 1800  contour line as it proceeds southwest for approximately 4.5 miles, then turns sharply south-southeast for approximately 0.3 miles, until the contour line turns sharply east at a point just north of the Klamath River; 
(6) The boundary then diverges from the 1800  contour line and proceeds south-southeast in a straight line, across the Klamath River and State Route 96, until it intersects with the 1600  contour line; 
(7) The boundary then follows the 1600  contour line south and west, then north and west, roughly following the course of the Klamath River, until it reaches an unnamed peak 1744 feet high; 
(8) The boundary continues along the 1600  contour line as it diverges from the Klamath River and proceeds south, just to the east of an unnamed light duty road, to the point where that road crosses Grider Creek; 
(9) The boundary diverges from the contour line and proceeds west in a straight line across the road and Grider Creek until it intersects with the 1600  contour line on the west side of Grider Creek;  
(10) The boundary then follows the 1600  contour line north, west and north again until it reaches a point where the contour line turns west, just south of the Klamath River; 
(11) The boundary diverges from the 1600  contour line and proceeds in a straight line in a northeasterly direction, back to the point of beginning.

**Comment by SoominHur** [comment]
Reviewed,
