### ISSUE TITLE
seneca_lake

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#196]
# AVA: Seneca Lake (seneca_lake)

name | value
--- | ---
ava_id | seneca_lake
cfr_index | 9.128
revision | [T.D. TTB-3, 68 FR 39835, July 3, 2003]
state | NY
county | Ontario|Schuyler|Seneca|Yates
within | Finger Lakes
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Burdett Quadrangle 
New York—Schuyler Co. 1950 (photoinspected 1976.); 
2. Montour Falls Quadrangle 
New York 1978 (photorevised 1976.); 
3. Beaver Dams Quadrangle 
New York 1953.; 
4. Reading Center Quadrangle 
New York 1950 (photorevised 1978.); 
5. Dundee Quadrangle 
New York 1942 (photoinspected 1976.); 
6. Dresden Quadrangle 
New York 1943 (photorevised 1978.); 
7. Penn Yan Quadrangle 
New York—Yates Co. 1942 (photoinspected 1976.); 
8. Stanley Quadrangle 
New York 1952.; 
9. Phelps Quadrangle 
New York—Ontario Co. 1953.; 
10. Geneva North Quadrangle 
New York 1953 (photorevised 1976.); 
11. Geneva South Quadrangle 
New York 1953 (photorevised 1978.); 
12. Ovid Quadrangle 
New York—Seneca Co. 1970.; and 
13. Lodi Quadrangle 
New York 1942..

## Boundary [src]

(1) Beginning in the town of Watkins Glen at the State Route 414 bridge over the New York State Barge Canal, follow the Canal south approximately 0.2 miles to the mouth of Glen Creek, on the Burdette, N.Y. map; 
(2) Follow Glen Creek upstream 
(west), crossing onto the Montour Falls, N.Y. map and continuing to the road locally known as the Van Zandt Hollow Road on the Beaver Dams, N.Y. map; 
(3) Proceed north on Van Zandt Hollow Road to Cross Road; 
(4) Continue north on Cross Road, which changes to Cretsley Road, to its intersection with Mud Lake Road 
(County Road 23) on the Reading Center, N.Y. map; 
(5) Proceed west approximately 0.7 miles on County Road 23 to its intersection with Pre-emption Road; 
(6) Then continue north on Pre-emption Road along the Dundee, N.Y., Penn Yan, N.Y. and Dresden, N.Y. maps, for approximately 18 miles to its junction with an unnamed light duty road just east of Keuka Lake Outlet on the Penn Yan, N.Y. map; 
(7) Follow the unnamed light duty road across the Keuka Outlet, traveling approximately 0.3 miles to its junction in Seneca Mills with an unnamed light duty road, known locally as Outlet Road; 
(8) Follow Outlet Road west along the north bank of the Keuka Outlet approximately 0.6 miles, until the road forks; 
(9) At the fork, continue north approximately 1 mile, on an unnamed light duty road know locally as Stiles Road, to its junction with Pre-emption Road. 
(10) Then proceed north 14.6 miles on Pre-emption Road across the Stanley, N.Y. map, to an unnamed medium duty road, known locally as County Road 4, on the Phelps, N.Y. map; 
(11) Continue west approximately 4.5 miles on County Road 4 to its intersection with Orleans Road in Seneca Castle; 
(12) Then proceed north on Orleans Road, which becomes Seneca Castle Road, for 2.1 miles, to Warner Corners where the name of the road changes to Wheat Road; 
(13) Continue north from Warner Corners on Wheat Road approximately 1.9 miles to its intersection with State Route 88; 
(14) Continue north on State Route 88 approximately 1.4 miles, to its intersection with State Route 96 at Knickerbocker Corner; 
(15) Continue east on State Route 96 approximately 10.4 miles, to the intersection with Brewer Road on the Geneva North, N.Y. map; 
(16) Follow Brewer Road south approximately 1.8 miles to the intersection with U.S. Route 20/State Route 5; 
(17) At the intersection of Brewer Road and U.S. Route 20/State Route 5, continue south approximately 0.1 miles, following an imaginary line to the south bank of the Seneca River; 
(18) Follow the south bank of the Seneca River east approximately 0.1 miles to the mouth of the Kendig Creek; 
(19) Continue south following the Kendig Creek approximately 3.3 miles to the Creek&#39;s intersection with Yellow Tavern Road on the Geneva South, N.Y. map; 
(20) Follow Yellow Tavern Road west approximately 0.1 miles, to its intersection with Post Road; 
(21) Follow Post Road south approximately 1.4 miles to its junction with State Route 96A; 
(22) Then follow State Route 96A south 17.5 miles across the Dresden, N.Y., Ovid, N.Y., and Lodi, N.Y. maps to the village of Lodi; 
(23) In Lodi, continue south where State Route 96A changes to S. Main Street and then changes to an unnamed medium duty road 
(known locally as Center Road-Country Road 137); 
(24) Continue south on Center Road-Country Road 137 for approximately 4.9 miles to the Seneca/Schuyler County Line; 
(25) Then proceed west 0.5 miles on the county line to Logan Road; 
(26) Then proceed 8.6 miles south on Logan Road to State Route 227 
(identified by the petitioner as State Route 79) on the Burdette, N.Y. map; 
(27) Then proceed approximately 800 feet east on Route 227 to Skyline Drive; 
(28) Then proceed south on Skyline Drive for 2.5 miles to an unnamed stream; 
(29) Follow the unnamed stream west approximately 0.6 miles to its intersection with State Route 414; and 
(30) Continue west on State Route 414 approximately 0.5 miles to the beginning point on the bridge over the New York State Barge Canal.

**Comment by ekalalip** [comment]
I'd like to start working on this location

**Comment by MicheleTobias** [comment]
Sounds good! I changed the tag for you to "In Progress".  Let me, Alex, or Sierra know if you have questions!

**Comment by ekalalip** [comment]
thank you. I actually decided to work on ozark_highlands

**Comment by ericallanwest** [comment]
Please label this one In Progress and Virginia Tech. Thanks!

**Comment by MicheleTobias** [comment]
Welcome @ericallanwest !  Let me know if you have any questions!

**Comment by ericallanwest** [comment]
I believe this issue can be closed as a result of PR #483.

**Comment by MicheleTobias** [comment]
Hi Eric, I will get to these when I have a chance to go through the state of the project.
