### ISSUE TITLE
shawnee_hills

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#197]
# AVA: Shawnee Hills (shawnee_hills)

name | value
--- | ---
ava_id | shawnee_hills
cfr_index | 9.206
revision | [T.D. TTB-57, 71 FR 68471, Nov. 27, 2006]
state | IL
county | Alexander|Gallatin|Hardin|Jackson|Johnson|Pope|Pulaski|Randolph|Saline|Union|Williamson
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Boundary [src]

(1) Beginning at the intersection of State Routes 3 and 150 in the town of Chester 
(Randolph County), proceed northeast on Route 150 to its intersection with the surveyed boundary line between Township 6 South 
(T6S) and Township 7 South 
(T7S); then 
(2) Proceed due east along the T6S/T7S boundary line until it becomes the boundary between Perry and Jackson Counties, and continue east along the Perry-Jackson County line to State Route 4; then 
(3) Proceed southeast on State Route 4 through the villages of Campbell Hill, Ava, and Oraville to its intersection with State Route 13/127; then 
(4) Proceed south on State Route 13/127 to the intersection where State Routes 13 and 127 divide in the town of Murphysboro; then 
(5) Proceed east on State Route 13 through the city of Carbondale to State Route 13&#39;s intersection with Interstate 57; then 
(6) Proceed south on Interstate 57 to its intersection with State Route 148; then 
(7) Proceed southeast on State Route 148 to its intersection with State Route 37; then 
(8) Proceed south on State Highway 37 to Saline Creek; then 
(9) Proceed northeasterly 
(downstream) along Saline Creek to its confluence with the South Fork of the Saline River, then continue easterly 
(downstream) along the South Fork of the Saline River to its confluence with the Saline River, then continue easterly and then southeasterly 
(downstream) along the Saline River to its confluence with the Ohio River near Saline Landing; then 
(10) Proceed southwesterly 
(downstream) along the Ohio River to the Interstate 24 bridge; then 
(11) Proceed north on Interstate 24 to its intersection with the New Columbia Ditch 
(with the towns of Big Bay to the northeast and New Columbia to the northwest); then 
(12) Proceed westerly along the New Columbia Ditch to its confluence with the Main Ditch, and continue westerly along the Main Ditch to its confluence with the Cache River 
(near the Cache River&#39;s confluence with the Post Creek Cutoff), approximately 1.5 miles east-northeast of the village of Karnak; then 
(13) Proceed westerly 
(downstream) along the Cache River, passing under Interstate 57 near the village of Ullin, and continue southeasterly along the Cache River to the river&#39;s confluence with Sandy Creek 
(northeast of the village of Sandusky); then 
(14) Proceed westerly 
(upstream) along Sandy Creek approximately 4 miles to its junction with an unnamed secondary road 
(known locally as Alexander County Road 4); then 
(15) Proceed south along the unnamed secondary road 
(Alexander County Road 4) to its junction with State Route 3 at the village of Olive Branch; then 
(16) Proceed northwest on State Route 3 to its intersection with the Main Ditch 
(also known locally as Sexton Creek) at the village of Gale; then 
(17) Proceed northerly along Main Ditch and Clear Creek Ditch to a light-duty road 
(known locally as State Forest Road) near the southwest corner of the Trail of Tears State Forest, approximately 3.75 miles east of the village of Wolf Lake; then 
(18) Proceed west on the light-duty road 
(State Forest Road) to its intersection with State Route 3 just south of Wolf Lake; then 
(19) Proceed north on State Route 3 to its junction with the Big Muddy River 
(near the village of Aldridge), and continue north 
(upstream) along the Big Muddy River to its confluence with Kincaid Creek near the village of Grimsby; then 
(20) Continue northerly along Kincaid Creek to its junction with State Route 149; then 
(21) Proceed west on State Route 149 to its junction with State Route 3, and then continue northwest along State Route 3 to the beginning point in the town of Chester.

**Comment by Alexenia** [comment]
I would like to do this one.

**Comment by Alexenia** [comment]
The are two versions of the Paducah, KY map, one with the edition date 1987 but with a scale of 100,000 (though the eCFR asks for a scale of 1:250,000) and the other has an edition date of 1988 but with a scale of 1:250,000 (thought the eCFR asks for the edition date 1987), could you let me know which I should download?

**Comment by MicheleTobias** [comment]
It's better to use a map with the right scale but a slightly different date.  The reason is, when you change the scale, you change what's visible and included so some of the landmarks will be missing if you use a different scale map.  Also, I'm guessing that the 1988 map listed on TopoView is actually the 1987 map printed in 1988.  They list the printing date, not the date the map was made.

**Comment by Alexenia** [comment]
When I changed the Geojson file and Geotiff file coordinate system to WGS 83, I could no longer see the two layers overlaying each other in QGIS. Is that normal? Also, I'm not sure if WGS83 is the correct coordinate system, could you let me know?

**Comment by Alexenia** [comment]
Sorry, I just sent a push request.

**Comment by Alexenia** [comment]
Following along the Ohio River and there is a small waterway (on google maps it is also recognized as the Ohio River) which separates and returns to the Ohio River. Could you let me know if I should follow along the small waterway or keep to the River? 
<img width="570" alt="ohio river" src="https://user-images.githubusercontent.com/46324469/51893648-60d34c80-235a-11e9-85a3-486696d4c6c5.png">

**Comment by MicheleTobias** [comment]
I would probably stick to the main river, but I could see reasons to go along the channel too.  Whatever you decide, make a comment on the issue noting which step was confusing and what you decided to do about it.

**Comment by MicheleTobias** [comment]
This happens sometimes and I'm not entirely sure why.  Try saving your map document, then close QGIS and reopen the project.  Usually restarting QGIS solves the problem.

**Comment by Alexenia** [comment]
ISSUE#1: 
No instruction on whether to follow the canal (also the Ohio River) that splits from and returns to Ohio River, IL. 

(ECFR: 9.206-Shawnee Hills). Step 10. States: " Proceed southwesterly (downstream) along the Ohio River to the interstate 24 bridge, then."

Action Taken: Digitized along the main Ohio River because it conservatively follows the instruction given.

**Comment by Alexenia** [comment]
ISSUE#2: Cache Creek splits and returns to the main 'Cache River'.
Need instruction on which, the upper or lower Cache River to digitized. 

STEP 13: states, "Proceed westerly (downstream) along the Cache River, passing under Interstate 57 near the village of Ullin, and continue southeasterly along the Cache River to the river's confluence with Sandy Creek (northeast of the village of Sandusky); then."

Action Taken: Followed along the curved (lower) Cache River because it includes more area.

**Comment by Alexenia** [comment]
ISSUE#3:
State Forest Road is not labeled on map, confirmation needed.

Step 17: states, " Proceed northerly along Main Ditch and Clear Creek Ditch to a light-duty road (known locally as State Forest Road) near the southwest corner of the Trail of Tears State Forest, approximately 3.75 miles east of the village of Wolf Lake; then."

Action Taken: Though the State Forest Road is not labeled on map, I compared it with Google maps and it resembled State Forest Road so it was digitized as such.

**Comment by Alexenia** [comment]
Great, thank you!
