### ISSUE TITLE
shenandoah_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#198]
# AVA: Shenandoah Valley (shenandoah_valley)

name | value
--- | ---
ava_id | shenandoah_valley
cfr_index | 9.60
revision | [T.D. ATF-120, 47 FR 57698, Dec. 28, 1982, as amended by T.D. ATF-249, 52 FR 5958, Feb. 27, 1987]
state | VI|WV
county | 
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Boundary [src]

(1) The boundary line starts at the point of the intersection of the Potomac River and the Virginia-West Virginia State line approximately eight miles east of Charlestown, West Virginia. 
(2) Then the boundary proceeds southwesterly approximately 14.8 miles along the State line, which essentially follows the crest of the Blue Ridge Mountains, to its intersection with the western border line of Clarke County, Virginia. 
(3) Then the boundary continues approximately 13.8 miles southwesterly along the county line and the crest of the Blue Ridge to its intersection with the western boundary line of Warren County, Virginia. 
(4) Then the boundary continues approximately 15 miles along the Warren County line to its intersection with the Skyline Drive. 
(5) Then the boundary continues approximately 71 miles in a southwesterly direction along the Skyline Drive and the Blue Ridge to its intersection with the Blue Ridge Parkway. 
(6) Then the boundary continues approximately 53 miles in a southeasterly direction along the Blue Ridge Parkway to its intersection with the James River. 
(7) Then the boundary proceeds approximately 44 miles along the James River in a west-northwesterly direction to its intersection with the northwest boundary line of the Jefferson National Forest near Eagle Rock. 
(8) Then the boundary proceeds approximately 10.5 miles in a northeasterly direction along the Jefferson National Forest line and along the crest of North Mountain to its intersection with the western boundary line of Rockbridge County. 
(9) Then the boundary continues approximately 23 miles along the county line in the same northeasterly direction to its intersection with the Chesapeake and Ohio Railroad. 
(10) Then the boundary continues approximately 23 miles along the railroad between the Great North Mountain and the Little North Mountain to its intersection with the southeastern boundary line of the George Washington National Forest at Buffalo Gap. 
(11) Then the boundary continues approximately 81 miles northeasterly along the George Washington National Forest Line to the Vertical Control Station, 
(elevation 1883), on the crest of Little North Mountain approximately 3 miles west of Van Buren Furnace. 
(12) Then the boundary line continues approximately 53 miles northeasterly along the crest of Little North Mountain to its intersection with the Potomac River in Fort Frederick State Park. 
(13) Then the boundary continues approximately 47.4 miles southeasterly along the Potomac River to the beginning point at that River&#39;s intersection with the boundary line between West Virginia and Virginia.

**Comment by dannyo33** [comment]
I'm currently working on this AVA.

**Comment by dannyo33** [comment]
Completed digitization of the AVA.

**Comment by dannyo33** [comment]
I can't seem to find the petition for Shenandoah Valley when I search for it through HeinOnline. There is only reference of the AVA in other petitions.

**Comment by MicheleTobias** [comment]
One reason it's challenging is that the original boundary was amended/changed.  You can tell that because the revision history string above on this page lists two documents.  You will need to find and read both.  Searching for the document code like "47 FR 57698" for the first document should turn it up.  Adding main words from the AVA name can help too ("valley" won't get you anything new).

Also, please be very meticulous in digitizing this boundary.  It's one of the more famous AVAs and it will likely get scrutinized.  Not that we don't want to always do a good job, because we do.

**Comment by davidkli** [comment]
I have checked this AVA and the boundary is good and no changes were made.
