### ISSUE TITLE
sierra_foothills

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#199]
# AVA: Sierra Foothills (sierra_foothills)

name | value
--- | ---
ava_id | sierra_foothills
cfr_index | 9.120
revision | [T.D. ATF-261, 52 FR 44105, Nov. 18, 1987]
state | CA
county | Amador
within | 
contains | California Shenandoah Valley\|El Dorado\|Fair Play\|Fiddletown\|North Yuba\|Calaveras\|El Dorado\|Mariposa\|Nevada\|Placer\|Tuolumne\|Yuba

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Chico” 
NJ 10-3., edition of 1958, revised 1970. 
2. “Sacramento” 
NJ 10-6., edition of 1957 revised 1970. 
3. “San Jose” 
NJ 10-9., edition of 1962, revised 1969. 
4. “Mariposa” 
NJ 11-7., edition of 1957, revised 1970.

## Boundary [src]

(1) Beginning on the “Chico” map at the point of intersection of the north border of T
(ownship) 18 N
(orth), R
(ange) 6 E
(ast), with S. Honcut Creek the boundary proceeds approximately 3.5 miles, in a generally south and southwesterly direction, along the eastern bank of S. Honcut Creek to the point where S. Honcut Creek meets the western border of T. 18 N., R. 6 E.; 
(2) Then south, approximately 15 miles, along the western borders of T. 18 N., T. 17 N., and T. 16 N. in R. 6 E., to the point where the western border of T. 16 N., R. 6 E. meets the northernmost perimeter of Beale Air Force Base in the southwestern corner of T. 16 N., R. 6 E.; 
(3) Then east, south and west along the perimeter of Beale Air Force Base to the point where the perimeter of Beale Air Force Base intersects the western border of R. 7 E. in T. 14 N.; 
(4) Then south, approximately 24 miles, along the western borders of T. 14 N., T. 13 N., T. 12 N., and T. 11 N. in R. 7 E., to the southwestern corner of T. 11 N., R. 7 E. 
(see “Sacramento” map); 
(5) Then east, approximately six miles, along the south border of T. 11 N., R. 7 E., to the southeastern corner of T. 11 N., R. 7 E.; 
(6) Then in a south southeasterly direction, in a straight line, approximately three miles, to the northeasternmost corner of Sacramento County in T. 10 N., R. 8 E.; 
(7) Then continuing in a south southeasterly direction, in a straight line, along the Sacramento County—El Dorado County line, approximately 15 miles, to the point where the county line meets the Cosumnes River in the southwestern corner of T. 8 N., R. 9 E.; 
(8) Then south, in a straight line, approximately 14.1 miles, along the Sacramento County—Amador County line, to the point where the county line meets Dry Creek in the northwestern corner of T. 5 N., R. 9 E.; 
(9) Then in a south southeasterly direction, in a stright line, approximately 5.4 miles. along the San Joaquin County—Amador County line, to the point where the Mokelumne River forms the Amador County—Calaveras County line in T. 4 N., R. 9 E.; 
(10) Then continuing in a south southeasterly direction, in a straight line, approximately 10.4 miles, along the San Joaquin County-Calaveras County line, to the point where the power line meets the western border of T. 3 N., R. 10 E.; 
(11) Then in a southeasterly direction, in a straight line, approximately 22.4 miles, along the Calaveras County-Stanislaus County line to the point where the county line meets the Stanislaus River in T. 1 S., R. 12 E. 
(see “San Jose” map); 
(12) Then in a southeasterly direction, in a straight line, approximately 20 miles, along the Tuolumne County-Stanislaus County line to the point where the county lines of Tuolumne, Mariposa, Stanislaus and Merced counties meet in the southeast corner of T. 3 S., R. 14 E.; 
(13) Then continuing along the Mariposa County-Merced County line in a generally southeasterly direction, approximately 37 miles, to the point where the county lines of Mariposa, Merced and Madera counties meet in the northwestern corner of T. 9 S, R. 18 E.; 
(14) Then northeasterly in a straight line, approximately 23 miles, along the Mariposa County-Merced County line to the point, approximately one mile west of Miami Mountain, where the Mariposa County-Merced County line meets the western border of the boundary of the Sierra National Forest in T. 6S, R. 20 E. 
(see “Mariposa” map); 
(15) Then in a generally northerly and westerly direction, along the western borders of the Sierra and Stanislaus National Forests in Mariposa County 
(see “San Jose” map); 
(16) Then in a generally northerly and westerly direction, along the western border of the Stanislaus National Forest in Tuolumne County 
(see “Sacramento” map); 
(17) Then in a generally northerly and westerly direction, along the western border of the Stanislaus National Forest in Calaveras and Amador counties; 
(18) Then in a generally northerly and westerly direction, along the western border of the El Dorado National Forest in Amador, El Dorado and Placer counties 
(see “Chico” map); 
(19) Then in a generally northerly and westerly direction, along the western border of the Tahoe National Forest in Placer, Nevada and Yuba counties to the point south of Ruef Hill where the western border of the Tahoe National Forest intersects the northeast corner of T. 18 N., R. 6 E.; 
(20) Then west, approximately five miles, along the north border of T. 18 N., R. 6 E., to the point of beginning.

**Comment by fyfangyao** [comment]
I am working on this.

**Comment by fyfangyao** [comment]
I use “Chico, Cali., scale 1:25,000, 1958, revised 1973,“ “Sacramento, Cali., scale 1:25,000, 1957, revised 1972,” “San Jose, Cali., scale 1:25,000, 1962, revised 1971,” and “Mariposa, Cali., scale 1:25,000, 1957, revised 1971” because I cannot find the map with the required revision year.

**Comment by MicheleTobias** [comment]
I checked this one and made a minor adjustment to step 6.
