### ISSUE TITLE
appalachian_high_country

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#20]
# AVA: Appalachian High Country (appalachian_high_country)

name | value
--- | ---
ava_id | appalachian_high_country
cfr_index | 9.260
revision | [T.D. TTB-144, 81 FR 74679, Oct. 27, 2016]
state | NC|TN|VI
county | 
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Unicoi, Tenn.-N.C, 1939; photorevised 1978; 
2. Iron Mountain Gap, Tenn.-N.C., 1960; photorevised 1968; 
3. Johnson City, Tenn., 1959; photorevised 1968; 
4. Elizabethton, Tenn., 1959; photorevised 1968; 
5. Watauga Dam, Tenn., 1960; 
6. Carter, Tenn., 1938; photorevised 1969; 
7. Keenburg, Tenn., 1960; 
8. Doe, Tenn., 1938; photorevised 1969; 
9. Shady Valley, Tenn.-VA., 1960; photorevised 1970; photoinspected 1988; 
10. Laurel Bloomery, Tenn.-VA., 1938; photorevised 1969; 
11. Grayson, Tenn.-N.C.-VA., 1959; photoinspected 1976; 
12. Park, N.C.-VA., 1959; photorevised 1978; 
13. Whitetop Mountain, VA., 1959; photorevised 1978; 
14. Trout Dale, VA., 1959; photorevised 1978; photoinspected 1988; 
15. Middle Fox Creek, VA., 1959; photoinspected 1988; 
16. Cedar Springs, VA., 1959; photorevised 1978; photoinspected 1988; 
17. Speedwell, VA., 1968; photorevised 1979; 
18. Cripple Creek, VA., 1968; photoinspected 1988; 
19. Austinville, VA., 1965; photorevised 1979; photoinspected 1982; 
20. Galax, VA., 1965; photorevised 1984; 
21. Cumberland Knob, N.C.-VA., 1965; photorevised 1977; 
22. Lambsburg, VA.-N.C., 1965; photorevised 1977; 
23. Roaring Gap, N.C., 1971; 
24. Glade Valley, N.C., 1968; 
25. Traphill, N.C., 1968; 
26. Whitehead, N.C., 1968; 
27. McGrady, N.C., 1968; photoinspected 1984; 
28. Horse Gap, N.C., 1968; 
29. Laurel Springs, N.C., 1968; 
30. Glendale Springs, N.C., 1967; 
31. Maple Springs, N.C., 1966; 
32. Deep Gap, N.C., 1967; 
33. Buffalo Cove, N.C., 1967; 
34. Globe, N.C., 1959; 
35. Grandfather Mountain, N.C., 1960; photorevised 1978; 
36. Newland, N.C., 1960; photorevised 1978; 
37. Linville Falls, N.C., 1994; 
38. Ashford, N.C., 1994; 
39. Little Switzerland, N.C., 1994; 
40. Spruce Pine, N.C., 1994; 
41. Celo, N.C., 1994; 
42. Micaville, N.C., 1960; photorevised 1978; 
43. Bakersville, N.C.,-Tenn., 1960; photorevised 1978; 
44. Burnsville, N.C., 1998; 
45. Huntdale, N.C.-Tenn., 1939; and 
46. Chestoa, Tenn.-N.C., 1939; photorevised 1978.

## Boundary [src]

(1) The beginning point is on the Unicoi map, at the point where the Unicoi/Mitchell County line intersects with an unnamed road known locally as Unaka Mountain Road near Beauty Spot Gap, Tennessee. From the beginning point, proceed northeasterly approximately 7.3 miles along the Unicoi/Mitchell County line, crossing onto the Iron Mountain Gap map, to the intersection of the Unicoi/Mitchell County line with the Carter County line; then 
(2) Proceed northerly along the Unicoi/Carter County line approximately 9.3 miles, crossing back onto the Unicoi map and then onto the Johnson City map, to the intersection of the Unicoi/Carter County line with the 2,000-foot elevation contour, southeast of an unnamed road known locally as Whispering Pine Road; then 
(3) Proceed southeasterly along the meandering 2,000-foot elevation contour, crossing onto the Unicoi map and then back onto the Johnson City map, and continuing onto the Elizabethton map for approximately 19 miles to the intersection of the elevation contour with an unnamed road known locally as Brimer Road near Bremer Hollow; then 
(4) Proceed northwesterly approximately 1,500 feet along Brimer Road to an unnamed road known locally as Jenkins Hollow Road; then 
(5) Proceed easterly approximately 1.4 miles along Jenkins Hollow Road, crossing the Doe River, to U.S. Route 321 in the town of Valley Forge, Tennessee; then 
(6) Proceed north approximately 400 feet along U.S. Route 321 to an unnamed road known locally as Ruby Harmon Road; then 
(7) Proceed northeasterly approximately 360 feet along Ruby Harmon Road to an unnamed road known locally as Nanny Goat Hill Road; then 
(8) Proceed easterly approximately 0.2 mile along Nanny Goat Hill Road to the 1,800-foot elevation contour, east of an unnamed road known locally as Gene Mathes Road; then 
(9) Proceed northeasterly approximately 0.4 mile along the 1,800-foot elevation contour to an unnamed road known locally as Franklin Lane; then 
(10) Proceed southerly approximately 0.3 mile along Franklin Lane to the 2,000-foot elevation contour; then 
(11) Proceed northeasterly along the meandering 2,000-foot elevation contour, crossing over Hardin Branch, Clover Branch, South Pierce Branch, and North Pierce Branch, to a fifth, unnamed stream; then 
(12) Proceed northerly approximately 0.47 mile along the unnamed stream to an unnamed road known locally as Wilbur Dam Road; then 
(13) Proceed southeasterly approximately 0.25 mile along Wilbur Dam Road to Wilbur Dam; then 
(14) Proceed northeasterly across Wilbur Dam to the marked transmission line; then 
(15) Proceed northerly approximately 0.5 mile along the transmission line to the 2,000-foot elevation contour; then 
(16) Proceed northeasterly approximately 19 miles along the meandering 2,000-foot elevation contour, crossing over the Watauga Dam map and onto the Carter map, and continuing along the 2,000-foot elevation contour as it crosses over State Route 91 near Sadie, Tennessee, and turns southwesterly, and continuing southwesterly for approximately 22.2 miles along the 2,000-foot elevation contour, crossing onto the Keenburg map and circling Carter Knob, to the intersection of the 2,000-foot elevation contour with the Carter/Sullivan County line; then 
(17) Proceed southeasterly, then northeasterly, approximately 7 miles along the Carter/Sullivan County line to an unnamed road known locally as National Forest Road 56, near Low Gap, Tennessee; then 
(18) Proceed easterly approximately 0.75 mile along National Forest Road 56, crossing onto the Carter map, to the Carter/Sullivan County line; then 
(19) Proceed easterly approximately 10.4 miles along the Carter/Sullivan County line, crossing over the Doe map 
(northwestern corner) and onto the Shady Valley Map, to the intersection of the Carter/Sullivan County line with the Johnson County line at Rich Knob, Tennessee; then 
(20) Proceed northeasterly approximately 13.4 miles along the Johnson/Sullivan County line, crossing onto the Laurel Bloomery map, to the intersection of the Johnson/Sullivan County line with the Washington County line at the Virginia/Tennessee State line; then 
(21) Proceed easterly approximately 10 miles along the Johnson/Washington County line, crossing onto the Grayson map, to the intersection of the Johnson/Washington County line with the Grayson County line; then 
(22) Proceed east, then northeasterly, then southeasterly, along the Grayson County line, crossing over the Park, Whitetop Mountain, Trout Dale, Middle Fox Creek, Cedar Springs, Speedwell, Cripple Creek, Austinville, Galax, and Cumberland Knob maps and onto the Lambsburg map, to the intersection of the Grayson County line with the Surry County line and an unnamed road known locally as Fisher&#39;s Peak Road, at the Virginia/North Carolina State line; then 
(23) Proceed west along the Grayson/Surry County line, crossing back onto the Cumberland Knob map, to Alleghany County line; then 
(24) Proceed southerly, then northwesterly, then southwesterly along the Alleghany County line, crossing over the Roaring Gap, Glade Valley, Traphill 
(northeastern corner), Whitehead, McGrady 
(northwestern corner), Horse Gap, and Laurel Springs map, then back onto the Horse Gap map and continuing along the Alleghany County line on the Horse Gap map to the Ashe/Wilkes County line at Mulberry Gap, North Carolina; then 
(25) Proceed westerly, then southwesterly along the Ashe/Wilkes County line, crossing over the Glendale Springs and onto the Maple Springs map, then back onto the Glendale Springs map, then back onto the Maple Springs map, and continuing along the Ashe/Wilkes County line on the Maple Springs map to the intersection of the Ashe/Wilkes County line and the Watauga County line at Thomkins Knob, North Carolina; then 
(26) Proceed southwesterly along the Watauga/Wilkes County line, crossing over the Deep Gap map 
(southeastern corner) and onto the Buffalo Cove map, to the intersection of the Watauga/Wilkes County line and the Caldwell County line at White Rock Mountain, North Carolina; then 
(27) Proceed west along the Watauga/Caldwell County line, crossing over the Globe map and onto the Grandfather Mountain map, to the intersection of the Watauga/Caldwell County line with the Avery County line at Calloway Peak, North Carolina; then 
(28) Proceed southeasterly approximately 1.8 miles along the Caldwell/Avery County line to the boundary of the Blue Ridge Parkway at Pilot Knob, North Carolina; then 
(29) Proceed southwesterly approximately 11.6 miles along the Blue Ridge Parkway boundary, crossing over the Newland map 
(southeastern corner) and onto the Linville Falls map, to the intersection of the parkway boundary with the Avery/Burke County line; then 
(30) Proceed northwesterly, then southwesterly, for a total of approximately 4.2 miles along the Avery/Burke County line to the McDowell County line; then 
(31) Proceed southerly approximately 5 miles along the Avery/McDowell County line to the Mitchell County line; then 
(32) Proceed southerly, then southwesterly, along the McDowell/Mitchell County line, crossing over the Ashford 
(northwestern corner) and Little Switzerland 
(northeastern corner) maps and onto the Spruce Pine map, then back onto the Little Switzerland map and continuing along the McDowell/Mitchell County line, crossing onto the Celo map, to the intersection of the McDowell/Mitchell County line with the Yancey County line; then 
(33) Proceed west then northerly along the Mitchell/Yancey County line, crossing over the Micaville, Bakersville, Huntdale 
(southeastern corner), and Burnsville maps, then back onto the Huntdale map and continuing along the Mitchell/Yancy County line, crossing onto the Chestoa map, to the intersection of the Mitchell/Yancey County line with the Mitchell/Unicoi County line, which is concurrent with the Tennessee/North Carolina State line; then 
(34) Proceed northeasterly along the Mitchell/Unicoi County line, crossing back over the Huntsdale 
(northwestern corner) map and onto the Unicoi map, returning to the beginning point.

**Comment by ericallanwest** [comment]
Please label this one In Progress and Virginia Tech. Thanks!

**Comment by davidkli** [comment]
This AVA has been checked. The boundaries were updated to follow the boundary descriptions. Boundary was also updated to share the same border as Yadking Valley as the descriptions for both indicate that they are neighboring AVAs.
