### ISSUE TITLE
sierra_pelona_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#200]
# AVA: Sierra Pelona Valley (sierra_pelona_valley)

name | value
--- | ---
ava_id | sierra_pelona_valley
cfr_index | 9.218
revision | [T.D. TTB-86, 75 FR 42604, July 22, 2010]
state | CA
county | Los Angeles
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Agua Dulce, CA, 1995; 
2. Sleepy Valley, CA, 1995; and 
3. Ritter Ridge, Calif., 1958, Photorevised 1974.

## Boundary [src]

(1) The beginning point is on the Agua Dulce map at the intersection of the section 26 east boundary line, the pipeline, and Escondido Canyon Road, a secondary highway, T5N, R14W. From the beginning point, proceed in a straight line south 0.3 mile to the line&#39;s intersection with the northeast corner of the Vasquez Rocks County Park, T5N, R14W; then 
(2) Proceed southwest through section 26 along the straight lines and 90-degree turns of the county park boundary line to the line&#39;s intersection with the southeast corner of section 27, T5N, R14W; then 
(3) Proceed southwest in a straight line 0.4 mile to the line&#39;s intersection with BM 2258, section 34, T5N, R14W; then 
(4) Proceed west-northwest in a straight line 0.15 mile, crossing over the Agua Dulce Road, to the line&#39;s intersection with the 2,400-foot elevation line and an unimproved dirt road, section 34, T5N, R14W; then 
(5) Proceed generally west along the meandering 2,400-foot elevation line to the line&#39;s intersection with the section 34 west boundary line, T5N, R14W; then 
(6) Proceed north along the section 34 west boundary line 1 mile to the line&#39;s intersection with the 2,800-foot elevation line and the section 27 west boundary line; then 
(7) Proceed along the 2,800-foot elevation line first generally northeast, then northwest around Saddleback Mountain, and then north across a trail and an unimproved dirt road, to the line&#39;s intersection with the section 21 south boundary line, T5N, R14W; then 
(8) Proceed straight east along the section 21 south boundary line 0.25 mile to the southeast corner of section 21, T5N, R14W; then 
(9) Proceed north along the section 21 south boundary line onto the Sleepy Valley map 0.6 mile to the line&#39;s intersection with the 2,800-foot elevation line and the section 22 west boundary line, T5N, R14W; then 
(10) Proceed along the 2,800-foot elevation line generally northeast around the 3,166-foot and 3,036-foot pinnacles, then continue southwest to the line&#39;s intersection with the section 22 north boundary line, T5N, R14W; then 
(11) Proceed west along the section 22 north boundary line 0.2 mile to the line&#39;s intersection with the 2,600-foot elevation line, T5N, R14W; then 
(12) Proceed generally west-southwest along the 2,600-foot elevation line to the line&#39;s intersection with the section 21 west boundary line, T5N, R14W; then 
(13) Proceed north along the section 21 west boundary line 0.2 mile to the line&#39;s intersection with the 2,400-foot elevation line and the section 20 east boundary line, T5N, R14W; then 
(14) Proceed generally southwest along the 2,400-foot elevation line to the line&#39;s intersection with an unimproved dirt road in section 20, T5N, R14W; then 
(15) Proceed northwest along the unimproved dirt road 0.15 mile to its intersection with the Sierra Highway, a secondary highway, section 20, T5N, R14W; then 
(16) Proceed southwest along the Sierra Highway 0.15 mile to its intersection with an unnamed stream, section 20, T5N, R14W; then 
(17) Proceed in a straight line north-northwest approximately 0.3 mile to the line&#39;s intersection with the Angeles National Forest boundary line, an unnamed stream running through Rowher Canyon, and the section 17 south boundary line, T5N, R14W; then 
(18) Proceed straight east, north, and east, making 90-degree turns, along the Angeles National Forest boundary line to the line&#39;s intersection with the section 7 southwest corner, T5N, R13W; then 
(19) Proceed straight north along the Angeles National Forest boundary line and the section 7 west boundary line 0.5 mile to the line&#39;s intersection with the 3,400-foot elevation line, T5N, R13W; then 
(20) Proceed along the 3,400-foot elevation line generally east, north, then west to the line&#39;s intersection with the section 6 west boundary line, T5N, R13W; then 
(21) Proceed north along the section 6 west boundary line 0.4 mile to the line&#39;s intersection with the 3,400-foot elevation line, T5N, R13W; then 
(22) Proceed generally southeast along the 3,400-foot elevation line, crossing over Latteau, Willow Springs, and Hauser Canyons and continuing onto the Ritter Ridge map, to the line&#39;s intersection with an unimproved dirt road at Summit, section 16, T5N, R13W; then 
(23) Proceed south along the unnamed dirt road less than 0.1 mile, crossing the Sierra Highway, to its intersection with the 3,400-foot elevation line, section 16, T5N, R13W; then 
(24) Proceed generally southwest along the 3,400-foot elevation line, meandering between the Sleepy Valley and Ritter Ridge maps and then returning to the Sleepy Valley map, to the line&#39;s intersection with the section 20 north boundary line, T5N, R13W; then 
(25) Proceed in a straight line west along the section 20 north boundary line 0.2 mile to the line&#39;s intersection with the 3,200-foot elevation line, section 20, T5N, R13W; then 
(26) Proceed generally southwest along the 3,200-foot elevation line to the line&#39;s intersection with the section 19 west boundary line, T5N, R13W; then 
(27) Proceed in a straight line north along the section 19 west boundary line 0.15 mile to the line&#39;s intersection with a pipeline, T5N, R13W; and then 
(28) Proceed southwest onto the Agua Dulce map 1.25 miles along the pipeline, returning to the beginning point.

**Comment by SoominHur** [comment]
Reviewed.
