### ISSUE TITLE
sloughhouse

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#201]
# AVA: Sloughhouse (sloughhouse)

name | value
--- | ---
ava_id | sloughhouse
cfr_index | 9.201
revision | [T.D. TTB-50, 71 FR 40414, July 17, 2006]
state | CA
county | Sacramento
within | Lodi
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Clay, Calif., 1968, photorevised 1980, minor revision 1993; 
2. Sloughhouse, Calif., 1968, photorevised 1980, minor revision 1993; 
3. Elk Grove, Calif., 1968, photorevised 1979; 
4. Buffalo Creek, Calif., 1967, photorevised 1980; 
5. Folsom SE, Calif., 1954, photorevised 1980; and 
6. Carbondale, Calif., 1968, photorevised 1980, minor revision 1993.

## Boundary [src]

(1) The beginning point is on the Clay map at the intersection of the Laguna estuary and Alta Mesa Road, on the western boundary of section 4, T5N, R7E. From the beginning point, proceed north 4.8 miles on Alta Mesa Road to the road&#39;s intersection with a line drawn due west from the western end of the landing strip shown in the northwestern quadrant of section 16, T6N, R7E 
(Sloughhouse Quadrangle); then 
(2) Proceed east 0.5 mile to the eastern end of the landing strip, section 16, T6N, R7E 
(Sloughhouse Quadrangle); then 
(3) Proceed northeast in a straight line 0.1 mile to the center of the loop at the south end of Tavernor Road, section 16, T6N, R7E 
(Sloughhouse Quadrangle); then 
(4) Proceed north 0.75 mile on Tavernor Road to its intersection with Blake Road, section 9, T6N, R7E 
(Sloughhouse Quadrangle); then 
(5) Proceed east 0.5 mile on the unimproved extension of Blake Road to its intersection with the 105-foot elevation line, section 9, T6N, R7E 
(Sloughhouse Quadrangle); then 
(6) Proceed due north about 0.85 mile to the 90 degree turn in Tavernor Road and continue north about 0.9 mile on Tavernor Road to its intersection with Lee Shorthorn Road, T7N, R7E 
(Sloughhouse Quadrangle); then 
(7) Proceed northwest 0.9 mile on Lee Shorthorn Road to its intersection with Dillard Road, T7N, R7E 
(Sloughhouse Quadrangle); then 
(8) Proceed southwest about 2.6 miles on Dillard Road to its intersection with Wilton Road at the hamlet of Dillard, section 6, T6N, R7E 
(Elk Grove Quadrangle); then 
(9) Proceed northwest 3.1 miles on Wilton Road to its intersection with Grant Line Road at the hamlet of Sheldon, section 27, T7N, R6E 
(Elk Grove Quadrangle); then 
(10) Proceed northwest on Grant Line Road to its intersection with State Route 16 
(Jackson Road), section 33, T8N, R7E 
(Buffalo Creek Quadrangle); then 
(11) Proceed east-southeast 1.6 miles on State Route 16 to its intersection with Deer Creek at BM 108 near Sloughhouse, T8N, R7E 
(Sloughhouse Quadrangle); then 
(12) Proceed northeasterly 
(upstream) about 11 miles along the meandering Deer Creek, crossing over the southeast corner of the Buffalo Creek map, to the creek&#39;s intersection with the Sacramento-El Dorado County line, section 1, T8N, R8E 
(Folsom, S.E. Quadrangle); then 
(13) Proceed south-southeast followed by south for about 12.4 miles along the Sacramento-El Dorado and Sacramento-Amador County line to the County line&#39;s intersection with the Laguna estuary, 0.75 mile south of the Ione Road, T6N, R9E 
(Carbondale Quadrangle); and 
(14) Proceed westerly 
(downstream) 17.5 miles along the meandering Laguna estuary, crossing over the Sloughhouse map, and return to the beginning point on the Clay Quadrangle.

**Comment by fyfangyao** [comment]
I am working on it

**Comment by fyfangyao** [comment]
I use “Elk Grove, Quad, Cali., 7.5 minute series, 1968, photorevised 1980” because I cannot find the map with the required revision year.

**Comment by SoominHur** [comment]
Continue Reviewing.
- Add petitioner and cfr author names in the attribute table because it was blank. 
- Add scale information of used maps in the attribute table.
