### ISSUE TITLE
snake_river_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#202]
# AVA: Snake River Valley (snake_river_valley)

name | value
--- | ---
ava_id | snake_river_valley
cfr_index | 9.208
revision | [T.D. TTB-59, 72 FR 10602, Mar. 9, 2007]
state | ID|OR
county | 
within | 
contains | Eagle Foothills (ID)

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Baker, Oregon-Idaho, 1981; 
2. Brogan, Oregon-Idaho, 1980; 
3. McCall, Idaho-Oregon, 1980, Photoinspected 1990; 
4. Weiser, Idaho-Oregon, 1980, Photoinspected 1990; 
5. Boise, Idaho-Oregon, 1981; 
6. Idaho City, Idaho, 1982; 
7. Murphy, Idaho, 1986; 
8. Mountain Home, Idaho, 1990; 
9. Fairfield, Idaho, 1978; 
10. Twin Falls, Idaho, 1979; 
11. Glenns Ferry, Idaho, 1992; 
12. Triangle, Idaho, 1990; 
13. Mahogany Mountain, Idaho, 1978; and 
14. Vale, Oregon-Idaho, 1993.

## Boundary [src]

(1) The beginning point is on the Baker map in Oregon at the intersection of the 1,040-meter contour line and Interstate 84, between Pleasant Valley and Oxman in Baker County, T10S/R42E; 
(2) From the beginning point proceed east following the 1,040-meter contour line along the eastern side of the Burnt River Valley, then crossing over to the Brogan map, proceed northerly along the western side of the Snake River Valley and, crossing back over to the Baker map, proceed westerly along the southern side of the Powder River Valley to the 1,040-meter contour line&#39;s intersection with the northern boundary of Baker County, T7S/R40E, on the Baker map; 
(3) Proceed 7.5 miles straight east along the northern boundary of Baker County to its intersection with the 1,040-meter line east of Oregon State Road 203 and three unnamed creeks, T7S/R41E, on the Baker map; 
(4) Proceed generally southeast along the 1,040-meter contour line onto the McCall map, to its intersection with the 45 degree north latitude line, to the immediate west of North Creek in the Hell&#39;s Canyon National Recreation Area, T6S/R47E, on the northern border of the McCall map; 
(5) Proceed straight east along the 45 degree north latitude line to its intersection with the 1,040-meter contour line, to the immediate east of North Creek, T6S/R47E, on the McCall map; 
(6) Follow the 1,040-meter contour line, which encircles the northern portion of McLain Gulch, to its third intersection with the 45 degree north latitude line, west of the Snake River in Baker County, Oregon, T6S/R48E, on the McCall map; 
(7) Proceed straight east along the 45 degree north latitude line to its intersection with the 1,040-meter contour line, to east of the Snake River and Indian Creek in Adams County, Idaho, T6S/R48W, on the McCall map; 
(8) Continue following the 1,040-meter contour line in a generally clockwise rotation on the McCall map, proceeding southerly on the southeast side of the Snake River, northeasterly north of the Crooked River, crossing the Crooked River, T7S/R3W, proceeding southwesterly south of the Crooked River, crossing Brownlee Creek, T16N/R4W, proceeding generally southwesterly onto the Baker map, continuing southwesterly, crossing Sturgill Creek, T15N/R6W, and Dennett Creek, T14N/R6W, proceeding onto the Brogan map, proceeding southeasterly, crossing Rock Creek, T13N/R6W, proceeding onto the Weiser map, proceeding northeasterly, north of the Mann Creek State Recreation Area, crossing Mann Creek, T13N/R5W, continuing northeasterly onto the McCall map; 
(9) Continue following the 1,040-meter contour line in a clockwise rotation on the McCall map, proceeding northeasterly, crossing Pine Creek, T15N/R4W, and Hornet Creek, T8S/R2W, passing west of the Payette National Forest, proceeding southerly, passing east of Mesa, onto the Weiser map, proceeding southerly, crossing Crane Creek, T12N/R1W, turning westerly, rounding north of the Paddock Valley Reservoir, crossing Willow Creek, T9N/R1W, turning southerly onto the Boise map, looping southerly and northerly north of the Black Canyon Reservoir and moving back onto the Weiser map; 
(10) Continue following the 1,040-meter contour line in a clockwise rotation on the Weiser map, proceeding northerly, crossing Squaw Creek, T12N/R1E, and then southerly, crossing Cottonweed Creek, T11N/R1E, and then southerly again onto the Boise map, rounding south of South Mountain, back onto the Weiser map, proceeding northeasterly north of the Payette River, crossing the North Fork Payette River, T10N/R3E, then proceeding southwesterly south of the Payette River, onto the Boise map, proceeding generally southerly, crossing Cartwright Creek, T6N/R2E, and proceeding westerly and southeasterly towards Lucky Peak Lake, and then turning northward onto the Idaho City map; 
(11) Continue following the 1,040-meter contour line in a clockwise rotation on the Idaho City map, proceeding northerly, crossing Grimes and Mores Creek, T5N/R4E, and then proceeding southerly to Lucky Peak Lake, turning northeasterly north of the Lucky Peak Lake, Arrowrock Reservoir, and Middle Fork Boise River to T4N/R7E, crossing the Middle Fork Boise River and proceeding southwesterly south of the Middle Fork Boise River, to the South Fork Boise River, crossing the South Fork Boise River, T2N/R6E, proceeding onto the Boise map proceeding southwesterly south of Lucky Peak Lake onto the Murphy map; 
(12) Continue following the 1,040-meter contour line in a clockwise rotation southeasterly on the Murphy map to the Mountain Home map, proceeding southeasterly, crossing Canyon Creek, passing north of Mountain Home Reservoir, crossing King Hill Creek, onto the Fairfield map, proceeding easterly, crossing Clover Creek, T4S/R13E, proceeding southerly onto the Twin Falls map; 
(13) Continue following the 1,040-meter contour line in a clockwise rotation on the Twin Falls map, proceeding southeasterly to the Snake River, T9S/R14E, following north of the Snake River and crossing at T10S/R18E, northeast of Twin Falls, proceeding westerly south of the Snake River to the Salmon River, following east of the Salmon River and crossing at T10S/R13E, proceeding northerly west of the Salmon River and the Hagerman Wildlife Management Area, proceeding west onto the Glenns Ferry map; 
(14) Continue following the 1,040-meter contour line in a clockwise rotation on the Glenns Ferry map, proceeding generally west to Rosevear Gulch, turning south between Rosevear Gulch and Pilgrim Gulch, near Deadman Creek, heading northwesterly, continuing through the Bruneau Desert, crossing Hole Creek in Pot Canyon and proceeding to Bruneau Canyon, proceeding southeasterly east of Bruneau Canyon, crossing Bruneau Canyon, T10S/R7E, proceeding west of Bruneau Canyon then west onto the Triangle map; 
(15) Continue following the 1,040-meter contour line in a clockwise rotation on the Triangle map, heading northwesterly, crossing Shoofly Creek and Alder Creek, T6S/R1W, onto the Murphy map, continuing northwesterly to Sinker Creek, crossing Sinker Creek, T4S/R2W, continuing northwesterly to Jump Creek, crossing Jump Creek, T1N/R5W, proceeding northwesterly onto the Boise map, crossing its southwestern corner, T2N/R5W, onto the Mahogany Mountain map; 
(16) Continue following the 1,040-meter contour line in a clockwise rotation onto the Mahogany Mountain map, proceeding westerly onto the Vale map, generally northwesterly then southwesterly onto the Mahogany Mountain map, proceeding southwest, west, and generally north onto the Vale map, passing through Succor Creek State Recreational Area, returning to the Mahogany Mountain map, and, passing east of McIntyre Ridge, crossing Succor Creek, T1N/R46E, proceeding northerly back onto the Vale map; 
(17) Continue following the 1,040-meter contour line in a clockwise rotation on the Vale map, proceeding northerly east of Owyhee Ridge and Long Draw to north of Lake Owyhee, southwesterly and southerly south of Lake Owyhee onto the Mahogany Mountain map, southwesterly south of Lake Owyhee, the Owyhee River, and Owyhee Canyon, crossing Owyhee Canyon at T29S/R41E, proceeding northerly west of Owyhee Canyon, northeasterly west of Owyhee River and Owyhee Reservoir, and northerly onto the Vale map; 
(18) Continue following the 1,040-meter contour line in a clockwise rotation on the Vale map, proceeding generally northerly to T20S/R42E, southwesterly east of Cottonwood Creek, crossing Cottonwood Creek, T22S/R40E, proceeding north to the Malheur River, following the Malheur River westerly to the intersection of the 1,040-meter contour line and the 118 degree west longitude line in Malheur County, Oregon, T21S/R38E, on the western border of the Vale map; 
(19) Proceed straight north along the 118 degree west longitude line to its intersection with the 1,040-meter contour line, north of the Malheur River, T20S/R38E, proceeding easterly north of the Malheur River to Hog Creek, crossing Hog Creek, T20S/R40E, and proceeding northerly on the Vale map; 
(20) Continue following the 1,040-meter contour line in a clockwise rotation, crossing onto the Brogan map, proceeding easterly, northerly, and westerly to and around Malheur Reservoir, T14S/R41E, proceeding easterly to Cottonwood Gulch then northerly to Dixie Creek, crossing Dixie Creek, T12S/RR41E, proceeding easterly and northerly onto the Baker map; 
(21) Continue following the 1,040-meter contour line in a clockwise rotation on the Baker map, proceeding westerly south of the Burnt River, crossing the Burnt River, T10S/R41E, proceeding easterly north of the Burnt River to Gravel Pits, then northerly, returning to the beginning point.

**Comment by elistockwell** [comment]
QUALITY CONTROL: The original digitization, although citing the approved maps in used maps, obviously used a different source.  The approved maps are available, so it had to be redone.  However, there were a couple of issues.  Firstly, the boundary went off of the approved maps in a couple places, so there I used similar date/scale maps.  The larger issue I ran into was that a few of the approved maps did not have the feature that the boundary followed, having a 1050 m contour line instead of the required 1040.  In steeper areas (contour lines closer together) I simply estimated the 1040 line by interpolating between 1000 and 1050 with occasional references to the topoview basemap to check the behavior of the contour lines.  In flatter areas this was no longer accurate, so there I supplemented with unapproved 1:24000 maps.  However, these maps used feet instead of meter elevations so I still had to interpolate, but it was interpolating between something like 1038 and 1042 feet instead of 1000 to 1050
