### ISSUE TITLE
snipes_mountain

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#203]
# AVA: Snipes Mountain (snipes_mountain)

name | value
--- | ---
ava_id | snipes_mountain
cfr_index | 9.213
revision | [T.D. TTB-73, 74 FR 3424, Jan. 21, 2009]
state | WA
county | Yakima
within | Yakima Valley\|Columbia Valley
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Sunnyside, Wash., 1965, photo revised 1978; and 
2. Granger, Wash., 1965.

## Boundary [src]

(1) The beginning point is on the Sunnyside map, to the southwest of the town of Sunnyside, at the intersection of South Hill Road and the eastern boundary of section 34, T10N, R22E. From the beginning point, proceed south along the eastern boundary of section 34 for less than 0.1 mile to its intersection with the 750-foot elevation line, T10N, R22E; then 
(2) Proceed along the 750-foot elevation line, first southeasterly then westerly, to its first intersection with the Union Pacific railroad line in section 31, T10N, R22E; then 
(3) Proceed west-northwesterly along the Union Pacific railroad line, crossing onto the Granger map, and continue along the railroad line to its intersection with the northern boundary of section 27, T10N, R21E; then 
(4) Proceed north in a straight line for less than 0.1 mile to the line&#39;s intersection with the 820-foot elevation line in section 22, T10N, R21E; then 
(5) Proceed along the meandering 820-foot elevation line, first northwesterly then easterly, and, returning to the Sunnyside map, continue along the elevation line to its intersection with the northern boundary of section 34, T10N, R22E; then 
(6) Proceed east along the northern boundary line of section 34 and then section 35 to its intersection with the 820-foot elevation line, section 35, T10N, R22E; then 
(7) Proceed southwesterly along the 820-foot elevation line to its intersection with the eastern boundary of section 34, T10N, R22E; and then 
(8) Proceed south along the eastern boundary of section 34 for approximately 0.2 mile, returning to the point of beginning.

**Comment by alisonsnwong** [comment]
Checked! Updated used_maps section
