### ISSUE TITLE
solano_county_green_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#204]
# AVA: Solano County Green Valley (solano_county_green_valley)

name | value
--- | ---
ava_id | solano_county_green_valley
cfr_index | 9.44
revision | [T.D. ATF-122, 47 FR 37922, Dec. 29, 1982]
state | CA
county | Solano
within | North Coast
contains | Wild Horse Valley

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Mt. George Quadrangle, California”, 7.5 minute series 
1968.; and 
2. “Cordelia Quadrangle, California”, 7.5 minute series 
1968..

## Boundary [src]

(1) From the beginning point, the boundary runs in a southerly direction along the Napa/Solano County border to State Road 12; 
(2) Thence east along State Road 12 to where it intersects with Interstate 80; 
(3) Thence southwest on Interstate 80 to where it intersects with the Southern Pacific Railroad track; 
(4) Thence in an easterly direction along the Southern Pacific Railroad track to where it intersects with range line “R3W/R2W”; 
(5) Thence due north on range line “R3W/R2W” to where it intersects with the Solano County/Napa County line; 
(6) Thence due west along the Solano County/Napa County line to the point of beginning.

**Comment by SoominHur** [comment]
Reviewed
- Edit created date in the attribute table
