### ISSUE TITLE
sonoita

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#205]
# AVA: Sonoita (sonoita)

name | value
--- | ---
ava_id | sonoita
cfr_index | 9.97
revision | [T.D. ATF-189, 49 FR 43054, Oct. 26, 1984]
state | AZ
county | Santa Cruz
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Benson Quadrangle, 15 minute series, 1958. 
2. Fort Huachuca Quadrangle, 15 minute series, 1958. 
3. Elgin Quadrangle, 15 minute series, 1958. 
4. Lochiel Quadrangle, 15 minute series, 1958. 
5. Mount Wrightson Quadrangle, 15 minute series, 1958. 
6. Sunnyside Quadrangle, 15 minute series, 1958. 
7. Empire Mountains Quadrangle, 15 minute series, 1958. Bouldary —
1.  General.  The Sonoita viticultural area is located in Arizona. The starting point of the following boundary description is the summit of Mount Wrightson 
9,543 feet. in the Santa Rita Mountains.

## Boundary [src]

(ii) From there in a straight line eastward for approximately 10 miles, to the summit of Huachuca Peak 
(8,410 feet) in the Huachuca Mountains. 
(iii) From there north-northwestward for approximately 21 miles in a straight line to the summit of Granite Peak 
(7,413 feet) in the Whetstone Mountains. 
(iv) From there west-southwestward in a straight line for approximately 26 miles, to the summit of Mount Wrightson 
(the point of beginning).

**Comment by MicheleTobias** [comment]
I'm working on this one.
