### ISSUE TITLE
sonoma_coast

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#206]
# AVA: Sonoma Coast (sonoma_coast)

name | value
--- | ---
ava_id | sonoma_coast
cfr_index | 9.116
revision | [T.D. ATF-253, 52 FR 22304, June 11, 1987]
state | CA
county | Sonoma
within | North Coast
contains | Bennett Valley\|Chalk Hill\|Green Valley of Russian River Valley\|Los Carneros\|Northern Sonoma\|Russian River Valley\|Sonoma Valley

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Sonoma County, California, scale 1:100,000, dated 1970; 
2. Mark West Springs, California, 7.5-minute series, dated 1958, photoinspected 1978; 
3. Healdsburg, California, 7.5-minute series, dated 1955, photorevised 1980; 
4. Jimtown, California, 7.5-minute series, dated 1955, photorevised 1975; 
5. Guerneville, California, 7.5-minute series, dated 1955; and 
6. Cazadero, California, 7.5-minute series, dated 1978.

## Boundary [src]

(1) The beginning point is the point at which the Sonoma County-Mendocino County line meets the shoreline of the Pacific Ocean. 
(2) The boundary follows the shoreline of the Pacific Ocean southerly to the Sonoma County-Marin County line. 
(3) The boundary follows the Sonoma County-Marin County line southeasterly to San Pablo Bay. 
(4) The boundary follows the shoreline of San Pablo Bay easterly to the Sonoma County-Napa County line. 
(5) The boundary follows the Sonoma County-Napa County line northerly to the peak of Arrowhead Mountain. 
(6) From the peak of Arrowhead Mountain, the boundary proceeds in a straight line westerly to the peak of Sonoma Mountain. 
(7) From the peak of Sonoma Mountain, the boundary proceeds in a straight line northwesterly to the peak of Taylor Mountain. 
(8) From the peak of Taylor Mountain, the boundary proceeds in a straight line northwesterly to the point, near the benchmark at 184 ft. elevation in Section 34, Township 8 North, Range 8 West, at which Mark West Road crosses an unnamed stream which flows northwesterly into Mark West Creek. 
(Mark West Springs map) 
(9) From this point, the boundary proceeds northerly in a straight line to the headwaters of Brooks Creek, in Section 4, Township 8 North, Range 8 West. 
(Mark West Springs map) 
(10) The boundary follows Brooks Creek northwesterly to its confluence with the Russian River. 
(Healdsburg map) 
(11) The boundary proceeds southwesterly in a straight line to an unidentified peak at elevation 672 ft. 
(Healdsburg map) 
(12) The boundary proceeds northwesterly in a straight line to the peak identified as Black Peak. 
(Healdsburg map) 
(13) The boundary proceeds westerly in a straight line to an unidentified peak at elevation 857 ft. 
(Healdsburg map) 
(14) The boundary proceeds westerly in a straight line to the peak of Fitch Mountain at elevation 991 ft. 
(Healdsburg map) 
(15) The boundary proceeds northwesterly in a straight line to the intersection, near a benchmark at elevation 154 ft. in the town of Chiquita, of a light-duty road 
(known locally as Chiquita Road) and a southbound primary highway, hard surface road 
(known locally as Healdsburg Avenue). 
(Jimtown map) 
(16) The boundary follows that road 
(known locally as Healdsburg Avenue) southerly through the city of Healdsburg to the point at which it is a light-duty, hard or improved surface road, identified on the map as Redwood Highway, which crosses the Russian River, immediately south of the city of Healdsburg at a bridge 
(known locally as the Healdsburg Avenue Bridge). 
(Healdsburg map) 
(17) The boundary follows the Russian River southerly to a point, near the confluence with Dry Creek, opposite a straight line extension of a light-duty, hard or improved surface road 
(known locally as Foreman Lane) located west of the Russian River. 
(Healdsburg map) 
(18) The boundary proceeds in a straight line to that road and follows it westerly, then south, then westerly, onto the Guerneville map, across a secondary highway, hard surface road 
(known locally as Westside Road), and continues westerly, then northwesterly to the point at which it crosses Felta Creek. 
(Guerneville map) 
(19) The boundary follows Felta Creek approximately 18,000 ft. westerly to its headwaters, at the confluence of three springs, located approximately 5,800 feet northwesterly of Wild Hog Hill. 
(Guerneville map) 
(20) The boundary proceeds in a straight line southwesterly to the southwest corner of Section 9, Township 8 North, Range 10 West. 
(Guerneville map) 
(21) The boundary proceeds in a straight line southwesterly to the point in, Section 24, Township 8 North, Range 11 West, at which Hulbert Creek crosses the 160 ft. contour line. 
(Cazadero map) 
(22) The boundary follows Hulbert Creek southerly to its confluence with the Russian River. 
(23) The boundary follows the Russian River southwesterly to its confluence with Austin Creek. 
(24) From this point, the boundary proceeds in a straight line northwesterly to the peak of Pole Mountain. 
(25) From the peak of Pole Mountain, the boundary proceeds in a straight line northwesterly to the peak of Big Oat Mountain. 
(26) From the peak of Big Oat Mountain, the boundary proceeds in a straight line northwesterly to the peak of Oak Mountain. 
(27) From the peak of Oak Mountain, the boundary proceeds in a straight line northwesterly approximately 14.5 miles to the Sonoma County-Mendocino County line at the northeast corner of Section 25, Township 11 North, Range 14 West. 
(28) The boundary follows the Sonoma County-Mendocino County line west, then southwesterly to the beginning point.

**Comment by amberreyes** [comment]
I'm having some trouble finding the first map (Sonoma County, scale 1:100,000). If you know a website I might be able to find it at please let me know!

**Comment by MicheleTobias** [comment]
Are the boundaries visible on the Napa 100K map on TopoView?  [This document](https://pubs.usgs.gov/fs/2002/0015/report.pdf) suggests that there are county maps, but I haven't been able to find them online.

**Comment by amberreyes** [comment]
I don't believe the Napa map would work because the points are closer to the shoreline

**Comment by MicheleTobias** [comment]
Worst case scenario is we scan/photograph and georeference the print copy in the UCD Map Room (Call Number: MAP G4363.S75 1970 .U8).  I'll keep looking for a digital version.

**Comment by MicheleTobias** [comment]
I have photos of the missing map, but I don't think it's worth georeferencing it. I think it's better to use it as a reference for picking the corresponding topoquads.  It will be a lot of them, but it's probably better to keep a similar scale anyway.

**Comment by amberreyes** [comment]
Okay, sounds good

**Comment by MicheleTobias** [comment]
![img_5858](https://user-images.githubusercontent.com/8761459/28231605-350a2c38-68a1-11e7-9c65-a8b6bfc981e7.JPG)
![img_5861](https://user-images.githubusercontent.com/8761459/28231614-3db788a8-68a1-11e7-98ef-5db4d1bfc6f5.JPG)
![img_5863](https://user-images.githubusercontent.com/8761459/28231621-4434c34e-68a1-11e7-89bd-214aadd98c98.JPG)
![img_5868](https://user-images.githubusercontent.com/8761459/28231627-4a7f8c16-68a1-11e7-8fe2-f0bd1dd09a42.JPG)

**Comment by SoominHur** [comment]
Reviewed.
- Edit created date in the attribute table.
- I also could not find approved map #1 "Sonoma County, California, scale 1:100,000, dated 1970." So I used same map @amberreyes used; "Gualala, CA" 1960, photorevised 1977, scale 1:24000; "McGuire Ridge, CA" provisional ed.1991, scale 1:24000; "Gube Mountain, CA" provisional ed.1991, scale 1:24000; "Stewarts Point, CA" 1978, scale 1:24000; "Annapolis, CA" 1977, scale 1:24000; "Tombs Creek, CA" 1978, scale 1:24000; "Plantation, CA" 1977, scale 1:24000; "Fort Ross, CA" 1978, scale 1:24000; "Arched Rock, CA" 1977, scale 1:24000;
"Duncans Mills, CA" 1979, scale 1:24000; "Camp Meeker, CA" 1954, photorevised 1971, scale 1:24000; "Santa Rosa, CA" 1954, photorevised 1968 and 1973, scale 1:24000; "Bodega Head, CA" 1972, scale 1:24000; "Valley Ford, CA" 1954, photrevised 1971, scale 1:24000; "Two Rock, CA" 1954, photrevised 1971, scale 1:24000; "Glen Ellen, CA" 1954, photorevised 1968, scale 1:24000; "Sonoma, CA" 1951 photorevised 1980, scale 1:24000; "Point Reyes NE, CA" 1954, scale 1:24000; "Petaluma, CA" 1953, photorevised 1981, scale 1:24000; "Petaluma River, CA" 1954, photorevised 1968, photoinspected 1973, scale 1:24000; "Sears Point, CA" 1951, photorevised 1968, scale 1:24000; "Cuttings Wharf, CA" 1949, photorevised 1981, scale 1:24000; "Novato, CA" 1954, photorevised 1980, scale 1:24000; "Petaluma Point, CA" 1959, photorevised 1968, photoinspected 1973, scale 1:24000;
- The boundary stopped following (4) "the shoreline of San Pablo Bay easterly" in the middle but followed levee. So edit the line to keep follow shoreline of San Pablo Bay.
- I edit the boundary to follow Foreman Ln (18) "westerly, then south, then westerly, onto the Guerneville map" because it followed Bramkampo Rd in the middle.
