### ISSUE TITLE
sonoma_mountain

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#207]
# AVA: Sonoma Mountain (sonoma_mountain)

name | value
--- | ---
ava_id | sonoma_mountain
cfr_index | 9.102
revision | [T.D. ATF-196, 50 FR 2979, Jan. 23, 1985, as amended by T.D. ATF-249, 52 FR 5960, Feb. 27, 1987]
state | CA
county | Sonoma
within | North Coast\|Sonoma Valley
contains | Bennett Valley

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Glen Ellen, Calif., dated 1954, photorevised 1980; and 
2. Kenwood, Calif., dated 1954, photorevised 1980.

## Boundary [src]

(1) The beginning point is the northern most point at which the 1600-foot contour line crosses the section line dividing section 22 from section 23, in Township 6 North, Range 7 West. 
(2) The boundary follows this section line north to the 800-foot contour line. 
(3) The boundary follows the 800-foot contour line westerly, easterly, and northerly to Bennett Valley Road. 
(4) The boundary follows Bennett Valley Road easterly to Enterprise Road. 
(5) The boundary follows Enterprise Road southeasterly to an unnamed stream, in Section 7, Township 6 North, Range 7 West, which crosses Enterprise Road near the point at which the road turns from an easterly to a southerly direction. 
(6) The boundary follows this stream easterly to the 400-foot contour line. 
(7) The boundary follows the 400-foot contour line southerly to the township line dividing Township 6 North from Township 5 North. 
(8) The boundary follows a straight line extension of this township line west to the 1200-foot contour line. 
(9) The boundary follows the 1200-foot contour line northwesterly to the range line dividing Range 6 West from Range 7 West. 
(10) The boundary follows this range line south to the 1600-foot contour line. 
(11) The boundary follows this contour line westerly to the beginning point.

**Comment by SoominHur** [comment]
Reviewed. Corrected created date in the attribute table.
And above boundary description (5) "... to an unnamed stream, in Section 7, Township 6 North, Range 7 West ..." seems like a typo. It must mean R.6.W. not R. 7. W. since Section 7, (T. 6. N. & R. 7. W.) is not even included in source maps.
