### ISSUE TITLE
sonoma_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#208]
# AVA: Sonoma Valley (sonoma_valley)

name | value
--- | ---
ava_id | sonoma_valley
cfr_index | 9.29
revision | [T.D. ATF-96, 46 FR 59238, Dec. 4, 1981, as amended by T.D. ATF-201, 50 FR 12533, Mar. 29, 1985; T.D. ATF-249, 52 FR 5956, Feb. 27, 1987] 
state | CA
county | Sonoma
within | North Coast\|Sonoma Coast
contains | Bennett Valley\|Los Carneros\|Moon Mountain District Sonoma County\|Sonoma Mountain

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Cuttings Wharf, Calif.”, 1949 
photorevised 1968 and photoinspected 1973., 7.5 minute quadrangle; 
2. “Petaluma Point, Calif.”, 1959 
photorevised 1968 and photoinspected 1973., 7.5 minute quadrangle; 
3. “Sears Point, Calif.”, 1951 
photorevised 1968., 7.5 minute quadrangle; 
4. “Petaluma River, Calif.”, 1954 
photorevised 1968 and 1973., 7.5 minute quadrangle; 
5. “Glen Ellen, Calif.”, 1954 
photorevised 1968 and photoinspected 1973., 7.5 minute quadrangle; 
6. “Cotati, Calif.”, 1954 
photorevised 1968 and 1973., 7.5 minute quadrangle; 
7. “Santa Rosa, Calif.”, 1954 
photorevised 1968 and 1973., 7.5 minute quadrangle; 
8. “Kenwood, Calif.”, 1954 
photorevised 1968 and photoinspected 1973., 7.5 minute quadrangle; and 
9. Appropriate Sonoma County tax assessor&#39;s maps showing the Sonoma County-Napa County line.

## Boundary [src]

(1) Northerly along Tolay Creek to Highway 37; 
(2) Westerly along Highway 37 to its junction with Highway 121; 
(3) Northwesterly in a straight line to the peak of Wildcat Mountain; 
(4) Northwesterly in a straight line to Sonoma Mountain to the horizontal control station at elevation 2,271 feet; 
(5) Northwesterly in a straight line to the peak of Taylor Mountain; 
(6) Northeasterly in a straight line to the point at which Los Alamos Road joins Highway 12; 
(7) Easterly in a straight line to the peak of Buzzard Peak; 
(8) Easterly in a straight line to the peak of Mount Hood; 
(9) Easterly in a straight line to an unnamed peak located on the Sonoma County-Napa County line and identified as having an elevation of 2,530 feet 
(This unnamed peak is located in the northeast quarter of Section 9, Township 7 North, Range 6 West, Mt. Diablo Base and Meridian); 
(10) Southerly along the Sonoma County-Napa County line to the point at which Sonoma Creek enters San Pablo Bay; and 
(11) Southwesterly along the shore of San Pablo Bay to the beginning point.

**Comment by SoominHur** [comment]
Reviewed.
- Add description about beginning point in the attribute table.
- Edit (1) "Northerly along Tolay Creek" because it followed along private road next to Toaly Creek
- Edit (11) "Southwesterly along the shore of San Pablo Bay" because it followed along levee.
