### ISSUE TITLE
applegate_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#21]
# AVA: Applegate Valley (applegate_valley)

name | value
--- | ---
ava_id | applegate_valley
cfr_index | 9.165
revision | [T.D. ATF-434, 65 FR 78099, Dec. 14, 2000]
state | OR
county | Jackson|Josephine
within | Rogue Valley\|Southern Oregon
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Boundary [src]

(1) Beginning at the confluence of the Applegate River with the Rogue River approximately 5 miles west of Grants Pass, the boundary proceeds due west to the boundary of the Siskiyou National Forest north of Dutcher Creek; 
(2) Then in a straight line in a southerly and westerly direction along the boundary of the Siskiyou National Forest to Highway 199; 
(3) Then in a straight line easterly to the peak of Roundtop Mountain 
(4693 feet); 
(4) Then in a straight line easterly and southerly to the peak of Mungers Butte; 
(5) Then in a straight line southerly and westerly to Holcomb Peak; 
(6) Then in a generally southeasterly direction along the eastern boundary of the Siskiyou National Forest until it joins the northern boundary of the Rogue River National Forest; 
(7) Then easterly along the northern boundary of the Rogue River National forest to a point due south of the peak of Bald Mountain; 
(8) Then due north to the peak of Bald Mountain 
(5635 feet); 
(9) Then in a straight-line northerly and westerly to the lookout tower on Anderson Butte; 
(10) Then in a straight line northerly and westerly to the peak of an unnamed mountain with an elevation of 3181 feet; 
(11) Then in a straight line northerly and westerly to the peak of Timber Mountain; 
(12) Then in a straight line westerly and southerly to the middle peak of Billy Mountain; 
(13) Then, northerly and westerly by straight lines connecting a series of five unnamed peaks with elevations of approximately 3600, 4000, 3800, 3400, and 3800 feet, respectively; 
(14) Then in a straight line northerly and easterly to Grants Pass Peak; 
(15) Then in a straight line westerly to Jerome Prairie; 
(16) Then in a straight line northwesterly to the confluence of the Applegate River and the Rogue River and the point of the beginning.

**Comment by gdmf** [comment]
Please tag applegate_valley as "In Progress". Thanks!
