### ISSUE TITLE
southeastern_new_england

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#210]
# AVA: Southeastern New England (southeastern_new_england)

name | value
--- | ---
ava_id | southeastern_new_england
cfr_index | 9.72
revision | [T.D. ATF-169, 49 FR 11830, Mar. 28, 1984]
state | CT|RI|MA
county | 
within | 
contains | Martha’s Vineyard (MA)

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Boston, Mass.; N.H.; Conn.; R.I.; Maine”, scaled 1:250,000, edition of 1956, revised 1970; 
2. “Hartford, Conn.; N.Y.; N.J.; Mass.”, scaled 1:250,000, edition of 1962, revised 1975; and 
3. “Providence, R.I.; Mass.; Conn.; N.Y.”, scaled 1:250,000, edition of 1947, revised 1969.

## Boundary [src]
(c) Boundaries. The Southeastern New England viticultural area is located in the counties of New Haven, New London, and Middlesex in Connecticut; in the counties of Bristol, Newport, Providence, and Washington, in Rhode Island; and in the counties of Barnstable, Bristol, Dukes, Nantucket, Norfolk, and Plymouth in Massachusetts. The beginning point is found on the “Hartford” U.S.G.S. map in New Haven Harbor;
(1) Then north following the Quinnipiac River to U.S. Interstate 91; 
(2) Then east following U.S. Interstate 91 to Connecticut Highway 80; 
(3) Then east following Connecticut Highway 80 to Connecticut Highway 9 near Deep River; 
(4) Then north following Connecticut Highway 9 to Connecticut Highway 82; 
(5) Then north, east, south and east following Connecticut Highway 82 and 182 to Connecticut Highway 2 in Norwich; 
(6) Then east following Connecticut Highway 2 to Connecticut Highway 165; 
(7) Then east following Connecticut and Rhode Island Highway 165 to Interstate Highway 95 near Millville; 
(8) Then north following Interstate Highway 95 to the Kent County-Washington County boundary; 
(9) Then east following the Kent County-Washington County boundary into Narragansett Bay; 
(10) Then north through Narragansett Bay, the Providence River, and the Blackstone River to the Rhode Island-Massachusetts State boundary; 
(11) Then east and south following the Rhode Island-Massachusetts State boundary to the Norfolk-Bristol 
(Mass.) County boundary; 
(12) Then northeast following the Norfolk-Bristol 
(Mass.) County boundary to the Amtrak right-of-way 
(Penn Central on map) northeast of Mansfield; 
(13) Then north following the Amtrak right-of-way to the Neponset River immediately east of the Norwood Memorial Airport; 
(14) Then northeast following the Neponset River into Dorchester Bay; 
(15) Then east following the Norfolk-Suffolk County boundary, and the Plymouth-Suffolk County boundary into Massachusetts Bay; 
(16) Then returning to the point of beginning by way of Massachusetts Bay, the Atlantic Ocean, Block Island Sound and Long Island Sound; and including all of the offshore islands in Norfolk, Plymouth, Barnstable, Nantucket, Dukes, and Bristol Counties, Massachusetts; all offshore islands in Rhode Island; and all offshore islands in Connecticut east of the Quinnipiac River.

**Comment by dannyo33** [comment]
I'm working on this AVA currently.

**Comment by MicheleTobias** [comment]
Sounds good!  Let me, Sierra, or Alex know if you have questions!

**Comment by dannyo33** [comment]
Created a pull request for the finished file.

**Comment by MicheleTobias** [comment]
@dannyo33 The petitioner is mentioned in the 2nd paragraph of the "Petition for Southeastern New England Viticultural Area" section of the document.  The author's name is in the "Drafting Information" section towards the end of the document.  These are pretty close to where I would expect them to be.  Sometimes you have to read for a while before you find these things.

**Comment by MicheleTobias** [comment]
Note that you should also read the whole document because you need to figure out if the AVA ever had any other names.  If it's there, it's usually in the first few sections, but you never know.  The documents aren't all that standardized.

**Comment by dannyo33** [comment]
![island](https://user-images.githubusercontent.com/46608707/51943114-8e0d1280-23cd-11e9-92d3-37b99b7a5ba3.jpg)
I am currently creating a multipart polygon for this AVA to include the islands. Is this okay or do I need to do single part polygons with identical attributes for each island?

![border](https://user-images.githubusercontent.com/46608707/51943164-aa10b400-23cd-11e9-8ba6-96945d958075.jpg)
In addition, the AVA boundary cuts through a bay, so I wanted to know if I would need to do a polygon for each island within the bay or could I continue along the coastline using the major highways to connect the islands thereby including the entire bay?

**Comment by MicheleTobias** [comment]
Creating a multipolygon should work - the data type is already set to multipolygon, so you should be able to make one item.  For the second question, follow the written description ask closely as you can.  These descriptions were not written in a standard way - almost every one was written by a different person - so we try to follow exactly what they say unless we can't understand or they reference something that isn't on the map.  If it says the boundary is the county line in the ocean, make that line the boundary.
