### ISSUE TITLE
southern_oregon

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#211]
# AVA: Southern Oregon (southern_oregon)

name | value
--- | ---
ava_id | southern_oregon
cfr_index | 9.179
revision | [T.D. TTB-19, 69 FR 70892, Dec. 8, 2004]
state | OR
county | Douglas|Jackson|Josephine
within | 
contains | Applegate Valley\|Elkton Oregon\|Red Hill Douglas County, Oregon\|Rogue Valley\|Umpqua Valley

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Roseburg, Oregon—1958, revised 1970; and 
2. Medford, Oregon; California—1955, revised 1976.

## Boundary [src]

(1) From the beginning point, proceed north along the Douglas-Lane County line approximately 0.5 miles to the 1,000-foot contour line; then 
(2) Proceed northwest along the 1,000-foot contour line to the Douglas-Lane County line; then west along the County line approximately 2.5 miles, returning to the 1,000-foot contour line; then in a generally westerly direction along the 1,000-foot contour line to its first intersection with the R9W-R10W range line; then 
(3) Proceed along the 1,000-foot contour line, crossing the R9W-R10W range line four more times; then proceed south along the R9W-R10W range line approximately 2.75 miles to the center of the Umpqua River; then along a straight line in an easterly direction approximately 6.25 miles to the intersection of range line R8W-R9W with the center of the Umpqua River; then south along range line R8W-R9W approximately 3.5 miles to its intersection with township line T22S-T23S; then 
(4) Proceed southeast approximately 8.5 miles along a straight line to the intersection of township line T23S-T24S with range line R7W-R8W; then south along the R7W-R8W range line approximately 8 miles to its intersection with the 1,000-foot contour line; then in a southeasterly direction in a straight line approximately 3.5 miles toward the intersection of township line T25S-T26S with range line R6W-R7W, but stopping short at the 1,000-foot contour line; then 
(5) Proceed in a southerly direction along the 1,000-foot contour line to the intersection of township line T27S-T28S with range line R7W-R8W; then in a southwesterly direction in a straight line approximately 3.5 miles toward the intersection of township line T28S-T29S with range line R8W-R9W, but stopping short and returning to the 1,000-foot contour line near the center of T28S, R8W; then generally south along the 1,000-foot contour line to its intersection with township line T29S-T30S; then 
(6) Proceed east along township line T29S-T30S approximately 0.33 mile, rejoining the 1,000-foot contour line; then in a northerly and eventually a southerly direction along the 1,000-foot contour line, passing onto the Medford map, and past the town of Riddle to range line R6W-R7W; then south along the R6W-R7W range line approximately 15 miles to the Josephine-Douglas County line; then in a general northeasterly direction along the County line to its intersection with Interstate 5 approximately 1.3 miles south of Cow Creek ; then 
(7) Proceed southerly and southwesterly along southbound Interstate 5 to its junction with Wolf Creek and then north about 500 feet to the Southern Pacific Railway line; then westerly and southerly out of the town of Wolf Creek along the Southern Pacific Railway line to the rail line&#39;s intersection with Hugo Road at the town of Hugo; then southwesterly along Hugo Road to the point where Hugo Road crosses Jumpoff Joe Creek; then westerly and downstream along that creek to the intersection of Jumpoff Joe Creek and the Rogue River; then 
(8) Proceed northwesterly and downstream along the Rogue River to the first point where the Wild and Scenic Rogue River designated area touches the easterly boundary of the Siskiyou National Forest, just south of Galice; then 
(9) Proceed in a generally southwesterly direction 
(with many diversions) along the easterly border of the Siskiyou National Forest to the 42 degree 0 minute north latitude line; then easterly along the latitude line to the point where the Siskiyou National Forest boundary again crosses into Oregon, approximately 1 mile east of U.S. Highway 199; then 
(10) Proceed in a generally northeasterly direction and then in a southeasterly direction 
(with many diversions) along the northern boundary of the Siskiyou National Forest to the point where the Siskiyou National Forest touches the Rogue River National Forest at Big Sugarloaf Peak; then 
(11) Proceed in a generally easterly direction 
(with many diversions) along the northern border of the Rogue River National Forest to the point where the Rogue River National Forest intersects with Slide Creek approximately 6 miles southeast of Ashland; then 
(12) Proceed southeasterly and northeasterly along Slide Creek to the point where the creek intersects State Route 273; then northwesterly along State Route 273 to the point where it intersects State Highway 66; then proceed in an easterly direction approximately 5 miles along State Route 66 to the east line of T39S, R2E; then 
(13) Proceed north along the east line of T39S, R2E to the northeast corner of T39S, R2E; then westerly approximately 5 miles along the north line of T39S, R2E, to the 2,600 foot contour line; then in a northerly direction following the 2,600 foot counter line across Walker Creek and then in a southwesterly direction to the point where the 2,600 foot contour line touches the east line of T38S, R1E; then 
(14) Proceed northerly along the east line of T38S, R1E, to the northeast corner of T38S, R1E; then 
(15) Proceed westerly along the north line of T38S, R1E, to the northwest corner of T38S, R1E; then 
(16) Proceed northerly along the west line of T37S, R1E, to the northwest corner of T37S, R1E; then 
(17) Proceed easterly along the north lines of T37S, R1E, and T37S, R2E, to the southeast corner of T36S, R2E; then 
(18) Proceed northerly along the east line of T36S, R2E, to the northeast corner of T36S, R2E; then 
(19) Proceed westerly along the north line of T36S, R2E, to the northwest comer of T36S, R2E; then 
(20) Proceed northerly along the east line of T35S, R1E, to the northeast comer of T35S, R1E; then 
(21) Proceed westerly along the north line of T35S, R1E, to the northwest corner of T35S, R1E; then 
(22) Proceed northerly along the east line of T34S, R1W, to the northeast corner of T34S, R1W; then 
(23) Proceed westerly along the common boundary line of T34S-T33S to the northwest corner of T34S, R5W; then 
(24) Proceed northerly along the west line of T33S, R5W, to the Josephine-Douglas County line; thence in a generally east, northeasterly direction along the county line to the intersection of R3W-R4W range line; thence north along the R3W-R4W range line approximately 11.8 miles to the 1,000-foot contour line just south of State Route 227 southeast of the town of Days Creek; then 
(25) Proceed in an easterly, westerly, and eventually northerly along the 1,000-foot contour line, crossing to the Roseburg map from the Medford map, to a point approximately 3.5 miles east of Dillard, where the contour line crosses Interstate 5 on the Roseburg map; thence northeast along Interstate 5 approximately 0.25 mile, returning to the 1,000-foot contour line; thence in a generally northeasterly, southeasterly, northwesterly, and eventually northeasterly along the 1,000-foot contour line past the town of Idleyld Park to the R2W-R3W range line; then 
(26) Proceed north along range line R2W-R3W approximately 1.75 miles to the T25S-T26S township line; thence west along township line T25S-T26S approximately .25 mile, returning to the 1,000-foot contour line; thence in a generally westerly and then a northerly direction along the 1,000-foot contour line toward the valley of Calapooya Creek to the R3W-R4W range line; thence north along range line R3W-R4W approximately 2.25 miles, back to the 1,000-foot contour line; then 
(27) Proceed in a westerly and then a northerly direction along the 1,000-foot contour line to the T23S-T24S township line, then east along the T23S-T24S township line approximately 2.75 miles to the 1,000-foot contour line; then in a northerly direction along the 1,000-foot contour line to its intersection with the Douglas-Lane County line; thence north along the county line approximately 0.75 mile to the beginning point.

**Comment by amgard** [comment]
Hi Michele, can  I work on this AVA? I noticed it was tagged UCSB for a bit then removed so wanted to make sure before I started. Thanks!

**Comment by MicheleTobias** [comment]
Yes, you can work on this one!  UCSB had planned on finishing Oregon and Washington but then some needs shifted and they decided to let others work on them instead.  Enjoy!

**Comment by alisonsnwong** [comment]
Checked! Updated boundary to follow official descriptions.
