### ISSUE TITLE
spring_mountain_district

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#212]
# AVA: Spring Mountain District (spring_mountain_district)

name | value
--- | ---
ava_id | spring_mountain_district
cfr_index | 9.143
revision | [T.D. ATF-341, 58 FR 28350, May 13, 1993]
state | CA
county | Napa
within | Napa Valley\|North Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Kenwood, Calif.,” 1954 
photorevised 1980.. 
2. “Rutherford, Calif.,” 1951 
photorevised 1968.. 
3. “St. Helena, Calif.,” 1960 
photorevised 1980.. 
4. “Calistoga, Calif.,” 1958 
photorevised 1980..

## Boundary [src]

(1) Beginning on the Calistoga quadrangle map at the Napa-Sonoma county line at the boundary line between sections 18 and 19 in T8N/R6W. 
(2) Then east along the boundary line between sections 18 and 19 for approximately   of a mile to its intersection with Ritchie Creek at the boundary line between sections 17 and 20. 
(3) Then northeast along Ritchie Creek approximately 2 miles, to the 400 foot contour line in the northeast corner in section 16 of T8N/R6W. 
(4) Then along the 400 foot contour line in a northeast then generally southeast direction, through the St. Helena and Rutherford quadrangle maps, approximately 9 miles, past the town of St. Helena to the point where it intersects Sulphur Creek in Sulphur Canyon, in the northwest corner of section 2 in T7N/R6W. 
(5) Then west along Sulfur Creek 
(onto the Kenwood quadrangle map) and south to the point where it first divides into two intermittent streams in section 3 in T7N/R6W. 
(6) Then south along the intermittent stream approximately 1.5 miles to the point where it intersects the 2,360 foot contour line in section 10 in T7N/R6W. 
(7) Then southwest in a straight line, approximately .10 mile, to the unnamed peak 
(elevation 2600 feet) at the boundary line between Napa and Sonoma Counties. 
(8) Then in a generally northwest direction along the Napa-Sonoma county line, through sections 10, 9, 4, 5, 32, 33, 32, 29, 20, and 19, to the beginning point on the Calistoga quadrangle map at the boundary between sections 18 and 19 in T8N/R6W.

**Comment by SoominHur** [comment]
Reviewed.
- edited created date
- moved the beginning point a little toward south, so the node can be "at the boundary line between sections 18 and 19 in T8N/R6W."
