### ISSUE TITLE
squaw_valley_miramonte

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#213]
# AVA: Squaw Valley-Miramonte (squaw_valley_miramonte)

name | value
--- | ---
ava_id | squaw_valley_miramonte
cfr_index | 9.251
revision | [T.D. TTB-129, 80 FR 47409, Aug. 7, 2015]
state | CA
county | Fresno
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Orange Cove North, Calif., 1966; 
2. Pine Flat Dam, Calif., 1965; photoinspected 1978; 
3. Luckett Mtn., Calif., provisional edition 1987; 
4. Verplank Ridge, Calif., provisional edition 1987; 
5. Miramonte, Calif., 1966; and 
6. Tucker Mtn., Calif., 1966.

## Boundary [src]

(1) The beginning point is located on the Orange Cove North map, at the southwest corner of section 21, T14S/R25E. From the beginning point, proceed north-northwesterly in a straight line to the marked 3,355-foot elevation point on Bear Mountain, section 5, T14S/R25E; then 
(2) Proceed northeast in a straight line, crossing onto the Pine Flat Dam map and over the marked 3,354-foot elevation point on Bear Mountain, section 32, T13S/R25E, and then continuing northeasterly in a straight line and crossing onto the Luckett Mountain map, proceed to the marked 3,489-foot summit of Dalton Mountain, section 22, T13S/R25E; then 
(3) Proceed easterly in a straight line to the Sequoia National Forest boundary line at the northwest corner of section 28, T13S/R26E; then 
(4) Proceed east along the Sequoia National Forest boundary line, crossing onto the Verplank Ridge map, and continue south, then east, then south along the national forest boundary line, crossing onto the Miramonte map, and then continue south, then east along the national forest boundary line to the northeast corner of section 5, T14S/R27E; then 
(5) Proceed south along the eastern boundary lines of sections 5, 8, and 17, T14S/R27E, to the southeast corner of section 17; then 
(6) Proceed east along the northern boundary line of section 21, T14S/R27E, to the northeast corner of that section; then 
(7) Proceed south along the eastern boundary lines of sections 21, 28, and 33, T14S/R27E, to the Fresno-Tulare County boundary line at the southeast corner of section 33; then 
(8) Proceed west along the Fresno-Tulare County boundary line, crossing onto the Tucker Mountain map, to the southwest corner of section 34, T14S/R26E; then 
(9) Proceed north along the western boundary lines of sections 34, 27, 22, and 15, T14S/R26E, to the northwest corner of section 15; then 
(10) Proceed west along the southern boundary lines of sections 9, 8, and 7, T14S/R26E, and sections 12 and 11, T14S/R25E, to the southwest corner of section 11; then 
(11) Proceed south along the eastern boundary lines of sections 15 and 22, T14S/R25E, to the southeast corner of section 22; then 
(12) Proceed west along the southern boundary line of section 22, T14S/R25E, and, crossing onto the Orange Cove North map, continue west along the southern boundary line of section 21, T14S/R25E, returning to the beginning point.

**Comment by ariellerose** [comment]
I am working on this one

**Comment by SoominHur** [comment]
Start reviewing

**Comment by SoominHur** [comment]
Finished reviewing. Corrected followings:
(1) node at section 21 @ T14S/R26E to section 21 @ T14S/R25E
(5) line along western boundary to along eastern boundary of section 5, 8, 17
Created date in attribute table form "2015/09/07" to "2015/09/08"
