### ISSUE TITLE
stags_leap_district

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#214]
# AVA: Stags Leap District (stags_leap_district)

name | value
--- | ---
ava_id | stags_leap_district
cfr_index | 9.117
revision | [T.D. ATF-281, 54 FR 4018, Jan. 27, 1989]
state | CA
county | Napa
within | Napa Valley\|North Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

The appropriate map for determining the boundaries of the Stags Leap District viticultural area is one U.S.G.S. topographic map in the 7.5 minute series, scaled 1:24000, titled “Yountville, Calif.,” 1951 (photorevised 1968).

## Boundary [src]

(1) Commencing at the intersection of the intermittent stream 
(drainage creek) with the Silverado Trail at the 60 foot contour line in T6N/R4W, approximately 7 miles north of the city of Napa. 
(2) Then southwest in a straight line, approximately 900 feet, to the main channel of the Napa River. 
(3) Then following the main branch of the Napa River 
(not the southern branch by the levee) in a northwesterly then northerly direction, until it intersects the medium-duty road 
(Grant Bdy) in T7N/R4W, known locally as the Yountville Cross Road. 
(4) Then northeast along the Yountville Cross Road until it intersects the medium-duty road, the Silverado Trail. 
(5) Then north along the Silverado Trail approximately 590 feet to a gully entering the Silverado Trail from the east. 
(6) Then northeast along the center line of that gully, approximately 800 feet, until it intersects the 400 foor contour line in Section 30 of T7N/R4W. 
(7) Then in a generally southeast direction, following the 400 foot contour line through Sections 29, 32, 33, 4, and 3, until it intersects the intermittent stream in the southwest corner of Section 3 in T6N/R4W. 
(8) Then in a generally southwest direction along that intermittent stream to the beginning point, at the intersection with the Silverado Trail.

**Comment by SoominHur** [comment]
Reviewed
- corrected created date @ attribute table
- refined lines
