### ISSUE TITLE
sta__rita_hills

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#215]
# AVA: Sta. Rita Hills (sta__rita_hills)

name | value
--- | ---
ava_id | sta__rita_hills
cfr_index | 9.162
revision | [T.D. ATF-454, 66 FR 29479, May 31, 2001, as amended by T.D. TTB-37, 70 FR 72713, Dec. 7, 2005; T.D. TTB 141, 81 FR 56504, Aug. 22, 2016]
state | CA
county | Santa Barbara
within | Central Coast\|Santa Ynez Valley
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Lompoc, Calif.,” edition of 1959 
photorevised in 1982..  
2. “Lompoc Hills, Calif.,” edition of 1959 
photoinspected 1971..  
3. “Los Alamos, Calif.,” edition of 1959.  
4. “Santa Rosa Hills, Calif.,” edition of 1959 
photoinspected 1978..  
5. “Solvang, Calif.,” edition of 1959 
photorevised 1982..  
6. “Zaca Creek, Calif.,” edition of 1959.

## Boundary [src]

(1) The beginning point is found on the Solvang, California U.S.G.S. Quadrangle map at an unnamed hilltop, elevation 1600 feet, in section 27, T.6N, R. 32W, on the Solvang, Calif., Quadrangle U.S.G.S. map.  
(2) Then proceed north and slightly west 2.3 miles to an unnamed hilltop elevation 1174 feet, Section 15, T.6N., R. 32W.  
(3) Proceed west-northwest in a straight line 0.5 mile to the intersection of Santa Rosa Road and an unnamed, unimproved road that runs just north of a marked gaging station. 
(4) Proceed west along the unnamed, unimproved road approximately 0.4 mile to a “T” intersection with an unnamed, unimproved road and the 320-foot elevation contour, Santa Rosa Land Grant, T. 6N, R. 32W. 
(5) Proceed northwest along the 320-foot elevation contour, crossing onto the Santa Rosa Hills, Calif., Quadrangle U.S.G.S. map, then continue northwest, north, and northeast along the meandering 320-foot elevation contour for approximately 1.2 miles, crossing onto the Solvang, Calif., Quadrangle U.S.G.S. map, and continue east then north along the 320-foot elevation contour approximately 0.5 miles, crossing onto the Zaca Creek, Calif., Quadrangle U.S.G.S. map, to the intersection of the 320-foot elevation contour with an unnamed, unimproved north-south road that follows the length of the Cañada de los Palos Blancos, San Carlos de Jonata Land Grant, T. 6N, R. 32W. 
(6) Proceed north-northwest along the unnamed, unimproved road 1.2 miles, crossing onto the Los Alamos, Calif., Quadrangle U.S.G.S. map, and continue along the road 1.3 miles to the marked 635-foot elevation point at the intersection of the road and a 4-wheel drive trail, San Carlos de Jonata Land Grant, T. 7N, R. 32W. 
(7) Proceed northwest in a straight line approximately 1.3 miles to an unnamed hilltop, elevation 1443 feet. Section 20, T. 7N, R. 32W. 
(8) Proceed west 1.4 miles to an unnamed hilltop elevation 1479 feet. Section 24, T.7N., R. 33W.  
(9) Proceed north 1.2 miles to an unnamed hilltop elevation 1705 feet. Section 13, T.7N., R. 33W.  
(10) Proceed northwest approximately 2 miles to an unnamed hilltop elevation 1543. Section 10, T.7N., R. 33W.  
(11) Proceed west and slightly south 1.6 miles to an unnamed hilltop elevation 935 feet within the northern section of the Santa Rosa Land Grant. T.7N., R. 33W.  
(12) Proceed south by southwest 1.5 miles to an unnamed hilltop elevation 605 feet in the northern section of the Santa Rosa Land Grant. T.7N., R. 33W.  
(13) Proceed west by southwest approximately 2 miles to the point where California Highway 246 intersects with the 200-foot elevation contour line comprising the western border of the Santa Rita Hills, within the Santa Rosa Land Grant. T.7N., R. 34W, on the Lompoc, Calif., Quadrangle U.S.G.S. map.  
(14) Proceed following the 200 foot elevation contour line south along the western border of the Santa Rita Hills to the extreme southern tip of the 200 foot elevation contour that is .6 miles due west of an unnamed hilltop 361 feet in elevation in the Canada de Salispuedes Land Grant. T.6N., R. 34W.  
(15) Proceed southeast 2.35 miles to an unnamed hilltop elevation 1070 feet. Section 18, T.6N., R. 33W, on the Lompoc Hills, Calif., Quadrangle U.S.G.S. map.  
(16) Proceed east and slightly south 1.95 miles to an unnamed hilltop elevation 921 feet. Section 16, T.6N., R. 33W, on the Santa Rosa Hills, Calif., Quadrangle U.S.G.S. map.  
(17) Proceed east by southeast 1.35 miles to an unnamed hilltop elevation 1307 feet at intersection between Sections 22 and 23. T.6N., R. 33W.  
(18) Proceed east 2.35 miles to an unnamed hilltop elevation 1507 feet in the southern area of the Santa Rosa Land Grant. T.6N., 32W.  
(19) Proceed east by southeast 2.1 miles to an unnamed hilltop elevation 1279 feet in the southern area of the Santa Rosa Land Grant. T.6N., 32W.  
(20) Then proceed east by southeast 1.45 miles to the point of the beginning. 
(d) From July 30, 2001, until January 5, 2006, this viticultural area was named “Santa Rita Hills”. Effective January 6, 2006, the name of this viticultural area is “Sta. Rita Hills”. Existing certificates of label approval showing “Santa Rita Hills” as the appellation of origin are revoked by operation of this regulation on January 6, 2007.

**Comment by SoominHur** [comment]
Reviewed.
- Add scale information of the used maps
