### ISSUE TITLE
st__helena

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#216]
# AVA: St. Helena (st__helena)

name | value
--- | ---
ava_id | st__helena
cfr_index | 9.149
revision | [T.D. ATF-366, 60 FR 47061, Sept. 11, 1995]
state | CA
county | Napa
within | Napa Valley\|North Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. St. Helena Quadrangle, California, edition of 1960, revised 1993; 
2. Calistoga Quadrangle, California, edition of 1958, photorevised 1980; 
3. Rutherford Quadrangle, California, edition of 1951, photorevised 1968, photoinspected 1973.

## Boundary [src]

(1) Beginning on the Rutherford Quadrangle map at the point of intersection between State Highway 29 and a county road shown on the map as Zinfandel Avenue, known locally as Zinfandel Lane, the boundary proceeds in a southwest direction along Zinfandel Avenue to its intersection with the north fork of Bale Slough 
(blueline stream) near the 201 foot elevation marker; 
(2) Thence in a northwesterly direction approximately 2,750 feet along the north fork of Bale Slough to a point of intersection with a southwesterly straight line projection of a light duty road locally known as Inglewood Avenue; 
(3) Thence in a straight line in a southwesterly direction along this projected extension of Inglewood Avenue approximately 2,300 feet to its intersection with the 500 foot contour line in Section 7, Township 7 North 
(T7N), Range 5 West 
(R5W); 
(4) Thence along the 500 foot contour line in a generally northwesterly direction through Sections 7, 1 and 2, to its intersection of the western border of Section 2, T7N, R6W;  
(5) Thence northerly along the western border of Section 2 approximately 500 feet to its intersection with Sulphur Creek in Sulphur Canyon in the northwest corner of Section 2, T7N, R6W; 
(6) Thence along Sulphur Creek in an easterly direction approximately 350 feet to its intersection with the 400 foot contour line; 
(7) Thence along the 400 foot contour line in a generally easterly, then northwesterly, direction past the city of St. Helena 
(on the St. Helena Quadrangle map) to a point of intersection with a southwesterly straight line projection of the county road shown as Bale Lane in the Carne Humana Rancho on the Calistoga Quadrangle map; 
(8) Thence along the projected straight line extension of Bale Lane in a northeasterly direction approximately 700 feet to the intersection of State Highway 29 and Bale Lane and continuing northeasterly along Bale Lane to its intersection with the Silverado Trail; 
(9) Thence in a northwesterly direction along the Silverado Trail approximately 1,500 feet to an unmarked driveway on the north side of the Silverado Trail near the 275 foot elevation marker; 
(10) Thence approximately 300 feet northeasterly along the driveway to and beyond its point of intersection with another driveway and continuing in a straight line projection to the 400 foot contour line; 
(11) Thence in a northerly and then generally southeasterly direction along the 400 foot contour line through Sections 10 
(projected), 11, 12, 13, 24 and 25 in T8N, R6W, Section 30 in T8N, R5W, Sections 25 and 24 in T8N, R6W, Sections 19 and 30 in T8N, R5W to a point of intersection with the city limits of St. Helena on the eastern boundary of Section 30 in T8N, R5W, on the St. Helena Quadrangle map; 
(12) Thence north, east and south along the city limits of St. Helena to the third point of intersection with the county road known as Howell Mountain Road in Section 29, T8N, R5W; 
(13) Thence in a northeasterly direction approximately 900 feet along Howell Mountain Road to its intersection with Conn Valley Road; 
(14) Thence northeasterly and then southeasterly along Conn Valley Road to its intersection with the eastern boundary of Section 28, T8N, R5W; 
(15) Thence south approximately 5,200 feet along the eastern boundary of Sections 28 and 33 to a point of intersection with the 380 foot contour line near the southeast corner of Section 33, T8N, R5W, on the Rutherford Quadrangle map; 
(16) Thence in a northwesterly direction along the 380 foot contour line in Section 33 to a point of intersection with a northeasterly straight line projection of Zinfandel Avenue; 
(17) Thence in a southwesterly direction approximately 950 feet along this straight line projection of Zinfandel Avenue to its intersection with the Silverado Trail; 
(18) Thence continuing along Zinfandel Avenue in a southwesterly direction to its intersection with State Highway 29, the point of beginning.

**Comment by SoominHur** [comment]
- (2) Removed extra nodes went above "a southwesterly straight line projection of a light duty road locally known as Inglewood Avenue."
- (7) Continued following 400' contour line until "a point of intersection with a southwesterly straight line projection of the county road shown as Bale Lane ... on the Calistoga Quadrangle map" because the line moved onto Hwy128 en route.
- Corrected create date in the attribute table
