### ISSUE TITLE
suisun_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#217]
# AVA: Suisun Valley (suisun_valley)

name | value
--- | ---
ava_id | suisun_valley
cfr_index | 9.45
revision | [T.D. ATF-117, 47 FR 52997, Nov. 24, 1982]
state | CA
county | Solano
within | North Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Mt. George Quadrangle, California”, 7.5 minute series 
1968.; 
2. “Fairfield North Quadrangle, California”, 7.5 minute series 
1973.; 
3. “Fairfield South Quadrangle, California”, 7.5 minute series 
1968.; and 
4. “Cordelia Quadrangle, California”, 7.5 minute series 
1968..

## Boundary [src]
The Suisun Valley viticultural area is located in Solano County, California. The beginning point is the intersection of the Southern Pacific Railroad track with range line “R3W/R2W” in the town of Cordelia, located on U.S.G.S. map “Cordelia Quadrangle.”
(1) From the beginning point, the boundary runs northeast in a straight line to the intersection of Ledgewood Creek with township line “T5N/T4N”; 
(2) Thence in a straight line in a northeast direction to Bench Mark 
(BM) 19 located in the town of Fairfield;  
(3) Thence in a straight line due north to Soda Springs Creek; 
(4) Thence in a straight line in a northwest direction to the extreme southeast corner of Napa County located just south of Section 34, Township 6 North, Range 2 West; 
(5) Thence due west along the Napa/Solano County border to where it intersects with range line “R3W/R2W”; 
(6) Thence due south along range line “R3W/R2W” to the point of beginning.

**Comment by SoominHur** [comment]
Reviewed.
- Add description about beginning point in the attribute table.
- Edit used maps information in the attribute table because it only listed maps' edited years (without map years).
