### ISSUE TITLE
swan_creek

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#218]
# AVA: Swan Creek (swan_creek)

name | value
--- | ---
ava_id | swan_creek
cfr_index | 9.211
revision | [T.D. TTB-69, 73 FR 22276, Apr. 25, 2008]
state | NC
county | Iredell|Wilkes|Yadkin
within | Yadkin Valley
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Winston-Salem, North Carolina, 1984, photoinspected 1982; 
2. Boone, North Carolina-Tennessee, 1985; and 
3. Salisbury, North Carolina, 1985, photoinspected 1983.

## Boundary [src]

(1) The beginning point is on the Winston-Salem, North Carolina map at the intersection of the Yadkin River and U.S. Highway 21, along the Surry-Yadkin county line, between Elkin and Jonesville; 
(2) From the beginning point, proceed 24.6 miles generally south on U.S. Highway 21, crossing onto the Salisbury, North Carolina map, to the intersection of U.S. Highway 21 with Rocky Creek at Turnersburg; then 
(3) Proceed 12.3 miles generally north and west along Rocky Creek, returning to the Winston-Salem map, to the intersection of Rocky Creek with State Highway 115 at New Hope in the southwest corner of the map; then 
(4) Proceed 15.5 miles generally northwest along State Highway 115, crossing onto the Boone, North Carolina-Tennessee map, to the intersection of State Highway 115 and the Yadkin River, at North Wilkesboro; and 
(5) Proceed 16.7 miles generally east-northeast along the Yadkin River, crossing onto the Winston-Salem map, and return to the beginning point.

**Comment by ouwxmaniac** [comment]
In progress

**Comment by davidkli** [comment]
This AVA has been checked and the boundary is good. No edits needed to be made
