### ISSUE TITLE
temecula_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#219]
# AVA: Temecula Valley (temecula_valley)

name | value
--- | ---
ava_id | temecula_valley
cfr_index | 9.50
revision | [T.D. ATF-188, 49 FR 42566, Oct. 23, 1984; 49 FR 43455, Oct. 29, 1984, as amended by T.D. ATF-221, 51 FR 750, Jan. 8, 1986; T.D. ATF-249, 52 FR 5958, Feb. 27, 1987; T.D. TTB-10, 69 FR 20825, Apr. 19, 2004]
state | CA
county | Riverside
within | South Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Wildomar, California, dated 1953, photorevised 1973; 
2. Fallbrook, California, dated 1968; 
3. Murrieta, California, dated 1953, photorevised 1979; 
4. Temecula, California, dated 1968, photorevised 1975; 
5. Pechanga, California, dated 1968; 
6. Sage, California, dated 1954; 
7. Bachelor Mountain, California, dated 1953, photorevised 1973.

## Boundary [src]

(1) The beginning point is the northernmost point of the Santa Rosa Land Grant where the Santa Rosa Land Grant boundary intersects the easternmost point of the Cleveland National Forest boundary. 
(2) The boundary follows the Cleveland National Forest boundary southwesterly to the point where it converges with the Riverside County-San Diego County line. 
(3) The boundary follows the Riverside County-San Diego County line southwesterly, then southeasterly to the point where the Riverside County-San Diego County line diverges southward and the Santa Rosa Land Grant boundary continues southeasterly. 
(4) The boundary follows the Santa Rosa Land Grant boundary southeasterly, then northeasterly, to its intersection with the Temecula Land Grant boundary. 
(5) The boundary follows the Temecula Land Grant boundary southeasterly, then northeasterly, to its intersection with the Little Temecula Land Grant boundary. 
(6) The boundary follows the Little Temecula Land Grant boundary southeasterly to its intersection with the boundary of that portion of the Pechanga Indian Reservation which, until 1907, was Lot “E” of the Little Temecula Land Grant. 
(7) The boundary follows the Pechanga Indian Reservation boundary southeasterly, then northeasterly 
(including that portion of the Penchanga Indian Reservation in the approved viticultural area) to the point at which it rejoins the Little Temecula Land Grant boundary. 
(8) The boundary follows the Little Temecula Land Grant boundary northeasterly to its intersection with the Pauba Land Grant boundary. 
(9) The boundary follows the Pauba Land Grant boundary southeasterly, then northeasterly, to the north-south section line dividing Section 23 from Section 24 in Township 8 South, Range 2 West. 
(10) The boundary follows this section line south to the 1500-foot contour line. 
(11) The boundary follows the 1500-foot contour line easterly to the range line dividing Range 2 West from Range 1 West. 
(12) The boundary follows this range line north, across California State Highway 71/79, to the 1400-foot contour line of Oak Mountain. 
(13) The boundary follows the 1400-foot contour line around Oak Mountain to its intersection with the 117°00  West longitude meridian. 
(14) The boundary follows the 117°00  West longitude meridian north to its intersection with the Pauba Land Grant boundary. 
(15) The boundary follows the Pauba Land Grant boundary northwesterly, then west, then south, then west, to Warren Road 
(which coincides with the range line dividing Range 1 West from Range 2 West). 
(16) The boundary follows Warren Road north to an unnamed east-west, light-duty, hard or improved surface road 
(which coincides with the section line dividing Section 12 from Section 13 in Township 7 South, Range 2 West). 
(17) The boundary follows this road west to the north-south section line dividing Section 13 from Section 14 in Township 7 South, Range 2 West. 
(18) The boundary follows this section line south to its intersection with Buck Road 
(which coincides with the east-west section line on the southern edge of Section 14 in Township 7 South, Range 2 West). 
(19) The boundary follows Buck Road west to the point where it diverges northwesterly from the section line on the southern edge of Section 14 in Township 7 South, Range 2 West. 
(20) The boundary follows this section line west, along the southern edges of Sections 14, 15, 16, 17, and 18 in Township 7 South, Range 2 West, to Tucalota Creek. 
(21) The boundary follows Tucalota Creek southerly to Santa Gertrudis Creek. 
(22) The boundary follows Santa Gertrudis Creek southwesterly to Murrieta Creek. 
(23) The boundary proceeds northwesterly along the westernmost branches of Murrieta Creek to its intersection with Hayes Avenue, northwest of Murrieta, California. 
(24) The boundary follows Hayes Avenue northwesterly, approximately 4,000 feet, to its terminus at an unnamed, unimproved, fair or dry weather road. 
(25) The boundary follows this road southwesterly to Murrieta Creek. 
(26) The boundary proceeds northwesterly along the westernmost branches of Murrieta Creek to its intersection with Orange Street in Wildomar, California. 
(27) From the intersection of Murrieta Creek and Orange Street in Wildomar, California, the boundary proceeds in a straight line to the beginning point. 
(d) From November 23, 1984, until June 17, 2004, the name of this viticultural area was “Temecula”. Effective June 18, 2004, this viticulture area is named “Temecula Valley”. Existing certificates of label approval showing “Temecula” as the appellation of origin will be revoked by operation of this regulation on June 19, 2006.

**Comment by SoominHur** [comment]
Reviewed.
- Add scale information of the used maps in the attribute table.
- There are four different edition of "Sage, CA" dated 1954. Among those four, usgs topo view website lists two different map as (1973 ed.). But actually only one of them stamped in 1973 but the other stamped in 1995. I used one that stamped in 1973 to review because it is the most recent date before the creation date of map description, which is 1984-11-23.
- Cannot find "Bachelor Mountain, CA" dated 1953, photorevised 1973. Instead, used  "Bachelor Mountain, CA" 2015, scale 1:24000 to review.
