### ISSUE TITLE
arkansas_mountain

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#22]
# AVA: Arkansas Mountain (arkansas_mountain)

name | value
--- | ---
ava_id | arkansas_mountain
cfr_index | 9.112
revision | [T.D. ATF-235, 51 FR 34205, Sept. 26, 1986]
state | AR
county | Conway|Crawford|Franklin|Johnson|Logan|Madison|Newton|Pope|Sebastian|Van Buren|Yell
within | Ozark Mountain
contains | Altus

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Russellville, Arkansas, 1:250,000 series compiled in 1954. 
2. Fort Smith, Arkansas-Oklahoma, 1:250,000 series, 1978.

## Boundary [src]
General.  The Arkansas Mountain viticultural area is located in northwestern Arkansas. Starting at the point where Frog Bayou converges with the Arkansas River, near Yoestown, Arkansas 
(or the Fort Smith map), the boundary proceeds: Boundary Description.  
(i) Southwestward along the Arkansas River to Vache Grasse Creek. 
(ii) Then southeastward and southwestward following Vache Grasse Creek to the place where it is crossed by Arkansas Highway 10, near Greenwood, Arkansas. 
(iii) From there westward along Highway 10 to U.S. Highway 71. 
(Note: Highway 10 is the primary highway leading to Greenwood to Hackett, Arkansas.) 
(iv) Then southward and eastward along Highway 71 until it crosses Rock Creek. 
(v) Then northeastward along Rock Creek to Petit Jean Creek. 
(vi) Then generally northeastward and eastward along Petit Jean Creek until it becomes the Petit Jean River 
(on the Russellville map). 
(vii) Then generally eastward along the Petit Jean River, flowing through Blue Mountain Lake, until the Petit Jean River joins the Arkansas River. 
(viii) Then generally eastward along the Arkansas River to Cadron Creek. 
(ix) Then generally northward and northeastward along Cadron Creek to the place where it is crossed by U.S. Highway 65. 
(x) From there northward along Highway 65 to its intersection with Arkansas Highway 16 near Clinton, Arkansas. 
(xi) From there following Highway 16 generally westward to its intersection with Arkansas Highway 23 in Brashears, Arkansas. 
(xii) From there southward along Highway 23 to the Madison County-Franklin County line. 
(xiii) Then westward and southward along that county line to the Madison County-Crawford County line. 
(xiv) Then westward along that county line to the Washington County-Crawford County line. 
(xv) Then westward along that county line to Jones Fork 
(on the Fort Smith map). 
(xvi) Then southward along Jones Fork until it joins Frog Bayou near Winfrey, Arkansas. 
(xvii) Then generally southward along Frog Bayou, flowing through Lake Shepherd Springs and Lake Fort Smith, to the starting point.

**Comment by dannyo33** [comment]
in progress

**Comment by dannyo33** [comment]
This AVA is within the Ozark Mountain AVA #154 so their boundaries should align. They also use the same maps for digitizing, therefore one would expect no differences in the boundaries. However, the Ozark Mountain AVA #154 does not following the boundary closely and seems to be done sloppily. Should I maintain the boundary that I created for the Arkansas Mountain AVA and we can use my boundary (which follows the directions more closely) to correct the Ozark Mountain AVA #154?
![oh](https://user-images.githubusercontent.com/46608707/58274629-1da54b00-7d48-11e9-9278-e90ce72d0a24.jpg)
The Arkansas Mountain AVA is in red. The Ozark Mountain AVA #154 is in blue. You can see that the Arkansas Mountain boundary follows the river line more closely than the Ozark Mountain boundary.

**Comment by MicheleTobias** [comment]
Danny, let's try to avoid language that diminishes the work of others.  Yes, I agree that the boundary for Ozark Mountain could be refined.  Let's use your boundary for Arkansas Mountain, and please put a comment on Ozark Mountain that we need to match it's boundary to that of Arkansas Mountain.
