### ISSUE TITLE
templeton_gap_district

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#220]
# AVA: Templeton Gap District (templeton_gap_district)

name | value
--- | ---
ava_id | templeton_gap_district
cfr_index | 9.248
revision | [T.D. TTB-125, 79 FR 60967, Oct. 9, 2014]
state | CA
county | San Luis Obispo
within | Central Coast\|Paso Robles
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Templeton, Calif., 1948, photorevised 1979; and 
2. York Mountain, Calif., 1948, photorevised 1979.

## Boundary [src]

(1) The beginning point is on the northern portion of the Templeton map at the point where the marked southern city of Paso Robles Corporate Boundary line intersects the Salinas River 
(now very approximate to the point where Niblick Road crosses the Salinas River). From the beginning point, proceed southerly 
(upstream) along the Salinas River approximately 1.1 miles to the river&#39;s confluence with the first marked unnamed intermittent stream flowing from the east, Santa Ysabel Land Grant; then 
(2) Proceed southeasterly 
(upstream) along the unnamed intermittent stream approximately 0.4 mile to the stream&#39;s intersection with an unnamed light-duty road locally known as S. River Road, Santa Ysabel Land Grant; then 
(3) Proceed southeasterly then southerly on S. River Road approximately 2.2 miles to the road&#39;s intersection with an unnamed light-duty road locally known as Neal Springs Road, Santa Ysabel Land Grant; then 
(4) Proceed east on Neal Springs Roads approximately 0.4 mile to the road&#39;s intersection with an unnamed light-duty road locally known as Hollyhock Lane, Santa Ysabel Land Grant; then 
(5) Proceed south-southeasterly on Hollyhock Lane approximately 0.95 mile to the road&#39;s intersection with an unnamed light-duty road locally known as El Pomar Drive, Santa Ysabel Land Grant; then 
(6) Proceed southerly in a series of straight lines, totaling approximately 1.4 miles, through the 1,329-foot and 1,338-foot elevation points 
(crossing from the Santa Ysabel to the Asuncion Land Grants) to the 1,344-foot elevation point; then 
(7) Proceed southwesterly in a straight line approximately 0.3 mile to the elevation control point 
(marked by a triangle) above the 1,440-foot contour line, Asuncion Land Grant; then 
(8) Proceed south-southeasterly in a straight line approximately 0.3 mile to the 1,452-foot elevation point, and continue south-southwesterly in a straight line approximately 0.3 mile to the intersection of two light-duty roads locally known as S. El Pomar Road and Homestead Road, Asuncion Land Grant; then 
(9) Proceed west-southwesterly in a straight line approximately 1.1 miles to the point where an unnamed light-duty road locally known as Templeton Road intersects with an unnamed intermittent stream 
(where Templeton Road makes a 90 degree turn at its junction with two unnamed unimproved roads), Asuncion Land Grant; then 
(10) Proceed westerly 
(downstream) along the unnamed intermittent stream approximately 0.5 mile to the stream&#39;s confluence with the Salinas River, Asuncion Land Grant; then 
(11) Proceed westerly 
(downstream) along the Salinas River approximately 2.3 miles to the river&#39;s intersection with the boundary line of the Paso de Robles Land Grant; then 
(12) Proceed southwesterly along the boundary line of the Paso de Robles Land Grant approximately 2.3 miles to the point where the boundary line turns sharply to the northwest; then 
(13) Proceed northwesterly approximately 4.65 miles along the boundary line of the Paso de Robles Land Grant, crossing onto the York Mountain map, to the point where the boundary line turns due north 
(coincides with the southeast corner of section 32, T27S/R11E); then 
(14) Proceed north and then north-northeasterly along the boundary line of the Paso de Robles Land Grant approximately 1.5 miles to the point where the boundary line turns sharply to the northwest 
(coincides with the eastern-most point of section 20, T27S/R11E); then 
(15) Proceed northwesterly along the boundary line of the Paso de Robles Land Grant approximately 0.3 mile to the eastern-most fork of an unnamed three-fork tributary of the Jack Creek; then 
(16) Proceed northerly 
(downstream) along the unnamed intermittent tributary of Jack Creek approximately 0.15 mile to the tributary&#39;s confluence with Jack Creek, Paso de Robles Land Grant; then 
(17) Proceed southeasterly 
(downstream) along Jack Creek approximately 1.8 miles to the creek&#39;s intersection with an unnamed light-duty road locally known as Jack Creek Road 
(near BM 920), Paso de Robles Land Grant; then 
(18) Proceed northeasterly and then east-southeasterly along Jack Creek Road approximately 1 mile to the road&#39;s intersection with State Route 46; then 
(19) Proceed east on State Route 46 approximately 0.15 mile to the road&#39;s intersection with an unnamed light-duty road locally known as Hidden Valley Road, Paso de Robles Land Grant; then 
(20) Proceed southeasterly and then easterly on Hidden Valley Road approximately 2.2 miles, crossing onto the Templeton map, to the road&#39;s intersection with an unnamed light-duty road locally known as Vineyard Drive, Paso de Robles Land Grant; then 
(21) Proceed east on Vineyard Drive approximately 0.85 mile to the road&#39;s intersection with an unnamed light-duty road locally known as S. Bethel Road, Paso de Robles Land Grant; then 
(22) Proceed north-northeasterly on S. Bethel Road and then N. Bethel Road approximately 1.7 miles to the road&#39;s fifth intersection with an unnamed intermittent stream, Paso de Robles Land Grant; then 
(23) Proceed westerly 
(upstream) along the unnamed intermittent stream and then the stream&#39;s middle branch approximately 1.1 miles to the marked end of the stream, and then continue due west in a straight line approximately 0.05 mile to State Route 46 
(Cayucos Road), Paso de Robles Land Grant; then 
(24) Proceed northeasterly on State Route 46 
(Cayucos Road) approximately 0.8 mile to BM 924, Paso de Robles Land Grant; then 
(25) Proceed due north in a straight line to the southeast corner of section 12, T27S/R11E, and continue north along the eastern boundary line of section 12, a total of approximately 1.1 miles, to the section boundary line&#39;s intersection with a light-duty road locally known as Live Oak Road; then 
(26) Proceed easterly on Live Oak Road approximately 0.2 mile to the road&#39;s intersection with an unnamed intermittent stream, Paso de Robles Land Grant; then 
(27) Proceed northwesterly 
(upstream) along the unnamed intermittent stream approximately 0.35 mile to the eastern boundary line of section 12, T27S/R11E; then 
(28) Proceed north along the eastern boundary line of section 12, T27S/R11E, to the section&#39;s northeast corner, and then proceed east along the southern boundary line of section 6, T27S/R11E, a total of approximately 1.3 miles, to the intersection of the section 6 boundary line with an unnamed light-duty road locally known as Arbor Road; then 
(29) Proceed south-southeasterly on Arbor Road approximately 0.35 mile to the road&#39;s first intersection with an unnamed intermittent stream, Paso de Robles Land Grant; then 
(30) Proceed southeasterly and then easterly 
(downstream) along the unnamed intermittent stream approximately 1.4 miles to the stream&#39;s intersection with an unnamed light-duty road known locally as S. Vine Street, just west of the U.S. 101/State Route 46 interchange, Paso de Robles Land Grant; then 
(31) Proceed northerly along S. Vine Street 
(which generally parallels U.S. 101) approximately 1.8 miles to the street&#39;s intersection with the marked city of Paso Robles Corporate Boundary line 
(concurrent with the locally-known intersection of S. Vine and 1st Streets), Paso de Robles Land Grant; then 
(32) Proceed east along the marked city of Paso Robles Corporate Boundary line 
(now very approximate to the alignment of 1st Street and then Niblick Road) approximately 0.5 mile, returning to the beginning point.

**Comment by SoominHur** [comment]
Reviewed.
- Added scale information of used maps.
