### ISSUE TITLE
texas_davis_mountains

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#221]
# AVA: Texas Davis Mountains (texas_davis_mountains)

name | value
--- | ---
ava_id | texas_davis_mountains
cfr_index | 9.155
revision | [T.D. ATF-395, 63 FR 11828, Mar. 11, 1998]
state | TX
county | Jeff Davis
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Fort Davis, Texas,” 1985. 
2. “Mount Livermore, Texas—Chihuahua,” 1985.

## Boundary [src]

(1) The beginning point is the intersection of Texas Highway 17 and Farm Road 1832 on the Fort Davis, Texas, U.S.G.S. map; 
(2) From the beginning point, the boundary follows Highway 17 in a southeasterly and then southwesterly direction until it reaches the intersection of Limpia Creek with the unnamed stream which flows through Grapevine Canyon on the Fort Davis, Texas, U.S.G.S. map; 
(3) The boundary then proceeds in a straight line in a southwesterly direction until it meets Highway 118 at a gravel pit 1  miles southeast of the intersection of Highway 118 and Highway 17; 
(4) The boundary then proceeds in a straight line east by southeast until it meets Highway 166 at its junction with Highway 17; 
(5) The boundary then follows Highway 166 in a southwesterly direction onto the Mt. Livermore, Texas-Chihuahua, U.S.G.S. map; 
(6) The boundary then continues to follow Highway 166 in a westerly direction; 
(7) The boundary then continues to follow Highway 166 as it turns in a northerly and then northeasterly direction to the point where it meets Highway 118; 
(8) The boundary then follows Highway 118 in a northerly direction until it reaches a point where it intersects with the 1600 meter contour line, just north of Robbers Roost Canyon; 
(9) The boundary then proceeds in a straight line due east for about two miles until it reaches the 1600 meter contour line to the west of Friend Mountain; 
(10) The boundary then follows the 1600 meter contour line in a northeasterly direction until it reaches the northernmost point of Friend Mountain; 
(11) The boundary then diverges from the contour line and proceeds in a straight line east-southeast until it reaches the beginning point of Buckley Canyon, approximately three fifths of a mile; 
(12) The boundary then follows Buckley Canyon in an easterly direction to the point where it meets Cherry Canyon; 
(13) The boundary then follows Cherry Canyon in a northeasterly direction to the point where it meets Grapevine Canyon on the Mt. Livermore, Texas-Chihuahua, U.S.G.S. map; 
(14) The boundary then proceeds in a straight line from the intersection of Cherry and Grapevine Canyons to the peak of Bear Cave Mountain, on the Fort Davis, Texas, U.S.G.S. map; 
(15) The boundary then proceeds in a straight line from the peak of Bear Cave Mountain to the point where Farm Road 1832 begins; 
(16) The boundary then follows Farm Road 1832 back to its intersection with Texas Highway 17, at the point of beginning.

**Comment by bsllee** [comment]
I will work on this, thank you!

**Comment by MicheleTobias** [comment]
I think I have a solution, @bsllee !  I think the author mean to say the 1700 foot contour line.  If you use that one, it all make sense.  Also, review Step 2.  I think the author meant to indicate a creek that's a little more to the east than the one you used.  And remove the 999s from the attribute table, but the rest of it is great.  Also, the boundary needs to be just one polygon.  You've got a great start to this AVA.  Just a few changes and finishing up, and we're good to go.

**Comment by bsllee** [comment]
Will work on these changes this week and start a new AVA as soon as possible since I'm back in one place. Thank you so much, @MicheleTobias !

**Comment by MicheleTobias** [comment]
Take your time!  Our mantra for this project is quality over quantity.  It will all get done eventually, so I'd rather everyone take their time and not stress.

**Comment by alisonsnwong** [comment]
Checked! Updated `used_maps` section & performed minor boundary edits.
