### ISSUE TITLE
texas_high_plains

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#222]
# AVA: Texas High Plains (texas_high_plains)

name | value
--- | ---
ava_id | texas_high_plains
cfr_index | 9.144
revision | [T.D. ATF-336, 58 FR 11967, Mar. 2, 1993]
state | TX
county | Armstrong|Bailey|Borden|Briscoe|Castro|Cochran|Crosby|Dawson|Deaf Smith|Dickens|Floyd|Gaines|Garza|Hale|Hockley|Lamb|Lubbock|Lynn|Motley|Parmer|Randall|Swisher|Terry|Yoakum
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Clovis, New Mexico; Texas” 1954, revised 1973. 
2. “Brownfield, Texas; New Mexico” 1954, revised 1973. 
3. “Hobbs, New Mexico; Texas” 1954, revised 1973. 
4. “Plainview, Texas” 1954, revised 1974. 
5. “Lubbock, Texas” 1954, revised 1975. 
6. “Big Spring, Texas” 1954, revised 1975.

## Boundary [src]

(1) Beginning on the Hobbs, New Mexico; Texas, map at the intersection of the Texas-New Mexico border and U.S. Route 180 east of Hobbs, New Mexico; 
(2) The boundary follows U.S. Route 180 east through Seminole, Texas and onto the Big Spring, Texas, U.S.G.S. map where it intersects with the 3,000 foot contour line in the town of Lamesa, Texas; 
(3) The boundary then follows the 3,000 foot contour line in a generally northeasterly direction across the U.S.G.S. maps of Big Spring and Lubbock, Texas; 
(4) The boundary continues along the 3,000 foot contour line onto the map of Plainview, Texas, where it follows a generally northwesterly direction until it intersects with State Highway 217 approximately 12 miles east of Canyon, Texas; 
(5) The boundary then follows State Highway 217 west to Canyon, Texas, leaves State Highway 217 and proceeds in a straight line in a northwesterly direction until it intersects with U.S. Route 60, still within Canyon, Texas; 
(6) The boundary then follows U.S. Route 60 in a southwesterly direction onto the U.S.G.S. map of Clovis, New Mexico; Texas, where it intersects the Texas-New Mexico border; 
(7) The boundary then follows the Texas-New Mexico border south, across the U.S.G.S. map of Brownfield, Texas; New Mexico, to the beginning point on the Hobbs, New Mexico; Texas, U.S.G.S. map.

**Comment by SoominHur** [comment]
I am working on this
