### ISSUE TITLE
texas_hill_country

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#223]
# AVA: Texas Hill Country (texas_hill_country)

name | value
--- | ---
ava_id | texas_hill_country
cfr_index | 9.136
revision | [T.D. ATF-318, 56 FR 60923, Nov. 29, 1991, as amended by T.D. ATF-344, 58 FR 40354, July 28, 1993]
state | TX
county | Bandera|Bexar|Blanco|Burnet|Comal|Edwards|Gillespie|Guadalupe|Hays|Kendall|Kerr|Kimble|Lampasas|Llano|Mason|McCulloch|Medina|Menard|Real|San Saba|Travis|Uvalde|Williamson
within | 
contains | Bell Mountain\|Fredericksburg in the Texas Hill Country

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Brownwood, Texas, 1954 
revised 1974.; 
2. Sonora, Texas, 1954 
revised 1978.; 
3. Llano, Texas, 1954 
revised 1975.; 
4. Austin, Texas, 1954 
revised 1974.; 
5. Del Rio, Texas, 1958 
revised 1969.; 
6. San Antonio, Texas, 1954 
revised 1980.; 
7. Seguin, Texas, 1953 
revised 1975..

## Boundary [src]

(1) The beginning point is the intersection of Interstate Highway 35 and State highway 29 to the north of the city of Austin, on the Austin Texas, U.S.G.S. map; 
(2) From the beginning point, the boundary follows State highway 29 in a west-northwesterly direction to the intersection with U.S. Highway 183; 
(3) The boundary then follows U.S. Highway 183 in a northwesterly direction to the top of the Austin map and across the northeast corner of the Llano, Texas, U.S.G.S. map, to the intersection with State Highway 190 in Lometa, on the Brownwood, Texas, U.S.G.S. map; 
(4) The boundary then follows State Highway 190 in a southwesterly direction through San Saba and Brady on the Brownwood map to the intersection of U.S. Highway 83 at Menard, on the Llano, Texas, U.S.G.S. map; 
(5) The boundary follows U.S. highway 83 in a southerly direction to the town of Junction, where it meets U.S. Highway 377 
(Llano map); 
(6) The boundary then follows U.S. Highway 377 southwest to the town of Rocksprings, on the Sonora, Texas, U.S.G.S. map, where it meets State Highway 55; 
(7) The boundary then follows State Highway 55 in a southeasterly direction across the southeast portion of the Del Rio, Texas, U.S.G.S. map, and continues to the town of Uvalde, on the San Antonio, Texas, U.S.G.S. map, where it meets U.S. Highway 83; 
(8) The boundary then follows U.S. Highway 83 south for approximately 2 miles, until it meets U.S. Highway 90; 
(9) The boundary then follows U.S. Highway 90 east across the San Antonio map to its intersection with Loop 410 in the city of San Antonio; 
(10) The boundary then follows Loop 410 to the west of San Antonio, until it meets Interstate Highway 35; 
(11) The boundary then follows Interstate Highway 35 in a northeasterly direction across the San Antonio map and then across the northwest corner of the Seguin, Texas, U.S.G.S. map until it reaches the beginning point at the intersection with State highway 29 on the Austin, Texas, U.S.G.S. map.

**Comment by KyleWSmith** [comment]
In progress.

**Comment by alisonsnwong** [comment]
Checked! Updated `used_maps` section.
