### ISSUE TITLE
texoma

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#224]
# AVA: Texoma (texoma)

name | value
--- | ---
ava_id | texoma
cfr_index | 9.185
revision | [T.D. TTB-38, 70 FR 72716, Dec. 7, 2005]
state | TX
county | Cooke|Fannin|Grayson|Montague
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Sherman, Texas; Oklahoma, 1954, revised 1977; and 
2. Texarkana, Tex.; Ark.; Okla.; La., 1953, revised 1972.

## Boundary [src]

(1) The beginning point is the northwest corner of Montague County 
(at the Red River, which is also the Texas-Oklahoma State line) on the Sherman map. From this point, the boundary line: 
(2) Follows the Red River eastward along the Texas-Oklahoma State line, passes onto the Texarkana map, and continues to the northeast corner of Fannin County; then 
(3) Continues southward along the eastern Fannin County line to a point approximately three miles west of Petty, Texas, where a power line shown on the Texarkana map crosses the county line; then 
(4) Continues southwest in a straight line for approximately 13 miles to the intersection of State Routes 34/50 and State Route 64 at Ladonia, Texas; then 
(5) Follows State Route 34 west to its intersection with State Route 68; then 
(6) Continues west-southwesterly in a straight line from that intersection to the intersection of U.S. Highway 69 and State Route 78 at Leonard, Texas, on the Sherman map; then 
(7) Continues northwest on U.S. Highway 69 for approximately 6 miles to the intersection of U.S. Highway 69 and State Route 121 at Trenton, Texas; then 
(8) Continues westerly in a straight line to the intersection of State Routes 160 and 121, and then continues west on State Route 121 to its intersection with U.S. Highway 75 at Van Alstyne, Texas; then 
(9) Continues south along U.S. Highway 75 to the Grayson County line; then 
(10) Continues west along the southern Grayson County line and then the southern Cooke County line to the county line&#39;s intersection with Interstate 35; then 
(11) Continues north along Interstate 35 to its intersection with State Route 922 in Valley View, Texas; then 
(12) Follows State Route 922 west for approximately 17 miles to Rosston, Texas; then 
(13) Continues west-southwest from Rosston in a straight line for approximately 19 miles to the intersection of U.S. Highway 287 and State Route 101 at Sunset, Texas; then 
(14) Follows U.S. 287 northwest approximately 17 miles to the western Montague County line; and 
(15) Continues north along the western Montague County line to the beginning point at the northwest corner of Montague County.

**Comment by ouwxmaniac** [comment]
Attempting my first digitize

**Comment by MicheleTobias** [comment]
Fantastic!  Let me know if you have any questions.

**Comment by elistockwell** [comment]
Wrong info in boundary description and used maps.  Used maps still needs updating by whoever checks this boundary.

**Comment by alisonsnwong** [comment]
Checked! Added `used_maps` section.
