### ISSUE TITLE
the_hamptons_long_island

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#225]
# AVA: The Hamptons Long Island (the_hamptons_long_island)

name | value
--- | ---
ava_id | the_hamptons_long_island
cfr_index | 9.101
revision | [T.D. ATF-205, 50 FR 20413, May 16, 1985, as amended by T.D. ATF-344, 58 FR 40354, July 28, 1993]
state | NY
county | Suffolk
within | Long Island
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Riverhead, N.Y.,” 7.5 minute series, scaled at 1:24,000, edition of 1956; 
2. “Eastport, N.Y.,” 7.5 minute series, scaled at 1:24,000, edition of 1956; 
3. “New York, N.Y.; N.J.; Conn., U.S. 1:250,000 series, scaled at 1:250,000, edition of 1960, revised 1979; 
4. “Providence, R.I.; Mass.; Conn.; N.Y., U.S. 1:250,000 series, scaled at 1:250,000, edition of 1947, revised 1969, and 
5. “Hartford, Conn.; N.Y.; N.J.; Mass., U.S. 1:250,000 series, scaled at 1:250,000, edition of 1962, revised 1975.

## Boundary [src]

(1) The boundary travels south approximately 10 miles along the Southampton/Brookhaven Township line until it reaches the dunes on the Atlantic Ocean near Cupsogue Beach on the “Eastport, N.Y.” U.S.G.S. map. 
(2) Then the boundary proceeds east and west along the beaches, shorelines, islands and mainland areas of the entire South Fork of Long Island described on the “New York,” “Providence,” and “Hartford” U.S.G.S. maps until it reaches the Peconic River near Calverton at the beginning point. These boundaries consist of all of the land found in the Townships of Southampton and East Hampton 
(including Gardiners Island).

**Comment by alriks** [comment]
I am working on it.

**Comment by MicheleTobias** [comment]
Welcome, @alriks !  Let me know if you have any questions or if the boundary descriptions or documentation are confusing in any way.

**Comment by alriks** [comment]
Thank you!

It all seems very straight forward. I've almost finished my first boundary
and hope to generate a pull request later this afternoon.

Warm regards,
Alrik

**Comment by MicheleTobias** [comment]
Hi Alrik, how's this one coming along?  Do you want to keep working on it or can I release it to the other contributors?

**Comment by ericallanwest** [comment]
Please label this one In Progress and Virginia Tech. Thanks!
