### ISSUE TITLE
the_rocks_district_of_milton_freewater

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#226]
# AVA: The Rocks District of Milton-Freewater (the_rocks_district_of_milton_freewater)

name | value
--- | ---
ava_id | the_rocks_district_of_milton_freewater
cfr_index | 9.249
revision | [T.D. TTB-127, 80 FR 6906, Feb. 9, 2015]
state | OR
county | Umatilla
within | Columbia Valley\|Walla Walla Valley
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Milton-Freewater, Oreg., 1964; and 
2. Bowlus Hill, Oreg., 1964; photoinspected 1976.

## Boundary [src]

(1) The beginning point is found on the Milton-Freewater map at the intersection of an unnamed medium-duty road known locally as Freewater Highway 
(State Route 339) and an unnamed light-duty road known locally as Crockett Road, section 26, T6N/R35E. From the beginning point, proceed east-southeasterly in a straight line for 0.8 mile to the intersection of State Highway 11 
(Oregon-Washington Highway) and an unnamed light-duty road known locally as Appleton Road, section 25, T6N/R35E; then 
(2) Proceed southeasterly in a straight line for 1.05 miles, crossing onto the Bowlus Hill map, to the intersection of three unnamed light-duty roads known locally as Grant Road, Turbyne Road, and Pratt Lane on the common boundary between section 36, T6N/R35E, and section 31, T5N/R36E; then 
(3) Proceed southwesterly in a straight line for 1.1 miles, crossing back onto the Milton-Freewater map, to the intersection of the Union Pacific railroad tracks with the Walla Walla River, section 1, T5N/R35E; then 
(4) Proceed southwesterly and then west-northwesterly along the Union Pacific railroad tracks for 1.2 miles to the intersection of the railroad tracks with the 980-foot elevation contour line, approximately 0.15 mile west of Lamb Street, section 2, T5N/R35E; then 
(5) Proceed west-northwesterly in a straight line for 2.25 miles to the intersection of the 840-foot elevation contour line and an unnamed light-duty road known locally as Lower Dry Creek Road, section 33, T6N/R35E; then 
(6) Proceed northwesterly in a straight line for 0.8 mile to the intersection of the 800-foot elevation contour line with an unnamed light-duty road running north-south in section 32, T6N/R35E; then 
(7) Proceed easterly in a straight line for 0.9 mile to the intersection of the 840-foot elevation contour line with the Hudson Bay Canal, section 33, T6N/R35E; then 
(8) Proceed due north in a straight line for 0.25 mile to the line&#39;s intersection with Sunnyside Road, section 33, T6N/T35E; then 
(9) Proceed northeasterly in a straight line for 0.5 mile to the intersection of the 840-foot elevation contour line with an unnamed medium-duty road known locally as State Highway 332 
(Umapine Highway), eastern boundary of section 28, R6N/T35E; then 
(10) Proceed east-northeasterly in a straight line for 0.3 mile to the intersection of three unnamed light-duty roads known locally as Triangle Road, Hodgen Road, and Appleton Road, section 27, T6N/R35E; then 
(11) Proceed east-northeasterly in a straight line for 1.25 miles, returning to the beginning point.

**Comment by gdmf** [comment]
Please add the "In Progress" label to this one.

**Comment by alisonsnwong** [comment]
Checked! Updated mistakes in steps 1 and 7.
