### ISSUE TITLE
tip_of_the_mitt

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#227]
# AVA: Tip of the Mitt (tip_of_the_mitt)

name | value
--- | ---
ava_id | tip_of_the_mitt
cfr_index | 9.257
revision | [T.D. TTB-139, 81 FR 47291, July 21, 2016]
state | MI
county | Alpena|Antrim|Charlevoix|Cheboygan|Emmet|Presque Isle
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Cheboygan, Michigan, 1955; revised 1981; and 
2. Alpena, Mich., US-Ontario, Can.; 1954.

## Boundary [src]

(1) The beginning point is on the Cheboygan map, at the point where the Mackinac Bridge intersects the southern shoreline of the Straits of Mackinac. From the beginning point, proceed east-southeasterly along the shoreline of the South Channel of the Straits of Mackinac and Lake Huron, crossing onto the Alpena map and continuing to follow the Lake Huron shoreline and then the Thunder Bay shoreline to the point where the Thunder Bay shoreline intersects the common T31N/T30N township line south of the city of Alpena and north of Bare Point; then 
(2) Proceed northwesterly in a straight line to the intersection of an unnamed medium-duty road known locally as Long Rapids Road and an unnamed light-duty road known locally as Cathro Road; then 
(3) Proceed west in a straight line to the line&#39;s intersection with State Highway 65 and an unnamed light-duty road known locally as Hibner Road; then 
(4) Proceed northwesterly in a straight line to the intersection of the Presque Isle, Alpena, and Montmorency county lines; then 
(5) Proceed west along the southern boundary of Presque Isle County, crossing onto the Cheboygan map, to the point where the Presque Isle county line becomes the southern boundary of Cheboygan County, and continuing along the Cheboygan county line to the intersection of the Cheboygan county line with the eastern boundary of Charlevoix County; then 
(6) Proceed south then east along the Charlevoix county line to the intersection of the Charlevoix county line with the eastern boundary of Antrim County; then 
(7) Proceed south along the Antrim county line to the point where the county line turns due east; then 
(8) Proceed west in a straight line to the eastern shoreline of Grand Traverse Bay; then 
(9) Proceed north-northeasterly along the shorelines of Grand Traverse Bay, Lake Michigan, Little Traverse Bay, Sturgeon Bay, Trails End Bay, and the Straits of Mackinac, returning to the beginning point.

**Comment by sierramabanta** [comment]
Hi, I would like to do this one. Thanks!

**Comment by MicheleTobias** [comment]
Looks like description points 2 & 4 got moved a little.  Can you go back and check them all?  The shoreline section looks great!
