### ISSUE TITLE
tracy_hills

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#228]
# AVA: Tracy Hills (tracy_hills)

name | value
--- | ---
ava_id | tracy_hills
cfr_index | 9.204
revision | [T.D. TTB-54, 71 FR 65411, Nov. 8, 2006]
state | CA
county | San Joaquin|Stanislaus
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Tracy, Calif., 1954, photorevised 1981; 
2. Vernalis, CA, 1991; 
3. Solyo, Calif., 1953, photorevised 1971, photoinspected 1978; 
4. Lone Tree Creek, Calif., 1955, photorevised 1971; and 
5. Midway Calif., 1953, photorevised 1980.

## Boundary [src]

(1) The beginning point is on the Tracy map at the intersection of the Delta-Mendota Canal and Lammers Ferry Road, along the western boundary line of section 6, T3S/R5E. From the beginning point, proceed 0.4 mile generally southeast along the Delta-Mendota Canal to its intersection with the Western Pacific Railway line along the southern boundary line of section 6, T3S/R5E 
(Tracy map); then 
(2) Proceed 5.6 miles straight east along the Western Pacific Railway line and then along Linne Road to the intersection of Linne Road and Lehman Road, along the northern boundary line of section 12, T3S/R5E 
(Vernalis map); then 
(3) Proceed 1.5 miles straight south and then east along Lehman Road to its intersection with Bird Road at the southeast corner of section 12, T3S/R5E 
(Vernalis map); then 
(4) Proceed 1 mile straight south along Bird Road to its intersection with Durham Ferry Road at the southeast corner of section 13, T3S/R5E 
(Vernalis map); then 
(5) Proceed 1.9 miles straight east along Durham Ferry Road to its intersection with State Highway 33 along the northern boundary line of section 20, T3S/R6E 
(Vernalis map); then 
(6) Proceed 5.1 miles straight southeast along State Highway 33, passing the hamlet of Vernalis, to the highway&#39;s intersection with McCracken Road along the eastern boundary of section 2, T4S/R6E 
(Solyo map); then 
(7) Proceed 3.4 miles straight south along McCracken Road to its intersection with Hamilton Road at the southeast corner of section 23, T4S/R6E 
(Solyo map); then 
(8) Proceed 2.4 miles straight west along the southern boundary lines of sections 23, 22, and 21, T4S/R6E, crossing the Delta-Mendota Canal and the California Aqueduct, to the junction of the southern boundary of section 21, the 500-foot elevation line, and the westernmost transmission line, 
(Solyo map); then 
(9) Proceed 4.2 miles generally northwest along the meandering 500-foot elevation line to section 18, T4S/R6E, where the 500-foot elevation line crosses all the transmission lines and then continues northwest a short distance to the easternmost transmission line in the northwest quadrant of section 18, T4S/R6E, 
(Solyo map); then 
(10) Proceed 8.45 miles straight northwest along the easternmost transmission line, crossing from the Solyo map, over the Lone Tree Creek map, to the Tracy map, and continue to the transmission line&#39;s intersection with the western boundary of section 19, T3S/R5W, about 0.7 mile north-northeast of Black Butte 
(Tracy map); then 
(11) Proceed in a straight line 2 miles northwest to this line&#39;s intersection with the 500-foot elevation line, immediately north of an unimproved dirt road, just north of the midpoint of the western boundary line of section 12, T3S/R4E 
(Tracy map); then 
(12) Proceed 0.65 mile straight north along the western boundaries of section 12 and then section 1 to the section 1 line&#39;s intersection with Interstate Highway 580 
(I-580), section 1, T3S/R4E 
(Tracy map); then 
(13) Proceed 0.8 mile straight northwest along I-580 to its intersection with the Western Pacific Railway line in section 2, T3S/R4E 
(Midway map); then 
(14) Proceed easterly 0.7 mile along the Western Pacific Railway line to its intersection with the eastern boundary line of section 2, T3S/R4E 
(Tracy map); and 
(15) Proceed east for 1 mile in a straight line, returning to the beginning point.

**Comment by fyfangyao** [comment]
I am working on it.

**Comment by fyfangyao** [comment]
I use “Tracy, CA, 7.5 Minute Series, edition of 1954, (revised 1982),” “Solyo, Calif. 7.5 Minute Series, edition of 1953, (revised 1973),” “Lone Tree Creek, Calif. 7.5 Minute Series, edition of 1955, (revised 1971),” and “Midway Calif. 7.5 Minute Series, edition of 1953, (revised 1981)” because I cannot find the editions revised in required years.

I use “Vernalis, CA, 7.5 Minute Series, edition of 1991, (revised 1995)" because the approved map don’t specify the revision year.
