### ISSUE TITLE
trinity_lakes

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#229]
# AVA: Trinity Lakes (trinity_lakes)

name | value
--- | ---
ava_id | trinity_lakes
cfr_index | 9.184
revision | [T.D. TTB-24, 70 FR 9530, Feb. 28, 2005]
state | CA
county | Trinity
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Carrville, Calif. Provisional Edition 1986; 
2. Whisky Bill Peak, Calif. Provisional Edition 1986; 
3. Damnation Peak, Calif. Provisional Edition 1982; 
4. Trinity Center, Calif. Provisional Edition 1982; 
5. Papoose Creek, Calif. Provisional Edition 1982; 
6. Trinity Dam, Calif. Provisional Edition 1982; 
7. Lewiston, Calif. Provisional Edition 1982; 
8. Weaverville, Calif. Provisional Edition 1982; 
9. Rush Creek Lakes, Calif. Provisional Edition 1982; 
10. Siligo Peak, Calif. Provisional Edition 1982; and 
11. Covington Mill, Calif. Provisional Edition 1982.

## Boundary [src]

(1) The beginning point is on the Carrville, California, quadrangle map on township line T38N/T37N at the northwest corner of section 5, T37N/R7W, near the Trinity River at Derrick Flat; 
(2) From the beginning point, follow township line T38N/T37N due east to the northeast corner of section 5, T37N/R7W; 
(3) Proceed due south on the eastern boundary of sections 5, 8, 17, and 20 to the northwest corner of section 28, T37N/R7W, near Snow Gulch; 
(4) Follow the northern boundary of section 28, T37N/R7W, due east to the section&#39;s northeast corner; 
(5) Continue due south on the eastern boundary of sections 28 and 33, T37N/R7W, to township line T37N/T36N at the northeast corner of section 4, T36N/R7W; 
(6) Proceed due east on township line T37N/T36N onto the Whisky Bill Peak, California quadrangle map to the R7W/R6W range line at the southwest corner of section 31, T37N/R6W, near the East Fork of the Trinity River; 
(7) Follow the R7W/R6W range line due north to the northwest corner of section 30, T37N/R6W; 
(8) Continue due east along the northern boundary of section 30, T37N/R6W, to the section&#39;s northeast corner; 
(9) Proceed due south on the eastern boundary of sections 30 and 31, T37N/R6W, and sections 6 and 7, T36N/R6W, and continue onto the Damnation Peak, California, quadrangle map to the southeast corner of section 7; 
(10) Follow the southern boundary of section 7, T36N/R6W, and section 12, T36N/R7W, due west onto the Trinity Center, California, quadrangle map to the northeast corner of section 14, T36N/R7W; 
(11) Continue due south along the eastern boundary of sections 14, 23, 26, and 35, T36N/R7W, to the boundary&#39;s intersection with township line T36N/T35N at the southeast corner of section 35; 
(12) Proceed due west along township line T36N/T35N approximately 0.5 mile to the township line&#39;s intersection with the 900-meter contour line; 
(13) Follow the meandering 900-meter contour line generally west through sections 35 and 34, T36N/R7W; cross the T36N/T35N township line and continue generally southwest on the contour line around Linton Ridge, through Bridge Gulch, Bragdon Gulch, and around Feeny Ridge; cross onto the Papoose Creek, California, quadrangle map and continue southwesterly to the contour line&#39;s first intersection with a line marked “NAT RECREATION BDY INDEFINITE,” approximately 2,000 feet north of Feeny Gulch; 
(14) Continue easterly on the 900-meter contour line over Feeny Gulch; then proceed southwesterly on the meandering contour line across Van Ness Creek, both Bear Gulches, Langdon Gulch, Digger Gulch, around Fairview Ridge, along the northern side of Papoose Arm, and over the North, East, and South Forks of Papoose Creek; continue westerly on the contour line along the southern side of Papoose Arm to the contour line&#39;s intersection with Little Papoose Creek in section 24, T34N/R8W; 
(15) Continue generally west along the meandering 900-meter contour line through sections 24, 23, 14, and 15, T34N/R8W; cross onto the Trinity Dam, California, quadrangle map and continue on the contour line through sections 15 and 22; pass back onto the Papoose Creek map and follow the contour line through sections 22, 23, and 22 again; then cross back onto the Trinity Dam map and follow the contour line to its intersection with the southern boundary of section 22, T34N/R8W; 
(16) Proceed due west along the southern boundary of section 22 to the northeast corner of section 28, T34N/R8W; 
(17) Follow the eastern boundary of sections 28 and 33, T34W/R8W, and section 4, T33N/R8W, due south onto the Lewiston, California, quadrangle map, and continue due south on the eastern boundary of sections 4, 9, 16, and 21 to the southeast corner of section 21, T33N/R8W; 
(18) Then proceed due west along the southern boundary of sections 21 and 20 to the northeast corner of section 30, T33N/R8W; 
(19) Follow the eastern boundary of section 30, T33N/R8W, due south to the section&#39;s southeast corner; 
(20) Continue due west along the southern boundary of section 30, T33N/R8W, and sections 25 and 26, T33N/R9W, to the northeast corner of section 34, T33N/R9W; 
(21) Proceed due south on the eastern boundary of section 34, T33N/R9W, and section 3, T32N/R9W, to the southeast corner of section 3 near Tom Lang Gulch; 
(22) Follow the southern boundary of section 3, T32N/R9W, due west onto the Weaverville, California, quadrangle map, and continue west along the southern boundary of sections 3, 4, and 5, T32N/R9W, to the southwest corner of section 5; 
(23) Then proceed due north along the western boundary of section 5, T32N/R9W, for approximately 0.8 mile to its intersection with the 700-meter contour line; 
(24) Follow the 700-meter contour line generally northwest through section 5, T32N/R9W, and then through sections 32, 31, 32 again, 29, and 28, T33N/R9W, to the contour line&#39;s intersection with the northern boundary of section 28; 
(25) Proceed due east along the northern boundary of section 28 across Limekiln Gulch and China Gulch to the southwest corner of section 22, T33N/R9W; 
(26) Follow the western boundary of section 22, T33N/R9W, due north to the section&#39;s northwest corner; 
(27) Then continue due east along the northern boundary of section 22, T33N/R9W, onto the Lewiston map to the section&#39;s northeast corner; 
(28) Proceed due north on the western boundary of section 14, T33N/R9W, to the section&#39;s northwest corner; 
(29) Follow the northern boundary of sections 14 and 13, T33N/R9W, due east to the R9W/R8W range line at the northeast corner of section 13; 
(30) Then proceed due north along the R9W/R8W range line onto the Trinity Dam map, and continue along the range line to the southeast corner of section 1, R9W/T34N, near Smith Gulch; 
(31) Continue due west along the southern boundary of section 1, T34N/R9W, for approximately 0.3 mile to its intersection with the 900-meter contour line; 
(32) Follow the meandering 900-meter contour line generally west over Tannery Gulch and around Tannery Ridge, cross onto the Rush Creek Lakes, California, quadrangle map, and continue along the 900-meter contour line to its intersection with Slate Creek in section 4, T34N/R9W; 
(33) Using the Rush Creek Lakes and Trinity Dam maps, follow the contour line generally northeast from Slate Creek, crossing Irish Gulch in section 3, T34N/R9W, 
(crossing back and forth between the two maps three times) to the contour line&#39;s intersection with township line T34N/T35N at the northern boundary of section 3, T34N/R9W, on the Trinity Dam map; 
(34) Continue generally northwest on the meandering 900-meter contour line and cross onto the Rush Creek Lakes map in section 34, T35N/R9W; continue northwesterly on the contour line over Cummings Creek, Bear Gulch, Snowslide Gulch, Sawmill Creek, and Van Matre Creek; cross onto the Siligo Peak, California, quadrangle map and continue generally northwest on the 900-meter contour line over Middle Creek and Owens Creek to the contour line&#39;s intersection with Stuart Fork; 
(35) Continue generally southeast on the 900-meter contour line over Fire Camp Creek, Lightning Creek, and Sunday Creek; cross onto the Rush Creek Lakes map and continue generally southeast on the contour line over Elk Gulch and Trinity Alps Creek; cross onto the Trinity Dam map in section 27, T35N/R9W, and proceed easterly along the contour line to its intersection with the eastern boundary of section 27, T35N/R9W; 
(36) Continue generally north along the 900-meter contour line through sections 26 and 23, T35N/R9W, cross onto the Covington Mill, California, quadrangle map in section 23, T35N/R9W, and continue northerly along the contour line to its intersection with Stoney Creek in the same section; 
(37) From Stoney Creek, continue generally south on the 900-meter contour line, cross back onto the Trinity Dam map in section 23, T35N/R9W, and continue southerly on the contour line through sections 23, 26, and 35 to the contour line&#39;s intersection with the eastern boundary of section 35, T35N/R9W, near that section&#39;s northeast corner; 
(38) Continue generally northeast on the meandering 900-meter contour line over Telephone Ridge, Buck Gulch, and Buck Ridge; cross onto the Covington Mill map in section 19, T35N/R8W, and continue northwesterly along the contour line across Mule Creek and Snowslide Gulch in section 13, T35N/R9W; continue on the contour line, cross Little Mule Creek in section 18, T35N/R8W, and continue southeasterly on the contour line to its intersection with a line marked “TRANS LINE SINGLE WOOD POLES” in section 20, T35N/R8W; 
(39) Continue generally northeast along the 900-meter contour line through sections 20 and 17, T35N/R8W, and cross Strope Creek, Mosquito Gulch, Greenhorn Gulch, Taylor Gulch, Stuart Fork 
(in section 5, T35N/R8W), and Davis Creek; cross onto the Trinity Center map in section 35, T36/R8W, and continue on the contour line to its intersection with the northern boundary of that section; 
(40) Proceed due east along the northern boundary of sections 35 and 36, T36N/R8W, to the R8W/R7W range line at the northeast corner of section 36; 
(41) Follow the R8W/R7W range line due north onto the Carrville map and continue along the range line to its intersection with township line T38N/T37N at the northwest corner of section 6, T37N/R7W; and 
(42) Proceed due east along township line T38N/T37N and return to the beginning point at the northwest corner of section 5, T37N/R7W.

**Comment by MicheleTobias** [comment]
I'm working on this one

**Comment by SoominHur** [comment]
Reviewed
- Add scale information of used maps
