### ISSUE TITLE
arroyo_grande_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#23]
# AVA: Arroyo Grande Valley (arroyo_grande_valley)

name | value
--- | ---
ava_id | arroyo_grande_valley
cfr_index | 9.129
revision | [T.D. ATF-291, 55 FR 287, Jan. 4, 1990]
state | CA
county | San Luis Obispo
within | Central Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Arroyo Grande, NE, California,” edition of 1965, photorevised 1978. 
2. “Tar Spring Ridge, California,” edition of 1967. 
3. “Nipomo, California,” edition of 1965. 
4. “Oceano, California,” edition of 1965, photorevised 1979.

## Boundary [src]

(1) Beginning on the “Arroyo Grande” map at the point of intersection of State Route 227 and Corbit Canyon Road in Arroyo Grande Township, the boundary proceeds approximately 0.1 mile, in a northwesterly direction, along the roadway of State Route 227 to the point where State Route 227 intersects with Printz Road in Poorman Canyon in the Santa Manuela land grant; 
(2) Then northwesterly, approximately 1.5 miles, along Printz Road to its intersection with Noyes Road in the Santa Manuela land grant; 
(3) Then northerly, approximately 1.5 miles, along Noyes Road to its intersection with State Route 227 
(at vertical control station “BM 452”) in the Santa Manuela land grant; 
(4) Then in a northeasterly direction in a straight line approximately 1.4 miles to the intersection of Corbit Canyon Road with an unnamed, unimproved road at Verde in the Santa Manuela land grant; 
(5) Then approximately 1.9 miles in a generally northeasterly direction, along the meanders of said unimproved road to its easternmost point, prior to the road turning back in a northwesterly direction to its eventual intersection with Biddle Ranch Road; 
(6) Then in a northwesterly direction approximately 1.13 miles in a straight line to the summit of an unnamed peak identified as having an elevation of 626 feet in the Santa Manuela land grant; 
(7) Then easterly, approximately 0.46 mile in a straight line, to the summit of an unnamed peak identified as having an elevation of 635 feet, in the Santa Manuela land grant; 
(8) Then east northeasterly, approximately 0.27 mile in a straight line, to the summit of an unnamed peak identified as having an elevation of 799 feet, in the Santa Manuela land grant; 
(9) Then easterly, approximately 0.78 mile in a straight line, to the summit of an unnamed peak identified as having an elevation of 952 feet, in the Santa Manuela land grant; 
(10) Then easterly, approximately 0.7 mile in a straight line, to the summit of an unnamed peak identified as having an elevation of 1,188 feet, in the southwest corner of section 29, T. 31 S., R. 14 E.; 
(11) Then east southeasterly, approximately 0.9 mile in a straight line, to the point at which Upper Arroyo Grande Road crosses the spillway of Lopez Dam in section 32, T. 31 S., R. 14 E. 
(see “Tar Spring Ridge” map); 
(12) Then, in a generally easterly direction, approximately 3.64 miles along Upper Arroyo Grande Road 
(under construction) to the point where the broken red line for the proposed location of said road diverges in a northerly direction from the light duty roadbed of said road in the Arroyo Grande land grant 
(north of section 35, T. 31 S., R. 14 E.); 
(13) Then, in a generally northerly direction, approximately 2.5 miles, along the broken red line for the proposed location of Upper Arroyo Grande Road to its point of intersection with an unnamed unimproved road 
(this intersection being 1.2 miles northwest of Ranchita Ranch) in the Arroyo Grande land grant; 
(14) From the point of intersection of the proposed location of Upper Arroyo Grande Road and the unnamed unimproved road, the boundary proceeds in a straight line, east northeasterly, approximately 1.8 miles, to the summit of an unnamed peak identified as having an elevation of 1,182 feet, in the northwest corner of section 19, T. 31 S., R. 15 E.; 
(15) Then southeasterly, approximately 1.8 miles in a straight line, to the summit of an unnamed peak identified as having an elevation of 1,022 feet, in the northeast corner of section 29, T. 31 S., R. 15 E.; 
(16) Then west southwesterly, approximately 0.84 mile in a straight line, to the summit of an unnamed peak identified as having an elevation of 1,310 feet, in the northeast corner of section 30, T. 31 S., R. 15 E.; 
(17) Then south southeasterly, approximately 1.46 miles in a straight line, to the summit of an unnamed peak identified as having an elevation of 1,261 feet, in section 32, T. 31 S., R. 15 E.; 
(18) Then southeasterly, approximately 0.7 mile in a straight line, to the summit of an unnamed peak identified as having an elevation of 1,436 feet, in the northwest corner of section 4, T. 32 S., R. 15 E.; 
(19) Then southwesterly, approximately 1.07 miles in a straight line, to the summit of an unnamed peak identified as having an elevation of 1,308 feet, in the Huasna land grant; 
(20) Then west northwesterly, approximately 1.50 miles in a straight line, to the summit of an unnamed peak identified as having an elevation of 1,070 feet, along the east border of section 1, T. 32 S., R. 14 E.; 
(21) Then south southeasterly, approximately 1.38 miles in a straight line, to the summit of an unnamed peak identified as having an elevation of 1,251 feet, in the Hausna land grant; 
(22) Then southwesterly, approximately 0.95 mile in a straight line, to the summit of an unnamed peak identified as having an elevation of 1,458 feet, in the Santa Manuela land grant; 
(23) Then southeasterly, approximately 0.8 mile in a straight line, to the summit of an unnamed peak identified as having an elevation of 1,377 feet, in the Huasna land grant; 
(24) Then southwesterly, approximately 1.4 miles in a straight line, to the summit of an unnamed peak identified as having an elevation of 1,593 feet, in the Santa Manuela land grant 
(See “Nipomo” map); 
(25) Then southwesterly, approximately 1.1 miles in a straight line, to the jeep trail immediately north of the summit of an unnamed peak identified as having an elevation of 1,549 feet, just north of section 35, T. 32 S., R. 14 E.; 
(26) Then north northwesterly, approximately 2.73 miles along the jeep trail on Newsom Ridge to the point of intersection of said jeep trail and an unnamed unimproved road 
(immediately north of section 28, T. 32 S., R. 14 E.); 
(27) Then southerly, approximately 1.63 miles along said unimproved road to its intersection with Upper Los Berros No. 2 Road in section 33, T. 32 S., R. 14 E.; 
(28) Then southwesterly, approximately 3.27 miles along the stream in Los Berros Canyon 
(of which approximately 2.0 miles are along Upper Los Berros No. 2 Road) to the point at which U.S. Highway 101 crosses said stream in section 35, T. 12 N., R. 35 W. 
(See “Oceano” map); 
(29) Then across U.S. Highway 101 and continuing in a southwesterly direction approximately 0.1 mile to Los Berros Arroyo Grande Road; 
(30) Then following Los Berros Arroyo Grande Road in generally a northwesterly direction approximately 4 miles until it intersects with Valley Road; 
(31) Then following Valley Road in generally a northerly direction approximately 1.2 miles until it intersects with U.S. Highway 101; 
(32) Then in a northwesterly direction along U.S. Highway 101 approximately .35 mile until it intersects with State Highway 227; 
(33) Then in a northeasterly and then a northerly direction along State Highway 227 approximately 1.4 miles to the point of beginning.

**Comment by SoominHur** [comment]
Reviewed.
- Add scale information of the used maps.
