### ISSUE TITLE
umpqua_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#230]
# AVA: Umpqua Valley (umpqua_valley)

name | value
--- | ---
ava_id | umpqua_valley
cfr_index | 9.89
revision | [T.D. ATF-170, 49 FR 12246, Mar. 29, 1984]
state | OR
county | Douglas
within | Southern Oregon
contains | Elkton Oregon\|Red Hill Douglas County Oregon

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Roseburg,” scale 1:250,000 
1958, revised 1970.; and 
2. “Medford,” scale 1:250,000 
1955, revised 1976..

## Boundary [src]

(1) From the beginning point, the boundary proceeds north along the Douglas/Lane County line approximately .5 miles to the 1,000-foot contour line; 
(2) Thence northwest along the 1,000-foot contour line to the Douglas/Lane County line; thence west along the Douglas/Lane County line approximately 2.5 miles, returning to the 1,000-foot contour line; thence in a generally westerly direction along the 1,000-foot contour line to the R9W/R10W range line; 
(3) Thence south along the R9W/R10W range line approximately 2.75 miles to the center of the Umpqua River; thence along a straight line in an easterly direction approximately 6.25 miles to the intersection of range line R8W/R9W with the center of the Umpqua River; thence south along range line R8W/R9W approximately 3.5 miles to its intersection with township line T22S/T23S; 
(4) Thence southeast approximately 8.5 miles along a straight line to the intersection of township line T23S/T24S with range line R7W/R8W; thence south along the R7W/R8W range line approximately 8 miles to its intersection with the 1,000-foot contour line; thence in a southeasterly direction in a straight line approximately 3.5 miles toward the intersection of township line T25S/T26S with range line R6W/R7W, returning to the 1,000-foot contour line; 
(5) Thence in a southerly direction along the 1,000-foot contour line to the intersection of township line T27S/T28S with range line R7W/R8W; thence in a southwesterly direction in a straight line approximately 3.5 miles toward the intersection of township line T28S/T29S with range line R8W/R9W, returning to the 1,000-foot contour line; thence south along the 1,000-foot contour line to its intersection with township line T29S/T30S; 
(6) Thence east along township line T29S/T30S approximately .33 miles, rejoining the 1,000-foot contour line; thence in a northerly and eventually a southerly direction along the 1,000-foot contour line past the town of Riddle on the “Medford” map to range line R6W/R7W; thence south along the R6W/R7W range line approximately .5 miles back to the 1,000-foot contour line; 
(7) Thence in an easterly, westerly, and eventually a northerly direction along the 1,000-foot contour line to a point approximately 3.5 miles east of Dillard, where the contour line crosses Interstate Highway 5 on the “Roseburg” map; thence northeast along Interstate Highway 5 approximately .25 mile, returning to the 1,000-foot contour line; thence in a generally northeasterly, southeasterly, northwesterly, and eventually a northeasterly direction along the 1,000-foot contour line past the town of Idleyld Park to the R2W/R3W range line; 
(8) Thence north along range line R2W/R3W approximately 1.75 miles to the T25S/T26S township line; thence west along township line T25S/T26S approximately .25 mile, returning to the 1,000-foot contour line; thence in a generally westerly and then a northerly direction along the 1,000-foot contour line up the valley of Calapooya Creek to the R3W/R4W range line; thence north along range line R3W/R4W approximately 2.25 miles, back to the 1,000-foot contour line; 
(9) Thence in a westerly and then a northerly direction along the 1,000-foot contour line to the T23S/T24S township line; thence east along the T23S/T24S township line approximately 2.75 miles to the 1,000-foot contour line; thence in a northerly direction along the 1,000-foot contour line to its intersection with the Douglas/Lane County line; thence north along the Douglas/Lane County line approximately .75 mile to the point of beginning.

**Comment by dannyo33** [comment]
in progress

**Comment by dannyo33** [comment]
I'm having trouble finding the petition entry for this AVA in the Federal Register Library. Umpqua Valley is mentioned in petitions of nearby AVAs, but I cannot find the specific petition for Umpqua Valley. Any advice on how to find the petition?

**Comment by MicheleTobias** [comment]
I find the revision history string to be helpful: [T.D. ATF-170, 49 FR 12246, Mar. 29, 1984]  The 49 tells you the volume number.  12246 is the page number in that volume.  Sometimes that page number puts you in the middle of the document, but it's close enough.  I also typically search Hein Online with the AVA name and the word viticultural, then scan the results for the right volume number.

**Comment by dannyo33** [comment]
There is a mismatch of boundaries along the 1000-ft contour line for Elkton Oregon AVA #70 and Umpqua Valley AVA. Elkton Oregon AVA should be completely within Umpqua Valley AVA but this is not the case because Elkton Oregon AVA uses 1:24,000 scale maps to digitize while Umpqua Valley AVA uses 1:250,000 scale maps to digitize. I wanted to know what to do about this as I think it would be bad practice to leave the mismatch in the boundary between the two AVAs. Photos of the problem are attached.

![overlap](https://user-images.githubusercontent.com/46608707/55746346-56829e00-59ee-11e9-96ab-789bd3949f9b.jpg)

![maps](https://user-images.githubusercontent.com/46608707/55746415-72863f80-59ee-11e9-9d2b-e8117d30c16c.jpg)

**Comment by MicheleTobias** [comment]
Excellent question!  Our policy is to match the boundaries whenever we know they should align.  I would suggest that we follow the directions for the oldest boundary and match the newer one to that.  Then we'd make sure to note that change in the issue for the AVA we had to change from the original description.

**Comment by dannyo33** [comment]
The Umpqua Valley AVA seems to be the older of the two AVAs with a creation date of 1984-03-16 while Elkton Oregon AVA has a creation date of 2013-03-07. Should I then just keep the current Umpqua Valley AVA boundary then edit Elkton Oregon AVA after finishing this issue? Or should I use the Elkton Oregon AVA boundary since it was digitized and completed before the Umpqua Valley AVA?

**Comment by MicheleTobias** [comment]
Let's keep the boundary with the oldest document creation date (so we'll digitize the Umpqua Valley boundary and move Elkton's to match)

**Comment by alisonsnwong** [comment]
Checked! Updated errors in https://github.com/UCDavisLibrary/ava/issues/501 and other minor vertex errors.
