### ISSUE TITLE
upper_hiwassee_highlands

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#231]
# AVA: Upper Hiwassee Highlands (upper_hiwassee_highlands)

name | value
--- | ---
ava_id | upper_hiwassee_highlands
cfr_index | 9.234
revision | [T.D. TTB-120, 79 FR 41893, July 18, 2014]
state | GA|NC
county | 
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Unaka, NC/TN, 1957; photorevised 1978; 
2. McDaniel Bald, NC/TN, 1957; photoinspected 1976; 
3. Marble, NC, 1938; photorevised 1990; 
4. Andrews, NC, 1938; photorevised 1990; 
5. Topton, NC, 1957; photoinspected 1976; 
6. Peachtree, NC, 1937; photorevised 1973; 
7. Hayesville, NC, 1966; photorevised 1978; photoinspected 1987; 
8. Shooting Creek, NC, 1957; photorevised 1990; 
9. Rainbow Springs, NC, 1957; photorevised 1978; 
10. Macedonia, GA/NC, 1988; 
11. Hightower Bald, GA/NC, 1988; 
12. Tray Mountain, GA, 1957; photorevised 1985; 
13. Jacks Gap, GA, 1988; 
14. Hiawassee, GA/NC, 1988; 
15. Blairsville, GA/NC, 1988; 
16. Cowrock, GA, 1988; 
17. Coosa Bald, GA, 1988; 
18. Neels Gap, GA, 1988; 
19. Mulky Gap, GA, 1965; 
20. Wilscot, GA, 1947; 
21. Nottely Dam, GA/NC, 1988; 
22. Culberson, NC/GA, 1988; 
23. Persimmon Creek, NC, 1957; photorevised 1978; and 
24. Isabella, TN/NC, 1957; photorevised 1978.

## Boundary [src]

(1) The beginning point is in Cherokee County, North Carolina, on the Unaka map at the intersection of the northwestern end of the Hiwassee Dam and an unnamed light-duty road known locally as Hiwassee Dam Access Road. 
(2) From the beginning point, proceed northwesterly on Hiwassee Dam Access Road approximately 4.2 miles to the road&#39;s intersection with an unnamed light-duty road known locally as Joe Brown Highway; then 
(3) Proceed northeasterly on Joe Brown Highway approximately 1.4 miles to the highway&#39;s intersection with an unnamed light-duty road known locally as Burrell Mountain Road; then 
(4) Proceed east-northeasterly along a straight line 
(drawn from the intersection of Joe Brown Highway and Burrell Mountain Road to the peak of Bird Knob) to the point where the line intersects the 2,400-foot elevation line west of Bird Knob; then 
(5) Proceed initially southerly and then easterly along the meandering 2,400-foot elevation line and continue to follow the elevation line in an overall clockwise direction through Cherokee and Clay Counties, North Carolina, and then Towns and Union Counties, Georgia, crossing over as necessary the McDaniel Bald, Marble, Andrews, Topton, Peachtree, Hayesville, Shooting Creek, Rainbow Springs, Macedonia, Hightower Bald, Tray Mountain, Jacks Gap, Hiwassee, Blairsville, Cowrock, Coosa Bald, Neels Gap, and Mulky Gap maps and ending on the Wilscot map, at the intersection of the 2,400-foot elevation line with the Union-Fannin County boundary line at Skeenah Gap; then 
(6) Proceed northerly along the meandering Union-Fannin County boundary line, crossing over the Mulky Gap and Nottely Dam maps and onto the Culberson map, to the summit of High Top Mountain; then 
(7) Proceed northwesterly in a straight line approximately one mile to the intersection of two unnamed light-duty roads known locally as Cutcane Road and Mt. Herman Road, near Mt. Herman Church; then 
(8) Proceed northwesterly on Mt. Herman Road approximately one mile to the road&#39;s intersection with State Spur 60 
(Murphy Highway); then 
(9) Proceed southwesterly on State Spur 60 
(Murphy Highway) approximately 2 miles to the road&#39;s intersection with an unnamed light-duty road known locally as Knollwood Road; then 
(10) Proceed northwesterly in a straight line approximately 1.75 miles to the summit of Watson Mountain; then 
(11) Proceed northeasterly in a straight line approximately 2.15 miles, crossing onto the Persimmon Creek map, to the line&#39;s intersection with the wagon and jeep track at the southernmost summit of Vance Mountain in Cherokee County, North Carolina; then 
(12) Proceed north-northwesterly along the wagon and jeep track approximately 0.8 mile to the track&#39;s intersection with a marked foot trail near the 2,200-foot elevation line on the northern spur of Vance Mountain; then 
(13) Proceed north-northwesterly along the foot trail approximately 0.5 mile to the trail&#39;s intersection with an unnamed road known locally as Wallace Road, and then continue north-northwesterly along Wallace Road approximately 0.4 mile to the road&#39;s intersection with U.S. Highway 64 near Hothouse; then 
(14) Proceed westerly along U.S. Highway 64 approximately one mile to the highway&#39;s intersection with a marked northerly foot trail at Nealy Gap; then 
(15) Proceed northerly along the marked foot trail, briefly crossing to and from the Isabella map, to the foot trail&#39;s intersection with an unnamed unimproved road, and then continue northerly on the unimproved road to its intersection with a second unnamed unimproved road known locally as Charles Laney Road, a total approximate distance of 0.75 mile; then 
(16) Proceed northwesterly on the unnamed unimproved road known locally as Charles Laney Road, crossing onto the Isabella map, to the road&#39;s end, and then continue north-northwesterly on a marked foot trail to the trail&#39;s intersection with a wagon and jeep track at Wolfpen Gap, a total approximate distance of one mile; then 
(17) Proceed easterly and then northeasterly along the wagon and jeep trail, crossing onto the Persimmon Creek map, to the 3,284-foot benchmark 
(MLB 1514) on Payne Mountain, then continue northeasterly on the wagon and jeep trail 
(which is partially marked as a foot trail) along the ridge line of Payne Mountain to the peak of Harris Top, then continue north-northeasterly on the wagon and jeep trail to the peak of Beaver Top, a total approximate distance of 2.75 miles; then 
(18) Proceed northeasterly approximately 0.25 mile on the wagon and jeep trail to the point where the trail turns sharply to the southeast at a summit within the 2,480-foot elevation line on the western shoulder of Indian Grave Gap; then 
(19) Proceed north in a straight line approximately 0.95 mile to the summit of Candy Mountain, and then continue north-northwest in a straight line approximately 0.45 mile to the line&#39;s intersection with an unnamed light-duty road known locally as Candy Mountain Road; then 
(20) Proceed east-northeasterly on Candy Mountain Road approximately 0.8 mile to the 1,740-foot benchmark 
(BM HR 116); then 
(21) Proceed northerly in a straight line approximately 1.2 miles to the southernmost peak of Ghormley Mountain 
(within the 2,440-foot elevation line); then 
(22) Proceed north-northeast in a straight line approximately 1.3 miles to the intersection of an unnamed light-duty road known locally as Lower Bear Paw Road and an unnamed unimproved road just south of Reids Chapel 
(the chapel is shown along the southern edge of the Unaka map); then 
(23) Proceed northerly on Lower Bear Paw Road approximately 0.35 mile, crossing onto the Unaka map, to the road&#39;s intersection with an unnamed light-duty road known locally as Hiwassee Dam Access Road; then 
(24) Proceed easterly and then northerly along Hiwassee Dam Access Road approximately 2.9 miles, returning to the beginning point at the northwestern end of Hiwassee Dam.

**Comment by davidkli** [comment]
This AVA has been checked and had its boundary updated.
