### ISSUE TITLE
upper_mississippi_river_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#232]
# AVA: Upper Mississippi River Valley (upper_mississippi_river_valley)

name | value
--- | ---
ava_id | upper_mississippi_river_valley
cfr_index | 9.216
revision | [T.D. TTB-77, 74 FR 29400, June 22, 2009]
state | IL|IA|MN|WI
county | 
within | 
contains | Lake Wisconsin (WI)

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. State of Minnesota, scale 1:500,000; compiled in 1963; edition of 1985; 
2. State of Wisconsin, scale 1:500,000; compiled in 1966; edition of 1984; 
3. State of Illinois, scale 1:500,000; compiled in 1970; edition of 1987; 
4. State of Iowa, scale 1:500,000; compiled in 1965; edition of 1984; 
5. Anamosa, Iowa, 1:100,000 scale; edited 1984; and 
6. Marshalltown, Iowa, 1:100,000 scale; edited 1984.

## Boundary [src]

(1) The beginning point is on the State of Minnesota map at the intersection of Interstate Highways 94 and 494 
(beltway), east of St. Paul at Oakbury in Washington County. From the beginning point, proceed east on Interstate 94, crossing over Lake St. Croix and onto the State of Wisconsin map at St. Croix County, and then continuing through Dunn County to Eau Claire County, to the intersection of Interstate Highway 94 with Wisconsin State Highway 85, southwest of the City of Eau Claire; then 
(2) Proceed northeast on Wisconsin State Highway 85 toward the City of Eau Claire to U.S. Highway 12; then 
(3) Proceed southeast on U.S. Highway 12 into Jackson County and passing through Clark County, to Interstate Highway 94 at Black River Falls; then 
(4) Proceed southeast on Interstate Highway 94 into Monroe County to Interstate Highway 90, east of the Fort McCoy Military Reservation; then 
(5) Proceed southeast on Interstate Highway 90 through Juneau, Sauk, Columbia, Dane, and Rock Counties, crossing onto the State of Illinois map at Winnebago County to U.S. Highway 20 at Cherry Valley; then 
(6) Proceed west on U.S. Highway 20 to Illinois State Highway 2, west of the Rock River; then 
(7) Proceed southwest on Illinois State Highway 2, passing through Ogle County and into Lee County, to Illinois State Highway 26 at Dixon; then 
(8) Proceed south on Illinois State Highway 26 to Illinois State Highway 5 
(which has been redesignated as Interstate Highway 88 on contemporary maps of Illinois); then 
(9) Proceed southwest on Illinois State Highway 5 
(Interstate Highway 88), passing through Whiteside County and into Rock Island County, to Interstate Highway 80 at Barstow; then 
(10) Proceed generally northwest on Interstate Highway 80, crossing the Mississippi River, onto the State of Iowa map at Scott County, and continuing west-northwest through Cedar County and into Johnson County to the intersection of Interstate Highways 80 and 380 at Tiffin; then 
(11) Proceed north-northwest on Interstate Highway 380 into Linn County and Cedar Rapids on the State of Iowa map. Then using the Anamosa map, followed by the Marshalltown map, follow Interstate Highway 380, labeled “Under Construction” on the Anamosa map, northwest through Benton and Buchanan Counties to Black Hawk County, to U.S. Highway 20, southeast of Waterloo and Raymond; then 
(12) Using the State of Iowa map, proceed west-northwest on U.S. Highway 20 to Waterloo and U.S. Highway 63; then 
(13) Proceed north on U.S. Highway 63 through Bremer, Chicksaw, and Howard Counties, skirting the Upper Iowa River at Chester, and crossing onto the State of Minnesota map at Fillmore County, to Minnesota State Highway 56; then 
(14) Proceed northwest and northerly on Minnesota State Highway 56 through Mower, Dodge, and Goodhue Counties to Dakota County, where it joins with State Highway 52 on commercial maps, to Interstate Highway 494 
(beltway), south of St. Paul; then 
(15) Follow Interstate Highway 494 
(beltway) northeast into Washington County, returning to the beginning point.

**Comment by InnisfreeM** [comment]
Ok, I'm going to work on this one since it is near me. I feel like I need to do one in order to show my student worker how it is done.

**Comment by MicheleTobias** [comment]
Sounds good to me!  I changed the label.  Don't hesitate to ask questions.  It helps me refine the documentation.

**Comment by InnisfreeM** [comment]
Hello again. I'm searching for maps now. The first 4 maps on the list are 1:500,000 state maps. I'm not finding these through the USGS interface. Either I'm not searching properly or I need another source.

**Comment by MicheleTobias** [comment]
Some of the boundary descriptions use maps we can't get from TopoView.  In that case, it's completely reasonable to find a different source or to substitute maps.  Since the description for this AVA generally follows county lines and highways, I would probably sub in a topo map (or maps) from a similar time period.  Just keep track of which maps you end up using to write that info in the  attribute table.
