### ISSUE TITLE
virginia_s_eastern_shore

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#233]
# AVA: Virginia’s Eastern Shore (virginia_s_eastern_shore)

name | value
--- | ---
ava_id | virginia_s_eastern_shore
cfr_index | 9.135
revision | [T.D. ATF-309, 56 FR 24, Jan. 2, 1991]
state | VA
county | Accomack|Northampton
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Eastville, VA.; N.C.; MD., 1946 
revised 1969.. 
2. Salisbury, MD.; DEL.; N.J.; VA., 1946 
revised 1969.. 
3. Richmond VA.; MD., 1973.

## Boundary [src]

(1) The beginning point is the intersection of the Virginia/Maryland border and Chincoteague Bay, near Greenbackville on the Salisbury, MD., U.S.G.S. map; 
(2) From the beginning point, the boundary follows the coastline in a southwesterly direction. Where there are marshes indicated on the U.S.G.S. maps, the boundry is the inland side of these marshes; 
(3) When the boundary reaches the southernmost point of the peninsula, on the Eastville, VA., U.S.G.S. map, the boundary turns and proceeds in a northwesterly direction, again following the coastline around Cherrystone Inlet on the Richmond, VA., U.S.G.S. map; 
(4) The boundary continues to follow the coastline and the inland side of any marshes indicated on the U.S.G.S. maps in a northeasterly direction, until it reaches the Virginia/Maryland border on the Eastville, VA., U.S.G.S. map; 
(5) The boundary then follows the Virginia/Maryland border back to the beginning point at Chincoteague Bay on the Salisbury, MD., U.S.G.S. map.

**Comment by ouwxmaniac** [comment]
In progress

**Comment by alisonsnwong** [comment]
Checked! Made edits to make the boundary more precise.
