### ISSUE TITLE
wahluke_slope

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#234]
# AVA: Wahluke Slope (wahluke_slope)

name | value
--- | ---
ava_id | wahluke_slope
cfr_index | 9.192
revision | [T.D. TTB-40, 70 FR 72710, Dec. 7, 2005]
state | WA
county | Grant
within | Columbia Valley
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Beverly Quadrangle, Washington, 1965; 
2. Beverly SE Quadrangle, Washington—Grant Co., 1965; 
3. Smyrna Quadrangle, Washington—Grant Co., Provisional Edition 1986; 
4. Wahatis Peak Quadrangle, Washington—Grant Co., Provisional Edition 1986; 
5. Coyote Rapids Quadrangle, Washington, Provisional Edition 1986; 
6. Vernita Bridge Quadrangle, Washington, Provisional Edition 1986; 
7. Priest Rapids NE Quadrangle, Washington, Provisional Edition 1986; and 
8. Priest Rapids Quadrangle, Washington, 1948; photo revised 1978.

## Boundary [src]

(1) The beginning point is at the northwest corner of the viticultural area where the east bank of the Columbia River intersects the north boundary line of section 22, T15N/R23E, on the Beverly map; then 
(2) From the beginning point proceed straight east 1.5 miles to the intersection of the section 23 north boundary line and the 1,480-foot elevation line, T15N/R23E, Beverly map; then 
(3) Proceed generally east along the meandering 1,480-foot elevation line, crossing the Beverly map, the Beverly SE map, and the Smyrna map, and continue onto the Wahatis Peak map to the intersection of the 1,480-foot elevation line and the eastern boundary line of section 15, which forms a portion of the boundary line of the Hanford Site, T15N/R26E, Wahatis Peak map; then 
(4) Proceed generally southwest along the Hanford Site boundary in a series of 90 degree angles, crossing the Wahatis map, the Coyote Rapids map in section 36, T15N/R25E, and the Vernita Bridge map, and continue onto the Priest Rapids NE map to the intersection of the Hanford Site boundary and the north bank of the Columbia River, section 10, T13N/R24E, Priest Rapids NE map; then 
(5) Proceed generally west along the north bank of the Columbia River, crossing onto the Priest Rapids map and, turning north-northwest, continue along the river bank and, crossing onto the Beverly map, return to the beginning point.

**Comment by SoominHur** [comment]
In Progress
