### ISSUE TITLE
warren_hills

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#236]
# AVA: Warren Hills (warren_hills)

name | value
--- | ---
ava_id | warren_hills
cfr_index | 9.121
revision | [T.D. ATF-276, 53 FR 29676, Aug. 8, 1988]
state | NJ
county | Warren
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Riegelsville Quadrangle, Pennsylvania—New Jersey, 1956 
photorevised 1968 and 1973.. 
2. Bloomsbury Quadrangle, New Jersey, 1955 
photorevised 1970.. 
3. High Bridge Quadrangle, New Jersey, 1954 
photorevised 1970.. 
4. Washington Quadrangle, New Jersey, 1954 
photorevised 1971.. 
5. Hackettstown Quadrangle, New Jersey, 1953 
photorevised 1971, photoinspected 1976.. 
6. Tranquility Quadrangle, New Jersey, 1954 
photorevised 1971.. 
7. Newton West Quadrangle, New Jersey, 1954 
photorevised 1971.. 
8. Flatbrookville Quadrangle, New Jersey—Pennsylvania, 1954 
photorevised 1971.. 
9. Blairstown Quadrangle, New Jersey—Warren Co., 1954 
photorevised 1971.. 
10. Portland Quadrangle, Pennsylvania—New Jersey, 1955 
photorevised 1984.. 
11. Belvidere Quadrangle, New Jersey—Pennsylvania, 1955 
photorevised 1984.. 
12. Bangor Quadrangle, Pennsylvania—New Jersey, 1956 
photorevised 1968 and 1973.. 
13. Easton Quadrangle, New Jersey—Pennsylvania, 1956 
photorevised 1968 and 1973..

## Boundary [src]
General.  The Warren Hills viticultural area is located in Warren County, New Jersey. The beginning point of the following boundary description is the junction of the Delaware River and the Musconetcong River, at the southern tip of Warren County 
(on the Riegelsville map). Boundary Description.  
(i) From the beginning point, the boundary goes northeastward along the Musconetcong River about 32 miles 
(on the Riegelsville, Bloomsbury, High Bridge, Washington, Hackettstown, and Tranquaility maps) to the point where it intersects the Warren County-Sessex County line; 
(ii) Then northwestward along that county line for about 10 miles 
(on the Tranquility, Newton West, and Flatbrookville maps) to Paulins Kill; 
(iii) Then generally southwestward along Paulins Kill 
(on the Flatbrookville, Blairstown and Portland maps) to the Delaware River; 
(iv) Then generally south-southwestward along the Delaware River 
(on the Portland, Belvidere, Bangor, Easton, and Reigelsville maps) to the beginning point.

**Comment by ouwxmaniac** [comment]
In progress

**Comment by davidkli** [comment]
This AVA has been checked and the boundary is good and requires no changes.
