### ISSUE TITLE
west_elks

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#237]
# AVA: West Elks (west_elks)

name | value
--- | ---
ava_id | west_elks
cfr_index | 9.172
revision | [T.D. ATF-445, 66 FR 13430, Mar. 6, 2001]
state | CO
county | Delta
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Lazear Quadrangle 
Colorado-Delta Co. 1955 (photorevised 1978.); 
2. Hotchkiss Quadrangle 
Colorado-Delta Co. 1965 (photorevised 1979.); 
3. Paonia Quadrangle 
Colorado-Delta Co. 1965 (photorevised 1979.; and 
4. Bowie Quadrangle 
Colorado-Delta Co. 1965 (photorevised 1978..

## Boundary [src]
corner common to Sections 19 and 20, Township 13 South, Range 91 West 
(T. 13 S., R. 91 W.); 
(1) The boundary proceeds east following the center subdivision lines of Sections 20 and 21 to its intersection with Colorado Highway 133; 
(2) Then northeasterly following Colorado Highway 133 to its intersection with the N-S center subdivision line of Section 14, T. 13 S., R. 91 W., near Juanita Junction; 
(3) Then south following the center subdivision line to its intersection with the North Fork of the Gunnison River; 
(4) Then southwesterly following the North Fork of the Gunnison River to its intersection with the Stewart Ditch in the extreme southern part of Section 15, T. 13 S., R. 91 W.; 
(5) Then southwesterly following the Stewart Ditch to its intersection with the section line common to Sections 21 and 28, T. 13 S., R. 91 W.; 
(6) Then east following the section line common to Sections 21 and 28 to its intersection with the 6000 foot contour; 
(7) Then southerly following the 6000 foot contour to its second intersection with the section line common to Sections 3 and 4, T. 14 S., R. 91 W., located on the Paonia, Colo. U.S.G.S. map; 
(8) Then south following the section line common to Sections 3 and 4 to its intersection with the 6200 foot contour; 
(9) Then southerly following the 6200 foot contour to its intersection with the section line common to Sections 16 and 17, T. 14 S., R. 91 W.; 
(10) Then south following the section line common to Sections 16 and 17 to the point of intersection of Sections 16, 17, 20 and 21; 
(11) Then west following the section line common to Sections 17 and 20 to the point of intersection of Sections 17, 18, 19 and 20; 
(12) Then south following the section line common to Sections 19 and 20 to the N1/16 corner common to Sections 19 and 20; 
(13) Then west following the subdivision line across Section 19 to the N1/16 corner common to Section 19, T. 14 S., R. 91 W. and Section 24, T, 14 S., R. 92 W.; 
(14) Then south following the range line between R. 91 W. and R. 92 W. to the point of intersection between Sections 19 and 30, T. 14 S., R. 91 W. and Sections 24 and 25, T. 14 S., R. 92 W.; 
(15) Then west following the section line common to Sections 24 and 25 to the point of intersection between Sections 23, 24, 25 and 26, located on the Hotchkiss, Colo. U.S.G.S. map; 
(16) Then south following the section line common to Sections 25 and 26 to the point of intersection between Sections 25, 26, 35 and 36; 
(17) Then west following the section lines common to Sections 26 and 35 and Sections 27 and 34 to the point of intersection between Sections 27, 28, 33 and 34; 
(18) Then south following the section line common to Sections 33 and 34 to the point of intersection between Sections 33 and 34, T. 14 S., R. 92 W. and Sections 3 and 4, T. 15 S., R. 92 W.; 
(19) Then west following the township line between T. 14 S. and T. 15 S. approximately three miles to the point of intersection between Section 31, T. 14 S., R. 92 W., Section 6, T. 15 S., R. 92 W., Section 1, T. 15 S., R. 93 W., and Section 36, T. 14 S., R. 93 W.; 
(20) Then south following the range line between R. 92 W. and R. 93 W. to the point of intersection between Sections 6 and 7, T. 15 S., R. 92 W. and Sections 1 and 12, T. 15 S., R. 93 W.; 
(21) Then west following the section lines common to Sections 1 and 12 and Sections 2 and 11 to its intersection with the North Fork of the Gunnison River, located on the Lazear, Colo. U.S.G.S. map; 
(22) Then westerly following the North Fork of the Gunnison River to its intersection with Big Gulch in the extreme northeastern corner of Section 6, T. 15 S., R. 93 W.; 
(23) Then northerly following Big Gulch to its intersection with the section line common to Sections 17 and 18, T. 14 S., R. 93 W.; 
(24) Then north following the section lines common to Sections 17 and 18, Sections 7 and 8, and Sections 5 and 6 to the point of intersection between Sections 5 and 6, T. 14 S., R. 93 W. and Sections 31 and 32, T. 13 S., R. 93 W.; 
(25) Then east following the township line between T. 13 S. and T. 14 S. approximately two miles to the point of intersection between Sections 3 and 4, T. 14 S., R. 93 W. and Sections 33 and 34, T. 13 S., R. 93 W.; 
(26) Then south following the section line common to Sections 3 and 4 to the point of intersection between Sections 3, 4, 9 and 10; 
(27) Then east following the section lines for approximately 6 miles to the point of intersection between Sections 3, 4, 9 and 10, T. 14 S., R. 92 W., located on the Hotchkiss, Colo. U.S.G.S. map; 
(28) Then north following the section line common to Sections 3 and 4 to the point of intersection between Sections 3 and 4, T. 14 S., R. 92 W. and Sections 33 and 34, T. 13 S., R. 92 W.; 
(29) Then east following the township line between T. 13 S. and T. 14 S. to its intersection with the Fire Mountain Canal in the southwestern corner of Section 35, T. 13 S., R. 92 W.; 
(30) Then northeasterly following the Fire Mountain Canal through the extreme northwest corner of the Paonia, Colo. U.S.G.S. map to its intersection with the section line common to Sections 29 and 30, T. 13 S., R. 91 W., located on the Bowie, Colo. U.S.G.S. map; 
(31) Then north following the section lines common to Sections 29 and 30 and Sections 19 and 20 to the   corner common to Sections 19 and 20, the point of beginning.

**Comment by ouwxmaniac** [comment]
In progress

**Comment by ouwxmaniac** [comment]
The West Elks
viticultural area is located in eastern
Delta County, Colorado. The beginning
point is found on the ‘‘Bowie
Quadrangle’’ U.S.G.S. map at the 1⁄4
corner common to Sections 19 and 20,
Township 13 South, Range 91 West (T.
13 S., R. 91 W.);
