### ISSUE TITLE
western_connecticut_highlands

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#238]
# AVA: Western Connecticut Highlands (western_connecticut_highlands)

name | value
--- | ---
ava_id | western_connecticut_highlands
cfr_index | 9.122
revision | [T.D. ATF-267, 53 FR 3747, Feb. 9, 1988]
state | CT
county | Fairfield|Hartford|Litchfield|New Haven
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Boundary [src]

(1) The beginning point is where Connecticut Route #15 
(Merritt Parkway) meets the Connecticut-New York State line near Glenville, CT, in the Town of Greenwich. 
(2) The boundary goes approximately 80 miles northerly along the Connecticut-New York State line to the northwest corner of Connecticut at the Town of Salisbury 
(Connecticut-New York-Massachusetts State line); 
(3) The boundary proceeds approximately 32 miles east along the Connecticut-Massachusetts State line to the northeast border of the Town of Hartland; 
(4) The boundary runs approximately 5 miles south along the eastern boundary of the Town of Hartland to the northeast corner of the Town of Barkhamstead 
(Litchfield-Hartford County line); 
(5) The boundary then goes south approximately 25 miles along the Litchfield-Hartford County line to the southeast corner of the Town of Plymouth 
(Litchfield-Hartford-New Haven County line); 
(6) The boundary then travels approximately 7 miles west along the Litchfield-New Haven County line to Connecticut Route #8 at Waterville in the Town of Waterbury; 
(7) The boundary proceeds approximately 25 miles south along Connecticut Route #8 to the intersection of Connecticut Route 15 
(Merritt Parkway) near Nichols in the Town of Trumbull; 
(8) The boundary travels approximately 32 miles west along Connecticut Route 15 
(Merritt Parkway) to the beginning point.

**Comment by gdmf** [comment]
Please add the "In Progress" label to this one.

**Comment by MicheleTobias** [comment]
I wanted to see if this boundary is still in progress or can I release it for the other contributors to work on?

**Comment by gdmf** [comment]
It can be released.

**Comment by Alexenia** [comment]
I would like to do this one.

**Comment by Alexenia** [comment]
Hi Michele,

On TopoView, I can't seem to find the map by the name State of Connecticut, could you let me know?

**Comment by MicheleTobias** [comment]
The state series maps aren't on TopoView unfortunately.  This is probably the map you want: https://www.loc.gov/resource/g3780.ct006368/ BUT it's not georeferenced.  I haven't been able to find a source for the state maps online and georeferenced.  So we have a couple of options.  Either (1) you can download the unreferenced one and georeference it or (2) you substitute other maps using the unreferenced one as a guide.  If you substitute maps, of course you'll keep good notes on what you used so you can put it into that part of the attribute table.

**Comment by Alexenia** [comment]
Hi Michele, I'm trying to determine the georeferencing error for the 15 ground control points that I made. The GSP table shows a 0 value for all the dx and dy pixel values. Could you let me know if there is a setting or an alternative way to see those values? Thank you.

**Comment by MicheleTobias** [comment]
You'll need to do the next step in the georeferencing process before it will calculate the errors.  You can always edit them after you do that, so don't worry about getting locked in to using what you currently have.

**Comment by Alexenia** [comment]
Ok, I have the residual errors for all the GCPs. There is only 1 point with an error above the 10 pixel error limit. To lower the error, I've moved the point which now sits on the edge of a road path.  Is that fine or should I delete that point and make a new one?

**Comment by MicheleTobias** [comment]
I would delete it.  If you are marking the center of road intersections but you have to move it to the edge to lower the error, just get rid of it and pick a different one.  The map is probably a little off in that area.

**Comment by Alexenia** [comment]
Hi Michele,

I'm filling out the attribute table, could you let me know these sections that I'm not sure about, thank you. 

1. Which [T.D. ATF-267 ####] I should use, given that the e-CFR and Federal Register Library have different [T.D. ATF-267 ####]. To see screen shots of the e-CFR and Federal Register Library, see the attached doc.

2. The last date of revision is also different between e-CFR (Feb. 9, 1988) and Federal Register Library (Feb. 8, 1988). I want to go with the e-CFR date but I want to make sure. 

2. Uses Maps Section: Please let me know if this is correct, given the used map is of CT but was created in Va.
"State of Connecticut: Base map with highways and contours, Va., 1974; Compiled in 1965."

[Western_Conn._Highlands.docx](https://github.com/UCDavisLibrary/ava/files/3135878/Western_Conn._Highlands.docx)
