### ISSUE TITLE
wild_horse_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#239]
# AVA: Wild Horse Valley (wild_horse_valley)

name | value
--- | ---
ava_id | wild_horse_valley
cfr_index | 9.124
revision | [T.D. ATF-278, 53 FR 48247, Nov. 30, 1988]
state | CA
county | Napa|Solano
within | Napa Valley\|North Coast\|Solano County\|Green Valley
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]
The appropriate map for determining the boundaries of the “Wild Horse Valley” viticultural area is one U.S.G.S. Quadrangle (7.5 Minute Series) map. It is titled Mt. George, California (1951), photorevised 1968.

## Boundary [src]

(1) The beginning point is on the section line boundary between Section 33, Range 3 West, Township 6 North and Section 4, Range 3 West, Township 5 North, Mount Diablo Range and Meridian, marked with an elevation of 1,731 feet, which is a northwest corner of the boundary between Napa and Solano Counties. 
(2) From the beginning point, the boundary runs in a north-northeasterly direction approximately .9 mile to the summit of an unnamed hill having a marked elevation of 1,804 feet; 
(3) Then northeasterly approximately .7 mile to the summit of an unnamed hill having a marked elevation of 1,824 feet; 
(4) Then south-southeasterly approximately .6 mile to the summit of an unnamed hill having a marked elevation of 1,866 feet; 
(5) Then south-southeasterly approximately .5 mile to the summit of an unnamed hill having a marked elevation of 2,062 feet; 
(6) Then southerly approximately .7 mile to the summit of an unnamed hill having a marked elevation of 2,137 feet; 
(7) Then south-southeasterly approximately .4 mile to the summit of an unnamed hill having a marked elevation of 1,894 feet; 
(8) Then southerly approximately 2.3 miles to the midpoint of the section line boundary between Sections 15 and 22, Township 5 North, Range 3 West, Mount Diablo Range and Meridian; 
(9) Then southwesterly approximately 1.3 miles to the summit of an unnamed hill having a marked elevation of 1,593 feet; 
(10) Then west-northwesterly approximately 1.2 miles to the summit of an unnamed hill, on the Napa/Solano County boundary, having a marked elevation of 1,686 feet; 
(11) Then north-northeasterly approximately 1.5 miles to the summit of an unnamed hill having a marked elevation of 1,351 feet; 
(12) Then north-northeasterly approximately 1.2 miles to the summit of an unnamed hill having a marked elevation of 1,480 feet; and 
(13) Then north-northwesterly approximately 1.0 miles to the point of beginning.

**Comment by SoominHur** [comment]
Reviewed. Corrected created date in attribute table.
