### ISSUE TITLE
arroyo_seco

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#24]
# AVA: Arroyo Seco (arroyo_seco)

name | value
--- | ---
ava_id | arroyo_seco
cfr_index | 9.59
revision | [T.D. ATF-131, 48 FR 16246, Apr. 15, 1983, as amended by T.D. TTB-49, 71 FR 34527, June 15, 2006]
state | CA
county | Monterey
within | Central Coast\|Monterey
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Greenfield, California,” 7.5 minute series, edition of 1956; 
2. “Paraiso Springs, California,” 7.5 minute series, edition of 1956; 
3. “Soledad, California,” 7.5 minute series, edition of 1955; and 
4. “Sycamore Flat, California,” 7.5 minute series, edition of 1956 
photoinspected 1972..

## Boundary [src]
The beginning point is found on the “Sycamore Flat” U.S.G.S. map at the junction of Arroyo Seco Road and the Carmel Valley Road (indicated as the Jamesburg Road on the map).
(1) Then east following Arroyo Seco Road to the southwest corner of Section 22, T. 19 S., R. 5 E. 
(2) Then east following the southern boundaries of Sections 22, 23, 24, 19, and 20 to the southeastern corner of Section 20, T. 19 S., R. 6 E. 
(3) Then northeast in a straight line for approximately 1.3 miles to the summit of Pettits Peak. 
(4) Then northeast in a straight line for approximately 1.8 miles to the point where the 400  contour line intersects the northern boundary of Section 14, T. 19 S., R. 6 E. 
(5) Then east following the 400  contour line to a point immediately west of the Reservoir within the Posa de los Ositos Land Grant. 
(6) Then following the ridge line in a northeasterly direction for approximately 7.5 miles to U.S. Highway 101 at the intersection of Underwood Road. 
(7) Then east following Underwood Road to its intersection with the Posa de los Ositos Land Grant. 
(8) Then north following the boundary of the Posa de los Ositos Land Grant to the west bank of the Salinas River. 
(9) Then northwest following the west bank of the Salinas River to the southern boundary of Section 17, T. 18 S., R. 7 E. 
(10) Then due west for approximately 2.0 miles following the southern boundary of Section 17, and continuing to U.S. Highway 101. 
(11) Then following U.S. Highway 101 in a northwesterly direction to its intersection with Paraiso Road. 
(12) Then south following Paraiso Road to the intersection with Clark Road. 
(13) Then east-northeasterly along Clark Road for approximately 1,000 feet to its intersection with an unnamed light-duty road to the south. 
(14) Then in a straight south-southeasterly line for approximately 1.9 miles to the line&#39;s intersection with the southeast corner of section 33, T18S, R6E 
(this line coincides with the unnamed light duty road for approximately 0.4 miles and then with the eastern boundaries of sections 29, 32 and 33, T18S, R6E, which mark this portion of the western boundary of the historical Arroyo Seco Land Grant). 
(15) Then straight west along the southern boundary of section 33, T18S, R6E, to its southwest corner. 
(16) Then due south following the eastern boundaries of Sections 5, 8, and 17, to Arroyo Seco Road. 
(17) Then southwest in a straight line for approximately 1.0 mile to Bench Mark 673. 
(18) Then west in a straight line for approximately 1.8 miles to Bench Mark 649. 
(19) Then northwest in a straight line for approximately 0.2 mile to the northeast corner of Section 23, T. 19 S., R. 5 E. 
(20) Then west following the northern boundaries of Section 23 and 22 to the northwest corner of Section 22, T. 19 S., R. 5 E. 
(21) Then south in a straight line for approximately 1.0 mile to the point of beginning.

**Comment by fyfangyao** [comment]
I am working on it.

**Comment by fyfangyao** [comment]
I use ““Greenfield Cali., 7.5 minute series, edition of 1956, (revised 1984),” “Paraiso Springs Cali.,7.5 minute series, edition of 1956 (revised 1984),” and ”Soledad Cali., 7.5 minute series, edition of 1955 (revised 1984)” because the approved maps don’t specify the revision years. And, I use “Sycamore Flat Cali., 7.5 minute series, edition of 1956 (revised 1977)” because I cannot find the map with the required revision year.

**Comment by fyfangyao** [comment]
I use ““Greenfield Cali., 7.5 minute series, edition of 1956, (revised 1984),” “Paraiso Springs Cali.,7.5 minute series, edition of 1956 (revised 1984),” and ”Soledad Cali., 7.5 minute series, edition of 1955 (revised 1984)” because the approved maps don’t specify the revision years.

I use “Sycamore Flat Cali., 7.5 minute series, edition of 1956 (revised 1977)” because I cannot find required the map with the required revision year.

**Comment by fyfangyao** [comment]
I use “Paraiso Springs Cali.,7.5 minute series, edition of 1956 (revised 1958)” instead of “Paraiso Springs Cali.,7.5 minute series, edition of 1956 (revised 1984).”

**Comment by MicheleTobias** [comment]
For boundary description item 6, "(6) Then following the ridge line in a northeasterly direction for approximately 7.5 miles to U.S. Highway 101 at the intersection of Underwood Road.", I think the most likely interpretation of what they meant by "ridge line" is the top of the cliff (closely spaced contour lines) between the reservoir and the intersection of the 101 and Underwood Road.  The boundary for Arroyo Seco is now in the ava folder, but let's go back and adjust that section before I close this issue.

**Comment by SoominHur** [comment]
Reviewed.
