### ISSUE TITLE
willamette_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#240]
# AVA: Willamette Valley (willamette_valley)

name | value
--- | ---
ava_id | willamette_valley
cfr_index | 9.90
revision | [T.D. ATF-162, 48 FR 54221, Dec. 1, 1983, as amended by T.D. TTB-134, 81 FR 11112, Mar. 3, 2016]
state | OR
county | Benton|Clackamas|Lane|Linn|Marion|Multnomah|Polk|Washington|Yamhill
within | 
contains | Chehalem Mountains\|Dundee Hills\|Eola-Amity Hills\|McMinnville\|Ribbon Ridge\|Yamhill-Carlton

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Vancouver,” Location Diagram NL 10-8, 1958 
revised 1974.. 
2. “Salem,” Location Diagram NL 10-11, 1960 
revised 1977.. 
3. “Roseburg,” Location Diagram NL 10-2, 1958 
revised 1970.. 
4. “Letz Creek, OR” 
revised 1984..

## Boundary [src]

(1) West along the Columbia/Multnomah County line 8.5 miles to its intersection with the Washington/Multnomah County line; 
(2) South along the Washington County line 5 miles to its intersection with the 1,000 foot contour line; 
(3) Northwest 
(15 miles due northwest) along the 1,000 foot contour line to its intersection with State Highway 47, .5 mile north of “Tophill”; 
(4) Then, due west from State Highway 47 one-quarter mile to the 1,000 foot contour line, continuing south and then southwest along the 1,000 foot contour line to its intersection with the Siuslaw National Forest 
(a point approximately 43 miles south and 26 miles west of “Tophill”), one mile north of State Highway 22; 
(5) Due south 6.5 miles to the 1,000 foot contour line on the Lincoln/Polk County line; 
(6) Continue along the 1,000 foot contour line 
(approximately 23 miles) east, south, and then west, to a point where the Polk County line is intersected by the Lincoln/Benton County line; 
(7) South along Lincoln/Benton County line, 11 miles to its intersection with the Siuslaw National Forest line; 
(8) East along the Siuslaw National Forest line six miles, and then south along the Siuslaw National Forest line six miles to State Highway 34 and the 1,000 foot contour line; 
(9) South along the 1,000 foot contour line to its intersection with Township line T17S/T18S 
(31 miles southwest, and one mile west of State Highway 126); 
(10) East along T17S/T18S 4.5 miles to Range line R6W/R7W, south along this range line 2.5 miles to the 1,000 foot contour line; 
(11) Northeast, then southeast along the 1,000 foot contour line approximately 12 miles to its intersection with the R5W/R6W range line; 
(12) South along the R5W/R6W range line approximately 0.25 mile to the intersection with the 1,000 foot contour line; 
(13) Generally southeast along the meandering 1,000 foot contour line, crossing onto the Letz Creek map, to a point on the 1,000 foot contour line located due north of the intersection of Siuslaw River Road and Fire Road; 
(14) South in a straight line approximately 0.55 mile, crossing over the Siuslaw River and the intersection of Siuslaw River Road and Fire Road, to the 1,000 foot contour line; 
(15) Generally southeast along the meandering 1,000 foot contour line, crossing onto the Roseburg, Oregon map, to the intersection of the 1,000 foot contour line with the Lane/Douglas County line; 
(16) East along the Lane/Douglas County line approximately 3.8 miles to the intersection with the 1,000 foot contour line just east of the South Fork of the Siuslaw River; 
(17) Generally north, then northeast along the 1,000 foot contour line around Spencer Butte, and then generally south to a point along the Lane/Douglas County line 0.5 mile north of State Highway 99; 
(18) South along the Lane/Douglas County line 1.25 miles to the 1,000 foot contour line; 
(19) Following the 1,000 foot contour line around the valleys of Little River, Mosby Creek, Sharps Creek and Lost Creek to the intersection of R1W/R1E and State Highway 58); 
(20) North along R1W/R1E, six miles, until it intersects the 1,000 foot contour line just north of Little Fall Creek; 
(21) Continuing along the 1,000 foot contour line around Hills Creek, up the southern slope of McKenzie River Valley to Ben and Kay Dorris State Park, crossing over and down the northern slope around Camp Creek, Mohawk River and its tributaries, Calapooia River 
(three miles southeast of the town of Dollar) to a point where Wiley Creek intersects R1E/R1W approximately one mile south of T14S/T13S; 
(22) North along R1E/R1W 7.5 miles to T12S/T13S at Cedar Creek; 
(23) West along T12S/T13S four miles to the 1,000 foot contour line; 
(24) Continuing in a general northerly direction along the 1,000 foot contour line around Crabtree Creek, Thomas Creek, North Santiam River 
(to its intersection with Sevenmile Creek), and Little North Santiam River to the intersection of the 1,000 foot contour line with R1E/R2E 
(approximately one mile north of State Highway 22); 
(25) North along R1E/R2E 
(through a small portion of Silver Falls State Park) 14 miles to T6S/T7S; 
(26) East along T6S/T7S six miles to R2E/R3E; 
(27) North along R2E/R3E six miles to T5S/T6S; 
(28) Due northeast 8.5 miles to the intersection of T4S/T5S and R4E/R3E; 
(29) East along T4S/T5S six miles to R4E/R5E; 
(30) North along R4E/R5E six miles to T3S/T4S; 
(31) East along T3S/T4S six miles to R5E/R6E; 
(32) North along R5E/R6E 10.5 miles to a point where it intersects the Mount Hood National Forest boundary 
(approximately three miles north of U.S. Highway 26); 
(33) West four miles and north one mile along the forest boundary to the 1,000 foot contour line 
(just north of Bull Run River); 
(34) North along the 1,000 foot contour line, into Multnomah County, to its intersection with R4E/R5E; 
(35) Due north approximately three miles to the Oregon/Washington State line; and 
(36) West and then north, 34 miles, along the Oregon/Washington State line to the beginning point.

**Comment by KyleWSmith** [comment]
Please tag Willamette Valley as "In Progress". Thanks!

**Comment by elistockwell** [comment]
Matching border to Tualatin Hills, uses newer map so it will probably look wrong on the old one for anyone doing quality control.
