### ISSUE TITLE
willcox

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#241]
# AVA: Willcox (willcox)

name | value
--- | ---
ava_id | willcox
cfr_index | 9.259
revision | [T.D.TTB-143, 81 FR 62628, Sept. 12, 2016]
state | AZ
county | Cochise|Graham
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Fort Grant, AZ, 1996; 
2. West of Greasewood Mountain, AZ, 1996; 
3. Greasewood Mountain, AZ, 1996; 
4. Willcox North, AZ, 1996; 
5. Railroad Pass, Ariz., 1979; 
6. Simmons Peak, AZ, 1996; 
7. Dos Cabezas, AZ, 1996; 
8. Pat Hills North, Ariz., 1974; 
9. Pat Hills South, Arizona, 1986 provisional edition; 
10. Sulphur Hills, AZ, 1996; 
11. Pearce, AZ., 1996; 
12. Turquoise Mountain, AZ, 1996; 
13. Black Diamond Peak, AZ, 1996; 
14. Cochise Stronghold, AZ, 1996; 
15. Cochise, AZ, 1996; 
16. Red Bird Hills, AZ, 1996; 
17. Steele Hills, AZ, 1996; 
18. Square Mountain, AZ, 1996; 
19. Muskhog Mountain, AZ, 1996; 
20. Reiley Peak, AZ, 1996; and 
21. Sierra Bonita Ranch, Ariz., 1972.

## Boundary [src]

(1) The beginning point is on the Fort Grant map at the intersection of State Highway 266 and an unnamed light-duty road known locally as Curtis Parkway, in Fort Grant, section 35, T9S/R23E. From the beginning point, proceed south-southeast in a straight line approximately 20.4 miles, crossing over the West of Greasewood Mountain and the Greasewood Mountain map and onto the Willcox North map, to the intersection of three unnamed light-duty roads known locally as Porters Ranch Road, East Saguaro Road, and North Circle I Road, near benchmark 
(BM) 4,243 on the Willcox North map, section 36, T12S/R24E; then 
(2) Proceed east in a straight line approximately 5 miles to Interstate Highway 10 near the community of Raso, section 1, T13S/R25E; then 
(3) Proceed south in a straight line approximately 0.8 mile to the 4,400-foot elevation contour, section 1, T13S/R25E; then 
(4) Proceed southwesterly along the 4,400-foot elevation contour around the west end of the Dos Cabezas Mountains and continue southeasterly along the 4,400-foot elevation contour for a total of approximately 13.3 miles, crossing over the Railroad Pass map and onto the Simmons Peak map, to State Highway 186 on the Simmons Peak map, section 28, T14S/R26E; then 
(5) Proceed south-southeast in a straight line approximately 15.8 miles, crossing over the Dos Cabezas map and onto the Pat Hills North map, to the intersection of the 4,700-foot elevation contour and an unnamed light-duty road known locally as East Creasey Ranch Road on the Pat Hills North map near BM 4,695, section 21, T16S/R28E; then 
(6) Proceed southerly along the 4,700-foot elevation contour approximately 10.6 miles, crossing onto the Pat Hills South map, to an unnamed light-duty road known locally as East Uncle Curtis Lane, section 7, T18S/R28 E; then 
(7) Proceed west along East Uncle Curtis Lane approximately 0.5 mile to an unnamed light-duty road known locally as South Single Tree Lane near the marked 4,664-foot elevation point, section 7, T18S/R28E; then 
(8) Proceed south along South Single Tree Lane approximately 0.5 mile to State Highway 181, section 7, T18S/R28E; then 
(9) Proceed west along State Highway 181 approximately 9.9 miles, crossing onto the Sulphur Hills map, to State Highway 191, section 10, T18S/R26E; then 
(10) Proceed north-northeasterly, then west, along State Highway 191 approximately 4.8 miles, crossing onto the Pearce map, to an unnamed light-duty road known locally as Kansas Settlement Road, near BM 4,327, section 36, T17S/R25E; then 
(11) Proceed southwest in a straight line approximately 8.9 miles, crossing over the Turquoise Mountain map and onto the Black Diamond Peak map, to the southeastern-most corner of the boundary of the Coronado National Forest on the Black Diamond Peak map, section 35, T18S/R24 E; then 
(12) Proceed north along the boundary of the Coronado National Forest approximately 2 miles to the marked 4,821-foot elevation point, section 26, T18S/R24E; then 
(13) Proceed north-northwest in a straight line approximately 13 miles, crossing over the Cochise Stronghold map and onto the Cochise map, to the northeastern corner of the boundary of the Coronado National Forest at the marked 4,642 elevation point on the Cochise map, section 26, T16S/R23E; then 
(14) Proceed north-northwest in a straight line approximately 1.2 miles to the intersection of the 4,450-foot elevation contour and an unnamed secondary highway known locally as West Dragoon Road, section 23, T16S/R23E; then 
(15) Proceed north in a straight line approximately 1.3 miles to the 4,400-foot elevation contour, section 11, T16S/R23E; then 
(16) Proceed generally northerly along the 4,400-foot elevation contour approximately 10 miles, crossing onto the Red Bird Hills map, to Interstate Highway 10, section 3, T15S/R23E; then 
(17) Proceed north-northwest in a straight line approximately 5.8 miles, crossing onto the Steele Hills map, to the intersection of the 4,600-foot elevation contour and an unnamed light-duty road known locally as West Airport Road, section 7, T14S/R23E; then 
(18) Proceed east-northeasterly, then easterly, then northerly, then easterly along West Airport Road approximately 7.2 miles, crossing back onto the Red Bird Hills map and then onto the Square Mountain map, to the 4,240-foot elevation contour east of BM 4,264, section 6, T14S/R24E; then 
(19) Proceed north-northwest in a straight line approximately 20.5 miles, crossing over the Muskhog Mountain and Reiley Peak maps and onto the Sierra Bonita Ranch map, to the intersection of two unnamed light-duty roads known locally as West Ash Creek Road and South Wells Road, near BM 4,487 on the Sierra Bonita Ranch map, section 3, T11S/R22E; then 
(20) Proceed generally northerly along South Wells Road to BM 4,502, then continuing northerly along the western fork of the road for a total of approximately 7.7 miles to an unnamed light-duty road known locally as Bonita Aravaipa Road, section 27, T9S/R22E; then 
(21) Proceed east in a straight line approximately 8.2 miles, crossing onto the Fort Grant map, to the beginning point.

**Comment by MicheleTobias** [comment]
I'm working on this one.
