### ISSUE TITLE
willow_creek

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#242]
# AVA: Willow Creek (willow_creek)

name | value
--- | ---
ava_id | willow_creek
cfr_index | 9.85
revision | [T.D. ATF-141, 48 FR 37376, Aug. 18, 1983]
state | CA
county | Humboldt|Trinity
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]
“Willow Creek Quadrangle,” California, U.S.G.S. 15 minute series (1952).

## Boundary [src]
The Willow Creek viticultural area is located within portions of Humboldt and Trinity Counties, California. From the point of beginning where the 1,000-foot contour line intersects Kirkham Creek (directly north of section 19, T.7 N./R.5E.), beginning in a southerly direction, the boundary line the 1,000-foot contour line to;
(1) The point of intersection between the 1,000-foot contour line and the north section line of section 27, T.6N./R.5E.; 
(2) Then in a straight, north easterly line to the point of intersection between the 1,000-foot contour line and the east section line of section 13, T.6N./R.5E.; 
(3) Then in a straight, northwesterly line to the point of intersection between the 1,000-foot contour line and the north section line of section 11, T.6N./R.5E.; 
(4) Then in a straight, south-southwesterly line to the point of intersection between the 1,000-foot contour line and the east section line of section 15, T.6N./R.5E.; 
(5) Then following the 1,000-foot contour line, beginning in a westerly direction, to the point of intersection between the 1,000-foot contour line and Coons Creek; 
(6) Then in a straight, westerly line to the point of beginning.

**Comment by MicheleTobias** [comment]
The 15 minute quads are on topoView in the 63k section, however, the projection file is not valid and I'm having a hard time matching it with a known projection because it's just labeled as "polyconic" with parameters that aren't working out.  http://prj2epsg.org/ can't identify the projection from the .prj either.

**Comment by MicheleTobias** [comment]
ArcMap can read the .prj as it comes from the USGS... investigating more potential work-arounds.
