### ISSUE TITLE
wisconsin_ledge

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#243]
# AVA: Wisconsin Ledge (wisconsin_ledge)

name | value
--- | ---
ava_id | wisconsin_ledge
cfr_index | 9.224
revision | [T.D. TTB-102, 77 FR 16675, Mar. 22, 2012]
state | WI
county | Brown|Calumet|Dodge|Door|Fond du Lac|Kewaunee|Manitowoc|Outagamie|Ozaukee|Sheboygan|Washington
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Door County, Wisconsin, 1986; 
2. Kewaunee County, Wisconsin, 1985; 
3. Manitowoc County, Wisconsin, 1986; 
4. Sheboygan County, Wisconsin, 1986; 
5. Ozaukee County, Wisconsin, 1986; 
6. Washington County, Wisconsin, 1986; 
7. Dodge County, Wisconsin, 1986; 
8. Fond du Lac County, Wisconsin, 1986; 
9. Calumet County, Wisconsin, 1986; 
10. Outagamie County, Wisconsin, 1985; and 
11. Brown County, Wisconsin, 1984.

## Boundary [src]

(1) The beginning point is shown on the Door County map and is located at the northern end of the Door Peninsula at the point where the R28E and R29E common boundary line intersects with the Lake Michigan shoreline at Gills Rock in Hedgehog Harbor. From the beginning point, proceed easterly along the Lake Michigan shoreline to Northport and then continue southerly along the meandering shoreline, passing in succession over the Kewaunee, Manitowoc, and Sheboygan County maps and onto the Ozaukee County map to the intersection of the Lake Michigan shoreline with a line drawn as an easterly extension of County Highway T 
(locally known as Lakefield Road), east of Cedarburg; then 
(2) Proceed west on County Highway T through Cedarburg, crossing onto the Washington County map, passing over the North Western railroad single track, and continuing to the intersection of County Highway T with U.S. Route 45; then 
(3) Proceed north on U.S. Route 45 to the intersection of U.S. Route 45 with State Road 60, south of Hasmer Lake; then 
(4) Proceed westerly on State Road 60, crossing onto the Dodge County map, to the intersection of State Road 60 with State Road 26 at Casper Creek, north-northwest of Clyman Junction; then 
(5) Proceed northerly on State Road 26 to the intersection of State Road 26 with U.S. Route 151, north of Plum Creek in Chester Township; then 
(6) Proceed northerly on U.S. Route 151, passing through Waupun onto the Fond du Lac County map, and continue northeasterly into the City of Fond du Lac to the point where U.S. Route 151 turns east, and, from that point, continue north in a straight line to the south shore of Lake Winnebago in Lakeside Park; then 
(7) Proceed easterly along the southern shoreline of Lake Winnebago, then northerly along the eastern shoreline, crossing onto the Calumet County map, to the intersection of the shoreline with a line drawn as a southerly extension of County Highway N at Highland Beach in Harrison Township; then 
(8) Proceed north on County Highway N, crossing onto the Outagamie County map, to the intersection of County Highway N with the Fox River; then 
(9) Proceed northeasterly 
(downstream) along the Fox River, crossing onto the Brown County map, until the Fox River meets the southern shoreline of Green Bay; and then 
(10) Proceed northeasterly along the eastern shoreline of Green Bay, passing over the Kewaunee County map and onto the Door County map, to Sister Bay, where the eastern shoreline of Green Bay becomes the shoreline of Lake Michigan, and then continue northeasterly along the shoreline of Lake Michigan, returning to the beginning point.

**Comment by ouwxmaniac** [comment]
In Progress

**Comment by MicheleTobias** [comment]
Yikes!  Which two maps is it?  I'll pull them down and see what I can figure out.  I suspect QGIS didn't read the projection file correctly for one of them, which happens occasionally.

**Comment by ouwxmaniac** [comment]
I'm using 100k Fond-du-lac 1980 and 100k Oconomowoc 1981. The docs say to use the county specific maps, but the USGS site doesn't do county based maps as far as I can tell.

**Comment by MicheleTobias** [comment]
It looks like the georeferencing for one of the maps is just wrong.  If you know which is it, report it it with the "fix" button in the TopoView record for that map.  I got the same result as you after having to do some work-arounds to get it it to load.  So I guess we'll have to pick a different map or maps.  The county maps are hard to find and I haven't seen them in the TopoView interface either.  The Madison, WI 1:250000 might work instead, or you might need to use a handful of 1:24000 maps instead.  It's completely fine to use different maps than the description uses when we can't find the cited ones.  Just make sure to put the map names in the "used maps" section of the attribute table.

**Comment by ouwxmaniac** [comment]
Great, I'll do that. Thanks Michele.

**Comment by alisonsnwong** [comment]
Reviewed this AVA. The 1:100,000 scale maps used by the approved maps were still not working. I removed unnecessary maps & added missing maps that were not mentioned in the used_maps section. I also updated the border of the existing ava to be more precise.
