### ISSUE TITLE
yadkin_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#244]
# AVA: Yadkin Valley (yadkin_valley)

name | value
--- | ---
ava_id | yadkin_valley
cfr_index | 9.174
revision | [T.D. ATF-485, 67 FR 72839, Dec. 9, 2002]
state | NC
county | Davidson|Davie|Forsythe|Stokes|Surrey|Wilkes|Yadkin
within | 
contains | Swan Creek

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Winston-Salem, N.C.; VA; Tenn. 
1953, Limited Revision 1962., and, 
2. Charlotte, North Carolina; South Carolina. 
1953, Revised 1974..

## Boundary [src]

(1) On the Winston-Salem, N.C.; VA; Tenn. map, the beginning point is 3.6 miles west of the northeast corner of Surry County on the Surry County and North Carolina/Virginia state line at the crest of Slate Mountain. From the beginning point, proceed southeast in a straight line approximately 6.5 miles to the intersection of the Surry/Stokes County line and State Route 89; 
(2) Then bear southeast in a straight line for approximately 9 miles to the line&#39;s intersection with State Route 66 in the village of Gap 
(between Sauratown and Hanging Rock Mountains); 
(3) Then bear south, following State Route 66 for approximately 9 miles to intersection of State Route 66 and U.S. Route 52; 
(4) Then, for approximately 9.5 miles, follow U.S. Route 52 south through Rural Hall and Stanelyville, to the intersection of the Southern Railway track and U.S. Route 52; 
(5) Then bear southerly for approximately 2 miles, following the Southern Railway track to where it intersects with U.S. Route 52 in Winston-Salem; 
(6) Then follow U.S. Route 52 south for approximately 19.5 miles, crossing on to the Charlotte, North Carolina; South Carolina map, to its intersection with Interstate 85 at Lexington; 
(7) Then, follow Interstate 85 southwest for approximately 11 miles to the Yadkin River and bear northwest approximately 4.5 miles along the Yadkin River to the mouth of the South Yadkin River; 
(8) Follow the South Yadkin River upstream in a generally northwest direction approximately 3.5 miles to its intersection with U.S. Route 601; 
(9) Then continue in a northerly direction, following U.S. Route 601 through the town of Mocksville, onto the Winston-Salem, N.C.; VA; Tenn. map approximately 20 miles to the Davie/Yadkin County line; 
(10) Then, following a series of county lines, continue west along the Yadkin/Davie County line to the Yadkin/Davie/Iredell County line intersection, then follow the Yadkin/Iredell County line to the Yadkin/Iredell/Wilkes County line intersection, then follow the Iredell/Wilkes County line to the Iredell/Wilkes/Alexander County line intersection, then follow the Wilkes/Alexander County line to the Wilkes/Alexander/Caldwell County line intersection; 
(11) Then bear northwesterly along the Wilkes/Caldwell County line, to the Wilkes/Caldwell/Watauga County intersection; 
(12) Then bear northerly along the Wilkes/Watauga County line to the intersection of the Wilkes/Watauga/Ashe County lines; 
(13) Then bear generally northeasterly along the Wilkes/Ashe County line, to the Wilkes/Ashe/Alleghany County line intersection; 
(14) Then bear generally easterly along the Wilkes/Alleghany County line to the Wilkes/Alleghany/Surry County line intersection; 
(15) Then bear northerly along Alleghany/Surry County line to the intersection of the Alleghany/Surry County line and the North Carolina/Virginia border; 
(16) Then bear east along the North Carolina/Virginia State line approximately 22.5 miles, returning to the point of beginning 3.6 miles west of the northeast corner of Surry County.

**Comment by ouwxmaniac** [comment]
In Progress

**Comment by MicheleTobias** [comment]
Fantastic!  I've also added your github handle to our contributors page.  If you'd like me to list a different name, just let me know.  And thank you for your contributions!

**Comment by davidkli** [comment]
This AVA has been checked and the boundary is good. No edits needed to be made.
