### ISSUE TITLE
yakima_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#245]
# AVA: Yakima Valley (yakima_valley)

name | value
--- | ---
ava_id | yakima_valley
cfr_index | 9.69
revision | [T.D. ATF-128, 48 FR 14375, Apr. 4, 1983]
state | WA
county | Benton|Yakima
within | Columbia Valley
contains | Rattlesnake Hills\|Red Mountain\|Snipes Mountain

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Walla Walla, Washington,” scaled 1:250,000, edition of 1953, limited revision 1963; and 
2. “Yakima, Washington,” scaled 1:250,000, edition of 1958, revised 1971.

## Boundary [src]

(1) Then east following the crest of the Rattlesnake Hills across Elephant Mountain, Zillah Peak, High Top 
(elevation 3031 feet), and an unnamed mountain 
(elevation 3629 feet) to the Bennett Ranch; 
(2) Then due east approximately 0.2 mile to the boundary of the Hanford Atomic Energy Commission Works; 
(3) Then southeast following the boundary of the Hanford AEC Works along the Rattlesnake Hills to the Yakima River; 
(4) Then southeast across the top of Red Mountain to the peak of Badger Mountain; 
(5) Then due south for approximately 4.9 miles to the 1000 foot contour line immediately south of the Burlington Northern Railroad 
(indicated on map as the Northern Pacific Railroad); 
(6) Then west following the 1000 foot contour line to its intersection with U.S. Highway 97 immediately west of Hembre Mountain; 
(7) Then west following the Toppenish Ridge, across an unnamed mountain 
(elevation 2172 feet), an unnamed mountain 
(elevation 2363 feet), to the peak of Toppenish Mountain 
(elevation 3609 feet); 
(8) Then northwest in straight line for approximately 9.3 miles to the lookout tower at Fort Simcoe Historical State Park; 
(9) Then north in a straight line for approximately 11.7 miles to an unnamed peak, 
(elevation 3372 feet); and 
(10) Then east following Ahtanum Ridge, crossing unnamed peaks of 2037 feet elevation, 2511 feet elevation, 2141 feet elevation, to the Wapato Dam at the point of beginning.

**Comment by alisonsnwong** [comment]
Checked! Performed minor boundary edits
