### ISSUE TITLE
yamhill_carlton

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#246]
# AVA: Yamhill-Carlton (yamhill_carlton)

name | value
--- | ---
ava_id | yamhill_carlton
cfr_index | 9.183
revision | [T.D. TTB-20, 69 FR 71374, Dec. 9, 2004, as amended by T.D. TTB-87, 75 FR 67618, Nov. 3, 2010]
state | OR
county | Washington|Yamhill
within | Willamette Valley
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Gaston Quadrangle, Oregon, 1956, revised 1992; 
2. Laurelwood Quadrangle, Oregon, 1956, revised 1992; 
3. Dundee Quadrangle, Oregon, 1956, revised 1993; 
4. Carlton Quadrangle, Oregon—Yamhill Co., 1957, revised 1992; 
5. Fairdale Quadrangle, Oregon-Yamhill Co., 1979; 
6. McMinnville Quadrangle, Oregon—Yamhill Co., 1957, revised 1992; 
7. Muddy Valley Quadrangle, Oregon—Yamhill Co., 1979, revised 1992; and 
8. Turner Creek Quadrangle, Oregon, 1979.

## Boundary [src]

(1) The point of beginning is on the Gaston map in the village of Gaston at the intersection of Gaston Road East 
(E. Main Street within Gaston) and the 200-foot elevation line, approximately 225 feet west of State Route 47, section 49, T1S, R4W. From this beginning point, proceed southerly and then southeasterly about 8.15 miles along the meandering 200-foot elevation line 
(crossing to and from the Laurelwood map in sections 12 and 13, T2S, R4W, and then returning to the Laurelwood map) to the 200-foot elevation line&#39;s intersection with Spring Hill Road, section 58, T2S, R3W 
(Laurelwood Quadrangle); then 
(2) Proceed south 1.1 miles on Spring Hill Road, which becomes North Valley Road at Laughlin Road, crossing onto the Dundee map, to the road&#39;s intersection with the 200-foot elevation line, section 30, T2S, R3W 
(Dundee Quadrangle); then 
(3) Proceed northerly then southerly for approximately 5 miles along the 200-foot elevation line, crossing over to and back from the Laurelwood map, to the 200-foot elevation line&#39;s intersection with State Route 240, section 47, T3S, R3W 
(Dundee Quadrangle); then 
(4) Proceed straight west for 0.2 mile on State Route 240 to its intersection with Kuehne Road at the 207-foot benchmark, section 47, T3S, R3W 
(Dundee Quadrangle); then 
(5) Proceed southerly for about 1.9 miles on Kuehne Road to its intersection with Abbey Road, section 50, T3S, R3W 
(Dundee Quadrangle); then 
(6) Proceed southerly 1.4 miles on Abbey Road to its intersection with the 200-foot elevation line, north of the 174-foot elevation point, section 52, T3S, R3W 
(Dundee Quadrangle); then 
(7) Proceed southwesterly for about 2.1 miles along the meandering 200-foot elevation line to Lafayette Cemetery on the Carlton map in section 1, T4S, R4W, and turning northerly along the 200-foot elevation line, continue along the elevation line for about 6 miles, crossing to and from the Dundee map, to the 200-foot elevation line&#39;s intersection with Stag Hollow Road, north of Hendricks Road and 190-foot elevation point, section 24, T3S, R4W 
(Carlton Quadrangle); then 
(8) Continue westerly along the meandering 200-foot elevation line, turning northeasterly as the elevation line passes through the Carlton Lakes State Wildlife Refuge, then westerly as the elevation line crosses Stag Hollow Creek in section 47, T3S, R4W, then southerly as the elevation line crosses the North Yamhill River on the Fairdale map in section 43, T2S, R5W, then, returning to the Carlton map, continue southerly on the 200-foot elevation line to its intersection with Meadow Lake Road near the southwest corner of section 55, T3S, R4W 
(Carlton Quadrangle); 
(9) Continue westerly along the meandering 200-foot elevation line, crossing onto the Fairdale map, to the elevation line&#39;s intersection with the 123°17  longitude line 
(north of Panther Creek) in the western extension of section 22, T3S, R5W 
(Fairdale Quadrangle); then 
(10) Proceed 0.2 mile straight south along the 123°17  longitude line, crossing Panther Creek, to the line&#39;s intersection with the 200-foot elevation line south of the creek in the western extension of section 22, T3S, R5W 
(Fairdale Quadrangle); then 
(11) Proceed easterly and then southeasterly along the meandering 200-foot elevation line, crossing onto the Carlton map, then the McMinnville map, to the elevation line&#39;s third intersection with an unnamed light-duty road, southwest of the Henderson Benchmark in section 87, T4S, R4W 
(McMinnville Quadrangle); 
(12) Continue southerly and then westerly along the meandering 200-foot elevation line, crossing onto the Muddy Valley map, to the elevation line&#39;s intersection with Baker Creek Road 
(very near Baker Creek Road&#39;s intersection with High Heaven Road) in section 54, T4S, R5W 
(Muddy Valley Quadrangle); then 
(13) Proceed west-southwest for 0.8 mile on Baker Creek Road to its intersection with the 123°17  longitude line in Happy Valley, section 54, T4S, R5W 
(Muddy Valley Quadrangle); then 
(14) Proceed straight north 13.4 miles on the 123°17  longitude line, passing through the Fairdale map and crossing onto the Turner Creek map, to the longitude line&#39;s intersection with the 1,000-foot elevation line in the northwestern quadrant of section 10, T2S, R5W, approximately one mile diagonally northwest of the footbridge in Menefee Park 
(Turner Creek Quadrangle); then 
(15) Proceed easterly and then northerly for 4.1 miles along the meandering 1,000-foot elevation line to its intersection with the Washington-Yamhill County line at northern boundary of section 3, T2S, R5W 
(also the common T1S/T2S boundary line) 
(Turner Creek Quadrangle); then 
(16) Proceed straight east 3.9 miles along the Washington-Yamhill County line, crossing onto the Gaston map, to the county line&#39;s intersection with South Road, just east of Mt. Richmond Road, section 60, T2S, R4W 
(Gaston Quadrangle); then 
(17) Proceed east-northeast for 1.8 miles on South Road to its intersection with the 200-foot elevation line, 0.3 mile west of the Gaging Station, section 34, T1S, R4W 
(Gaston Quadrangle); then 
(18) Proceed easterly 1.9 miles along the 200-foot elevation line and return to the beginning point within the village of Gaston. 
(d) From February 7, 2005, until December 2, 2010, the name of this viticultural area was “Yamhill-Carlton District”. Effective December 3, 2010, this viticulture area is named “Yamhill-Carlton”. Existing certificates of label approval showing “Yamhill-Carlton District” as an appellation of origin are revoked by operation of this regulation on December 3, 2012.

**Comment by ccohn2** [comment]
I can contribute on this one

**Comment by MicheleTobias** [comment]
@ccohn2 , we're happy to have your contribution, bu unless you are affiliated with  UCSB, I'd like you to pick a different AVA to work on.

**Comment by MicheleTobias** [comment]
Thanks!  Look for one that doesn't have a UC label.  UCSB is doing Oregon, Washington, and Idaho.

**Comment by kylebillings** [comment]
Hey—I've got the boundaries for Yamhill-Carlton ready to contribute. Do I need any sort of permissions before creating a pull request?

**Comment by MicheleTobias** [comment]
Thanks!  That's great news!  Anyone should be able to send a pull request.  Give it a try and if you run into any problems, let me know.
