### ISSUE TITLE
york_mountain

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#247]
# AVA: York Mountain (york_mountain)

name | value
--- | ---
ava_id | york_mountain
cfr_index | 9.80
revision | [T.D. ATF-143, 48 FR 38463, Aug. 24, 1983, as amended by T.D. ATF-249, 52 FR 5959, Feb. 27, 1987]
state | CA
county | San Luis Obispo
within | Central Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Boundary [src]

(1) From the beginning point at the northwest corner of the York Mountain Quadrangle map where the Dover Canyon Jeep Trail and Dover Canyon Road intersect, proceed east along Dover Canyon Road 1.5 miles to the western boundary line of Rancho Paso de Robles; 
(2) Follow the western boundary line of Rancho Paso de Robles southwest 6.0 miles to where the boundary joins Santa Rita Creek; 
(3) Turn right at Santa Rita Creek and follow the creek 5 miles to where the waters of Dover Canyon and Santa Rita Creek meet; and 
(4) Then proceed north along Dover Canyon Creek to its intersection with Dover Canyon Road, then following Dover Canyon Road 
(which becomes Dover Canyon Jeep Trail) back to the point of beginning.

**Comment by SoominHur** [comment]
Reviewed.
