### ISSUE TITLE
yorkville_highlands

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#248]
# AVA: Yorkville Highlands (yorkville_highlands)

name | value
--- | ---
ava_id | yorkville_highlands
cfr_index | 9.159
revision | [T.D. ATF-397, 63 FR 16904, Apr. 7, 1998]
state | CA
county | Mendocino
within | Mendocino\|North Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Gube Mountain, Calif., provisional edition 1991; 
2. Big Foot Mountain, Calif., provisional edition 1991; 
3. Cloverdale, Calif., 1960, photoinspected 1975; 
4. Ornbaun Valley Quadrangle, Calif., provisional edition, 1991; 
5. Yorkville, Calif., provisional edition, 1991; 
6. Hopland, Calif., 1960, photoinspected 1975.

## Boundary [src]

(1) The beginning point is Benchmark 680, located in Section 30, T. 12 N., R. 13 W., on the Ornbaum Valley quadrangle map; 
(2) From the beginning point, the boundary proceeds in a straight line in a northeasterly direction to a point intersecting the North Fork of Robinson Creek and the Section 20, T. 13 N., R. 13 W.; 
(3) The boundary then proceeds in a straight line in a southeasterly direction to the summit of Sanel Mountain, located at the southeast corner of Section 30, T. 13 N., R. 12 W., on the Yorkville quadrangle map; 
(4) The boundary then proceeds in a straight line in a southeasterly direction until it reaches the southeast corner of Section 15, T. 12 N., R 11 W., on the Hopland quadrangle map; 
(5) The boundary then proceeds south, following the eastern boundaries of Sections 22 and 27, T. 12 N., R 11 W., until it reaches the Mendocino-Sonoma County line on the Cloverdale quadrangle map; 
(6) The boundary then follows the Mendocino-Sonoma county line west, south and west until it reaches the southwest corner of Section 32, T. 12 N., R. 11 W.; 
(7) The boundary then diverges from the county line and proceeds in a northwesterly direction, traversing the Big Foot Mountain quadrangle map, until it reaches the southwest corner of Section 5, T. 12 N., R. 13 W. on the Ornbaun Valley quadrangle map; 
(8) The boundary proceeds in a straight line in a northerly direction until it reaches the beginning point at Benchmark 680.

**Comment by SoominHur** [comment]
Reviewed.
- Edit created date in the attribute table.
