### ISSUE TITLE
atlas_peak

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#25]
# AVA: Atlas Peak (atlas_peak)

name | value
--- | ---
ava_id | atlas_peak
cfr_index | 9.140
revision | [T.D. ATF-320, 57 FR 2681, Jan. 22, 1992]
state | CA
county | Napa
within | Napa Valley\|North Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Yountville, Calif.,” 7.5 minute series, edition of 1951, 
photorevised 1968.; and 
2. “Capell Valley, Calif.,” 7.5 minute series, edition of 1951, 
photorevised 1968..

## Boundary [src]
The Atlas Peak viticultural area is located in Napa County, California. It lies entirely within the Napa Valley viticultural area. The beginning point is Haystack (peak) found in section 21, T. 7 N., R. 4 W. on the “Yountville” U.S.G.S. map;
(1) From the beginning point, the boundary proceeds south in a straight line approximately 0.5 miles, to the highest point of an unnamed peak of 1443 feet elevation on the boundary of sections 21 and 28, T. 7 N., R. 4 W.; 
(2) Then southeast in a straight line approximately one mile to an unnamed pass with an elevation of 1485 feet, located on Soda Canyon Road; 
(3) Then easterly in a straight line approximately 0.5 miles to an unnamed peak of 2135 feet elevation; 
(4) Then in a generally southeasterly direction, as a series of five straight lines connecting the highest points of unnamed peaks with elevations of 1778, 2102, 1942, 1871 and 1840 feet, ending in the center of section 2, T. 6 N., R. 4 W.; 
(5) Then southeast in a straight line approximately 1.8 miles to the highest point of an unnamed peak of 1268 feet elevation in section 12, T. 6 N., R. 4 W. on the Capell Valley U.S.G.S. map; 
(6) Then east-southeast in a straight line approximately 1.1 miles to the point where an unnamed tributary stream enters Milliken Creek, immediately south of the Milliken Reservoir in section 7, T. 6 N., R. 3 W.; 
(7) Then following the unnamed stream east-northeast approximately 0.5 miles to its source; 
(8) Then northeast in a straight line approximately 0.5 miles, through the highest point of an unnamed peak of 1846 feet elevation, to the 1600 foot contour line in the eastern portion of section 8, T. 6 N., R. 3 W.; 
(9) Then following the 1600 foot contour line generally north and west for approximately 10 miles, to the point of intersection with the boundary line between sections 12 and 13, T. 7 N., R. 4 W. on the Yountville U.S.G.S. map; 
(10) Then following the section boundary line west approximately 1.1 miles to the intersection with an unnamed, unimproved road; 
(11) Then northwest in a straight line approximately 0.7 miles to the highest point of an unnamed peak of 2114 feet elevation, located in section 10, T. N., R. 4 W.; 
(12) Then northwest in a straight line approximately 0.7 miles to the highest point of an unnamed peak of 2023 feet elevation, located in section 10, T. N., R. 4 W.; 
(13) Then southwest in a straight line approximately 2.2 miles to Haystack 
(peak), the point of beginning.

**Comment by SoominHur** [comment]
Reviewed.
- (7) Add nodes "following the unnamed stream ... to its source" because the line was in straight.
- edited created date in attribute table
