### ISSUE TITLE
augusta

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#26]
# AVA: Augusta (augusta)

name | value
--- | ---
ava_id | augusta
cfr_index | 9.22
revision | 
state | MO
county | Saint Charles
within | Ozark Mountain
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c

**Comment by Alexenia** [comment]
Hi Michele,

I would like to do this one, please let me know.

**Comment by MicheleTobias** [comment]
Enjoy!  I hope this one is easier than the last one!

**Comment by MicheleTobias** [comment]
Hi @Alexenia! Are you still working on this AVA or have you moved on to other things?  One of our partner schools has this one in their dataset they want to contribute, but I want to make sure you didn't have it finished somewhere on your computer.

**Comment by Alexenia** [comment]
Hi Michele,

Sorry for not getting back to you earlier. Thank you for closing #26. 

Alex

P.S. I’m doing well and still applying to jobs left and right. I hope to get one as soon as possible. Thank you for the all the learning/professional opportunities, without them I would feel a lot more anxious. I’m looking forward to telling you which job I get.  Thank you so much Michele!
