### ISSUE TITLE
Updating a standard google Map.

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#269]
It would be nice for us to be able to maintain a consistent google map for this project output.  I have started that process with the [Google Map](https://drive.google.com/open?id=10cLnLW6aBCx8xLd7WM0SfVFPDlA&usp=sharing). 

I've divided the avas.geojson file into two components, the completed AVA's and the TBDs.   Right now, I'm maintaining that file by hand, with the following commands.  This depends on the created tag being properly filled out.

```bash
ogr2ogr -f KML -where 'created is not null' -nln 'American Viticulture Areas' avas.kml avas.geojson
ogr2ogr -f KML -where 'created is null' -nln 'To Be Completed' tbd.kml avas.geojson
```

Then I upload these two layers and remove the old ones.  I then add the styling.  Right now you can see that we have run out of colors for the default categorical styling from Google Maps. 

We could come up with a more sophisticated setup.  I have previously written a more complete KML making tool which we  could use to create a single KML with a few folders.  That would require a bit more complicated conversion.  Probably geojson->postgis->kml.

**Comment by qjhart** [comment]
@MicheleTobias I'll just delete the starting example I made above?

**Comment by MicheleTobias** [comment]
I think at some point, making a map beyond the one that GitHub makes would be helpful, but maybe Google Maps isn't the right solution any more.  I'm thinking a leaflet map that pulls data directly from the repo so we don't have to update it.  If you want to delete your Google Map, that's fine.  It's up to you.
