### ISSUE TITLE
ballard_canyon

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#27]
# AVA: Ballard Canyon (ballard_canyon)

name | value
--- | ---
ava_id | ballard_canyon
cfr_index | 9.230
revision | [T.D. TTB-116, 78 FR 60695, Oct. 2, 2013]
state | CA
county | Santa Barbara
within | Central Coast\|Santa Ynez Valley
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Los Olivos, CA, 1995; 
2. Zaca Creek, Calif., 1959; and 
3. Solvang, CA, 1995.

## Boundary [src]

(1) The beginning point is on the Los Olivos map at the intersection of State Route 154 and Foxen Canyon Road, section 23, T7N/R31W. 
(2) From the beginning point, proceed southwesterly in a straight line approximately 0.3 mile, crossing onto the Zaca Creek map, to the intersection of Ballard Canyon Road and an unnamed, unimproved road known locally as Los Olivos Meadows Drive, T7N/R31W; then 
(3) Proceed south-southeasterly in a straight line approximately 1 mile, crossing onto the Los Olivos map, to a marked, unnamed large structure located within a circular-shaped 920-foot contour line in the southwest corner of section 26, T7N/R31W; then 
(4) Proceed south-southwesterly in a straight line approximately 1.25 miles, crossing onto the Zaca Creek map, to the marked “Ball” 801-foot elevation control point, T6N/R31W; then 
(5) Proceed south-southwesterly in a straight line approximately 1.45 miles, crossing onto the Solvang map, to a marked, unnamed 775-foot peak, T6N/R31W; then 
(6) Proceed south-southwesterly in a straight line approximately 0.55 mile to a marked communication tower located within the 760-foot contour line, T6N/R31W; then 
(7) Proceed west-southwesterly in a straight line approximately 0.25 mile to the intersection of Chalk Hill Road and an unnamed, light-duty road known locally as Mesa Vista Lane, T6N/R31W; then 
(8) Proceed west-southwesterly in a straight line approximately 0.6 mile to the southern-most terminus of a marked, unnamed stream known locally as Ballard Creek, T6N/R31W; then 
(9) Proceed northerly 
(upstream) along Ballard Creek approximately 0.35 mile to the creek&#39;s intersection with the 400-foot contour line, T6N/R31W; then 
(10) Proceed southerly and then northwesterly along the 400-foot contour line approximately 1.5 miles, to the contour line&#39;s first intersection with Ballard Canyon Road, T6N/R31W; then 
(11) Proceed north-northeasterly in a straight line approximately 1.7 miles, crossing onto the Zaca Creek map, to the western-most intersection of the 800-foot contour line and the T6N/T7N boundary line 
(approximately 0.9 mile east of U.S Highway 101); then 
(12) Proceed west along the T6N/T7N boundary line approximately 0.4 mile to the boundary line&#39;s third intersection with the 600-foot contour line 
(approximately 0.5 mile east of U.S. Highway 101); then 
(13) Proceed northerly along the meandering 600-foot elevation contour line to the contour line&#39;s intersection with Zaca Creek, T7N/R31W; then 
(14) Proceed northeasterly in a straight line for approximately 1.2 miles to the western-most intersection of the southern boundary of the Corral de Quati Land Grant and the 1,000-foot contour line 
(approximately 0.4 mile east of U.S. Highway 101), T7N/R31W; then 
(15) Proceed easterly along the meandering 1,000-foot contour line approximately 1.5 miles to the contour line&#39;s third intersection with the southern boundary of the Corral de Quati Land Grant 
(approximately 0.1 mile west of State Route 154), section 22, T7N/R31W; then 
(16) Proceed southeasterly in a straight line approximately 0.8 mile, crossing onto the Los Olivos map, returning to the beginning point.

**Comment by tbrittnacher** [comment]
UCSB is now working on this boundary.

**Comment by SoominHur** [comment]
Reviewed.
- There are several  "Zaca Creek" maps with different edition years. There were no significant differences among different editions. But I used 1985ed. version and noted it in the attribute table. Because it is closest to the map year of the other maps, which are 1995.
- Unable to find (2) "Zaca Creek map ... intersection of Ballard Canyon Road and an unnamed, unimproved road,  known locally as Los Olivos Meadows Drive." So, searched google maps and put the node at the third intersection (from north to south direction) of Ballard Cayon Road and eastern edge of Zaca Creek map. Where is approximately 115 feet above in straight line from "unimproved road known locally as Los Olivos Meadows Drive" in Los Olivos map.
