### ISSUE TITLE
bell_mountain

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#28]
# AVA: Bell Mountain (bell_mountain)

name | value
--- | ---
ava_id | bell_mountain
cfr_index | 9.55
revision | [T.D. ATF-238, 51 FR 36400, Oct. 10, 1986]
state | TX
county | Gillespie
within | Texas Hill Country
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]
 The appropriate map for determining the boundaries of the Bell Mountain viticultural area is one U.S.G.S. map, titled: Willow City Quadrangle, 7.5 minute series, 1967.

## Boundary [src]
General.  The Bell Mountain viticultural area is located in Gillespie County, Texas. The starting point of the following boundary description is the summit of Bell Mountain 
(1,956 feet). Boundary Description.  
(i) From the starting point, the boundary proceeds due southward for exactly one half mile; 
(ii) Then southeastward in a straight line to the intersection of Willow City Loop Road with an unnamed unimproved road, where marked with an elevation of 1,773 feet; 
(iii) Then generally southward along Willow City Loop Road 
(a light-duty road) to Willow City. 
(iv) Then continuing southward and westward along the same light-duty road to the intersection having an elevation of 1,664 feet; 
(v) Then continuing westward along the light-duty road to the intersection having an elevation of 1,702 feet; 
(vi) Then turning southward along the light-duty road to the intersection having an elevation of 1,736 feet; 
(vii) Then turning westward along the light-duty road to the intersection having an elevation of 1,784 feet; 
(viii) Then turning southward and then westward, following the light-duty road to its intersection with Texas Highway 16, where marked with an elevation of 1,792 feet; 
(ix) Then due westward to the longitude line 98°45 
(x) Then northward along that longitude line to a point due west of an unnamed peak with an elevation of 1,784 feet; 
(xi) Then due eastward to the summit of that unnamed peak; 
(xii) Then in a straight line eastward to the intersection of an unnamed unimproved road with Texas Highway 16, where marked with an elevation of 1,822 feet; 
(xiii) Then following that unnamed road, taking the right-hand fork at an intersection, to a point due west of the summit of Bell Mountain; 
(xiv) Then due eastward to the summit of Bell Mountain.

**Comment by SoominHur** [comment]
Begin working on this

**Comment by alisonsnwong** [comment]
Checked!
