### ISSUE TITLE
ben_lomond_mountain

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#29]
# AVA: Ben Lomond Mountain (ben_lomond_mountain)

name | value
--- | ---
ava_id | ben_lomond_mountain
cfr_index | 9.118
revision | [T.D. ATF-264, 52 FR 46591, Dec. 9, 1987]
state | CA
county | Santa Cruz
within | Santa Cruz Mountains
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Davenport Quadrangle 
1955, photorevised 1968.; 
2. Big Basin Quadrangle 
1955, photorevised 1973.; 
3. Felton Quadrangle 
1955, photorevised 1980.; and 
4. Santa Cruz Quadrangle 
1954, photorevised 1981..

## Boundary [src]

(1) From the beginning point, the boundary follows the 800-foot contour line in a meandering manner in a generally northwesterly direction across section 26 into section 27 
(T. 10S., R. 3W.). 
(2) Thence along the 800-foot contour line in an easterly and then generally a northeasterly direction through section 27 and then back across the northwest corner of section 26 and thence in a generally northwesterly direction along the 800-foot contour line across sections 23, 22 and into section 15. 
(3) Thence along the 800-foot contour line in a northerly and then a southerly direction across section 22 and eventually in a generally northwesterly direction into section 20. 
(4) Thence continuing along the 800-foot contour line in a generally northwesterly direction through sections 20, 17, 16, 17, 16, 9, 8, 5, 8, 7 and 6 
(T. 10S., R. 3W.). 
(5) Thence continuing in a northerly direction across sections 5 and 32 and thence in a southwesterly direction across sections 31 and 6. 
(6) Thence continuing in a generally northerly direction across sections 1, 6, 31, 36, 31, 36 and 30 
(T. 9S., R. 3W.) to the intersection of the 800-foot contour line and Scott Creek in section 19 
(T. 9S., R. 3W.). 
(7) Thence in a northeasterly direction along the south bank of Scott Creek through sections 19, 20 and 17 to the intersection of Scott Creek with the 1600-foot contour line in section 16 
(T. 9S., R. 3W.). 
(8) Thence in a generally northeasterly and then southerly direction along the 1600-foot contour line through section 16 and then through the southeast and southwest corners of sections 9 and 10 respectively to the intersection of the 1600-foot contour line with Jamison Creek in section 16 
(T. 9S., R. 3W.). 
(9) Thence in an easterly direction along the south bank of Jamison Creek across sections 15 and 14 
(T. 9S., R. 3W.) to the intersection of Jamison Creek and the 800-foot contour line in the southeast corner of section 14 
(T. 9S., R. 3W.). 
(10) Thence in a southeasterly direction in a meandering manner along the 800-foot contour line across sections 14, 23, 24, 25 
(T. 9S., R. 3W.), sections 30 and 31 
(T. 9S., R. 2W.), and sections 32, 5, 8, 9, 16, 17 and 21 
(T. 10S., R. 2W.). 
(11) Thence in a southwesterly, then generally a southeasterly and then a northwesterly direction along the 800-foot contour line in a meandering manner to section 31 and then continuing on through sections 31 and 30 
(T. 10S., R. 2W.). 
(12) Thence continuing along the 800-foot contour line in a generally southerly and then a generally northwesterly direction through sections 25, 36, 31 and 36 to the point of beginning at the intersection of sections 25, 26, 35 and 36 
(T. 10S., R. 3W.).

**Comment by fyfangyao** [comment]
I am working on it.

**Comment by fyfangyao** [comment]
I use “Davenport, CA, 7.5 Minute Series, edition of 1955, (revised 1970),” “Big Basin, Calif. 7.5 Minute Series, edition of 1955, (revised 1970),” and “Santa Cruz, Calif. 7.5 Minute Series, edition of 1954, (revised 1982)” because I cannot find the edition revised in required year.

**Comment by SoominHur** [comment]
Reviewed.
- Add scale information of used maps. 
- Add description about the beginning point.
