### ISSUE TITLE
benmore_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#30]
# AVA: Benmore Valley (benmore_valley)

name | value
--- | ---
ava_id | benmore_valley
cfr_index | 9.138
revision | [T.D. ATF-315, 56 FR 52191, Oct. 18, 1991]
state | CA
county | Lake
within | North Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Hopland, CA,” 7.5 Minute Series, edition of 1960, 
photoinspected 1975.; and 
2. “Purdys Gardens, CA,” 7.5 Minute Series, edition of 1958, 
photoinspected 1975..

## Boundary [src]

(1) Then southwest in a straight line to the point where an unnamed unimproved road crosses the south section line of section 35, T. 14 N., R. 11 W., west of Benmore Creek; 
(2) Then following the unnamed unimproved road south to the intersection with the boundary between Lake and Mendocino Counties; 
(3) Then following the county boundary between Lake and Mendocino Counties east and south to the intersection with the 2800 foot contour line; 
(4) Then following the 2800 foot contour line in a northerly and then southernly direction to its intersection with the boundary between Lake and Mendocino Counties on the southern edge of section 2, T. 13 N., R. 11 W; 
(5) Then following the boundary between Lake and Mendocino Counties east to the point of intersection of sections 1, 2, 11, and 12, T. 13 N., R. 11 W; 
(6) Then southeasterly in a straight line to an unnamed peak of 2769 feet elevation in the center of section 12, T. 13 N., R. 11 W; 
(7) Then south in a straight line to the point where the boundary between Lake and Mendocino Counties changes from an east-west direction to a north-south direction; 
(8) Then in a straight line in an easterly direction to an unnamed peak of 2883 feet elevation in the southwestern portion of section 5, T. 13 N., R. 10 W; 
(9) Then northeast in a straight line to the easternmost peak of an unnamed ridge with four peaks in the center of section 5, T. 13 N., R. 10 W; 
(10) Then northerly in a straight line to an unnamed peak of 2647 feet elevation near the north section line of section 5, T. 13 N., R. 10 W; 
(11) Then westerly in a straight line to the point of intersection between section 5, T. 13 N., R 10 W., section 31, T. 14 N., R. 10 W., and section 1, T. 13 N., R. 11 W; 
(12) Then northwest in a straight line to an unnamed peak of 2904 feet elevation in the north portion of section 1, T. 13 N., R. 11 W; 
(13) Then northwest in a straight line to an unnamed peak of 2788 feet elevation, the point of beginning.

**Comment by fyfangyao** [comment]
I am working on it.

**Comment by fyfangyao** [comment]
The “cfr revision history” is [T.D. ATF-315, 56 FR 52190, Oct. 18, 1991] in the final report but [T.D. ATF-315, 56 FR 52191, Oct. 18, 1991] in the attribute table.

**Comment by MicheleTobias** [comment]
@qjhart do you have any thoughts on why the revision history string in the geojson files don't match the string in the documentation?  Yao found 2 so far that are off by one digit.

**Comment by qjhart** [comment]
Hmm, I can't say for sure.  What I can say, is that from my [Notes](https://github.com/UCDavisLibrary/ava/blob/master/NOTES.org) I can see the [AVA Link](https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c) that I used.  This seems to bre an evergreen link, but you can see in Benmoore valley, that's the revision they have.

**Comment by SoominHur** [comment]
Reviewed. Added beginning point information in boundary description of attribute table.
