### ISSUE TITLE
bennett_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#31]
# AVA: Bennett Valley (bennett_valley)

name | value
--- | ---
ava_id | bennett_valley
cfr_index | 9.142
revision | [T.D. TTB-6, 68 FR 61748, Oct. 30, 2003]
state | CA
county | Sonoma
within | North Coast\|Sonoma Coast\|Sonoma Mountain\|Sonoma Valley
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Santa Rosa Quadrangle, CA—Sonoma Co. 1994 
2. Kenwood Quadrangle, CA 1954, photorevised 1980 
3. Glen Ellen Quadrangle, CA—Sonoma Co. 1954, photorevised 1980 
4. Cotati Quadrangle, CA—Sonoma Co. 1954, photorevised 1980

## Boundary [src]

(1) Beginning at the peak of Taylor Mountain 
(BM 1401), Section 6, T6N, R7W, proceed straight northeast to the intersection of the common line between Sections 31 and 32 and the 560-foot elevation line, T7N, R7W; continue straight northeast at the same angle, crossing the Bennett Valley Golf Course and Matanzas Creek, to a point on the 500-foot elevation line approximately 400 feet north of the southern boundary of Section 20, T7N, R7W 
(Santa Rosa Quadrangle); then 
(2) Proceed straight southeast to the center peak of the three unnamed peaks above the 1,100-foot elevation line, located approximately 1,600 feet southwest of Hunter Spring, in Section 28, T7N, R7W 
(Santa Rosa Quadrangle); then 
(3) Proceed straight east-southeast to a 1,527-foot peak in the southeast corner of Section 28, T7N, R7W 
(Santa Rosa Quadrangle); then 
(4) Proceed straight southeast to Bennett Mountain&#39;s 1,887-foot peak, Section 34, T7N, R7W 
(Kenwood Quadrangle); then 
(5) Proceed straight southeast to the 1,309-foot peak located northwest of a water tank and approximately 400 feet north of the southern boundary of Section 35, T7N, R7W 
(Kenwood Quadrangle); then 
(6) Proceed straight south-southeast to the 978-foot peak in the northeast quadrant of Section 11, T6N, R7W, and continue straight south-southeast approximately 600 feet to the “T” intersection of two unimproved roads located on the common boundary line between Sections 11 and 12, T6N, R7W 
(Kenwood Quadrangle); then 
(7) Proceed south along the north-south unimproved road to its intersection with Sonoma Mountain Road, Section 13, T6N, R7W, and continue straight south to the 1,600-foot elevation line, Section 13, T6N, R7W 
(Glen Ellen Quadrangle); then 
(8) Proceed west along the meandering 1,600-foot elevation line to the point where it crosses the common line between Sections 22 and 23, T6N, R7W 
(Glen Ellen Quadrangle); then 
(9) Proceed straight west-northwest to the point where the 900-foot elevation line crosses the common line between Sections 15 and 16, T6N, R7W, approximately 500 feet north of the southwest corner of Section 15 
(Cotati Quadrangle); then 
(10) Proceed straight northwest to the intersection of Grange Road 
(known as Crane Canyon Road to the west) and the southern boundary of Section 9, and continue straight west along that section boundary to the southwest corner of Section 9, T6N, R7W 
(Cotati Quadrangle); then 
(11) Proceed straight north-northwest to the 961-foot peak on the east side of Section 8, T6N, R7W 
(Santa Rosa Quadrangle); and then 
(12) Proceed straight northwest to the peak of Taylor Mountain, returning to the point of beginning.

**Comment by SoominHur** [comment]
Reviewed. Edited created date in attribute table.
