### ISSUE TITLE
big_valley_district_lake_county

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#32]
# AVA: Big Valley District-Lake County (big_valley_district_lake_county)

name | value
--- | ---
ava_id | big_valley_district_lake_county
cfr_index | 9.232
revision | [T.D. TTB-118, 78 FR 60688, Oct. 2, 2013]
state | CA
county | Lake
within | \|Clear LakeNorth Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Lucerne, CA, 1996; 
2. Kelseyville, CA, 1993; 
3. Highland Springs, CA, 1993; and 
4. Lakeport, CA, 1958; photorevised 1978; minor revision 1994.

## Boundary [src]

(1) The beginning point is on the Lucerne map at the point where Cole Creek flows into Clear Lake, section 36, T14N/R9W. From the beginning point, proceed southerly 
(upstream) along Cole Creek approximately 0.9 mile to the creek&#39;s intersection with Soda Bay Road, section 1, T13N/R9W; then 
(2) Proceed east on Soda Bay Road less than 0.1 mile to the road&#39;s intersection with the unnamed, light-duty road known locally as Clark Drive, section 1, T13N/R09W; then 
(3) Proceed southeast in a straight line less than 0.1 mile to the 1,400-foot elevation line, section 1, T13N/R9W; then 
(4) Proceed southerly along the 1,400-foot elevation line, crossing onto the Kelseyville map, to the line&#39;s intersection with a marked cemetery east of Kelseyville 
(in the northeast quadrant of section 14, T13N/R9W), and then continue along the 1,400-foot elevation line approximately 0.35 mile to the line&#39;s intersection with an unnamed, unimproved road which runs north from Konocti Road, section 13, T13N/R9W; then 
(5) Proceed south-southeast along the unnamed, unimproved road to the road&#39;s intersection with the improved portion of Konocti Road, section 13, T13N/R9W; then 
(6) Proceed west on Konocti Road approximately 0.9 mile to the road&#39;s intersection with an unnamed, light-duty road within Kelseyville known locally as Main Street, section 14, T13N/R9W; then 
(7) Proceed south-southeast on Main Street approximately 0.35 mile to its intersection with State Highway 29/175, section 14, T13N/R9W; then 
(8) Proceed west-northwest on State Highway 29/175 approximately 0.4 mile to the highway&#39;s intersection with Kelsey Creek, section 14, T13N/R9W; then 
(9) Proceed northwesterly 
(downstream) along Kelsey Creek approximately 0.5 mile to the creek&#39;s intersection with an unnamed, light-duty road known locally as Big Valley Road 
(or North Main Street), section 15, T13N/R9W; then 
(10) Proceed west and then northwest on Big Valley Road approximately 0.35 mile to the road&#39;s intersection with Merritt Road, southern boundary of section 10, T13N/R9W; then 
(11) Proceed west on Merritt Road approximately 0.3 mile to the road&#39;s intersection with the 1,400-foot elevation line, southern boundary of section 10, T13N/R9W; then 
(12) Proceed northwesterly along the 1,400-foot elevation line to the line&#39;s intersection with State Highway 29/175, section 9, T13N/R9W, and then continue southerly along the 1,400-foot elevation to the line&#39;s intersection with Merritt Road, southern boundary of section 9, T13N/R9W; then 
(13) Proceed west on Merritt Road approximately 0.1 mile to the road&#39;s intersection with Hill Creek, southern boundary of section 9, T13N/R9W; then 
(14) Proceed southerly 
(upstream) along Hill Creek approximately 0.9 mile to the creek&#39;s intersection with Bell Hill Road, section 16, T13N/R9W; then 
(15) Proceed west then southwest on Bell Hill Road approximately 0.15 mile, passing the intersection of Bell Hill Road and Hummel Lane, to Bell Hill Road&#39;s intersection with the 1,400-foot elevation line, section 16, T13N/R9W; then 
(16) Proceed westerly and then southwesterly along the meandering 1,400-foot elevation line, crossing onto the Highland Springs map, to the line&#39;s first intersection with Bell Hill Road in section 20, T13N/R9W; then 
(17) Proceed west on the meandering Bell Hill Road, crossing Adobe Creek, to the road&#39;s intersection with Highland Springs Road, section 30, T13N/R9W; then 
(18) Proceed north on Highland Springs Road approximately 2.8 miles to the road&#39;s intersection with Mathews Road at the northwest corner of section 8, T13N/R9W; then 
(19) Proceed west on Mathews Road approximately 0.7 mile to the road&#39;s intersection with an unnamed paved road known locally as Ackley Road, southern boundary of section 6, T13N/R9W; then 
(20) Proceed north on Ackley Road approximately 0.9 mile, crossing onto the Lakeport map, to the road&#39;s intersection with State Highway 29/175, section 6; T13N/R9W; then 
(21) Proceed due north-northeast in a straight line approximately 0.15 mile to the unnamed secondary highway known locally as Soda Bay Road, northern boundary of section 6, T13N/R9W; then 
(22) Proceed east on Soda Bay Road approximately 0.35 mile to the road&#39;s intersection with Manning Creek, northern boundary of section 6, T13N/R9W; then 
(23) Proceed northwesterly 
(downstream) along Manning Creek to the shore of Clear Lake, section 30, T14N/R9W; then 
(24) Proceed easterly along the meandering shore of Clear Lake, crossing onto the Lucerne map, to the beginning point.

**Comment by fyfangyao** [comment]
I am working on this.

**Comment by fyfangyao** [comment]
I use “Lucerne, CA, 7.5 Minute Series, edition of 1996, (revised 2001),”  “Kelseyville, CA, 7.5 Minute Series, edition of 1993, (revised 1993),” and “Highland Springs, CA, 7.5 Minute Series, edition of 1993, (revised 1993)” because the approved maps don’t specify the revision years.

**Comment by SoominHur** [comment]
Reviewed.
- refined some nodes' location at sharing boundary with Kelsey Bench Lake County geojson.
- edited petitioner name in attribute table.
