### ISSUE TITLE
borden_ranch

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#33]
# AVA: Borden Ranch (borden_ranch)

name | value
--- | ---
ava_id | borden_ranch
cfr_index | 9.196
revision | [T.D. TTB-50, 71 FR 40414, July 17, 2006]
state | CA
county | Sacramento|San Joaquin
within | Lodi
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Lockeford, Calif., 1968, photorevised 1979, minor revision 1993; 
2. Clay, Calif., 1968, photorevised 1980, minor revision 1993; 
3. Sloughhouse, Calif., 1968, photorevised 1980, minor revision 1993; 
4. Carbondale, Calif., 1968, photorevised 1980, minor revision 1993; 
5. Goose Creek, Calif., 1968, photorevised 1980, minor revision 1993; and 
6. Clements, Calif., 1968, minor revision 1993.

## Boundary [src]

(1) The beginning point is on the Lockeford map at the intersection of Liberty Road and Elliott Road at the southwest corner of section 36, T5N, R7E. From the beginning point, proceed north 2 miles on Elliot Road, which becomes Clay Station Road upon crossing the Sacramento-San Joaquin County line at Dry Creek, to Clay Station Road&#39;s intersection with Simmerhorn Road, at the southeast corner of section 23, T5N, R7E 
(Clay Quadrangle); then 
(2) Proceed west 2 miles on Simmerhorn Road to its intersection with Alabama Road at the southwest corner of section 22, T5N, R7E 
(Clay Quadrangle); then 
(3) Proceed north 2 miles on Alabama Road to its intersection with Borden Road at the northwest corner of section 15, T5N, R7E 
(Clay Quadrangle); then 
(4) Proceed west 1 mile on Borden Road to its intersection with Alta Mesa Road at the southwest corner of section 9, T5N, R7E 
(Clay Quadrangle); then 
(5) Proceed north 1.35 miles on Alta Mesa Road, crossing State Route 104, to Alta Mesa Road&#39;s intersection with the Laguna tributary along the western boundary line of section 4, T5N, R7E 
(Clay Quadrangle); then 
(6) Proceed easterly 
(upstream) about 16.5 miles along the meandering Laguna tributary, crossing over the southeast corner of the Sloughhouse map, to the Laguna&#39;s intersection with the Sacramento-Amador County line, 0.75 mile south of the Ione Road, T6N, R9E 
(Carbondale Quadrangle); then 
(7) Proceed south and then southeast about 10.8 miles along the Sacramento-Amador and Sacramento-San Joaquin County lines, crossing over the Goose Creek map, to the County line&#39;s intersection with Liberty Road, section 32, T5N, R9E 
(Clements Quadrangle); and 
(8) Proceed west about 9.3 miles west along Liberty Road, returning to the beginning point.

**Comment by fyfangyao** [comment]
I am working on it.

**Comment by SoominHur** [comment]
Reviewed.
- Add scale information of used maps in the attribute table.
