### ISSUE TITLE
california_shenandoah_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#34]
# AVA: California Shenandoah Valley (california_shenandoah_valley)

name | value
--- | ---
ava_id | california_shenandoah_valley
cfr_index | 9.37
revision | [T.D. ATF-121, 47 FR 57696, Dec. 28, 1982, as amended by T.D. ATF-249, 52 FR 5957, Feb. 27, 1987]
state | CA
county | Amador|El Dorado
within | Sierra Foothills
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Boundary [src]

(1) Beginning at the point where the Consumnes River meets Big Indian Creek. 
(2) Then south, following Big Indian Creek, until Big Indian Creek meets the boundary between Sections 1 and 2 of Township 7 North Range 10 East. 
(3) Then following this boundary south until it meets the Oleta 
(Fiddletown) Road. 
(4) Then following the Oleta Road east until it meets the boundary between Sections 6 and 5 of Township 7 North Range 11 East. 
(5) Then following that boundary north into Township 8 North Range 11 East, and continues north on the boundary between Sections 31 and 32 until this boundary meets Big Indian Creek. 
(6) Then following Big Indian Creek in a northeasterly direction until Big Indian Creek meets the boundary between Sections 28 and 27 of Township 8 North Range 11 East. 
(7) Then following this boundary north until it reaches the southeast corner of Section 21 of Township 8 North Range 11 East. 
(8) The boundary then proceeds east, then north, then west along the boundary of the western half of Section 22 of Township 8 North Range 11 East to the intersection of Sections 16, 15, 21, and 22. 
(9) Then proceeding north along the boundary line between Sections 16 and 15 of Township 8 North Range 11 East and continues north along the boundary of Sections 9 and 10 of Township 8 North Range 11 East to the intersection of Sections 9, 10, 3, and 4 of Township 8 North Range 11 East. 
(10) Then proceeding west along the boundary of Sections 9 and 4. 
(11) Then continuing west along the boundary of Sections 5 and 8 of Township 8 North Range 11 East to the Consumnes River. 
(12) Then the boundary proceeds west along the Consumnes River to the point of the beginning.

**Comment by fyfangyao** [comment]
I am working it

**Comment by fyfangyao** [comment]
“Fiddletown Quad, CA, 7.5 minute series, 1949, photorevised 1986” and “Amador City Quad, CA, 7.5 minute series, 1962, photorevised 1986.”

**Comment by SoominHur** [comment]
Reviewed
- The line suddenly stopped to (12) "proceeds west along the Consumnes River" in section 12 (T8N, R10E), so add nodes to keep follow river.
