### ISSUE TITLE
calistoga

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#35]
# AVA: Calistoga (calistoga)

name | value
--- | ---
ava_id | calistoga
cfr_index | 9.209
revision | [T.D. TTB-83, 74 FR 64612, Dec. 8, 2009]
state | CA
county | Napa
within | Napa Valley\|North Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Mark West Springs, Calif. 
1993.; 
2. Calistoga, CA 
1997.; 
3. St. Helena, Calif. 
1960, revised 1993.; and 
4. Detert Reservoir, CA 
1997..

## Boundary [src]

(1) Continues northeasterly along Petrified Forest Road approximately 1.9 miles to the road&#39;s intersection with the 400-foot contour line near the north bank of Cyrus Creek approximately 1,000 feet southwest of the intersection of Petrified Forest Road and State Route 128 on the Calistoga map; 
(2) Proceeds generally east-southeast 
(after crossing Cyrus Creek) along the 400-foot contour line to its intersection with Ritchey Creek in section 16, T8N/R6W; 
(3) Follows Ritchey Creek northeast approximately 0.3 mile to its intersection with State Route 29 at the 347-foot benchmark; 
(4) Proceeds east-southeast along State Route 29 approximately 0.3 mile to its intersection with a light-duty road labeled Bale Lane; 
(5) Follows Bale Lane northeast approximately 0.7 mile to its intersection with the Silverado Trail; 
(6) Proceeds northwest along the Silverado Trail approximately 1,500 feet to its intersection with an unmarked driveway on the north side of the Silverado Trail near the 275-foot benchmark; 
(7) Continues northeasterly along the driveway for 300 feet to its intersection with another driveway, and then continues north-northeast in a straight line to the 400-foot contour line; 
(8) Follows the 400-foot contour line easterly approximately 0.7 miles to its intersection with an unimproved dirt road 
(an extension of a road known locally as the North Fork of Crystal Springs Road), which lies in the Carne Humana Land Grant approximately 1,400 feet southwest of the northwest corner of section 11, T8N/R6W on the St. Helena map; 
(9) Continues northerly along the unimproved dirt road approximately 2,700 feet to its intersection with the 880-foot contour line in section 2, T8N/R6W; 
(10) Follows the meandering 880-foot contour line northwesterly, crossing onto the Calistoga map in section 2, T8N/R6W, and continues along the 880-foot contour line through section 3, T8N/R6W, sections 34 and 35, T9N/R6W, 
(with a brief return to the St. Helena map in section 35), to the 880-contour line&#39;s intersection with Biter Creek in the northeast quadrant of section 34, T9N/R6W; 
(11) Continues westerly along the meandering 880-foot contour line around Dutch Henry Canyon in section 28, T9N/R6W, and Simmons Canyon in section 29, T9N/R6W, to the contour line&#39;s first intersection with the R7W/R6W range line in section 30, T9N/R6W; 
(12) Continues northerly along the meandering 880-foot contour line across the two forks of Horns Creek and through Hoisting Works Canyon in section 19, T9N/R6W, crossing between the Calistoga and Detert Reservoir maps, to the contour line&#39;s intersection with Garnett Creek in section 13, T9N/R7W, on the Detert Reservoir map; 
(13) Continues westerly along the meandering 880-foot contour line, crossing between the Calistoga and Detert Reservoir maps in sections 13 and 14, T9N/R7W, and in the region labeled “Mallacomes or Moristul y Plan de Agua Caliente,” to the contour line&#39;s intersection with the Napa-Sonoma county line approximately 1.1 miles northeast of State Route 128 in the “Mallacomes or Moristul y Plan de Agua Caliente” region, T9N/R7W, of the Mark Springs West map; and 
(14) Proceeds southerly along the Napa-Sonoma county line to the beginning point. Transition Period.  A label containing the word “Calistoga” in the brand name approved prior to December 8, 2009 may not be used on wine bottled on or after December 10, 2012 if the wine does not conform to the standards for use of the label set forth in §4.39
(i) of this chapter.

**Comment by SoominHur** [comment]
Continue Reviewing
- edited created date in attribute table
- (5) refined nodes to "Follows Bale Lane..."
- (9), (10), (11), (12), (13) redrew line "Follows the meandering 880-foot contour line..." because it followed 960' contour line
