### ISSUE TITLE
capay_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#36]
# AVA: Capay Valley (capay_valley)

name | value
--- | ---
ava_id | capay_valley
cfr_index | 9.176
revision | [T.D. ATF-486, 67 FR 77924, Dec. 20, 2002] 
state | CA
county | Yolo
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]
Note: The federal register description and approved maps section for this AVA was not standard so I'm pasting the text in. (Michele)
Approved maps. The appropriate map for determining the boundary of the Capay Valley viticultural area is the United States Geological Survey (U.S.G.S.) topographic map titled: 30X60 Minute Quadrangle (Healdsburg, California 1972) (Scale: 1:100,000).

## Boundary [src]

The beginning point is the junction of the Yolo, Napa, and Lake County lines.
(1) From the beginning point, proceed north then east along the Yolo-Lake County line;  
(2) At the junction of the Yolo, Lake, and Colusa County lines, continue east along the Yolo-Colusa County line to its junction with the boundary between ranges R4W and R3W;  
(3) Then south along the R4W and R3W boundary to its junction with the 250 meter contour line;  
(4) Proceed generally southeast along the meandering 250 meter contour line to its junction with the T10N-T11N section line;  
(5) Continue east along the T10N-T11N section line to the unnamed north-south secondary highway known locally as County Road 85;  
(6) Then south along County Road 85, crossing Cache Creek, to its intersection with State Highway 16;  
(7) Proceed east on Highway 16 to its junction with the unnamed north-south light duty road known locally as County Road 85B;  
(8) Then south on County Road 85B to its junction with the unnamed east-west light duty road known locally as County Road 23;  
(9) Proceed west on County Road 23 for approximately 500 feet to an unnamed light duty road known locally as County Road 85;  
(10) Proceed south on County Road 85 until the road ends and continue south in a straight line to the T9N-T10N section line;  
(11) Then west on the T9N-T10N section line to the Napa-Yolo County line;  
(12) Continue northwest following the Napa-Yolo county line and return to the starting point.

**Comment by fyfangyao** [comment]
I am working on it.

**Comment by fyfangyao** [comment]
I use "Healdsburg, Calif.," scale 1:100,000, 1972 (edition 1993) because the approved maps don’t specify the edition years.

**Comment by SoominHur** [comment]
Reviewed
- Edit line to turn (3) "south along the R4W and R3W boundary to its junction with the 250 meter contour line" because the line kept proceed east along Yolo-Colusa County line past R4W/R3W section line.
- As the line proceeded in wrong direction in (3), the line meandered along wrong 250 meter contour line. So I deleted existing meandering line and  (4) "proceed generally southeast along the meandering 250 meter contour line" that intersects with R4W/R3W section line.
