### ISSUE TITLE
carmel_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#37]
# AVA: Carmel Valley (carmel_valley)

name | value
--- | ---
ava_id | carmel_valley
cfr_index | 9.58
revision | [T.D. ATF-119, 47 FR 55916, Dec. 14, 1982, as amended by T.D. TTB-91, 76 FR 5477, Feb. 1, 2011]
state | CA
county | Monterey
within | Central Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Mt. Carmel, Calif., dated 1956; 
2. Carmel Valley, Calif., dated 1956; 
3. Ventana Cones, Calif., dated 1956; 
4. Chews Ridge, Calif., dated 1956; and 
5. Rana Creek, Calif., dated 1956.

## Boundary [src]

(1) The beginning point is the northeast corner of Section 5 in Township 17 South, Range 2 East. 
(2) The boundary follows the Los Laurelles Land Grant boundary south, then easterly, to the north-south section line dividing Section 9 from Section 10 in Township 17 South, Range 2 East. 
(3) The boundary follows this section line south to the southwest corner of Section 22 in Township 17 South, Range 2 East. 
(4) From this point, the boundary follows section lines in Township 17 South, Range 2 East: 
(i) To the southeast corner of Section 22, 
(ii) To the southwest corner of Section 26, 
(iii) To the southeast corner of Section 26, 
(iv) To the southwest corner of Section 36. 
(5) From this point, the boundary follows the Los Padres National Forest boundary east, then south, then east to the southwest corner of Section 9 in Township 18 South, Range 3 East. 
(6) The boundary follows the section line east to the southeast corner of the same section, where the section line rejoins the Los Padres National Forest boundary. 
(7) The boundary follows the Los Padres National Forest boundary to the north-south section line dividing Section 11 from Section 12 in Township 18 South, Range 3 East. 
(8) The boundary follows this section line north to the township line dividing Township 17 South from Township 18 South. 
(9) The boundary follows this township line west to the north-south section line dividing Section 34 from Section 35 in Township 17 South, Range 3 East. 
(10) The boundary follows this section line north to the Los Tularcitos Land Grant boundary. 
(11) The boundary follows the Los Tularcitos Land Grant boundary northwesterly to the Carmel River. 
(12) The boundary follows the Carmel River northerly to the Los Tularcitos Land Grant boundary. 
(13) The boundary follows the Los Tularcitos Land Grant boundary northeasterly to the unsurveyed township line 
(approximate location denoted by a line of red dashes) dividing Township 16 South from Township 17 South. 
(14) The boundary follows the unsurveyed township line west to the beginning point.

**Comment by fyfangyao** [comment]
I am working on it.

**Comment by fyfangyao** [comment]
I use “Mt. Carmel Cali., 7.5 minute series, edition of 1956 (revised 1963),” “Carmel Valley Cali., 7.5 minute series, edition of 1956 (revised 1963),” “Ventana Cones Cali., 7.5 minute series, edition of 1956 (revised 1963),” “Chews Ridge., 7.5 minute series, edition of 1956 (revised 1964),” and “Rana Creek Cali., 7.5 minute series, edition of 1956 (revised 1963)”because the approved maps don’t specify the edition years.

**Comment by SoominHur** [comment]
Reviewed.
- Add scale information of used maps.
