### ISSUE TITLE
catoctin

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#38]
# AVA: Catoctin (catoctin)

name | value
--- | ---
ava_id | catoctin
cfr_index | 9.67
revision | [T.D. ATF-154, 48 FR 46523, Oct. 13, 1983, as amended by T.D. ATF-249, 52 FR 5959, Feb. 27, 1987]
state | MD
county | Frederick|Washington
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Point of Rocks Quadrangle, Maryland—Virginia,” 7.5 minute series, 1970; 
2. “Buckeystown Quadrangle, Maryland,” 7.5 minute series, 1952 
Photorevised 1971.; 
3. “Frederick Quadrangle, Maryland,” 7.5 minute series, 1953 
Photorevised 1980.; 
4. “Catoctin Furnace Quadrangle, Maryland,” 7.5 minute series, 1953 
Photorevised 1979.; 
5. “Blue Ridge Summit Quadrangle, Maryland—Pennsylvania,” 7.5 minute series, 1953 
Photorevised 1971.; 
6. “Emmitsburg Quadrangle, Maryland—Pennsylvania,” 7.5 minute series, 1953 
Photorevised 1971.; 
7. “Smithsburg Quadrangle, Maryland—Pennsylvania,” 7.5 minute series, 1953 
Photorevised 1971.; 
8. “Myersville Quadrangle, Maryland,” 7.5 minute series, 1953 
Photorevised 1971.; 
9. “Funkstown Quadrangle, Maryland,” 7.5 minute series, 1953 
Photorevised 1971.; 
10. “Keedysville Quadrangle, Maryland—West Virginia,” 7.5 minute series, 1978; 
11. “Harpers Ferry Quadrangle, Virginia—Maryland—West Virginia,” 7.5 minute series, 1969; and 
12. “Charles Town Quadrangle, West Virginia—Virginia—Maryland,” 7.5 minute series, 1978; 
13. “Middletown Quadrangle, Maryland,” 7.5 minute series, 1953 
photorevised 1979.;

## Boundary [src]

(1) Northerly 1,100 feet in a straight line to the point of intersection with a 500-foot contour line; 
(2) Then northeasterly along the meanders of the 500-foot contour line on the “Point of Rocks Quadrangle,” “Buckeystown Quadrangle,” “Frederick Quadrangle,” “Catoctin Furnace Quadrangle,” “Blue Ridge Summit Quadrangle,” and “Emmitsburg Quadrangle” maps to the point of intersection with the Maryland—Pennsylvania State line on the “Emmitsburg Quadrangle” map; 
(3) Then west along the Maryland-Pennsylvania State line on the “Emmitsburg Quadrangle,” “Blue Ridge Summit Quadrangle,” and “Smithsburg Quadrangle” maps to the point of intersection with the first 800-foot contour line lying west of South Mountain on the “Smithsburg Quadrangle” map; 
(4) Then southwesterly along the meanders of the 800-foot contour line on the “Smithburg Quadrangle,” “Myersville Quadrangle,” “Funkstown Quadrangle,” and “Keedysville Quadrangle” maps to the point of intersection with an unnamed light duty road 
(known locally as Clevelandville Road) north of the town of Clevelandville on the “Keedysville Quadrangle” map; 
(5) Then southerly along the unnamed light duty road to the point of intersection with Reno Monument Road; 
(6) Then southwesterly 13,500 feet in a straight line to the point lying at the intersection of Highway 67 and Millbrook Road; 
(7) Then westerly along Millbrook Road to the point of intersection with Mount Briar Road; 
(8) Then northerly along Mount Briar Road to the point of intersection with a 500-foot contour line; 
(9) Then northerly along the 500-foot contour line to the point of intersection with Red Hill Road; 
(10) Then southerly along the 500-foot contour line to the point of intersection with Porterstown Road; 
(11) Then south-southwesterly 29,000 feet in a straight line to the most eastern point on the boundary line of the Chesapeake and Ohio Canal National Historical Park lying north of the town of Dargan; 
(12) Then southwesterly 7,500 feet in a straight line to the point of the “Harpers Ferry Quadrangle” map lying approximately 600 feet northwest of Manidokan Camp at the confluence of an unnamed stream and the Potomac River; and 
(13) Then easterly along the meanders of the Potomac River on the “Harpers Ferry Quadrangle,” “Charles Town Quadrangle,” and “Point of Rocks Quadrangle” maps to the point of beginning.

**Comment by ericallanwest** [comment]
Please label this one In Progress. Thanks!

**Comment by davidkli** [comment]
I have checked this AVA and the boundary needs no edits. I updated the attribute table to use pipes instead of commas to separate items in the county field.
