### ISSUE TITLE
Check CA AVAs

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#386]
Review the CA AVA boundaries for deviations from the Federal Register Descriptions.  In particular, Napa & Sonoma Counties, as these were the first boundaries to be completed.

**Comment by sdelong** [comment]
Hi Michele,
This is a great project.  I will try to contribute as much as possible, but I first need to get familiar with GitHub.

In the meantime, I have found two errors in AVA boundaries:
from the eCFR specification:
Petaluma Gap AVA
(21) The wrong BM 10 is plotted - there is another BM 10 at the mouth of the Walker River, which is the correct one.
(5) The wrong section 34 southwest corner has been plotted - the correct one is approx 5 miles west T24S, R9E.

Hope this helps.
Best regards,
Steve

**Comment by MicheleTobias** [comment]
Thanks! I'll move the comments over to the issue for Petaluma Gap and re-open the issue.  Ideally, we post concerns with any individual AVA boundary on the issue for that specific boundary.

**Comment by MicheleTobias** [comment]
@sdelong I'd like to add you to our list of contributors on the landing page readme.  Would you like me to list your name (if so, let me know what you want listed) or just your github handle?

**Comment by sdelong** [comment]
Hi Michele, that sounds good. Please use my name in the list: Steve De Long.  Thank you.
