### ISSUE TITLE
cayuga_lake

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#39]
# AVA: Cayuga Lake (cayuga_lake)

name | value
--- | ---
ava_id | cayuga_lake
cfr_index | 9.127
revision | [T.D. ATF-269, 53 FR 9769, Mar. 25, 1988]
state | NY
county | Cayuga|Seneca|Tompkins
within | Finger Lakes
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Boundary [src]

(1) Commencing at the intersection of State Route 90 with State Route 5 in Cayuga County, north of Cayuga Lake. 
(2) Then south along State Route 90 to a point approximately one mile past the intersection of State Route 90 with State Route 326. 
(3) Then south along the primary, all-weather, hard surface road, approximately   mile, until it becomes State Route 90 again at Union Springs. 
(4) Then south/southeast along State Route 90 until it intersects the light-duty, all-weather, hard or improved surface road, approximately 1.5 miles west of King Ferry. 
(5) Then south along another light-duty, all-weather, hard or improved surface road, approximately 4 miles, until it intersects State Route 34B, just south of Lake Ridge. 
(6) Then follow State Route 34B in a generally southeast direction until it intersects State Route 34, at South Lansing. 
(7) Then south along State Route 34, until it meets State Route 13 in Ithaca. 
(8) Then southwest along State Routes 34/13, approximately 1.5 miles, until it intersects State Route 79, in Ithaca. 
(9) Then west along State Route 79, approximately   mile, until it intersects State Route 96. 
(10) Then along State Route 96, in a generally northwest direction, until it intersects State Routes 414 and 96A in Ovid. 
(11) Then north along State Routes 96/414, until they divide, approximately 2.5 miles north of Ovid. 
(12) Then along State Route 414, in a generally northeast direction, until it meets U.S. Route 20 in the town of Seneca Falls. 
(13) Then along U.S. Route 20, in a northeast direction, until it intersects State Routes 318, 89, and 5. 
(14) Then along U.S. Route 20/State Route 5, in a northeast direction, to the beginning point, at the intersection with State Route 90.

**Comment by gdmf** [comment]
Please add the "In Progress" label to this one.
