### ISSUE TITLE
central_delaware_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#41]
# AVA: Central Delaware Valley (central_delaware_valley)

name | value
--- | ---
ava_id | central_delaware_valley
cfr_index | 9.49
revision | [T.D. ATF-168, 49 FR 10117, Mar. 19, 1984, as amended by T.D. ATF-249, 52 FR 5958, Feb. 27, 1987]
state | NJ|PA
county | 
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Bloomsbury Quadrangle, New Jersey, 1955 
photorevised 1970.. 
2. Riegelsville Quadrangle, Pennsylvania-New Jersey, 1956 
photorevised 1968 and 1973.. 
3. Frenchtown Quadrangle, Pennsylvania-New Jersey, 1955 
photorevised 1970.. 
4. Lumberville Quadrangle, Pennsylvania-New Jersey, 1955 
photorevised 1968 and 1973.. 
5. Stockton Quadrangle, New Jersey-Pennsylvania, 1954 
photorevised 1970.. 
6. Hopewell Quadrangle, New Jersey, 1954 
photorevised 1970.. 
7. Buckingham Quadrangle, Pennsylvania—Bucks Co., 1953 
photorevised 1968 and 1973.. 
8. Lambertville Quadrangle, Pennsylvania-New Jersey, 1953 
photorevised 1968 and 1973.. 
9. Pennington Quadrangle, New Jersey-Pennsylvania 1954 
photorevised 1970..

## Boundary [src]
General.  The Central Delaware Valley viticultural area is located in Pennsylvania and New Jersey. The starting point of the following boundary description is the summit of Strawberry Hill, which is located in New Jersey near the Delaware River about one mile northwest of Titusville, at the southern end of the Central Delaware Valley viticultural area. The starting point is found on the Lambertville Quadrangle map. Boundary Description:  
(i) From the summit of Strawberry Hill 
(475 feet) in a straight line to the summit of Mt. Canoe 
(428 feet—on the Pennington Quadrangle map). 
(ii) From there due east to Mercer County Route 579 
(Bear Tavern Road) about .2 mile south of Ackors Corner. 
(iii) Then northward along Mercer 579 to Harbourton. 
(iv) From there northwestward along Route 3 
(Mount Airy-Harbourton Road) to the 2nd English Presbyterian Church in Mount Airy 
(on the Stockton Quadrangle map). 
(v) From there along Old York Road northward to Benchmark 157 on U.S. Route 202. 
(vi) From there westward along Queen Road and northwestward along Mount Airy Road to Dilts Corner. 
(vii) From there northwestward along Dilts Corner Road to Sandy Ridge Church. 
(viii) From there northwestward via Cemetary Road to Benchmark 305. 
(ix) From there northward along Covered Bridge Road to Green Sergeant Covered Bridge. 
(x) From there generally westward along Sanford Road to its intersection with Route 519 about one mile north of Rosemont. 
(xi) From there northward along Route 519 
(via Kingwood, Barbertown and Baptistown) to Palmyra 
(on the Frenchtown Quadrangle map). 
(xii) From the intersection in Palmyra, in a straight line northward to the 487 ft. elevation point near Nishisakawick Creek. 
(xiii) From there in a straight line northwestward to Benchmark 787 on Rt. 579 
(a secondary hard surface highway, unnamed on the map). 
(xiv) From there northward along Route 579 to Benchmark 905 
(on the Bloomsbury Quadrangle map). 
(xv) From there in a straight line westward to the 952 ft. summit of Musconetcong Mountain 
(on the Frenchtown Quadrangle map). 
(xvi) From there in a straight line southwestward to the 836 ft. summit of Musconetcong Mountain 
(on the Riegelsville Quadrangle map). 
(xvii) From there in straight lines connecting the 838 ft., 839 ft., 707 ft., and 386 ft. summits of Musconetcong Mountain. 
(xviii) From the 386 ft. summit of Musconetcong Mountain in a straight line across the Delaware River to the intersection of Routes 611 and 212. 
(xix) From there along Route 212 to the intersection with the lane going up Mine Hill. 
(xx) From there in a straight line to the summit of Mine Hill 
(488 feet). 
(xxi) From there in a straight line southwestward to the 522 ft. summit elevation point. 
(xxii) From there southeastward to the summit of Chestnut Hill 
(743 feet). 
(xxiii) From there in a straight line southeastward to the 347 ft. summit elevation point 
(located south of Kintnersville near Benchmark 173, about .1 mile west of Route 611). 
(xxiv) From there in a straight line eastward to the summit of Coffman Hill 
(826 feet). 
(xxv) From there in a straight line southeastward to the 628 ft. summit elevation point 
(about .3 mile north of Camp Davis). 
(xxvi) From there in a straight line southeastward to the point where Bridgeton, Nockamixon, and Tinicum Townships meet 
(on the Frenchtown Quadrangle map). 
(xxvii) From there in a straight line southward to the intersection of Slant Hill Road 
(Covered Bridge Road) and Stump Road in Smiths Corner 
(on the Lumberville Quadrangle map). 
(xxviii) From there in a straight line southeastward to the 472 ft. elevation point near Rocky Ridge School. 
(xxix) From there southeastward in a straight line to the 522 ft. elevation point on Plumstead Hill. 
(xxx) From there in a straight line to the 482 ft. elevation point about .7 mile northwest of Lahaska. 
(xxxi) From there in a straight line southeastward to the 352 ft. elevation point approximately .6 mile northeast of Lahaska. 
(xxxii) From there in a straight line to the point where a power transmission line crosses the 400 ft. contour line on the south side of Solebury Mountain 
(on the Lambertville Quadrangle map). 
(xxxiii) From there in a straight line to the tower on Bowman Hill in Washington Crossing State Park. 
(xxxiv) From there in a straight line across the Delaware River to the starting point, the summit of Strawberry Hill 
(475 feet).

**Comment by davidkli** [comment]
I have reviewed this AVA. The boundary is good, just fixed some formatting in the attribute table.
