### ISSUE TITLE
QGIS saves geojson.tmp instead of updating file.

### ISSUE THREAD

**Issue by wildintellect** [UCDavisLibrary/ava#415]
There seems to be a bug in QGIS 2.18.26+ (and QGIS 3.x which should not be used for this project anyways), where when you save your edits to a geojson it makes a new file ending in .tmp by the otherwise same name instead of overwriting the original file. It's been reported and discussed on https://gis.stackexchange.com/questions/300860/why-does-qgis-3-4-create-tmp-file-instead-of-refresh-editing-layer-after-saving 

I'm going to follow up with the QGIS Developer list to see if we can trace the issue and get it fixed. For now contributors should use any 2.18 version less than 2.18.26 instead.

**Comment by MicheleTobias** [comment]
@wildintellect Can you post your work-around here so we have options while we wait for a solution?  Thanks!

**Comment by wildintellect** [comment]
1. Save your edits in QGIS.
2. Turn off editing.
3. Save and exit QGIS.
3. In Windows File Explorer
    1. Delete the original geojson file
    2. Rename the new tmp geojson file, by removing the .tmp ending. The name will now match the original
4. You should be able to confirm your changes with GIT, and see the changes next time you open QGIS.

**Comment by MicheleTobias** [comment]
Thank you!

**Comment by wildintellect** [comment]
Updating with QGIS ticket information https://issues.qgis.org/issues/20760
