### ISSUE TITLE
chalk_hill

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#42]
# AVA: Chalk Hill (chalk_hill)

name | value
--- | ---
ava_id | chalk_hill
cfr_index | 9.52
revision | [T.D. ATF-155, 48 FR 48812, Oct. 21, 1983, as amended by T.D. ATF-272, 53 FR 17023, May 13, 1988]
state | CA
county | Sonoma
within | North Coast\|Northern Sonoma\|Russian River Valley\|Sonoma Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]
“Mark West Springs Quadrangle, California”, 7.5 minute series, 1958; and, “Healdsburg Quadrangle, California”, 7.5 minute series, 1955 
Photorevised 1980..

## Boundary [src]

(1) Southeasterly along Redwood Highway through Section 11, T. 8 N., R. 9 W., to the point of intersection with Windsor River Road; 
(2) Then westerly along Windsor River Road on the south boundary of Section 11, T. 8 N., R. 9 W., to the point of intersection with Starr Road; 
(3) The southerly along Starr Road to the point of intersection with the south line of Section 14, T. 8 N., R. 9 W.; 
(4) Then easterly along the south line of Sections 14 and 13, T. 8 N., R. 9 W. and Section 18, T. 8 N., R. 8 W., to the point of intersection with the Redwood Highway; 
(5) Then southeasterly along the Redwood Highway to the intersection with an unnamed road that intersects the Redwood Highway at a right angle from the northeast near the southwest corner of Section 28 near Mark West Creek, T. 8 N., R. 8 W.; 
(6) Then northeast approximately 500 feet along the unnamed road to its intersection with the Pacific Gas and Electric power transmission line; 
(7) Then northeast approximately 1,000 feet along the power transmission line 
(paralleling the unnamed road) to the point where the power transmission line turns in a northerly direction; 
(8) Then in a northerly direction along the power transmission line to the point of its intersection with the south line of Section 17, T. 8 N., R. 8 W.; 
(9) Then east along the south line of Sections 17, 16 and 15, T. 8 N., R. 8 W. to the point of intersection with Mark West Road on the “Mark West Quadrangle Map”; 
(10) Then northerly for approximately 1.3 miles along Mark West Road 
(which becomes Porter Creek Road), then northeasterly for approximately 1.7 miles on Porter Creek Road to its intersection with the unnamed medium duty road that parallels Porter Creek in Section 12, T. 8 N., R. 8 W.; then northeasterly on the Franz Valley Road over the Tarwater Grade and continuing along the Franz Valley Road for approximately 3 miles to its intersection with Franz Creek 
(approximately 2,000 feet west of the range line common to R. 7 W. and R. 8 W. in T. 9 N. and approximately 1,150 feet north of the north line of Section 25, T. 9 N., R. 8 W.); 
(11) Then westerly along Franz Creek to its point of intersection with the east line of Section 21, T. 9 N., R. 8 W.; 
(12) Then southerly along the east line of Section 21 to the southeast corner thereof; 
(13) Then southerly, approximately 0.08 mile, along the west line of section 27, T. 9 N., R. 8 W., to the point at which an unnamed unimproved road which parallels the south bank of Martin Creek intersects the west line of section 27,    T. 9 N., R. 8 W.; 
(14) Then southeasterly, approximately 1.07 miles, along said road to the point at which the road is crossed by the east line of section 27,   T. 9 N., R. 8 W.; 
(15) Then southerly, approximately 0.65 mile, along the east lines of sections 27 and 34, T. 9 N., R. 8 W., to the point in the northeast corner of section 34, T. 9 N., R. 8 W. where the north fork of Barnes Creek intersects such line in section 34, T. 9 N., R. 8 W.; 
(16) Then continuing along the north fork of Barnes Creek, approximately 0.5 mile, in a generally westerly direction to a small dwelling at the eastern terminus of an unnamed unimproved road 
(known locally as the access to the Shurtleff Ranch) in section 34, T. 9 N., R. 8 W.; 
(17) Then continuing in a generally westerly direction, approximately 1.4 miles, along the unnamed unimproved road 
(known locally as the access to the Shurtleff Ranch) to its intersection with an unnamed unimproved road 
(known locally as Spurgeon Road) in section 33, T. 9 N., R. 8 W. on the Healdsburg, California, Quadrangle Map; 
(18) Then westerly, approximately 0.45 mile, along the unnamed unimproved road 
(known locally as Spurgeon Road) to the point where the road intersects Chalk Hill Road in section 32, T. 9 N., R. 8 W.; 
(19) Then in a generally northwesterly direction, approximately 1.3 miles, along Chalk Hill Road to the point where Chalk Hill Road crosses Brooks Creek in section 29, T. 9 N., R. 8 W.; 
(20) Then north in a straight line, approximately 0.2 mile, to the top of a peak identified as Chalk Hill; 
(21) Then west-northwesterly in a straight line to the confluence of Brooks Creek and the Russian River; 
(22) Then westerly along the Russian River to the point of intersection with the range line common to R. 8 W. and R. 9 W. in T. 9 N.; 
(23) Then southwesterly in a straight line to the point of a hill identified as having an elevation of 737 feet; 
(24) Then south-southwesterly in a straight line to the point at the easterly terminus of Reiman Road; 
(25) Then southwesterly in a straight line to the point at the intersection of the township line common to T. 8 N. and T. 9 N. in R. 9 W. and the frontage road 
(a.k.a. Los Amigos Road) for U.S. Highway 101; 
(26) Then west approximately 3,000 feet along the township line common to T. 8 N. and T. 9 N. in R. 9 W.; 
(27) Then southerly for approximately 2,000 feet in a straight line to the point of intersection with an unnamed stream drainage; 
(28) Then east in a straight line to the point of intersection with Eastside Road; 
(29) Then northeasterly along Eastside Road to the point of intersection with Redwood Highway; 
(30) Then southeasterly along Redwood Highway to the point of beginning.

**Comment by SoominHur** [comment]
Reviewed.
- Edit created (effective) date in the attribute table.
- Add the beginning point description in the attribute table.
- (24) Edit the node locating westerly terminus in stead of "the easterly terminus of Reiman Road."
- Description from (25) - (28) is pretty unclear. For example, (25) it is hard to define what exactly "frontage road (a.k.a. Los Amigos Road) for U.S. Highway 101" is because there is no road labeled Los Amigos on the assigned map. On Google map, there is a road named Los Amigos but that road does not even exist in the assigned map (guess the Los Amigos in Google map must been built after the assigned map). Also in (27), the line should proceed toward (27) "the point of intersection with an unnamed stream drainage." However, in addition to the ambiguous descriptions in previous steps, approximate distance description makes unclear which unnamed stream it means. Followed the distance description as much as possible, but think it can be discussed or improved more.
