### ISSUE TITLE
chalone

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#43]
# AVA: Chalone (chalone)

name | value
--- | ---
ava_id | chalone
cfr_index | 9.24
revision | 
state | CA
county | Monterey|San Benito
within | Central Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c

**Comment by fyfangyao** [comment]
I am working on this.

**Comment by fyfangyao** [comment]
(1)“Mount Johnson, Cali, 7.5 minute series, 1968, photoinspected 1984;” 
(2) “Bickmore Canyon, Cali, 7.5 minute series, 1968, photoinspected 1984;” 
(3) “Soledad, Cali, 7.5 minute series, photoinspected 1984;”  
(4) “North Chalone Peak, Cali, 7.5 minute series, 1969, photoinspected 1984.”

**Comment by fyfangyao** [comment]
I have finished this one.

**Comment by SoominHur** [comment]
Reviewed. Edited cfr.author name in attribute table.
