### ISSUE TITLE
north coast and central coast

### ISSUE THREAD

**Issue by bizouwines** [UCDavisLibrary/ava#430]
North coast and central coast AVAs contain invalid/unsupported data that prevent uploading them to google my maps. Have converted to kml and checked file sizes, neither of those are the issue.

**Comment by MicheleTobias** [comment]
Thanks for the feedback!  We're currently in the process of reviewing the California AVAs.  I'll make a note for these two and we'll see if we can figure out what's causing the problem.

**Comment by MicheleTobias** [comment]
Could you share the process you're using to convert the files?  If I can replicate the problem, I'll be able to solve it more quickly.

**Comment by bizouwines** [comment]
I've been using https://geoconverter.hsr.ch/ to convert from geojson to
kml (have been setting the EPSGs too). From there I've been uploading the
kml files into google my maps. Here's the map I've been working on
<https://www.google.com/maps/d/u/0/edit?hl=en&hl=en&mid=13FzRnddkzt3-gy1agWE1aCzAGOvubTfW&ll=35.986129964496335%2C-117.87582757404232&z=6>
if that helps. Thanks for your help!

Adrienne

**Comment by MicheleTobias** [comment]
I created KML files for each state that we've finished.  They are in the AVAs By State folder.  All of them opened fine in Google Earth, so hopefully they will work in your web map.

Your webmap is off to a great start!  Can I link to it on our list of projects using our data?

**Comment by bizouwines** [comment]
Yeah I tried using the California one but it was too large to upload into
google my maps (it's a 5MB limit), so I've been trying to go through the
AVAs individually. When I go through the process described above for north
coast, central coast, monterey, and a few others, I get "The file contains
invalid or unsupported data, or the file is too large to parse" on Google
my maps. Is there anything you can think of that I can do from my end,
maybe a change to the conversion process, to fix this? North coast and
central coast contain most of our Californian wineries so I was hoping to
get them in there!
Thanks, and sure, go ahead and link it!

Adrienne

**Comment by MicheleTobias** [comment]
I loaded the central_coast.geojson file in QGIS and then exported it as KML.  It's only 400kb.  It opened in Google Earth.  Maybe that's the way to go?

**Comment by bizouwines** [comment]
I don't know any coding and most of this stuff is pretty new to me. I'm
going to stick with google my maps. Thank you for your help! Also, when you
link to our map, would you mind linking to where we have it on our website?
Here is the link: http://www.bizouwines.com/mapping-our-wines

Thanks!
