### ISSUE TITLE
champlain_valley_of_new_york

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#44]
# AVA: Champlain Valley of New York (champlain_valley_of_new_york)

name | value
--- | ---
ava_id | champlain_valley_of_new_york
cfr_index | 9.258
revision | [T.D. TTB-142, 81 FR 56491, Aug. 22, 2016]]
state | NY
county | Clinton|Essex
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Lake Champlain, N.Y.; VT.; N.H.; U.S.; CAN., 1962; revised 
U.S. area. 1972; and 
2. Glens Falls, N.Y.; VT.; N.H., 1956; revised 1972.

## Boundary [src]

(1) The beginning point is found on the Lake Champlain map at the intersection of the western shore of Lake Champlain and the U.S.-Canada border, just north of the town of Rouses Point. 
(2) From the beginning point, proceed south along the western shore of Lake Champlain approximately 109.4 miles, crossing onto the Glens Falls map, to a road marked on the map as State Route 73 
(now known as State Route 74) and known locally as Fort Ti Road, at the Fort Ticonderoga-Larrabees Point Ferry landing; then 
(3) Proceed west along State Route 73 
(State Route 74/Fort Ti Road) approximately 1.6 miles to State Route 22; then 
(4) Proceed north along State Route 22 approximately 21 miles, crossing onto the Lake Champlain map and passing through the town of Port Henry, to an unnamed light-duty road known locally as County Road 44 
(Stevenson Road); then 
(5) Proceed north along County Road 44 
(Stevenson Road) approximately 5.8 miles to a railroad track; then 
(6) Proceed northerly along the railroad track approximately 1.6 miles to State Route 9N, west of the town of Westport; then 
(7) Proceed westerly along State Route 9N approximately 4.1 miles to Interstate 87; then 
(8) Proceed north along Interstate 87 approximately 21 miles to the Ausable River, southwest of the town of Keeseville; then 
(9) Proceed west 
(upstream) along the Ausable River approximately 6 miles to a bridge connecting two unnamed light-duty roads known locally as Burke Road and Lower Road in the town of Clintonville, and proceed north along the bridge to Lower Road; then 
(10) Proceed west along Lower Road approximately 0.6 mile to State Route 9N; then 
(11) Proceed west along State Route 9N approximately 0.8 mile to an unnamed light-duty road known locally as County Route 39 
(Clintonville Road); then 
(12) Proceed north along County Route 39 
(Clintonville Road) approximately 1.5 miles to the second crossing of the Little Ausable River, west of Cook Mountain; then 
(13) Proceed northeast along the Little Ausable River approximately 3.5 miles to the confluence of the river with Furnace Brook, near the town of Harkness; then 
(14) Proceed west along Furnace Brook approximately 0.17 mile to an unnamed light-duty road known locally as County Route 40 
(Calkins Road); then 
(15) Proceed north along County Route 40 
(Calkins Road) approximately 5.8 miles to an unnamed light-duty road known locally as County Route 35 
(Peasleeville Road), south of an unnamed creek known locally as Arnold Brook; then 
(16) Proceed west along County Route 35 
(Peasleeville Road) approximately 0.1 mile to an unnamed light-duty road known locally as Connors Road; then 
(17) Proceed north along Connors Road approximately 2.1 miles, crossing the Salmon River, to an unnamed light-duty road known locally as County Route 33 
(Norrisville Road); then 
(18) Proceed west along County Route 33 
(Norrisville Road) approximately 1.2 miles to an unnamed light-duty road known locally as Shingle Street; then 
(19) Proceed north along Shingle Street approximately 4 miles to an unnamed light-duty road known locally as County Route 31 
(Rabideau Street); then 
(20) Proceed west along County Route 31 
(Rabideau Street) approximately 0.4 mile to an unnamed light-duty road known locally as Goddeau Street; then 
(21) Proceed north along Goddeau Street approximately 0.9 mile, crossing the Saranac River, to State Route 3 just east of the town of Cadyville; then 
(22) Proceed east along State Route 3 approximately 0.5 mile to an unnamed light-duty road known locally as Akey Road; then 
(23) Proceed north on Akey Road approximately 0.2 mile to State Route 374; then 
(24) Proceed east along State Route 374 approximately 3.6 miles to State Route 190, also known locally as Military Turnpike; then 
(25) Proceed northwest along State Route 190 
(Military Turnpike) approximately 15.2 miles to an unnamed light-duty road just east of Park Brook known locally as County Route 12 
(Alder Bend Road), northwest of Miner Lake State Park; then 
(26) Proceed north along County Route 12 
(Alder Bend Road) approximately 3 miles to U.S. Highway 11; then 
(27) Proceed west along U.S. Highway 11 approximately 1.7 miles to an unnamed light-duty road known locally as County Route 10 
(Cannon Corners Road); then 
(28) Proceed north along County Route 10 
(Cannon Corners Road) approximately 6 miles to the U.S.-Canada border; then 
(29) Proceed east along the U.S.-Canada border approximately 19.8 miles, returning to the beginning point.

**Comment by elistockwell** [comment]
The existing ava clearly used a source other than the approved maps, but cited them. I redid it with the approved maps, although in what I assume is a typo the document lists them as 1:100,000 scale, when maps with those names and years only exist in 1:250,000. I also had to use a few smaller scale maps for the US-Canada border on the northern side of the AVA.
