### ISSUE TITLE
Incorrect AVA names

### ISSUE THREAD

**Issue by kurtishouser** [UCDavisLibrary/ava#446]
The following AVA names have issues.
- Green Valley of Russian River -> Green Valley of Russian River Valley (filename update required too)
- Kelsey Bench–Lake County - Kelsey Bench-Lake County (different hyphen character)
- Knights Valley -> trailing space
- Lewis–Clark Valley -> Lewis-Clark Valley (different hyphen character)
- North_Fork_Of_Roanoke -> North Fork of Roanoke
- Rutherford -> trailing space
- Saddle Rock- Malibu -> Saddle Rock-Malibu (extra pace after hyphen, filename update required too)
- Virginia’s Eastern Shore -> trailing space

Although perhaps minor, the alternate hyphen character and a double hyphen (Pine Mountain--Cloverdale Peak) is also present in the `within` and `contains` properties so this will need to be corrected as well.

Since this will require updating some filenames and it also appears that there is a review underway with the CA AVAs, perhaps it's best if someone directly associated with the project makes the changes. I don't want to interfere with any established git workflow.

**Comment by MicheleTobias** [comment]
Thank you.  I think it is best to handle these changes in a batch process once we've finished all of the planned AVA boundaries.

**Comment by kurtishouser** [comment]
Maybe add the `Quality Control` label to this issue?
