### ISSUE TITLE
chehalem_mountains

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#45]
# AVA: Chehalem Mountains (chehalem_mountains)

name | value
--- | ---
ava_id | chehalem_mountains
cfr_index | 9.205
revision | [T.D. TTB-56, 71 FR 68462, Nov. 27, 2006]
state | OR
county | Clackamas|Washington|Yamhill
within | Willamette Valley
contains | Ribbon Ridge

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Newberg Quadrangle, Oregon, 7.5 Minute Series, 1961 
photorevised 1985.; 
2. Dundee Quadrangle, Oregon, 7.5 Minute Series, 1956 
revised 1993.; 
3. Laurelwood Quadrangle, Oregon, 7.5 Minutes Series 1956 
revised 1992.; 
4. Scholls Quadrangle, Oregon, 7.5 Minute Series, 1961 
photorevised 1985.; 
5. Beaverton Quadrangle, Oregon, 7.5 Minute Series, 1961 
photorevised 1984.; and 
6. Sherwood Quadrangle, Oregon, 7.5 Minute Series, 1961 
photorevised 1985..

## Boundary [src]

(1) The beginning point is in Yamhill County on the Newberg map in section 15, T3S/R2W, at the intersection of Oregon Highway 99W and the 250-foot contour line, 0.4 mile east of Spring Brook; 
(2) From the beginning point, proceed northwesterly 1.2 miles along the 250-foot contour to its intersection with an unnamed light-duty road locally known as Benjamin Road, section 50, T3S/R2W, Newberg map; then 
(3) Proceed west 0.5 mile along Benjamin Road, crossing railroad tracks, to its intersection with an unnamed light-duty road locally known as Spring Brook Road, section 48, T3S/R2W, Newberg map; then 
(4) Proceed southwest 0.3 mile along Spring Brook Road, parallel to the railroad tracks, to its intersection with an unnamed light-duty road locally known as Mountainview Drive, section 48, T3S/R2W, on the Newberg map; then 
(5) Proceed west 0.35 mile on Mountainview Drive to its intersection with an unnamed light-duty road locally known as Aspen Way, along the western boundary of section 8, T3S/R2W, Newberg map; then 
(6) Proceed northwesterly 1.4 miles on Aspen Way to its intersection with Bell Road, along the northern boundary of section 47, T3S/R2W, Newberg map; then 
(7) Proceed west 0.8 mile on Bell Road, which becomes North Valley Road after crossing Oregon Highway 219, to its intersection with the 250-foot contour line, immediately before an unimproved dirt road on the left, section 46, T3S/R2W, Newberg map; then 
(8) Proceed westerly 2 miles along the 250-foot contour line to its first intersection with the western boundary line of section 43, T3S/R3W, along the western border of the Newberg map; then 
(9) Proceed north 0.2 mile along the western boundary of section 43, T3S/R3W, to its intersection with the 240-foot contour line, Newberg map; then 
(10) Proceed westerly for 4 miles along the 240-foot contour line, crossing onto the Dundee map, to its intersection with an unnamed light-duty road locally known as Sullivan Lane, section 74, T3S/R3, Dundee map; then 
(11) Proceed south 0.25 mile along Sullivan Lane to its intersection with North Valley Road at elevation point 216, section 74, T3S/R3, Dundee map; then 
(12) Proceed west 0.1 mile along North Valley Road to its intersection with the 200-foot contour line, section 74, T3S/R3W, Dundee map; then 
(13) Proceed northwesterly 1 mile along the 200-foot contour line to its intersection with an unnamed creek northeast of elevation point 215, and continue northwesterly 0.05 mile along the unnamed creek to its intersection with Dopp Road along the western boundary line of section 74, T3S/R3W, Dundee map; then 
(14) Proceed south 0.8 mile along Dopp Road to its intersection with North Valley Road at the elevation point 202 near the Ewing Young School, section 39, T3S/R3W, Dundee map; then 
(15) Proceed northerly 5 miles on North Valley Road, crossing onto the Laurelwood map, to the road&#39;s intersection with Laughlin Road and Albertson Road at elevation point 235, section 58, T2S/R3W, Laurelwood map; then 
(16) Proceed east 0.1 mile on Albertson Road to its intersection with the 240-foot contour line, section 58, T2S/R3W, Laurelwood map; then 
(17) Proceed northerly 15.6 miles along the 240-foot contour line to its intersection with Sandstrom Road, section 19, T1S/R3W, Laurelwood map; then 
(18) Proceed west 0.15 mile on Sandstrom Road to its third crossing of the 200-foot contour line, just before Fern Hill Road to the west, section 24, T1S/R4W, Laurelwood map; then 
(19) Proceed northwesterly and then northeasterly 4.5 miles along the meandering 200-foot contour line to its intersection with La Follette Road along the eastern boundary of section 8, T1S/R3W, Laurelwood map; then 
(20) Proceed south 0.25 mile on La Follette Road to its intersection with the 240-foot contour line, north of Blooming Fern Hill Road, along the western boundary line of section 16, T1S/R3W, Laurelwood map; then 
(21) Proceed easterly and then southerly 17 miles along the meandering 240-foot contour line, crossing over and back on the Scholls map in section 25 and 56, T1S/R3W, crossing Christensen Creek in section 35, T1S/R3W, and continuing to the contour line&#39;s intersection with Laurel Road West, along the southern boundary line of section 1, T2S/R3W, Laurelwood map; then 
(22) Proceed east 0.15 mile on Laurel Road West to its intersection with the 200-foot contour line, along the southern boundary line of section 1, T2S/R3W, Laurelwood map; then 
(23) Proceed easterly 17.5 miles along the meandering 200-foot contour line, and, after crossing onto the Scholls map and crossing over Laurel Road South, McCormick Hill Road four times, and Midway Road, and after crossing over and back on the Newberg map 
(crossing Heaton Creek) in section 28, T2S/R2W, continue to the contour line&#39;s intersection with Mountain Home Road, east of Heaton Creek, section 21, T2S/R2W, Scholls map; then 
(24) Continue easterly and then southerly 8.9 miles along the 200-foot contour line and, after crossing Baker Creek, skirting Laurel Ridge to the north, crossing onto the Beaverton map, crossing over and back on the Sherwood map, crossing over in the northwest corner of the Beaverton map, and returning to the Scholls map, continue to the contour line&#39;s intersection with the middle tributary of an unnamed creek, along the western boundary line of section 24, T2S/R2W, Scholls map; then 
(25) Proceed southeast along the meandering 200-foot contour line and, after crossing over to the northeast corner of the Newberg map to the Sherwood map, continue to the contour line&#39;s intersection with Edy Road, section 25, T2S/R2W, Sherwood map; then 
(26) Proceed southwest along the meandering 200-foot contour line and, after crossing onto the Newberg map, skirting part of Chicken Creek, and returning to the Sherwood map, continue to the contour line&#39;s intersection with Elwert Road, along the eastern boundary line of section 25, T2S/R2W, Sherwood map; then 
(27) Proceed south 0.85 mile on Elwert Road to its intersection with Oregon Highway 99W, along the eastern boundary line of section 36, T2S/R2W, Sherwood map; then 
(28) Proceed south-southwest 0.45 mile on Oregon Highway 99W to its intersection with the 250-foot contour line immediately south of an unnamed Cedar Creek tributary, section 36, T2S/R2W, Sherwood map; then 
(29) Proceed southerly 1 mile along the meandering 250-foot contour line to its intersection with Middleton Road, section 1, T3S/R2W, Sherwood map; then 
(30) Proceed southwesterly 0.5 mile on Middleton Road, which becomes Rein Road, to the road&#39;s intersection with the 200-foot contour line, immediately south of Cedar Creek, section 1, T3S/R2W, Sherwood map; then 
(31) Proceed 1.6 miles generally east along the 200-foot contour line to its intersection, in the village of Middleton, with an unnamed light-duty east-west road locally known as Brookman Road, section 6, T3S/R1W, Sherwood map; then 
(32) Proceed easterly 0.7 mile on Brookman Road to its intersection with the Washington-Clackamas County line, at the northwest corner of section 5, T3S/R1W, Sherwood map; then 
(33) Proceed east 1 mile along the Washington-Clackamas County line to its intersection with Brown Road, at the northeast corner of section 5, T3S/R1W, Sherwood map; then 
(34) Proceed southerly 1 mile on Brown Road to its second intersection with the 250-foot contour line, immediately south of an intermittent stream, in section 4, T3S/R1W, Sherwood map; then 
(35) Proceed southerly 2.8 miles along the meandering 250-foot contour line, skirting Hoodview, to the contour line&#39;s intersection with Baker Road, section 16, T3S/R1W, Sherwood map; then 
(36) Proceed south 0.15 mile on Baker Road to its intersection with the 200-foot contour line, section 16, T3S/R1W, Sherwood map; then 
(37) Proceed southwesterly 13.1 miles along the meandering 200-foot contour line and, after crossing onto the Newberg map, continue to the contour line&#39;s intersection with Wilsonville Road, north of Willamette Greenway State Park, section 60, T3S/R2W, Newberg map; then 
(38) Proceed northwesterly 2 miles on Wilsonville Road to its intersection with an unnamed tributary of Spring Brook, east-northeast of Grouse Butte, section 57, T3S/R2W, Newberg map; then 
(39) Proceed southwesterly 0.25 mile along the unnamed tributary of Spring Brook to its intersection with the 200-foot contour line, section 57, T3S/R2W, Newberg map; then 
(40) Proceed westerly and then northerly 0.45 mile along the 200-foot contour line, following the base of Grouse Butte, to the contour line&#39;s intersection with Wilsonville Road, section 57, T3S/R2W, Newberg map; then 
(41) Proceed east 0.45 mile on Wilsonville Road to its intersection with the same unnamed tributary of Spring Brook, section 57, T3S/R2W, Newberg map; then 
(42) Proceed northeasterly 0.05 mile along the unnamed tributary of Spring Brook to its intersection with the 250-foot contour line, southwest of the quarries, section 57, T3S/R2W, Newberg map; then 
(43) Proceed northerly 2.2 miles along the 250-foot contour line to its intersection with Corral Creek Road 
(misnamed Ladd Hill Road on the Newberg map), south of Oregon Highway 99W, section 15, T3S/R2W, Newberg map; then 
(44) Proceed north 0.5 mile along Corral Creek Road to its western-most intersection with an unnamed light-duty road locally known as Veritas Lane, section 15, T3S/R2W, Newberg map; then 
(45) Proceed north-northwesterly in a straight line approximately 0.05 mile and return to the beginning point.

**Comment by gdmf** [comment]
Please tag chehalem_mountains as "In Progress". Thanks!

**Comment by MicheleTobias** [comment]
Will do!  Welcome to the project!  Let me know if you have any questions.

**Comment by alisonsnwong** [comment]
Checked! Made changes in step 9 and performed minor boundary edits.
