### ISSUE TITLE
Dry Creek Valley

### ISSUE THREAD

**Issue by sdelong** [UCDavisLibrary/ava#456]
There is an error in (28), which is a the northern border of the AVA:

(28) Then northerly along the east line of Sections 18, 7, and 6, T. 9 N., R. 11 W., continuing along the east line of Sections 31, 30, 19, 18, 7, and 6, T. 10 N., R. 11 W. to the point of intersection with latitude line 38 degrees 45 minutes on the “Warm Springs Dam Quadrangle” map;

Currently, the line goes north of 38 degrees 45 minutes onto the the Cloverdale Map, which is not an approved map for the AVA

**Comment by MicheleTobias** [comment]
Thanks! This is helpful!  If you can, I'd like to have this information on the original issue for the AVA.  It's #63  You can find the closed one by changing the filter on the Issues search bar.  I usually just delete "is: open" or you can click on the closed link.

**Comment by sdelong** [comment]
OK - thanks I'll do that in the future!

**Comment by MicheleTobias** [comment]
Thanks!  I transferred your comment to #63 and reopened it so I'll close this one.
