### ISSUE TITLE
chiles_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#46]
# AVA: Chiles Valley (chiles_valley)

name | value
--- | ---
ava_id | chiles_valley
cfr_index | 9.154
revision | [T.D. ATF-408, 64 FR 7787, Feb. 17, 1999]
state | CA
county | Napa
within | Napa Valley\|North Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. St. Helena, CA 1960 photorevised 1980; 
2. Rutherford, CA 1951 photorevised 1968; 
3. Chiles Valley, CA 1958 photorevised 1980; 
4. Yountville, CA 1951 photorevised 1968.

## Boundary [src]

(1) Beginning on the St. Helena, CA quadrangle map at the northernmost corner of Rancho Catacula in Section 34, Township 9 North 
(T9N), Range 5 West 
(R5W), Mount Diablo Base and Meridian 
(MDBM); 
(2) Then in southwesterly direction along the Rancho Catacula boundary line to its intersection with the Rancho La Jota boundary line; 
(3) Then in a south-southeasterly direction approximately 3,800 feet along the Rancho Catacula/Rancho La Jota boundary line to the point where the Rancho Catacula boundary separates from the common boundary with Rancho La Jota; 
(4) Then in a southeasterly direction continuing along the Rancho Catacula boundary approximately 23,600 feet to a point of intersection, in the NE   Sec. 19, T8N, R4W, on the Chiles Valley quadrangle map, with a county road known locally as Chiles and Pope Valley Road; 
(5) Then in a southwesterly direction along Chiles and Pope Valley Road to a point where it first crosses an unnamed blueline stream in the SE   Section 19, T8N, R4W; 
(6) Then following the unnamed stream in generally southeast direction to its intersection with the 1200 foot contour; 
(7) Then following the 1200 foot contour in a northeasterly direction to a point of intersection with the Rancho Catacula boundary in section 20, T8N, R4W; 
(8) Then in a southeasterly direction along the Rancho Catcula boundary approximately 17,500 feet to the southwest corner of Rancho Catacula in section 34, T8N, R4W on the Yountville, CA, quadrangle map; 
(9) Then in a northeasterly direction along the Rancho Catacula boundary approximately 650 feet to its intersection with the 1040 foot contour; 
(10) Then along the 1040 foot contour in a generally east and northeast direction to its intersection with the Rancho Catacula boundary; 
(11) Then in a northeasterly direction along the Rancho Catacula boundary approximately 1100 feet to its intersection with the 1040 foot contour; 
(12) Then along the 1040 foot contour in an easterly direction and then in a northwesterly direction to its intersection of the Rancho Catacula boundary; 
(13) Then in a southwesterly direction along the Rancho Catacula boundary approximately 300 feet to a point of intersection with a line of high voltage power lines; 
(14) Then in a westerly direction along the high voltage line approximately 650 feet to its intersection with the 1000 foot contour; 
(15) Then continuing along the 1000 foot contour in a generally northwesterly direction to the point of intersection with the first unnamed blueline stream; 
(16) Then along the unnamed stream in a northerly direction to its point of intersection with the 1200 foot contour; 
(17) Then along the 1200 foot contour in a northwesterly direction to its points of intersection with the Rancho Catacula boundary in Section 35, T9N, R5W on the St. Helena, CA, quadrangle map; 
(18) Then along the Rancho Catacula boundary in a northwesterly direction approximately 5,350 feet to a northernmost corner of Rancho Catacula, the beginning point on the St. Helena quadrangle map a the northernmost corner of Rancho Catacula in Section 34, T9N, R5W, MDBM.

**Comment by SoominHur** [comment]
Reviewed. Corrected created date.
