### ISSUE TITLE
Missing Oregon AVAs

### ISSUE THREAD

**Issue by mossrussell** [UCDavisLibrary/ava#463]
This is a great repository :)  It looks like y'all are missing the shapefile for the Yamhill-Carlton AVA and the Van Duzer Corridor AVA in Oregon.  It would be awesome if there's a way to get those up too :) I'm not sure how to help with that.

**Comment by MicheleTobias** [comment]
We aren't finished creating AVAs - see the issues list for what's still ongoing. The ReadMe has instructions on how to help.
