### ISSUE TITLE
cienega_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#47]
# AVA: Cienega Valley (cienega_valley)

name | value
--- | ---
ava_id | cienega_valley
cfr_index | 9.38
revision | [T.D. ATF-109, 47 FR 36126, Aug. 19, 1982]
state | CA
county | San Benito
within | Central Coast\|San Benito
contains | Lime Kiln Valley

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Hollister Quadrangle, California,” 7.5 minute series 
1971.; 
2. “Tres Pinos Quadrangle, California,” 7.5 minute series 
1971.; 
3. “Mt. Harlan Quadrangle, California,” 7.5 minute series 
1968.; and 
4. “Paicines Quadrangle, California,” 7.5 minute series 
1968..

## Boundary [src]

(1) From the beginning point, the boundary follows the Pescadero Creek Bed in a southeasterly direction about 100 feet to the unimproved road and continues southwesterly on the unimproved road .5 mile to where it intersects with the south border of Township 14 South, Range 6 East, Section 21; 
(2) Thence in a straight line to the southwest portion of Section 28, Township 14 South, Range 6 East, where the 1400-foot contour line intersects the south border of Section 28; 
(3) Thence following the 1400-foot contour line through the following sections; Sections 28, 29, and 30, Township 14 South, Range 6 East; Section 25, Township 14 South, Range 5 East; Sections 30, 19, 20, and returning to 19, Township 14 South, Range 6 East, to a point where the 1400-foot contour line intersects with the section line between Sections 19 and 18, Township 14 South, Range 6 East; 
(4) Thence in a straight line due north to the intersection with the 1200-foot contour line in Section 18, Township 14 South, Range 6 East; 
(5) Thence following the 1200-foot contour line in a generally northwesterly direction to where it intersects with the north boundary of Township 14 South, Range 5 East, Section 10; then following this boundary line in a northwesterly direction to where this boundary intersects with the 1600-foot contour line; thence following the 1600-foot contour line in a generally northerly direction to where it intersects with the unimproved road; 
(6) Thence looping southward along the unimproved road and continuing on in an easterly direction past the designated “Spring” and then in a northeasterly direction parallel with the Gulch to the Vineyard School on Cienega Road; thence in a southeasterly direction on Cienega Road .4 mile to where the unimproved road intersects; thence traveling north and following the unimproved road in a northwesterly direction about 5. mile; then looping in an easterly direction .75 mile to the intersection of the unimproved road and branching in a southeasterly direction; 
(7) Thence crossing Township 13 South to Township 14 South and following the unimproved road to the intersection of the western border of Township 14 South, Range 6 East, Section 6; thence south to the northwest corner of Section 7; 
(8) Thence continuing in a straight diagonal line to the southeast corner of Township 14 South, Range 6 East, Section 7; thence from the southeast corner of Section 7 .25 mile west to where it intersects with an unimproved road; 
(9) Thence following this unimproved road in a southeasterly direction to the Gaging Station, the point of beginning.

**Comment by fyfangyao** [comment]
I am working on it.

**Comment by fyfangyao** [comment]
I use (1)“Hollister Quadrangle, Cali, 7.5 minute series, 1955, revised 1973;” (2) “Tres Pinos Quadrangle, Cali, 7.5 minute series, 1955, revised 1972;” (3) “SMt. Harlan Quadrangle, Cali, 7.5 minute series, 1968, revised 1971;”  and (4) “Paicines Quadrangle, Cali, 7.5 minute series, 1968, revised 1971.”
