### ISSUE TITLE
van_duzer_corridor

### ISSUE THREAD

**Issue by ericallanwest** [UCDavisLibrary/ava#472]
[§9.265 - Van Duzer Corridor](https://www.ecfr.gov/cgi-bin/text-idx?c=ecfr;sid=33fc0c0194b58b6fe95208945b5c637a;rgn=div5;view=text;node=27:1.0.1.1.7;idno=27;cc=ecfr#se27.1.9_1265)

(a) _Name._ The name of the viticultural area described in this section is "Van Duzer Corridor". For purposes of part 4 of this chapter, "Van Duzer Corridor" is a term of viticultural significance.

(b) _Approved maps._ The five United States Geological Survey (USGS) 1:24,000 scale topographic maps used to determine the boundary of the Van Duzer Corridor viticultural area are titled:

(1) [Sheridan, Oreg., 1956; revised 1992](https://ngmdb.usgs.gov/ht-bin/tv_browse.pl?id=8f3661351c7057cc84163431babd8da0&fmt=tif);

(2) [Ballston, Oreg., 1956; revised 1992](https://ngmdb.usgs.gov/ht-bin/tv_browse.pl?id=9ee27c8dfa6baad3f1f6f7009aae4328&fmt=tif);

(3) [Dallas, Oreg., 1974; photorevised 1986](https://ngmdb.usgs.gov/ht-bin/tv_browse.pl?id=13ab4960e538af6a757a125e18c8ff48&fmt=tif);

(4) [Amity, Oreg., 1957; revised 1993](https://ngmdb.usgs.gov/ht-bin/tv_browse.pl?id=3f17e112aa2286784a750353a6210b67&fmt=tif); and

(5) [Rickreall, Oreg., 1969; photorevised 1976](https://ngmdb.usgs.gov/ht-bin/tv_browse.pl?id=18c9b4ea6a75a1d9c6af74d964802965&fmt=tif);

(c) _Boundary._ The Van Duzer Corridor viticultural area is located in Polk and Yamhill Counties, in Oregon. The boundary of the Van Duzer Corridor viticultural area is as described below:

(1) The beginning point is on the Sheridan map at the intersection of State Highway 22 and Red Prairie Road. From the beginning point, proceed southeasterly along State Highway 22 for a total of 12.4 miles, crossing over the Ballston and Dallas maps and onto the Rickreall map, to the intersection of the highway with the 200-foot elevation contour west of the Oak Knoll Golf Course; then

(2) Proceed north on the 200-foot elevation contour, crossing onto the Amity map, to the third intersection of the elevation contour with Frizzell Road; then

(3) Proceed east on Frizzell Road for 0.3 mile to the intersection of the road with Oak Grove Road; then

(4) Proceed north along Oak Grove Road for 1.7 miles to the intersection of the road with Zena Road; then

(5) Proceed east on Zena Road for approximately 0.25 mile to the second intersection of the road with the 200-foot elevation contour; then

(6) Proceed northwest along the 200-foot elevation contour to the intersection of the elevation contour with Oak Grove Road; then

(7) Proceed north along Oak Grove Road (which becomes Old Bethel Road) approximately 7.75 miles to the intersection of the road with Patty Lane; then

(8) Proceed west in a straight line for a total of 10.8 miles, crossing over the Ballston map and onto the Sheridan map, to the intersection of the line with State Highway 18; then

(9) Proceed southwest along State Highway 18 for 0.3 miles to the intersection of the highway with Red Prairie Road; then

(10) Proceed south along Red Prairie Road for approximately 5.3 miles, returning to the beginning point.

[T.D. TTB-155, [83 FR 64280](https://www.govinfo.gov/app/details/FR-2018-12-14/2018-27017), Dec. 14,2018]

**Comment by sdelong** [comment]
What is the issue?

**Comment by ericallanwest** [comment]
There have been 5 AVAs created in the past few years, including this one. @MicheleTobias suggested I create issues for them.

**Comment by sdelong** [comment]
Great - sorry - I have Van Duzer Corridor done  - I'll upload it in the next few days.

**Comment by ericallanwest** [comment]
I wasn't able to label these as issues as **AVA**, so I understand the confusion. I'm currently working on the new AVAs in the Eastern US.

**Comment by MicheleTobias** [comment]
I put the labels on them.  Thanks for making the issues.  It will help us track what's going on similarly to the other ones.

**Comment by ericallanwest** [comment]
The Virginia Tech label can be removed.

**Comment by alisonsnwong** [comment]
Checked! Fixed step 4.
