### ISSUE TITLE
crest_of_the_blue_ridge_henderson_county

### ISSUE THREAD

**Issue by ericallanwest** [UCDavisLibrary/ava#473]
[§9.266 - Crest of the Blue Ridge Henderson County](https://www.ecfr.gov/cgi-bin/text-idx?c=ecfr;sid=33fc0c0194b58b6fe95208945b5c637a;rgn=div5;view=text;node=27:1.0.1.1.7;idno=27;cc=ecfr#se27.1.9_1266)

(a) _Name._ The name of the viticultural area described in this section is “Crest of the Blue Ridge Henderson County”. For purposes of part 4 of this chapter, “Crest of the Blue Ridge Henderson County” is a term of viticultural significance.

(b) _Approved maps._ The nine United States Geological Survey (USGS) 1:24,000 scale topographic maps used to determine the boundary of the Crest of the Blue Ridge Henderson County viticultural area are titled:

(1) [Black Mountain, North Carolina, 1941; photorevised 1978](https://ngmdb.usgs.gov/ht-bin/tv_browse.pl?id=58a6e802a80608373653038057fa9ad7&fmt=tif);

(2) [Bat Cave, North Carolina, 1997](https://ngmdb.usgs.gov/ht-bin/tv_browse.pl?id=5368b3634f78f9fdf2c2aa4bf181ceff&fmt=tif);

(3) [Cliffield Mountain, North Carolina, 1946; photorevised 1991](https://ngmdb.usgs.gov/ht-bin/tv_browse.pl?id=4e7b15ee6673c56d75103e166c0a93bc&fmt=tif);

(4) [Saluda, North Carolina-South Carolina, 1983 (provisional edition)](https://ngmdb.usgs.gov/ht-bin/tv_browse.pl?id=6a54ec2d15bc268c58ec07cc858df770&fmt=tif);

(5) [Zirconia, North Carolina-South Carolina, 1997](https://ngmdb.usgs.gov/ht-bin/tv_browse.pl?id=6ef70d79bf0e6cea16636ab0ea5b0713&fmt=tif);

(6) [Standingstone Mountain, South Carolina-North Carolina, 1997](https://ngmdb.usgs.gov/ht-bin/tv_browse.pl?id=802c8f4cdc61971c1ba3464c7df7a82e&fmt=tif);

(7) [Horse Shoe, North Carolina, 1997](https://ngmdb.usgs.gov/ht-bin/tv_browse.pl?id=c2ec41ef291e57ea7003dc79328830f5&fmt=tif);

(8) [Hendersonville, North Carolina, 1997](https://ngmdb.usgs.gov/ht-bin/tv_browse.pl?id=233fe0ce09032d2d35493989f3bbe77c&fmt=tif); and

(9) [Fruitland, North Carolina, 1997](https://ngmdb.usgs.gov/ht-bin/tv_browse.pl?id=0ef90f53a53ff301542b91ac4cc4859a&fmt=tif).

(c) _Boundary._ The Crest of the Blue Ridge Henderson County viticultural area is located in Henderson County, North Carolina. The boundary of the Crest of the Blue Ridge Henderson County viticultural area is as described below:

(1) The beginning point is on the Black Mountain map at the 4,412-foot elevation marker atop Little Pisgah Mountain, along the shared Buncombe-Henderson county line. From the beginning point, proceed southeast along the Buncombe-Henderson county line approximately 4.4 miles, crossing onto the Bat Cave map, to the intersection of the Buncombe-Henderson county line with the shared Henderson-Rutherford county line; then

(2) Proceed southerly along the shared Henderson-Rutherford county line approximately 5.1 miles to its intersection with the Polk county line; then

(3) Proceed southwest along the shared Henderson-Polk county line approximately 14.9 miles, crossing over the Cliffield Mountain map and onto the Saluda map, to its intersection with the North Carolina-South Carolina border; then

(4) Proceed westerly along the North Carolina-South Carolina border approximately 8.1 miles, crossing onto the Zirconia map, to the 3,058-foot elevation marker atop Big Top Mountain; then

(5) Proceed northwest in a straight line approximately 2.0 miles, crossing onto the Standingstone Mountain map, to the center of the highest closing contour atop Maybin Mountain; then

(6) Proceed northeast in a straight line approximately 2.2 miles, crossing back onto the Zirconia map, to the intersection of an unnamed road, known locally as County Road 1113/Maybin Road, with Mountain Valley Road, also known as County Road 1109/Cabin Creek Road; then

(7) Proceed northwest along Mountain Valley Road/County Road 1109/Cabin Creek Road approximately 1.3 miles, crossing back onto the Standingstone Mountain map, to its intersection with Pinnacle Mountain Road; then

(8) Proceed northwest in a straight line approximately 1.0 mile to the intersection of Little Cove Creek with the 2,800-foot elevation contour; then

(9) Proceed westerly along the 2,800-foot elevation contour approximately 2.4 miles to its intersection with an unnamed creek on the north slope of Stone Mountain that flows into Jeffers Lake; then

(10) Proceed southwest in a straight line approximately 2.0 miles to the intersection of the shared Henderson-Transylvania county line with the Dupont State Forest boundary atop Hickory Mountain; then

(11) Proceed northeast along the Henderson-Transylvania county line approximately 2.6 miles, crossing onto the Horse Shoe map, to its intersection with an unnamed road, known locally as Clipper Lane, on the hilltop above the Sentell Cemetery; then

(12) Proceed northeast in a straight line approximately 1.6 miles to the center of the highest closing contour atop Jeter Mountain; then

(13) Proceed southeast in a straight line approximately 1.3 miles to the center of the highest closing contour atop Evans Mountain; then

(14) Proceed northeast in a straight line approximately 2.0 miles to the center of the highest closing contour atop Wolf Mountain; then

(15) Proceed northeast in a straight line approximately 1.2 miles to the center of the highest closing contour atop Drake Mountain; then

(16) Proceed northwest in a straight line approximately 0.7 mile to the center of the highest closing contour atop Cantrell Mountain; then

(17) Proceed northeast in a straight line approximately 3.3 miles to the 2,618-foot elevation marker on the northeast slope of Long John Mountain; then

(18) Proceed northeast in a straight line approximately 1.4 miles, crossing onto the Hendersonville map, to the center of the highest closing contour atop Stoney Mountain; then

(19) Proceed northeast in a straight line approximately 0.6 mile to the intersection of Brookside Camp Road with Dixie Highway; then

(20) Proceed northeast along Brookside Camp Road approximately 2.1 miles, crossing onto the Fruitland map, to its intersection with Locust Grove Road; then

(21) Proceed northeast along Locust Grove Road approximately 1.4 miles to its intersection with an unnamed trail near Locust Grove Church; then

(22) Proceed northeast in a straight line approximately 0.7 mile to the 3,442-foot elevation marker atop Rich Mountain; then

(23) Proceed northwest in a straight line approximately 0.4 mile to the intersection of Southern Leveston Road with an unnamed jeep trail; then

(24) Proceed northwest along Southern Leveston Road approximately 2.4 miles to its intersection with Hoopers Creek Road; then

(25) Proceed northeast in a straight line approximately 0.7 mile to the 2,983-foot elevation marker labeled Edneyville-5 atop a peak on Burney Mountain along the shared Henderson-Buncombe county line; then

(26) Proceed northeast along the Henderson-Buncombe county line approximately 8.2 miles, crossing onto the Black Mountain map, and return to the beginning point atop Little Pisgah Mountain.

[T.D. TTB-156, [84 FR 34784](https://www.govinfo.gov/app/details/FR-2019-07-19/2019-15353), July 19, 2019]

**Comment by ericallanwest** [comment]
I believe this issue can be closed as a result of PR #478.

**Comment by davidkli** [comment]
This AVA has been checked and the boundary is good. No edits needed to be made.
