### ISSUE TITLE
clear_lake

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#49]
# AVA: Clear Lake (clear_lake)

name | value
--- | ---
ava_id | clear_lake
cfr_index | 9.99
revision | [T.D. ATF-174, 49 FR 19468, May 8, 1984]
state | CA
county | Lake
within | North Coast
contains | Big Valley District–Lake County\|High Valley\|Kelsey Bench–Lake County\|Red Hills Lake County

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Lower Lake Quadrangle, California,” 15 minute series, 1958; 
2. “Clearlake Oaks Quadrangle, California,” 15 minute series, 1960; 
3. “Lakeport Quadrangle, California,” 15 minute series, 1958; 
4. “Kelseyville Quadrangle, California,” 15 minute series, 1959.

## Boundary [src]
Lower Lake Quadrangle Map  
(15 minute series); From the beginning point on Mt. Hannah in Section 16, Township 12 North 
(T12N), Range 8 West 
(R8W), identified as having an elevation of 3,978 feet, the boundary runs— 
(1) East-southeasterly in a straight line to the point on Seigler Mountain in Section 23, T12N/R8W, identified as having an elevation of 3,692 feet; 
(2) Then east-southeasterly in a straight line to the point on Childers Peak in Section 34, T12N/R7W, identified as having an elevation of 2,188 feet; 
(3) Then east-northeasterly in a straight line to the point on the southeast corner of Section 25, T12N/R7W; 
(4) Then northeasterly in a straight line to the point in Section 16, T12N/R6W, identified as being the “Baker Mine;” 
(5) Then northwesterly in a straight line to the point at the southeast corner of Section 23, T13N/R7W; 
(6) Then northerly along the east line of Sections 23, 14, 11, and 2, to the point at the northeast corner of Section 2, T13N/R7W, on the Clearlake Oaks Quadrangle map; Clearlake Oaks Quadrangle Map  
(15 minute series); Continuing from the northeast corner of Section 2, T13N/R7W— 
(7) Then northwesterly in a straight line to the point in Section 21, T14N/R7W, at the top of Round Mountain 
(8) Then northwesterly in a straight line to the southeast corner of Section 4, T14N/R8W; Lakeport Quadrangle Map  
(15 minute series); Continuing from the southeast corner of Section 4, T14N/R8W, on the Clearlake Oaks Quadrangle Map— 
(9) Then northwesterly on the Lakeport Quadrangle in a straight line to a point on Charlie Alley Peak in Section 28, T16N/R9W, identified as having an elevation of 3,482 feet; 
(10) Then westerly in a straight line to a point on Hells Peak in Section 29, T16N/R10W, identified as having an elevation of 2,325 feet; 
(11) The southeasterly in a straight line to a point on Griner Peak in Section 23, T15N/R10W, identified as having an elevation of 2,132 feet; 
(12) Then southwesterly in a straight line to a point on Scotts Mountain in Section 8, T14N/R10W, identified as having an elevation of 2,380 feet; 
(13) Then southeasterly in a straight line to a point on Lakeport Peak in Section 35, T14N/R10W, identified as having an elevation of 2,180 feet; Kelseyville Quadrangle Map  
(15 minute series); Continuing from Lakeport Peak in Section 35, T14N/R10W, on the Lakeport Quadrangle Map— 
(14) Then southeasterly in a straight line to the point at the southwest corner of Section 1, T13N/R10W; 
(15) Then south by southeast in a straight line to the point at the southeast corner of Section 36, T13N/R10W; 
(16) Then south by southeasterly in a straight line to the point at the southwest corner of Section 18, T12N/R8W; 
(17) Then east by northeast in a straight line to the beginning point at Mount Hannah, Section 16, T12N/R8W, on the Lower Lake Quadrangle Map.

**Comment by SoominHur** [comment]
Reviewed
- The line proceeded southerly to the southeast corner of Section 4 (T13N/R7W), so edit the line to proceed (8) "northwesterly in a straight line to the southeast corner of Section 4, T14N/R8W; Lakeport Quadrangle Map."
- Edit the node at the southeast corner of Section 1 (T13N/R10W) to (14) "the southwest corner of Section 1, T13N/R10W."
- Edit the node at the southeast corner of Section 36 (T13N, R9W) to (15) "the southeast corner of Section 36, T13N/R10W."
