### ISSUE TITLE
los_carneros

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#5]
# AVA: Los Carneros (los_carneros)

name | value
--- | ---
ava_id | los_carneros
cfr_index | 9.32
revision | [T.D. ATF-142, 48 FR 37368, Aug. 18, 1983, as amended by T.D. ATF-249, 52 FR 5956, Feb. 27, 1987; T.D. TTB-55, 71 FR 66455, Nov. 15, 2006]
state | CA
county | Napa|Sonoma
within | Napa Valley\\|North Coast\\|Sonoma Coast\\|Sonoma Valley
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c

## Approved Maps [src]
1. “Sonoma Quadrangle, California,” 7.5 minute series topographic., 1951 photorevised 1968.. 
2. “Napa Quadrangle, California—Napa Co.,” 7.5 minute series topographic., 1951 photorevised 1968 and 1973.. 
3. “Cuttings Wharf Quadrangle, California,” 7.5 minute series topographic., 1949 photorevised 1968; photoinspected 1973.. 
4. “Sears Point Quadrangle, California,” 7.5 minute series topographic., 1951 photorevised 1968.. 
5. “Petaluma River Quadrangle,California—Sonoma Co.,” 7.5 minute series topographic., 1954 photorevised 1980.. 
6. “Glen Ellen Quadrangle, California—Sonoma Co.,” 7.5 minute series topographic., 1954 photorevised 1980..

## Boundary [src]

(1) The point of beginning is the intersection of highway 12/121 and the Napa County-Sonoma County line, near the extreme southeast corner of the Sonoma Quadrangle map.

(2) From there, following the Napa County-Sonoma County line generally northwestward for about 1.6 miles to the summit of an unnamed hill with a marked elevation of 685 ft.

(3) From there in a straight line northeastward to the summit of Milliken Peak (743 ft.), located on the Napa Quadrangle map.

(4) From there due eastward to the 400 ft. contour line.

(5) Then following that contour line generally northwestward to Carneros Creek (on the Sonoma Quadrangle map).

(6) Then following the same contour line generally southeastward to the range line R. 5 W/R. 4 W (on the Napa Quadrangle map).

(7) Then continuing to follow the same contour line generally northward for about one mile, till reaching a point due west of the summit of an unnamed hill having a marked elevation of 446 ft. (That hill is about .8 mile southwest of Browns Valley School.)

(8) From that point due eastward to the summit of that hill.

(9) From there in a straight line northeastward across Buhman Avenue to the summit of an unnamed hill having a marked elevation of 343 ft.

(10) From there due eastward to the Napa-Entre Napa land grant boundary.

(11) Then northeastward along that land grant boundary to Browns Valley Road.

(12) Then eastward along Browns Valley Road to Highway 29.

(13) Then southward along Highway 29 to Imola Avenue.

(14) Then eastward along Imola Avenue to the Napa River.

(15) Then generally southward along the west bank of the Napa River to the Southern Pacific Railroad tracks.

(16) Then generally westward and northwestward along the Southern Pacific Railroad tracks to their intersection with the township line T. 5 N./T. 4 N. (on the Sears Point Quadrangle map).

(17) From there due westward to the Northwestern Pacific Railroad tracks.

(18) Then generally southward along the Northwestern Pacific Railroad tracks to Highway 37.

(19) The westward along Highway 37 to its intersection with Highway 121.

(20) From there northwestward in a straight line to the summit of Wildcat Mountain (682 ft.).

(21) From there northwestward, following a straight line toward the summit of Sonoma Mountain (2295 ft.—on the Glenn Ellen Quadrangle map) till reaching a point due west of the intersection of Lewis Creek with the 400-ft. contour line. (That point is about 41⁄3 miles southeast of Sonoma Mountain.)

(22) From that point due eastward to Lewis Creek.

(23) Then generally southeastward along Lewis Creek to Felder Creek.

(24) Then generally eastward along Felder Creek to Leveroni Road (on the Sonoma Quadrangle map).

(25) Then generally eastward along Leveroni Road to Napa Road.

(26) Then eastward and southeastward along Napa Road to Highway 12/121.

(27) Then eastward along Highway 12/121 to the starting point.

[T.D. ATF-142, 48 FR 37368, Aug. 18, 1983, as amended by T.D. ATF-249, 52 FR 5956, Feb. 27, 1987; T.D. TTB-55, 71 FR 66455, Nov. 15, 2006]

**Comment by SoominHur** [comment]
Reviewed.
- Continue (6) "following the contour line" when it disconnected.
