### ISSUE TITLE
clements_hills

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#50]
# AVA: Clements Hills (clements_hills)

name | value
--- | ---
ava_id | clements_hills
cfr_index | 9.197
revision | [T.D. TTB-50, 71 FR 40414, July 17, 2006]
state | CA
county | San Joaquin
within | Lodi
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Waterloo, Calif., 1968, photoinspected 1978; 
2. Lockeford, Calif., 1968, photorevised 1979, minor revision 1993; 
3. Clements, Calif., 1968, minor revision 1993; 
4. Wallace, Calif., 1962; 
5. Valley Springs SW., Calif., 1962, photoinspected 1973; and 
6. Linden, Calif., 1968, minor revision 1993.

## Boundary [src]

(1) The beginning point is on the Waterloo map at the intersection of the Calaveras River and Jack Tone Road, section 31 west boundary line, T3N, R8E. From the beginning point, proceed north 6.9 miles on Jack Tone Road to its intersection with Elliot Road in the village of Lockeford 
(where Jack Tone Road is known as E. Hammond Street for a short distance), section 30, T4N, R8E 
(Lockeford Quadrangle); then 
(2) Proceed northwest 5.4 miles on Elliott Road, crossing the Mokelumne River, to Elliott Road&#39;s intersection with Liberty Road at the northwest corner of section 1, T4N, R7E, 
(Lockeford Quadrangle); then 
(3) Proceed east 9.3 miles on Liberty Road to its junction with the San Joaquin-Amador County line, north of the Camanche Reservoir, section 32, T5N, R9E 
(Clements Quadrangle); then 
(4) Proceed south-southeast 13 miles along the San Joaquin-Amador and San Joaquin-Calaveras County lines, crossing over the Wallace map, to the County line&#39;s intersection with the Calaveras River, section 31, T3N, R10E 
(Valley Springs SW., Quadrangle); and 
(5) Proceed southwest 
(downstream) 14.2 miles along the Calaveras River, crossing over the Linden map, returning to the beginning point.

**Comment by fyfangyao** [comment]
I am working on this.

**Comment by fyfangyao** [comment]
I use “Waterloo Quad, Cali., 7.5 minute series, 1968, revised 1980,“ “Wallace, Cali., 7.5 minute series, 1962, revised 1971,” and “Valley Springs SW, Cali., 7.5 minute series, 1962, revised 1980.”

**Comment by ariellerose** [comment]
I'm working on this.

**Comment by MicheleTobias** [comment]
Oh, wait.  This one is finished.  Whoops!  I'll close it.  @ariellerose

**Comment by SoominHur** [comment]
Reviewed.
- Add scale information of used maps in the attribute table.
- (5) At the middle of "Linden, CA" map, the Calaveras River diverges into two waterway. The line followed one that goes northwesterly, but the another waterway goes southwesterly has a thicker line and 'River' letter along with. So I assumed it is the Calaveras River that supposed to follow and edit the line to go along that southwesterly waterway.
