### ISSUE TITLE
Columbia Valley AVA Errors

### ISSUE THREAD

**Issue by sdelong** [UCDavisLibrary/ava#500]
Hi Michele,

I found a few errors.  Should I make a pull request for the updated file?  Or would you like to review the errors first?:

Errors in Columbia Valley AVA:
1.
(36) Then east following Washington Highways 26 and 127 through La Crosse and Dusty to the intersection with U.S. Highway 195 at Colfax;
Instead, the boundary takes a wrong turn at Dusty and follows Dusty Road instead of Highway 26.
2.
(39) Then south following the Garfield-Asotin county line to the 600-meter elevation contour; then following generally west and south in a counterclockwise direction along the meandering 600-meter elevation contour to Charley Creek in section 4, R. 44 E./T. 9 N.; and then west following Charley Creek on to the township line between R. 42 E. and R. 43 E.;
It misses the 600 meter contour, and travels much further south in a straight line.  It should follow the outline of Lewis-Clark Valley.
3.
(47) Then southwest following Oregon Highway 207 to Highway 206 in Ruggs;
(48) Then northwest following Oregon Highway 206 to the intersection with the township line between T. 1 S. and T. 2 S.;
instead, the boundary follows Rhea Creek Road directly northwest from Ruggs instead of Highway 206

That's it. Let me know.

Thanks,
Steve

**Comment by MicheleTobias** [comment]
Yes, please submit a pull request.
