### ISSUE TITLE
Errors on Umpqua Valley AVA

### ISSUE THREAD

**Issue by sdelong** [UCDavisLibrary/ava#501]
Hi Michele,

I found some errors in the digitization.  Should I submit a pull request for the updated file?

Here are the issues, as per the AVA spec numbers:

![Umpqua_Valley_verify_4](https://user-images.githubusercontent.com/3198731/74824558-40c55100-5300-11ea-8e90-6abff7055a41.png)

(4) Thence southeast approximately 8.5 miles along a straight line to the intersection of township line T23S/T24S with range line R7W/R8W; thence south along the R7W/R8W range line approximately 8 miles to its intersection with the 1,000-foot contour line; thence in a southeasterly direction in a straight line approximately 3.5 miles toward the intersection of township line T25S/T26S with range line R6W/R7W, returning to the 1,000-foot contour line;

_1. Travelling south along the R7W/R8W range line, it misses the 1,000 countour line at 8 miles and goes 8.7 miles to meet it later._

![Umpqua_Valley_verify_7](https://user-images.githubusercontent.com/3198731/74824582-49b62280-5300-11ea-8ac8-0bbe5ceb3dfa.png)

(7) Thence in an easterly, westerly, and eventually a northerly direction along the 1,000-foot contour line to a point approximately 3.5 miles east of Dillard, where the contour line crosses Interstate Highway 5 on the “Roseburg” map; thence northeast along Interstate Highway 5 approximately .25 mile, returning to the 1,000-foot contour line; thence in a generally northeasterly, southeasterly, northwesterly, and eventually a northeasterly direction along the 1,000-foot contour line past the town of Idleyld Park to the R2W/R3W range line;

_1. goes rogue (but not as in the Rogue River! Yes the jokes are too much!) at Canyonville and decides to go north and east in a series of straight lines instead of following the 1,000-foot contour line._

![Umpqua_Valley_verify_8-9](https://user-images.githubusercontent.com/3198731/74824593-4fac0380-5300-11ea-8386-67194adfac87.png)

(8) Thence north along range line R2W/R3W approximately 1.75 miles to the T25S/T26S township line; thence west along township line T25S/T26S approximately .25 mile, returning to the 1,000-foot contour line; thence in a generally westerly and then a northerly direction along the 1,000-foot contour line up the valley of Calapooya Creek to the R3W/R4W range line; thence north along range line R3W/R4W approximately 2.25 miles, back to the 1,000-foot contour line; 
_1. misses the  “west along township line T25S-T26S approximately .25 mile”, 
2. goes north too early on the R3W-R4W line as it doesn’t get to the the valley of Calapooya Creek, which also causes the north line along  R3W-R4W to be approximately 4 miles instead of 2.25 miles._

(9) Thence in a westerly and then a northerly direction along the 1,000-foot contour line to the T23S/T24S township line; thence east along the T23S/T24S township line approximately 2.75 miles to the 1,000-foot contour line; thence in a northerly direction along the 1,000-foot contour line to its intersection with the Douglas/Lane County line; thence north along the Douglas/Lane County line approximately .75 mile to the point of beginning. 

_1. doesn’t go east far enough along the T23S-T24S township line and takes the 1,000-foot contour line south and then north._

**Comment by sdelong** [comment]
In the images, the current file is the yellow-orange semi-transparent area and the lines are my updates.

**Comment by MicheleTobias** [comment]
Yes, please submit a pull request if you have corrections!  We haven't gone through the second round of checking on any other state (California is almost done) so I'm not surprised there's some errors to fix.

**Comment by sdelong** [comment]
OK, thanks Michele - I just need to get my file into your format.
