### ISSUE TITLE
Is there a metadata file for the CA_avas_shapefile.zip file

### ISSUE THREAD

**Issue by awesolowski1080** [UCDavisLibrary/ava#506]
Hi All,

I am a student at Portland Community College and in an Intro to GIS class. I am looking to do a project around the wine regions of California and when I downloaded the shapefile for the AVA regions, there was a bunch of data in the data layer attribute table but I wasn't able to find any metadata to help explain what some of the abbreviations were in the attribute table. 

Example would be "petitnr", "cfr_thr", "cfr_ndx," etc... 

Any help would be greatly appreciated :).

**Comment by ericallanwest** [comment]
The abbreviations are explained in the [Attribute Data Definitions](https://github.com/UCDavisLibrary/ava#attribute-data-definitions) in the Readme file.

**Comment by ericallanwest** [comment]
The field aliases are slightly different in that shapefile, I can understand the confusion. The abbreviations in the [GeoJSON version](https://github.com/UCDavisLibrary/ava/blob/master/avas_by_state/CA_avas.geojson) appear to match the table in the link I sent.

**Comment by MicheleTobias** [comment]
Yes, Eric is correct.  The Attribute Data Definitions of the readme have the explanation of what the columns mean in the geojson attribute table.  When we process the data into the shapefile, the column names get truncated, but they should be similar enough to match up the column names in the readme.  Please don't hesitate to ask more questions.

**Comment by awesolowski1080** [comment]
Thank you both for the clarification and I was able to find all the information. Really appreciate the work everyone has done here and can't wait to see things continue to progress :).
