### ISSUE TITLE
cole_ranch

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#51]
# AVA: Cole Ranch (cole_ranch)

name | value
--- | ---
ava_id | cole_ranch
cfr_index | 9.42
revision | [T.D. ATF-130, 48 FR 16248, Apr. 15, 1983]
state | CA
county | Mendocino
within | Mendocino\|North Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]
The approved map for the Cole Ranch viticultural area is the U.S.G.S. map entitled “Elledge Peak Quadrangle California—Mendocino County,” 7.5 minute series (topographic), 1958.

## Boundary [src]

(1) The point of beginning is the intersection of the 1480-foot-elevation contour line with the Boonville-Ukiah Cutoff Road near the southest coner of section 13; 
(2) The Boundary follows the 1480-foot-elevation contour line southerly, then easterly, within section 24, then easterly and northwesterly within section 19 to its first intersection with this section line. The boundary proceeds due west on the north section line of section 19 until it intersects with the Boonville-Ukiah Cutoff Road; 
(3) The boundary follows this road northwesterly to the point of beginning.

**Comment by fyfangyao** [comment]
I am working on it.

**Comment by fyfangyao** [comment]
I use “Elledge Peak Quadrangle, CA,” 7.5 Minute Series, 1958, (edition 1978) because the approved map doesn’t specify the edition year.

**Comment by SoominHur** [comment]
Reviewed. Updated cfr author info since there are multiple authors.
