### ISSUE TITLE
Check WI Boundaries

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#516]
The following AVAs should be reviewed for this state:

- [ ] Wisconsin Ledge
- [ ] Lake Wisconsin

Communicate about each AVA's revision status and questions on that AVA's Issue on the Issues Tab (search the closed issues to find all the AVAs).  [Review the Quality Control Procedures](/quality_control_procedure.md) before beginning.  Direct questions to @MicheleTobias.

**Comment by alisonsnwong** [comment]
In progress

**Comment by MicheleTobias** [comment]
@alisonsnwong did you check both of these?

**Comment by alisonsnwong** [comment]
Yes I did.
