### ISSUE TITLE
Check WA Boundaries

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#517]
The following AVAs should be reviewed for this state:

- [x] Columbia Valley
- [x] Puget Sound
- [x] Yakima Valley
- [x] Horse Heaven Hills
- [x] Walla Walla Valley
- [x] Columbia Gorge
- [x] Ancient Lakes of Columbia Valley
- [x] Wahluke Slope
- [x] Rattlesnake Hills
- [x] Lake Chelan
- [x] Naches Heights
- [x] Red Mountain
- [x] Snipes Mountain

Communicate about each AVA's revision status and questions on that AVA's Issue on the Issues Tab (search the closed issues to find all the AVAs).  [Review the Quality Control Procedures](/quality_control_procedure.md) before beginning.  Direct questions to @MicheleTobias.

**Comment by elistockwell** [comment]
Noticed Yakima Valley update in the CFR for Candy Mountain, adding edits to copy of layer

**Comment by alisonsnwong** [comment]
Columbia Valley was checked by Eli https://github.com/UCDavisLibrary/ava/issues/524
