### ISSUE TITLE
Check VI Boundaries

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#518]
The following AVAs should be reviewed for this state:

- [ ] Shenandoah Valley

Communicate about each AVA's revision status and questions on that AVA's Issue on the Issues Tab (search the closed issues to find all the AVAs).  [Review the Quality Control Procedures](/quality_control_procedure.md) before beginning.  Direct questions to @MicheleTobias.

**Comment by elistockwell** [comment]
Currently working on issue

**Comment by MicheleTobias** [comment]
Welcome, @elistockwell ! Let me know if you have questions as you go!

**Comment by elistockwell** [comment]
VI_avas only includes Shenandoah Valley, which is actually in Virginia (VA), so VI will be changed to VA and this layer can be merged with the VA_avas layer.

**Comment by MicheleTobias** [comment]
Fixing the attribute table will make it sort into the right state groups when I do the post-pull request processing.

**Comment by elistockwell** [comment]
Should I fix the attribute table for shenandoah_valley.geojson, VI_avas.geojson, or both?

**Comment by MicheleTobias** [comment]
Just fix shenandoah_valley.geojson  The VI_avas.geojson gets generated when I run the states R script so VI will go away once we fix this one.
