### ISSUE TITLE
Check VA Boundaries

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#519]
The following AVAs should be reviewed for this state:

- [x] Appalachian High Country
- [x] Monticello
- [x] Northern Neck George Washington Birthplace
- [x] Virginia’s Eastern Shore 
- [x] Middleburg Virginia
- [x] North_Fork_Of_Roanoke
- [x] Rocky Knob

Communicate about each AVA's revision status and questions on that AVA's Issue on the Issues Tab (search the closed issues to find all the AVAs).  [Review the Quality Control Procedures](/quality_control_procedure.md) before beginning.  Direct questions to @MicheleTobias.

**Comment by alisonsnwong** [comment]
In progress
