### ISSUE TITLE
columbia_gorge

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#52]
# AVA: Columbia Gorge (columbia_gorge)

name | value
--- | ---
ava_id | columbia_gorge
cfr_index | 9.178
revision | [T.D. TTB-11, 69 FR 25833, May 10, 2004]
state | OR|WA
county | 
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Hood River Quadrangle, Oregon—Washington, 1994; 
2. Northwestern Lake Quadrangle, Washington, 1983; 
3. Husum Quadrangle, Washington—Klickitat Co., 1994; 
4. Appleton Quadrangle, Washington—Klickitat Co., 1994; 
5. Lyle Quadrangle, Washington—Oregon, 1994; 
6. Brown Creek Quadrangle, Oregon, 1994; 
7. Ketchum Reservoir Quadrangle, Oregon, 1994; 
8. Parkdale Quadrangle, Oregon—Hood River Co., 1994; 
9. Dee Quadrangle, Oregon—Hood River Co., 1994; and 
10. Mt. Defiance Quadrangle, Oregon—Washington, 1994.

## Boundary [src]

(1) Goes 1.5 miles straight north along the R9E-R10E line to the northwest corner of section 19, T3N, R10E 
(Hood River Quadrangle); 
(2) Continues 2 miles straight east along the section line to the northeast corner of section 20, T3N, R10E 
(Hood River Quadrangle); 
(3) Goes 4.1 miles straight north along the section line, crossing onto the Northwestern Lake map, to the northwest corner of section 33, T4N, R10E 
(Northwestern Lake Quadrangle); 
(4) Continues 1 mile straight east on the section line to the northeast corner of section 33, T4N, R10E 
(Northwestern Lake Quadrangle); 
(5) Goes 1 mile straight north on the section line to the northwest corner of section 27, T4N, R10E 
(Northwestern Lake Quadrangle); 
(6) Continues 1 mile straight east on the section line to the northeast corner of section 27, T4N, R10E 
(Northwestern Lake Quadrangle); 
(7) Goes 3.8 miles north on the section line to its intersection with the T4N-T5N line, R10E 
(Northwestern Lake Quadrangle); 
(8) Continues 4 miles straight east on the T4N-T5N line, crossing onto the Husum map, to the northeast corner of section 5, R11E 
(Husum Quadrangle); 
(9) Goes 2 miles straight south on the section line to the southwest corner of section 9, T4N, R11E 
(Husum Quadrangle); 
(10) Continues 2 miles straight east on the section line to the northeast corner of section 15, T4N, R11E 
(Husum Quadrangle); 
(11) Goes 3 miles straight south on the section line to the southwest corner of section 26, T4N, R11E 
(Husum Quadrangle); 
(12) Continues 2 miles straight east on the section line, crossing onto the Appleton map, to the R11E-R12E line 
(Appleton Quadrangle); 
(13) Goes 1.25 miles straight south on the R11E-R12E line to its intersection with the 2,000-foot contour line near the northeast corner of section 1, T3N 
(Appleton Quadrangle); 
(14) Continues 11 miles south along the meandering 2,000-foot contour line through sections 1 and 12; then generally east through sections 7, 18, 8, and 9 to section 10; then generally north, weaving back and forth between sections 3, 4, 33, and 34; then south to section 3, until the 2,000-foot contour line first intersects the section line between sections 2 and 3, near a creek and an unnamed light duty road, T3N, R12E 
(Appleton Quadrangle); 
(15) Goes 5.1 miles straight south on the section line, crossing onto the Lyle map, and continuing south until it intersects with the Klickitat River along the section 34 east boundary line, T3N, R12E 
(Lyle Quadrangle); 
(16) Continues 0.9 mile generally southwest along the Klickitat River until it joins the Columbia River, and then continues 0.4 mile southwest in a straight line to the Washington-Oregon State line in the center of the Columbia River, section 3, T2N, R12E 
(Lyle Quadrangle); 
(17) Follows the Oregon-Washington state line 2.4 miles generally southeast until it intersects with a northward extension of the R12E-R13E line, T2N 
(Lyle Quadrangle); 
(18) Goes 11 miles straight south on the R12E-R13E line, crossing onto the Brown Creek map, to its intersection with the T1N-T1S Base Line at the southeast corner of section 36 
(Brown Creek Quadrangle); 
(19) Continues 6.1 miles straight west along the T1N-T1S Base Line, crossing onto the Ketchum Reservoir map, to its intersection with the R11E-R12E line at the southeast corner of section 36 
(Ketchum Reservoir Quadrangle);  
(20) Goes 6 miles straight north on the R11E-R12E line to its intersection with the T1N-T2N line at the northeast corner of section 1 
(Ketchum Reservoir Quadrangle);  
(21) Continues 6.2 miles straight west on the T1N-T2N line, crossing onto the Parkdale map, to its intersection with the R10E-R11E line at the southeast corner of section 36 
(Parkdale Quadrangle);  
(22) Goes 1.85 miles south on the R10E-R11E line to its intersection with the 2,000-foot contour line near the southeast corner of section 12, T1N, R10E 
(Parkdale Quadrangle);  
(23) Continues 10.1 miles along the meandering 2,000-foot contour line generally southwest through sections 12, 13, 14, 23, 22, 26, 27, and 34 in T1N, and section 4 in T1S, to its intersection with the section 4 south boundary line, T1S, R10E 
(Parkdale Quadrangle);  
(24) Goes 2.4 miles straight west along the section line to its intersection with the R9E-R10E line, just west of Trout Creek, at the southwest corner of section 6, T1S 
(Parkdale Quadrangle);  
(25) Continues 1 mile straight north along the R9E-R10E line to its intersection with the T1S-T1N Base Line at the northwest corner of section 6 
(Parkdale Quadrangle);  
(26) Goes 1.3 miles straight west along the T1S-T1N Base Line, crossing onto the Dee map, to its intersection with the R9E-R10E line at the southwest corner of section 21 
(Dee Quadrangle);  
(27) Continues 3.1 miles north along the R9E-R10E line to the southeast corner of section 13, T1N 
(Dee Quadrangle);  
(28) Goes 2 miles west along the section line to the southwest corner of section 14, T1N, R9E 
(Dee Quadrangle);  
(29) Continues 1 mile straight north along the section line to the northwest corner of section 14, T1N, R9E 
(Dee Quadrangle);  
(30) Goes 1 mile east along the section line to the northeast corner of section 14, T1N, R9E 
(Dee Quadrangle);  
(31) Continues 2 miles straight north along the section line until its intersection with the T1N-T2N line, R9E 
(Dee Quadrangle);  
(32) Goes 1 mile straight east along the T1N-T2N line to the southeast corner of section 36, R9E 
(Dee Quadrangle);  
(33) Continues 6.75 miles straight north along the R9E-R10E line, crossing onto the Mt. Defiance map, to the Washington-Oregon State line in the Columbia River, T3N 
(Mt. Defiance Quadrangle);  
(34) Goes 1 mile straight east-northeast along the State line, crossing onto the Hood River map, to its intersection with a southward extension of the R9E-R10E line, T3N 
(Hood River Quadrangle); and 
(35) Continues 0.6 mile north along the R9E-R10E extension, returning to the point of beginning at its intersection with the Washington State Highway 14, close to Tunnel 4, on the north bank of the Columbia River 
(Hood River Quadrangle).

**Comment by KyleWSmith** [comment]
Hi all,

Thanks to @MicheleTobias for the invite to this project via #gistribe. I'm looking forward to contributing. I'd like to start with working on Columbia River Gorge. I've forked the repo but it doesn't look like I have the ability to add the In Progress label. Thanks! Kyle

**Comment by MicheleTobias** [comment]
Sounds good to me!  It turns out that changing the labels is tied to admin access, so when you pick a new AVA to work on, just make a comment like you did and I'll change the label.

**Comment by alisonsnwong** [comment]
Checked! Performed boundary edits
