### ISSUE TITLE
Check TX Boundaries

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#520]
The following AVAs should be reviewed for this state:

- [x] Texas Hill Country
- [x] Texas High Plains
- [x] Texoma
- [x] Texas Davis Mountains
- [x] Escondido Valley
- [x] Bell Mountain
- [x] Fredericksburg in the Texas Hill Country
- [x] Mesilla Valley

Communicate about each AVA's revision status and questions on that AVA's Issue on the Issues Tab (search the closed issues to find all the AVAs).  [Review the Quality Control Procedures](/quality_control_procedure.md) before beginning.  Direct questions to @MicheleTobias.

**Comment by elistockwell** [comment]
Texoma had info for a different AVA in the boundary description and used maps.  Was able to fix boundary description but don't know which maps were used, so whoever checks the boundary needs to populate that field.
