### ISSUE TITLE
Check TN Boundaries

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#521]
The following AVAs should be reviewed for this state:

- [x] Appalachian High Country

Communicate about each AVA's revision status and questions on that AVA's Issue on the Issues Tab (search the closed issues to find all the AVAs).  [Review the Quality Control Procedures](/quality_control_procedure.md) before beginning.  Direct questions to @MicheleTobias.

**Comment by alisonsnwong** [comment]
I think this AVA has been checked by David. https://github.com/UCDavisLibrary/ava/issues/20

**Comment by MicheleTobias** [comment]
Thank you!
