### ISSUE TITLE
Check PA Boundaries

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#523]
The following AVAs should be reviewed for this state:

- [ ] Lake Erie
- [ ] Lehigh Valley
- [ ] Cumberland Valley
- [ ] Lancaster Valley
- [ ] Central Delaware Valley

Communicate about each AVA's revision status and questions on that AVA's Issue on the Issues Tab (search the closed issues to find all the AVAs).  [Review the Quality Control Procedures](/quality_control_procedure.md) before beginning.  Direct questions to @MicheleTobias.

**Comment by davidkli** [comment]
All these AVAs have been checked

**Comment by MicheleTobias** [comment]
Thank you!
