### ISSUE TITLE
Check OH Boundaries

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#525]
The following AVAs should be reviewed for this state:

- [ ] Lake Erie
- [ ] Grand River Valley
- [ ] Loramie Creek
- [ ] Isle St. George

Communicate about each AVA's revision status and questions on that AVA's Issue on the Issues Tab (search the closed issues to find all the AVAs).  [Review the Quality Control Procedures](/quality_control_procedure.md) before beginning.  Direct questions to @MicheleTobias.

**Comment by elistockwell** [comment]
Checking these now.

**Comment by elistockwell** [comment]
Issue is ready to close once #812 is merged
