### ISSUE TITLE
Check NY Boundaries

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#526]
The following AVAs should be reviewed for this state:

- [ ] Hudson River Region
- [ ] Lake Erie
- [ ] Finger Lakes
- [ ] Upper Hudson
- [ ] Long Island
- [ ] Champlain Valley of New York
- [ ] Seneca Lake
- [ ] The Hamptons Long Island
- [ ] North Fork of Long Island
- [ ] Cayuga Lake
- [ ] Niagara Escarpment

Communicate about each AVA's revision status and questions on that AVA's Issue on the Issues Tab (search the closed issues to find all the AVAs).  [Review the Quality Control Procedures](/quality_control_procedure.md) before beginning.  Direct questions to @MicheleTobias.

**Comment by elistockwell** [comment]
Checking these next.
