### ISSUE TITLE
Check NM Boundaries

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#527]
The following AVAs should be reviewed for this state:

- [ ] Middle Rio Grande Valley
- [ ] Mimbres Valley
- [ ] Mesilla Valley

Communicate about each AVA's revision status and questions on that AVA's Issue on the Issues Tab (search the closed issues to find all the AVAs).  [Review the Quality Control Procedures](/quality_control_procedure.md) before beginning.  Direct questions to @MicheleTobias.

**Comment by elistockwell** [comment]
Checking these next.

**Comment by elistockwell** [comment]
Issue is ready to close after #782 is merged.
