### ISSUE TITLE
Check NJ Boundaries

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#528]
The following AVAs should be reviewed for this state:

- [ ] Outer Coastal Plain
- [ ] Warren Hills
- [ ] Central Delaware Valley

Communicate about each AVA's revision status and questions on that AVA's Issue on the Issues Tab (search the closed issues to find all the AVAs).  [Review the Quality Control Procedures](/quality_control_procedure.md) before beginning.  Direct questions to @MicheleTobias.

**Comment by davidkli** [comment]
Currently checking these AVAs. (Central Delaware Valley has already been checked in the PA AVAs).

**Comment by davidkli** [comment]
All these AVAs have been checked

**Comment by MicheleTobias** [comment]
Thank you!
