### ISSUE TITLE
Check NC Boundaries

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#529]
The following AVAs should be reviewed for this state:

- [ ] Appalachian High Country
- [ ] Yadkin Valley
- [ ] Haw River Valley
- [ ] Upper Hiwassee Highlands
- [ ] Swan Creek
- [ ] Crest of the Blue Ridge Henderson County

Communicate about each AVA's revision status and questions on that AVA's Issue on the Issues Tab (search the closed issues to find all the AVAs).  [Review the Quality Control Procedures](/quality_control_procedure.md) before beginning.  Direct questions to @MicheleTobias.

**Comment by davidkli** [comment]
Currently checking these AVAs

**Comment by davidkli** [comment]
These AVAs have all been checked.
