### ISSUE TITLE
columbia_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#53]
# AVA: Columbia Valley (columbia_valley)

name | value
--- | ---
ava_id | columbia_valley
cfr_index | 9.74
revision | [T.D. ATF-190, 49 FR 44897, Nov. 13, 1984, as amended by T.D. ATF-249, 52 FR 5959, Feb. 27, 1987; 52 FR 10224, Mar. 31, 1987; T.D. ATF-344, 58 FR 40354, July 28, 1993; T.D. ATF-441, 66 FR 11542, Feb. 26, 2001; T.D. TTB-136, 81 FR 23161, Apr. 20, 2016]
state | OR|WA
county | 
within | 
contains | Ancient Lakes of Columbia Valley (WA)\|Horse Heaven Hills (WA)\|Naches Heights (WA)\|Rattlesnake Hills (WA)\|Red Mountain (WA)\|The Rocks District of Milton–Freewater (OR)\|Snipes Mountain (WA)\|Walla Walla Valley (WA,OR)\|Yakima Valley (WA)

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Concrete, Washington, U.S.; British Columbia, Canada, edition of 1955, limited revision 1963; 
2. Okanogan, Washington, edition of 1954, limited revision 1963; 
3. Pendleton, Oregon, Washington, edition of 1954, revised 1973; 
4. Pullman, Washington, Idaho, edition of 1953, revised 1974; 
5. Clarkston, Washington, Idaho, Oregon, 1:100,000 
metric. scale, edition of 1981; 
6. Ritzville, Washington, edition of 1953, limited revision 1965; 
7. The Dalles, Oregon, Washington, edition of 1953, revised 1971; 
8. Walla Walla, Washington, Oregon, edition of 1953, limited revision 1963; 
9. Wenatchee, Washington, edition of 1957, revised 1971; and 
10. Yakima, Washington, edition of 1958, revised 1971.

## Boundary [src]

(1) Then north and east following the Klickitat and Little Klickitat Rivers to U.S. Highway 97 northeast of Goldendale; 
(2) Then north following U.S. Highway 97 to the 1,000  contour line southwest of Hembre Mountain; 
(3) Then west following the Toppenish Ridge, across unnamed mountains of 2,172  and 2,363  elevation, to the peak of Toppenish Mountain, elevation 3,609 
(4) Then northwest in a straight line for approximately 11.3 miles to the intersection of Agency Creek with the township line between R. 15 E. and R. 16 E.; 
(5) Then north following the township line between R. 15 E. and R. 16 E. to the Tieton River; 
(6) Then northeast following the Tieton River to the confluence with the Naches River; 
(7) Then east in a straight line for approximately 15.3 miles to the intersection of the 46°45  latitude line with the Yakima River; 
(8) Then north following the Yakima River to the confluence with the North Branch Canal approximately one mile northwest of Throp; 
(9) Then north, east, and southeast following the North Branch Canal to its intersection with U.S. Interstate 90 in Johnson Canyon; 
(10) Then east following U.S. Interstate 90 to the Columbia River; 
(11) Then north following the Columbia River to the township line between T. 21 N. and T. 22 N. immediately north of the Rock Island Dam; 
(12) Then west following the township line between T. 21 N. and T. 22 N. for approximately 7.1 miles 
(from the west shore of the Columbia River) to the 2,000  contour line immediately west of Squilchuck Creek; 
(13) Then north and west following the 2,000  contour line to the township line between R. 18 E. and R. 19 E. west of the landing area at Cashmere-Dryden; 
(14) Then north following the township line between R. 18 E. and R. 19 E. for approximately 4.4 miles to the 2,000  contour line in Ollala Canyon; 
(15) Then east, north, and northwest following the 2,000  contour line to the township line between R. 19 E. and R. 20 E. immediately west of Ardenoir; 
(16) Then north following the township line between R. 19 E. and R. 20 E for approximately 2.8 miles to the 2,000  contour line immediately north of the secondary road; 
(17) Then southwest and north following the 2,000  contour line to the township line between T. 28 N. and T. 29 N.; 
(18) Then east following the township line between T. 28 N. and T. 29 N. for approximately 2.1 miles to the 2,000  contour line immediately east of Lake Chelan; 
(19) Then southeast and north following the 2,000  contour line 
(beginning in the “Wenatchee” U.S.G.S. map, passing through the “Ritzville” and “Okanogan” maps, and ending in the “Concrete” map) to the point where the 2,000  contour line intersects the township line between T. 30 N. and T. 31 N. immediately west of Methow; 
(20) Then east following the township line between T. 30 N. and T. 31 N. for approximately 20.2 miles to the 2,000  contour line east of Monse; 
(21) Then south and east following the 2,000  contour line to the township line between T. 30 N. and T. 31 N. west of Alkali Lake; 
(22) Then northeast in a straight line for approximately 10.7 miles to the point of intersection of the 2,000  contour line with Coyote Creek; 
(23) Then east, north, south, east, and north following the 2,000  contour line to the township line between T. 29 N. and T. 30 N. immediately west of the Sanpoil River; 
(24) Then east following the township line between T. 29 N. and T. 30 N. for approximately 2.3 miles to the 2,000  contour line immediately east of the Sanpoil River; 
(25) Then south, east, and north following the 2,000  contour line to the township line between T. 29 N. and T 30 N. at Ninemile Flat; 
(26) Then east following the township line between T. 29 N. and T. 30 N. for approximately 10.7 miles to the township line between R. 36 E. and R. 37 E.; 
(27) Then south following the township line between R. 36 N. and R. 37 E. to the township line between T. 26 N. and T. 27 N.; 
(28) Then west following the township line between T. 26 N. and T. 27 N. to Banks Lake; 
(29) Then south following Banks Lake to Dry Falls Dam; 
(30) Then west and south following U.S. Highway 2 and Washington Highway 17 to the intersection with Washington Highway 28 in Soap Lake; 
(31) Then southeast in a straight line for approximately 4.7 miles to the source of Rocky Ford Creek near a fish hatchery; 
(32) Then south following Rocky Ford Creek and Moses Lake to U.S. Interstate 90 southwest of the town of Moses Lake; 
(33) Then east following U.S. Interstate 90 to the Burlington Northern 
(Northern Pacific) Railroad right-of-way at Raugust Station; 
(34) Then south following the Burlington Northern 
(Northern Pacific) Railroad right-of-way to Washington Highway 260 in Connell; 
(35) Then east following Washington Highway 260 through Kahlotus to the intersection with Washington Highway 26 in Washtucna; 
(36) Then east following Washington Highways 26 and 127 through La Crosse and Dusty to the intersection with U.S. Highway 195 at Colfax; 
(37) Then south following U.S. Highway 195 to the Washington-Idaho State boundary; 
(38) Then south following the Washington-Idaho State boundary on the 1:100,000 
(metric) scale Clarkston, Washington, Idaho, Oregon map to the 600-meter elevation contour along the eastern boundary of section 9, R. 46 E./T. 11 N.; and then generally west following the meandering 600-meter contour to the eastern boundary of section 17, R. 45E./T. 11N.; then south following the eastern boundary of section 17 to the southern boundary of section 17; and then west following the southern boundaries of sections 17 and 18 to the Asotin-Garfield county line in section 19, R. 45E./T. 11N.; 
(39) Then south following the Garfield-Asotin county line to the 600-meter elevation contour; then following generally west and south in a counterclockwise direction along the meandering 600-meter elevation contour to Charley Creek in section 4, R. 44 E./T. 9 N.; and then west following Charley Creek on to the township line between R. 42 E. and R. 43 E.; 
(40) Then north following the township line between R. 42 E. and R. 43 E. on the 1:250,000 scale “Pullman, Washington, Idaho” map to Washington Highway 128 at Peola; 
(41) Then north following Washington Highway 128 to the intersection with U.S. Highway 12 in Pomeroy; 
(42) Then west following U.S. Highway 12 for approximately 5 miles to the intersection with Washington Highway 126 [in Zumwalt]; 
(43) Then southwest following Washington Highway 126 and U.S. Highway 12 through Marengo, Dayton, and Waitsburg to a point where an unnamed light-duty road leaves Highway 12 in an easterly direction in Minnick Station, Washington; 
(44) Then east following the unnamed light-duty road for approximately 250 feet until it reaches the 2000  contour line; 
(45) Then south and southwest following the 2000  contour line to the place where it crosses Oregon Highway 74 in Windmill, Oregon; 
(46) Then west following Oregon Highway 74 to Highway 207 in Heppner; 
(47) Then southwest following Oregon Highway 207 to Highway 206 in Ruggs; 
(48) Then northwest following Oregon Highway 206 to the intersection with the township line between T. 1 S. and T. 2 S.; 
(49) Then west following the township line between T. 1 S. and T. 2 S. to the Deschutes River; 
(50) Then north following the Deschutes River to the Willamette Base Line; 
(51) Then west following the Willamette Base Line to the township line between R. 12 E. and R. 13 E.; 
(52) Then north following the township line between R. 12 E. and R. 13. to the Columbia River; 
(53) Then west following the Columbia River to the confluence with the Klickitat River and the point of beginning. Transition period.  A label containing the words “Columbia Valley” in the brand name or as an appellation of origin approved prior to May 20, 2016 may be used on wine bottled before May 21, 2018 if the wine conforms to the standards for use of the label set forth in §4.25 or §4.39
(i) of this chapter in effect prior to May 20, 2016.

**Comment by alisonsnwong** [comment]
Checked by Eli https://github.com/UCDavisLibrary/ava/issues/524
