### ISSUE TITLE
Check MO Boundaries

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#531]
The following AVAs should be reviewed for this state:

- [ ] Ozark Highlands
- [ ] Hermann
- [ ] Augusta

Communicate about each AVA's revision status and questions on that AVA's Issue on the Issues Tab (search the closed issues to find all the AVAs).  [Review the Quality Control Procedures](/quality_control_procedure.md) before beginning.  Direct questions to @MicheleTobias.

**Comment by elistockwell** [comment]
Working on this now.

**Comment by elistockwell** [comment]
Ozark Highlands is good besides what looks like a very small shift due to a change in map/ava transformation
