### ISSUE TITLE
Check MN Boundaries

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#532]
The following AVAs should be reviewed for this state:

- [ ] Upper Mississippi River Valley
- [ ] Alexandria Lakes

Communicate about each AVA's revision status and questions on that AVA's Issue on the Issues Tab (search the closed issues to find all the AVAs).  [Review the Quality Control Procedures](/quality_control_procedure.md) before beginning.  Direct questions to @MicheleTobias.

**Comment by elistockwell** [comment]
Working on this issue now

**Comment by elistockwell** [comment]
UMRV was edited for QC for another state, Alexandria Lakes is good.  Closing issue.
