### ISSUE TITLE
Check MI Boundaries

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#533]
The following AVAs should be reviewed for this state:

- [ ] Tip of the Mitt
- [ ] Lake Michigan Shore
- [ ] Leelanau Peninsula
- [ ] Fennville
- [ ] Old Mission Peninsula

Communicate about each AVA's revision status and questions on that AVA's Issue on the Issues Tab (search the closed issues to find all the AVAs).  [Review the Quality Control Procedures](/quality_control_procedure.md) before beginning.  Direct questions to @MicheleTobias.

**Comment by elistockwell** [comment]
Checking these now.

**Comment by elistockwell** [comment]
Leelanau looks good.  The approved maps don't have dates, but I think the ones used make sense given the date the AVA was created.

**Comment by elistockwell** [comment]
Matched part of the Fennville border to Lake Michigan Shore (LMS).  Although Fennville is the newer AVA, so our documentation dictates that we should match LMS to it instead, the Fennville maps don't have dates, so I decided to use the maps with dates from LMS.

**Comment by elistockwell** [comment]
Old Mission Peninsula is good.  Issue is ready to close after #767 is checked and merged.
