### ISSUE TITLE
Check MD Boundaries

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#534]
The following AVAs should be reviewed for this state:

- [x] Cumberland Valley
- [ ] Catoctin
- [ ] Linganore

Communicate about each AVA's revision status and questions on that AVA's Issue on the Issues Tab (search the closed issues to find all the AVAs).  [Review the Quality Control Procedures](/quality_control_procedure.md) before beginning.  Direct questions to @MicheleTobias.

**Comment by davidkli** [comment]
Currently checking these AVAs. (Cumberland Valley was checked already in PA AVAs)

**Comment by davidkli** [comment]
These have all been checked. The pull request with the PA AVAs included these as well.
