### ISSUE TITLE
Check IL Boundaries

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#539]
The following AVAs should be reviewed for this state:

- [ ] Upper Mississippi River Valley
- [ ] Shawnee Hills

Communicate about each AVA's revision status and questions on that AVA's Issue on the Issues Tab (search the closed issues to find all the AVAs).  [Review the Quality Control Procedures](/quality_control_procedure.md) before beginning.  Direct questions to @MicheleTobias.

**Comment by elistockwell** [comment]
Checking these now.

**Comment by elistockwell** [comment]
Updated UMRV recently with approved maps, Shawnee Hills looks good.  Closing issue.
