### ISSUE TITLE
coombsville

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#54]
# AVA: Coombsville (coombsville)

name | value
--- | ---
ava_id | coombsville
cfr_index | 9.223
revision | [T.D. TTB-100, 76 FR 77684, Dec. 14, 2011]
state | CA
county | Napa
within | Napa Valley\|North Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Mt. George Quadrangle, California, 1951, Photoinspected 1973; and 
2. Napa Quadrangle, California-Napa Co., 1951, Photorevised 1980.

## Boundary [src]

(1) The beginning point is on the Mt. George map at the 1,877-foot peak of Mt. George, section 29, T6N/R3W. From the beginning point, proceed southeast in a straight line for 0.4 mile to the intersection of the 1,400-foot elevation line and an unnamed intermittent creek that feeds northeast into Leonia Lakes, section 29, T6N/R3W; then 
(2) Proceed east-southeast in a straight line for 0.45 mile to the intersection of the 1,380-foot elevation line and an unnamed, unimproved dirt road, and then continue in the same straight line to the section 29 east boundary line, T6N/R3W; then 
(3) Proceed south-southeast in a straight line for 0.6 mile to the unnamed 1,804-foot elevation point in the northwest quadrant of section 33, T6N/R3W; then 
(4) Proceed south-southwest in a straight line for 1 mile, passing over the marked 1,775-foot elevation point, to the intersection of the T6N and T5N common line and the 1,600-foot elevation line; then 
(5) Proceed south-southeast in a straight line for 1.1 miles to the 1,480-foot elevation point along the section 9 north boundary line, T5N/R3W; then 
(6) Proceed south-southwest in a straight line for 1.3 miles to the 1,351-foot elevation point, section 16, T5N/R3W; then 
(7) Proceed south-southwest in a straight line for 1.5 miles to the intersection with two unimproved dirt roads and the 1,360-foot elevation line in Kreuse Canyon at the headwaters of the intermittent Kreuse Creek, northeast of Sugarloaf, section 20, T5N/R3W; then 
(8) Proceed northwest in a straight line for 1.95 miles to the 90-degree turn of Imola Avenue at the 136-foot elevation point, section 13, T5N/R4W; then 
(9) Proceed west along Imola Avenue for 2.1 miles, crossing from the Mt. George map onto the Napa map, to the intersection of Imola Avenue with the Napa River at the Maxwell Bridge, T5N/R4W; then 
(10) Proceed north 
(upstream) along the Napa River for 3.2 miles, crossing over the T6N/T5N common line, to the intersection of the Napa River with Milliken Creek, T6N/R4W; then 
(11) Proceed north 
(upstream) along Milliken Creek for 0.75 mile to the intersection of Milliken Creek with Monticello Road, T6N/R4W; then 
(12) Proceed northeast along Monticello Road for 2.4 miles, crossing from the Napa map onto the Mt. George map, to the intersection of Monticello Road with the section 19 west boundary line, T6N/R3W; and then 
(13) Proceed east-southeast in a straight line for 1.4 miles to the beginning point, section 29, T6N/R3W.

**Comment by SoominHur** [comment]
Reviewed
- Add nodes so the straight/direct line to proceed (9) "... along Imola Avenue to the intersection of Imola Avenue with the Napa River at the Maxwell Bridge."

**Comment by MicheleTobias** [comment]
We don't necessarily need to add nodes to the straight lines when the directions say it should be a straight line.  Ideally, we're adding nodes only when necessary because it keeps the files smaller.
