### ISSUE TITLE
Check ID Boundaries

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#540]
The following AVAs should be reviewed for this state:

- [ ] Lewis–Clark Valley
- [ ] Eagle Foothills
- [ ] Snake River Valley

Communicate about each AVA's revision status and questions on that AVA's Issue on the Issues Tab (search the closed issues to find all the AVAs).  [Review the Quality Control Procedures](/quality_control_procedure.md) before beginning.  Direct questions to @MicheleTobias.

**Comment by elistockwell** [comment]
Checking these now.

**Comment by elistockwell** [comment]
All the boundaries have been checked so this is ready to close pending the merge for snake river valley.  The only thing I'm not sure about is that snake river valley and eagle foothills seem to share a small section of border, however one of them follows the 3400 ft contour and the other follows 1040 m (3412 ft).  So they are not actually following the same border, nor on the same maps, but they are close enough that it looks pretty horrendous.

**Comment by MicheleTobias** [comment]
If they look like they were intended to be the same boundary, let's snap them together, but if there's a spot where the boundaries deviate a lot, let's leave them separate. The ultimate question to answer is whether they were intended to share a boundary and the petitioners didn't do a good job making the description of one match the other.

**Comment by elistockwell** [comment]
Given that the contour line is actually different, it is such a short section, it is one of the sections where I was actually able to use the approved map for snake river valley, and there are a couple spots where they deviate a significant amount, I think I'm going to leave them unmatched for now.  If it causes any issues in the future I can come back to it.  Closing issue now.
