### ISSUE TITLE
Check IA Boundaries

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#541]
The following AVAs should be reviewed for this state:

- [ ] Upper Mississippi River Valley
- [ ] Loess Hills District

Communicate about each AVA's revision status and questions on that AVA's Issue on the Issues Tab (search the closed issues to find all the AVAs).  [Review the Quality Control Procedures](/quality_control_procedure.md) before beginning.  Direct questions to @MicheleTobias.

**Comment by elistockwell** [comment]
Checking these now.

**Comment by elistockwell** [comment]
Submitted PRs for both of these (see #731 and #732).  Closing issue.
