### ISSUE TITLE
Check GA Boundaries

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#542]
The following AVAs should be reviewed for this state:

- [ ] Upper Hiwassee Highlands
- [ ] Dahlonega Plateau

Communicate about each AVA's revision status and questions on that AVA's Issue on the Issues Tab (search the closed issues to find all the AVAs).  [Review the Quality Control Procedures](/quality_control_procedure.md) before beginning.  Direct questions to @MicheleTobias.

**Comment by yuanmengzhu** [comment]
Hi Michele, I have finished checking the GA boundries by last week.

**Comment by MicheleTobias** [comment]
@yuanmengzhu Did you have any edits or were these boundaries correct as they are?

**Comment by yuanmengzhu** [comment]
> @yuanmengzhu Did you have any edits or were these boundaries correct as they are?

Everything seems clear and correct to me.

**Comment by elistockwell** [comment]
Going to recheck these and make sure everything is up to date with current methods.

**Comment by elistockwell** [comment]
Checking Dahlonega Plateau now
