### ISSUE TITLE
Check CT Boundaries

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#543]
The following AVAs should be reviewed for this state:

- [ ] Southeastern New England
- [ ] Western Connecticut Highlands

Communicate about each AVA's revision status and questions on that AVA's Issue on the Issues Tab (search the closed issues to find all the AVAs).  [Review the Quality Control Procedures](/quality_control_procedure.md) before beginning.  Direct questions to @MicheleTobias.

**Comment by elistockwell** [comment]
Checking these out.

**Comment by elistockwell** [comment]
Did some border matching for both of these, otherwise they are good.  Closing issue.
