### ISSUE TITLE
Check CO Boundaries

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#544]
The following AVAs should be reviewed for this state:

- [x] Grand Valley
- [ ] West Elks

Communicate about each AVA's revision status and questions on that AVA's Issue on the Issues Tab (search the closed issues to find all the AVAs).  [Review the Quality Control Procedures](/quality_control_procedure.md) before beginning.  Direct questions to @MicheleTobias.

**Comment by APRios** [comment]
I would like to begin Quality Checking Grand Valley AVA.

**Comment by APRios** [comment]
Pull request submitted for Grand Valley.  I will begin Quality Checking West Elks AVA.

**Comment by MicheleTobias** [comment]
Thanks!  I've got your PR on my to-do list, but the reminder is appreciated!   I'll try to get to that today.

**Comment by elistockwell** [comment]
Rechecked and edited both of these, going to close the issue now.
