### ISSUE TITLE
Check AZ Boundaries

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#545]
The following AVAs should be reviewed for this state:

- [ ] Willcox
- [ ] Sonoita

Communicate about each AVA's revision status and questions on that AVA's Issue on the Issues Tab (search the closed issues to find all the AVAs).  [Review the Quality Control Procedures](/quality_control_procedure.md) before beginning.  Direct questions to @MicheleTobias.

**Comment by APRios** [comment]
Hello. I would like to begin Quality Control review of Sonoita and Willcox AVAs.

**Comment by MicheleTobias** [comment]
Hey Arturo! I just saw this!  I'm not sure why it didn't send me an email.  Go for it!  It would be great if you can check the Arizona boundaries.  Let me know if you have any questions.

**Comment by APRios** [comment]
Hello. Fantastic!! I have completed QC of Sonoita and submitted pull request. No edits made to boundary, but I did make a few edits to Attribute table. I have also completed Willcox, but have NOT submitted pull request. I am waiting for Sonoita to be accepted and merged. I made several edits to boundary and Attribute table for Willcox.  There are too many edits to list in this email.

I check email daily, and Github a couple times a week.

Thanks. Arturo
________________________________

**Comment by elistockwell** [comment]
Double checked these, closing issue.
