### ISSUE TITLE
Check AR Boundaries

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#546]
The following AVAs should be reviewed for this state:

- [ ] Ozark Mountain
- [ ] Arkansas Mountain
- [ ] Altus

Communicate about each AVA's revision status and questions on that AVA's Issue on the Issues Tab (search the closed issues to find all the AVAs).  [Review the Quality Control Procedures](/quality_control_procedure.md) before beginning.  Direct questions to @MicheleTobias.

**Comment by elistockwell** [comment]
Working on this now.

**Comment by elistockwell** [comment]
Checked these and made a couple edits a while ago, forgot to close issue.
