### ISSUE TITLE
covelo

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#56]
# AVA: Covelo (covelo)

name | value
--- | ---
ava_id | covelo
cfr_index | 9.187
revision | [T.D. TTB-42, 71 FR 8205, Feb. 16, 2006]
state | CA
county | Mendocino
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Dos Rios, California Quadrangle,—Mendocino Co., 7.5 Minute Series, edition of 1967, revised 1994; 
2. Covelo West, California Quadrangle,—Mendocino Co., 7.5 Minute Series, edition of 1967, photoinspected 1973; 
3. Covelo East, California Quadrangle,—Mendocino Co., 7.5 Minute Series, edition of 1967, revised 1994; and 
4. Jamison Ridge, California Quadrangle,—Mendocino Co., 7.5 Minute Series, edition of 1967, revised 1994.

## Boundary [src]

(1) Beginning on the Dos Rios map at the intersection of State Highway 162 and the southern boundary of section 25, T22N, R13W 
(labeled Inspiration Point on the map), proceed west 0.3 miles on Highway 162 to BM 2006 in section 36, T22N, R13W; then 
(2) Proceed straight west-northwest 1.5 miles to the 2,537-foot elevation point in the northwest quadrant of section 26, T22N, R13W, Dos Rios map; then 
(3) Proceed straight northwest 1.6 miles to the 2,488-foot peak in the northwest quadrant of section 22, T22N, R13W, Covelo West map; then 
(4) Proceed straight north-northwest 0.75 miles to the 2,262-foot peak on the section 15 and 16 boundary line, T22N, R13W, and continue straight north 1.6 miles to the 2,247-foot peak on the section 3 and 4 boundary line, T22N, R13W, Covelo West map; then 
(5) Proceed straight northerly 1 mile to the 1,974-foot peak on the T22N/T23N boundary line, and continue straight north 1.6 miles to the 2,290-foot peak in the northwest quadrant of section 27, T23N, R13W, Covelo West map; then 
(6) Proceed straight northeast 1.2 miles to the 2,397-foot peak in the northeast quadrant of section 22, and continue straight northeast 1.5 miles to BM 2210 in the northeast quadrant of section 14, T23N, R13W, Covelo West map; then 
(7) Proceed straight east-southeast 1.75 miles to the 2,792-foot peak in the southwest quadrant of section 18, T23, R12W, Covelo East map; then 
(8) Proceed straight north-northeasterly 0.9 mile to the 2,430-foot elevation point in the southeast quadrant of section 7, T23N, R12W, Covelo East map; then 
(9) Proceed straight east-northeast 1.6 miles to the peak of Coyote Rock in section 9, T23N, R12W, Covelo East map; then 
(10) Proceed straight east-southeast 1.55 miles to the 2,435-foot elevation point in the northern half of section 15, and continue straight southeast 2.3 miles to the 2,066-foot peak in the southwest quadrant of section 24, T23N, R12W, Covelo East map; then 
(11) Proceed straight south-southwest 0.6 mile to the 2,024-foot peak near the section 26 eastern boundary line, T23N, R12W, Covelo East map; then 
(12) Proceed straight west-southwest 1.9 miles to the 2,183-foot peak in the northwest quadrant of section 34, T23N, R12W, Covelo East map; then 
(13) Proceed straight south-southeast 1.2 miles to the 1,953-foot peak in the northeast quadrant of section 3, T22N, R12W, Covelo East map; then 
(14) Proceed straight southerly 0.9 mile to the 2,012-foot peak in the northeast quadrant of section 10, T22N, R12W, Covelo East map; then 
(15) Proceed straight south-southeast 1.4 miles along Dingman Ridge to the 2,228-foot peak along the section 14 and 15 boundary line, T22N, R12W, Covelo East map; then 
(16) Proceed straight southeast 0.95 mile to the 2,398-foot peak in the northeast quadrant of section 23, T22N, R12W, Covelo East map; then 
(17) Proceed straight south-southeast 1.75 miles to the 2,474-foot elevation point along the section 25 and 26 boundary line, T22N, R12W, Jamison Ridge map; then 
(18) Proceed straight west-southwest 0.9 mile to BM 2217 in the southwest quadrant of section 26, and continue straight westerly 1.5 miles to the 2,230-foot peak northwest of Iron Spring, in the southeast quadrant of section 28, T22N, R12W, Jamison Ridge map; then 
(19) Proceed straight southwest 0.65 mile to the 2,022-foot peak very near an unimproved road in section 33, T22N, R12W, Jamison Ridge map; then 
(20) Proceed straight west-northwest 1.5 miles to the 1,762-foot peak in the northeast quadrant of section 31, T22N, R12W, Jamison Ridge map, and continue in the same line of direction 1.1 miles to the beginning point at the intersection of State Highway 162 and the southern boundary of section 25, T22N, R13W 
(labeled Inspiration Point), on the Dos Rios map.

**Comment by fyfangyao** [comment]
I am working on it.

**Comment by fyfangyao** [comment]
I use “Covelo West, CA,” 7.5 Minute Series, edition of 1967, (revised 1969) because I could not find the approved one.

**Comment by SoominHur** [comment]
Reviewed
