### ISSUE TITLE
tualatin_hills

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#561]
# AVA: Tualatin Hills (tualatin_hills)

name | value
--- | ---
ava_id | tualatin_hills
cfr_index | 9.268
revision | [T.D. TTB-160, 85 FR 34099, June 3, 2020]
state | OR
county | Clackamas\|Multnomah\|Washington
within | **Update in File**
contains | **Update in File**

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c#se27.1.9_1268
## Approved Maps [src]

(b) Approved maps. The 6 United States Geological Survey (USGS) 1:24,000 scale topographic maps and the single 1:250,000 scale topographic map used to determine the boundary of the Tualatin Hills viticultural area are titled:

(1) Vancouver, 1974 (1:250,000);

(2) Dixie Mountain, OR, 2014;

(3) Gaston, OR, 2014;

(4) Laurelwood, OR, 2014;

(5) Forest Grove, OR, 2014;

(6) Hillsboro, OR, 2014; and

(7) Linnton, OR, 2014.

## Boundary [src]
(c) Boundary. The Tualatin Hills viticultural area is located in Clackamas, Multnomah and Washington Counties, in Oregon. The boundary of the Tualatin Hills viticultural area is as described below:

(1) The beginning point is on the Dixie Mountain map at the intersection of North West Skyline Boulevard and North West Moreland Road. From the beginning point, proceed southwesterly along North West Moreland Road for approximately 1.3 miles to road's intersection with the Multnomah-Washington County line; then

(2) Proceed south along the Multnomah-Washington County for approximately 1.2 miles to the county line's intersection with the 1,000-foot elevation contour; then

(3) Proceed northwesterly along the 1,000-foot elevation contour, crossing onto the Vancouver map and continuing generally southwesterly along the meandering 1,000-foot elevation contour to its intersection with the Washington-Yamhill County line; then

(4) Proceed east along the Washington-Yamhill County line, crossing onto the Gaston map, to the intersection of the county line with NW South Road; then

(5) Proceed northeast along NW South Road to its intersection with SW South Road; then

(6) Proceed northeasterly along SW South Road to its intersection with the 200-foot elevation contour; then

(7) Proceed easterly along the 200-foot elevation contour for approximately 1.9 miles to its intersection with East Main Street/SW Gaston Road in the village of Gaston; then

(8) Proceed south, then east along SW Gaston Road for approximately 0.9 mile, crossing onto the Laurelwood map, to the road's intersection with the 240-foot contour line just south of an unnamed road known locally as SW Dixon Mill Road; then

(9) Proceed north along the meandering 240-foot elevation contour for approximately 5 miles to its intersection with SW Sandstrom Road; then

(10) Proceed west along SW Sandstrom Road for approximately 0.15 mile to its third crossing of the 200-foot elevation contour; then

(11) Proceed northwesterly and then northeasterly along the meandering 200-foot contour line for approximately 2.9 miles to its intersection with an unnamed road known locally as SW Fern Hill Road, north of an unnamed road known locally as SW Blooming Fern Hill Road; then

(12) Proceed north along SW Fern Hill Road for approximately 1.2 miles, crossing onto the Forest Grove map, to the road's intersection with Oregon Highway 47; then

(13) Proceed northerly along Oregon Highway 47 for approximately 7.6 miles to its intersection with Oregon Highway 6/NW Wilson River Highway; then

(14) Proceed east along Oregon Highway 6/NW Wilson River Highway for approximately 2.5 miles to its intersection with Sunset Highway; then

(15) Proceed southeast along Sunset Highway for approximately 2.3 miles to its intersection with the railroad tracks; then

(16) Proceed east along the railroad tracks, crossing onto the Hillsboro map, to the intersection of the railroad tracks and an unnamed road known locally as NW Dick Road; then

(17) Proceed south along NW Dick Road for approximately 0.3 mile to its intersection with NW Phillips Road; then

(18) Proceed east along NW Phillips Road for approximately 1.2 miles, crossing onto the Linnton map, to the road's intersection with an unnamed road known locally as NW Old Cornelius Pass Road; then

(19) Proceed northeast along NW Old Cornelius Pass Road to its intersection with NW Skyline Boulevard Road; then

(20) Proceed north and west along NW Skyline Boulevard for approximately 10.5 miles, crossing over the northeast corner of the Hillsboro map and onto the Dixie Mountain map and then returning to the beginning point.

[T.D. TTB-160, 85 FR 34099, June 3, 2020]

**Comment by yuanmengzhu** [comment]
Hi Michele, I plan to start drawing the tualatin_hills bountries this week.

**Comment by MicheleTobias** [comment]
@yuanmengzhu How are you doing with the boundary for Tualatin Hills?

**Comment by yuanmengzhu** [comment]
Hello Michele,

Hope that your quarter is going well!

Thank you for checking on me. I would finish and upload it as soon as
possible.

Best,
Mengzhu

**Comment by MicheleTobias** [comment]
No worries!  Take your time!  If you have questions, need help, or decide you want someone else to work on it, just let me know.

**Comment by MicheleTobias** [comment]
Hi @yuanmengzhu we really need to get this dataset completed so we can move on with the next stage of the project.  If you don't think you can finish it this week, I'm happy to have what you've been able to complete or if you'd rather just pass it off to @elistockwell that would be fine too.  Let me know what works best for you.

**Comment by elistockwell** [comment]
Going to start working on this now

**Comment by MicheleTobias** [comment]
Sounds good!  @yuanmengzhu if you have data to share, we'd love to have it, but otherwise, I think it's time for @elistockwell to work on this so we can wrap up the current list of AVAs.
