### ISSUE TITLE
laurelwood_district

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#562]
# AVA: Laurelwood District (laurelwood_district)

name | value
--- | ---
ava_id | laurelwood_district
cfr_index | 9.269
revision | [T.D. TTB-160, 85 FR 34099, June 3, 2020]
state | OR
county | Washington\|Yamhill 
within | **Update in File**
contains |  **Update in File**

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c#se27.1.9_1269
## Approved Maps [src]
(b) Approved maps. The six United States Geological Survey (USGS) 1:24,000 scale topographic maps used to determine the boundary of the Laurelwood District viticultural area are titled:

(1) Laurelwood, OR, 2014;

(2) Scholls, Oreg., 1961; photorevised 1985;

(3) Newberg, OR, 2014;

(4) Beaverton, Oreg., 1961; photorevised 1984;

(5) Sherwood, Oreg., 1961; photorevised 1985; and

(6) Dundee, Oreg., 1956; revised 1993.

## Boundary [src]
(c) Boundary. The Laurelwood District viticultural area is located in Washington and Yamhill Counties, in Oregon. The boundary of the Laurelwood District viticultural area is as described below:

(1) The beginning point is on the Laurelwood map at the intersection of Winters Road and Blooming Fern Hill Road in section 17, T1S/R3W. From the beginning point, proceed west then northwest along Blooming Fern Hill Road for approximately 0.4 mile to its intersection with the 200-foot elevation contour; then

(2) Proceed north then northeasterly along the 200-foot elevation contour for 1.5 miles to its intersection with SW La Follette Road; then

(3) Proceed south along SW La Follette Road for 0.25 mile to its intersection with the 240-foot elevation contour, north of Blooming Fern Hill Road; then

(4) Proceed easterly then southerly along the 240-foot elevation contour, crossing onto the Scholls map and back onto the Laurelwood map, for a total of 17 miles to the intersection of the elevation contour with SW Laurel Road; then

(5) Proceed east along SW Laurel Road for 0.15 mile to its intersection with the 200-foot elevation contour; then

(6) Proceed easterly along the 200-foot elevation contour, crossing over the Scholls map and onto the Newberg map, then crossing Heaton Creek and back onto the Scholls map for a total of 17.5 miles to the intersection of the elevation contour with Mountain Home Road east of Heaton Creek; then

(7) Proceed easterly then southerly along the 200-foot elevation contour, crossing over the Beaverton and Sherwood maps and back onto the Scholls map for a total of 8.9 miles to the intersection of the elevation contour with the middle tributary of an unnamed stream along the western boundary of section 24, T2S/R2W; then

(8) Proceed southeast along the 200-foot elevation contour, crossing over the northeast corner of the Newberg map and onto the Sherwood map, to the intersection of the elevation contour with Edy Road in section 25, T2S/R2W; then

(9) Proceed southwest along the 200-foot elevation contour, crossing onto the Newberg map and back onto the Sherwood map, to the intersection of the elevation contour with Elwert Road along the eastern boundary of section 25, T2S/R2W; then

(10) Proceed south along Elwert Road for 0.85 mile to its intersection with an unnamed highway known locally as Oregon Highway 99W, along the eastern boundary of section 36, T2S/R2W; then

(11) Proceed southwesterly along Oregon Highway 99W for 0.45 mile to its intersection with the 250-foot elevation contour immediately south of an unnamed tributary of Cedar Creek in section 36, T2S/R2W; then

(12) Proceed southerly along the 250-foot elevation contour for 1 mile to its intersection with Middleton Road in section 1, T2S/R2W; then

(13) Proceed southwesterly along Middleton Road, which becomes Rein Road, for 0.5 mile to the intersection of the road with the 200-foot elevation contour immediately south of Cedar Creek; then

(14) Proceed easterly along the 200-foot elevation contour for 1.6 miles to its intersection with an unnamed light-duty east-west road known locally as Brookman Road in the village of Middleton, section 6, T3S/R1W; then

(15) Proceed east on Brookman Road for 0.4 mile to its intersection with the shared Washington-Clackamas County line at the western corner of section 5, T3S/R1W; then

(16) Proceed south along the Washington-Clackamas County line for 1 mile to its intersection with Parrett Mountain Road along the eastern boundary of section 7, T3S/R1W; then

(17) Proceed southwesterly along Parrett Mountain Road, crossing onto the Newberg map, for a total of 2.6 miles, to the intersection with an unnamed local road known locally as NE Old Parrett Mountain Road; then

(18) Proceed west along NE Old Parrett Mountain Road for 1.7 mile to its intersection with NE Schaad Road; then

(19) Proceed west along NE Schaad Road for 0.5 mile to its intersection with an unnamed local road known locally as NE Corral Creek Road; then

(20) Proceed north along NE Corral Creek Road for 0.9 mile to its westernmost intersection with an unnamed local road known locally as NE Veritas Lane, south of Oregon Highway 99W; then

(21) Proceed north westerly in a straight line for approximately 0.05 mile to the intersection of Oregon Highway 99W and the 250-foot elevation contour; then

(22) Proceed northwesterly along the 250-foot elevation contour for 1 mile to its intersection with the second, westernmost intermittent stream that is an unnamed tributary of Spring Brook; then

(23) Proceed northerly along the unnamed stream, crossing the single-gauge railroad track, for 0.5 mile to the intersection of the stream with the 430-foot elevation contour; then

(24) Proceed west along the 430-foot elevation contour for 0.25 mile, crossing an unnamed road known locally as Owls Lane, to the intersection of the elevation contour with NE Kincaid Road; then

(25) Proceed northwesterly along NE Kincaid Road for 0.25 mile to its intersection with NE Springbrook Road; then

(26) Proceed northwesterly along NE Springbrook Road for 0.22 mile to its intersection with an unnamed road known locally as Bell Road; then

(27) Proceed east along Bell Road for 0.5 mile, making a sharp northwesterly turn, then continuing along the road for 0.2 mile to its intersection with Mountain Top Road; then

(28) Proceed northwesterly along Mountain Top Road for 1.9 miles to its intersection with SW Hillsboro Highway, also known as Highway 219; then

(29) Proceed north along SW Hillsboro Highway for 0.1 mile to its intersection with Mountain Top Road at the Washington-Yamhill County line; then

(30) Proceed northwest along Mountain Top Road for 3.1 miles, crossing onto the Dundee map, to the intersection of the road with Bald Peak Road in section 26, T2S/R3W; then

(31) Proceed northwest, then northeast, then north along Bald Peak Road, crossing onto the Laurelwood map, for a total of 4.8 miles, to the intersection of the road with SW Laurelwood Road; then

(32) Proceed southwest, then northwest, along SW Laurelwood Road for 0.8 mile to its intersection with the 700-foot elevation contour; then

(33) Proceed northeast, then northwest, then north along the 700-foot elevation contour for 5 miles, passing west of Iowa Hill and Spring Hill, to the intersection of the elevation contour and SW Winters Road; then

(34) Proceed north on SW Winters Road for 2 miles, returning to the beginning point.

[T.D. TTB-160, 85 FR 34099, June 3, 2020]

**Comment by elistockwell** [comment]
Working on this now.

**Comment by alisonsnwong** [comment]
Checked!
