### ISSUE TITLE
Fix Date Column Inconsistencies

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#564]
The date format should be YYYY-MM-DD but several of the AVAs have a different format - commonly YYYY/MM/DD.  

1. Investigate the variety of date formats
2. Update the files to the correct format using an R script

**Comment by elistockwell** [comment]
I believe this issue has been solved with my "find bad dates" R code, although this code only checks that the first four digits are numbers and the fifth is a "-".  Let me know if I should alter this code to be more comprehensive.  I know that the most common error YYYY/MM/DD comes from QGIS, at least in my experience, it will change dates entered in the other format automatically which is annoying but it usually sticks after correcting it once.

**Comment by MicheleTobias** [comment]
Have you seen any dates that wouldn't have gotten caught by your code?  I'm thinking maybe someone did YYYY-DD-MM but I don't think we would find those without checking the CFR by hand.

**Comment by alisonsnwong** [comment]
I can update the `find bad dates` R code to also check the individual ava files in addition to only the avas.geojson file.
