### ISSUE TITLE
Update California's County Data

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#565]
Some AVAs are missing counties that they intersect. This stemmed from the script that created the initial files. 

Create an R script that finds which counties each AVA intersects with and updates the column with the correct counties in the correct format.

**Comment by kurtishouser** [comment]
If you're using this page, https://www.ttb.gov/wine/established-avas, make sure all of the county names are spelled correctly as well. I found these. Perhaps there are more.

San Bernadino, CA -> San Bernardino
Owens, IN -> Owen
Courtland, NY -> Cortland
Duchess, NY -> Dutchess
Forsythe, NC -> Forsyth
Surrey, NC -> Surry

**Comment by MicheleTobias** [comment]
US county data can be found on the Census Bureau's vector data site: https://www.census.gov/cgi-bin/geo/shapefiles/index.php

**Comment by alisonsnwong** [comment]
Completed this issue, let me know if there are anything else to update. https://github.com/UCDavisLibrary/ava/pull/896.
