### ISSUE TITLE
Videos in digitizing_ava_boundaries.md Cannot Be Played 

### ISSUE THREAD

**Issue by yuanmengzhu** [UCDavisLibrary/ava#566]
The following videos from [digitizing_ava_boundaries.md](https://github.com/UCDavisLibrary/ava/blob/master/digitizing_ava_boundaries.md) are indicated "No preview available. File is in owner's trash" when clicking them: 

1. the video in Download the Approved Maps 
2. the video in Digitizing the Boundary >> Set Up Your Project File 
3. the video in  Digitizing the Boundary >> Digitizing the Boundary

**Comment by MicheleTobias** [comment]
Thanks, @yuanmengzhu!  I need to update the videos anyway so that's probably the solution.
