### ISSUE TITLE
alisos_canyon

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#568]
# AVA: Alisos Canyon

name | value
--- | ---
ava_id | alisos_canyon
cfr_index | 9.270
revision | [T.D TTB 1611, 85 FR 52273, Aug. 25, 2020]
state | CA
county |  Santa Barbara 
within | **Update in File**
contains |  **Update in File**

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c#se27.1.9_1269
## Approved Maps [src]
Approved maps. The two United States Geological Survey (USGS) 1:24,000 scale topographic maps used to determine the boundary of the Alisos Canyon viticultural area are titled:

(1) Foxen Canyon, CA, 1995; and

(2) Zaca Creek, Calif., 1959.

## Boundary [src]
(c) Boundary. The Alisos Canyon viticultural area is located in Santa Barbara County, California. The boundary of the Alisos Canyon viticultural area is as described below:

(1) The beginning point is on the Foxen Canyon map at an unnamed hilltop with a marked elevation of 1,137 feet, located west of the Cañada de los Coches in the La Laguna Grant. From the beginning point, proceed east in a straight line for 3.71 miles to the intersection of two unnamed, unimproved roads north of Rancho San Juan; then

(2) Proceed east-southeast in a straight line for approximately 1.2 miles to an unnamed hilltop with a marked elevation of 1,424 feet in the La Laguna Grant; then

(3) Proceed southwest in a straight line for approximately 1.7 miles, crossing onto the Zaca Creek map, to a point designated “Oil,” adjacent to the north fork of San Antonio Creek and the intersection of three unnamed light-duty roads in the Cañada del Comasa, La Laguna Grant; then

(4) Proceed west-southwest in a straight line for approximately 1.56 miles to the intersection of the north fork of San Antonio Creek and the 800-foot elevation contour in the Cañada del Comasa, La Laguna Grant; then

(5) Proceed west in a straight line 1.95 miles to an unnamed rectangular structure northeast of the terminus of an unnamed, unimproved road north of U.S. Highway 101 and BM 684 in the La Laguna Grant; then

(6) Proceed northwesterly in a straight line 0.32 mile to the intersection of Alisos Canyon Road and an unnamed, unimproved road east of the Cañada de los Coches in the La Laguna Grant; then

(7) Proceed north-northwest in a straight line for 1.68 miles, crossing onto the Foxen Canyon map, to an unnamed hilltop with a marked elevation of 997 feet in the La Laguna Grant; then

(8) Proceed northeast in a straight line for 0.5 mile to return to the beginning point.

**Comment by elistockwell** [comment]
Working on this issue.
