### ISSUE TITLE
royal_slope

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#569]
# AVA: Royal Slope (royal_slope)

name | value
--- | ---
ava_id | royal_slope
cfr_index | 9.271
revision | [T.D. TTB-162, 85 FR 54493, Sept. 2, 2020]
state | WA
county | Grant \|Adams 
within | **Update in File**
contains |  **Update in File**

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c#se27.1.9_1269
## Approved Maps [src]
The one United States Geological Survey (USGS) 1:100,000 scale topographic map used to determine the boundary of the Royal Slope viticultural area is “Priest Rapids, WA,” 2015.

## Boundary [src]
(1) The point of the beginning is on the Priest Rapids map at the intersection of the 250 meter elevation contour and the northern boundary of Section 8, T17N/R23E. From the beginning point, proceed east for approximately 7 miles along the northern boundaries of Sections 8, 9, 10, 11, and 12, T17N/R23E, and Sections 7 and 8, T17N/R24E to the northeast corner of Section 8, T17N/R24E; then

(2) Proceed south for approximately 1 mile along the eastern boundary of Section 8 to the southeast corner of Section 8, T17N/R24 E; then

(3) Proceed east for approximately 4 miles along the southern boundaries of Sections 9, 10, 11, and 12, T17N/R24E, to the southeastern corner of Section 12, T17N/R24E; then

(4) Proceed north for approximately 1.8 miles along the eastern boundaries of Sections 12 and 1, T17N/R24E, to the intersection of the eastern boundary of Section 1 and the southern boundary of the Desert Unit of the Columbia Basin State Wildlife Area; then

(5) Proceed easterly for approximately 20 miles along the boundary of the Desert Unit of the Columbia Basin State Wildlife Area to the intersection of the wildlife area boundary with O'Sullivan Dam Road/State Highway 262; then

(6) Proceed east for approximately 1.5 miles along O'Sullivan Dam Road/State Highway 262 to the intersection of the road with an unnamed road known locally as H Road SE; then

(7) Proceed southeasterly for approximately 1.6 miles along H Road SE to the intersection of the road with the southern boundary of Section 16, T17N/R28E; then

(8) Proceed east for approximately 0.4 mile along the southern boundary of Section 16 to the intersection of the southeastern corner of Section 16, T17N/R28E, and the western boundary of the Columbia National Wildlife Refuge; then

(9) Proceed southerly, then southwesterly, for approximately 8 miles along the western boundary of the Columbia National Wildlife Refuge and the concurrent western boundary of the Goose Lakes Unit of the Columbia Basin State Wildlife Area to the intersection of the wildlife refuge boundary with the eastern boundary of Section 14, T16N/R27E; then

(10) Proceed south along the eastern boundaries of Sections 14, 23, 26, and 35, T16N/R27E, to the intersection of the eastern boundary of Section 35 with State Highway 26; then

(11) Proceed northwesterly for approximately 3 miles along State Highway 26 to the intersection of the highway with the 250-meter elevation contour in the southwest corner of Section 21, T16/R27E; then

(12) Proceed westerly for approximately 28 miles along the 250-meter elevation contour to the intersection of the elevation contour with the eastern boundary of Section 26, T16N/R23E; then

(13) Proceed north for approximately 1,100 feet along the eastern boundary of Section 26 to the northeast corner of Section 26, T16N/R23E; then

(14) Proceed west for 1 mile along the northern boundary of Section 26, T16N/R23E, to the intersection with the eastern boundary of Section 22, T16N/R23E; then

(15) Proceed north for 1 mile along the eastern boundary of Section 22 to the northern boundary of Section 22, T16N/R23E; then

(16) Proceed west for approximately 1.05 miles along the northern boundary of Section 22, T16N/R23E, to the intersection of the section boundary with the 250-meter elevation contour; then

(17) Proceed northerly for approximately 10 miles along the 250-meter elevation contour to return to the beginning point.

**Comment by elistockwell** [comment]
Working on this issue.
