### ISSUE TITLE
creston_district

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#57]
# AVA: Creston District (creston_district)

name | value
--- | ---
ava_id | creston_district
cfr_index | 9.239
revision | [T.D. TTB-125, 79 FR 60960, Oct. 9, 2014]
state | CA
county | San Luis Obispo
within | Central Coast\|Paso Robles
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

(1) Creston, Calif., 1948, photorevised 1980;

(2) Shedd Canyon, Calif., 1961;

(3) Wilson Corner, CA, 1995;

(4) Camatta Ranch, CA, 1995; and

(5) Santa Margarita, Calif., 1965, revised 1993.

## Boundary [src]

(c) Boundary. The Creston District viticultural area is located in San Luis Obispo County, California. The boundary of the Creston District viticultural area is as described below:

(1) The beginning point is located on the Creston map along the common boundary line of the Huerhuero Land Grant and section 34, T27S/R13E, at the eastern-most intersection of State Route 41 and an unnamed light-duty road locally known as Cripple Creek Road. From the beginning point, proceed northerly on Cripple Creek Road approximately 1 mile to the road's intersection with an unnamed light duty road locally known as El Pomar Drive (at BM 1052), section 27, T27S/R13E; then

(2) Proceed northeasterly in a straight line approximately 0.75 mile to the unnamed 1,142-foot elevation point, T27S/R13E; then

(3) Proceed north in a straight line approximately 1.2 miles to the line's intersection with an unnamed light duty road locally known as Creston Road at the southwest corner of section 14, T27S/R13E; then

(4) Proceed east on Creston Road approximately 0.35 mile to the road's intersection with an unnamed light-duty road known locally as Geneseo Road (at BM 1014), T27S/R13E; then

(5) Proceed north-northwesterly on Geneseo Road approximately 0.7 mile to the road's intersection with a jeep trail (locally known as Rancho Verano Place) and the western boundary line of section 14, T27S/R13E; then

(6) Proceed due east in a straight line approximately 0.2 mile to the line's intersection with the Huerhuero Land Grant boundary line, section 14, T27S/R13E; then

(7) Proceed north-northeasterly along the Huerhuero Land Grant boundary line approximately 0.7 mile to the land grant's northern-most point, and then continue east-southeasterly along the land grant's boundary line approximately 0.4 mile to the line's intersection with the northern boundary line of section 14, T27S/R13E; then

(8) Proceed east approximately 1.3 miles along the northern boundary lines of sections 14 and 13, T27S/R13E, and continue east approximately 0.25 mile along the northern boundary line of section 18, T27S/R14E, to the T-intersection of two unnamed unimproved roads; then

(9) Proceed east-southeasterly on the generally east-west unnamed unimproved road approximately 0.85 mile, crossing onto the Shedd Canyon map, to the road's intersection with the eastern boundary line of section 18, T27S/R14E; then

(10) Proceed southeasterly in a straight line approximately 1.2 miles to the 1,641-foot elevation point located at the southeast corner of section 17, T27S/R14E; then

(11) Proceed southeasterly approximately 0.55 mile in a straight line to BM 1533 (located beside Creston Shandon Road (State Route 41)) and continue southeasterly in a straight line approximately 1.8 miles to the 1,607 elevation point near the western boundary line of section 27, T27S/R14E; then

(12) Proceed east-southeasterly in a straight line approximately 1.1 miles to the 1.579-foot elevation point at the southeast corner of section 27, T27S/R14E; then

(13) Proceed east approximately 1.9 miles along the northern boundary lines of sections 35 and 36, T27S/R14E, to the section 36 boundary line's intersection with Indian Creek; then

(14) Proceed southerly (upstream) along Indian Creek approximately 5.3 miles in straight-line distance, crossing onto the Wilson Corner map, to the creek's intersection with an unnamed light-duty road locally known as La Panza Road, section 20, T28S/R15E; then

(15) Proceed southeasterly on La Panza Road approximately 0.15 mile to the road's intersection with State Route 58 at Wilson Corner, section 29, T28S/R15E; then

(16) Proceed easterly on State Route 58 approximately 1.4 miles, crossing onto the Camatta Ranch map, to the road's intersection with the eastern boundary line of section 28, T28S/R15E; then

(17) Proceed south approximately 1.5 miles along the eastern boundary lines of sections 28 and 33, T28S/R15E, to the T28S/T29S common boundary line at the southeast corner of section 33, T28S/15E; then

(18) Proceed west along the T28S/T29S common boundary line approximately 9.1 miles, crossing over the Wilson Corner map and onto the Santa Margarita map, to the boundary line's intersection with the Middle Branch of Huerhuero Creek, section 31, T28S/R14E; then

(19) Proceed north-northwesterly (downstream) along the Middle Branch of Huerhuero Creek approximately 2.3 miles in straight-line distance to the creek's intersection with the southern boundary line of section 24, T28S/R13E; then

(20) Proceed west along the southern boundary line of section 24, T28S/R13E, approximately 0.45 mile to that section's southwestern corner; then

(21) Proceed north along the western boundary line of section 24, T28S/R13E, approximately 1.0 mile to the boundary line's intersection with an unnamed unimproved road at the section's northwestern corner; then

(22) Proceed northwesterly on the unnamed unimproved road approximately 0.7 mile to the road's intersection with State Route 229 near BM 1138, section 14, T28S/R13E; then

(23) Proceed northeasterly on State Route 229 approximately 0.2 mile to the road's intersection with the Huerhuero Land Grant boundary line, section 14, T28S/R13E; then

(24) Proceed north-northwesterly along the boundary of the Huerhuero Land Grant approximately 3 miles, crossing onto the Creston map and returning to the beginning point.

**Comment by SoominHur** [comment]
Reviewed.
- Add scale information of the used maps.
