### ISSUE TITLE
candy_mountain

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#570]
# AVA: Candy Mountain (candy_mountain)

name | value
--- | ---
ava_id | candy_mountain
cfr_index | 9.272
revision | [T.D. TTB-163, 85 FR 60361, Sept. 25, 2020]
state | WA
county | Benton
within | **Update in File**
contains |  **Update in File**

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c#se27.1.9_1269
## Approved Maps [src]
The three United States Geological Survey (USGS) 1:24,000 scale topographic maps used to determine the boundary of the Candy Mountain viticultural area are titled:

(1) Badger Mountain, Washington, 2013;

(2) Benton City, Washington, 2013; and

(3) Richland, Washington, 2014.

## Boundary [src]
The Candy Mountain viticultural area is located in Benton County in Washington. The boundary of the Candy Mountain viticultural area is as described below:

(1) The beginning point is on the Badger Mountain map at the southernmost point of an unnamed road known locally as Arena Road. From the beginning point, proceed northwest in a straight line for approximately 1.85 miles, crossing onto the Benton City map, to the intersection with East Kennedy Road NE; then

(2) Proceed westerly along East Kennedy Road NE for approximately 2,500 feet to the intersection with an intermittent creek approximately 0.8 mile south of Lost Lake; then

(3) Proceed southeasterly along the easternmost fork of the intermittent creek to the intersection with Interstate 82; then

(4) Proceed southeast along Interstate 82 for 2.25 miles, crossing over the Richland map and onto the Badger Mountain map, and continuing along the ramp onto Interstate 182 to a point due south of the intersection of Dallas Road and an unnamed road known locally as East 260 Private Road NE; then

(5) Proceed north in a straight line for 0.5 mile, crossing onto the Richland map, to the intersection of Dallas Road and the 670-foot elevation contour; then

(6) Proceed west along the 670-foot elevation contour for 0.4 mile to the intersection with Arena Road; then

(7) Proceed southerly along Arena Road for approximately 0.45 miles, returning to the beginning point.

**Comment by elistockwell** [comment]
Working on this
