### ISSUE TITLE
tehachapi_mountains

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#579]
# AVA: Tehachapi Mountains (tehachapi_mountains)

name | value
--- | ---
ava_id | tehachapi_mountains
cfr_index | 9.273
revision | [T.D. TTB-164, 85 FR 73617, Nov, 19, 2020]
state | CA
county | Kern
within | **Update in File**
contains |  **Update in File**

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c#se27.1.9_1273
## Approved Maps [src]
The eight United States Geological Survey (USGS) 1:24,000 scale topographic maps used to determine the boundary of the Tehachapi Mountains viticultural area are titled:
(1) Bear Mountain, CA, 2015;
(2) Keene, CA, 2015;
(3) Cummings Mountain, CA, 2015;
(4) Tehachapi North, CA, 2015;
(5) Tehachapi NE, CA, 2015;
(6) Monolith, CA, 2015;
(7) Tehachapi South, CA, 2015; and
(8) Tejon Ranch, CA, 2015.

## Boundary [src]
The Tehachapi Mountains viticultural area is located in Kern County, California. The boundary of the Tehachapi Mountains viticultural area is as described below:

(1) The beginning point is on the Bear Mountain map at the intersection of the 4,800-foot elevation contour and an unnamed road known locally as Skyline Drive. From the beginning point, proceed easterly along the 4,800-foot elevation contour, crossing onto the Keene map, to the intersection of the 4,800-foot elevation contour and Horizon Court; then

(2) Proceed south along Horizon Court to its intersection with the 4,600-foot elevation contour; then

(3) Proceed east, then north along the meandering 4,600-foot elevation contour to its intersection with Shenandoah Place; then

(4) Proceed southeast in a straight line to the 4,400-foot elevation contour south of an unnamed road known locally as Big Sky Court; then

(5) Proceed east, then north along the meandering 4,400-foot elevation contour to its intersection with Bear Valley Road; then

(6) Proceed east in a straight line to the 4,600-foot elevation contour; then

(7) Proceed southeasterly along the 4,600-foot elevation contour, crossing onto the Cummings Mountain map and continuing southeasterly, then northerly along the 4,600-foot elevation contour, crossing back onto the Keene map, and continuing northerly along the 4,600-foot elevation contour to a point due west of the intersection of Marcel Drive and an unnamed road known locally as Woodford-Tehachapi Road; then

(8) Proceed east in a straight line to the intersection of Woodford-Tehachapi Road and Marcel Drive; then

(9) Proceed east in a straight line, crossing onto the Tehachapi North map and crossing Tehachapi Creek, to the 4,400-foot elevation contour northeast of the community of Cable, California; then

(10) Proceed easterly along the 4,400-foot elevation contour, crossing onto the Tehachapi NE map, and continuing southeasterly along the 4,400-foot elevation contour to a point due west of the terminus of Zephyr Court; then

(11) Proceed east in a straight line to the terminus of Zephyr Court; then

(12) Proceed east in a straight line to Sand Canyon Road; then

(13) Proceed south along Sand Canyon Road, crossing onto the Monolith map, to its intersection with East Tehachapi Boulevard; then

(14) Proceed southwesterly in a straight line, crossing the railroad tracks and State Route 58, to the 4,200-foot elevation contour; then

(15) Proceed westerly along the 4,200-foot elevation contour to its intersection with an unnamed intermittent creek; then

(16) Proceed southwest in a straight line to the 4,400-foot elevation contour; then

(17) Proceed west along the 4,400-foot elevation contour, crossing onto the Tehachapi South map, to its intersection with Tehachapi-Willow Springs Road; then

(18) Proceed south along Tehachapi-Willow Springs Road to its intersection with the 4,520-foot elevation contour; then

(19) Proceed west in a straight line to the intersection of the 4,840-foot elevation contour and Snowshoe Lane; then

(20) Proceed north in a straight line to the 4,800-foot elevation contour; then

(21) Proceed westerly along the 4,800-foot elevation contour, crossing onto the Cummings Mountain map and over two unnamed intermittent streams, and continuing to the intersection of the 4,800-foot elevation contour and a third unnamed intermittent stream; then

(22) Proceed south in a straight line to the 5,200-foot elevation contour; then

(23) Proceed southerly along the 5,200-foot elevation contour to a point northeast of the southern terminus of Arosa Road; then

(24) Proceed east in a straight line, crossing onto the Tehachapi South map and over an unnamed road known locally as Water Canyon Road, to the 5,400-foot elevation contour; then

(25) Proceed southeasterly, then south, then southwesterly along the 5,400-foot elevation contour, crossing onto the Cummings Mountain map and continuing to the intersection of the 5,400-foot elevation contour with an unnamed road known locally as Matterhorn Drive; then

(26) Proceed west in a straight line, crossing Mountain Climber Way, to the 4,600-foot elevation contour; then

(27) Proceed westerly along the 4,600-foot elevation contour to its intersection with High Gun Drive; then

(28) Proceed south in a straight line to the second intersection of the line with the 5,000-foot elevation contour; then

(29) Proceed west in a straight line, crossing onto the Tejon Ranch map, to the line's intersection with an unnamed 4-wheel drive road; then

(30) Proceed northwesterly along the 4-wheel drive road to its intersection with the southern terminus of an unnamed road known locally as Carlisle Drive; then

(31) Proceed southwesterly in a straight line to an unmarked 4,680-foot summit; then

(32) Proceed north in a straight line to the 3,640-foot elevation contour; then

(33) Proceed west in a straight line to the 3,600-foot elevation contour; then

(34) Proceed west, then northwesterly along the 3,600-foot elevation contour to its intersection with an unnamed intermittent stream northwest of Jack Springs Road; then

(35) Proceed northeast in a straight line, crossing onto the Bear Mountain map, and continuing to the intersection of the 4,800-foot elevation contour and an unnamed intermittent creek west of Rockspring Court; then

(36) Proceed north along the 4,800-foot elevation to a point due west of the intersection of the 4,800-foot elevation point and an unnamed road known locally as Skyline Drive; then

(37) Proceed east in a straight line to the beginning point.

**Comment by elistockwell** [comment]
Working on this issue now.

**Comment by alisonsnwong** [comment]
Checked!
