### ISSUE TITLE
cucamonga_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#58]
# AVA: Cucamonga Valley (cucamonga_valley)

name | value
--- | ---
ava_id | cucamonga_valley
cfr_index | 9.150
revision | [T.D. ATF-362, 60 FR 16578, Mar. 31, 1995]
state | CA
county | Riverside|San Bernadino
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Mt. Baldy, Calif., 1967, photorevised 1988; 
2. Cucamonga Peak, Calif., 1966, photorevised 1988; 
3. Devore, Calif., 1966, photorevised 1988; 
4. San Bernardino North, Calif., 1967, photorevised 1988; 
5. Ontario, Calif., 1967, photorevised 1981; 
6. Guasti, Calif., 1966, photorevised 1981; 
7. Fontana, Calif., 1967, photorevised 1980; 
8. San Bernardino South, Calif., 1967, photorevised 1980; 
9. Prado Dam, Calif., 1967, photorevised 1981; 
10. Corona North, Calif., 1967, photorevised 1981.

## Boundary [src]

(1) The beginning point is the intersection of Euclid Avenue and 24th Street on the Mt. Baldy, Calif. U.S.G.S. map; 
(2) From the beginning point, the boundary follows 24th Street east for approximately 0.3 mile, until it reaches the intersection of 24th Street with two unnamed light-duty streets to the north; 
(3) The boundary then diverges from 24th Street and goes straight north for approximately 0.3 mile, until it reaches the 2,000 foot contour line; 
(4) The boundary then follows the 2,000 foot contour line in a generally easterly direction across the Cucamonga Peak, Calif., U.S.G.S. map and onto the Devore, Calif., U.S.G.S. map until it reaches Lytle Creek Wash; 
(5) The boundary follows the intermittent stream in Lytle Creek Wash in a southeasterly direction to the end of the intermittent stream on the Devore, Calif., U.S.G.S. map; 
(6) The boundary then continues through Lytle Creek Wash, proceeding southeast in a straight line from the end of the intermittent stream, across the southwest corner of the San Bernardino North, Calif., U.S.G.S. map and onto the San Bernardino, South, Calif., U.S.G.S. map, to the northernmost point of the flood control basin at the end of the Lytle Creek Wash, a distance of approximately 4.3 miles; 
(7) The boundary then proceeds in a straight line south-southeast across the flood control basin to the point where Lytle Creek Channel exits the basin; 
(8) The boundary continues along Lytle Creek Channel until it empties into Warm Creek; 
(9) The boundary then follows Warm Creek until it meets the Santa Ana River; 
(10) The boundary then follows the western edge of the Santa Ana River in a generally southwesterly direction until it meets the San Bernardino—Riverside County line; 
(11) The boundary follows the county line west, crossing onto the Guasti, Calif., U.S.G.S. map, until it reaches the unnamed channel between Etiwanda and Mulberry Avenues 
(identified by the petitioner as Etiwanda Creek Channel); 
(12) The boundary then follows Etiwanda Creek Channel in a southerly direction until it parallels Bain Street; 
(13) The boundary then diverges from Etiwanda Creek Channel and follows Bain Street south until it ends at Limonite Avenue in the northeast corner of the Corona North, Calif., U.S.G.S. map; 
(14) The boundary then continues south in a straight line until it reaches the northern shore of the Santa Ana River; 
(15) The boundary then follows the north shore of the Santa Ana River until it intersects the 560 foot contour line in Section 1 T3S/R7W; 
(16) The boundary then follows the 560  contour line to the north of the Santa Ana River in a generally westerly direction until it reaches Euclid Avenue on the Prado Dam, Calif., U.S.G.S. map; 
(17) The boundary then follows Euclid Avenue north to the point of beginning.

**Comment by SoominHur** [comment]
Reviewed
- Add scale information of used maps in the attribute table.
