### ISSUE TITLE
cumberland_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#59]
# AVA: Cumberland Valley (cumberland_valley)

name | value
--- | ---
ava_id | cumberland_valley
cfr_index | 9.105
revision | [T.D. ATF-210, 50 FR 29971, July 23, 1985, as amended by T.D. ATF-249, 52 FR 5960, Feb. 27, 1987]
state | MD|PA
county | 
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Williamsport Quadrangle”, edition of 1969. 
2. “Shepherdstown Quadrangle”, edition of 1978. 
3. “Keedysville Quadrangle”, edition of 1978. 
4. “Middletown Quadrangle”, edition of 1953, photo-revised 1979. 
5. “Myersville Quadrangle”, edition of 1953, photo-revised 1971. 
6. “Smithsburg Quadrangle”, edition of 1953, photo-revised 1971. 
7. “Waynesboro Quadrangle”, edition of 1944, photo-revised 1968 and 1973. 
8. “Iron Springs Quadrangle”, edition of 1953, photo-revised 1968 and 1973. 
9. “Scotland Quadrangle”, edition of 1944, photo-revised 1968 and 1973. 
10. “Caledonia Park Quadrangle”, edition of 1944, photo-revised 1968 and 1973. 
11. “Walnut Botton Quadrangle”, edition of 1952, photo-revised 1969 and 1977. 
12. “Dickinson Quadrangle”, edition of 1952, photo-revised 1969 and 1977. 
13. “Mount Holly Springs Quadrangle”, edition of 1952, photo-revised 1968 and 1973. 
14. “Mechanicsburg Quadrangle”, edition of 1952, photo-revised 1968 and 1973. 
15. “LeMoyne Quadrangle”, edition of 1963, photo-revised 1972. 
16. “Steelton Quadrangle”, edition of 1963, photo-revised 1972. 
17. “Harrisburg West Quadrangle”, edition of 1969, photo-revised 1974. 
18. “Wertzville Quadrangle”, edition of 1952, photo-revised 1968 and 1973. 
19. “Sherman&#39;s Dale Quadrangle”, edition of 1952, photo-revised 1968 and 1973. 
20. “Landisburg Quadrangle”, edition of 1952, photo-revised 1969 and 1977. 
21. “Andersonburg Quadrangle”, edition of 1952, photo-revised 1969 and 1977. 
22. “Newville Quadrangle”, edition of 1952, photo-revised 1969 and 1975. 
23. “Newburg Quadrangle”, edition of 1966, photo-revised 1973. 
24. “Doylesburg Quadrangle”, edition of 1966, photo-revised 1973. 
25. “Roxbury Quadrangle”, edition of 1966, photo-revised 1973. 
26. “Fannettsburg Quadrangle”, edition of 1966, photo-revised 1973. 
27. “St. Thomas Quadrangle” edition of 1944, photo-revised 1968 and 1973. 
28. “McConnellsburg Quadrangle”, edition of 1944, photo-revised 1968 and 1973. 
29. “Mercersburg Quadrangle”, edition of 1943, photo-revised 1968 and 1973. 
30. “Clear Spring Quadrangle”, edition of 1955, photo-revised 1971. 
31. “Hedgesville Quadrangle”, edition of 1979. 
32. “Mason Dixon Quadrangle”, edition of 1943-53 
photorevised 1971.. 
33. “Hagerstown Quadrangle”, edition of 1943-53 
photorevised 1971, photoinspected 1977.. 
34. “Funkstown Quadrangle”, edition of 1943-53 
photorevised 1971, photoinspected 1977.. 
35. “Plainfield Quadrangle”, edition of 1975. 
36. “Shippensburg Quadrangle”, edition of 1973. 
37. “Chambersburg Quadrangle”, edition of 1973. 
38. “Williamson Quadrangle”, edition of 1973. 
39. “Greencastle Quadrangle”, edition of 1973. 
40. “Dillsburg Quadrangle”, edition of 1973.

## Boundary [src]

(1) Starting immediately west of the Town of Williamsport in Washington County, Maryland, at Lock 45 of the Chesapeake &amp; Ohio 
(C&amp;O) Canal National Historical Park and the confluence of the Potomac River and Conococheague Creek 
(see Williamsport Quadrangle), the boundary proceeds in a southeasternly direction along the perimeter of the park on the northeastern bank of the Potomac River to the confluence of Antitam Creek and the Potomac River; 
(2) Then southeast of Limekiln Road which runs along the perimeter of the park from Antietam Creek to the intersection of Limekiln Road and Harpers Ferry Road; 
(3) Then northeasterly a straight line approximately two miles to the 952-foot summit of Hawk&#39;s Hill; 
(4) Then northerly on a straight line approximately 2.5 miles to the intersection of Red Hill Road and Porterstown Road; 
(5) Then southeasterly along Porterstown Road to its intersection with Mount Briar—Trego Road; 
(6) Then southerly along Mount Briar—Trego Road to its intersection with Millbrook Road; 
(7) Then east along Millbrook Road to its intersection with State Route 67, approximately 0.5 mile north of Rohersville, Maryland; 
(8) Then directly east approximately 1.25 miles in a straight line to the 1,000-foot contour line of South Mountain; 
(9) Then in a north northeasterly direction along the 1,000-foot contour line of South Mountain in Washington County, Maryland, and Franklin and Cumberland counties in Pennsylvania to the point on South Mountain where the 1,000-foot contour line crosses State Hollow Road 
(Rt. 233); 
(10) Then north along Rt. 233 to the point where it crosses the 750-foot contour of South Mountain; 
(11) Then east along the 750-foot contour line of South Mountain to the point southwest of the Mount Holly Springs Reservoir where Cold Spring Run, a tributary of Yellow Breeches Creek, crosses the 750-foot contour line, approximately 3 miles southwest of the town of Mount Holly Springs, Pennsylvania; 
(12) Then east northeast in a straight line approximately seven miles to Center Point Knob, elev. 1050 feet, approximately two miles southeast of Boiling Springs, Pennsylvania 
(see Mechanicsburg Quadrangle); 
(13) Then continuing east northeast in a straight line approximately six miles to the point where U.S. Rt. 15 crosses Yellow Breeches Creek, approximately one mile east of Williams Grove, Pennsylvania; 
(14) Then east and northeast in a meandering line along the north bank of Yellow Breeches Creek to its confluence with the Susquehanna River; 
(15) Then north along the west bank of the Susquehanna River, which forms the western portion of the corporate boundary line of the City of Harrisburg, Pennsylvania, to the point where the 300-foot contour line and the west bank of the Susquehanna River meet; 
(16) Then directly west to the 700-foot contour line of Blue Mountain overlooking the Susquehanna River; 
(17) Then along the 700-foot contour line of Blue Mountain as it meanders west and around McClures Gap; 
(18) Then along the 700-foot contour line of Blue Mountain to the point where the 700-foot contour line crosses State Rt. 233; 
(19) Then northeast along Rt. 233 through Doubling Gap to the 1,000-foot contour line of Blue Mountain; 
(20) Then in a generally southwesterly direction along the 1,000-foot contour line of Blue Mountain into Franklin County to the point where the 1,000-foot contour line meets the roadbed of the Pennsylvania Turnpike, Interstate 76; 
(21) Then along the roadbed of the Pennsylvania Turnpike to the east entrance of the Blue Mountain Tunnel; 
(22) Then in a straight line approximately 6.5 miles to the intersection of State Rt. 533 and the 1,000-foot contour line of Blue Mountain, approximately one mile west northwest of Upper Strasburg, Pennsylvania; 
(23) Then southwest along the 1,000-foot contour line of Blue Mountain to and along the 1,000-foot contour line of Broad Mountain;  
(24) Then along the 1,000-foot contour line as it meanders along and around Broad Mountain and Front Mountain to the point where the 1,000-foot contour line crosses Wilson Run near Franklin Furnace, Pennsylvania; 
(25) Then southwest in a straight line approximately 3.5 miles to Parnell Knob, elev. 2060 feet; 
(26) Then west northwest in a straight line approximately four miles to the point where the 1,000-foot contour line crosses Township Run near Cape Horn on Cove Mountain, approximately two miles north northwest of Fort Loudon, Pennsylvania; 
(27) Then southwest along the 1,000-foot contour line of Cove Mountain into and out of Cove Gap; 
(28) Then along the 1,000-foot contour line of Cove Mountain and Two Top Mountain in Franklin County, Pennsylvania, and Sword Mountain and Fairview Mountain in Washington County, Maryland, to the point on Fairview Mountain where the 1,000-foot contour line intersects the National Road 
(U.S. Rt. 40); 
(29) Then west along U.S. Rt. 40 approximately 0.5 mile to the intersection of U.S. Rt. 40 and Cove Road; 
(30) Then south in a straight line from the intersection of U.S. Rt. 40 and Cove Road approximately 1.25 miles to the intersection of McCoys Ferry Road and State Rt. 56; 
(31) Then south along McCoys Ferry Road to the perimeter of the C&amp;O Canal National Historical Park along the Potomac River; 
(32) Then southeast along the perimeter of the C&amp;O National Historical Park to the point of beginning.

**Comment by ericallanwest** [comment]
Please label this one In Progress. Thanks!

**Comment by davidkli** [comment]
I have reviewed this AVA. This boundary is good, just had to fix some formatting in the attribute table.

**Comment by elistockwell** [comment]
Based on the formatting of the approved maps section, the maps available and the map next to it, it seems like the Williamsport approved map's date is a typo and should be 1979 instead of 1969.  This is the one that was used, just making note to avoid future confusion.

**Comment by MicheleTobias** [comment]
There was a big series of maps from 1969, so it probably exists in print form, but it hasn't been scanned into topoview yet. Remember that Topoview is a fairly new repository and doesn't necessarily have all of the maps that ever were printed.

**Comment by elistockwell** [comment]
Good point, and I guess assuming typos in the CFR can make things very messy.  In any case, the 1979 map is the best option we have right now.
