### ISSUE TITLE
diablo_grande

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#60]
# AVA: Diablo Grande (diablo_grande)

name | value
--- | ---
ava_id | diablo_grande
cfr_index | 9.156
revision | [T.D. ATF-399, 63 FR 33853, June 22, 1998]
state | CA
county | Stanislaus
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Patterson Quadrangle, California—Stanislaus Co., 1953 
Photorevised 1971, Photoinspected 1978.; 
2. Copper Mtn. Quadrangle, California—Stanislaus Co., 1953 
Field Check 1956, Aerial Photo 1971.; 
3. Wilcox Ridge, California—Stanislaus Co., 1956 
Photorevised 1971.; 
4. Orestimba Peak, California—Stanislaus Co., 1955 
Photorevised 1971..

## Boundary [src]

(1) Then proceed northwest to Salt Grass Springs to the point where the 1000 foot contour line crosses the northern section line of section 9, T. 6S., R. 6E., on the Copper Mtn., Quadrangle U.S.G.S. map. 
(2) Then proceed due south past Copper Mountain in section 16, T. 6S., R. 6E., to Mikes Peak in section 4, T. 7S., R. 6E., on the Wilcox Ridge Quadrangle U.S.G.S. map. 
(3) Then proceed due west to Oristimba Creek in section 6, T. 7S., R. 6E. 
(4) Then proceed following Orestimba Creek south/southeast and then east/northeast to the point where Orestimba Creek meets Bench Mark #340 in section 28, T. 7S., R. 7E., on the Orestimba Peak Quadrangle U.S.G.S. map. 
(5) Then proceed northwest to the point of beginning at Reservoir Spillway 780 in section 8, T. 6S., R. 7E.

**Comment by fyfangyao** [comment]
I use (1) Patterson, Calif., 1953 (photorevised 1972); (2) Copper Mtn, CA, 1953, revised 1956 (photorevised 1972); (3) Wilcox ridge, CA, 1956, (photorevised 1972); and (4) Orestimba Peak, Calif., 1955 (photorevised 1973).

**Comment by SoominHur** [comment]
Reviewed.
- Set the begining point (Reservoir Spillway 780) as the intersection between western boundary of section 8 (T6S, R7E) and Salado Creek.
- Used "Copper Mtn.; CA", 1956 (photorevised 1971), scale 1:24000. map instead of (2) Copper Mtn. Quadrangle, California—Stanislaus Co., 1953 (Field Check 1956, Aerial Photo 1971)
