### ISSUE TITLE
diamond_mountain_district

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#61]
# AVA: Diamond Mountain District (diamond_mountain_district)

name | value
--- | ---
ava_id | diamond_mountain_district
cfr_index | 9.166
revision | [T.D. ATF-456, 66 FR 29698, June 1, 2001]
state | CA
county | Napa
within | Napa Valley\|North Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Mark West Springs, CA 1993 
2. Calistoga, CA 1993.

## Boundary [src]

(1) Then north and east along Petrified Forest Road approximately 1.9 miles to the point where it intersects the 400-foot contour just east of Section 35 of Township 9 North, Range 7 West, Mount Diablo Base and Meridian, in the Mallacomes land grant;  
(2) Then generally east southeast along the 400-foot contour approximately 6.5 miles to the point where it intersects Ritchey Creek in Section 3 of Township 8 North, Range 6 West, Mount Diablo Base and Meridian;  
(3) Then west southwest along Ritchey Creek approximately 2.2 miles to the point where it intersects the boundary between Sections 17 and 20 of Township 8 North, Range 6 West, Mount Diablo Base and Meridian;  
(4) Then due west in a straight line along the section boundary approximately 0.8 miles to the point where it intersects the boundary between Napa and Sonoma Counties between Sections 18 and 19 of Township 8 North, Range 6 West, Mount Diablo Base and Meridian;  
(5) Then generally northwest along the boundary between Napa and Sonoma Counties approximately 4.2 miles to the point where it intersects Petrified Forest Road, to the point of beginning.

**Comment by SoominHur** [comment]
Reviewed. Edited created date in attribute table.
