### ISSUE TITLE
Green Valley of Russian River Valley History

### ISSUE THREAD

**Issue by elistockwell** [UCDavisLibrary/ava#611]
This AVA has the following revisions:

- [ ] [T.D. ATF-161, 48 FR 52579, Nov. 21, 1983]
- [ ] [T.D. TTB-60, 72 FR 13692, Mar. 23, 2007]

Each revision should be represented by a polygon inside the .geojson file for this AVA.  See the [Adding Historical Boundaries](https://github.com/UCDavisLibrary/ava/blob/master/digitizing_ava_boundaries.md#adding-historical-ava-boundaries) document for more information on how to add historical boundaries.

**Comment by kurtishouser** [comment]
The correct name is Green Valley of Russian River Valley so be sure to change all the affected fields as well as the file name.

See Issue #446.

**Comment by MicheleTobias** [comment]
Ah, the original script that made this one dropped the "Valley" from the end.  Whoever works on the history for this one can fix the name in the "ava_id" and "name" columns.

FYI, don't get confused by the "Russian River Valley" AVA which is an unfortunately similarly named boundary.

**Comment by elistockwell** [comment]
Fixed ava_id and name fields in the pull request addressing issue 655, will make sure there are no other errors when I do the history for this AVA.

**Comment by elistockwell** [comment]
Working on this now.

**Comment by elistockwell** [comment]
Looks like the revision also just has to do with the name, changing from "Sonoma County Green Valley" to what it is now.
