### ISSUE TITLE
dos_rios

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#62]
# AVA: Dos Rios (dos_rios)

name | value
--- | ---
ava_id | dos_rios
cfr_index | 9.175
revision | [T.D. TTB-34, 70 FR 59995, Oct. 14, 2005]
state | CA
county | Mendocino
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Dos Rios, California—Mendocino County, 1967 edition, revised 1994; 
2. Laytonville, California—Mendocino County, 1967 edition, revised 1994; 
3. Iron Peak, California—Mendocino County, 1967 edition, revised 1994; and 
4. Covelo West, California—Mendocino County, 1967 edition, photoinspected 1973.

## Boundary [src]

(1) Beginning in the northwestern quarter of the Dos Rios map in section 32, T22N, R13W, at the intersection of the 2,000-foot contour line and Poonkinny Road, proceed southerly and then easterly along the meandering 2,000-foot contour line to its intersection with the eastern boundary of section 2, T21N, R13W, immediately south of State Route 162 
(Dos Rios Quadrangle); then 
(2) Proceed straight south along the section line, crossing the Middle Fork of the Eel River, to the southeast corner of section 11, T21N, R13W 
(Dos Rios Quadrangle); then 
(3) Proceed 0.9 mile straight west along the southern boundary of section 11 to its intersection with the 2,000-foot elevation line, T21N, R13W 
(Dos Rios Quadrangle); then 
(4) Proceed northerly then westerly along the meandering 2,000-foot contour line, crossing Big Water Canyon, Doghouse Creek, and Eastman Creek, to the contour line&#39;s intersection with the southern boundary of section 17, T21N, R13W 
(Dos Rios Quadrangle); then 
(5) Proceed 2.1 miles straight west along the section line, crossing the Eel River, to the section line&#39;s intersection with the 2,000-foot contour line along the southern boundary of section 18, T21N, R13W 
(Dos Rios Quadrangle); then 
(6) Proceed northerly along the meandering 2,000-foot contour line, crossing between the Dos Rios and Laytonville maps 
(passing around the Sims 2208 benchmark near the southeast corner of section 36, T22N, R14W), and, returning to the Laytonville map, continue westerly to the contour line&#39;s intersection with the southwest corner of section 36, T22N, R14W, at Windy Point 
(Laytonville Quadrangle); then 
(7) Proceed 1.2 miles straight north along the section line to its intersection with the 2,000-foot elevation line, section 25, T22N, R14W 
(Laytonville Quadrangle); then 
(8) Proceed northerly along the meandering 2,000-foot elevation, crossing between the Laytonville and Iron Peak maps, and, returning to the Iron Peak map, continue along the contour line to its intersection with the western boundary of section 14 immediately south of an unnamed unimproved road, T22N, R14W 
(Iron Peak Quadrangle); then 
(9) Proceed straight north along the section line to the southeast corner of section 3, T22N, R14W 
(Iron Peak Quadrangle); then 
(10) Proceed straight west along the section line to the southwest corner of section 3, T22N, R14W 
(Iron Peak Quadrangle); then 
(11) Proceed straight north along the section line to the northwest corner of section 3, T22N, R14W 
(Iron Peak Quadrangle); then 
(12) Proceed straight east along the section line, crossing the Eel River, to the northeast corner of section 2, which coincides with the Round Valley Indian Reservation&#39;s southern boundary, T22N, R14W 
(Iron Peak Quadrangle); then 
(13) Proceed straight south along the section line to the southeast corner of section 2, T22N, R14W 
(Iron Peak Quadrangle); then 
(14) Proceed 0.3 mile straight east to the section line&#39;s intersection with the 2,000-foot elevation line along the northern boundary of section 12, T22N, R14W, west of Eberle Ridge, 
(Iron Peak Quadrangle); and 
(15) Proceed generally southeast along the meandering 2,000-foot elevation, crossing onto the Covelo West map and continuing southerly along the 2,000-foot contour line from Stoner Creek in section 18, T22N, R13W, and, returning to the Dos Rios map, continue southeasterly along the 2,000-foot contour line 
(crossing Goforth and Poonkinny Creeks), to the beginning point at the contour line&#39;s intersection with Poonkinny Road.

**Comment by fyfangyao** [comment]
I am working on it.

**Comment by fyfangyao** [comment]
I use “Covelo West, CA," 7.5 Minute Series, edition of 1967, (revised 1969) because I cannot find the map with the required revision year.

**Comment by SoominHur** [comment]
Reviewed.
- For (4), the line stopped at the intersection between 2000ft contour and eastern boundary. So, completed "Proceed northerly then westerly along the meandering 2,000-foot contour line, ... , to the contour line's intersection with the southern boundary of section 17, T21N, R13W (Dos Rios Quadrangle). "
- Corrected Created date
