### ISSUE TITLE
dry_creek_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#63]
# AVA: Dry Creek Valley (dry_creek_valley)

name | value
--- | ---
ava_id | dry_creek_valley
cfr_index | 9.64
revision | [T.D. ATF-137, 48 FR 35397, Aug. 4, 1983, as amended by T.D. ATF-468, 66 FR 50565, Oct. 4, 2001]
state | CA
county | Sonoma
within | North Coast\|Northern Sonoma
contains | Rockpile

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Geyserville Quadrangle, California—Sonoma County,” 7.5 minute series, 1955 
Photorevised 1975.; 
2. “Jimtown Quadrangle, California—Sonoma County,” 7.5 minute series, 1955 
Photorevised 1975.; 
3. “Healdsburg Quadrangle, California—Sonoma County,” 7.5 minute series, 1955 
Photorevised 1980.; 
4. “Guerneville Quadrangle, California—Sonoma County,” 7.5 minute series, 1955; 
5. “Cazadero Quadrangle, California—Sonoma County,” 7.5 minute series, 1978; and 
6. “Warm Springs Dam Quadrangle 
formerly ‘Skaggs Springs Quadrangle’., California—Sonoma County,” 7.5 minute series, 1978.

## Boundary [src]

From the beginning point, lying at the intersection of latitude line 38 degrees 45 minutes and the northwest corner of Section 5, T. 10 N., R. 10 W. on the “Geyserville Quadrangle” map, the boundary runs—
(1) Southeasterly in a straight line approximately 11,000 feet 
(closely following the ridge line) to the northeast corner of Section 9, T. 10 N., R. 10 W.; 
(2) Then southerly along the east line of Section 9 to the southeast corner thereof; 
(3) Then S. 74 degrees, E. 2,800 feet in a straight line to the northeasterly tip of a small unnamed lake; 
(4) Then N. 57 degrees, E. 2,300 feet in a straight line to the southeast corner of Section 10, T. 10 N., R. 10 W.; 
(5) Then S. 16 degrees, E. 1,800 feet in a straight line to the point on a peak identified as having an elevation of 664 feet; 
(6) Then S. 55 degrees, E. 7,900 feet in a straight line to the most northerly point on the northeasterly line of “Olive Hill” cemetery lying on the easterly side of Canyon Road; 
(7) Then southeasterly along the northeasterly line of “Olive Hill” cemetery to the most easterly point thereon; 
(8) Then S. 2 degrees, E. 3,100 feet in a straight line to the point in the westerly fork of Wood Creek lying at the westerly terminus of a dirt road; 
(9) Then southerly 3,000 feet along the west fork of Wood Creek to the point lying 400 feet north of the point on a peak identified as having an elevation of 781 feet; 
(10) Then southerly 400 feet in a straight line to the point on a peak identified as having an elevation of 781 feet; 
(11) Then S. 50  degrees, E. 15,500 feet in a straight line to the point lying at the intersection of Lytton Creek and the township line common to T. 9 N. and T. 10 N. in R. 9 W.; 
(12) Then southerly along the meanders of Lytton Creek to the point of intersection with Lytton Springs Road in T. 9 N., R. 9 W.; 
(13) Then easterly along Lytton Springs Road to the point of intersection with U.S. Highway 101 
(a.k.a. Redwood Highway) on the “Jimtown Quadrangle” map; 
(14) Then southerly along U.S. Highway 101 to the point of intersection with an unnamed light duty road 
(known locally as Chiquita Road) on the “Geyserville Quadrangle” map; 
(15) Then easterly along the unnamed light duty road to the point of intersection with an unnamed heavy duty road 
(known locally as Healdsburg Avenue) on the “Jimtown Quadrangle” map; 
(16) Then southerly along the unnamed heavy duty road through the town of Healdsburg to the point of intersection with the Russian River on the “Healdsburg Quadrangle” map; 
(17) Then southerly along the meanders of the Russian River to the confluence of Dry Creek; 
(18) Then west-southwesterly 1,300 feet in a straight line to an unnamed light duty road 
(known locally as Foreman Lane); 
(19) Then westerly along the unnamed light duty road, crossing West Dry Creek Road and passing Felta School, to the point of intersection with Felta Creek on the “Guerneville Quadrangle” map; 
(20) Then southwesterly 18,000 feet along the meanders of Felta Creek to the point lying at the intersection of three springs in T. 8 N., R. 10 W., approximately 300 feet east from the word “Springs”; 
(21) Then S. 58 degrees, W. 15,000 feet in a straight line to the southwest corner of Section 9, T. 8 N., R. 10 W.; 
(22) Then northerly along the west line of Sections 9 and 4, T. 8 N., R. 10 W., continuing along the west line of Section 33, T. 9 N., R. 10 W. to the northwest corner thereof; 
(23) Then westerly along the south line of Sections 29 and 30, T. 9 N., R. 10 W. to the southwest corner of Section 30 on the “Cazadero Quadrangle” map; 
(24) Then northerly along the west line of Sections 30 and 19, T. 9 N., R. 10 W. to the northwest corner of Section 19; 
(25) Then westerly along the south line of Section 13, T. 9 N., R. 11 W. to the southwest corner thereof; 
(26) Then southwesterly 14,200 feet in a straight line to the northeast corner of Section 20, T. 9 N., R. 11 W.; 
(27) Then westerly along the north line of Section 20 to the northwest corner thereof; 
(28) Then northerly along the east line of Sections 18, 7, and 6, T. 9 N., R. 11 W., continuing along the east line of Sections 31, 30, 19, 18, 7, and 6, T. 10 N., R. 11 W. to the point of intersection with latitude line 38 degrees 45 minutes on the “Warm Springs Dam Quadrangle” map; and 
(29) Then easterly along latitude line 38 degrees 45 minutes to the point of beginning on the “Geyserville Quadrangle” map.

**Comment by SoominHur** [comment]
Reviewed
- Edit created date in the attribute table.
- Remove nodes to make (1) a straight line ... to the northeast corner of Section 9, T. 10 N., R. 10 W.
- The line should follow (19) along the unnamed light duty road (known locally as Foreman Lane). But according to the google map, the line followed along Bramkampo Rd in the middle. So I edit the line to just follow Foreman Ln.

**Comment by MicheleTobias** [comment]
@sdlong reports:

There is an error in (28), which is a the northern border of the AVA:

(28) Then northerly along the east line of Sections 18, 7, and 6, T. 9 N., R. 11 W., continuing along the east line of Sections 31, 30, 19, 18, 7, and 6, T. 10 N., R. 11 W. to the point of intersection with latitude line 38 degrees 45 minutes on the “Warm Springs Dam Quadrangle” map;

Currently, the line goes north of 38 degrees 45 minutes onto the the Cloverdale Map, which is not an approved map for the AVA

**Comment by MicheleTobias** [comment]
I made the fix to this one and check the rest of the points.
