### ISSUE TITLE
dundee_hills

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#64]
# AVA: Dundee Hills (dundee_hills)

name | value
--- | ---
ava_id | dundee_hills
cfr_index | 9.180
revision | [T.D. TTB-18, 69 FR 69527, Nov. 30, 2004]
state | OR
county | Yamhill
within | Willamette Valley
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Dundee Quadrangle, Oregon, 1956, revised 1993; 
2. Newberg Quadrangle, Oregon, 1961, photorevised 1985; and 
3. Dayton Quadrangle, Oregon, 1957, revised 1992.

## Boundary [src]

(1) The beginning point is on the Dundee map at the intersection of the 200-foot contour line with Kuehne Road at the common boundary line of sections 47 and 48, T3S, R3W; 
(2) From the beginning point, proceed east then south along the meandering 200-foot contour line, crossing over to and back off the Newberg map, and then cutting diagonally southwest through the town of Dundee to the 200-foot contour line&#39;s intersection with Hess Creek, section 34, T3S, R3W 
(Dundee Quadrangle); then 
(3) Proceed south, then west, and then northeast, along the meandering 200-foot contour line, twice crossing over to and back off the Dayton map, to the contour line&#39;s intersection with Abbey Road after the line passes a quarry and crosses the two forks of Millican Creek in section 52, T3S, R3W 
(Dundee Quadrangle); then 
(4) Proceed generally north on Abbey Road to Kuehne Road and then follow Kuehne Road northeasterly to the beginning point.

**Comment by gdmf** [comment]
Please add the "In Progress" label to this one.

**Comment by gdmf** [comment]
I think I'm confused where to find the authoritative "creation_date". For instance, here is the Federal Register document establishing the [Dundee Hills AVA](https://www.gpo.gov/fdsys/pkg/FR-2004-11-30/pdf/04-26330.pdf). Is the creation_date the date at the top of the Federal Register document itself (November 30, 2004)? Or is it the "Effective Dates" (January 31, 2005), found in the first column, first page? Or the "Approved" date (November 9, 2004), found in the signature section? Or the "Filed" date (11-29-04), final line?

**Comment by MicheleTobias** [comment]
Use the Effective Date.
