### ISSUE TITLE
dunnigan_hills

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#65]
# AVA: Dunnigan Hills (dunnigan_hills)

name | value
--- | ---
ava_id | dunnigan_hills
cfr_index | 9.145
revision | [T.D. ATF-340, 58 FR 28352, May 13, 1993]
state | CA
county | Yolo
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Guinda, Calif.,” 1959. 
2. “Dunnigan, Calif.,” 1953. 
3. “Woodland, Calif.,” 1953.

## Boundary [src]

(1) The beginning point is on the Dunnigan, Calif., U.S.G.S. map at the intersection of Buckeye Creek and U.S. Route 99W just south of the Colusa-Yolo county line; 
(2) From the beginning point, the boundary follows Route 99W in a southeasterly direction until an unnamed westbound light-duty road coincident with a grant boundary 
(referred to by the petitioner as County Road 17) diverges from Route 99W just north of the town of Yolo, California, on the Woodland, Calif., U.S.G.S. map; 
(3) The boundary then follows the County Road 17 for approximately 2 miles to an unnamed southbound light duty road 
(referred to by the petitioner as County Road 95A); 
(4) The boundary then follows County Road 95A south for approximately   mile to an unnamed westbound light duty road 
(referred to by the petitioner as County Road 17A); 
(5) The boundary then proceeds west along County Road 17A for approximately   mile to an unnamed southbound light duty road 
(referred to by the petitioner as County Road 95); 
(6) The boundary then proceeds south along County Road 95 for approximately 1 mile to an unnamed light duty road which goes in a southwesterly direction 
(referred to by the petitioner as County Road 19); 
(7) The boundary then proceeds southwest along County Road 19 for approximately   mile to an unnamed light duty road which travels south-southwest 
(referred to by the petitioner as County Road 94B); 
(8) The boundary then proceeds southwest along County Road 94B approximately 1  mile until it intersects Cache Creek; 
(9) The boundary then follows Cache Creek in a westerly direction 5.5 miles until it intersects an unnamed north-south light duty road approximately 1 mile north of the city of Madison, California 
(referred to by the petitioner as County Road 89); 
(10) The boundary then follows County Road 89 two miles in a northerly direction back on to the Dunnigan, Calif., U.S.G.S. map where it intersects an unnamed light duty road 
(referred to by the petitioner as County Road 16); 
(11) The boundary follows County Road 16 west for approximately 2 miles onto the Guinda, Calif., U.S.G.S. map, where it turns north onto an unnamed light-duty road between sections 31 and 32 of T10N/R1W 
(referred to by the petitioner as County Road 87); 
(12) The boundary follows County Road 87 north for 2 miles to an unnamed east-west light duty road 
(referred to by the petitioner as County Road 14); 
(13) The boundary follows County Road 14 west for 3 miles, and then leaves the unnamed road and turns north on the dividing line between sections 22 and 23 of T11N/R2W. 
(14) The boundary continues due north until it intersects Little Buckeye Creek just south of the Yolo-Colusa county line; 
(15) The boundary then follows Little Buckeye Creek in an easterly direction until it joins Buckeye Creek; 
(16) The boundary then follows Buckeye Creek in an easterly direction back to the point of beginning on the Dunnigan, Calif., U.S.G.S. map.

**Comment by fyfangyao** [comment]
I am working on this.

**Comment by fyfangyao** [comment]
I use (1) "Guinda, Calif.," 1959 (edition 1968), (2) "Dunnigan, Calif.," 1953 (edition 1966), and (3) "Woodland, Calif.," 1953 (edition 1968) because the approved maps don’t specify the edition years.

**Comment by SoominHur** [comment]
Reviewed.
- Add scale information of the used maps in the attribute table.
