### ISSUE TITLE
(d) Transition Period section from the eCFR page is in the 'boundary_description' property 

### ISSUE THREAD

**Issue by kurtishouser** [UCDavisLibrary/ava#655]
There are only nine AVAs with this issue.

Temecula Valley
Mendocino
Green Valley of Russian River
Columbia Valley
Ohio River Valley
Redwood Valley
Sta. Rita Hills
Yamhill-Carlton
Calistoga

So I guess the data needs to be removed or moved to it's own property?

I looked at a couple of the CFR documents for these and it appears that sometimes it's just a name change (Sta. Rita Hills, Green Valley of Russian River Valley). I checked the recent St. Rita Hills pull request from @elistockwell and it looks like all historical data will remain in one file even if the previous name was different. Although an edge case it might be prudent to mention this in the Adding Historical AVA Boundaries instructions.

**Comment by MicheleTobias** [comment]
This is another artifact from the script that created the original files. Thanks for finding these!

**Comment by MicheleTobias** [comment]
For anyone working on this, look for extra text at the end of the "boundary_description" field that isn't a part of the actual boundary description and remove it.  Look for information that needs to be put in a different field.  For example, with Temecula Valley, it talks about changing the name.  That information should go in the "aka" field ("also known as").

**Comment by MicheleTobias** [comment]
Thank you @elistockwell for taking care of this today!
