### ISSUE TITLE
eagle_peak_mendocino_county

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#67]
# AVA: Eagle Peak Mendocino County (eagle_peak_mendocino_county)

name | value
--- | ---
ava_id | eagle_peak_mendocino_county
cfr_index | 9.237
revision | [T.D. TTB-124, 79 FR 60973, Oct. 9, 2014]
state | CA
county | Mendocino
within | North Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Laughlin Range, California, provisional edition 1991; 
2. Redwood Valley, Calif., 1960, photo revised 1975; 
3. Orrs Springs, California, provisional edition 1991; and 
4. Greenough Ridge, California, provisional edition 1991.

## Boundary [src]

(1) The beginning point is located on the Laughlin Range map within McGee Canyon at the point where the 1,600-foot contour line intersects with Bakers Creek near the western boundary of section 25, T17N/R13W. From the beginning point, proceed southeasterly 
(downstream) approximately 0.2 mile along Bakers Creek to the creek&#39;s intersection with the 1,400-foot contour line, section 25, T17N/R13W; then 
(2) Proceed southeasterly in a straight line approximately 1.5 miles, crossing onto the Redwood Valley map, to the southeast corner of section 36, T17N/R13W; then 
(3) Proceed west-southwesterly in a straight line approximately 0.55 mile, crossing onto the Laughlin Range map, to the intersection of U.S. Highway 101 and an unnamed road locally known as Reeves Canyon Road, section 1, T16N/R13W; then 
(4) Proceed southeasterly in a straight line approximately 0.9 mile, crossing onto the Redwood Valley map, to the southeast corner of section 1, T16N/R13W; then 
(5) Proceed south-southwesterly in a straight line approximately 0.65 mile to the intersection of an unnamed, unimproved road and an unnamed intermittent stream located approximately 500 feet south of Seward Creek, section 12, T16N/R13W; then 
(6) Proceed west-southwesterly in a straight line approximately 0.9 mile, crossing onto the Laughlin Ridge map, to the southwest corner of section 12, T16N/R13W; then 
(7) Proceed west-southwesterly in a straight line approximately 0.8 mile, crossing onto the Orrs Springs map, to the 1,883-foot elevation point in section 14, T16N/R13W; then 
(8) Proceed west-southwesterly in a series of three straight lines 
(totaling approximately 3.15 miles in distance), first to the 1,836-foot elevation point in section 15, T16N/R13W; then to the 1,805-foot elevation point in section 16, T16N/R13W; and then to the 2,251-foot elevation point in section 20, T16W/R13W; then 
(9) Proceed south-southwesterly in a straight line approximately 0.8 mile to the 2,562-foot elevation point, section 20, T16N/R13W; then 
(10) Proceed north-northwesterly in a straight line approximately 0.8 mile to the 2,218-foot elevation point, section 19, T16N/R13W; then 
(11) Proceed northeasterly in a straight line approximately 0.35 mile to the 2,112-foot elevation point in the southeast corner of section 18, T16N/R13W; then 
(12) Proceed north-northeasterly in a straight line approximately 0.9 mile to the 2,344-foot elevation point, section 17, T16N/R13W; then 
(13) Proceed northwesterly in a straight line approximately 1.8 miles, crossing onto the Laughlin Range map, to the intersection of the R13W/R14W common boundary line and an unnamed, unimproved road east of Leonard Lake, section 1, T16N/R14W; then 
(14) Proceed west-northwesterly along the unnamed, unimproved road to the road&#39;s intersection with the 2,000 foot contour line between Leonard Lake and Mud Lake, section 1, T16N/R13W; then 
(15) Proceed north-northwesterly in a straight line approximately 1.6 miles, crossing onto the Greenough Ridge map, to the 2,246-foot elevation point, section 26, T17N/R14W; then 
(16) Proceed northerly in a straight line approximately 0.9 mile to the 2,214-foot elevation point, section 23, T17N/R14W; then 
(17) Proceed northeasterly in a straight line approximately 1 mile, crossing onto the Laughlin Range map, to the peak of Impassable Rocks, section 24, T17N/R14W; then 
(18) Proceed northwesterly in a straight line approximately 0.95 mile, crossing onto the Greenough Ridge map, to the 2,617-foot elevation point, section 14, T17N/R14W, and continue northwesterly in a straight line approximately 0.8 mile to the 2,836-foot elevation point of Irene Peak, section 11, T17N/R14W; then 
(19) Proceed northerly in a straight line approximately 1 mile to the intersection of 3 unnamed unimproved roads approximately 0.3 mile west of the headwaters of Walker Creek 
(locally known as the intersection of Blackhawk Drive, Walker Lake Road, and Williams Ranch Road) section 2, T17N/R14W; then 
(20) Proceed easterly along the unnamed improved road, locally known as Blackhawk Drive, approximately 1.35 miles, crossing onto the Laughlin range map, to the road&#39;s intersection with the section 2 eastern boundary line, T17N/R14W; then 
(21) Proceed east-northeasterly in a straight line approximately 0.75 mile, returning to the 2,213 elevation point near the northeast corner of section 1, T17N/R14W; then 
(22) Proceed southeasterly in a straight line approximately 3.55 miles to BM 1893 
(0.2 mile south of Ridge) in section 16, T17N/R13W, and then continue southeasterly in a straight line approximately 0.85 mile to a radio facility located at approximately 2,840 feet in elevation in the Laughlin Range, section 15, T17N/R13W; then 
(23) Proceed easterly in a straight line approximately 0.85 mile to another radio facility located at approximately 3,320 feet in elevation in the Laughlin Range, section 14, T17N/R13W; then 
(24) Proceed southerly in a straight line approximately 1.5 miles to the 2,452-foot elevation point in section 26, T17N/R13W; then 
(25) Proceed southeasterly in a straight line approximately 0.4 mile to the intersection of the 1,800-foot contour line with Bakers Creek within McGee Canyon, section 26, T17N/R13W; then 
(26) Proceed southeasterly 
(downstream) approximately 0.2 mile along Bakers Creek, returning to the beginning point.

**Comment by SoominHur** [comment]
Reviewed
- Add scale information of used maps in the attribute table.
- Edit straight line to follow (1) along Bakers Creek to the creek's intersection with the 1,400-foot contour line, section 25 (T17N/R13W)
