### ISSUE TITLE
Fair Play American Viticultural Area (Calif.)

### ISSUE THREAD

**Issue by labriola** [UCDavisLibrary/ava#673]
It looks as though the last edit of Fairplay may have introduced an inadvertent partial duplication. It seems to now include two features with identical properties but an overlap on all but the north eastern side.

**Comment by MicheleTobias** [comment]
There are two polygons because Fairplay has two boundaries.  One is the boundary defined when the AVA was originally named, and the other is the revision of the boundary when the TTB included more area (based on soil samples).

**Comment by MicheleTobias** [comment]
The attribute table should indicate which is current because it has no end date.

**Comment by labriola** [comment]
@MicheleTobias thank you for taking the time to respond; it's appreciated. I absolutely missed the valid_end attribute so I will adjust. Thanks again
