### ISSUE TITLE
Data consistency with valid_end field

### ISSUE THREAD

**Issue by labriola** [UCDavisLibrary/ava#674]
Building a bit upon closed issue #438

The valid_end field seems to use the following ways of stating that a feature is the current version:

valid_end == 'N/A' 
valid_end == null
valid_end == '' #empty string

While it's certainly easy to work around when using the data, it's probably best for cross-platform consistency to establish a single standard, e.g. it will either contain a data formatted as YYYY-MM-DD or it will contain null.

I believe the following list is exhaustive based on master of those features using a 'N/A' or a space as opposed to null for reference:

**N/A**
- Applegate Valley
- Cayuga Lake
- Chehalem Mountains
- Dundee Hills
- Eola-Amity Hills
- Lake Chelan
- Ribbon Ridge
- Rogue Valley
- The Rocks District of Milton-Freewater

**Space**
- Appalachian High Country
- Augusta
- Cape May Peninsula
- Catoctin
- Central Delaware Valley
- Champlain Valley of New York
- Crest of the Blue Ridge Henderson County
- Cumberland Valley
- Dahlonega Plateau
- Eagle Foothills
- Eastern Connecticut Highlands
- Finger Lakes
- Fredericksburg in the Texas Hill Country
- Grand River Valley
- Haw River Valley
- Hermann
- Hudson River Region
- Indiana Uplands
- Isle St. George
- Kanawha River Valley
- Lake Erie
- Lake Michigan Shore
- Lancaster Valley
- Lehigh Valley
- Linganore
- Loess Hills District
- Long Island
- Martha's Vineyard
- Middleburg Virginia
- Monticello
- Northern Neck George Washington Birthplace
- North Fork of Long Island
- Outer Coastal Plain
- Seneca Lake
- Snake River Valley
- Southern Oregon
- The Hamptons Long Island
- Upper Hiwassee Highlands
- Upper Hudson

**Comment by MicheleTobias** [comment]
Thanks for this!  The way the original data templates were made introduced some inconsistencies and making the rest of the data by hand means there are more human-created errors compounding that.  I appreciate you finding this an bringing it to our attention.  

@elistockwell when you get a chance, can you look at these and see if we can fix them?  Also, we should set a standard for the blank fields, apply that, and update the documentation for the fields to say what it should be.

**Comment by labriola** [comment]
FWIW, I would be happy to submit a PR to fix these (assuming you let me know your preference for the value), however, I assumed these were the output of an existing process. If I am wrong, and it would be helpful to have the revised geojson files, let me know and they are yours

**Comment by MicheleTobias** [comment]
@labriola if you have the time, I'd appreciate a PR with the fix!  Looks like we use null in the other fields like AKA and LCSH, so let's use null here as the standard for no data.

I'm curious to know how you found this project and what you're using it for.  We collect links and citations to projects using the data on the main readme, so let me know if you want a mention there.

**Comment by labriola** [comment]
@MicheleTobias got it. I will get this to you tomorrow. I am going to open a separate issue and create a related PR on a few more formatting issues I found (e.g. Yakima Valley : 2020/10/26 whereas the others use dashes). Stay tuned on those and will reach out on your other question soon

**Comment by MicheleTobias** [comment]
Sounds good!  I thought we had caught all the dates... it's like a whack-a-mole.  When I get a chance, I need to finish my script that checks for these kinds of errors, but in the mean time, if you have fixes to send, I'm happy to have them.

**Comment by elistockwell** [comment]
Thanks for catching this!  While looking at your PR I noticed that a lot of other fields also have an empty string instead of null.  This seems like something we could fix pretty quick with some R code, is that something you would want to work on Michael?  If not let me know and I am happy to.

**Comment by labriola** [comment]
@elistockwell yep, i was going to fix the rest of the dates and empty fields next. I will just keep submitting them until we get everything cleaned up if you are good with that

**Comment by labriola** [comment]
Side note, I am used to working in projects where each change should be in a separate PR for review. If you prefer that I do all of this and make one big PR at the end, I am also happy to do so

**Comment by elistockwell** [comment]
Works for me!  I will double check with Michele.
