### ISSUE TITLE
edna_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#68]
# AVA: Edna Valley (edna_valley)

name | value
--- | ---
ava_id | edna_valley
cfr_index | 9.35
revision | [T.D. ATF-101, 47 FR 20299, May 12, 1982, as amended by T.D. ATF-249, 52 FR 5956, Feb. 27, 1987]
state | CA
county | San Luis Obispo
within | Central Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “San Luis Obispo Quadrangle, California—San Luis Obispo Co.,” 7.5 minute series; 
2. “Lopez Mtn, Quadrangle, California—San Luis Obispo Co.,” 7.5 minute series; 
3. “Pismo Beach Quadrangle, California—San Luis Obispo Co.,” 7.5 minute series; and 
4. “Arroyo Grande NE Quadrangle, California—San Luis Obispo Co.”, 7.5 minute series.

## Boundary [src]

(1) From the beginning point, the boundary runs southwesterly along San Luis Obispo Creek to a point .7 mile southerly of the confluence with Davenport Creek; 
(2) Thence due east to the intersection with the 400-foot contour line of the northeastern flank of the San Luis Range; 
(3) Thence in a generally easterly and then a southeasterly direction along this 400-foot contour line of the northeastern flank of the San Luis Range, which forms the southwestern rim of Edna Valley, to the township line identified as “T31S/T32S” on the U.S.G.S. map; 
(4) Thence east along township line “T31S/T32S”, across Price Canyon to Tiber; 
(5) Thence in a generally easterly direction along the 400-foot contour line of Tiber Canyon and the southern rim of Canada Verde, crossing Corbit Canyon Road and continuing along the 400-foot contour line to longitude line 120°32 
(6) Thence north along longitude line 120°32  to the 600-foot contour line of the southwestern flank of the Santa Lucia Mountain Range; 
(7) Thence in a generally northwesterly direction along the 600-foot contour line of the southwestern flank of the Santa Lucia Range to Cuesta Canyon County Park, the beginning point.

**Comment by SoominHur** [comment]
Continue Reviewing
- (5) It is unclear when to "[cross] Corbit Canyon Road." Therefore, crossed the Corbit Canyon Road right before the direction of 400' contour line changes, from easterly to westerly.
