### ISSUE TITLE
el_dorado

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#69]
# AVA: El Dorado (el_dorado)

name | value
--- | ---
ava_id | el_dorado
cfr_index | 9.61
revision | [T.D. ATF-152, 48 FR 46520, Oct. 13, 1983, as amended by T.D. ATF-254, 52 FR 23651, June 24, 1987]
state | CA
county | El Dorado
within | Sierra Foothills
contains | Fair Play

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Pilot Hill, California,” 1954 
photorevised 1973.; 
2. “Auburn, California,” 1953 
photorevised 1973.; 
3. “Greenwood, California,” 1949 
photorevised 1973.; 
4. “Georgetown, California,” 1949 
photorevised 1973.; 
5. “Foresthill, California,” 1949 
photorevised 1973.; 
6. “Michigan Bluff, California,” 1952 
photorevised 1973.; 
7. “Tunnel Hill, California,” 1950 
photorevised 1973.; 
8. “Slate Mountain, California,” 1950 
photorevised 1973.; 
9. “Pollock Pines, California,” 1950 
photorevised 1973.; 
10. “Stump Spring, California,” 1951 
photorevised 1973.; 
11. “Caldor, California,” 1951 
photorevised 1973.; 
12. “Omo Ranch, California,” 1952 
photorevised 1973.; 
13. “Aukum, California,” 1952 
photorevised 1973.; 
14. “Fiddletown, California,” 1949; 
15. “Latrobe, California,” 1949 
photorevised 1973.; 
16. “Shingle Springs, California,” 1949; 
17. “Coloma, California,” 1949 
photorevised 1973.; 
18. “Garden Valley, California,” 1949 
photorevised 1973.; 
19. “Placerville, California,” 1949 
photorevised 1973.; 
20. “Camino, California,” 1952 
photorevised 1973.; 
21. “Sly Park, California,” 1952 
photorevised 1973.;

## Boundary [src]

(1) The beginning point of the boundaries is the intersection of the North Fork of the American River 
(also the boundary line between El Dorado and Placer Counties) and the township line “T. 11 N./T. 12 N.” 
(“Pilot Hill” Quadrangle); 
(2) Thence northeast along the North Fork of the American River to its divergence with the Middle Fork of the American River, continuing then, following the Middle Fork of the American River to its intersection with the Rubicon River which continues as the boundary line between El Dorado and Placer Counties 
(“Auburn,” “Greenwood,” “Georgetown,” “Foresthill,” and “Michigan Bluff” Quadrangles); 
(3) Thence southeast along the Rubicon River to its intersection with the range line “R. 11 E./R. 12 E.” 
(“Tunnel Hill” Quadrangle); 
(4) Thence south along the range line through T. 13 N. and T. 12 N., to its intersection with the township line “T. 12 N./T. 11 N.” 
(“Tunnel Hill” and “Slate Mountain” Quadrangles); 
(5) Thence east along the range line to its intersection with the range line “R. 12 E./R. 13 E.” 
(“Slate Mountains” and “Pollock Pines” Quadrangles); 
(6) Thence south along the range line to its intersection with the township line “T. 11 N./T. 10 N.” 
(“Pollock Pines” Quadrangle); 
(7) Thence east along the township line to its intersection with the range line “R. 13 E./R. 14 E.” 
(“Pollock Pines” and “Stump Spring” Quadrangles); 
(8) Thence south along the range line through T. 10 N., T. 9 N., and T. 8 N. to its intersection with the South Fork of the Cosumnes River 
(also the boundary line between El Dorado and Amador Counties) 
(“Stump Spring” and “Caldor” Quadrangles); 
(9) Thence west and northwest along the South Fork of the Cosumnes River to its intersection with range line “R. 11 E./R. 10 E.” 
(“Caldor,” “Omo Ranch,” “Aukum,” and “Fiddletown” Quadrangles); 
(10) Thence north along the range line to its intersection with the township line “T. 8 N./T. 9 N.” 
(“Fiddletown” Quadrangle); 
(11) Thence west along the township line to its intersection with range line “R. 10 E./R. 9 E.” 
(“Fiddletown” and “Latrobe” Quadrangles); 
(12) Thence north along the range line to its intersection with U.S. Route 50; 
(13) Thence west along U.S. Route 50 to its intersection with Cameron Park Drive; 
(14) Thence north along Cameron Park Drive to its intersection with Green Valley Road; 
(15) Thence east along Green Valley Road to its intersection with range line R.10 E/ R.9 E; 
(16) Thence north along the range line to its intersection with the township line T.10 N./ T.11 N; 
(17) Thence east along the township line approximately 4,000 feet to its intersection with the range line “R. 9 E./R. 10 E.” 
(“Coloma” Quadrangle); 
(18) Thence north on the range line to its intersection with the township line “T. 11 N./T. 12 N.” 
(“Coloma” Quadrangle); and 
(19) Thence west along the township line to the point of beginning 
(“Coloma” and “Pilot Hill” Quadrangles).

**Comment by ariellerose** [comment]
I am working on this one.

**Comment by ariellerose** [comment]
Need help: I am already following north on the range line 9 and 10, when it intersects in step 16 I am still on the range line 9 and 10 so step 17 doesn't make sense.
(15) Thence east along Green Valley Road to its **intersection with range line R.10 E/ R.9 E**;
(16) Thence **north along the range line** to its intersection with the township line T.10 N./ T.11 N;
(17) Thence **_east along the township line_** approximately 4,000 feet to its **intersection with the range line “R. 9 E./R. 10 E.**”
(“Coloma” Quadrangle);

**Comment by MicheleTobias** [comment]
Yes, you are correct that these instructions don't make a lot of sense.  It's pretty typical that an AVA description has something like this.  Does it make sense to go to the next range line to the east?  Maybe that's what they meant.  If the instructions make sense after this point substituting in the next range line, go with that.  Another option is to skip ahead and digitize the next points that make sense.  Sometimes this can help you figure out what they meant to say.

**Comment by SoominHur** [comment]
Reviewed.
- Filled in cfr author name in the attribute table.
- Filled in petitioner name in the attribute table.
- Add scale information of the used maps in the attribute table.
- Could not find the approved map #14 “Fiddletown, CA, 1949, scale 1:24000" on the usgs topo view website. Instead, used “Fiddletown, CA, 1949, photoinspected 1973, scale 1:24000" for review.
