### ISSUE TITLE
elkton_oregon

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#70]
# AVA: Elkton Oregon (elkton_oregon)

name | value
--- | ---
ava_id | elkton_oregon
cfr_index | 9.229
revision | [T.D. TTB-111, 78 FR 8018, Feb. 5, 2013]
state | OR
county | Douglas
within | Southern Oregon\|Umpqua Valley
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

(1) Kellogg Quadrangle, Oregon-Douglas Co., Provisional Edition 1990;

(2) Old Blue Quadrangle, Oregon-Douglas Co., Provisional Edition 1990;

(3) Devils Graveyard Quadrangle, Oregon-Douglas Co., Provisional Edition 1990;

(4) Elkton Quadrangle, Oregon-Douglas Co., Provisional Edition 1990; and

(5) Yellow Butte, Oregon-Douglas Co., Provisional Edition 1987.

## Boundary [src]
(c) Boundary. The Elkton Oregon viticultural area is located in Douglas County, Oregon. The boundary of the Elkton Oregon viticultural area is described as follows:

(1) The beginning point is on the Kellogg map at the intersection of the T23S/T24S and R7W/R8W common lines. From the beginning point, proceed northwest in a straight line, crossing onto the Old Blue map, to the eastern-most intersection of the T22S/T23S and R8W/R9W common lines; then

(2) Proceed north along the R8W/R9W common line onto the Devils Graveyard map, across the Umpqua River, to the intersection of the R8W/R9W common line with the 1,000-foot elevation line along the western boundary of section 30, T21S/R8W; then

(3) Proceed generally east along the meandering 1,000-elevation line, crossing over Patterson Creek, Weatherly Creek headwaters, Cedar Creek, and House Creek; continue following the 1,000-foot elevation line onto the Elkton map, back to the Devils Graveyard map, returning to the Elkton map, and then continuing generally east and southeast across Paradise Creek and Little Tom Folley Creek, to the intersection of the 1,000-foot elevation line with an unnamed, improved road in the southeast quadrant of section 4, T22S/R7W; then

(4) Proceed south-southwest along the unnamed, improved road to the intersection of that road with an unimproved logging road, approximately 1.65 miles due north of the Mile 5 marker on Elk Creek, section 9, T22S/R7W; then

(5) Proceed southeast in a straight line, passing through the southeast corner of section 9, T22S/R7W, to Elk Creek, section 15, T22S/R7W; then

(6) Proceed generally southeast (downstream) along Elk Creek to the State Route 38 bridge at BM 172, section 15, T22S/R7W; then

(7) Proceed south in a straight line to the intersection of the 1,000-foot elevation line and the section 22 south boundary line, T22S/R7W; then

(8) Proceed generally south, west, and then north along the meandering 1,000-foot elevation line, crossing first onto the Kellogg map, then crossing back and forth between the Kellogg map and the Yellow Butte map, returning to the Yellow Butte map to the intersection of the 1,000-foot elevation line with the R7W/R6W common line on Bell Ridge, along the section 1 east boundary line, T23S/R7W; then

(9) Proceed southeast in a straight line to the intersection of the line with the 1,000-foot elevation line and an unnamed, unimproved road, section 7, T23S/R6W; then

(10) Proceed south and west along the meandering 1,000-foot elevation, crossing back and forth between the Kellogg and Yellow Butte maps, and finally returning to the Kellogg map, to the intersection of the 1,000-foot elevation line with the T23S/T24S common line along the section 3 north boundary line, T24S/R7W; and then

(11) Proceed west along the T23S/T24S common line to the beginning point.

**Comment by MicheleTobias** [comment]
The boundary of this AVA needs to be adjusted to match with Umpqua Valley.

**Comment by alisonsnwong** [comment]
Checked! Made edits on steps 4 & 5 as per the boundary description.
