### ISSUE TITLE
el_pomar_district

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#71]
# AVA: El Pomar District (el_pomar_district)

name | value
--- | ---
ava_id | el_pomar_district
cfr_index | 9.240
revision | [T.D. TTB-125, 79 FR 60961, Oct. 9, 2014]
state | CA
county | San Luis Obispo
within | Central Coast\|Paso Robles
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Templeton, Calif., 1948, photorevised 1979; and 
2. Creston, Calif., 1948, photorevised 1980.

## Boundary [src]

(1) The beginning point is on the southeastern portion of the Templeton map at the intersection of State Route 41 and an unnamed light-duty road locally known as Homestead Road, east-northeast of Atascadero within the Asuncion Land Grant. From the beginning point, proceed north-northwesterly on Homestead Road approximately 1.1 miles to the road&#39;s intersection with an unnamed light-duty road locally known as South El Pomar Road, Asuncion Land Grant; then 
(2) Proceed north-northwesterly in a straight line approximately 0.8 mile to the 1,452-foot elevation point, and continue north-northwesterly in a straight line approximately 0.3 mile to an unnamed peak above the 1,440-foot elevation line 
(marked on the map by a triangle), Asuncion Land Grant; then 
(3) Proceed northeasterly in a straight line approximately 0.3 mile to the 1,344-foot elevation point, Asuncion Land Grant; then 
(4) Proceed northerly in a series of straight lines, totaling approximately 1.4 miles, through the 1,338-foot and 1,329-foot elevation points to the intersection of two unnamed light-duty roads locally known as El Pomar Drive and Hollyhock Lane in the Santa Ysabel Land Grant, T27S/R12E; then 
(5) Proceed north-northwesterly on Hollyhock Lane approximately 1 mile to the road&#39;s intersection with an unnamed light-duty road locally known as Neal Springs Road, Santa Ysabel Land Grant; then 
(6) Proceed west on Neal Springs Road approximately 0.4 mile to the road&#39;s intersection with an unnamed light-duty road locally known as South River Road, Santa Ysabel Land Grant; then 
(7) Proceed northwesterly and then northerly on South River Road approximately 2.8 miles to the road&#39;s intersection with an unnamed light-duty road locally known as Charolais Road 
(0.1 mile north of a marked windmill), Santa Ysabel Land Grant; then 
(8) Proceed east-southeasterly on Charolais Road approximately 1.4 miles to the road&#39;s intersection with an unnamed light-duty road locally known as Creston Road, Santa Ysabel Land Grant; then 
(9) Proceed north and then west-northwesterly on Creston Road approximately 1.9 miles to the road&#39;s intersection with a marked telephone line 
(approximately 1.3 miles due east of U.S. Route 101) in the Santa Ysabel Land Grant, T26/R12E; then 
(10) Proceed easterly in a straight line approximately 2 miles, crossing onto the Creston map, to the line&#39;s intersection with the point where the R12E/R13E common boundary line crosses Huerhuero Creek, western boundary line of section 31, T26S/R13E; then 
(11) Proceed southeasterly 
(upstream) along Huerhuero Creek approximately 2.4 miles to the creek&#39;s first confluence with an unnamed intermittent stream in the northwest quadrant of section 8, T27S/R13E; then 
(12) Proceed southeasterly in a straight line approximately 1.4 miles to the 1,255-foot elevation point in the northwest quadrant of section 16, T27S/R13E; then 
(13) Proceed easterly in a straight line approximately 0.75 mile to an unnamed peak above the 1,380-foot elevation line 
(marked on the map with a triangle), section 16, T27S/R13E; then 
(14) Proceed east-southeasterly in a straight line approximately 0.6 mile to the 1,342-foot elevation point in section 15, T27S/R13E, and then continue east-southeasterly in a straight line approximately 0.6 mile to the northern end of a marked, unnamed light-duty road 
(locally known as a private driveway located approximately 430 feet east of Old Ford Road), section 15, T27S/R13E; then 
(15) Proceed south on the marked, unnamed light-duty road 
(locally known as a private driveway located approximately 430 feet east of Old Ford Road) approximately 0.3 mile to the road&#39;s intersection with an unnamed light-duty road locally known as Creston Road, section 15, T27S/R13E; then 
(16) Proceed east on Creston Road approximately 0.2 mile to the road&#39;s intersection with northeast corner of section 22, T27S/R13E; then 
(17) Proceed southerly in a straight line approximately 1.2 miles to the 1,142 elevation point in the Huerhuero Land Grant 
(0.1 mile south of a pipe line), T27S/R13E; then 
(18) Proceed southwesterly in a straight line approximately 0.75 mile to BM 1052 located at the intersection of two unnamed light-duty roads locally known locally as El Pomar Drive and Cripple Creek Road, section 27, T27S/R13E; then 
(19) Proceed south on Cripple Creek Road approximately 1.0 mile to the road&#39;s eastern-most intersection with State Route 41, section 34, T27S/R13E; then 
(20) Proceed southwesterly on State Route 41 approximately 0.5 mile to the marked 1,128-foot elevation point, section 3, T28S/R13E; then 
(21) Proceed south-southwesterly in a straight line approximately 1.1 miles to the southeast corner of section 4, T28S/R13E; then 
(22) Proceed east along the southern boundary of section 4 approximately 0.75 mile to the section line&#39;s intersection with State Route 41; then 
(23) Proceed southwesterly on State Route 41 approximately 4.5 miles, crossing onto the Templeton map and returning to the beginning point.

**Comment by SoominHur** [comment]
Reviewed.
- Add scale information of used maps
- (14) - (16) There are two marked, unnamed light-duty road in section 15 (T27S/R13E); one is straight and the other is curved. The description is unclear which one to proceed along. It seems more reasonable to follow straight road according to the distance descriptions; (14) "east-southeasterly in a straight line approximately 0.6 mile," (16) "approximately 0.2 mile to the road's intersection with northeast corner of section 22, T27S/R13E" However, the name of straight road is Old Ford Road according to the google map. And the marked, unnamed light-duty road must not Old Ford Road because of descriptions in (14) & (15); "locally known as a private driveway located approximately 430 feet east of Old Ford Road" Therefore, I decided to proceed along curved road next to straight (Old Ford) road.
