### ISSUE TITLE
Eola-Amity Hills still need to be updated

### ISSUE THREAD

**Issue by kurtishouser** [UCDavisLibrary/ava#714]
Current: `[T.D. TTB-51, 71 FR 40404, July 17, 2006]`
Updated: `[T.D. TTB-51, 71 FR 40404, July 17, 2006; T.D. TTB-155, 83 FR 64279, Dec. 14, 2018]`

**Comment by MicheleTobias** [comment]
I moved this information over to Eola-Amity Hills' history issue #650 so we can handle it there the next time someone is working with it.
