### ISSUE TITLE
eola_amity_hills

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#72]
# AVA: Eola-Amity Hills (eola_amity_hills)

name | value
--- | ---
ava_id | eola_amity_hills
cfr_index | 9.202
revision | [T.D. TTB-51, 71 FR 40404, July 17, 2006]
state | OR
county | Polk|Yamhill
within | Willamette Valley
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Rickreall, Oregon, 1969, photorevised 1976; 
2. Salem West, Oregon, 1969, photorevised 1986; 
3. Mission Bottom, Oregon, 1957, revised 1993; 
4. Dayton, Oregon, 1957, revised 1992; 
5. McMinnville, Oregon, 1957, revised 1992; and 
6. Amity, Oregon, 1957, revised 1993.

## Boundary [src]

(1) The beginning point is on the Rickreall, Oregon, map, at the intersection of State Highways 22 and 223; 
(2) From the beginning point, proceed east on State Highway 22 to its intersection with Doaks Ferry Road on the Salem West, Oregon, map; then 
(3) Proceed northeast on Doaks Ferry Road to its intersection with the 200-foot contour line southeast of Gibson Gulch, in section 65; then 
(4) Follow the 200-foot contour line in a westerly loop until it rejoins Doaks Ferry Road; then 
(5) Continue north on Doaks Ferry Road to its intersection with State Highway 221; then 
(6) Continue north on State Highway 221 to its intersection with the 200-foot contour line at the point where the contour line departs from Highway 221 and runs southwest along the southern edge of Spring Valley 
(section 53 on the Mission Bottom, Oregon, map); then 
(7) Follow the 200-foot contour line first south onto the Salem West, Oregon, map, then northwest around the southern and western edge of Spring Valley and back on to the Mission Bottom, Oregon, map; then 
(8) Continue to follow the 200-foot contour line generally north on the Mission Bottom, Oregon, map, crossing onto and back from the Amity, Oregon, map and continue past the Yamhill County line and onto the Dayton, Oregon, map; then 
(9) Follow the 200-foot contour line from the Dayton, Oregon, map onto the McMinnville, Oregon, map and back to the Dayton, Oregon, map and continue around the northeast edge of the Amity Hills spur of the Eola Hills; then 
(10) Follow the 200-foot contour line onto the McMinnville, Oregon, map as it continues around the northern and western periphery of the Amity Hills spur; then 
(11) Follow the 200-foot contour line onto the Amity, Oregon, map as it heads first south, then generally southeast, then generally south, along the western edge of the Eola Hills until it intersects Old Bethel Road at a point just north of the Polk County line; then 
(12) Follow Old Bethel Road, which becomes Oak Grove Road, south until it intersects with the 200-foot contour line just northwest of the township of Bethel; then 
(13) Follow the 200-foot contour line around in a southeasterly loop until it again intersects Oak Grove Road where Oak Grove and Zena Roads intersect; then 
(14) Follow Oak Grove Road south until it intersects with Frizzell Road; then 
(15) Follow Frizzell Road west for three-tenths mile until it intersects with the 200-foot contour line; then 
(16) Follow the 200-foot contour line generally south until it intersects with the beginning point.

**Comment by gdmf** [comment]
Please add the "In Progress" label to this one.

**Comment by alisonsnwong** [comment]
Checked!
