### ISSUE TITLE
VI_avas still in avas_by_state

### ISSUE THREAD

**Issue by elistockwell** [UCDavisLibrary/ava#723]
I believe this folder was created by a typo in one of the Virginia (VA) AVAs.  That AVA has been fixed, so there is no longer anything in this folder, but for some reason the folder remains.  I'll see if I can figure out why by looking at the script that creates avas_by_state.

**Comment by MicheleTobias** [comment]
I believe I took it out of the script, but that's a good place to start.

**Comment by MicheleTobias** [comment]
So it's not coming from the state script code. I removed the VI files from the repo. I think people need to be careful to update their forks so it doesn't come back.  I'll watch for it in PRs too.
