### ISSUE TITLE
escondido_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#73]
# AVA: Escondido Valley (escondido_valley)

name | value
--- | ---
ava_id | escondido_valley
cfr_index | 9.141
revision | [ATF-322, 57 FR 20761, May 15, 1992]
state | TX
county | Pecos
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]
Approved map. The appropriate map for determining the boundaries of the “Escondido Valley” viticultural area is 1 U.S.G.S. (scale 1:250,000) map. It is titled Fort Stockton, Texas, 1954 (revised 1973).

## Boundary [src]

(1) The beginning point is the intersection of Interstate Route 10 
(I-10) and an intermittent stream approximately 18 miles east of the city of Fort Stockton 
(standard reference GE3317 on the Fort Stockton, Texas, U.S.G.S. map); 
(2) From the beginning point, the boundary follows I-10 in an easterly direction approximately 9 miles until a southbound trail diverges from I-10 just past the point where it intersects horizontal grid line 2 of square GE on the Fort Stockton, Texas, U.S.G.S. map; 
(3) The boundary then follows the trail in a generally southeasterly direction about 5 miles until it intersects the 3000 foot contour line; 
(4) The boundary follows the 3000 foot contour line in a generally westerly direction approximately 17 miles; 
(5) The boundary continues to follow the 3000 foot contour line as it turns sharply northwest, but diverges from the contour line when the contour line turns south again; 
(6) From the point where it diverges from the contour line, the boundary follows a straight north-northwesterly line as it returns to the beginning point at I-10.

**Comment by SoominHur** [comment]
Start working on this

**Comment by alisonsnwong** [comment]
Checked!
