### ISSUE TITLE
Approved Maps on USGS Store

### ISSUE THREAD

**Issue by elistockwell** [UCDavisLibrary/ava#733]
I recently discovered that approved maps from multiple AVAs that aren't on topoview are available for free download at the USGS store: https://store.usgs.gov/filter-products?page=1.  It's possible that all of the approved maps are actually on here.  I added a note to the digitizing instructions for future reference, but we will probably want to go back through all of the AVAs that used different than the approved maps and and update them with the correct maps.

**Comment by MicheleTobias** [comment]
I added this to the list of resources for the documentation so I'm going to close this issue now.
