### ISSUE TITLE
Add Historical Boundary Notes to Quality Control Procedures

### ISSUE THREAD

**Issue by elistockwell** [UCDavisLibrary/ava#736]
I just reached a historical boundary in my quality control and realized that the documentation hasn't been updated to include these and a new contributor might be confused if they start off with quality control for one of these AVAs.  Just making a note so we won't forget when we update the documentation.

**Comment by MicheleTobias** [comment]
I know we talked about this issue. @elistockwell did you end up writing this up? I think this issue might be complete.

**Comment by elistockwell** [comment]
Yes, it is! Closing now.
