### ISSUE TITLE
Overlap in Quality Control Issues

### ISSUE THREAD

**Issue by elistockwell** [UCDavisLibrary/ava#739]
It looks like AVAs that span multiple states show up in the QC issues for each state.  This is ok for me to keep track of when I'm the only one doing QC, and it's probably a good idea to check the big ones a couple times anyways, but it could cause problems if we get more contributors.  For now I could make a list of AVAs present in closed QC issues and then manually remove them from the open ones, unless anyone has a better idea?

**Comment by MicheleTobias** [comment]
There is a checkbox list on all of the QC issues. You could just search for the big ones and check them off. I know that's manual work, but I think it won't be too bad.

**Comment by elistockwell** [comment]
I removed all of the AVAs that I've already checked or am in progress checking in other issues, going to hold off on removing all the redundancies until I see more contributors working on QC.
