### ISSUE TITLE
fair_play

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#74]
# AVA: Fair Play (fair_play)

name | value
--- | ---
ava_id | fair_play
cfr_index | 9.168
revision | [T.D. ATF-440, 66 FR 11539, Feb. 26, 2001, as amended by T.D. TTB-126, 80 FR 402, Jan. 6, 2015]
state | CA
county | El Dorado
within | El Dorado\|Sierra Foothills
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Aukum, Calif., 1952 
photorevised 1973.; 
2. Camino, CA, 1952 
photorevised 1973.; 
3. Sly Park, CA, 1952 
photorevised 1973.; and 
4. Omo Ranch, Calif., 1952 
photorevised 1973..

## Boundary [src]

(1) The beginning point of the boundary is the intersection of the Middle Fork of the Cosumnes River and the U.S.G.S. map section line between Sections 26 and 27, T. 9 N., R. 11 E. 
(“Aukum” Quadrangle); 
(2) From the beginning point, the boundary follows northeast along the Middle Fork of the Cosumnes River until it meets an unnamed medium-duty road 
(Mt. Aukum Road or El Dorado County Road E-16) just as it crosses onto the “Camino” Quadrangle map; 
(3) The boundary continues then northeast along Mt. Aukum Road to its intersection with Grizzly Flat Road at the town of Somerset 
(“Camino” Quadrangle); 
(4) The boundary continues east along Grizzly Flat Road to its intersection with the 2,200-foot contour line 
(“Camino Quadrangle”); 
(5) The boundary continues northeasterly and then easterly along the 2,200-foot contour line until the contour line intersects with Jackass Canyon Creek near the eastern boundary of Section 10, T. 9 N., R. 12. E., on the “Camino Quadrangle” map; 
(6) The boundary then proceeds southeast along Jackass Canyon Creek, crossing over the southwestern corner of the “Sly Park” Quadrangle map and onto the “Omo Ranch” Quadrangle map, to the headwaters of the creek, then proceeds in a straight line southeast to Grizzly Flat Road in Section 24, T. 9 N., R. 12 E.; 
(7) The boundary continues east along Grizzly Flat Road until the road intersects with the range line between R. 12 E. and R. 13 E. 
(“Omo Ranch Quadrangle”); 
(8) The boundary then follows south along the range line between R. 12 E. and R. 13 E. to its intersection with an unnamed medium-duty road in T. 8 N. 
(Omo Ranch Road) 
(“Omo Ranch” Quadrangle); 
(9) The boundary then continues west in a straight line approximately 0.3 miles to the point where Cedar Creek intersects with the 3200-foot contour line, within Section 1, T. 8 N.,R. 12 E. 
(“Omo Ranch” Quadrangle);  
(10) The boundary follows along Cedar Creek west and then southwest until it empties into Scott Creek 
(“Aukum” Quadrangle); 
(11) The boundary then proceeds west along Scott Creek until it empties into the South Fork of the Cosumnes River 
(“Aukum” Quadrangle); 
(12) The boundary continues west along the South Fork of the Cosumnes River to its intersection with the western boundary of Section 14, T. 8 N., R 11 E. 
(“Aukum Quadrangle”); 
(13) The boundary then proceeds north along the western boundary lines of Sections 14, 11, and 2, T. 8 N., R 11 E., and then the western boundary lines of Sections 35 and 26, T. 9 N., R 11 E., to return to the beginning point 
(“Aukum Quadrangle”).

**Comment by fyfangyao** [comment]
I am working on this.

**Comment by fyfangyao** [comment]
I use “Aukum Quad, Cali., 7.5 minute series, 1952, revised 1977,“ “Sly Park Quad, Cali., 7.5 minute series, 1952, revised 1972,” and “Omg Ranch Quad, Cali., 7.5 minute series, 1952, revised 1974.”

**Comment by SoominHur** [comment]
Reviewed.
- Edit cfr author name
- Could find maps that have same map years and photorevised years with the approved maps. So used following maps for reviewing/editing; (1) "Aukum, CA" 1952, photorevised 1973 (1977 ed.), Scale 1:24000; (2) "Camino, CA" 1952, photorevised 1973 (1977 ed.), Scale 1:24000; (3) "Sly Park, CA" 1952, photorevised 1973 (1975 ed.), Scale 1:24000; and (4) "Omo Ranch, CA" 1952, photorevised 1973 (1975 ed.), Scale 1:24000.
