### ISSUE TITLE
fennville

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#75]
# AVA: Fennville (fennville)

name | value
--- | ---
ava_id | fennville
cfr_index | 9.33
revision | [T.D. ATF-91, 46 FR 46320, Sept. 18, 1981]
state | MI
county | Allegan
within | Lake Michigan Shore
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Fennville Quadrangle, Michigan-Allegan County,” 15 minute series; 
2. “Bangor Quadrangle, Michigan,” 15 minute series; and 
3. “South Haven Quadrangle, Michigan,” 15 minute series.

## Boundary [src]

(1) The western boundary is the eastern shore of Lake Michigan, extending from the Black River, at the City of South Haven, north to the Kalamazoo River. 
(2) The northern boundary is the Kalamazoo River, extending easterly from Lake Michigan to 86°5  west longitude. 
(3) The eastern boundary is the 86°5  west longitude meridian, extending from the Kalamazoo River to the intersection of the Middle Fork of the Black River. 
(4) The southern boundary is the Middle Fork of the Black River extending westerly from 86°5  west longitude until it joins the Black River, continuing west along the Black River to the eastern shore of Lake Michigan.

**Comment by MicheleTobias** [comment]
I'm working on this one.

**Comment by MicheleTobias** [comment]
The document didn't list dates for the  maps, so I used the most current ones TopoView had (~1940s).  All the landmarks were there, so I think this is fine.
