### ISSUE TITLE
palos_verdes_peninsula

### ISSUE THREAD

**Issue by elistockwell** [UCDavisLibrary/ava#750]
New AVA to digitize!
https://www.ecfr.gov/current/title-27/chapter-I/subchapter-A/part-9/subpart-C#9.274

**Comment by elistockwell** [comment]
Working on this now.

**Comment by elistockwell** [comment]
Step 3 of the boundary description was weird on this one, see linked PR for more details.

**Comment by alisonsnwong** [comment]
Checked!

**Comment by alisonsnwong** [comment]
Checked!
