### ISSUE TITLE
fiddletown

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#76]
# AVA: Fiddletown (fiddletown)

name | value
--- | ---
ava_id | fiddletown
cfr_index | 9.81
revision | [T.D. ATF-147, 48 FR 45239, Oct. 4, 1983, as amended by T.D. ATF-249, 52 FR 5959, Feb. 27, 1987]
state | CA
county | Amador
within | Sierra Foothills
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Fiddletown, CA, 1949, 7.5 minute series; 
2. Amador City, CA, 1962, 7.5 minute series; 
3. Pine Grove, CA, 1948 
photoinspected 1973., 7.5 minute series; 
4. Aukum, CA, 1952 
photorevised 1973., 7.5 minute series.

## Boundary [src]

(1) From the beginning point at the north boundary where Fiddletown Shenandoah Road crosses Big Indian Creek in Section 28, Township 8 N, Range 11 E, proceed in a southwesterly direction following Big Indian Creek through the southeast corner of Section 29, crossing the northwest corner of Section 32 to where it meets Section 31; 
(2) Then in a southerly direction follow the Section line between Sections 31 and 32, Township 8 N, Range 11 E, and Sections 5 and 6, 7 and 8, Township 7 N, Range 11 E, to where the Section line meets the South Fork of Dry Creek; 
(3) Then following the South Fork of Dry Creek in an easterly direction crossing the lower portions of Sections 8, 9, 10, 11, 12 and into Township 8 N, Range 12 E, at Section 7 and across Section 7 to where it meets Section 8; 
(4) Then north following the Section line between Sections 7 and 8, 5 and 6 into Township 8 N, Range 12 E, between Sections 31 and 32, to Big Indian Creek; and 
(5) Then following Big Indian Creek in a northwesterly direction through Sections 31, 30, 25, 26 and 27, returning to the point of beginning.

**Comment by fyfangyao** [comment]
I am working on this.

**Comment by fyfangyao** [comment]
I use “Fiddle Quad, Cali., 7.5 minute series, 1949, revised 1985“ and “Amador City Quad, Cali., 7.5 minute series, 1962, revised 1976” because the approved maps don’t specify the revision years. Also, I use “Pine Grove Quad, Cali., 7.5 minute series, 1948, revised 1979”and “Paicines Quad, Cali., 7.5 minute series, 1952, revised 1977” because I cannot find the map with the required revision year.

**Comment by SoominHur** [comment]
Reviewed
