### ISSUE TITLE
finger_lakes

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#77]
# AVA: Finger Lakes (finger_lakes)

name | value
--- | ---
ava_id | finger_lakes
cfr_index | 9.34
revision | [T.D. ATF-113, 47 FR 38518, Sept. 1, 1982, as amended by T.D. ATF-249, 52 FR 5956, Feb. 27, 1987]
state | NY
county | Cayuga|Courtland|Livingston|Monroe|Onondaga|Ontario|Schuyler|Seneca|Steuben|Tompkins|Wayne|Yates
within | 
contains | Cayuga Lake\|Seneca Lake

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Rochester,” Location diagram NK 18-1, 1961; and 
2. “Elmira,” Location diagram NK 18-4, 1968.

## Boundary [src]

(1) Starting at the most northwest point, the intersection of the Erie Canal and the north/south Conrail line south of the City of Rochester. 
(2) Then east along the course of the Erie Canal approximately 56 miles 
(45 miles due east) to the intersection of New York State Highway 89 
(NY-89). 
(3) Then south on NY-89 four miles to the intersection of highway US-20. 
(4) Then east on US-20 for 36 miles to the intersection of interstate 81 
(I-81). 
(5) Then south along I-81 for ten miles to NY-281. 
(6) Then south along NY-281 for 20 miles around the western city limits of Cortland where NY-281 becomes NY-13. 
(7) Then continuing southwest on NY-13 
(through the cities of Dryden and Ithaca) approximately 36 miles to the intersection of NY-224. 
(8) Then due west one mile to the southern boundary of Schuyler County. 
(9) Then continuing west along this county line 20 miles to the community of Meads Creek. 
(10) Then north along the Schuyler-Steuben county line four miles to the major east-west power line. 
(11) Then west along the power line for eight miles to the intersection of NY-17 
(four miles southeast of the community of Bath). 
(12) Then northwest on NY-17 approximately nine miles to the intersection of I-390. 
(13) Then northwest on I-390 for 21 miles to the intersection of NY-36. 
(14) Then north for two miles through the community of Dansville to NY-63. 
(15) Then northwest on NY-63 approximately 18 miles to the intersection of NY-39, just south of Genesco. 
(16) Then north on NY-39 nine miles to the intersection where the west and north/south Conrail lines meet at the community of Avon. 
(17) Then north along the north/south Conrail line for 15 miles to the beginning point at the intersection of the Erie Canal.

**Comment by amgard** [comment]
I'm going to begin working on this AVA. I looked at the maps, and for Elmira 1968, it looks like 1968 map isn't in topoview. What map do you recommend I use instead?

**Comment by MicheleTobias** [comment]
It looks like there's a 1962 (1969 edition).  I would try that one or the 1965 (1965 edition).  Usually when the maps with a specific quad name stop getting updated, nothing much is changing in that area, or they changed the quad name.  I think the 1962 or 1965 should be good.  Just make sure to list what you used in the "used maps" column.

**Comment by ericallanwest** [comment]
The map labeled "1965 (HTMC, 1965 ed.)" says Edit Year: 1968 in the description. But if you look in the bottom right corner of the [actual map](https://ngmdb.usgs.gov/ht-bin/tv_browse.pl?id=70435a37f303edfc1a221a94a17d33a8), there is no indication that it was edited in 1968.

I would recommend "1962 (HTMC, 1969 ed.)" in which the [actual map](https://ngmdb.usgs.gov/ht-bin/tv_browse.pl?id=3175fbba28798f511a16498a5e6c2099) does state Limited Revision 1968 in the bottom right corner.

That said, I have almost completed this boundary, which is why I joined the conversation! If you could label it Virginia Tech, it would be appreciated. No one on our team has experience with GitHub, so we are still figuring things out.

**Comment by MicheleTobias** [comment]
@amgard How far along are you on this boundary?  Would you mind switching?

**Comment by MicheleTobias** [comment]
@ericallanwest I think you've now figured out that we have a process for claiming AVAs to work on so we don't double up on boundaries.  If you have any questions about how we're using GitHub, just let me know.  We have contributors all over the country so we try to stay in communication about what everyone's planning to do.

**Comment by amgard** [comment]
@MicheleTobias Sure thing, I will switch AVA's. @ericallanwest It is all yours to finish up.

**Comment by MicheleTobias** [comment]
@amgard thanks for being flexible!
