### ISSUE TITLE
Test how to embed a wepmap into Jekyll 

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#777]
Try adding a web map into one of the .rmd files to make sure we can use html and javascript in addition to the markdown.

**Comment by MicheleTobias** [comment]
This task will be for Erika once we get her added to the repo.

**Comment by erklopez** [comment]
Embedding a webmap is possible in jekyll using iframe. Previous attempts at adding the map included using the HTML file of a leaflet map and trying to implement it (fails to implement js).

**Comment by erklopez** [comment]
Webmap in progress, issue #779
