### ISSUE TITLE
Create Web Map

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#779]
Create a web map to include in the new documentation. Perhaps we can adapt the [Covid Exposures](https://github.com/datalab-dev/covid_worksite_exposure) html to use the AVAs.

Features to include:

- [x] Popup with limited information - name, year, etc. (not the full description)
- [ ] Nice to have: a timeline slider

**Comment by erklopez** [comment]
Webmap is being made with leaflet, using the geojson for the avas and wrapping it into a json.

**Comment by MicheleTobias** [comment]
Let's increase the detail in the notes here so later we'll remember what happened. What problems are you running into? What examples are you looking at?

I created the `avas.js` file in the new `avas_aggregated_files` folder. That should make it easier to use the avas.geojson data in the leaflet map.

**Comment by erklopez** [comment]
Currently looking at the script used to create the covid worksite exposure map found [here](https://github.com/datalab-dev/covid_worksite_exposure/blob/main/docs/index.html) as well as the leaflet workshop ([here](https://ucdavisdatalab.github.io/workshop_web_maps/build-a-leaflet-web-map.html)) for the general layout of a base map and integration of the js file. Currently looking at this example, which works with a bigger geojson file ([here](https://github.com/iamtekson/Leaflet-Basic/blob/master/vector-tiles/vector_tiles.html))

**Comment by erklopez** [comment]
Success adding the avas geojson after following the official documentation for Leaflet found [here](https://leafletjs.com/SlavaUkraini/reference.html#geojson). Next step will be styling the map to be more readable.

**Comment by erklopez** [comment]
In order to change the style of the map see [here](https://leafletjs.com/SlavaUkraini/reference.html#path-option). To change the base map, see the leaflet providers [here](https://leaflet-extras.github.io/leaflet-providers/preview/)

**Comment by MicheleTobias** [comment]
Make sure you find the license information for any of the basemaps we use. I suspect OSM data is fair game regardless of how it's styled, but let's be sure.

**Comment by erklopez** [comment]
Data about copyright for OpenStreenMaps can be found [here](https://wiki.osmfoundation.org/wiki/Licence/Licence_and_Legal_FAQ). The map that I chose is called Carto, and is a contributor for OSM, so it should be fine.

**Comment by MicheleTobias** [comment]
The data is open, but is the visualization?

**Comment by erklopez** [comment]
For future reference, the popup default option is set for the geojson template on the leaflet documentation like this:
" L.geoJSON(data, {
    style: function (feature) {
        return {color: feature.properties.color};
    }
}).bindPopup(function (layer) {
    return layer.feature.properties.description;
}).addTo(map);
" 
However, if the option to hover the mouse over the popup and have it be open is a desired outcome, the  bindPopup function must be replaced by bindTooltip like this:
"L.geoJSON(avas, {
    style: function (feature) {
        return {color: '#990F02', weight: .75};
    }
}).bindTooltip(function (layer) {
    return "<b>Name: </b>" + layer.feature.properties.name + "<br><b>Date Created: </b>" + layer.feature.properties.created;
}).addTo(map);
"
As an extra note, the <b> will make the name of the property show up in bold, and the description on the first example must be replaced with the correct name of the desired property from the the .js or geojs file.

**Comment by erklopez** [comment]
Jekyll will not find the .js file if iframe is used inside a .md file to embed a map. The git bash console showed me this two error messages " ERROR `/avas_aggregated_files/avas.js'" and " ERROR `/web_map/leaflet-geojson-vt.js'".
   Initially I thought the problem was the second message, but after solving the first message adding a copy of the avas.js file to the web_map folder (where the webmap.html is hosted) the map, which first showed blank, was populated with the data. I speculated that the problem is that markdown cannot reference files in relationship to the files within the HTML file, only in relationship to itself.

**Comment by MicheleTobias** [comment]
I made issue #803 to change where we save the avas.js file. It makes more sense to keep it in the webmap folder since people won't probably want to download that file anyway.
