### ISSUE TITLE
fort_ross_seaview

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#78]
# AVA: Fort Ross-Seaview (fort_ross_seaview)

name | value
--- | ---
ava_id | fort_ross_seaview
cfr_index | 9.221
revision | [T.D. TTB-98, 76 FR 77695, Dec. 14, 2011]
state | CA
county | Sonoma
within | North Coast\|Sonoma Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Arched Rock, California-Sonoma Co., 1977 edition; 
2. Fort Ross, California-Sonoma Co., 1978 edition; 
3. Plantation, California-Sonoma Co., 1977 edition; 
4. Annapolis, California-Sonoma Co., 1977 edition; and 
5. Tombs Creek, California-Sonoma Co., 1978 edition.

## Boundary [src]

(1) The beginning point is on the Arched Rock map at the intersection of the 920-foot elevation line and Meyers Grade Road, T8N, R12W. From the beginning point, proceed northwest on Meyers Grade Road approximately 4.3 miles, on to the Fort Ross map, to the intersection of Meyers Grade Road with Seaview and Fort Ross Roads, T8N, R12W; then 
(2) Proceed northwest on Seaview Road approximately 6.4 miles, on to the Plantation map, to the intersection of Seaview Road with Kruse Ranch and Hauser Bridge Roads in the southeast corner of section 28, T9N, R13W; then 
(3) Proceed west on Kruse Ranch Road approximately 0.2 mile to the intersection of Kruse Ranch Road with the 920-foot elevation line, T9N, R13W; then 
(4) Proceed generally north then east along the 920-foot elevation line approximately 2.2 miles to the intersection of the elevation line with Hauser Bridge Road, section 27, T9N, R13W; then 
(5) Proceed east on Hauser Bridge Road approximately 1.5 miles to the intersection of Hauser Bridge Road with the 920-foot elevation line, section 23, T9N, R13W; then 
(6) Proceed generally northwest then east along the 920-foot elevation line, on to the Annapolis map, approximately 7.8 miles to the intersection of the elevation line with an unnamed, unimproved road that forks to the south from Tin Barn Road, section 8, T9N, R13W; then 
(7) Proceed east then north along the unnamed, unimproved road to the intersection of that road with Tin Barn Road, section 8, T9N, R13W; then 
(8) Proceed east in a straight line approximately 1.55 miles to Haupt Creek, section 10, T9N, R13W; then 
(9) Proceed generally southeast along Haupt Creek approximately 1.2 miles to the western boundary of section 11, T9N, R13W; then 
(10) Proceed straight north along the western boundary of section 11 approximately 0.9 mile to the northwest corner of section 11 
(near Buck Spring), T9N, R13W; then 
(11) Proceed straight east along the northern boundary of section 11 and then along the northern boundary of section 12 approximately 1.1 miles to the intersection of the section 12 northern boundary with an unnamed, unimproved road along Skyline Ridge, section 12, T9N, R13W; 
(12) Proceed generally southeast along the unnamed, unimproved road, on to the Tombs Creek map, approximately 1.3 miles to the intersection of that road with the 1,200-foot elevation line, section 13, T9N, R13W; then 
(13) Proceed generally southeast along the 1,200-foot elevation line approximately 0.6 mile to the intersection of that elevation line with Allen Creek, section 18, T9N, R12W; then 
(14) Proceed generally north along Allen Creek approximately 0.2 mile to the intersection of Allen Creek with the 920-foot elevation line, section 18, T9N, R12W; then 
(15) Proceed generally east and then southeast along the meandering 920-foot elevation line, on to the Fort Ross map, to the intersection of that elevation line with Jim Creek, section 21, T9N, R12W; then 
(16) Proceed generally southeast along Jim Creek approximately 0.7 mile to the northern boundary of section 27, T9N, R12W; then 
(17) Proceed east along the northern boundary of section 27, T9N, R12W, to the northeast corner of section 27; then 
(18) Proceed south along the eastern boundaries of sections 27 and 34, T9N, R12W, and continue south along the eastern boundaries of sections 3, 10, 15, and 22, T8N, R12W, to Fort Ross Road; then 
(19) Proceed east along Fort Ross Road to the intersection of Fort Ross Road with the Middle Branch of Russian Gulch Creek, and then proceed south along that creek for approximately 1.2 miles to the intersection of that creek with the 920-foot elevation line, section 26, T8N, R12W; then 
(20) Proceed generally south along the meandering 920-foot elevation line approximately 8.1 miles, passing back and forth on the Fort Ross and Arched Rock maps as the 920-foot elevation line meanders north then south around the West Branch of Russian Gulch, returning to the beginning point, T8N, R12W.

**Comment by SoominHur** [comment]
- Edit cfr author name in the attribute table
- Add edition years of used maps in the attribute table; 
(1) "Arched Rock, CA" (Topographic) 1977 (1978 ed.), Scale 1:24000;
(2) "Fort Ross, CA" (Topographic) 1978 (1978 ed.), Scale 1:24000;
(3) "Plantation, CA" (Topographic) 1977 (1978 ed.), Scale 1:24000;
(4) "Annapolis, CA" (Topographic) 1977 (1978 ed.), Scale 1:24000; and 
(5) "Tombs Creek, CA" (Topographic) 1978, Scale 1:24000.
