### ISSUE TITLE
fountaingrove_district

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#79]
# AVA: Fountaingrove District (fountaingrove_district)

name | value
--- | ---
ava_id | fountaingrove_district
cfr_index | 9.250
revision | [T.D. TTB-128, 80 FR 8531, Feb. 18, 2015]
state | CA
county | Sonoma
within | North Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Mark West Springs, CA; 1993; 
2. Calistoga, CA; 1997; 
3. Kenwood, CA; 1954; photorevised 1980; and 
4. Santa Rosa, CA; 1994.

## Boundary [src]

(1) The beginning point is on the Mark West Springs map at the intersection of the shared Sonoma-Napa County line with Petrified Forest Road, section 3, T8N/R7W. 
(2) From the beginning point, proceed southeasterly along the Sonoma-Napa County line, crossing onto the Calistoga map and then the Kenwood map, to the marked 2,530-peak of an unnamed mountain, section 9, T7N/R6W; then 
(3) Proceed west-southwest in a straight line to the marked 2,730-foot summit of Mt. Hood, section 8, T7N/R6W; then 
(4) Proceed west-northwest in a straight line to the marked 1,542-foot summit of Buzzard Peak, section 11, T7N/R7W; then 
(5) Proceed west-southwest in a straight line, crossing onto the Santa Rosa map, to the intersection of State Highway 12 and Los Alamos Road; then 
(6) Proceed due north in a straight line to the southern boundary of section 9, T7N/R7W; then 
(7) Proceed west-northwest along the southern boundaries of sections 9, 4, and 5, T7N/R7W, to the western boundary of the Los Guilicos Land Grant; then 
(8) Proceed west-southwest along the southern boundaries of sections 5, 6, and 7, T7N/R7W; then continue west-southwest along the southern boundaries of sections 12 and 11, T7N/R8W, to the point where the section 11 boundary becomes concurrent with an unnamed light-duty road known locally as Lewis Road; and then continue west-southwest along Lewis Road to the road&#39;s intersection with Mendocino Avenue in Santa Rosa; then 
(9) Proceed north-northwesterly along Mendocino Avenue to the road&#39;s intersection with an unnamed road known locally as Bicentennial Way; then 
(10) Proceed north in a straight line, crossing through the marked 906-foot elevation peak in section 35, T8N/R8W, and, crossing on to the Mark West Springs map, continue to the line&#39;s intersection with Mark West Springs Road, section 26, T8N/R8W; then 
(11) Proceed northerly along Mark West Springs Road, which turns easterly and becomes Porter Creek Road, to the road&#39;s intersection with Franz Valley Road, section 12, T8N/R8W; then 
(12) Proceed northeasterly along Franz Valley Road to the western boundary of section 6, T8N/R7W; then 
(13) Proceed south along the western boundary of section 6, T8N/R7W, to the southwest corner of section 6; then 
(14) Proceed east, then east-northeast along the southern boundaries of sections 6, 5, and 4, T8N/R7W, to the southeast corner of section 4; then 
(15) Proceed north along the eastern boundary of section 4, T8N/R7W, to the Sonoma-Napa County line; then 
(16) Proceed easterly along the Sonoma-Napa County line to the beginning point.

**Comment by SoominHur** [comment]
Reviewed.
- Edit created date in the attribute table. 
- Referenced Google Maps and moved a node at the intersection with Mendocino Avenue and De Vera Way to the intersection with Mendocino Avenue and (9) "an unnamed road known locally as Bicentennial Way."
