### ISSUE TITLE
404 Error for Documentation Website

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#792]
Our github pages site with the documentation is throwing a 404 error. The theme we used moved the repo to a different account so we need to update the _config.yml file with the new path.

See: https://github.com/just-the-docs/just-the-docs/issues/780

**Comment by MicheleTobias** [comment]
For building locally, you may also need to update your gem file. See the linked issue above for more details about that.

**Comment by erklopez** [comment]
Currently fixed. If the local building fails, run "Jekyll clean" and try again.
