### ISSUE TITLE
fredericksburg_in_the_texas_hill_country

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#80]
# AVA: Fredericksburg in the Texas Hill Country (fredericksburg_in_the_texas_hill_country)

name | value
--- | ---
ava_id | fredericksburg_in_the_texas_hill_country
cfr_index | 9.125
revision | [T.D. ATF-279, 53 FR 51541, Dec. 22, 1988]
state | TX
county | Gillespie
within | Texas Hill Country
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Stonewall Quadrangle 
1961.; 
2. Cain City Quadrangle 
1963.; 
3. Fredericksburg East Quadrangle 
1967, photorevised 1982.; 
4. Cave Creek School Quadrangle 
1961.; 
5. Fredericksburg West Quadrangle 
1967, photorevised 1982.; and 
6. Lady Bird Johnson Park Quadrangle 
1964, photoinspected 1979..

## Boundary [src]

(1) From the beginning point, the boundary proceeds on Jung Road in a northwesterly direction across the Pedernales River. 
(2) Then northwesterly approximately 1 mile along Jung Road as it parallels the Pedernales River. 
(3) Then north along Jung Road approximately 3.9 miles to a point where Jung Road meets a medium-duty road known locally as Texas Ranch Road 2721. 
(4) Then westerly approximately .1 mile on Texas Ranch Road 2721 to a point where it meets a medium-duty road known locally as Texas Ranch Road 1631. 
(5) Then northeasterly along Texas Ranch Road 1631 approximately 1 mile to a point where Texas Ranch Road 1631 crosses the 1,800 foot contour line. 
(6) Then northwesterly in a meandering manner along the 1,800-foot contour line to the point where the 1,800-foot contour line crosses State Route 16. 
(7) Then in a generally westerly direction along the 1,800-foot contour line to the point where the 1,800-foot contour line crosses State Route 965. 
(8) Then in a northwesterly and then generally a southeasterly direction along the 1,800-foot contour line to a point where the 1,800-foot contour line goes just south of the Kordzik Hills approximately 1 mile due east of the city of Fredericksburg. 
(9) Then continuing on the 1,800-foot contour line in a generally northwesterly, southerly, and again northwesterly direction to the point where the 1,800-foot contour line crosses Loudon Road approximately 4 miles northwest of Fredericksburg. 
(10) Then continuing on the 1,800-foot contour line in a northwesterly, then generally a southeasterly, westerly and finally a southerly direction to a point where the 1,800-foot contour line crosses a light-duty road known locally as Hayden Ranch Road about 50 yards north of Texas Ranch Road 2093. 
(11) Then 50 yards south on Hayden Ranch Road to Texas Ranch Road 2093 and then east on Texas Ranch Road 2093 approximately .15 mile to an unimproved, southbound, gravel and dirt county road known locally as Beverly Gold&#39;s Road. 
(12) Then approximately 2.6 miles south on Beverly Gold&#39;s Road to a point where it joins Texas State Route 16. 
(13) Then approximately 1.5 miles northeast on State Route 16 to a light-duty county road known locally as Bear Creek Road. 
(14) Then approximately 1 mile in a southeasterly, northeasterly, and then a southerly direction along Bear Creek Road to the point where the road crosses the 1,700-foot contour line. 
(15) Then in a generally easterly direction for approximately 10 miles along the 1,700-foot contour line to a point where the 1,700-foot contour line crosses Texas Ranch Road 1376. 
(16) Then approximately 3.1 miles southeast along Texas Ranch Road 1376 to a light-duty road at Luckenbach known locally both as Kunz-Klien Road and Luckenbach Road. 
(17) Then approximately 1.3 miles in a generally northeasterly and then an easterly direction along Luckenbach Road and continuing along Luckenbach Road in a northerly direction about 2.5 miles to the point where Luckenbach Road joins U.S. Route 290. 
(18) Then west approximately .2 mile on U.S. Route 290 to the intersection with Jung Road, the point of beginning.

**Comment by KyleWSmith** [comment]
In progress.

**Comment by MicheleTobias** [comment]
Hi Kyle! Are you still working on this one?

**Comment by MicheleTobias** [comment]
@KyleWSmith are you still working on this AVA?  If you are, that's great.  If not, let me know and I will let @SoominHur finish it.

**Comment by MicheleTobias** [comment]
@KyleWSmith I've got several new contributors who would be happy to finish this one.  I'll give it a few more days, but if I don't hear soon I'll let someone else work on it.

**Comment by MicheleTobias** [comment]
This AVA is available for someone to work on.

**Comment by Glenn-Mortimer** [comment]
Working on this one. Polygon created and pushed. Missing attribute data, I was unable to access Hein Online Federal Register Library.

**Comment by MicheleTobias** [comment]
Thanks for picking this one up! I'll await your pull request.  In the future, let everyone know you're working on it before you start by commenting on the issue just to prevent people working on the same one.  I can do the attributes for it.  I know the government docs source we've recommended is not available to everyone.

**Comment by kurtishouser** [comment]
The Federal Register documents are available at https://www.govinfo.gov as well.

The FR doc concerning Fredericksburg in the Texas Hill Country can be found here.
https://www.govinfo.gov/app/details/FR-1988-12-22
The PDF can be downloaded using the link in the left column. Here's the direct link.
https://www.govinfo.gov/content/pkg/FR-1988-12-22/pdf/FR-1988-12-22.pdf

Since these are coming directly from the US Government I'm assuming they are the same documents as those in the Hein Online Federal Register Library.

**Comment by alisonsnwong** [comment]
Checked!
- Updated `used_maps` section
- Corrected contour lines
- Fixed mistake in Step (12)
