### ISSUE TITLE
grand_river_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#81]
# AVA: Grand River Valley (grand_river_valley)

name | value
--- | ---
ava_id | grand_river_valley
cfr_index | 9.87
revision | [T.D. ATF-157, 48 FR 48821, Oct. 21, 1983]
state | OH
county | Ashtabula|Geauga|Lake
within | Lake Erie
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c

**Comment by ericallanwest** [comment]
Please label this one In Progress and Virginia Tech. Thanks!
