### ISSUE TITLE
Check that the ava.js is updated from the avas.geojson

### ISSUE THREAD

**Issue by erklopez** [UCDavisLibrary/ava#815]
Is the ava.js in the docs/webmap directory is automatically updated if any changes are made to the ava.geojson in the avas_aggregated_files directory.

**Comment by MicheleTobias** [comment]
See where it outputs in the mergeGeoJson.R file.

**Comment by erklopez** [comment]
The output is the docs/webmap ( writeLines(js, "./docs/web_map/avas.js") )
