### ISSUE TITLE
green_valley_of_russian_river

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#83]
# AVA: Green Valley of Russian River (green_valley_of_russian_river)

name | value
--- | ---
ava_id | green_valley_of_russian_river
cfr_index | 9.57
revision | [T.D. ATF-161, 48 FR 52579, Nov. 21, 1983, as amended by T.D. TTB-60, 72 FR 13692, Mar. 23, 2007]
state | CA
county | Sonoma
within | North Coast\|Northern Sonoma Valley\|Russian River Valley\|Sonoma Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Sebastopol Quadrangle, California—Sonoma Co.”, 7.5 minute series 
1954, photorevised 1980.; 
2. “Camp Meeker Quadrangle, California—Sonoma Co.”, 7.5 minute series 
1954, photorevised 1971.; and 
3. “Guerneville Quadrangle, California—Sonoma Co.”, 7.5 minute series 
1955..

## Boundary [src]

(1) From the beginning point, the boundary runs south along the line separating Section 31 from Section 32, continuing south along Covey Road 
(shown on the map as an unnamed, light-duty road) to the town of Forestville where Covey Road intersects with State Highway 116 
(Gravenstein Highway). 
(2) Thence east along State Highway 116 until it turns in a southeasterly direction and then proceeding along State Highway 116 in a southeasterly direction until the point at which State Highway 116 intersects State Highway 12 in the town of Sebastopol 
(located on the “Sebastopol Quadrangle” map); 
(3) Thence in a southwesterly direction on State Highway 12 through the town of Sebastopol; 
(4) Thence in a westerly direction on State Highway 12, which becomes Bodega Road, until Bodega Road intersects with Pleasant Hill Road; 
(5) Thence in a southerly direction on Pleasant Hill Road until it intersects with Water Trough Road; 
(6) Thence westerly and then northwesterly on Water Trough Road until it intersects with Gold Ridge Road; 
(7) Thence in a southwesterly, northwesterly, and then a northeasterly direction along Gold Ridge Road until it intersects with Bodega Road; 
(8) Thence in a southwesterly direction along Bodega Road until Bodega Road intersects with Jonive Road in Township 6 North 
(T.6N.), Range 9 West 
(R.9W.) located in the southeast portion of U.S.G.S. map “Camp Meeker Quadrangle”; 
(9) Thence proceeding in a northwesterly direction on Jonive Road until it intersects Occidental Road; 
(10) Thence proceeding on Occidental Road in a northwesterly direction until Occidental Road intersects the west border of Section 35; 
(11) Thence proceeding due north along the west borders of Sections 35, 26, 23, and 14 to the northwest corner of Section 14; 
(12) Thence in an easterly direction along the north border of Section 14 to the northeast corner of Section 14; 
(13) Thence north along the west borders of Sections 12, 1, and 36 to the northwest corner of Section 36 located in the extreme southern portion of the “Guerneville Quadrangle” map; 
(14) Thence in an easterly direction along the north border of Section 36 until it intersects with River Road; 
(15) Thence in a southeasterly direction along River Road to the point of beginning located on the “Camp Meeker Quadrangle” map. 
(d) From December 21, 1983, until April 23, 2007, the name of this viticultural area was “Sonoma County Green Valley”. Effective April 23, 2007, this viticulture area is named “Green Valley of Russian River Valley”. Existing certificates of label approval showing “Sonoma County Green Valley” as the appellation of origin will be revoked by operation of this regulation on April 23, 2009.

**Comment by amberreyes** [comment]
I'm finishing up this AVA and the only Federal Register document I can find is for the name change of the AVA, which doesn't  have the original petitioner/author that I need for the attribute table.
Should I use the names listed anyways or leave them blank?

**Comment by MicheleTobias** [comment]
I couldn't find it until I realized I had to search for the old name (before they changed the name): http://heinonline.org/HOL/Page?men_tab=srchresults&handle=hein.fedreg/048225&size=2&collection=fedreg&id=21 Limiting the search years also helps.

**Comment by SoominHur** [comment]
Reviewed.
- Edit created date in the attribute table
