### ISSUE TITLE
upper_lake_valley

### ISSUE THREAD

**Issue by elistockwell** [UCDavisLibrary/ava#836]
New AVA to digitize!

https://www.ecfr.gov/current/title-27/chapter-I/subchapter-A/part-9/subpart-C/section-9.286

Digitizing Methods:
https://ucdavislibrary.github.io/ava/methods.html#digitize-new-boundaries

**Comment by alisonsnwong** [comment]
Will be working on digitizing this AVA.

**Comment by alisonsnwong** [comment]
There were 2 mistakes in the boundary description for Upper Lake Valley:
(13) Proceed south, then west (should be east) along the Mendocino National Forest boundary to its intersection with the 1,600-foot elevation contour along the northern boundary of Section 5, T15N/R9W; then

(19) Proceed northeasterly (should be NW) along the shoreline of Clear Lake, crossing onto the Lakeport map, and continuing southwesterly along the shoreline, crossing Rodman Slough, to return to the beginning point.
