### ISSUE TITLE
paulsell_valley

### ISSUE THREAD

**Issue by elistockwell** [UCDavisLibrary/ava#837]
New AVA to digitize!

https://www.ecfr.gov/current/title-27/chapter-I/subchapter-A/part-9/subpart-C/section-9.285

Digitizing Methods:
https://ucdavislibrary.github.io/ava/methods.html#digitize-new-boundaries

**Comment by alisonsnwong** [comment]
Will start working on this.

**Comment by MicheleTobias** [comment]
Step 5 says to stop at the 5th intermittent creek, but I think the author miscounted (there's one in a cove in the southeast section of the reservoir. I think the way Alison digitalized it makes more sense, given the rest of the description.

**Comment by MeyaSaenzZagar** [comment]
I agree with Allison and Michele's interpretation of Step 5. The directions say to stop at the northernmost point which is described as the fifth intermittent creek. But the directions miscounted the creeks as the sixth intermittent creek is actually at the northernmost part of the lake.
