### ISSUE TITLE
rocky_reach

### ISSUE THREAD

**Issue by elistockwell** [UCDavisLibrary/ava#838]
New AVA to digitize!

https://www.ecfr.gov/current/title-27/chapter-I/subchapter-A/part-9/subpart-C/section-9.287

Digitizing Methods:
https://ucdavislibrary.github.io/ava/methods.html#digitize-new-boundaries

**Comment by alisonsnwong** [comment]
In progress

**Comment by alisonsnwong** [comment]
There are some details I believe that are missing in the boundary description:

(6) Proceed easterly along the 1,200-foot elevation contour, (crosses over ENTIAT map first) crossing onto the Winesap map, and continuing northeasterly along the 1,200-foot elevation contour to its intersection with the boundary between sections 11 and 12, T26N/R21E; then

(10) Proceed generally westerly along the 1,600-foot elevation contour (some parts crosses over WATERVILLE map), crossing over the southeastern corner of the Winesap map and onto the Entiat map, and continuing southwesterly along the 1,600-foot elevation contour to its intersection with an unnamed stream in section 35, T26N/R21E; then

(12) Proceed southerly along the 1,200-foot elevation contour, crossing over the Orondo map and (crosses over ROCKY REACH DAM map first) onto the Wenatchee map to the intersection of the elevation contour with the southern boundary of section 14, T23N/R20E; then
