### ISSUE TITLE
guenoc_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#84]
# AVA: Guenoc Valley (guenoc_valley)

name | value
--- | ---
ava_id | guenoc_valley
cfr_index | 9.26
revision | 
state | CA
county | Lake
within | North Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]
(b) Approved maps. The appropriate maps for determining the boundaries of the Guenoc Valley viticultural area are four USGS maps. They are titled:

(1) “Middletown Quadrangle, California-Lake Co.,” 7.5 minute series;

(2) “Jericho Valley Quadrangle, California,” 7.5 minute series;

(3) “Detert Reservoir Quadrangle, California,” 7.5 minute series; and

(4) “Aetna Springs Quadrangle, California,” 7.5 minute series.

## Boundary [src]
(c) Boundaries. The Guenoc Valley viticultural area is located within Lake County, California. The beginning point of the boundary is Station 20 of Denton's Survey of Guenoc Rancho, presently marked by a 11⁄2 inch galvanized pipe located atop Jim Davis Peak. On the approved maps, Jim Davis Peak is the unnamed peak (elevation 1,455 feet) located on the western boundary of Section 35, Township 11 North, Range 6 West. From this beginning point the boundary runs:

(1) South 07°49′34″ East, 9,822.57 feet to the USGS triangulation station “Guenoc;”

(2) Then, South 29°14′31″ West, 10,325.08 feet;

(3) Then, South 00°00′ West, 2,100.00 feet;

(4) Then, North 90°00′ West, 4,150.00 feet;

(5) Then, North 24°23′11″ West, 16,469.36 feet;

(6) Then, North 75°47′20″ East, 7,943.08 feet; and

(7) Then, North 60°47′00″ East, 7,970.24 feet to the beginning point.

**Comment by MicheleTobias** [comment]
The description that made it into the issue text wasn't right (now updated). Because the description uses compass bearings and distances, I generated the boundary using R.  The code is here: https://github.com/UCDavisLibrary/ava/blob/master/rcode/GuenocValley.R

**Comment by MicheleTobias** [comment]
The approved maps are largely irrelevant for this boundary.
