### ISSUE TITLE
hames_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#85]
# AVA: Hames Valley (hames_valley)

name | value
--- | ---
ava_id | hames_valley
cfr_index | 9.147
revision | [T.D. ATF-356, 59 FR 14100, Mar. 25, 1994]
state | CA
county | Monterey
within | Central Coast\|Monterey
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]
Approved maps. The appropriate map for determining the boundary of the Hames Valley viticultural area is one U.S.G.S. 15 minute series topographical map, titled Bradley Quadrangle, California, edition of 1961, with a scale of 1:62,500.

## Boundary [src]

(1) Beginning at the southeast corner of section 26, T. 23 S., R. 10 E., which coincides with the point where the 640 foot contour line crosses the Swain Valley drainage, the boundary proceeds in a straight line across section 26 to the northwest corner of section 26, T. 23 S., R. 10 E.; 
(2) Then west northwest in a straight line across sections 22, 21, 20, and 19, T. 23 S., R. 10 E., to the northwest corner of section 24, T. 23 S., R. 9 E.; 
(3) Then southeast in a straight line across sections 24, 25, 30, 31, and 32, to the southeast corner of section 5, T. 24 S., R. 10 E.; 
(4) Then east southeast in a straight line across section 9 to the southeast corner of section 10, T. 24 S., R. 10 E.; 
(5) Then east southeast in a straight line for approximately 2.25 miles to Hill 704, located in section 18, T. 24 S., R. 11 E.; 
(6) Then north northwest in a straight line for approximately 1.35 miles to Hill 801, located near the northwest corner of section 7, T. 24 S., R. 11 E., and then continue in a straight line to the northwest corner of section 6, T. 24 S., R. 11 E.; 
(7) Then in a generally northwesterly direction along the Salinas River for approximately 1 mile to where the Swain Valley drainage enters the Salinas River about .11 mile south of the northern boundary line of section 36, T. 23 S., R. 10 E.; 
(8) Then in a westerly direction for approximately .75 mile along the Swain Valley drainage to the southeast corner of section 26, T. 23 S., R. 10 E., the point of beginning.

**Comment by MicheleTobias** [comment]
I'm working on this one.

**Comment by SoominHur** [comment]
Reviewed.
