### ISSUE TITLE
Check Mount Pisgah

### ISSUE THREAD

**Issue by alisonsnwong** [UCDavisLibrary/ava#850]
This AVA was created after our quality control issues, and needs to be checked!

Original issue: https://github.com/UCDavisLibrary/ava/issues/835

Quality Control Procedures:
https://ucdavislibrary.github.io/ava/methods.html#quality-control-methods

**Comment by MeyaSaenzZagar** [comment]
I will be checking this AVA.

**Comment by MeyaSaenzZagar** [comment]
I checked this AVA and no edits are needed
