### ISSUE TITLE
Check West Sonoma Coast

### ISSUE THREAD

**Issue by alisonsnwong** [UCDavisLibrary/ava#853]
This AVA was created after our quality control issues, and needs to be checked!

Original issue: https://github.com/UCDavisLibrary/ava/issues/834

Quality Control Procedures:
https://ucdavislibrary.github.io/ava/methods.html#quality-control-methods

**Comment by MeyaSaenzZagar** [comment]
I will be checking this AVA.

**Comment by MeyaSaenzZagar** [comment]
I have checked this AVA and it does not need any edits.
