### ISSUE TITLE
Santa Lucia Highlands History

### ISSUE THREAD

**Issue by alisonsnwong** [UCDavisLibrary/ava#858]
This AVA has the following revisions:

- [ ] [T.D. TTB172, 86 FR 47379, Aug. 25, 2021]

Each revision should be represented by a polygon inside the .geojson file for this AVA. See the [Historical Boundary Methods](https://ucdavislibrary.github.io/ava/methods.html#historical-boundary-methods) document for more information on how to add historical boundaries.

**Comment by kurtishouser** [comment]
I'm working on this and #862. Arroyo Seco is part of the same revision.
