### ISSUE TITLE
happy_canyon_of_santa_barbara

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#86]
# AVA: Happy Canyon of Santa Barbara (happy_canyon_of_santa_barbara)

name | value
--- | ---
ava_id | happy_canyon_of_santa_barbara
cfr_index | 9.217
revision | [T.D. TTB-82, 74 FR 51776, Oct. 8, 2009]
state | CA
county | Santa Barbara
within | Central Coast\|Santa Ynez Valley
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Los Olivos, CA, 1995; 
2. Figueroa Mountain, CA, 1995; 
3. Lake Cachuma, CA, 1995; and 
4. Santa Ynez, CA, 1995.

## Boundary [src]

(1) The beginning point is on the Los Olivos map at the intersection of the Santa Lucia Ranger District diagonal line and Figueroa Mountain Road, a light-duty road, section 27, T8N, R30W. From the beginning point, proceed southeast along the Santa Lucia Ranger District diagonal line, crossing onto the Figueroa Mountain map, and continuing east to its intersection with the northwest corner of section 6, T7N, R29W; then 
(2) Proceed straight south along the R29W and R30W line, which is a boundary line of the Los Padres National Forest, to its intersection with the southwest corner of section 18 that coincides with one of the two 90-degree, southwest corners of the Los Padres National Forest, T7N, R29W; then 
(3) Proceed east, south, and then east, along the boundary line of the Los Padres National Forest, to its intersection with the boundary line of the Cañada de Los Pinos, or College Rancho Grant, at the northwest corner of section 28, T7N, R29W; then 
(4) Proceed straight south along the boundary line of the Cañada de Los Pinos, or College Rancho Grant, crossing onto the Lake Cachuma map, to its intersection with the 1,074-foot Bitt elevation point and the Lake Cachuma Recreation Area boundary line, section 17 east boundary line, T6N, R29W; then 
(5) Proceed generally southwest along the Lake Cachuma Recreation Area boundary line to its intersection with the Santa Ynez River to the west of Lake Cachuma and Bradbury Dam, T6N, R30W; then 
(6) Proceed generally west along the Santa Ynez River, crossing onto the Santa Ynez map, and continuing to its intersection with California State Road 154, northwest of BM 533, T6N, R30W; then 
(7) Proceed north-northwest in a straight line 1.2 miles to the marked 924-foot elevation point, T6N, R30W; then 
(8) Proceed north-northwest in a straight line 1.2 miles to the “Y” in an unimproved road 0.1 mile south of the 800-foot elevation line, west of Happy Canyon Road, T6N, R30W; then 
(9) Proceed north-northwest in a straight line for 0.5 mile, crossing onto the Los Olivos map, and continuing to the marked 1,324-foot elevation point, 0.5 mile southwest of Bar G O Ranch, T7N, R30W; then 
(10) Proceed north-northwest in a straight line for 2.5 miles crossing over the marked 1,432-foot elevation point in section 9, then continue in a straight line northerly 1.4 miles to the marked 1,721-foot elevation point in section 4, T7N, R30W; then 
(11) Proceed north in a straight line 1.4 miles to the marked 2,334-foot elevation point, west of a meandering unimproved road and south of Figueroa Mountain Road, T8N, R30W; then 
(12) Proceed east-northeast in a straight line, returning to the beginning point.

**Comment by SoominHur** [comment]
Reviewed
- Correct cfr author name typo
- Add scale information of used maps
