### ISSUE TITLE
Clarksburg History

### ISSUE THREAD

**Issue by alisonsnwong** [UCDavisLibrary/ava#860]
This AVA has the following revisions:

[T.D. TTB178, 87 FR 13159, Mar. 9, 2022]

Each revision should be represented by a polygon inside the .geojson file for this AVA. See the [Historical Boundary Methods](https://ucdavislibrary.github.io/ava/methods.html#historical-boundary-methods) document for more information on how to add historical boundaries.

**Comment by kurtishouser** [comment]
I'm working on this.
