### ISSUE TITLE
Arroyo Seco History

### ISSUE THREAD

**Issue by alisonsnwong** [UCDavisLibrary/ava#862]
This AVA has the following revisions:

 [T.D. TTB172, 86 FR 47379, Aug. 25, 2021]

Each revision should be represented by a polygon inside the .geojson file for this AVA. See the [Historical Boundary Methods](https://ucdavislibrary.github.io/ava/methods.html#historical-boundary-methods) document for more information on how to add historical boundaries.

**Comment by kurtishouser** [comment]
I'm working on this and #858. Santa Lucia Highlands is part of the same revision.

**Comment by kurtishouser** [comment]
Arroyo Seco revision [86 FR 52825, Sept. 23, 2021](https://www.federalregister.gov/citation/86-FR-52825) is a correction that did not change the boundaries or info used by the dataset so an additional feature was not created for it.
