### ISSUE TITLE
Can we change the name of the Mendocino Ridge outside boundary?

### ISSUE THREAD

**Issue by kurtishouser** [UCDavisLibrary/ava#869]
The TTB map uses Outline.

So how about 'mendocino_ridge_outline' and 'Mendocino Ridge (Outline)' for all the respective places?

It's currently mendocino_ridge_outside_boundary.geojson, mendocino_ridge3, mendocino_ridge, and Mendocino Ridge.

**Comment by MicheleTobias** [comment]
I'm open to clarifying things and using better names, but I don't understand what the ask is.  Can you clarify a bit? I'm looking at the mendocino_ridge.geojson polygon and that's just one multipolygon with a ton of subpolygons, so I'm not sure what the other names refer to.

**Comment by kurtishouser** [comment]
I'm referring the the file in the `unofficial_boundaries` folder.

Currently
`mendocino_ridge_outside_boundary.geojson`
```
{
"type": "FeatureCollection",
"name": "mendocino_ridge3",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "ava_id": "mendocino_ridge", "name": "Mendocino Ridge", ...
```

Proposed:
`mendocino_ridge_outline.geojson`
```
{
"type": "FeatureCollection",
"name": "mendocino_ridge_outline",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "ava_id": "mendocino_ridge_outline", "name": "Mendocino Ridge (Outline)", ...
```

**Comment by MicheleTobias** [comment]
Oh! That makes sense. Thanks for clarifying. I'll take a look at that.

**Comment by MicheleTobias** [comment]
Ok, yes, @kurtishouser your proposed changes make sense to me. When we originally made this file, I remember that we knew it would need some updates once we had more perspective and I think what you're proposing solves those questions.   Do you want to submit a PR for this?

**Comment by kurtishouser** [comment]
@MicheleTobias Sure! I can submit the PR. I also noticed that the `boundary_description` for both files has omitted this section of text from the CFR.

"(c) Boundary.  The Mendocino Ridge viticultural area is located within Mendocino County, California. Within the boundary description that follows, the viticultural area starts at the 1200 foot elevation (contour line) and encompasses all areas at or above the 1200 foot elevation line. The boundaries of the Mendocino Ridge viticultural area, using landmarks and points of reference found on appropriate U.S.G.S. maps, follow."


It seems rather pertinent to me. Shall I include all/some of this (for both files) in the PR as well?

**Comment by MicheleTobias** [comment]
Yes, please fix the boundary description. The original script that scraped the eCFR back in 2017 sometimes missed the unnumbered steps in some cases.

**Comment by kurtishouser** [comment]
I believe the original scraping script intentionally excluded the non-numbered steps. There's important info in the (b) and (c) sections that should probably be included in the data set. And even in the (d) section for the AVAs that were renamed.
