### ISSUE TITLE
haw_river_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#87]
# AVA: Haw River Valley (haw_river_valley)

name | value
--- | ---
ava_id | haw_river_valley
cfr_index | 9.214
revision | [T.D. TTB-74, 74 FR 14045, Mar. 30, 2009]
state | NC
county | Alamance|Caswell|Chatham|Guilford|Orange|Rockingham
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Greensboro, North Carolina, 1984; and 
2. Chapel Hill, North Carolina, 1984.

## Boundary [src]

(1) Begin at a point on the Greensboro map at the intersection of the Caswell and Orange Counties boundary line with Lynch Creek, southeast of Corbett and the Corbett Ridge, and then proceed in a straight line southeast 2 miles to the intersection of North Carolina State Highway 49 and an unnamed, light-duty road, known locally as McCulloch Road, located approximately 1 mile northeast of Carr, in west Orange County; then 
(2) Proceed in a straight line south-southwest 11.9 miles, crossing over U.S. Interstate 85, to Buckhorn at Turkey Hill Creek in west Orange County; then 
(3) Proceed in a straight line southeast 5.2 miles, crossing onto the Chapel Hill map, to its intersection with Dodsons Crossroad and an unnamed, light-duty road that runs generally north-northeast-south-southwest in west Orange County; then 
(4) Proceed south-southwest on the unnamed, light-duty road 3.4 miles to its intersection with North Carolina State Highway 54, also known as Star Route 54, east of White Cross in west Orange County; then 
(5) Proceed southeast in a straight line 14.1 miles, crossing over Terrells Mountain, Wilkinson Creek and several of its eastern tributaries, and U.S. Route 15-501, until the line intersects with an unnamed road, known locally as Gilead Church Road, and U.S. Route 64 at Griffins Crossroads in Chatham County; then 
(6) Proceed generally west along U.S. Route 64 approximately 20.7 miles to its intersection with U.S. Route 421 in Siler City, Chatham County; then 
(7) Proceed generally northwest on U.S. Route 421 approximately 5.6 miles to its intersection with the Randolph County line, southeast of Staley; then 
(8) Proceed straight north along the Randolph County line 7.4 miles to its intersection with the Guilford County line; then 
(9) Proceed straight west along the Randolph County line 5.8 miles to its intersection with U.S. Route 421; then 
(10) Proceed in a straight line north-northwest 20.5 miles, crossing onto the Greensboro map, to its intersection with U.S. Route 29 and North Carolina State Highway 150, between Browns Summit and Monticello in Guilford County; then 
(11) Proceed generally east and north on North Carolina State Highway 150 approximately 4.3 miles to its intersection with North Carolina State Highway 87, east-northeast of Williamsburg in southeast Rockingham County; then 
(12) Proceed in a straight line east-northeast 8.3 miles, crossing over the Caswell County line to a point at the intersection of the 236-meter elevation line, as marked on the map, and an unnamed road, known locally as Cherry Grove Road; then 
(13) Proceed east and southeast along the unnamed road, known locally as Cherry Grove Road, 5 miles to its intersection with North Carolina State Highway 62 at Jericho in Caswell County; then 
(14) Proceed generally southeast on North Carolina State Highway 62 approximately 1.8 miles to its intersection with an unnamed road, known locally as Bayne&#39;s Road at Anderson in Caswell County; then 
(15) Proceed generally east on the unnamed road known locally as Baynes Road 2 miles to its intersection with North Carolina State Highway 119 at Baynes in Caswell County; then 
(16) Proceed generally south-southeast along North Carolina State Highway 119 approximately 1.7 miles to its intersection with the Caswell County line; then 
(17) Proceed straight east along the Caswell County line 4.3 miles to the beginning point.

**Comment by davidkli** [comment]
This AVA has been checked. The boundary is good. The attribute table was updated to follow the formatting.
