### ISSUE TITLE
Missing Gabilan Mountains AVA

### ISSUE THREAD

**Issue by wayne530** [UCDavisLibrary/ava#887]
https://www.ecfr.gov/current/title-27/chapter-I/subchapter-A/part-9/subpart-C/section-9.288

Chalone and Mt. Harlan AVAs that are currently (in your database) contained within the Central Coast AVA are now wholly contained in the new Gabilan Mountains AVA.

**Comment by MicheleTobias** [comment]
Please clarify your proposed solution to this issue.

**Comment by wayne530** [comment]
@MicheleTobias I believe the following changes should be made:

1. Add the Gabilan Mountains AVA; [CFR 9.288](https://www.ecfr.gov/current/title-27/chapter-I/subchapter-A/part-9/subpart-C/section-9.288). It is `within` the Central Coast AVA and it `contains` the Mt. Harlan and Chalone AVAs.
2. Add the Gabilan Mountains AVA to the Central Coast AVA's `contains` property.
3. Update the Mt. Harlan AVA's `within` property to `Central Coast|Gabilan Mountains`.
4. Update the Chalone AVA's `within` property to `Central Coast|Gabilan Mountains`.

Let me know if you have any other questions.

**Comment by MicheleTobias** [comment]
This is a known issue #683 that arises when new AVAs that are created and it affects fore than this particular situation. We are in the process of writing a script to batch fix these. If you feel it is important to update this specific AVA, please submit a pull request with the changes.

**Comment by wayne530** [comment]
@MicheleTobias The repository seems to contain materialized views of some central source of truth. It doesn't seem effective to update the materialized views here in this repository, which contain a lot of duplicated information, while the source of truth remains unchanged.
