### ISSUE TITLE
"The Hamptons, Long Island" AVA

### ISSUE THREAD

**Issue by wayne530** [UCDavisLibrary/ava#888]
As defined in https://www.ecfr.gov/current/title-27/chapter-I/subchapter-A/part-9/subpart-C/section-9.101

The Long Island AVA definition's `contains` doesn't seem to follow other definitions, where wholly contained AVAs are pipe-delimited:

```
{
  ...,
  "contains": "North Fork of Long Island; The Hamptons|Long Island",
  ...
}
```

It seems like this should be set to `North Fork of Long Island|The Hamptons, Long Island`.

In "The Hamptons, Long Island" AVA definition, the name of the AVA is missing the comma. I'm not sure if that was done intentionally or simply a typo.

In the file `us_by_ava.csv`, the row for the Long Island AVA incorrectly lists the contained AVA as `The Hamptons` rather than `The Hamptons, Long Island`.

**Comment by MicheleTobias** [comment]
@alisonsnwong can you explore this and see if changes need to be made? Ask me questions as needed.
