### ISSUE TITLE
high_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#89]
# AVA: High Valley (high_valley)

name | value
--- | ---
ava_id | high_valley
cfr_index | 9.189
revision | [T.D. TTB-30, 70 FR 38001, July 1, 2005]
state | CA
county | Lake
within | Clear Lake\|North Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Clearlake Oaks Quadrangle, California—Lake County; edition of 1958; photorevised 1975, minor revision 1994; 
2. Benmore Canyon Quadrangle, California—Lake County; provisional edition of 1989, minor revision 1994; and 
3. Lucerne Quadrangle, California—Lake County; edition of 1958, photorevised 1975, minor revision 1994.

## Boundary [src]

(1) The point of beginning is on the Clearlake Oaks map on the northern boundary line of section 16 
(also the southern boundary of the Mendocino National Forest), T14N, R8W, at the intersection of the section line and High Valley Road; 
(2) From the beginning point, proceed due east 2.4 miles along the northern boundary lines of sections 16, 15, and 14 
(also the southern boundary of the Mendocino National Forest) to the northeast corner of section 14, T14N, R8W; then 
(3) Proceed straight east-southeast 3.15 miles to the intersection of the 2,000-foot elevation line and the eastern boundary of section 17, T14N, R7W; then 
(4) Proceed easterly 2.7 miles along the meandering 2,000-foot elevation line to its first intersection with the eastern boundary of section 22, T14N, R7W, on the Benmore Canyon map; then 
(5) Proceed due south approximately 300 feet along the eastern boundary of section 22, T14N, R7W, to its intersection with the headwaters of the north branch of the Salt Canyon Creek; then 
(6) Proceed easterly 0.4 mile along the north branch of the Salt Canyon Creek to its intersection with the 1,600-foot elevation line in section 23, T14N, R7W; then 
(7) Proceed southerly along the meandering 1,600-foot elevation line 4.1 miles to its intersection with State Route 20, just north of Sweet Hollow Creek, in section 35, T14N, R7W; then 
(8) Proceed southwest and then west 1.7 miles on State Route 20 to its intersection with the 1,600-foot elevation line just northwest of BM 1634, Wye, in section 3, T13N, R7W; then 
(9) Proceed westerly 15.2 miles along the meandering 1,600-foot elevation line, crossing the Clearlake Oaks map, to the elevation line&#39;s intersection with an unnamed intermittent stream in Pierce Canyon in the northeast quadrant of section 20, approximately 0.4 mile east of VABM 2533, T14N, R8W, on the Lucerne map; then 
(10) Proceed northerly and then northeasterly along the unnamed intermittent stream in Pierce Canyon and then the stream&#39;s northern fork approximately 1.6 miles to the northern fork&#39;s intersection with the 3,000-foot elevation line in section 16, T14N, R8W, on the Clearlake Oaks map; and then 
(11) Proceed straight northeast 0.15 mile, returning to the beginning point.

**Comment by SoominHur** [comment]
Reviewed.
