### ISSUE TITLE
gabilan_mountains

### ISSUE THREAD

**Issue by alisonsnwong** [UCDavisLibrary/ava#891]
New AVA to digitize!
https://www.ecfr.gov/current/title-27/chapter-I/subchapter-A/part-9/subpart-C/section-9.288

Full document: https://www.federalregister.gov/documents/2022/08/15/2022-17508/establishment-of-the-gabilan-mountains-viticultural-area#sectno-citation-9.288

Digitizing Methods: https://ucdavislibrary.github.io/ava/methods.html#digitize-new-boundaries

**Comment by vanithyL** [comment]
In progress by Anthony La!

**Comment by MicheleTobias** [comment]
Welcome to the AVA project, @vanithyL ! Let me know when questions come up, either by posting here or you can reach out to me on DataLab's Slack. I added the In Progress label to let other collaborators know this issue is underway.

**Comment by kurtishouser** [comment]
As noted by @wayne530, the `contains` and `within` fields in other files will need to be updated as well. See issue [887](https://github.com/UCDavisLibrary/ava/issues/887#issuecomment-1281118919).

**Comment by MicheleTobias** [comment]
#877 is a duplicate issues. #683 will handle this and all the others that have this issue. 
@vanithyL please just worry about the boundary and the attribute table following our established methods. @alisonsnwong is currently working on the county issue that is related and when that code is finished, we'll be able to add the within and contains checking fairly easily.

**Comment by kurtishouser** [comment]
@MicheleTobias I disagree that these are duplicate issues. #683 is addressing historical data for these fields as they relate to changing boundaries. Gabilan Mountains is a new AVA that exists within and contains previous AVAs. Best practice would be to make the necessary changes manually (as noted on Federal Register page and summarized on the TTB page) in the other files and include them in the PR. It doesn't even need to involve QGIS. All one has to do is open the files in a text editor, locate the current feature and make the appropriate changes. Easy peasy.

Then the dataset in the `ava` folder would be complete the moment the PR is merged.

**Comment by kurtishouser** [comment]
I'm only referring to Gabilan Mountain. I'm not concerned with the others.

Going forward, the standard process should be to include other files in the PR that are affected by any new or updated AVAs.

That is the case here. It's not a new AVA in a completely different area. It `contains` and is `within` other AVAs so the `contains` and `within` fields in those AVAs need to be updated  as well. Do [this](https://github.com/UCDavisLibrary/ava/issues/887#issuecomment-1281118919) and you're good to go.

**Comment by MicheleTobias** [comment]
As I said, we have a plan for handling this. Your concern has been noted.

**Comment by wayne530** [comment]
I'm not sure where you're obtaining the `contains` and `within` information for each AVA, but by chance if it is from the TTB's established AVAs site, you might find the following parser helpful: https://github.com/devcraftco/extract-ttb-avas
It is definitely not the most reliable source of the data as it appears to be updated by hand (and inconsistently with many typos), but seemed good enough. I think the other source is the `AVAs_Production` dataset in ArcGIS.

**Comment by kurtishouser** [comment]
Fine. I'll submit a PR with the correct info myself after this AVA has been added.

**Comment by MicheleTobias** [comment]
Is there a reason this needs to be updated for Galiban Mountains quickly and we shouldn't handle it programmatically?

**Comment by kurtishouser** [comment]
It's not really about wanting something updated quickly. It's the proper way to handle it.

If this AVA is merged without the changes to the Central Coast, Chalone and Mt. Harlan AVAs then the `/avas` dataset  as a whole in the `master` branch will be incorrect until somebody writes and runs a script.

A simple copy-paste into three text files will remedy this. Why wait for the script?

You're so close to having a complete, up-to-date dataset...
