### ISSUE TITLE
Can we get the aggregated files updated?

### ISSUE THREAD

**Issue by kurtishouser** [UCDavisLibrary/ava#897]
I'm using avas.geojson for a little side project and they haven't been updated in five months?

Thanks  & Happy Holidays!

**Comment by MicheleTobias** [comment]
Trying to run the script uncovered Issue #898. On the surface, it should be a pretty quick fix. Fingers crossed!

**Comment by MicheleTobias** [comment]
I fixed the invalid files and ran the scripts that make the aggregated files.

**Comment by kurtishouser** [comment]
@MicheleTobias
I noticed this is in two of the aggregated files (`avas.geojson`, `avas_allboundaries.geojson`). It's also in `docs/web_map/avas.js`.

`{ "type": "Feature", "properties": { "ava_id": null, "name": "delete later", "aka": null, "created": null, "removed": null, "county": null, "state": null, "within": null, "contains": null, "petitioner": null, "cfr_author": null, "cfr_index": null, "cfr_revision_history": null, "approved_maps": null, "boundary_description": null, "used_maps": null, "valid_start": null, "valid_end": null, "lcsh": null, "sameas": null, "area": 45989746.227163531 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ -123.020117170043633, 38.632403888595533 ], [ -122.887020805621091, 38.629048518063875 ], [ -122.954128216254304, 38.702307441338462 ], [ -123.020117170043633, 38.632403888595533 ] ] ] } },`

Is your aggregation script merging `tbd/template.geojson`?

I just removed the line from the file I'm using in my project so I'm good with what I have.

**Comment by MicheleTobias** [comment]
Yes, it probably is getting the template file. I'll update the aggregation script to skip it.

**Comment by kurtishouser** [comment]
I just noticed that there's an `area` property in these files as well. Nice! Maybe include it in the docs?

**Comment by MicheleTobias** [comment]
The file without the TBD boundaries should be available now. I removed the area column from the final product. We use it to order the boundaries so the little boundaries don't get visually lost, but it's not calculated with a good projection for a final product. If you want the area, I'd recommend running it with the data in an area-preserving projection.
