### ISSUE TITLE
horse_heaven_hills

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#90]
# AVA: Horse Heaven Hills (horse_heaven_hills)

name | value
--- | ---
ava_id | horse_heaven_hills
cfr_index | 9.188
revision | [T.D. TTB-28, 70 FR 38007, July 1, 2005]
state | WA
county | Benton|Klickitat|Yakima
within | Columbia Valley
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Umatilla Quadrangle, Oregon—Washington, 1993; 
2. Irrigon Quadrangle, Oregon—Washington, 1993; 
3. Paterson Quadrangle, Washington—Oregon, 1993; 
4. West of Paterson Quadrangle, Washington—Oregon, 1993; 
5. Boardman Quadrangle, Oregon—Washington, 1993; 
6. Crow Butte Quadrangle, Washington—Oregon, 1993; 
7. Golgotha Butte Quadrangle, Washington—Oregon, 1993; 
8. Heppner Junction Quadrangle, Oregon—Washington, 1962, photo revised, 1970; 
9. Wood Gulch Quadrangle, Washington—Oregon, 1962, photo revised 1970, photo inspected 1975; 
10. Crider Valley Quadrangle, Washington, 1962; 
11. Douty Canyon Quadrangle, Washington, 1962; 
12. Tule Prong Quadrangle, Washington, 1965; 
13. Prosser SW Quadrangle, Washington, 1965, photo inspected 1975; 
14. Mabton West Quadrangle, Washington, 1965; 
15. Mabton East Quadrangle, Washington, 1965; 
16. Prosser Quadrangle, Washington, 1965; 
17. Whitstran Quadrangle, Washington, 1965; 
18. Whitstran NE Quadrangle, Washington, 1965; 
19. Corral Canyon Quadrangle, Washington, 1977; 
20. Webber Canyon Quadrangle, Washington, 1965; 
21. Badger Mountain Quadrangle, Washington, 1965, photo revised 1978; 
22. Taylor Canyon Quadrangle, Washington, 1965; 
23. Johnson Butte Quadrangle, 1964, photo revised 1978; 
24. Nine Canyon Quadrangle, 1964; 
25. Wallula Quadrangle, 1992; 
26. Juniper Canyon Quadrangle, 1966, photo revised 1978; 
27. Juniper Quadrangle, 1993; and 
28. Hat Rock Quadrangle, 1993.

## Boundary [src]

(1) Beginning on the Umatilla map at the intersection of Interstate Highway 82 and the north bank of the Columbia River in Benton County, Washington, proceed westerly 
(downstream) along the river&#39;s north bank, passing through the Irrigon, Paterson, West of Paterson, Boardman, Crow Butte, and Golgotha Butte maps, to the mouth of Pine Creek in section 32, T4N/R22E, on the Heppner Junction map in Klickitat County; then 
(2) Follow Pine Creek northwesterly 
(upstream) for approximately 7.0 miles to the junction of Pine Creek and the western boundary of section 16, T4N/R21E, on the Wood Gulch map, then continue north along the section boundary to the point where East Road, which coincides with the section line at this point, crosses the 1,700-foot contour line, very near the southwestern corner of section 9, T4N, R21E; then 
(3) Proceed northeasterly along the meandering 1,700-foot contour line through, and crossing between, the Crider Valley and Douty Canyon maps 
(crossing Alder Creek, Stegeman Canyon, Spring Canyon, Sand Ridge, and Willow Creek) to the point where the 1,700-foot contour line intersects Sand Ridge Road in section 4, T5N, R22E, on the Douty Canyon map; then 
(4) Continue north-northeasterly along the meandering 1,700-foot contour line through, and crossing between, the Tule Prong and Douty Canyon maps 
(crossing Tule Canyon, Tule Prong, and Dead Canyon) to the contour line&#39;s intersection with Alderdale Road in section 31, T7N/R23E, northeast of Coyote Canyon, on the Prosser SW map in Yakima County; then 
(5) Follow Alderdale Road northwest, returning to the Tule Prong map, and continue northwest and then north along Alderdale Road to its intersection with Wandling Road in section 2, T7N/R22E; then 
(6) From that intersection, proceed northeasterly in a straight line to the 2,011-foot peak near the northwest corner of section 1, T7N/R22E, on the Mabton West map, and continue northeasterly in a straight line to the 1,989-foot peak in the southeast corner of section 36, T8N/R22E, on the Mabton East map; then 
(7) From that peak, proceed easterly in a straight line through the 1,860-foot benchmark along side Township Road in section 31, T8N/R23E, to the 2,009-foot peak in section 32, T8N/R23E, then northerly in a straight line to the 2,011-foot peak in the same section, then easterly to the 1,850 foot peak in the northwest quadrant of section 33, T8N/R23E, then east-northeasterly to the 1,964-foot peak beside the western boundary of section 27, T8N/R23E, then east-northeasterly through the 2,031-foot peak in the northwest corner of section 26, T8N/R23E, to the 2,064-foot peak in the northern portion of the same section; then 
(8) From that peak, proceed east-southeast to the 2,093 foot peak in the northeastern quadrant of section 25, T8N/R23E on the Prosser map, then northeasterly in a straight line to the 2,193-foot peak of Horse Hill in the northeast corner of section 25, T8N/R23E, then northeasterly in a straight line, crossing into Benton County, to the 2,107-foot peak in section 19, T8N/R24E, then easterly to the 2,081-foot peak in section 21, T8N/R24E, then east-northeasterly through the 1,813-foot peak near the northwest corner of section 13, T8N/R24E, to the 1,861-foot peak marked with radio towers near the southern boundary of section 12, T8N/R24E; then 
(9) From that peak, proceed northeasterly in a straight line to an unmarked 1,410-foot summit in the northeast corner of section 7, T8N/R25E, on the Whitstran map, then east-southeasterly to the 1,637-foot peak near the center of section 8, T8N/R25E, and then north-northeasterly to the intersection of State Route 221 and Carter Road near the southeast corner of section 5, T8N/R25E; then 
(10) Follow Carter Road northerly to the point where it becomes an unimproved road and continue northerly then easterly along the unimproved road to the 1,854-foot peak of Gibbon Hill in the northeast corner of section 4, T8N/R25E; then 
(11) From that peak, proceed east-northeasterly in a straight line through the 1,745-foot peak in section 35, T9N/R25E, to the 1,976-foot peak in section 36, T9N/R25E, then east-northeasterly in a straight line onto the Whitstran NE map through the 1,808-foot peak in section 30, T9N/R26E, to the 1,818-foot peak in the same section; then 
(12) From that peak, proceed due north in a straight line to the jeep trail above the 1,750-foot contour line near the northeast corner of section 30, T9N/R26E; then 
(13) Follow the jeep trail east-northeasterly to the 2,046-foot peak of Chandler Butte in section 21, T9N/R26E, then east-northeasterly and then southeasterly along the jeep trail through sections 22 and 23, T9N/R26E, on the Corral Canyon map, to the intersection of the jeep trail and McBee Grade road near the gravel pit in the southeast corner of section 23, T9N/R26E, on the Whitstran NE map; then 
(14) From that intersection, proceed southeasterly in a series of straight lines through the 1,689-foot peak in the southeast corner of section 23, T9N/R26E, and the 1,826-foot peak in section 25, T9N/R26E, on the Whitstran map, then, on the Webber Canyon map, through the 1,845-foot peak in section 30, T9N/R27E, the 1,808-foot peak in section 31, T9N/R27E, the 1,745-foot peak in section 32, T9N/R27E, and the 1,572-foot peak of Rome Hill in section 14, T8N/R27E, and then, on the Badger Mountain map, continue in a straight line to the 1,757-foot peak in section 30, T8N/R28E; then 
(15) From the 1,757-foot peak, proceed due south in a straight line to the line&#39;s intersection with Smith Road near the northern boundary of section 6, T7N/R28E; then 
(16) Continue southerly along Smith Road to the road&#39;s intersection with Clodfelter Road at the southern boundary of section 6, T7N/R28E, on the Taylor Canyon map; then 
(17) Proceed east on Clodfelter Road to its intersection with Williams Road at the eastern boundary of section 5, T7N/R28E, and continue east on Williams Road to its intersection with the 1,800-foot contour line in section 4, T7N/R28E; then 
(18) Follow the meandering 1,800-foot contour line southerly then easterly to the contour line&#39;s junction with the northeast corner of section 15, T7N/R28E; then 
(19) From that point, proceed east-southeasterly in a straight line to the 1,680-foot benchmark in section 17, T7N/R29E, on the Johnson Butte map, and continue east-northeasterly in a straight line through the 2,043-foot peak of Johnson Butte in section 16, T7N/R29E, to the 2,220-foot peak of Jump Off Joe summit in section 12, T7N/R29E; then 
(20) From that point, proceed southeasterly in a straight line, through the Nine Canyon map, to the 343-foot benchmark on the bank of the Columbia River at Palmer Pond in section 13, T6N/R30E, on the Wallula map; and then 
(21) Follow the north bank of the Columbia River westerly 
(downstream), through the Juniper Canyon, Juniper, and the Hat Rock maps, to the beginning point at the intersection of Interstate Highway 82 and the north bank of the Columbia River on the Umatilla map.

**Comment by alisonsnwong** [comment]
Checked! Performed minor boundary edits.
