### ISSUE TITLE
Re-Check Cienega Valley

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#907]
The southeast corner of Cienega Valley has a description that previous digitizers (myself included) have interpreted as a self-intersecting polygon that looks like an hourglass. Please check this boundary again to make sure it has been interpreted correctly. If it has, do not change the polygon - it's been designed to maintain the shape without actually creating a self-intersection. If this shape isn't correct, please update the polygon.

**Comment by MeyaSaenzZagar** [comment]
I will be checking AVA.

**Comment by MeyaSaenzZagar** [comment]
I checked this AVA and it does not need any edits.
