### ISSUE TITLE
howell_mountain

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#91]
# AVA: Howell Mountain (howell_mountain)

name | value
--- | ---
ava_id | howell_mountain
cfr_index | 9.94
revision | [T.D. ATF-163, 48 FR 57487, Dec. 30, 1983, as amended by T.D. ATF-249, 52 FR 5960, Feb. 27, 1987]
state | CA
county | Napa
within | Napa Valley\|North Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Detert Reservoir, CA.,” 1959 
photorevised 1980.. 
2. “Aetna Springs, CA.,” 1958 
photorevised 1981.. 
3. “Calistoga, CA.,” 1958 
photorevised 1980.. 
4. “St. Helena, CA.,” 1960 
photorevised 1980..

## Boundary [src]

(1) Beginning at the 1,400 foot contour line at the intersection of Sections 15 and 16 in R6W/T9N of the Detert Reservoir Quadrangle U.S.G.S. map. 
(2) Then continuing in an east and southeast direction along the 1,400 foot contour line to the southeast corner of Section 23 in R5W/T8N. 
(3) Then in a generally northwest direction along the 1,400 foot contour line until it intersects the line between Sections 21 and 22 in R6W/T9N. 
(4) Then north along the Section 21/22 boundary line to the starting point at the 1,400 foot contour line.

**Comment by SoominHur** [comment]
Reviewed.
- Edited creation date in attribute table
