### ISSUE TITLE
long_valley_lake_county

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#911]
# AVA: Long Valley–Lake County (long_valley_lake_county)

name | value
--- | ---
ava_id | long_valley_lake_county
cfr_index | 9.289
revision | [T.D. TTB–188, [88 FR 42881](https://www.federalregister.gov/citation/88-FR-42881), July 5, 2023]
state | CA
county | Lake
within | *** Fill In ***
contains | *** Fill In ***

[src]: https://www.ecfr.gov/current/title-27/chapter-I/subchapter-A/part-9/subpart-C
## Approved Maps [src]

The three United States Geological Survey (USGS) 1:24,000 scale topographic maps used to determine the boundary of the Long Valley–Lake County viticultural area are titled: 

(1) Clearlake Oaks, California, 1996; 

(2) Benmore Canyon, California, 1996; and 

(3) Lower Lake, California, 1993.

## Boundary

Boundary.  The Long Valley–Lake County viticultural area is located in Lake County, California. The boundary of the Long Valley–Lake County viticultural area is as described as follows: 

(1) The beginning point is on the Benmore Canyon map at the intersection of State Highway 20 and the 1,600-foot elevation contour, just north of Sweet Hollow Creek, in section 35, T14N/R7W. 

(2) From the beginning point, proceed northerly along the meandering 1,600-foot elevation contour for approximately 4.1 miles to its intersection with the northern fork of an unnamed creek in Salt Canyon known locally as Salt Creek in section 23, T14N/R7W; then 

(3) Proceed westerly (upstream) along Salt Creek approximately 760 feet to its intersection with the 1,720-foot elevation contour in section 23, T14N/R7W; then 

(4) Proceed northeasterly, then westerly along the meandering 1,720- foot elevation contour for approximately 11.3 miles, crossing onto the Clearlake Oaks map, to the intersection of the elevation contour with the Mendocino National Forest boundary along the western boundary of section 12, T15N/R8W; then 

(5) Proceed north along the Mendocino National Forest boundary approximately 896 feet to its intersection with the unnamed creek in Sulphur Canyon; then 

(6) Proceed northeast (downstream) along the unnamed creek approximately 770 feet to its intersection with the 1,400-foot elevation contour in section 12, T14N/R8W; then 

(7) Proceed northeasterly, then northwesterly along the meandering 1,400-foot elevation contour to its intersection with the Mendocino National Forest boundary along the western boundary of section 36, T15N/R8W; then 

(8) Proceed north along the western boundary of section 36 to its intersection with the northern boundary of section 36; then 

(9) Proceed east along the northern boundary of section 36 to its intersection with the 1,400-foot elevation contour; then 

(10) Proceed southeasterly along the 1,400-foot elevation contour, crossing onto the Benmore Canyon map and continuing easterly along the 1,400-foot elevation contour to its intersection with the southern boundary of section 11, T14N/R7W; then 

(11) Proceed north in a straight line to the northern boundary of section 11; then 

(12) Proceed east along the northern boundary of section 11, crossing Wolf Creek, to the intersection of the section boundary with the 1,320-foot elevation contour; then 

(13) Proceed south in a straight line to the 1,400-foot elevation contour in section 11; then 

(14) Proceed southeasterly along the 1,400-foot elevation contour to the western boundary of section 12, T14N/R7W; then 

(15) Proceed southeast in a straight line, crossing the North Fork of Cache Creek, to the 1,400-foot elevation contour in section 12 west of the summit of Chalk Mountain; then 

(16) Proceed southeasterly, then southerly along the meandering 1,400- foot elevation contour to its third intersection with the eastern boundary of section 13; then 

(17) Proceed west in a straight line to an unnamed, unimproved 4-wheel drive road in section 13; then 

(18) Proceed south in a straight line, crossing over a second unnamed, unimproved 4-wheel drive road in section 13, to the 1,240-foot elevation contour in section 24, T14N/R7W; then 

(19) Proceed east in a straight line to the 1,400-foot elevation contour in section 24; then 

(20) Proceed southeasterly, then northeasterly along the meandering 1,400-foot elevation contour to its intersection with an unnamed creek in section 19, T14N/R6W; then 

(21) Proceed southwesterly (downstream) along the unnamed creek to its intersection with the 1,200-foot contour in section 19; then 

(22) Proceed south in a straight line to the northern boundary of section 30, T14N/R6W; then 

(23) Proceed southeast, then east along the northern boundary of section 30 to its intersection with the 1,400-foot elevation contour; then 

(24) Proceed south in a straight line to the unnamed creek in Benmore Canyon in section 30; then 

(25) Proceed southeast in a straight line to the 1,400-foot elevation contour in section 30; then 

(26) Proceed southeasterly along the 1,400-foot elevation contour to its intersection with the eastern boundary of section 31, T14N/R6W; then 

(27) Proceed generally south along the eastern boundary of section 31 and continuing along the eastern boundary of section 6, T13N/R6W, crossing onto the Lower Lake map, to the intersection of the boundary line and State Highway 20 north of Phipps Creek; then 

(28) Proceed west in a straight line to the 1,200-foot elevation contour; then 

(29) Proceed northerly along the 1,200-foot elevation contour, crossing onto the Benmore Canyon map, and continuing along the 1,200-foot elevation contour to its intersection with an unnamed trail in section 31, T14N/R6W; then 

(30) Proceed north in a straight line to State Highway 20; then 

(31) Proceed west along State Highway 20, returning to the beginning point.

**Comment by kurtishouser** [comment]
Unfortunately, the eCFR/CFR has started mixing the the hyphen-minus (regular dash) ```-``` (\u2003) and the en dash ```–``` (\u2013) in the data on their web pages and XML files. My check-for-updates script flagged the change (It's why I don't strip out anything from the revision history string).

The AVA name is a mixture of both.
https://www.ecfr.gov/current/title-27/chapter-I/subchapter-A/part-9/subpart-C
https://www.ttb.gov/wine/established-avas
https://www.ecfr.gov/api/versioner/v1/structure/2023-08-31/title-27.json

The revision history appears to be using just the en dash now.

It's probably best to stick with the regular dash so if that's the plan then anything copied from these sources would need to be checked/edited first. All fields are affected. The AVA name and revision history are easy. The maps and boundary description are a bit more involved although a simple search/replace in a text editor would probably work fine if these fields are included as well.

It appears that it started with the 2022 CFR XML file.
No en dash
https://www.govinfo.gov/content/pkg/CFR-2021-title27-vol1/xml/CFR-2021-title27-vol1-part9-subpartC.xml
Mixed
https://www.govinfo.gov/content/pkg/CFR-2022-title27-vol1/xml/CFR-2022-title27-vol1-part9-subpartC.xml

I did contact Karen Thornton (AVA Program Manager) back in May when I noticed it but never heard back. I plan to follow up soon to see if she received any information from the Federal Register folks.
