### ISSUE TITLE
hudson_river_region

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#92]
# AVA: Hudson River Region (hudson_river_region)

name | value
--- | ---
ava_id | hudson_river_region
cfr_index | 9.47
revision | [T.D. ATF-105, 47 FR 24294, June 4, 1982]
state | NY
county | Columbia|Duchess|Orange|Putnam|Rockland|Sullivan|Ulster|Westchester
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Albany 
NK 18-6., scale of 1:250,000 series; 
2. Hartford 
NK 18-9., scale of 1:250,000 series; 
3. Scranton 
NK 18-8., scale of 1:250,000 series; 
4. Binghamton 
NK 18-5., scale of 1:250,000 series.

## Boundary [src]

(1) The beginning point is the point where N.Y. Route 15 
(Merritt Parkway) crosses the New York-Connecticut state line. 
(2) The boundary proceeds northerly along the New York-Connecticut state line and the New York-Massachusetts state line to the northeast corner of Columbia County, New York. 
(3) The boundary proceeds westerly along the Columbia County-Rensselaer County line to the Columbia County-Greene County line in the Hudson River. 
(4) The boundary proceeds southerly along the Columbia County-Greene County line in the Hudson River to the northeast corner of Ulster County. 
(5) The boundary proceeds westerly along the Ulster County-Greene County line to N.Y. Route 214. 
(6) The boundary proceeds southerly along the eastern side of N.Y. Route 214 to the junction with N.Y. Route 28 in Phoenicia. 
(7) The boundary proceeds southerly along the eastern side of N.Y. Route 28 to the junction with N.Y. Route 28A. 
(8) The boundary proceeds southerly along the eastern side of N.Y. Route 28A to the intersection with the secondary, hard surface, southbound road leading toward Samsonville. 
(9) The boundary proceeds southerly along the eastern side of this southbound road through Samsonville, Tabasco, Mombaccus, Fantinekill, and Pataukunk to the junction with U.S. Route 209. 
(10) The boundary proceeds southerly along the eastern side of U.S. Route 209 to the New York-Pennsylvania state line in the Delaware River. 
(11) The boundary proceeds easterly along the Delaware River to the New York-New Jersey state line. 
(12) The boundary proceeds easterly along the New York-New Jersey state line to N.Y. Route 17. 
(13) The boundary proceeds northerly along the western side of N.Y. Route 17 to the junction with Interstate Route 287. 
(14) The boundary proceeds easterly along the northern side of Interstate Route 287 to the junction with N.Y. Route 15. 
(15) The boundary proceeds easterly along the northern side of N.Y. Route 15 to the beginning point.

**Comment by sierramabanta** [comment]
I'd like to work on this one.

**Comment by MicheleTobias** [comment]
Enjoy!  Let me or Alex know if you have any questions!
