### ISSUE TITLE
winter-highlands

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#920]
# AVA: Winters Highlands (winter-highlands)

name | value
--- | ---
ava_id | winter-highlands
cfr_index | 9.290
revision | [T.D. TTB–189, [88 FR 59448](https://www.federalregister.gov/citation/88-FR-59448), Aug. 29, 2023]
state | CA
county |  *** Fill In ***
within | *** Fill In ***
contains | *** Fill In ***

[src]: https://www.ecfr.gov/current/title-27/chapter-I/subchapter-A/part-9/subpart-C
## Approved Maps [src]

The four United States Geological Survey (USGS) 1:24,000 scale topographic maps used to determine the boundary of the Winters Highlands viticultural area are: 

(1) Winters, CA, 2018; 

(2) Allendale, CA, 2018; 

(3) Mount Vaca, CA, 2018; and 

(4) Monticello Dam, CA, 2018.

## Boundary

Boundary.  The Winters Highlands viticultural area is located in portions of Solano and Yolo Counties, California. The boundary of the Winters Highlands viticultural area is as follows: 

(1) The boundary begins on the Winters map at the intersection of Putah Creek Road and Wintu Way. From the beginning point, proceed southeasterly along Wintu Way, crossing onto the Allendale map, to the terminus of Wintu Way; then 

(2) Proceed south-southwest in a straight line for 1.05 miles to the eastern terminus of Morse Lane; then 

(3) Proceed westerly along Morse Lane to its intersection with Olive School Lane; then 

(4) Proceed north-northwest in a straight line for 2.52 miles, crossing over the northeastern corner of the Mount Vaca map and onto the Monticello Dam map, to the line's intersection with Highway 128, approximately 2.78 miles west of the intersection of Highway 128 and County Road 89; then 

(5) Proceed north in a straight line to the intersection of the line with the Chickahominy Slough; then 

(6) Proceed east-southeast along the Chickahominy Slough, crossing onto the Winters map, to its intersection with the 170-foot elevation contour; then 

(7) Proceed south-southeasterly along the 170-foot elevation contour to its intersection with the Winters Canal; then 

(8) Proceed south along the Winters Canal to its intersection with the terminus of an unnamed local road; then 

(9) Proceed due west in a straight line to the 200-foot elevation contour; then 

(10) Proceed south in a straight line to the northern terminus of County Road 88; then 

(11) Proceed south along County Road 88 to its southern terminus and continue south in a straight line to Valley Oak Drive; then 

(12) Proceed southerly along Valley Oak Drive to its intersection with Highway 128; then 

(13) Proceed southeasterly in a straight line for 1.04 miles, returning to the beginning point.

**Comment by alisonsnwong** [comment]
https://github.com/UCDavisLibrary/ava/pull/922
