### ISSUE TITLE
Multiple errors in several files

### ISSUE THREAD

**Issue by kurtishouser** [UCDavisLibrary/ava#928]
I was reviewing the latest merged PRs and encountered a lot of errors with the basic properties (skipping boundaries and maps). I discovered some in Rocky Reach and Gabilan Mountains as well.

Error count:
- Rocky Reach (1)
- Gabilan Mountains (2)
- Long Valley-Lake County (4)
- High Valley (5)
- North Coast (6)
- Winter Highlands (4)

Trying to remember everything to check/change is quite the cognitive load so I'm not too surprised with all the errors, especially with the AVAs that have revised boundaries. It might be a good time to review the whole instruction/documentation/creation/updating/checking process and see what can be improved and perhaps even automated.

For example, opening the raw GeoJSON file on GitHub in a browser with a JSON formatting extension installed is helpful.

A lot of the errors involved the dates. Also, maybe there's some confusion with some of the documentation because I see the CFR publication date used in multiple places.

The first is on the Data page, the second on the Methods page.
created: YYYY-MM-DD format; the date of the first publication creating the AVA
created: the date the AVA officially began

I could submit PRs for all the fixes but I don't think that really solves the problem. So maybe somebody can start checking the above files one by on and see if they find the same errors as I do.

**Comment by MicheleTobias** [comment]
Thanks, Kurtis! I'll look into it. My team has been focused on other things and it looks like it's time to come back to this.

**Comment by MicheleTobias** [comment]
@kurtishouser can you give me some more detail about what you mean when you said "skipping boundaries and maps"? Did you mean that the person who digitized the boundary missed a step in the description?

**Comment by kurtishouser** [comment]
@MicheleTobias Oops! That is a little confusing. It means I didn't check the dataset text against the text in the CFR site/documents. Specifically, I skipped the `approved_maps`, `boundaries`, and `used_maps` properties.

**Comment by MicheleTobias** [comment]
Thanks! That makes more sense now!
