### ISSUE TITLE
inwood_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#94]
# AVA: Inwood Valley (inwood_valley)

name | value
--- | ---
ava_id | inwood_valley
cfr_index | 9.226
revision | [T.D. TTB-107, 77 FR 56544, Sept. 13, 2012]
state | CA
county | Shasta
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Clough Gulch, California—Shasta County, Provisional edition 1985; 
2. Inwood, California—Shasta County, Provisional edition 1985; 
3. Hagaman Gulch, California—Shasta County, Provisional edition 1985; 
4. Shingletown, California—Shasta County, Provisional edition 1985; and 
5. Tuscan Buttes NE., California, 1965, Photoinspected 1976.

## Boundary [src]

(1) The beginning point is on the Clough Gulch map at BM 
(Benchmark) 1254.4 located along State Route 44 in T31N/R2W. From the beginning point, proceed east-northeasterly in a straight line approximately 4.1 miles, onto the Inwood map, to the 1,786-foot elevation point, section 17, T31N/R1W; then 
(2) Proceed east-northeasterly in a straight line approximately 2.1 miles to the 2,086-foot elevation point, section 15, T31N/R1W; then 
(3) Proceed north-northeasterly in a straight line approximately 0.7 mile to the marked 1,648-foot elevation point 
(which should be marked as 2,648 feet based on its two adjacent elevation lines) on Bear Creek Ridge, section 10, T31N/R1W; then 
(4) Proceed east-northeasterly in a straight line approximately 0.8 mile to the 2,952-foot elevation point 
(located between two transmission lines), section 11, T31N/R1W; then 
(5) Proceed east-northeasterly in a straight line approximately 1.2 miles to the 3,042-foot summit of Blue Mountain, section 1, T31N/R1W; then 
(6) Proceed easterly in a straight line approximately 0.7 mile, crossing over the R1W/R1E “Mt. Diablo Meridian” line, to the 3,104-foot elevation point, section 6, T31N/R1E; then 
(7) Proceed east-northeasterly in a straight line approximately 2.2 miles to the summit of Alamine Peak, section 32, T32N/R1E; then 
(8) Proceed southeasterly in a straight line approximately 2.1 miles, onto the Hagaman Gulch map, to Bear Pen Springs, section 10, T31N/R1E; then 
(9) Proceed west-southwesterly in a straight line approximately 0.8 mile to the 3,373-foot summit of Chalk Mountain, section 9, T31N/R1E; then 
(10) Proceed south-southwesterly in a straight line approximately 1 mile, returning to the Inwood map, to 2,756-foot elevation point, section 17, T31N/R1E; then 
(11) Proceed south in a straight line approximately 0.6 mile to the intersection of that line with an improved road marked “Private” at the southern boundary of section 17, T31N/R1E; then 
(12) Proceed south-southwesterly along that “Private” road approximately 1.6 miles to the marked gate of the “Private” road at the road&#39;s intersection with unnamed improved and unimproved roads, section 29, T31N/R1E; then 
(13) Proceed southwesterly in a straight line approximately 1.6 miles, onto the Shingletown map, to the intersection of that line with State Route 44 and an unnamed improved road 
(known locally as Ash Creek Road), section 31, T31N/R1E; then 
(14) Proceed southwesterly in a straight line approximately 0.2 miles to the 3,334-foot elevation point, section 31, T31N/R1E; then 
(15) Proceed southwesterly in a straight line approximately 1.5 miles, crossing over the R1W/R1E “Mt. Diablo Meridian” line, to the 3,029-foot elevation point on Shingletown Ridge, section 1, T30N/R1W; then 
(16) Proceed westerly in a straight line approximately 1.6 miles to the 2,435-foot elevation point, section 3, T30N/R1W; then 
(17) Proceed west-southwesterly in a straight line approximately 1.7 miles to the 2,065-foot elevation point 
(southeast of a marked Borrow Pit), section 8, T30N/R1W; then 
(18) Proceed west-northwesterly in a straight line approximately 5.2 miles, onto the Tuscan Buttes NE map, to the 956-foot elevation point near an unnamed spring in section 33, T31N/R2W; then 
(19) Proceed north in a straight line approximately 1.7 miles, onto the Clough Gulch map, to BM 1048.1 on State Route 44, section 28, T31N/R2W; then 
(20) Proceed east along State Route 44 approximately 1.1 miles, returning to the beginning point.

**Comment by MicheleTobias** [comment]
I'm working on this one.

**Comment by SoominHur** [comment]
Reviewed.
