### ISSUE TITLE
isle_st__george

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#95]
# AVA: Isle St. George (isle_st__george)

name | value
--- | ---
ava_id | isle_st__george
cfr_index | 9.51
revision | [T.D. ATF-110, 47 FR 36421, Aug. 20, 1982]
state | OH
county | Ottawa
within | Lake Erie
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c

**Comment by ericallanwest** [comment]
Please label this one In Progress and Virginia Tech. Thanks!
