### ISSUE TITLE
Incorrect dates for Yakima Valley

### ISSUE THREAD

**Issue by kurtishouser** [UCDavisLibrary/ava#954]
One of the `created` dates is incorrect. One of `valid_start` dates is incorrect. This one appears to be an older error that was introduced a while back.

**Comment by MicheleTobias** [comment]
@kurtishouser it's helpful when you notify us that something is incorrect, but it's even more helpful if you can tell us what you think is the correct value. Even more helpful is to submit a PR with the correction (geoJSON is editable with a text editor or QGIS), but I understand that isn't always an option for everyone.

**Comment by MicheleTobias** [comment]
Because you use this data so heavily, I'm inviting you to contribute rather than telling us how to do things. We rely on contributors because if this is a community project and if you've already identified a fix, why not just share it?

**Comment by kurtishouser** [comment]
I'm not telling anybody how to do things.

I've identified an underlying problem to the QC process and have provided a solution that makes it easier to see the changes made to the GeoJson files and spot errors.

I've contributed plenty to this project.
