### ISSUE TITLE
kanawha_river_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#97]
# AVA: Kanawha River Valley (kanawha_river_valley)

name | value
--- | ---
ava_id | kanawha_river_valley
cfr_index | 9.111
revision | [T.D. ATF-226, 51 FR 11913, Apr. 8, 1986]
state | WV
county | Cabell|Jackson|Kanawha|Mason|Putnam
within | Ohio River Valley
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Addison, Ohio—W. Va., dated 1960; 
2. Gallipolis, Ohio—W. Va., dated 1958; 
3. Apple Grove, Ohio—W. Va., dated 1968, photorevised 1975; 
4. Glenwood, W. Va.—Ohio, dated 1968; 
5. Milton, W. Va., dated 1972; 
6. West Hamlin, W. Va., dated 1957; 
7. Hamlin, W. Va., dated 1958; 
8. Garrets Bend, W. Va., dated 1958; 
9. Scott Depot, W. Va., dated 1958; 
10. Saint Albans, W. Va., dated 1958; 
11. Pocatalico, W. Va., dated 1958; 
12. Sissonville, W. Va., dated 1958; 
13. Romance, W. Va.,—Ky., dated 1957; 
14. Kentuck, W. Va., dated 1957; 
15. Kenna, W. Va., dated 1957; 
16. Ripley, W. Va., dated 1960; 
17. Cottageville, W. Va., dated 1960; 
18. Mount Alto, W. Va.—Ohio, dated 1958, photorevised 1972; 
19. Beech Hill, W. Va.—Ohio, dated 1957, photorevised 1975; 
20. Cheshire, W. Va.—Ohio, dated 1968;

## Boundary [src]

(1) The beginning point is the West Virginia-Ohio State Line at the confluence of Champaign Creek and the Ohio River. 
(Addison quadrangle) 
(2) The boundary follows the West Virginia-Ohio State Line, in the Ohio River 
(across the Gallipolis and Apple Grove quadrangles) southwesterly to the point at which the Mason County-Cabell County Line intersects the State Line. 
(Glenwood quadrangle) 
(3) The boundary proceeds in a straight line southerly to the benchmark at 583 ft. elevation in the town of Yates Crossing in Cabell County, WV. 
(Milton quadrangle) 
(4) The boundary proceeds in a straight line southeasterly to the benchmark at 640 ft. elevation in the town of Balls Gap, in Lincoln County, WV. 
(West Hamlin quadrangle) 
(5) The boundary proceeds in a straight line easterly 
(across the Hamlin, Garrett Bend, and Scott Depot quadrangles) to the benchmark at 590 ft. elevation in the town of Institute in Kanawha County, WV. 
(Saint Albans quadrangle) 
(6) The boundary proceeds in a straight line northeasterly to the benchmark at 654 ft. elevation in the town of Pocatalico, in Kanawha County, WV. 
(Pocatalico quadrangle) 
(7) The boundary proceeds in a straight line northeasterly 
(across the Sissonville quadrangle) to the confluence of Johns Branch and Sugar Creek in the town of Romance, in Jackson County, WV. 
(Romance quadrangle) 
(8) The boundary proceeds in a straight line northwesterly 
(across the Kentuck quadrangle) to the confluence of Plum Orchard Run and Stonelick Creek in the town of Plum Orchard, in Jackson County, WV. 
(Kenna quadrangle) 
(9) The boundary proceeds in a straight line northwesterly 
(across the Ripley quadrangle) to the Baltimore and Ohio Railroad crossing of State Highway 87 in the town of Evans, in Jackson County, WV. 
(Cottageville quadrangle) 
(10) The boundary proceeds in a straight line northwesterly 
(across the Mount Alto quadrangle) to the benchmark at 674 ft. elevation in the town of Flatrock, in Mason County, WV. 
(Beech Hill quadrangle) 
(11) The boundary proceeds northwesterly in a straight line 
(across the Cheshire quadrangle) to the beginning point.

**Comment by davidkli** [comment]
I have checked this AVA and the boundary looks good. The attribute table was updated to follow the formatting.
