### ISSUE TITLE
kelsey_bench_lake_county

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#98]
# AVA: Kelsey Bench–Lake County (kelsey_bench_lake_county)

name | value
--- | ---
ava_id | kelsey_bench_lake_county
cfr_index | 9.233
revision | [T.D. TTB-118, 78 FR 60689, Oct. 2, 2013]
state | CA
county | Lake
within | Clear Lake\|North Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Kelseyville, CA, 1993; and 
2. Highland Springs, CA, 1993.

## Boundary [src]

(1) The beginning point is on the Kelseyville map within the town of Kelseyville at the intersection of Konocti Road and Main Street 
(not named on the map), section 14, T13N/R9W. From the beginning point, proceed east on Konocti Road approximately 0.9 mile to the road&#39;s 3-way intersection with an unnamed, unimproved road to the south, section 13, T13N/R9W; then 
(2) Proceed south on the unnamed, unimproved road approximately 0.35 mile to a fork in the road, and continue on the eastern branch of the fork approximately 0.4 mile to the point where the road intersects a straight line drawn westward from the marked 2,493-foot elevation point in section 19, T13N/R9W, to the intersection of the 1,600-foot elevation line and the eastern boundary of section 23, T13N/R9W 
(which is concurrent with Wilkerson Road); then 
(3) Proceed westerly along the straight line described in paragraph 
(c)
(2) approximately 0.3 mile to the line&#39;s western end at the intersection of the 1,600-foot elevation line and the eastern boundary of section 23, T13N/R9W; then 
(4) Proceed south along the eastern boundaries of sections 23 and 26, T13N/R9W, approximately 0.8 mile to the first intersection of the eastern boundary of section 26 and the 1,720-foot elevation line; then 
(5) Proceed southeasterly along the 1,720-foot elevation line to the line&#39;s intersection with State Highway 29/175, just west of BM 1758, section 25, T13N/R9W; then 
(6) Proceed west on State Highway 29/175 approximately 0.15 mile to the highway&#39;s intersection with an unnamed, unimproved road, section 25, T13N/R9W; then 
(7) Proceed southwest then west on the unnamed, unimproved road approximately 0.4 mile to the road&#39;s intersection with Cole Creek Road at Bottle Rock Road, section 25, T13N/R9W; then 
(8) Proceed west on Cole Creek Road approximately 0.65 mile to the road&#39;s intersection with an unnamed, light-duty road known locally as Live Oak Drive 
(at BM 1625), section 26, T13N/R9W; then 
(9) Proceed northwest on Live Oak Drive to the road&#39;s intersection with Gross Road 
(at BM 1423), section 26, T13N/R9W; then 
(10) Proceed south on Gross Road approximately 0.65 mile to the road&#39;s intersection with the 1,600-foot elevation line, section 26, T13N/R9W; then 
(11) Proceed southerly along the meandering 1,600-foot elevation line to the line&#39;s intersection with Sweetwater Creek section 10, T12N/R9W; then 
(12) Proceed due west in a straight line approximately 0.6 mile to the line&#39;s first intersection with the 1,600-foot elevation after crossing Kelsey Creek, section 10, T12N/R9W; then 
(13) Proceed westerly and then northerly along the meandering 1,600-foot elevation line to the line&#39;s intersection with Kelsey Creek Drive, section 4, T12N/R9W; then 
(14) Proceed west on Kelsey Creek Drive and then Adobe Creek Drive, crossing onto the Highland Springs map, and continue north-northwest on Adobe Creek Drive, a total distance of approximately 3.25 miles, to the marked 1,439-foot elevation point in section 29, T13N/R9W; then 
(15) Proceed west-southwest in a straight line that passes through the marked 1,559-foot elevation point in section 29, T13N/R9W, and continue in the same direction to the line&#39;s intersection with an unnamed, light-duty road known locally as East Highland Springs Road, a total distance of approximately 0.6 mile, section 30, T13N, R9W; then 
(16) Proceed north on East Highland Springs Road approximately 0.5 mile, to the road&#39;s intersection with an unnamed road in the northeast quadrant of section 30, T13N/R9W; then 
(17) Proceed northwest on the unnamed road to the road&#39;s end point, then continue due north-northwest in a straight line, a total distance of approximately 0.3 mile, to the line&#39;s intersection with the southern boundary of section 19, T13N/R9W; then 
(18) Proceed west along the southern boundary of section 19, T13N/R9W, approximately 0.5 mile to the section&#39;s southwest corner; then 
(19) Proceed north along the western boundary of section 19, T13N/R9W, approximately 0.3 mile to the section line&#39;s seventh intersection with the 1,600-foot elevation line; then 
(20) Proceed westerly, northwesterly, and then easterly along the meandering 1,600-foot elevation line to the line&#39;s second intersection with the northern boundary of section 19, T13N/R9W; then 
(21) Proceed east along the northern boundary of section 19, T13N/R9W, approximately 0.35 mile to the section boundary&#39;s intersection with an unnamed road known locally as Fritch Road; then 
(22) Proceed east on Fritch Road approximately 0.4 mile to the road&#39;s intersection with Highland Springs Road, section 18, T13N/R9W; then 
(23) Proceed south on Highland Springs Road approximately 0.8 mile to the road&#39;s intersection with Bell Hill Road, section 19, T13N/R9W; then 
(24) Proceed eastward on the meandering Bell Hill Road approximately 1.4 miles to the road&#39;s last intersection with the 1,400-foot elevation line in section 20, T13N/R9W; then 
(25) Proceed northeasterly along the 1,400-foot elevation line, crossing onto the Kelseyville map, to the line&#39;s first intersection with Bell Hill Road in the southeast quadrant of section 16, T13N/R9W; then 
(26) Proceed northeast and then east on Bell Hill Road approximately 0.15 mile to the road&#39;s intersection with Hill Creek, section 16, T13N/R9W; then 
(27) Proceed northerly 
(downstream) along Hill Creek approximately 0.9 mile to the creek&#39;s intersection with Merritt Road, section 16, T13N/R9W; then 
(28) Proceed east on Merritt Road approximately 0.1 mile to the road&#39;s intersection with the 1,400-foot elevation line, northern boundary of section 16, T13N/R9W; then 
(29) Proceed northerly along the 1,400-foot elevation line approximately 0.2 mile to State Highway 29/175, section 9, T13N/R9W, and then continue northerly and then southeasterly along the 1,400-foot elevation line approximately 0.5 mile to the line&#39;s intersection with Merritt Road, northern boundary of section 15, T13N/R9W; then 
(30) Proceed east on Merritt Road approximately 0.3 mile to the road&#39;s intersection with an unnamed road known locally as Big Valley Road 
(or North Main Street), northern boundary of section 15, T13N/R9W; then 
(31) Proceed south then east on Big Valley Road 
(North Main Street) approximately 0.35 mile to the road&#39;s intersection with Kelsey Creek, section 15, T13N/R9W; then 
(32) Proceed southerly 
(upstream) along Kelsey Creek approximately 0.5 mile to the creek&#39;s intersection with State Highway 29/175, section 14, T13N/R9W; then 
(33) Proceed southeast on State Highway 29/175 approximately 0.4 mile, crossing Live Oak Drive, to the highway&#39;s intersection with an unnamed road known locally as Main Street, section 14, T13N/R9W; then 
(34) Proceed north on Main Street approximately 0.3 mile, returning to the beginning point.

**Comment by MicheleTobias** [comment]
I'm working on this one so we can get Lake County done today!

**Comment by SoominHur** [comment]
Reviewed. Add scale information in used maps.
