### ISSUE TITLE
knights_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#99]
# AVA: Knights Valley (knights_valley)

name | value
--- | ---
ava_id | knights_valley
cfr_index | 9.76
revision | [T.D. ATF-158, 48 FR 48816, Oct. 21, 1983]
state | CA
county | Sonoma
within | North Coast\|Northern Sonoma
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Mount St. Helena Quadrangle, California,” 7.5 minute series, 1959 
Photoinspected 1973.; 
2. “Jimtown Quadrangle, California,” 7.5 minute series, 1955 
Photorevised 1975.; 
3. “Mark West Springs Quadrangle, California,” 7.5 minute series, 1958; and 
4. “Detert Reservoir Quadrangle, California,” 7.5 minute series, 1958 
Photorevised 1980..

## Boundary [src]

From the beginning point lying at the intersection of the Sonoma/Lake County line and the north line of Section 11, Township 10 North (T. 10 N.), Range 8 West (R. 8 W.) on the “Mount St. Helena Quadrangle” map, the boundary runs—
(1) Westerly along the north line of Sections 11, 10, and 9, T. 10 N., R. 8 W. to the northwest corner of Section 9 on the “Jimtown Quadrangle” map; 
(2) Then southerly along the west line of Sections 9, 16, 21, 28, and 33, T. 10 N., R. 8 W., continuing along the west line of Section 4, T. 9 N., R. 8 W. to the southwest corner thereof; 
(3) Then easterly along the south line of Section 4 to the southeast corner thereof on the “Mount St. Helena Quadrangle” map; 
(4) Then southerly along the west line of Sections 10, 15, and 22, T. 9 N., R. 8 W. to the point of intersection with Franz Creek in Section 22 on the “Mark West Springs Quadrangle” map; 
(5) Then easterly along Franz Creek approximately 14,000 feet to the centerline of Franz Valley Road; 
(6) Then southerly along the centerline of Franz Valley Road to the point of intersection with the west line of Section 6, T. 8 N., R. 7 W.; 
(7) Then southerly along the west line of Section 6 to the southwest corner thereof; 
(8) Then easterly along the south line of Sections 6, 5, and 4, T. 8 N., R. 7 W. to the southeast corner of Section 4; 
(9) Then northerly along the east line of Section 4 to the point of intersection with the Sonoma/Napa County line; 
(10) Then northerly along the meanders of the Sonoma/Napa County line on the “Mark West Springs Quadrangle,” “Detert Reservoir Quadrangle,” and “Mount St. Helena Quadrangle” maps to the point of intersection with the Lake County line on the “Mount St. Helena Quadrangle” map; 
(11) Then northerly along the meanders of the Sonoma/Lake County line on the “Mount St. Helena Quadrangle” and “Detert Reservoir Quadrangle” maps to the point of beginning.

**Comment by SoominHur** [comment]
Reviewed.
- Edit created date in the attribute table. 
- Referenced Google Maps; The line went toward the intersection between Pepperwood Preserve Rd and the west line of Section 6 (T8N, R7W). So corrected it to go toward the intersection between (6) "the centerline of Franz Valley Road ... [and] west line of Section 6 (T8N, R7W)."
